<script type="text/javascript">
$(document).ready(function(){
	$( ".select2" ).select2();
			// Validate form
			$("#add").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
				rules: {
				},
        submitHandler: function(form) {
                
          var formData = new FormData($("#add")[0]);
          
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/route/addroute", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: formData, // giá trị post
              cache: false,
              contentType: false,
              processData: false,
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error').hide();
                  $('#error').slideToggle(100); // hiển thị thẻ div success
                  $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error').fadeOut(10000);

              }
          });
          return false;
           
       }
					 
				 
			});
	
});
</script>
     
<div class="login_body">
  
      <form id="add" method="post" action="" autocomplete="off">
          <table style="margin-top:20px;">
            <tr>
                <td>Tên địa điểm </td>
                <td><input type="text" id="route_name" name="route_name" tabindex="1" autofocus required="required"></td>
                
            </tr>
            <tr>
                <td>Tỉnh/TP </td>
                <td>
                  <select class="form-control select2" id="route_province" name="route_province" required="required" tabindex="2">
                    <?php foreach ($provinces as $province) { ?>
                      <option value="<?php echo $province->province_id ?>"><?php echo $province->province_name ?></option>
                    <?php } ?>
                  </select>
                </td>
            </tr>
        </table> 
    </form>
</div>
<div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>


