
<?php
$url_order = 'ASC';
if ($order_by == 'route_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'route_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'province_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';


    $i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>
<section class="content-header">
    <h1>DANH SÁCH ĐỊA ĐIỂM</h1>
  <ol class="breadcrumb">
    <li><a href="<?php echo $this->url('admin') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><a href="<?php echo $this->url('route') ?>">Địa điểm</a></li>
  </ol>
</section>
<div id="content" style="padding:5px;">

    <div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" routeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
        <?php if(!isset($disable_control)){ ?>
        <div class="add-box"><a class="add_button" id="btnExport" ><i class="fa fa-download"></i> Xuất</a></div>
        <div class="add-box"><a class="add_button" onClick="add_click();"><i class="fa fa-plus"></i> Thêm mới</a></div>
        <?php } ?>
    </div>
    <div class="tablenav top">
        <?php if(!isset($disable_control)){ ?>
        <div class="alignleft actions">
            <select name="action" id="action">
                <option value="-1" selected="selected">Chọn</option>
                
                <option value="delete">Xóa</option>
            </select>
            <input type="button" name="" id="doaction" class="button action" value="Áp dụng" onclick="action();">
        </div>
        <?php } ?>
        <div class="alignleft actions">
        <select name="m" id="chonloc">
          <option  value="18446744073709">Hiển thị tất cả</option>
          <option value="50">Hiển thị 50 giá trị</option>
                <option value="100">Hiển thị 100 giá trị</option>
                <option value="150">Hiển thị 150 giá trị</option>
                <option selected="selected" value="200">Hiển thị 200 giá trị</option>
        </select>
        <input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">                               
        </div>

      </div>

</div>


<table class="table_data" id="tblExport">
<thead>
    <tr>
        <th class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','route_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'route_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','route_name','<?php echo $url_order ?>')">Tên địa điểm <?php if ($order_by == 'route_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','province_name','<?php echo $url_order ?>')">Tên tỉnh/TP <?php if ($order_by == 'province_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
           
        <?php if(!isset($disable_control)){ ?>
           
        <th  class="fix">&nbsp;</th>
        <?php } ?>
    </tr>
    
   </thead>
   <tbody>
    <?php foreach ($routes as $route) : ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $route->route_id ?>" class="edit_tr">
            <td><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $route->route_id ?>"></td>
            <td class="fix"><?php echo $i++; ?></td>
            <td class="fix"  id="route_name_<?php echo $route->route_id; ?>"><?php echo $route->route_name ?></td>
            <td class="fix" data="<?php echo $route->province; ?>" id="province_name_<?php echo $route->route_id; ?>"><?php echo $route->province_name ?></td>
        
            <?php if(!isset($disable_control)){ ?>
            <td class="pull-right">
                <button class="btn btn-sm btn-flat btn-primary"><i class="fa fa-edit"></i> Sửa</button>
                <button class="btn btn-sm btn-flat btn-danger" onclick="del(<?php echo $route->route_id ?>)" ><i class="fa fa-remove"></i> Xóa</button>
            </td>
            <?php } ?>
        </tr>
    <?php endforeach; ?>
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>
<div class="add-field">
    <section class="content">
      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
            <!-- /.box-header -->
            <!-- form start -->
            <form id="add_route" role="form" method="post" action="" enctype="multipart/form-data">
              <div class="row">
                <div class="col-md-6 col-xs-6">
                  <div class="box-body">
                    <div class="form-group">
                      <label for="route_name">Tên địa điểm</label>
                      <input type="text" id="route_name"  name="route_name" tabindex="1" required="required" >
                    </div>
                    
                    
                  </div>
                  <!-- /.box-body -->
                  
                </div>
                <div class="col-md-6 col-xs-6">
                  <div class="box-body">
                    <div class="form-group">
                      <label for="province">Tên tỉnh/TP</label>
                      <select id="province" name="province" tabindex="2" required="required">
                        <?php foreach ($provinces as $province) {
                            echo '<option value="'.$province->province_id.'">'.$province->province_name.'</option>';
                        }
                        ?>
                    </select>
                    </div>
                    
                    
                  </div>
                  <!-- /.box-body -->
                </div>

              </div>
              <?php if(!isset($disable_control)){ ?>
              <div class="row">
                <div class="col-md-12">
                    <div class="box-footer">
                    <input type="hidden" readonly id="yes" name="yes" required="required" >
                    <button type="submit" class="btn btn-primary" tabindex="3">Hoàn thành</button>
                    <button type="reset" class="btn" tabindex="4">Nhập lại</button>
                  </div>
                  <div class="box-footer">
                    <div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>
                  </div>
                </div>
              </div>
              <?php } ?>
            </form>
          </div>
          <!-- /.box -->

        </div>
        <!--/.col (left) -->
        
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
       
</div>


<script type="text/javascript">

    $('.edit_tr').click(function(e){
            if(!$('.checkbox').is(':focus')){
                $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);
            }
            var route_name = $(this).find("#route_name_"+$(this).attr('id')).text();
            var province = $(this).find("#province_name_"+$(this).attr('id')).attr('data');
            
            //alert(route_code);
            $('#yes').val($(this).attr('id'));
            
            $('#province option[value='+province+']').attr('selected','selected');
            $('#route_name').val(route_name);
            $( ".add-field" ).dialog( "open" );
        
    });
</script>
<script type="text/javascript">

function add_click(){
    $('#yes').val("");
    $('.add-field').slideDown(500);
     $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);   
        $('#route_name').val("");
        
        
        $('.number').focus(function(){
            if ( $(this).val() == '0') {
               $(this).val(""); 
            };
            
        });
        $('.number').blur(function(){
            if ( $(this).val() == "") {
                $(this).val(0);
            };
            
        });


   $( ".add-field" ).dialog( "open" );

}


$(document).ready(function(){
            // Validate form
            $("#add_route").validate({
                errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
                rules: {
                    
                },
                submitHandler: function(form) {
                
                    var route_name = $('#route_name').attr('value');
                    var province = $('#province').attr('value');
                    
                    var yes = $('#yes').attr('value');
                    
                    var action      = "them";
                 
                    $.ajax({
                        type: "POST", // phương thức gởi đi
                        url: "<?php echo BASE_URL ?>/route/add", // nơi mà dữ liệu sẽ chuyển đến khi submit
                        data: {
                            route_name: route_name,
                            province: province,
                            yes: yes,
                            }, // giá trị post
                        success: function(answer){ // if everything goes well
                            //alert(answer);
                            $('#error').hide();
                            $('#error').slideToggle(100); // hiển thị thẻ div success
                            $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                            $('#error').fadeOut(10000);

                            if (yes != "") {
                                if (answer.trim() != "Tên đã được sử dụng" ) {
                                  setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);
                                    $('#route_name_'+yes).text(route_name);
                                    $('#province_name_'+yes).text($('#province option:selected').text());
                                }
                            }
                            else{
                                if (answer.trim() != "Tên đã được sử dụng") {
                                  setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);
                                    var lastID = parseInt($('#lasted').html());
                                    var rowCount = parseInt($('.table_data > tbody > tr').length);
                                    $('.table_data > tbody:last')
                                    .append(
                                        '<tr onclick="HighLightTR(this,#4d90fe,cc3333);" id="'+parseInt(lastID+1)+'" class="edit_tr"><td><input name="check[]" type="checkbox" class="checkbox" value="'+parseInt(lastID+1)+'"></td><td class="fix">'+parseInt(rowCount+1)+'</td><td class="fix" id="route_name_'+parseInt(lastID+1)+'">'+route_name+'</td><td class="fix" data="'+province+'" id="province_name_'+parseInt(lastID+1)+'">'+$('#province option:selected').text()+'</td><td><a class="error" href="#">Sửa</a> | <a class="error" onclick="del('+parseInt(lastID+1)+')">Xóa</a></td></tr>'
                                    );

                                    $('#lasted').html(parseInt(lastID+2));
                                }
                            }
                        }
                    });
                    return false;
                     
                 }
            });
   
   
   
    $('.number').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .reroute(/[^0-9]/g, "")
        ;
      });
    });
   
   $('.numbers').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .reroute(/[^0-9]/g, "")
          .reroute(/(\d{3})(\d{3})(\d{4})/, "$1 $2 $3")
        ;
      });
    });
    

});
function get_number(id){
    return $(id).val().reroute(/\,/g,'');
}

</script>
<div style="display:none" id="lasted"></div>
<script type="text/javascript">
    var count = parseInt(<?php echo $lastID ?>);
    $('#lasted').html(count);

$("#import_excel").click(function(){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:300,
            width:400,
            resizable: false,
            title:'Import Excel',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        return false;
    });
</script>
</div>

<script type="text/javascript">
var l = "<?php echo $limit ?>";
$('#chonloc option[value='+l+']').attr('selected','selected');

$( ".add-field" ).dialog({
    autoOpen: false,
    modal: true,
    width: "auto",
    title: "Thông tin địa điểm",
    hide: 'fold',
    show: 'blind'
});

</script>