<script type="text/javascript">
$(document).ready(function(){
	$( ".select2" ).select2({dropdownAutoWidth : true});
			// Validate form
			$("#add_coordinate").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
        ignore: "",
        rules: {
        },
        errorPlacement: function (error, element) {
          if(element.is('input[type=checkbox]') || element.is('input[type=radio]')) {
            var controls = element.closest('div[class*="col-"]');
            if(controls.find(':checkbox,:radio').length > 1) controls.append(error);
            else error.insertAfter(element.nextAll('.lbl:eq(0)').eq(0));
          }
          else if(element.is('.select2')) {
            error.insertAfter(element.siblings('[class*="select2-container"]:eq(0)'));
          }
          else if(element.is('.chosen-select')) {
            error.insertAfter(element.siblings('[class*="chosen-container"]:eq(0)'));
          }
          else error.insertAfter(element.parent());
        },
        submitHandler: function(form) {
          var coordinate_data = [];    

          var coordinate_booking_number = [];  
          var coordinate_booking = []; 
          var coordinate_vehicle = [];
          var coordinate_place = [];
          var coordinate_type = [];
          var coordinate_number = [];
          var coordinate_comment = [];
          var coordinate_unit = [];
          var id_coordinate = [];

          $('.coordinate_booking').each(function() { 
              coordinate_booking_number.push($(this).val());
              coordinate_booking.push($(this).attr('data') || "");
              
          });
          $('.coordinate_vehicle').each(function() { 
              coordinate_vehicle.push($(this).val());
          });
          $('.coordinate_place').each(function() { 
              coordinate_place.push($(this).val());
          });
          $('.coordinate_type').each(function() { 
              coordinate_type.push($(this).val());
          });
          $('.coordinate_unit').each(function() { 
              coordinate_unit.push($(this).val());
          });
          $('.coordinate_number').each(function() { 
              coordinate_number.push($(this).val());
              id_coordinate.push($(this).attr('data') || "");
          });
          $('.coordinate_comment').each(function() { 
              coordinate_comment.push($(this).val());
          });

          for (var i = 0; i < coordinate_number.length; i++) {
              coordinate_data.push({'coordinate_booking_number':coordinate_booking_number[i], 'coordinate_booking':coordinate_booking[i], 'coordinate_vehicle':coordinate_vehicle[i], 'coordinate_place':coordinate_place[i], 'coordinate_type':coordinate_type[i], 'coordinate_unit':coordinate_unit[i], 'coordinate_number':coordinate_number[i], 'coordinate_comment':coordinate_comment[i]});
          };

          var formData = new FormData($("#add_coordinate")[0]);
          formData.append('coordinate_data', JSON.stringify(coordinate_data));
          
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/coordinate/addcoordinate", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: formData, // giá trị post
              cache: false,
              contentType: false,
              processData: false,
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error_coordinate').hide();
                  $('#error_coordinate').slideToggle(100); // hiển thị thẻ div success
                  $('#error_coordinate').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error_coordinate').fadeOut(10000);

              }
          });
          return false;
           
       }
					 
				 
			});

});

</script>

<div id="error_coordinate" class="error"><?php echo isset($error) ? $error : null; ?></div>     
<div class="tabbable">
  <form id="add_coordinate" method="post" action="" autocomplete="off">
    <div class="col-md-2 col-xs-6">
      <label for="coordinate_date">Ngày </label>
      <div class="input-group">
        <input class="form-control input-mask-date" type="text" id="coordinate_date" name="coordinate_date" tabindex="1" required="required" value="<?php echo date('d/m/Y') ?>">
      </div>
    </div>
    <div class="col-md-2 col-xs-6">
      <label for="coordinate_code">Số lệnh </label>
      <div class="input-group">
        <input class="form-control" type="text" id="coordinate_code" name="coordinate_code" tabindex="2" value="<?php echo $lastID ?>" >
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="hr hr-8 dotted hr-double"></div>
    <div class="col-xs-12">
      <table id="dataTable_coordinate" style="width: 100%;">
          <tbody>
          <tr>
              <td style="padding-right: 10px;"><input type="checkbox" name="chk"></td>
              <td>
                  <table style="width:100%;">
                      <tbody>
                        <tr>
                          <td>
                            <label>BK/BL</label>
                            <div class="input-group">
                              <input type="text" class="coordinate_booking" name="coordinate_booking[]" tabindex="3">
                              <ul class="name_list_id"></ul>
                            </div>
                          </td>
                          <td>
                            <label>Xe lấy <a title="Thêm xe mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("vehicle/add") ?>','Thêm xe mới','.coordinate_vehicle','<?php echo $this->url("vehicle/getvehicle") ?>','add_vehicle')"></i></a></label>
                            <div class="input-group">
                              <select class="form-control coordinate_vehicle select2" name="coordinate_vehicle[]" tabindex="4" required="required">
                                <?php foreach ($vehicles as $vehicle) { ?>
                                  <option value="<?php echo $vehicle->vehicle_id ?>" ><?php echo $vehicle->vehicle_number ?></option>
                                <?php } ?>
                              </select>
                            </div>
                          </td>
                          
                          <td>
                            <label>Nơi lấy <a title="Thêm địa điểm mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("place/add") ?>','Thêm địa điểm mới','.coordinate_place','<?php echo $this->url("place/getplace") ?>','add_place')"></i></a></label>
                            <div class="input-group">
                              <select class="form-control coordinate_place select2" name="coordinate_place[]" tabindex="5" required="required">
                                <?php foreach ($places as $place) { ?>
                                  <option value="<?php echo $place->place_id ?>" ><?php echo $place->place_name ?></option>
                                <?php } ?>
                              </select>
                            </div>
                          </td>
                          
                          <td>
                            <label>Loại hàng</label>
                            <div class="input-group">
                              <select class="form-control coordinate_type" name="coordinate_type[]" tabindex="6">
                                <option value="1">Hàng nhập</option>
                                <option value="2">Hàng xuất</option>
                                <option value="3">Khác</option>
                              </select>
                            </div>
                          </td>
                          <td>
                            <label>ĐVT <a title="Thêm đơn vị tính mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("unit/add") ?>','Thêm đơn vị tính mới','.coordinate_unit','<?php echo $this->url("unit/getunit") ?>','add_unit')"></i></a></label>
                            <div class="input-group">
                              <select class="form-control coordinate_unit" name="coordinate_unit[]" tabindex="7">
                                <?php foreach ($units as $unit) { ?>
                                  <option value="<?php echo $unit->unit_id ?>" ><?php echo $unit->unit_name ?></option>
                                <?php } ?>
                              </select>
                            </div>
                          </td>
                          <td>
                            <label>Sản lượng</label>
                            <div class="input-group">
                              <input type="text" class="coordinate_number numbers" name="coordinate_number[]" tabindex="8" required="required">
                            </div>
                          </td>
                          <td>
                            <label>Ghi chú</label>
                            <div class="input-group">
                              <input type="text" class="coordinate_comment" name="coordinate_comment[]" tabindex="9">
                            </div>
                          </td>
                        </tr>
                        
                  </tbody></table>
                  <div class="hr hr-8 dotted hr-double"></div>
              </td>
              
          </tr>
      </tbody>
      </table>
  
      <input type="button" value="Thêm" onclick="addRow_coordinate('dataTable_coordinate')">

      <input type="button" value="Xóa" onclick="deleteRow_coordinate('dataTable_coordinate')">
  </div>
  </form>
</div>



<script type="text/javascript">
get_booking();

$('html').click(function(e) {
    $('.name_list_id').slideUp(200);
});

function get_booking(){
  $('.coordinate_booking').keyup(function(){
    var row = $(this).parent().parent().parent().parent().parent().parent().parent();
    var rowIndex = row[0].rowIndex;

    var keyword = $(this).val();
    $.ajax({
        url: '<?php echo BASE_URL ?>/coordinate/getBooking',
        type: 'GET',
        data: {keyword:keyword, offset:rowIndex},
        success:function(data){
            $('.name_list_id:eq('+rowIndex+')').slideDown(200);
            $('.name_list_id:eq('+rowIndex+')').html(data);
        }
    });
    if ($('.coordinate_booking:eq('+rowIndex+')').val() == "" || $('.coordinate_booking:eq('+rowIndex+')').attr('data') == "") {
        
        $('.coordinate_booking:eq('+rowIndex+')').attr('data',"");
    }

    
  });

  $('.coordinate_booking').on('keydown', function() {
    var row = $(this).parent().parent().parent().parent().parent().parent().parent();
    var rowIndex = row[0].rowIndex;

    var key = event.keyCode || event.charCode;

    if( key == 8 || key == 46 ){
        $('.coordinate_booking:eq('+rowIndex+')').attr('data',"");
    }
        
  }); 
}
function set_item(item,value,type,vitri) {
    // change input value
    $('.coordinate_booking:eq('+vitri+')').val(value);
    $('.coordinate_booking:eq('+vitri+')').attr("data",item);
    $('.coordinate_type:eq('+vitri+')').val(type).change();
    // hide proposition list
    $('.name_list_id').hide();
    $('.coordinate_booking:eq('+vitri+')').focus();

}

function addRow_coordinate(tableID){
    var table=document.getElementById(tableID);
    var rowCount=table.rows.length;
    var row=table.insertRow(rowCount);
    var colCount=table.rows[0].cells.length;
    for(var i=0;i<colCount;i++){
        var newcell=row.insertCell(i);
        newcell.innerHTML=table.rows[0].cells[i].innerHTML;
        switch(newcell.childNodes[0].type){
            case"text":newcell.childNodes[0].value="";
            break;
            case"checkbox":newcell.childNodes[0].checked=false;
            break;
            case"select-one":newcell.childNodes[0].selectedIndex=0;
            break;
        }
    }

    $('.coordinate_booking:last').val("");
    $('.coordinate_booking:last').attr('data',"");
    $('.coordinate_number:last').val("");
    $('.coordinate_comment:last').val("");

    $('input[name="chk"]:last').attr('data',"");
    $('input[name="chk"]:last').attr('title',"");

    //
    var style = $('.coordinate_vehicle').last().next().attr('style');
    $('.coordinate_vehicle').last().next().remove();
    $('.coordinate_vehicle').select2();
    $('.coordinate_vehicle').last().next().attr('style',style);

    //
    var style = $('.coordinate_place').last().next().attr('style');
    $('.coordinate_place').last().next().remove();
    $('.coordinate_place').select2();
    $('.coordinate_place').last().next().attr('style',style);

    get_booking();
}
function deleteRow_coordinate(tableID){
    try{
        var table=document.getElementById(tableID);
        var rowCount=table.rows.length;

        bootbox.confirm("Bạn có chắc chắn muốn xóa không?", function(result) {
          if(result) {
            for(var i=0;i<rowCount;i++){
                var row=table.rows[i];
                var chkbox=row.cells[0].childNodes[0];
                if(null!=chkbox&&true==chkbox.checked){
                  if(rowCount<=1){
                        alert_form("Không thể xóa hết.");
                        break;
                    }
                    else if(chkbox.getAttribute("title") > 0){
                        
                            var data = chkbox.getAttribute("data");
                            var coordinate = chkbox.getAttribute("title");

                            $.post("<?php echo BASE_URL ?>/coordinate/deletecoordinatedetail", {data: data, coordinate: coordinate},
                               function(data){
                                
                               }); 
                        
                    }
                    
                    table.deleteRow(i);
                    rowCount--;
                    i--;

                }
            }
          }
        });
    }
    catch(e){
        alert(e);
    }
}
</script>