<script type="text/javascript">
$(document).ready(function(){
  $( ".select2" ).select2({dropdownAutoWidth : true});
      // Validate form
      $("#edit_coordinate").validate({
        errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
        ignore: "",
        rules: {
        },
        errorPlacement: function (error, element) {
          if(element.is('input[type=checkbox]') || element.is('input[type=radio]')) {
            var controls = element.closest('div[class*="col-"]');
            if(controls.find(':checkbox,:radio').length > 1) controls.append(error);
            else error.insertAfter(element.nextAll('.lbl:eq(0)').eq(0));
          }
          else if(element.is('.select2')) {
            error.insertAfter(element.siblings('[class*="select2-container"]:eq(0)'));
          }
          else if(element.is('.chosen-select')) {
            error.insertAfter(element.siblings('[class*="chosen-container"]:eq(0)'));
          }
          else error.insertAfter(element.parent());
        },
        submitHandler: function(form) {
          var coordinate_booking = $('#coordinate_booking_number').attr('data');

          var formData = new FormData($("#edit_coordinate")[0]);
          formData.append('coordinate_id', '<?php echo $coordinate_data->coordinate_id ?>');
          formData.append('coordinate_booking', JSON.stringify(coordinate_booking));
          
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/coordinate/editcoordinate", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: formData, // giá trị post
              cache: false,
              contentType: false,
              processData: false,
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error_coordinate').hide();
                  $('#error_coordinate').slideToggle(100); // hiển thị thẻ div success
                  $('#error_coordinate').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error_coordinate').fadeOut(10000);

              }
          });
          return false;
           
       }
           
         
      });

    
  
});


</script>

<div id="error_coordinate" class="error"><?php echo isset($error) ? $error : null; ?></div>     
<div class="tabbable">
  <form id="edit_coordinate" method="post" action="" autocomplete="off">
    <div class="col-md-4 col-xs-6">
        <label for="coordinate_date">Ngày</label>
        <div class="input-group">
          <input class="form-control input-mask-date" type="text" id="coordinate_date" name="coordinate_date" tabindex="1" required="required" value="<?php echo $lib->hien_thi_ngay_thang($coordinate_data->coordinate_date) ?>">
        </div>
        <label for="coordinate_code">Số lệnh</label>
        <div class="input-group">
          <input class="form-control" type="text" id="coordinate_code" name="coordinate_code" tabindex="2" value="<?php echo $coordinate_data->coordinate_code ?>">
        </div>
        <label for="coordinate_vehicle">Xe lấy <a title="Thêm xe mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("vehicle/add") ?>','Thêm xe mới','coordinate_vehicle','<?php echo $this->url("vehicle/getvehicle") ?>','add_vehicle')"></i></a></label>
        <div class="input-group">
          <select class="form-control select2" id="coordinate_vehicle" name="coordinate_vehicle" required="required" tabindex="3">
            <?php foreach ($vehicles as $vehicle) { ?>
              <option value="<?php echo $vehicle->vehicle_id ?>" <?php echo $coordinate_data->coordinate_vehicle==$vehicle->vehicle_id?'selected="selected"':null ?>><?php echo $vehicle->vehicle_number ?></option>
            <?php } ?>
          </select>
        </div>
        
        
     </div>
     <div class="col-md-4 col-xs-6">
        <label for="coordinate_booking">BK/BL</label>
        <div class="input-group">
          <input type="text" class="coordinate_booking" id="coordinate_booking_number" name="coordinate_booking_number" tabindex="4" value="<?php echo $coordinate_data->coordinate_booking_number ?>" data="<?php echo $coordinate_data->coordinate_booking ?>">
          <ul class="name_list_id"></ul>
        </div>
        <label for="coordinate_type">Loại hàng</label>
        <div class="input-group">
          <select class="form-control" id="coordinate_type" name="coordinate_type" required="required" tabindex="5">
            <option value="1" <?php echo $coordinate_data->coordinate_type==1?'selected="selected"':null ?>>Hàng nhập</option>
            <option value="2" <?php echo $coordinate_data->coordinate_type==2?'selected="selected"':null ?>>Hàng xuất</option>
            <option value="3" <?php echo $coordinate_data->coordinate_type==3?'selected="selected"':null ?>>Khác</option>
          </select>
        </div>
        <label for="coordinate_place">Nơi lấy <a title="Thêm kho hàng mới" ><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("place/add") ?>','Thêm kho hàng mới','coordinate_place','<?php echo $this->url("place/getplace") ?>','add_place')"></i> </a></label>
        <div class="input-group">
          <select class="form-control select2 coordinate_place" id="coordinate_place" name="coordinate_place" required="required" tabindex="6">
            <?php foreach ($places as $place) { ?>
              <option value="<?php echo $place->place_id ?>" <?php echo $coordinate_data->coordinate_place==$place->place_id?'selected="selected"':null ?>><?php echo $place->place_name ?></option>
            <?php } ?>
          </select>
        </div>
        
     </div>
     <div class="col-md-4 col-xs-6">
      <label for="coordinate_number">Sản lượng</label>
        <div class="input-group">
          <input class="form-control numbers" type="text" id="coordinate_number" name="coordinate_number" tabindex="7" value="<?php echo $lib->formatMoney($coordinate_data->coordinate_number,2) ?>">
        </div>
        <label for="coordinate_unit">ĐVT <a title="Thêm đơn vị tính mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("unit/add") ?>','Thêm đơn vị tính mới','.coordinate_unit','<?php echo $this->url("unit/getunit") ?>','add_unit')"></i></a></label>
        <div class="input-group">
          <select class="form-control" id="coordinate_unit" name="coordinate_unit" tabindex="8">
            <?php foreach ($units as $unit) { ?>
              <option value="<?php echo $unit->unit_id ?>" <?php echo $coordinate_data->coordinate_unit==$unit->unit_id?'selected="selected"':null ?>><?php echo $unit->unit_name ?></option>
            <?php } ?>
          </select>
        </div>
        <label for="coordinate_comment">Ghi chú</label>
        <div class="input-group">
          <input class="form-control" type="text" id="coordinate_comment" name="coordinate_comment" tabindex="9" value="<?php echo $coordinate_data->coordinate_comment ?>">
        </div>
     </div>
  </form>
</div>



<script type="text/javascript">
get_booking();

$('html').click(function(e) {
    $('.name_list_id').slideUp(200);
});

function get_booking(){
  $('.coordinate_booking').keyup(function(){
    
    var rowIndex = 0;

    var keyword = $(this).val();
    $.ajax({
        url: '<?php echo BASE_URL ?>/coordinate/getBooking',
        type: 'GET',
        data: {keyword:keyword, offset:rowIndex},
        success:function(data){
            $('.name_list_id:eq('+rowIndex+')').slideDown(200);
            $('.name_list_id:eq('+rowIndex+')').html(data);
        }
    });
    if ($('.coordinate_booking:eq('+rowIndex+')').val() == "" || $('.coordinate_booking:eq('+rowIndex+')').attr('data') == "") {
        
        $('.coordinate_booking:eq('+rowIndex+')').attr('data',"");
    }

    
  });

  $('.coordinate_booking').on('keydown', function() {
    var row = $(this).parent().parent().parent().parent().parent().parent().parent();
    var rowIndex = row[0].rowIndex;

    var key = event.keyCode || event.charCode;

    if( key == 8 || key == 46 ){
        $('.coordinate_booking:eq('+rowIndex+')').attr('data',"");
    }
        
  }); 
}
function set_item(item,value,type,vitri) {
    // change input value
    $('.coordinate_booking:eq('+vitri+')').val(value);
    $('.coordinate_booking:eq('+vitri+')').attr("data",item);
    $('.coordinate_type:eq('+vitri+')').val(type).change();
    // hide proposition list
    $('.name_list_id').hide();
    $('.coordinate_booking:eq('+vitri+')').focus();

}
</script>