  
<div class="tabbable">
  
    <div class="col-md-4 col-xs-6">
        <label for="coordinate_date">Ngày</label>
        <div class="input-group">
          <input class="form-control input-mask-date" type="text" id="coordinate_date" name="coordinate_date" tabindex="1" required="required" value="<?php echo $lib->hien_thi_ngay_thang($coordinate_data->coordinate_date) ?>">
        </div>
        <label for="coordinate_code">Số lệnh</label>
        <div class="input-group">
          <input class="form-control" type="text" id="coordinate_code" name="coordinate_code" tabindex="2" value="<?php echo $coordinate_data->coordinate_code ?>">
        </div>
        <label for="coordinate_vehicle">Xe lấy <a title="Thêm xe mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("vehicle/add") ?>','Thêm xe mới','coordinate_vehicle','<?php echo $this->url("vehicle/getvehicle") ?>','add_vehicle')"></i></a></label>
        <div class="input-group">
          <select class="form-control select2" id="coordinate_vehicle" name="coordinate_vehicle" required="required" tabindex="3">
            <?php foreach ($vehicles as $vehicle) { ?>
              <option value="<?php echo $vehicle->vehicle_id ?>" <?php echo $coordinate_data->coordinate_vehicle==$vehicle->vehicle_id?'selected="selected"':null ?>><?php echo $vehicle->vehicle_number ?></option>
            <?php } ?>
          </select>
        </div>
        
        
     </div>
     <div class="col-md-4 col-xs-6">
        <label for="coordinate_booking">BK/BL</label>
        <div class="input-group">
          <input type="text" class="coordinate_booking" id="coordinate_booking_number" name="coordinate_booking_number" tabindex="4" value="<?php echo $coordinate_data->coordinate_booking_number ?>" data="<?php echo $coordinate_data->coordinate_booking ?>">
          <ul class="name_list_id"></ul>
        </div>
        <label for="coordinate_type">Loại hàng</label>
        <div class="input-group">
          <select class="form-control" id="coordinate_type" name="coordinate_type" required="required" tabindex="5">
            <option value="1" <?php echo $coordinate_data->coordinate_type==1?'selected="selected"':null ?>>Hàng nhập</option>
            <option value="2" <?php echo $coordinate_data->coordinate_type==2?'selected="selected"':null ?>>Hàng xuất</option>
            <option value="3" <?php echo $coordinate_data->coordinate_type==3?'selected="selected"':null ?>>Khác</option>
          </select>
        </div>
        <label for="coordinate_place">Nơi lấy <a title="Thêm kho hàng mới" ><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("place/add") ?>','Thêm kho hàng mới','coordinate_place','<?php echo $this->url("place/getplace") ?>','add_place')"></i> </a></label>
        <div class="input-group">
          <select class="form-control select2 coordinate_place" id="coordinate_place" name="coordinate_place" required="required" tabindex="6">
            <?php foreach ($places as $place) { ?>
              <option value="<?php echo $place->place_id ?>" <?php echo $coordinate_data->coordinate_place==$place->place_id?'selected="selected"':null ?>><?php echo $place->place_name ?></option>
            <?php } ?>
          </select>
        </div>
        
     </div>
     <div class="col-md-4 col-xs-6">
      <label for="coordinate_number">Sản lượng</label>
        <div class="input-group">
          <input class="form-control numbers" type="text" id="coordinate_number" name="coordinate_number" tabindex="7" value="<?php echo $lib->formatMoney($coordinate_data->coordinate_number,2) ?>">
        </div>
        <label for="coordinate_unit">ĐVT <a title="Thêm đơn vị tính mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("unit/add") ?>','Thêm đơn vị tính mới','.coordinate_unit','<?php echo $this->url("unit/getunit") ?>','add_unit')"></i></a></label>
        <div class="input-group">
          <select class="form-control" id="coordinate_unit" name="coordinate_unit" tabindex="8">
            <?php foreach ($units as $unit) { ?>
              <option value="<?php echo $unit->unit_id ?>" <?php echo $coordinate_data->coordinate_unit==$unit->unit_id?'selected="selected"':null ?>><?php echo $unit->unit_name ?></option>
            <?php } ?>
          </select>
        </div>
        <label for="coordinate_comment">Ghi chú</label>
        <div class="input-group">
          <input class="form-control" type="text" id="coordinate_comment" name="coordinate_comment" tabindex="9" value="<?php echo $coordinate_data->coordinate_comment ?>">
        </div>
     </div>
  
</div>

