<script type="text/javascript">
$(document).ready(function(){
	
			// Validate form
			$("#add_house").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
				rules: {
				},
        submitHandler: function(form) {
                
          var formData = new FormData($("#add_house")[0]);
          
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/house/addhouse", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: formData, // giá trị post
              cache: false,
              contentType: false,
              processData: false,
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error_house').hide();
                  $('#error_house').slideToggle(100); // hiển thị thẻ div success
                  $('#error_house').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error_house').fadeOut(10000);

              }
          });
          return false;
           
       }
					 
				 
			});
	
});
</script>
     
<div class="login_body">
  
      <form id="add_house" method="post" action="" autocomplete="off">
          <table style="margin-top:20px;">
            <tr>
                <td>Mã kho vật tư </td>
                <td><input type="text" id="house_code" name="house_code" tabindex="1" autofocus required="required"></td>
                
            </tr>
            <tr>
                <td>Tên kho vật tư </td>
                <td><input type="text" id="house_name" name="house_name" tabindex="2" required="required"></td>
            </tr>
        </table> 
    </form>
</div>
<div id="error_house" class="error"><?php echo isset($error) ? $error : null; ?></div>


