<script type="text/javascript">
$(document).ready(function(){
	$( ".select2" ).select2({dropdownAutoWidth : true});
			// Validate form
			$("#add_vehicleromooc").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
				rules: {
				},
        submitHandler: function(form) {
                
          var formData = new FormData($("#add_vehicleromooc")[0]);
          
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/vehicleromooc/addvehicleromooc", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: formData, // giá trị post
              cache: false,
              contentType: false,
              processData: false,
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error_vehicleromooc').hide();
                  $('#error_vehicleromooc').slideToggle(100); // hiển thị thẻ div success
                  $('#error_vehicleromooc').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error_vehicleromooc').fadeOut(10000);

              }
          });
          return false;
           
       }
					 
				 
			});
	
});
</script>
     
<div class="login_body">
  
      <form id="add_vehicleromooc" method="post" action="" autocomplete="off">
          <table style="margin-top:20px;">
            <tr>
                <td>Xe <a title="Thêm xe mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("vehicle/add") ?>','Thêm xe mới','vehicle','<?php echo $this->url("vehicle/getvehicle") ?>','add_vehicle')"></i></a></td>
                <td>
                  <select class="form-control select2" id="vehicle" name="vehicle" required="required" tabindex="1">
                    <?php foreach ($vehicles as $vehicle) { ?>
                      <option value="<?php echo $vehicle->vehicle_id ?>"><?php echo $vehicle->vehicle_number ?></option>
                    <?php } ?>
                  </select>
                </td>
            </tr>
            <tr>
                <td>Mooc <a title="Thêm mooc mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("romooc/add") ?>','Thêm mooc mới','romooc','<?php echo $this->url("romooc/getromooc") ?>','add_romooc')"></i></a></td>
                <td>
                  <select class="form-control select2" id="romooc" name="romooc" required="required" tabindex="2">
                    <?php foreach ($romoocs as $romooc) { ?>
                      <option value="<?php echo $romooc->romooc_id ?>"><?php echo $romooc->romooc_number ?></option>
                    <?php } ?>
                  </select>
                </td>
            </tr>
            <tr>
                <td>Ngày lắp vào </td>
                <td><input type="text" id="start_time" name="start_time" tabindex="3" class="start-date" required="required"></td>
            </tr>
            <tr>
                <td>Ngày thay ra </td>
                <td><input type="text" id="end_time" name="end_time" tabindex="4" class="end-date"></td>
            </tr>
        </table> 
    </form>
</div>
<div id="error_vehicleromooc" class="error"><?php echo isset($error) ? $error : null; ?></div>


