
<div class="login_body">
  
          <table style="margin-top:20px;">
            <tr>
                <td>Xe <a title="Thêm xe mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("vehicle/add") ?>','Thêm xe mới','vehicle','<?php echo $this->url("vehicle/getvehicle") ?>','add_vehicle')"></i></a></td>
                <td>
                  <select class="form-control select2" id="vehicle" name="vehicle" required="required" tabindex="1">
                    <?php foreach ($vehicles as $vehicle) { ?>
                      <option value="<?php echo $vehicle->vehicle_id ?>" <?php echo $vehicle_romooc_data->vehicle==$vehicle->vehicle_id?'selected="selected"':null ?>><?php echo $vehicle->vehicle_number ?></option>
                    <?php } ?>
                  </select>
                </td>
            </tr>
            <tr>
                <td>Mooc <a title="Thêm mooc mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("romooc/add") ?>','Thêm mooc mới','romooc','<?php echo $this->url("romooc/getromooc") ?>','add_romooc')"></i></a></td>
                <td>
                  <select class="form-control select2" id="romooc" name="romooc" required="required" tabindex="2">
                    <?php foreach ($romoocs as $romooc) { ?>
                      <option value="<?php echo $romooc->romooc_id ?>" <?php echo $vehicle_romooc_data->romooc==$romooc->romooc_id?'selected="selected"':null ?>><?php echo $romooc->romooc_number ?></option>
                    <?php } ?>
                  </select>
                </td>
            </tr>
            <tr>
                <td>Ngày lắp vào </td>
                <td><input type="text" id="start_time" name="start_time" tabindex="3" class="start-date" required="required" value="<?php echo $lib->hien_thi_ngay_thang($vehicle_romooc_data->start_time) ?>"></td>
            </tr>
            <tr>
                <td>Ngày thay ra </td>
                <td><input type="text" id="end_time" name="end_time" tabindex="4" class="end-date" value="<?php echo $lib->hien_thi_ngay_thang($vehicle_romooc_data->end_time) ?>"></td>
            </tr>
        </table> 
    
</div>
<div id="error_vehicleromooc" class="error"><?php echo isset($error) ? $error : null; ?></div>
