<script type="text/javascript">
$(document).ready(function(){
	$( ".select2" ).select2({dropdownAutoWidth : true});
			// Validate form
			$("#add_spare_part").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
				rules: {
				},
        submitHandler: function(form) {
                
          var formData = new FormData($("#add_spare_part")[0]);
          
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/sparepart/addsparepart", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: formData, // giá trị post
              cache: false,
              contentType: false,
              processData: false,
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error_spare_part').hide();
                  $('#error_spare_part').slideToggle(100); // hiển thị thẻ div success
                  $('#error_spare_part').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error_spare_part').fadeOut(10000);

              }
          });
          return false;
           
       }
					 
				 
			});
	
});
</script>
     
<div id="error_spare_part" class="error"><?php echo isset($error) ? $error : null; ?></div>
<div class="login_body">
  
      <form id="add_spare_part" method="post" action="" autocomplete="off">
        <div class="col-xs-6">
          <label for="spare_part_code">Mã vật tư <a title="Thêm mã mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("sparepartcode/add") ?>','Thêm mã mới','spare_part_code','<?php echo $this->url("sparepartcode/getsparepartcode") ?>','add_spare_part_code')"></i></a></label>
          <div class="input-group">
            <select class="form-control select2" id="spare_part_code" name="spare_part_code" required="required" tabindex="1">
              <?php foreach ($codes as $code) { ?>
                <option value="<?php echo $code->spare_part_code_id ?>" data="<?php echo $code->name ?>"><?php echo $code->code ?></option>
              <?php } ?>
            </select>
          </div>
          <label for="spare_part_name">Tên vật tư</label>
          <div class="input-group">
            <input type="text" id="spare_part_name" name="spare_part_name" tabindex="2" required="required">
          </div>
          <label for="spare_part_seri">Số seri</label>
          <div class="input-group">
            <input type="text" id="spare_part_seri" name="spare_part_seri" tabindex="3" >
          </div>
        </div>
        <div class="col-xs-6">
          <label for="spare_part_brand">Nhà sản xuất</label>
          <div class="input-group">
            <input type="text" id="spare_part_brand" name="spare_part_brand" tabindex="4">
          </div>
          <label for="spare_part_date_manufacture">Ngày sản xuất</label>
          <div class="input-group">
            <input class="input-mask-date" type="text" id="spare_part_date_manufacture" name="spare_part_date_manufacture" tabindex="5">
          </div>
          <label for="spare_part_unit">Đơn vị tính</label>
          <div class="input-group">
            <input type="text" id="spare_part_unit" name="spare_part_unit" tabindex="6">
          </div>
        </div>
    </form>
</div>



<script type="text/javascript">
$('#spare_part_name').val($('#spare_part_code option:selected').attr('data'));

  $('#spare_part_code').on("select2:select", function(e) { 
    var val = $(this).val();
    $.ajax({
        type: "GET",
        url: "<?php echo BASE_URL ?>/sparepartcode/getcode",
        data: {data:val}, 
        success: function(answer){
           $('#spare_part_name').val(answer);
        }
    });
  });
</script>