
<?php
$url_order = 'DESC';
if ($order_by == 'spare_part_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'spare_part_seri')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'spare_part_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'code')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'spare_part_date_manufacture')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'spare_part_brand')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
$i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>
<div class="tools action-buttons pull-right">
    <?php
    if (isset($filter)) {
        echo '<a class="tooltip-warning" data-rel="tooltip" data-original-title="Dữ liệu đã được lọc bớt"><span class="green"><i class="ace-icon fa fa-filter bigger-150"></i></span></a>';
    }
    ?>
    <select name="m" id="chonloc" class="input-sm" onchange="limit_change($(this).val(),'<?php echo $order_by ?>','<?php echo $order ?>','<?php echo $keyword ?>')">
        <option value="18446744073709">All</option>
        <option value="10">10</option>
        <option value="20">20</option>
        <option value="50">50</option>
        <option value="100">100</option>
        <option value="500">500</option>
    </select>
    <a class="purpose" data-original-title="Thêm mới">
        <i class="ace-icon fa fa-plus-circle bigger-150" onclick="add_click('<?php echo $this->url("sparepart/add") ?>','Thêm vật tư mới')"></i>
    </a> 
    <div class="pull-right pos-rel dropdown-hover">
        <button class="btn btn-minier bigger" style="line-height: 26px">
            <i class="ace-icon fa fa-windows icon-only bigger-120"></i>
        </button>

        <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-caret dropdown-close dropdown-menu-right">
            <li>
                <a class="tooltip-warning" data-rel="tooltip" data-original-title="Tìm">
                    <span class="orange">
                        <i class="ace-icon fa fa-search bigger-150" onclick="search_click()"></i>
                    </span>
                </a>
            </li>
            <li>
                <a class="tooltip-success" data-rel="tooltip" data-original-title="Lọc">
                    <span class="green">
                        <i class="ace-icon fa fa-filter bigger-150" onclick="filter_click('<?php echo $this->url("sparepart/filter?page=".$page."&order_by=".$order_by."&order=".$order."&limit=".$limit."&keyword=".$keyword) ?>','Lọc dữ liệu')"></i>
                    </span>
                </a>
            </li>
            <li>
                <a class="tooltip-error" data-rel="tooltip" data-original-title="Xóa">
                    <span class="red">
                        <i class="ace-icon fa fa-trash-o bigger-150" onclick="del_click()"></i>
                    </span>
                </a>
            </li>
            <li>
                <a class="tooltip-info" data-rel="tooltip" data-original-title="Nhập">
                    <span class="purple">
                        <i class="ace-icon fa fa-cloud-upload bigger-150" onclick="import_click('<?php echo $this->url("sparepart/import") ?>','Nhập dữ liệu từ file Excel')"></i>
                    </span>
                </a>
            </li>
            <li>
                
                <div class="text-center pos-rel dropdown-hover">
                    <a class="tooltip-info" data-rel="tooltip" data-original-title="Xuất">
                        <span class="blue">
                            <i class="ace-icon fa fa-cloud-download bigger-150"></i>
                        </span>
                    </a>
                    <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-caret dropdown-close dropdown-menu-right">
                        <li>
                            <a class="tooltip-success" data-rel="tooltip" data-original-title="Excel">
                                <span class="green">
                                    <i class="ace-icon fa fa-file-excel-o bigger-130" onclick="export_click('excel','tblexport')"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a class="tooltip-error" data-rel="tooltip" data-original-title="PDF">
                                <span class="red">
                                    <i class="ace-icon fa fa-file-pdf-o bigger-130" onclick="export_click('pdf','tblexport')"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a class="tooltip-info" data-rel="tooltip" data-original-title="Word">
                                <span class="blue">
                                    <i class="ace-icon fa fa-file-word-o bigger-130" onclick="export_click('word','tblexport')"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            
        </ul>
    </div>                        
</div>
<div class="clearfix"></div>
<div id="content" style="padding:5px;">
   
<table class="table_data" id="tblexport" >
<thead>
    <tr>
    	<th><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall" class="ace ace-checkbox-2" /><span class="lbl"></span></th>
        <th><a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','spare_part_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'spare_part_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a></th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','code','<?php echo $url_order ?>')">Mã <?php if ($order_by == 'code'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','spare_part_name','<?php echo $url_order ?>')">Tên <?php if ($order_by == 'spare_part_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','spare_part_seri','<?php echo $url_order ?>')">Số seri <?php if ($order_by == 'spare_part_seri'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','spare_part_brand','<?php echo $url_order ?>')">Nhà sản xuất <?php if ($order_by == 'spare_part_brand'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','spare_part_date_manufacture','<?php echo $url_order ?>')">Ngày sản xuất <?php if ($order_by == 'spare_part_date_manufacture'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
           
        <th>
            
        </th>
    </tr>
   </thead>
   <tbody>
    <?php $l=1;
        foreach ($arr as $key => $value) { ?>
        <tr style="font-weight: bold; background: #96d7f170">
            <td><a class="tr_parent" data="tr_<?php echo $l ?>" title="Ẩn/Hiện"><i class="fa fa-angle-down ace-icon bigger-150"></i></a></td>
            <td><?php echo $l++; ?></td>
            <td><?php echo $key; ?></td>
            <td><?php echo key($value); ?></td>
            <td colspan="4"></td>
        </tr>
        <?php $h=1;
            foreach ($value as $key1) { 
                foreach($key1 as $sparepart){
                ?>
                <tr style="display: none;" id="<?php echo $sparepart->spare_part_id ?>" class="edit_tr tr_<?php echo ($l-1) ?>" >
                    <td class="text-center"><input name="check[]" type="checkbox" class="checkbox ace" value="<?php echo $sparepart->spare_part_id ?>"><span class="lbl"></span></td>
                    <td class="text-center"><?php echo $h++; ?></td>
                    <td></td>
                    <td><?php echo $sparepart->spare_part_name; ?></td>
                    <td><?php echo $sparepart->spare_part_seri; ?></td>
                    <td><?php echo $sparepart->spare_part_brand; ?></td>
                    
                    <td><?php echo $lib->hien_thi_ngay_thang($sparepart->spare_part_date_manufacture); ?></td>
                    
                    <td class="text-right">
                        <div class="tools action-buttons">
                            <a class="blue"  onclick="view_click('<?php echo $this->url("sparepart/view/") ?>','Thông tin vật tư',<?php echo $sparepart->spare_part_id ?>)">
                                <i class="ace-icon fa fa-info-circle bigger-130"></i>
                            </a>
                            <a class="green"  onclick="edit_click('<?php echo $this->url("sparepart/edit/") ?>','Cập nhật vật tư',<?php echo $sparepart->spare_part_id ?>)">
                                <i class="ace-icon fa fa-pencil bigger-130"></i>
                            </a>

                            <a class="red" >
                                <i class="ace-icon fa fa-trash-o bigger-130" onclick="del(<?php echo $sparepart->spare_part_id ?>)"></i>
                            </a>
                        </div>
                    </td>
                </tr>
    <?php  } } }?>
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>
</div>
<script type="text/javascript">
    var ch = "<?php echo $limit ?>";
$('#chonloc option[value='+ch+']').attr('selected','selected');

$('.tr_parent').on('click', function(event) {        
     $('.'+$(this).attr('data')).toggle('show');
});
</script>