
<?php

$url_order = 'ASC';

if ($order_by == 'payment_voucher_id')

    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';



elseif ($order_by == 'payment_voucher_date')

    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

elseif ($order_by == 'payment_voucher_number')

    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

elseif ($order_by == 'payment_voucher_money')

    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

elseif ($order_by == 'bank_name')

    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';




    $ii = $sonews*$page-($sonews-1);



?>



<div id="loading"></div>

<div id="winpopup"></div>

<section class="content-header">

    <h1>BÁO CÁO CHI TIỀN MẶT - TIỀN GỬI</h1>

  <ol class="breadcrumb">

    <li><a href="<?php echo $this->url('admin') ?>"><i class="fa fa-dashboard"></i> Home</a></li>

    <li class="active"><a href="<?php echo $this->url('paymentvoucher') ?>">Chi</a></li>

  </ol>

</section>

<div id="content" style="padding:5px;">



    <div class="search-box">

        

        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">

        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">

        <?php if(!isset($disable_control)){ ?>

        <div class="add-box"><a class="add_button" id="btnExport" ><i class="fa fa-download"></i> Xuất</a></div>

        <div class="add-box"><a class="add_button" onClick="add_click();"><i class="fa fa-plus"></i> Thêm mới</a></div>

        <?php } ?>

    </div>

    <div class="tablenav top">

        <div class="add-box">

            <select id="sl_round" name="sl_round" style="width:90px">

             <?php 

                for ($k=1; $k < 13; $k++) { 

                    echo '<option value="'.$k.'">Tháng '.$k.'</option>';

                }

             ?>

            </select>

            <select id="sl_staff" name="sl_staff" style="width:100px">

             <?php 

                $nam = date('Y');

                for ($k=($nam-5); $k < ($nam+5); $k++) { 

                    echo '<option value="'.$k.'">Năm '.$k.'</option>';

                }

             ?>

            </select>



            <input type="button" name="xem" id="xem" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  

            

        </div>

    </div>

    <div class="tablenav top">

        <div style="clear:both"></div>

        <div class="add-box">

                  

            Từ  <input style="width:80px" type="search" name="batdau" id="batdau" placeholder="Chọn ngày" <?php if(isset($batdau)) echo "value='$batdau'"; ?> >  

            Đến  <input style="width:80px" type="search" name="ketthuc" id="ketthuc" placeholder="Chọn ngày" <?php if(isset($ketthuc)) echo "value='$ketthuc'"; ?> >  

             <input type="button" name="xem" id="xem" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  

            

        </div>



      </div>

      <div class="tablenav top">

        <div style="clear:both"></div>

        

        <div class="add-box">

            <input type="button" name="chon" id="chon" value="Chọn" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  

        </div>

        

        <div class="add-box" style="margin-right: 5px">


            <select style="width:120px" name="sl_status" id="sl_status">

                <option value="0">Khách hàng</option>

                <?php foreach ($customers as $sm) { ?>

                <option value="<?php echo $sm->customer_id ?>"><?php echo $sm->customer_name ?></option>

                <?php } ?>

            </select>



            

            

        </div>

        <?php if(!isset($disable_control)){ ?>

        <div class="alignleft actions">

            <select name="action" id="action">

                <option value="-1" selected="selected">Chọn</option>

                

                <option value="delete">Xóa</option>

            </select>

            <input type="button" name="" id="doaction" class="button action" value="Áp dụng" onclick="action();">

        </div>

        <?php } ?>

        <div class="alignleft actions">

        <select name="m" id="chonloc" style="width:200px">

            <option value="18446744073709">Hiển thị tất cả</option>

            <option value="50">Hiển thị 50 giá trị</option>

            <option value="100">Hiển thị 100 giá trị</option>

            <option value="150">Hiển thị 150 giá trị</option>

            <option value="200">Hiển thị 200 giá trị</option>

            <option selected="selected" value="250">Hiển thị 250 giá trị</option>

        </select>

        <input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">                               

        </div>



      </div>

</div>





<table class="table_data" id="tblExport">

<thead>

    <tr>

    	<th class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>

        <th  class="fix" >

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','payment_voucher_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'payment_voucher_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>

        

        <th  class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','payment_voucher_date','<?php echo $url_order ?>')">Ngày <?php if ($order_by == 'payment_voucher_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>

        <th  class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','payment_voucher_number','<?php echo $url_order ?>')">Số chứng từ <?php if ($order_by == 'payment_voucher_number'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>

        <th  class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','payment_voucher_money','<?php echo $url_order ?>')">Số tiền <?php if ($order_by == 'payment_voucher_money'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>

        <th  class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','payment_voucher_comment','<?php echo $url_order ?>')">Nội dung <?php if ($order_by == 'payment_voucher_comment'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>
        <th  class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','bank_name','<?php echo $url_order ?>')">Tài khoản trả <?php if ($order_by == 'bank_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>

        <?php if(!isset($disable_control)){ ?>

           

        <th  class="fix">&nbsp;</th>

        <?php } ?>

    </tr>

    

   </thead>

   <tbody>

    <?php 
    $tongthanhtien = 0;
    foreach ($payments as $payment_voucher) : 
      $tongthanhtien += $payment_voucher->payment_voucher_money;
    ?>

    

        

        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $payment_voucher->payment_voucher_id ?>" class="edit_tr" title="<?php echo $payment_voucher->payment_voucher_type ?>">

        	<td><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $payment_voucher->payment_voucher_id ?>"></td>

            <td  class="fix"><?php echo $ii++; ?></td>

            <td class="fix" id="payment_voucher_date_<?php echo $payment_voucher->payment_voucher_id; ?>"><?php echo $lib->hien_thi_ngay_thang($payment_voucher->payment_voucher_date); ?></td>

            <td class="fix" id="payment_voucher_number_<?php echo $payment_voucher->payment_voucher_id; ?>"><?php echo $payment_voucher->payment_voucher_number; ?></td>

            <td class="fix" id="payment_voucher_money_<?php echo $payment_voucher->payment_voucher_id; ?>"><?php echo $lib->formatMoney($payment_voucher->payment_voucher_money); ?></td>

            <td class="fix" id="payment_voucher_comment_<?php echo $payment_voucher->payment_voucher_id; ?>"><?php echo $payment_voucher->payment_voucher_comment; ?></td>

            <td class="fix" id="bank_out_<?php echo $payment_voucher->payment_voucher_id; ?>"><?php echo $payment_voucher->bank_name; ?></td>

            <td class="fix" style="display:none" id="payment_voucher_attach_<?php echo $payment_voucher->payment_voucher_id; ?>"><?php echo $payment_voucher->payment_voucher_attach; ?></td>

            <td class="fix" style="display:none" data="<?php echo $payment_voucher->customer; ?>" id="customer_<?php echo $payment_voucher->payment_voucher_id; ?>"><?php echo $payment_voucher->customer>0?$data_customer[$payment_voucher->customer]['name']:null; ?></td>

            <td class="fix" style="display:none" data="<?php echo $payment_voucher->staff; ?>" id="staff_<?php echo $payment_voucher->payment_voucher_id; ?>"><?php echo $payment_voucher->staff>0?$data_staff[$payment_voucher->staff]['name']:null; ?></td>

            <td class="fix" style="display:none" data="<?php echo $payment_voucher->steersman; ?>" id="steersman_<?php echo $payment_voucher->payment_voucher_id; ?>"><?php echo $payment_voucher->steersman>0?$data_steersman[$payment_voucher->steersman]['name']:null; ?></td>

            <td class="fix" style="display:none" data="<?php echo $payment_voucher->toll; ?>" id="toll_<?php echo $payment_voucher->payment_voucher_id; ?>"><?php echo $payment_voucher->toll>0?$data_toll[$payment_voucher->toll]['name']:null; ?></td>

            <td class="fix" style="display:none" id="cost_list_<?php echo $payment_voucher->payment_voucher_id; ?>"><?php echo $payment_voucher->cost_list; ?></td>

            <?php if(!isset($disable_control)){ ?>

            <td class="pull-right">

                <button class="btn btn-sm btn-flat btn-primary"><i class="fa fa-edit"></i> Sửa</button>

                <button class="btn btn-sm btn-flat btn-danger" onclick="del(<?php echo $payment_voucher->payment_voucher_id ?>)" ><i class="fa fa-remove"></i> Xóa</button>

            </td>

            <?php } ?>

        </tr>



    <?php endforeach; ?>

        <tr  style="font-weight: bold; color: rgb(23, 119, 226);" >
            
            <th colspan="4" style="border-right: 1px solid rgb(236, 235, 235);border-top: 1px solid #80C8E5;padding: 7px; text-align: right;" >
                Tổng cộng
            </th>
            <td class="fix" ><?php echo $lib->formatMoney($tongthanhtien) ?></td>
            <td class="fix" ></td>
            <td class="fix" ></td>
        </tr>

   </tbody>

</table>

<?php

$this->helper('slidePaginator');

?>



<div class="add-field">

    <section class="content">

      <div class="row">

        <!-- left column -->

        <div class="col-md-12">

          <!-- general form elements -->
          <div class="tabs">
              <ul class="tab-links">
                <li class="active"  ><a href="#tab1">Thanh toán công nợ</a></li>
                <li ><a href="#tab2">Hành chính</a></li>
              </ul>
              <div class="tab-content">
                <div class="tab active" id="tab1" >

                  <div class="box box-primary">

            <!-- /.box-header -->
            
                    <!-- form start -->
                    <form id="add_payment_voucher" role="form" method="post" action="" enctype="multipart/form-data">

                      <div class="row">

                        <div class="col-md-3 col-xs-6">

                          <div class="box-body">

                            <div class="form-group">

                              <label for="customer">
                                <input type="radio" name="customer_type" value="1" checked> Khách hàng/Đối tác/Cá nhân <a target="_blank" title="Thêm khách hàng" href="<?php echo $this->url('customer') ?>"><i class="fa fa-plus"></i></a> <br>
                                <input type="radio" name="customer_type" value="2"> Nhân viên <a target="_blank" title="Thêm nhân viên" href="<?php echo $this->url('staff') ?>"><i class="fa fa-plus"></i></a> <br>
                                <input type="radio" name="customer_type" value="3"> Tài xế <a target="_blank" title="Thêm tài xế" href="<?php echo $this->url('steersman') ?>"><i class="fa fa-plus"></i></a> <br>
                                <input type="radio" name="customer_type" value="4"> Cầu đường <a target="_blank" title="Thêm trạm thu phí" href="<?php echo $this->url('tollcost') ?>"><i class="fa fa-plus"></i></a>
                              </label>

                              <input type="text" autocomplete="off" id="customer"  name="customer" tabindex="1"  placeholder="Nhập tên hoặc * để chọn" required="required" >

                                <ul id="customer_list_id"></ul>

                            </div>



                          </div>

                          <!-- /.box-body -->

                          

                        </div>

                        <div class="col-md-3 col-xs-6">

                          <div class="box-body">

                            <div class="form-group">

                              <label for="payment_voucher_date">Ngày</label>

                              <input class="ngay" type="text" id="payment_voucher_date"  name="payment_voucher_date" tabindex="2" required="required" >

                            </div>


                            <div class="form-group">

                              <label for="payment_voucher_money">Số tiền</label>

                              <input type="text" class="numbers" id="payment_voucher_money"  name="payment_voucher_money" tabindex="4" required="required" disabled >

                            </div>
                            
                            

                          </div>

                          <!-- /.box-body -->

                          

                        </div>

                        <div class="col-md-3 col-xs-6">

                          <div class="box-body">

                            <div class="form-group">

                              <label for="payment_voucher_number">Số chứng từ</label>

                              <input type="text" id="payment_voucher_number"  name="payment_voucher_number" tabindex="3" required="required" >

                            </div>

                            <div class="form-group">

                              <label for="payment_voucher_comment">Nội dung</label>

                              <input type="text" id="payment_voucher_comment"  name="payment_voucher_comment" tabindex="5" required="required">

                            </div>
                            

                          </div>

                          <!-- /.box-body -->

                          

                        </div>
                        <div class="col-md-3 col-xs-6">

                          <div class="box-body">

                            
                            <div class="form-group">

                              <label for="bank_out">Tài khoản trả</label>

                              <select id="bank_out" name="bank_out" tabindex="7" required="required" >
                                <?php foreach ($banks as $bank) { ?>
                                  <option value="<?php echo $bank->bank_id ?>"><?php echo $bank->bank_name ?></option>
                                <?php } ?>
                                
                              </select>

                            </div>
                            <div class="form-group">

                              <label for="payment_voucher_attach">Kèm theo</label>

                              <input type="text" id="payment_voucher_attach"  name="payment_voucher_attach" tabindex="6">

                            </div>

                          </div>

                          <!-- /.box-body -->

                          

                        </div>




                      </div>

                      <div class="row">

                        <div class="col-md-12">

                            <div class="box-body">

                                <fieldset class="groupbox">

                                        <table id="dataTable" border="1" style="width: 100%; border: 1px solid rgb(221, 217, 217); margin-bottom: 10px" >

                                            <tbody>

                                                <tr>

                                                    <td><input type="checkbox" name="chk2" data="" title="0"></td>

                                                    <td>

                                                        <table style="width:100%">

                                                            <tr>

                                                                <td>Công nợ <br>

                                                                    <input type="text" class="comment" name="comment[]" placeholder="Nhập số hóa đơn,DO hoặc nội dung" autocomplete="off" >
                                                                    <ul class="name_list_id"></ul>
                                                                </td>

                                                                <td>Ngày <br>

                                                                    <input type="text" class="debit_date ngay" name="debit_date[]" style="width:80px" disabled >

                                                                </td>

                                                                <td>Số tiền phải chi <br>

                                                                    <input type="text" class="money numbers" name="money[]" style="width:120px" disabled >

                                                                </td>

                                                                <td>Còn lại<br>

                                                                    <input type="text" class="money_conlai numbers" name="money_conlai[]" style="width:120px" disabled >

                                                                </td>

                                                                <td>Số tiền <br>

                                                                    <input type="text" class="debit_pay_money numbers" name="debit_pay_money[]" style="width:120px" >

                                                                </td>

                                                            </tr>

                                                        </table>

                                                    </td>

                                                </tr>

                                                

                                            </tbody>

                                        </table>

                                        <input type="button" value="Thêm" onclick="addRow('dataTable')">

                                        <input type="button" value="Xóa" onclick="deleteRow('dataTable')">



                                    </fieldset>

                            </div>

                        </div>

                      </div>

                      <div class="row">

                        <div class="col-md-12">

                            <table class="pull-right">

                                <tr>

                                    <td>Cộng</td>

                                    <td><input type="text" class="text-right numbers" id="payment_voucher_sum"  name="payment_voucher_sum" disabled ></td>

                                </tr>


                            </table>

                            

                        </div>

                    </div>

                      <?php if(!isset($disable_control)){ ?>

                      <div class="row">

                        <div class="col-md-12">

                            <div class="box-footer">

                            <input type="hidden" readonly id="yes" name="yes" required="required" >

                            <button type="submit" class="btn btn-primary" tabindex="6">Hoàn thành</button>

                            <button type="reset" class="btn" tabindex="7">Nhập lại</button>

                          </div>

                          <div class="box-footer">

                            <div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>

                          </div>

                        </div>

                      </div>

                      <?php } ?>

                    </form>
                  </div>
                </div>
                <div class="tab" id="tab2" >
                  <div class="box box-primary">

                    <!-- /.box-header -->

                    <!-- form start -->
                    <form id="add_payment_voucher2" role="form" method="post" action="" enctype="multipart/form-data">

                      <div class="row">


                        <div class="col-md-3 col-xs-6">

                          <div class="box-body">

                            <div class="form-group">

                              <label for="payment_voucher_date2">Ngày</label>

                              <input class="ngay" type="text" id="payment_voucher_date2"  name="payment_voucher_date2" tabindex="1" required="required" >

                            </div>
                            
                            <div class="form-group">

                              <label for="bank_out2">Tài khoản chi</label>

                              <select id="bank_out2" name="bank_out2" tabindex="5" required="required" >
                                <?php foreach ($banks as $bank) { ?>
                                  <option value="<?php echo $bank->bank_id ?>"><?php echo $bank->bank_name ?></option>
                                <?php } ?>
                                
                              </select>

                            </div>

                          </div>

                          <!-- /.box-body -->

                          

                        </div>

                        <div class="col-md-3 col-xs-6">

                          <div class="box-body">

                            <div class="form-group">

                              <label for="payment_voucher_number2">Số chứng từ</label>

                              <input type="text" id="payment_voucher_number2"  name="payment_voucher_number2" tabindex="2" required="required" >

                            </div>

                            <div class="form-group">

                              <label for="payment_voucher_attach2">Kèm theo</label>

                              <input type="text" id="payment_voucher_attach2"  name="payment_voucher_attach2" tabindex="6">

                            </div>

                            
                            

                          </div>

                          <!-- /.box-body -->

                          

                        </div>
                        <div class="col-md-3 col-xs-6">

                          <div class="box-body">

                            <div class="form-group">

                              <label for="payment_voucher_comment2">Nội dung</label>

                              <input type="text" id="payment_voucher_comment2"  name="payment_voucher_comment2" tabindex="3" required="required">

                            </div>
                            <div class="form-group">

                              <label for="payment_voucher_attach2">Chi phí</label>

                              <select style="width:150px" id="cost_list2"  name="cost_list2" tabindex="7" >

                                  <?php foreach ($cost_lists as $cost) { ?>

                                      <option value="<?php echo $cost->cost_list_id ?>"><?php echo $cost->cost_list_name ?></option>

                                  <?php } ?>

                              </select>

                            </div>
                            
                            

                          </div>

                          <!-- /.box-body -->

                          

                        </div>

                        <div class="col-md-3 col-xs-6">

                          <div class="box-body">

                            
                            <div class="form-group">

                              <label for="payment_voucher_money2">Số tiền</label>

                              <input type="text" class="numbers" id="payment_voucher_money2"  name="payment_voucher_money2" tabindex="4" required="required" >

                            </div>

                          </div>

                          <!-- /.box-body -->

                          

                        </div>


                      </div>

                      <?php if(!isset($disable_control)){ ?>

                      <div class="row">

                        <div class="col-md-12">

                            <div class="box-footer">

                            <input type="hidden" readonly id="yes2" name="yes2" required="required" >

                            <button type="submit" class="btn btn-primary" tabindex="8">Hoàn thành</button>

                            <button type="reset" class="btn" tabindex="9">Nhập lại</button>

                          </div>

                          <div class="box-footer">

                            <div id="error2" class="error"><?php echo isset($error) ? $error : null; ?></div>

                          </div>

                        </div>

                      </div>

                      <?php } ?>

                    </form>

                  </div>
                </div>
              </div>
            

          </div>

          <!-- /.box -->



        </div>

        <!--/.col (left) -->

        

      </div>

      <!-- /.row -->

    </section>

    <!-- /.content -->

       

</div>



<script type="text/javascript">

$('html').click(function(e) {

    $('#customer_list_id').slideUp(200);
    $('.name_list_id').slideUp(200);

});



    $('.edit_tr').click(function(e){

      var check_sub = $(this).attr('title');

        if(!$('.checkbox').is(':focus') && e.target.nodeName != "A"){

            if(!$('.checkbox').is(':focus')){

                $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);

            }

            var payment_voucher_number = $(this).find("#payment_voucher_number_"+$(this).attr('id')).text();

            var bank_out = $(this).find("#bank_out_"+$(this).attr('id')).text();

            var customer_name = $(this).find("#customer_"+$(this).attr('id')).text();

            var customer = $(this).find("#customer_"+$(this).attr('id')).attr('data');

            var staff_name = $(this).find("#staff_"+$(this).attr('id')).text();

            var staff = $(this).find("#staff_"+$(this).attr('id')).attr('data');

            var steersman_name = $(this).find("#steersman_"+$(this).attr('id')).text();

            var steersman = $(this).find("#steersman_"+$(this).attr('id')).attr('data');

            var toll_name = $(this).find("#toll_"+$(this).attr('id')).text();

            var toll = $(this).find("#toll_"+$(this).attr('id')).attr('data');

            var payment_voucher_date = $(this).find("#payment_voucher_date_"+$(this).attr('id')).text();

            var payment_voucher_money = $(this).find("#payment_voucher_money_"+$(this).attr('id')).text();

            var payment_voucher_comment = $(this).find("#payment_voucher_comment_"+$(this).attr('id')).text();

            var payment_voucher_attach = $(this).find("#payment_voucher_attach_"+$(this).attr('id')).text();

            var cost_list = $(this).find("#cost_list_"+$(this).attr('id')).text();


            if (check_sub == 2) {

              $('#tab2').show();

              $('.tab-links li:nth-child(2)').show();

              $('#tab2').addClass('active');

              $('#tab1').hide();

              $('.tab-links li:nth-child(2)').addClass('active');

              $('.tab-links li:nth-child(1)').hide();

              $('#tab2').css({'display':'block'});

              $('#tab1').hide();

              $('#payment_voucher_number2').val(payment_voucher_number);

              $('#payment_voucher_date2').val(payment_voucher_date.replace(/\//g,"-"));

              $('#bank_out2 option:contains('+bank_out+')').attr('selected','selected');

              $('#payment_voucher_money2').val(payment_voucher_money);

              $('#payment_voucher_comment2').val(payment_voucher_comment);

              $('#payment_voucher_attach2').val(payment_voucher_attach);

              $('#cost_list2 option[value='+cost_list+']').attr('selected','selected');

              $('#yes2').val($(this).attr('id'));

            }
            else{
              $('#tab1').show();

              $('.tab-links li:nth-child(1)').show();

              $('#tab1').addClass('active');

              $('#tab2').hide();

              $('.tab-links li:nth-child(1)').addClass('active');

              $('.tab-links li:nth-child(2)').hide();

              $('#tab1').css({'display':'block'});

              $('#tab2').hide();


              $('#payment_voucher_number').val(payment_voucher_number);

              $('#payment_voucher_date').val(payment_voucher_date.replace(/\//g,"-"));

              $('#bank_out option:contains('+bank_out+')').attr('selected','selected');

              $('#payment_voucher_money').val(payment_voucher_money);

              $('#payment_voucher_comment').val(payment_voucher_comment);

              $('#payment_voucher_attach').val(payment_voucher_attach);

              $('#payment_voucher_sum').val(payment_voucher_money);


              if (customer > 0) {
                $('input[name=customer_type][value=1]').prop('checked',true);

                $('#customer').val(customer_name);

                $('#customer').attr('data',customer);

                $('#customer').attr('code',true);
              }
              else if (staff > 0) {
                $('input[name=customer_type][value=2]').prop('checked',true);

                $('#customer').val(staff_name);

                $('#customer').attr('data',staff);

                $('#customer').attr('code',true);
              }
              else if (steersman > 0) {
                $('input[name=customer_type][value=3]').prop('checked',true);

                $('#customer').val(steersman_name);

                $('#customer').attr('data',steersman);

                $('#customer').attr('code',true);
              }
              else if (toll > 0) {
                $('input[name=customer_type][value=4]').prop('checked',true);

                $('#customer').val(toll_name);

                $('#customer').attr('data',toll);

                $('#customer').attr('code',true);
              }

              


              $('#yes').val($(this).attr('id'));




              $('#dataTable tbody tr').remove();

          

              var payment_voucher_id = $(this).attr('id');

              $.ajax({

                  url: '<?php echo BASE_URL ?>/paymentvoucher/getdebitadd',

                  type: 'POST',

                  data: {payment_voucher:payment_voucher_id},

                  success:function(data){

                      //alert(data);

                      $('#dataTable tbody').append(data);



                      $('.comment').keyup(function(){

                        var row = $(this).parent().parent().parent().parent().parent().parent();

                        var rowIndex = row[0].rowIndex;

                        var type = $('input[name=customer_type]:checked').val();

                        var customer = $('#customer').attr('data');

                        var keyword = $(this).val();

                        $.ajax({

                            url: '<?php echo BASE_URL ?>/paymentvoucher/getDebit',

                            type: 'POST',

                            data: {keyword:keyword, offset:rowIndex, type:type, customer:customer},

                            success:function(data){

                                $('.name_list_id:eq('+rowIndex+')').slideDown(200);

                                $('.name_list_id:eq('+rowIndex+')').html(data);

                            }

                        });

                        if ($('.comment:eq('+rowIndex+')').val() == "" || $('.comment:eq('+rowIndex+')').attr('data') == "") {

                            

                            $('.comment:eq('+rowIndex+')').attr('data',"");

                        }



                        

                    });



                $('.comment').on('keydown', function() {

                        var row = $(this).parent().parent().parent().parent().parent().parent();

                        var rowIndex = row[0].rowIndex;



                        var key = event.keyCode || event.charCode;



                        if( key == 8 || key == 46 ){

                            $('.comment:eq('+rowIndex+')').attr('data',"");

                        }

                            

                      }); 

                $('.debit_pay_money').keyup(function(){

                      var row = $(this).parent().parent().parent().parent().parent().parent();

                      var rowIndex = row[0].rowIndex;


                      var number = parseFloat($(this).val().replace(/\,/g, ""));

                      var max = parseFloat($('.money_conlai:eq('+rowIndex+')').val().replace(/\,/g, "")) || 0;

                      if (max == 0 || max == "") {
                        $(this).val(0);
                      }

                      if (number > max) {
                        $(this).val(max);
                      }


                      var total = 0;

                      $('.debit_pay_money').each(function() { 

                        total += parseFloat($(this).val().replace(/\,/g, ""));

                        $('#payment_voucher_sum').val(total);
                        $('#payment_voucher_money').val(total);

                    });




                      $('.numbers').val(function(index, value) {

                          return value

                            .replace(/\D/g, "")

                            .replace(/\B(?=(\d{3})+(?!\d))/g, ",")

                          ;

                        });




                    });



                        $('.numbers').val(function(index, value) {

                            return value

                              .replace(/\D/g, "")

                              .replace(/\B(?=(\d{3})+(?!\d))/g, ",")

                            ;

                          });



                      $('.number').keyup(function(event) {



                            // skip for arrow keys

                        if(event.which >= 37 && event.which <= 40) return;



                        // format number

                        $(this).val(function(index, value) {

                          return value

                            .replace(/[^0-9-.]/g, "")

                          ;

                        });

                      });

                     

                     $('.numbers').keyup(function(event) {



                            // skip for arrow keys

                        if(event.which >= 37 && event.which <= 40) return;



                        // format number

                        $(this).val(function(index, value) {

                          return value

                            .replace(/[^0-9]/g, "")

                            .replace(/\B(?=(\d{3})+(?!\d))/g, ",")

                          ;

                        });

                      });



                     function get_number(id){

                      return $(id).val().replace(/\,/g,'');

                    }



                  }



              });



              $(".numbers").val(function(index, value) {

                return value

                  .replace(/\B(?=(\d{3})+(?!\d))/g, ",")

                ;

              });
            }


            



            $( ".add-field" ).dialog( "open" );

        }

    });

</script>

<script type="text/javascript">

function add_click(){

  $('#tab1').show();

  $('.tab-links li:nth-child(2)').show();

  $('.tab-links li:nth-child(1)').show();

  $('.tab-links li:nth-child(1)').addClass('active');

  $('.tab-links li:nth-child(2)').removeClass('active');

  $('#tab1').addClass('active');

  $('#tab2').removeClass('active');

    $('#yes').val("");
    $('#yes2').val("");

    $('.add-field').slideDown(500);

     $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);   

        $('#payment_voucher_number2').val("");

        $('#payment_voucher_date2').val("");

        $('#payment_voucher_money2').val("");

        $('#payment_voucher_comment2').val("");

        $('#payment_voucher_attach2').val("");

        ////////////

        $('#payment_voucher_number').val("");

        $('#payment_voucher_date').val("");

        $('#payment_voucher_money').val("");

        $('#payment_voucher_comment').val("");

        $('#payment_voucher_attach').val("");

        $('#customer').val("");

        $('#customer').attr('data',"");

        $('#customer').attr('code',false);

        
        $('.comment').val("");

        $('.comment').attr('data',"");

        $('.comment').attr('alt',"");

        $('.debit_date').val("");

        $('.money').val("");

        $('.money_conlai').val("");

        $('.debit_pay_money').val("");

        $('input[name="chk"]').attr('data',"");

        

        $('.number').focus(function(){

            if ( $(this).val() == '0') {

               $(this).val(""); 

            };

            

        });

        $('.number').blur(function(){

            if ( $(this).val() == "") {

                $(this).val(0);

            };

            

        });





   $( ".add-field" ).dialog( "open" );



}



$(document).ready(function(){

            // Validate form

            $("#add_payment_voucher").validate({

                errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi

                rules: {

                    

                },

                submitHandler: function(form) {

                

                    if ($('#customer').attr('code') == 'false') {

                        $('#customer').val("");

                        $('#customer').focus();

                        return false;

                    };



                    var payment_voucher_number = $('#payment_voucher_number').attr('value');

                    var bank_out = $('#bank_out').attr('value');

                    var customer = $('#customer').attr('data');

                    var payment_voucher_date = $('#payment_voucher_date').attr('value');

                    var payment_voucher_money = $('#payment_voucher_money').attr('value');

                    var payment_voucher_comment = $('#payment_voucher_comment').attr('value');

                    var payment_voucher_attach = $('#payment_voucher_attach').attr('value');

                    var type = $('input[name=customer_type]:checked').val();



                    var debit_pay = [];

                    var debit_id = [];

                    var debit_pay_id = [];

                    var debit_pay_money = [];



                    $('.comment').each(function() { 

                        debit_id.push($(this).attr('data'));

                        debit_pay_id.push($(this).attr('alt'));

                    });



                    $('.debit_pay_money').each(function() { 

                        debit_pay_money.push($(this).val());

                    });



                    for (var i = 0; i < debit_pay_id.length; i++) {

                        debit_pay.push({'debit_pay_id':debit_pay_id[i],'debit_id':debit_id[i],'debit_pay_money':debit_pay_money[i]});

                        

                        

                    };

                    

                    var yes = $('#yes').attr('value');

                    

                    var action      = "them";

                 

                    $.ajax({

                        type: "POST", // phương thức gởi đi

                        url: "<?php echo BASE_URL ?>/paymentvoucher/add", // nơi mà dữ liệu sẽ chuyển đến khi submit

                        data: {

                            payment_voucher_number: payment_voucher_number,

                            bank_out: bank_out,

                            customer: customer,

                            payment_voucher_date: payment_voucher_date,

                            payment_voucher_money: payment_voucher_money,

                            payment_voucher_comment: payment_voucher_comment,

                            payment_voucher_attach: payment_voucher_attach,

                            type: type,

                            debit_pay: debit_pay,

                            yes: yes,

                            }, // giá trị post

                        success: function(answer){ // if everything goes well

                            //alert(answer);

                            $('#error').hide();

                            $('#error').slideToggle(100); // hiển thị thẻ div success

                            $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success

                            $('#error').fadeOut(10000);



                            if (yes != "") {

                                if (answer.trim() != "Thông tin này đã tồn tại" ) {

                                  setTimeout(function() {

                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');

                                      }, 200);

                                    $('#export_stock_name_'+yes).text(export_stock_name);

                                    $('#province_name_'+yes).text($('#province option:selected').text());

                                }

                            }

                            else{

                                if (answer.trim() != "Thông tin này đã tồn tại") {

                                  setTimeout(function() {

                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');

                                      }, 200);

                                    var lastID = parseInt($('#lasted').html());

                                    var rowCount = parseInt($('.table_data > tbody > tr').length);

                                    $('.table_data > tbody:last')

                                    .append(

                                        '<tr onclick="HighLightTR(this,#4d90fe,cc3333);" id="'+parseInt(lastID+1)+'" class="edit_tr"><td><input name="check[]" type="checkbox" class="checkbox" value="'+parseInt(lastID+1)+'"></td><td class="fix">'+parseInt(rowCount+1)+'</td><td class="fix" id="export_stock_name_'+parseInt(lastID+1)+'">'+export_stock_name+'</td><td class="fix" data="'+province+'" id="province_name_'+parseInt(lastID+1)+'">'+$('#province option:selected').text()+'</td><td><a class="error" href="#">Sửa</a> | <a class="error" onclick="del('+parseInt(lastID+1)+')">Xóa</a></td></tr>'

                                    );



                                    $('#lasted').html(parseInt(lastID+2));

                                }

                            }

                        }

                    });

                    return false;

                     

                 }

            });

            
            $("#add_payment_voucher2").validate({

                errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi

                rules: {

                    

                },

                submitHandler: function(form) {

                

                    var payment_voucher_number = $('#payment_voucher_number2').attr('value');

                    var bank_out = $('#bank_out2').attr('value');

                    var payment_voucher_date = $('#payment_voucher_date2').attr('value');

                    var payment_voucher_money = $('#payment_voucher_money2').attr('value');

                    var payment_voucher_comment = $('#payment_voucher_comment2').attr('value');

                    var payment_voucher_attach = $('#payment_voucher_attach2').attr('value');

                    var cost_list = $('#cost_list2').attr('value');

                    
                    

                    var yes = $('#yes2').attr('value');

                    

                    var action      = "them";

                 

                    $.ajax({

                        type: "POST", // phương thức gởi đi

                        url: "<?php echo BASE_URL ?>/paymentvoucher/add2", // nơi mà dữ liệu sẽ chuyển đến khi submit

                        data: {

                            payment_voucher_number: payment_voucher_number,

                            bank_out: bank_out,

                            payment_voucher_date: payment_voucher_date,

                            payment_voucher_money: payment_voucher_money,

                            payment_voucher_comment: payment_voucher_comment,

                            payment_voucher_attach: payment_voucher_attach,

                            cost_list: cost_list,

                            yes: yes,

                            }, // giá trị post

                        success: function(answer){ // if everything goes well

                            //alert(answer);

                            $('#error2').hide();

                            $('#error2').slideToggle(100); // hiển thị thẻ div success

                            $('#error2').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success

                            $('#error2').fadeOut(10000);



                            if (yes != "") {

                                if (answer.trim() != "Thông tin này đã tồn tại" ) {

                                  setTimeout(function() {

                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');

                                      }, 200);

                                    $('#export_stock_name_'+yes).text(export_stock_name);

                                    $('#province_name_'+yes).text($('#province option:selected').text());

                                }

                            }

                            else{

                                if (answer.trim() != "Thông tin này đã tồn tại") {

                                  setTimeout(function() {

                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');

                                      }, 200);

                                    var lastID = parseInt($('#lasted').html());

                                    var rowCount = parseInt($('.table_data > tbody > tr').length);

                                    $('.table_data > tbody:last')

                                    .append(

                                        '<tr onclick="HighLightTR(this,#4d90fe,cc3333);" id="'+parseInt(lastID+1)+'" class="edit_tr"><td><input name="check[]" type="checkbox" class="checkbox" value="'+parseInt(lastID+1)+'"></td><td class="fix">'+parseInt(rowCount+1)+'</td><td class="fix" id="export_stock_name_'+parseInt(lastID+1)+'">'+export_stock_name+'</td><td class="fix" data="'+province+'" id="province_name_'+parseInt(lastID+1)+'">'+$('#province option:selected').text()+'</td><td><a class="error" href="#">Sửa</a> | <a class="error" onclick="del('+parseInt(lastID+1)+')">Xóa</a></td></tr>'

                                    );



                                    $('#lasted').html(parseInt(lastID+2));

                                }

                            }

                        }

                    });

                    return false;

                     

                 }

            });



    $('#customer').keyup(function(){

      var type = $('input[name=customer_type]:checked').val();

        var keyword = $(this).val();

        $.ajax({

            url: '<?php echo BASE_URL ?>/paymentvoucher/getcustomer',

            type: 'POST',

            data: {keyword:keyword, type:type},

            success:function(data){

                $('#customer_list_id').slideDown(200);

                $('#customer_list_id').html(data);

            }

        });

        if ($('#customer').val() == "" || $('#customer').attr('data') == "") {

            //$('#loc_from').val("");

            $('#customer').attr('data',"");

            $('#customer').attr('code',false);

        }

      

   });

   $('#customer').on('keydown', function() {

        var key = event.keyCode || event.charCode;



        if( key == 8 || key == 46 ){

            $('#customer').attr('data',"");

        }

            

      }); 

   $('input[name=customer_type]').change(function(){
      $('#customer').attr('data',"");
      $('#customer').val("");
      $('#customer').attr('code',false);
      $('.comment').val("");
      $('.comment').attr('data',"");
      $('.debit_date').val("");
      $('.money').val("");
      $('.money_conlai').val("");

   });

   $('.comment').keyup(function(){

        var row = $(this).parent().parent().parent().parent().parent().parent();

        var rowIndex = row[0].rowIndex;

        var type = $('input[name=customer_type]:checked').val();

        var customer = $('#customer').attr('data');

        var keyword = $(this).val();

        $.ajax({

            url: '<?php echo BASE_URL ?>/paymentvoucher/getDebit',

            type: 'POST',

            data: {keyword:keyword, offset:rowIndex, type:type, customer:customer},

            success:function(data){

                $('.name_list_id:eq('+rowIndex+')').slideDown(200);

                $('.name_list_id:eq('+rowIndex+')').html(data);

            }

        });

        if ($('.comment:eq('+rowIndex+')').val() == "" || $('.comment:eq('+rowIndex+')').attr('data') == "") {

            

            $('.comment:eq('+rowIndex+')').attr('data',"");

        }



        

    });



$('.comment').on('keydown', function() {

        var row = $(this).parent().parent().parent().parent().parent().parent();

        var rowIndex = row[0].rowIndex;



        var key = event.keyCode || event.charCode;



        if( key == 8 || key == 46 ){

            $('.comment:eq('+rowIndex+')').attr('data',"");

        }

            

      }); 

$('.debit_pay_money').keyup(function(){

      var row = $(this).parent().parent().parent().parent().parent().parent();

      var rowIndex = row[0].rowIndex;

      var number = parseFloat($(this).val().replace(/\,/g, ""));

      var max = parseFloat($('.money_conlai:eq('+rowIndex+')').val().replace(/\,/g, "")) || 0;

      if (max == 0 || max == "") {
        $(this).val(0);
      }

      if (number > max) {
        $(this).val(max);
      }

      var total = 0;

      $('.debit_pay_money').each(function() { 

        total += parseFloat($(this).val().replace(/\,/g, ""));

        $('#payment_voucher_sum').val(total);
        $('#payment_voucher_money').val(total);

    });



      $('.numbers').val(function(index, value) {

          return value

            .replace(/\D/g, "")

            .replace(/\B(?=(\d{3})+(?!\d))/g, ",")

          ;

        });




    });




    $('.number').keyup(function(event) {



          // skip for arrow keys

      if(event.which >= 37 && event.which <= 40) return;



      // format number

      $(this).val(function(index, value) {

        return value

          .replace(/[^0-9-.]/g, "")

        ;

      });

    });

   

   $('.numbers').keyup(function(event) {



          // skip for arrow keys

      if(event.which >= 37 && event.which <= 40) return;



      // format number

      $(this).val(function(index, value) {

        return value

          .replace(/[^0-9]/g, "")

          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")

        ;

      });

    });





});

function get_number(id){

    return $(id).val().replace(/\,/g,'');

}

function set_item_customer(value,name) {

    // change input value

    $('#customer').val(name);

    $("#customer").attr("data",value);

    $("#customer").attr("code",'true');

    

    // hide proposition list

    $('#customer_list_id').hide();

    $('#customer').focus();

    $('.comment').val("");
    $('.comment').attr('data',"");
    $('.debit_date').val("");
    $('.money').val("");
    $('.money_conlai').val("");


    $(".numbers").val(function(index, value) {

      return value

        .replace(/\B(?=(\d{3})+(?!\d))/g, ",")

      ;

    }); 

}
function set_item_debit(value,name,ngay,phaithu,conlai,vitri) {

      // change input value

      $('.comment:eq('+vitri+')').val(name);

      $('.comment:eq('+vitri+')').attr("data",value);
      $('.debit_date:eq('+vitri+')').val(ngay);
      $('.money:eq('+vitri+')').val(phaithu);
      $('.money_conlai:eq('+vitri+')').val(conlai);

      var check = 0;
      $('.comment').each(function() { 

        if ($(this).attr('data').trim() == value) {
          check ++;
        }

    });

      if (check > 1) {
        alert('Đã tồn tại!');
        $('.comment:eq('+vitri+')').val("");

        $('.comment:eq('+vitri+')').attr("data","");
        $('.debit_date:eq('+vitri+')').val("");
        $('.money:eq('+vitri+')').val("");
        $('.money_conlai:eq('+vitri+')').val("");
      }

      // hide proposition list

      $('.name_list_id_3').hide();

      $('.comment:eq('+vitri+')').focus();

       $(".numbers").val(function(index, value) {

      return value

        .replace(/\B(?=(\d{3})+(?!\d))/g, ",")

      ;

    }); 

       

  }
</script>

<script type="text/javascript">



$( ".add-field" ).dialog({

    autoOpen: false,

    modal: true,

    width: "auto",

    title: "Chi tiền",

    hide: 'fold',

    show: 'blind'

});



</script>



<script type="text/javascript">

    $(function() {

    var pickerOpts = {

        closeText: "Đóng",

        currentText: "Hiện tại",

        nextText: "Tiếp",

        prevText: "Quay lại",

        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",

        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],

        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",

        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],

        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",

        "Thứ sáu", "Thứ bảy"],

        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",

        "T6", "T7"],

        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",

        "T6", "T7"],

        //defaultDate: "+1w",

        changeMonth: true,

        changeYear: true,

        dateFormat: 'dd-mm-yy',

        firstDay: 1,

        isRTL: false,

        showButtonPanel: true,

         

    };  

    $(".ngay").datepicker(pickerOpts);



    

              

            

    

});



</script>







<style type="text/css">

    #ui-datepicker-div{

        font-size: 13px;

    }

</style>

<script type="text/javascript">

    $(function() {

    var pickerOpts = {

        closeText: "Đóng",

        currentText: "Hiện tại",

        nextText: "Tiếp",

        prevText: "Quay lại",

        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",

        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],

        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",

        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],

        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",

        "Thứ sáu", "Thứ bảy"],

        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",

        "T6", "T7"],

        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",

        "T6", "T7"],

        //defaultDate: "+1w",

        changeMonth: true,

        changeYear: true,

        dateFormat: 'dd-mm-yy',

        firstDay: 1,

        isRTL: false,

        showButtonPanel: true,

        onClose: function(selectedDate) {

                

                $( "#ketthuc" ).datepicker( "option", "minDate", selectedDate );



         },

         

    };  

    $("#batdau").datepicker(pickerOpts);



    var pickerOpts4 = {

        closeText: "Đóng",

        currentText: "Hiện tại",

        nextText: "Tiếp",

        prevText: "Quay lại",

        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",

        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],

        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",

        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],

        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",

        "Thứ sáu", "Thứ bảy"],

        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",

        "T6", "T7"],

        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",

        "T6", "T7"],

        //defaultDate: "+1w",

        changeMonth: true,

        changeYear: true,

        dateFormat: 'dd-mm-yy',

        firstDay: 1,

        isRTL: false,

        showButtonPanel: true,

        onClose: function(selectedDate) {

                

                $( "#batdau" ).datepicker( "option", "maxDate", selectedDate );

                

         },

         

    };  

    $("#ketthuc").datepicker(pickerOpts4);

              

            

    

});



var ch = "<?php echo $limit ?>";

$('#chonloc option[value='+ch+']').attr('selected','selected');



var kh = "<?php echo $kh ?>";

$('#sl_status option[value='+kh+']').attr('selected','selected');



var v = "<?php echo $vong ?>";

$('#sl_round option[value='+v+']').attr('selected','selected');



var tt = "<?php echo $trangthai ?>";

$('#sl_staff option[value='+tt+']').attr('selected','selected');



</script>

<script type="text/javascript">

    

    $('#sl_round').change(function(){

        var m = $(this).val();

        var y = $('#sl_staff').val();

        var firstDay = new Date(y, m-1, 1);

        var lastDay = new Date(y, m, 0);



        $('#batdau').datepicker("setDate", firstDay );

        $('#ketthuc').datepicker("setDate", lastDay );



    });



    $('#sl_staff').change(function(){

        var y = $(this).val();

        var m = $('#sl_round').val();

        var firstDay = new Date(y, m-1, 1);

        var lastDay = new Date(y, m, 0);



        $('#batdau').datepicker("setDate", firstDay );

        $('#ketthuc').datepicker("setDate", lastDay );



    });





function addRow(tableID){

    var table=document.getElementById(tableID);

    var rowCount=table.rows.length;

    var row=table.insertRow(rowCount);

    var colCount=table.rows[0].cells.length;

    for(var i=0;i<colCount;i++){

        var newcell=row.insertCell(i);

        newcell.innerHTML=table.rows[0].cells[i].innerHTML;

        switch(newcell.childNodes[0].type){

            case"text":newcell.childNodes[0].value="";

            break;

            case"checkbox":newcell.childNodes[0].checked=false;

            break;

            case"select-one":newcell.childNodes[0].selectedIndex=0;

            break;

        }

    }



    $('.comment:last').val("");

    $('.comment:last').attr('data',"");

    $('.comment:last').attr('alt',"");

    $('.debit_date:last').val("");

    $('.money:last').val("");

    $('.money_conlai:last').val("");

    $('.debit_pay_money:last').val("");

    

    $('input[name="chk"]:last').attr('data',"");

    $('input[name="chk"]:last').attr('tabindex',0);

    $('input[name="chk"]:last').attr('title',(colCount-1));

    $('input[name="chk"]:last').attr('class',"");

    $('input[name="chk"]:last').attr('alt',0);


    $('.comment').keyup(function(){

        var row = $(this).parent().parent().parent().parent().parent().parent();

        var rowIndex = row[0].rowIndex;

        var type = $('input[name=customer_type]:checked').val();

        var customer = $('#customer').attr('data');

        var keyword = $(this).val();

        $.ajax({

            url: '<?php echo BASE_URL ?>/paymentvoucher/getDebit',

            type: 'POST',

            data: {keyword:keyword, offset:rowIndex, type:type, customer:customer},

            success:function(data){

                $('.name_list_id:eq('+rowIndex+')').slideDown(200);

                $('.name_list_id:eq('+rowIndex+')').html(data);

            }

        });

        if ($('.comment:eq('+rowIndex+')').val() == "" || $('.comment:eq('+rowIndex+')').attr('data') == "") {

            

            $('.comment:eq('+rowIndex+')').attr('data',"");

        }



        

    });



$('.comment').on('keydown', function() {

        var row = $(this).parent().parent().parent().parent().parent().parent();

        var rowIndex = row[0].rowIndex;



        var key = event.keyCode || event.charCode;



        if( key == 8 || key == 46 ){

            $('.comment:eq('+rowIndex+')').attr('data',"");

        }

            

      }); 

$('.debit_pay_money').keyup(function(){

      var row = $(this).parent().parent().parent().parent().parent().parent();

      var rowIndex = row[0].rowIndex;


      var number = parseFloat($(this).val().replace(/\,/g, ""));

      var max = parseFloat($('.money_conlai:eq('+rowIndex+')').val().replace(/\,/g, "")) || 0;

      if (max == 0 || max == "") {
        $(this).val(0);
      }

      if (number > max) {
        $(this).val(max);
      }


      var total = 0;

      $('.debit_pay_money').each(function() { 

        total += parseFloat($(this).val().replace(/\,/g, ""));

        $('#payment_voucher_sum').val(total);
        $('#payment_voucher_money').val(total);

    });



      

      $('.numbers').val(function(index, value) {

          return value

            .replace(/\D/g, "")

            .replace(/\B(?=(\d{3})+(?!\d))/g, ",")

          ;

        });




    });


    function get_number(id){

        return $(id).val().replace(/[^0-9\.-]+/g,"");

    }



    $('.number').keyup(function(event) {



          // skip for arrow keys

      if(event.which >= 37 && event.which <= 40) return;



      // format number

      $(this).val(function(index, value) {

        return value

          .replace(/[^0-9-.]/g, "")

        ;

      });

    });

   

   $('.numbers').keyup(function(event) {



          // skip for arrow keys

      if(event.which >= 37 && event.which <= 40) return;



      // format number

      $(this).val(function(index, value) {

        return value

          .replace(/[^0-9]/g, "")

          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")

        ;

      });

    });



   $('.number').focus(function(){

        if ( $(this).val() == '0') {

           $(this).val(""); 

        };

        

    });

    $('.number').blur(function(){

        if ( $(this).val() == "") {

            $(this).val(0);

        };

        

    });

    $('.numbers').focus(function(){

        if ( $(this).val() == '0') {

           $(this).val(""); 

        };

        

    });

    $('.numbers').blur(function(){

        if ( $(this).val() == "") {

            $(this).val(0);

        };

        

    });



}

function deleteRow(tableID){

    try{

        var table=document.getElementById(tableID);

        var rowCount=table.rows.length;



        var r = confirm("Bạn có chắc chắn không?");

        if (r == true){

            for(var i=0;i<rowCount;i++){

                var row=table.rows[i];

                var chkbox=row.cells[0].childNodes[0];

                if(null!=chkbox&&true==chkbox.checked){

                  if(rowCount<=1){

                        alert("Cannot delete all the rows.");

                        break;

                    }

                    else if(chkbox.getAttribute("data") > 0){

                        

                            var debit_pay_id = chkbox.getAttribute("data");

                            var payment_voucher = chkbox.getAttribute("alt");

                            $.post("<?php echo BASE_URL ?>/paymentvoucher/deletedebit", {payment_voucher: payment_voucher, debit_pay_id:debit_pay_id},

                               function(data){

                                //alert(data);

                               }); 

                        

                    }

                    

                    table.deleteRow(i);

                    rowCount--;

                    i--;

                    var total = 0;

                    $('.debit_pay_money').each(function() { 

                      total += parseFloat($(this).val().replace(/\,/g, ""));

                      $('#payment_voucher_sum').val(total);
                      $('#payment_voucher_money').val(total);

                  });

                    $('.numbers').val(function(index, value) {

                      return value

                        .replace(/\D/g, "")

                        .replace(/\B(?=(\d{3})+(?!\d))/g, ",")

                      ;

                    });

                }

            }

        }

    }

    catch(e){

        alert(e);

    }

}


jQuery(document).ready(function() {

    jQuery('.tabs .tab-links a').on('click', function(e)  {

        var currentAttrValue = jQuery(this).attr('href');



        var id = currentAttrValue.replace('#tab','');

        $('.tab_active').val(id);

        // Show/Hide Tabs

        jQuery('.tabs ' + currentAttrValue).addClass('active').siblings().removeClass('active');

        jQuery('.tabs ' + currentAttrValue).slideDown(300).siblings().slideUp(300);



 

        // Change/remove current tab to active

        jQuery(this).parent('li').addClass('active').siblings().removeClass('active');

 

        e.preventDefault();

    });



    jQuery('.tabs .tab-left a').on('click', function(e)  {

        var currentAttrValue = jQuery(this).attr('href');

 

        // Show/Hide Tabs

        jQuery('.tabs ' + currentAttrValue).addClass('active').siblings().removeClass('active');

        jQuery('.tabs ' + currentAttrValue).slideDown(300).siblings().slideUp(300);

 

        // Change/remove current tab to active

        jQuery(this).parent('li').addClass('active').siblings().removeClass('active');

 

        e.preventDefault();

    });

});
</script>

<style type="text/css">

.ui-multiselect-menu {

    z-index: 9999999;

}

</style>