
<?php
    $i = 1;
    $j = 1;
?>

<div id="loading"></div>
<div id="winpopup"></div>
<section class="content-header">
    <h1>QUÁ TRÌNH HOẠT ĐỘNG</h1>
  <ol class="breadcrumb">
    <li><a href="<?php echo $this->url('admin') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><a href="<?php echo $this->url('vehicleanalytics') ?>">Hoạt động</a></li>
  </ol>
</section>
<div id="content" style="padding:5px;">

    <div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">

        <div class="add-box">
                  
            Từ  <input style="width:80px" type="search" name="batdau" id="batdau" placeholder="Chọn ngày" <?php if(isset($batdau)) echo "value='$batdau'"; ?> >  
            Đến  <input style="width:80px" type="search" name="ketthuc" id="ketthuc" placeholder="Chọn ngày" <?php if(isset($ketthuc)) echo "value='$ketthuc'"; ?> >  
             <input type="button" name="xem" id="xem" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  
            
        </div>
    </div>
    <div class="tablenav top">
        
        <div style="clear:both"></div>
        
        <div class="add-box">
            <input type="button" name="chon" id="chon" value="Chọn" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  
        </div>

        <div class="add-box" style="margin-right: 5px">
            <select style="width:100px" name="sl_vehicle" id="sl_vehicle">
                <option selected="selected" value="0">Xe</option>
                <?php foreach ($vehicle_lists as $sm) { ?>
                <option value="<?php echo $sm->vehicle_id ?>"><?php echo $sm->vehicle_number ?></option>
                <?php } ?>
            </select>

            <select style="width:100px" name="sl_status" id="sl_status">
                <option selected="selected" value="0">Mooc</option>
                <?php foreach ($romooc_lists as $sm) { ?>
                <option value="<?php echo $sm->romooc_id ?>"><?php echo $sm->romooc_number ?></option>
                <?php } ?>
            </select>
            
        </div>
        <div style="clear:both"></div>
        <div class="add-box">
          <select name="sl_round" id="sl_round" style="width:150px" onChange="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
            <option value="0" >Tổng hợp chung</option>
            <option value="1" >Tổng hợp theo tháng</option>
          </select>
        </div>

      </div>

</div>
<?php if($xem == 0){ ?>
<div class="tabs">
  <ul class="tab-links">
    <li class="active"  ><a href="#tab1"><i class="fa fa-truck"></i> Đầu xe</a></li>
    <li ><a href="#tab2"><i class="fa fa-eraser"></i> Mooc</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab active" id="tab1" >
        <div class="add-box"><a class="add_button" id="btnExport" ><i class="fa fa-download"></i> Xuất</a></div>
        <table class="table_data" id="tblExport">
        <thead>
            <tr>
                <th class="fix">
                    <a>STT </a>
                </th>
                
                <th class="fix">
                    <a >Xe</a>
                </th>
                <th class="fix">
                    <a >Tổng số chuyến </a>
                </th>
                <th class="fix">
                    <a >Tổng km đã chạy </a>
                </th>
                <th class="fix">
                    <a >Tổng dầu sử dụng </a>
                </th>
                <th class="fix">
                    <a >Tổng doanh thu </a>
                </th>
            </tr>
            
           </thead>
           <tbody>
            <?php foreach ($vehicles as $vehicle) : ?>
            <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $vehicle->vehicle_id ?>" class="edit_tr">
                <td class="fix"><?php echo $i++; ?></td>
                <td class="fix" id="vehicle_number_<?php echo $vehicle->vehicle_id; ?>"><a target="_blank" href="<?php echo $this->url('vehicle/index/'.$vehicle->vehicle_id) ?>" ><?php echo $vehicle->vehicle_number ?></a></td>
                <td class="fix"><?php echo isset($data_vehicle[$vehicle->vehicle_id]['ship'])?$data_vehicle[$vehicle->vehicle_id]['ship']:null; ?></td>
                <td class="fix"><?php echo isset($data_vehicle[$vehicle->vehicle_id]['km'])?$data_vehicle[$vehicle->vehicle_id]['km']:null; ?></td>
                <td class="fix"><?php echo isset($data_vehicle[$vehicle->vehicle_id]['oil'])?$data_vehicle[$vehicle->vehicle_id]['oil']:null; ?></td>
                <td class="fix"><?php echo $lib->formatMoney(isset($data_vehicle[$vehicle->vehicle_id]['revenue'])?$data_vehicle[$vehicle->vehicle_id]['revenue']:null); ?></td>
            </tr>
            
            <?php endforeach; ?>
           </tbody>
        </table>
    </div>
    <div class="tab" id="tab2" >
        <div class="add-box"><a class="add_button" id="btnExport2" ><i class="fa fa-download"></i> Xuất</a></div>
            <table class="table_data" id="tblExport2">
            <thead>
                <tr>
                    <th class="fix">
                        <a>STT </a>
                    </th>
                    
                    <th class="fix">
                        <a >Mooc</a>
                    </th>
                    <th class="fix">
                        <a >Tổng số chuyến </a>
                    </th>
                    <th class="fix">
                        <a >Tổng km đã chạy </a>
                    </th>
                    <th class="fix">
                        <a >Tổng doanh thu </a>
                    </th>
                    
                    
                </tr>
                
               </thead>
               <tbody>
                <?php foreach ($romoocs as $romooc) : ?>
                <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $romooc->romooc_id ?>" class="edit_tr">
                    <td class="fix"><?php echo $j++; ?></td>
                    <td class="fix" id="romooc_number_<?php echo $romooc->romooc_id; ?>"><a target="_blank" href="<?php echo $this->url('romooc/index/'.$romooc->romooc_id) ?>" ><?php echo $romooc->romooc_number ?></a></td>
                    <td class="fix"><?php echo isset($data_romooc[$romooc->romooc_id]['ship'])?$data_romooc[$romooc->romooc_id]['ship']:null; ?></td>
                    <td class="fix"><?php echo isset($data_romooc[$romooc->romooc_id]['km'])?$data_romooc[$romooc->romooc_id]['km']:null; ?></td>
                    <td class="fix"><?php echo $lib->formatMoney(isset($data_romooc[$romooc->romooc_id]['revenue'])?$data_romooc[$romooc->romooc_id]['revenue']:null); ?></td>
                </tr>
                
                <?php endforeach; ?>
               </tbody>
            </table>
        </div>
    </div>
</div>
<?php }else{ ?>
<div class="tabs">
  <ul class="tab-links">
    <li class="active"  ><a href="#tab1"><i class="fa fa-truck"></i> Đầu xe</a></li>
    <li ><a href="#tab2"><i class="fa fa-eraser"></i> Mooc</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab active" id="tab1" >
        <div class="add-box"><a class="add_button" id="btnExport" ><i class="fa fa-download"></i> Xuất</a></div>
        <table class="table_data" id="tblExport">
        <thead>
            <tr>
                <th rowspan="2" class="fix">
                    <a>STT </a>
                </th>
                
                <th rowspan="2" class="fix">
                    <a >Xe</a>
                </th>
                <th colspan="<?php echo $numberMonth+1 ?>" class="fix">
                    <a >Số chuyến </a>
                </th>
                <th colspan="<?php echo $numberMonth+1 ?>" class="fix">
                    <a >Km đã chạy </a>
                </th>
                <th colspan="<?php echo $numberMonth+1 ?>" class="fix">
                    <a >Dầu sử dụng </a>
                </th>
                <th colspan="<?php echo $numberMonth+1 ?>" class="fix">
                    <a >Doanh thu </a>
                </th>
            </tr>
            <tr>
                <?php
                $thang = (int)date('m',strtotime($batdau));
                $nam = date('Y',strtotime($batdau));
                for ($m=$thang; $m <= $countMonth; $m++) { 
                    $thang = $m;
                        if ($thang == 13) {
                            $thang = 1;
                            $nam ++;
                        }
                ?>
                <th class="fix">
                    <a ><?php echo $thang ?></a>
                </th>
                <?php } ?>
                <?php
                $thang = (int)date('m',strtotime($batdau));
                $nam = date('Y',strtotime($batdau));
                for ($m=$thang; $m <= $countMonth; $m++) { 
                    $thang = $m;
                        if ($thang == 13) {
                            $thang = 1;
                            $nam ++;
                        }
                ?>
                <th class="fix">
                    <a ><?php echo $thang ?></a>
                </th>
                <?php } ?>
                <?php
                $thang = (int)date('m',strtotime($batdau));
                $nam = date('Y',strtotime($batdau));
                for ($m=$thang; $m <= $countMonth; $m++) { 
                    $thang = $m;
                        if ($thang == 13) {
                            $thang = 1;
                            $nam ++;
                        }
                ?>
                <th class="fix">
                    <a ><?php echo $thang ?></a>
                </th>
                <?php } ?>
                <?php
                $thang = (int)date('m',strtotime($batdau));
                $nam = date('Y',strtotime($batdau));
                for ($m=$thang; $m <= $countMonth; $m++) { 
                    $thang = $m;
                        if ($thang == 13) {
                            $thang = 1;
                            $nam ++;
                        }
                ?>
                <th class="fix">
                    <a ><?php echo $thang ?></a>
                </th>
                <?php } ?>
            </tr>
            
           </thead>
           <tbody>
            <?php foreach ($vehicles as $vehicle) : ?>
            <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $vehicle->vehicle_id ?>" class="edit_tr">
                <td class="fix"><?php echo $i++; ?></td>
                <td class="fix" id="vehicle_number_<?php echo $vehicle->vehicle_id; ?>"><a target="_blank" href="<?php echo $this->url('vehicle/index/'.$vehicle->vehicle_id) ?>" ><?php echo $vehicle->vehicle_number ?></a></td>
                <?php
                $thang = (int)date('m',strtotime($batdau));
                $nam = date('Y',strtotime($batdau));
                for ($m=$thang; $m <= $countMonth; $m++) { 
                    $thang = $m;
                        if ($thang == 13) {
                            $thang = 1;
                            $nam ++;
                        }
                ?>
                <td class="fix"><?php echo isset($data_vehicle[$vehicle->vehicle_id]['ship'][$thang.'-'.$nam])?$data_vehicle[$vehicle->vehicle_id]['ship'][$thang.'-'.$nam]:null; ?></td>
                <?php } ?>
                <?php
                $thang = (int)date('m',strtotime($batdau));
                $nam = date('Y',strtotime($batdau));
                for ($m=$thang; $m <= $countMonth; $m++) { 
                    $thang = $m;
                        if ($thang == 13) {
                            $thang = 1;
                            $nam ++;
                        }
                ?>
                <td class="fix"><?php echo isset($data_vehicle[$vehicle->vehicle_id]['km'][$thang.'-'.$nam])?$data_vehicle[$vehicle->vehicle_id]['km'][$thang.'-'.$nam]:null; ?></td>
                <?php } ?>
                <?php
                $thang = (int)date('m',strtotime($batdau));
                $nam = date('Y',strtotime($batdau));
                for ($m=$thang; $m <= $countMonth; $m++) { 
                    $thang = $m;
                        if ($thang == 13) {
                            $thang = 1;
                            $nam ++;
                        }
                ?>
                <td class="fix"><?php echo isset($data_vehicle[$vehicle->vehicle_id]['oil'][$thang.'-'.$nam])?$data_vehicle[$vehicle->vehicle_id]['oil'][$thang.'-'.$nam]:null; ?></td>
                <?php } ?>
                <?php
                $thang = (int)date('m',strtotime($batdau));
                $nam = date('Y',strtotime($batdau));
                for ($m=$thang; $m <= $countMonth; $m++) { 
                    $thang = $m;
                        if ($thang == 13) {
                            $thang = 1;
                            $nam ++;
                        }
                ?>
                <td class="fix"><?php echo $lib->formatMoney(isset($data_vehicle[$vehicle->vehicle_id]['revenue'][$thang.'-'.$nam])?$data_vehicle[$vehicle->vehicle_id]['revenue'][$thang.'-'.$nam]:null); ?></td>
                <?php } ?>
            </tr>
            
            <?php endforeach; ?>
           </tbody>
        </table>
    </div>
    <div class="tab" id="tab2" >
        <div class="add-box"><a class="add_button" id="btnExport2" ><i class="fa fa-download"></i> Xuất</a></div>
            <table class="table_data" id="tblExport2">
            <thead>
                <tr>
                    <th rowspan="2" class="fix">
                        <a>STT </a>
                    </th>
                    
                    <th rowspan="2" class="fix">
                        <a >Mooc</a>
                    </th>
                    <th colspan="<?php echo $numberMonth+1 ?>" class="fix">
                        <a >Số chuyến </a>
                    </th>
                    <th colspan="<?php echo $numberMonth+1 ?>" class="fix">
                        <a >Km đã chạy </a>
                    </th>
                    <th colspan="<?php echo $numberMonth+1 ?>" class="fix">
                        <a >Doanh thu </a>
                    </th>
                </tr>
                <tr>
                    <?php
                    $thang = (int)date('m',strtotime($batdau));
                    $nam = date('Y',strtotime($batdau));
                    for ($m=$thang; $m <= $countMonth; $m++) { 
                        $thang = $m;
                            if ($thang == 13) {
                                $thang = 1;
                                $nam ++;
                            }
                    ?>
                    <th class="fix">
                        <a ><?php echo $thang ?></a>
                    </th>
                    <?php } ?>
                    <?php
                    $thang = (int)date('m',strtotime($batdau));
                    $nam = date('Y',strtotime($batdau));
                    for ($m=$thang; $m <= $countMonth; $m++) { 
                        $thang = $m;
                            if ($thang == 13) {
                                $thang = 1;
                                $nam ++;
                            }
                    ?>
                    <th class="fix">
                        <a ><?php echo $thang ?></a>
                    </th>
                    <?php } ?>
                    <?php
                    $thang = (int)date('m',strtotime($batdau));
                    $nam = date('Y',strtotime($batdau));
                    for ($m=$thang; $m <= $countMonth; $m++) { 
                        $thang = $m;
                            if ($thang == 13) {
                                $thang = 1;
                                $nam ++;
                            }
                    ?>
                    <th class="fix">
                        <a ><?php echo $thang ?></a>
                    </th>
                    <?php } ?>
                    
                </tr>
                
               </thead>
               <tbody>
                <?php foreach ($romoocs as $romooc) : ?>
                <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $romooc->romooc_id ?>" class="edit_tr">
                    <td class="fix"><?php echo $j++; ?></td>
                    <td class="fix" id="romooc_number_<?php echo $romooc->romooc_id; ?>"><a target="_blank" href="<?php echo $this->url('romooc/index/'.$romooc->romooc_id) ?>" ><?php echo $romooc->romooc_number ?></a></td>
                    <?php
                    $thang = date('m',strtotime($batdau));
                    $nam = date('Y',strtotime($batdau));
                    for ($m=$thang; $m <= $countMonth; $m++) { 
                        $thang = $m;
                        if ($thang == 13) {
                            $thang = 1;
                            $nam ++;
                        }
                    ?>
                    <td class="fix"><?php echo isset($data_romooc[$romooc->romooc_id]['ship'][$thang.'-'.$nam])?$data_romooc[$romooc->romooc_id]['ship'][$thang.'-'.$nam]:null; ?></td>
                    <?php } ?>
                    <?php
                    $thang = date('m',strtotime($batdau));
                    $nam = date('Y',strtotime($batdau));
                    for ($m=$thang; $m <= $countMonth; $m++) { 
                        $thang = $m;
                        if ($thang == 13) {
                            $thang = 1;
                            $nam ++;
                        }
                    ?>
                    <td class="fix"><?php echo isset($data_romooc[$romooc->romooc_id]['km'][$thang.'-'.$nam])?$data_romooc[$romooc->romooc_id]['km'][$thang.'-'.$nam]:null; ?></td>
                    <?php } ?>
                    <?php
                    $thang = date('m',strtotime($batdau));
                    $nam = date('Y',strtotime($batdau));
                    for ($m=$thang; $m <= $countMonth; $m++) { 
                        $thang = $m;
                        if ($thang == 13) {
                            $thang = 1;
                            $nam ++;
                        }
                    ?>
                    <td class="fix"><?php echo $lib->formatMoney(isset($data_romooc[$romooc->romooc_id]['revenue'][$thang.'-'.$nam])?$data_romooc[$romooc->romooc_id]['revenue'][$thang.'-'.$nam]:null); ?></td>
                    <?php } ?>
                </tr>
                
                <?php endforeach; ?>
               </tbody>
            </table>
        </div>
    </div>
</div>
<?php } ?>

<style type="text/css">
.table_data td {
    vertical-align: middle;
    text-align: center;
}
</style>


<style type="text/css">
    .ui-dialog .ui-dialog-content{
        padding: 3px;
    }

    .showtooltip {
        display:none;
        position:absolute;
        border:1px solid #333;
        background-color:#161616;
        border-radius:5px;
        padding:10px;
        color:#fff;
        font-size:12px Arial;
    }
    
    .ok{
        color: green;
        float: right;
    }
    .no{
        color: red;
    }


.table_data td {
    font-size: 13px;
}
.ui-front {
  z-index: 1031;
}

</style>



<style type="text/css">
    #ui-datepicker-div{
        font-size: 13px;
    }
</style>
<script type="text/javascript">
    $(function() {
    var pickerOpts = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#ketthuc" ).datepicker( "option", "minDate", selectedDate );

         },
         
    };  
    $("#batdau").datepicker(pickerOpts);

    var pickerOpts4 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#batdau" ).datepicker( "option", "maxDate", selectedDate );
                
         },
         
    };  
    $("#ketthuc").datepicker(pickerOpts4);
              
            
    
});

var x = "<?php echo $xe ?>";
$('#sl_vehicle option[value='+x+']').attr('selected','selected');

var m = "<?php echo $mooc ?>";
$('#sl_status option[value='+m+']').attr('selected','selected');

var t = "<?php echo $xem ?>";
$('#sl_round option[value='+t+']').attr('selected','selected');

$(document).ready(function () {
    $("#btnExport2").click(function () {
        $("#tblExport2").battatech_excelexport({
            containerid: "tblExport2"
           , datatype: 'table'
        });
    });
});


jQuery(document).ready(function() {
    jQuery('.tabs .tab-links a').on('click', function(e)  {
        var currentAttrValue = jQuery(this).attr('href');

        var id = currentAttrValue.replace('#tab','');
        $('.tab_active').val(id);
        // Show/Hide Tabs
        jQuery('.tabs ' + currentAttrValue).addClass('active').siblings().removeClass('active');
        jQuery('.tabs ' + currentAttrValue).slideDown(300).siblings().slideUp(300);

 
        // Change/remove current tab to active
        jQuery(this).parent('li').addClass('active').siblings().removeClass('active');
 
        e.preventDefault();
    });

    jQuery('.tabs .tab-left a').on('click', function(e)  {
        var currentAttrValue = jQuery(this).attr('href');
 
        // Show/Hide Tabs
        jQuery('.tabs ' + currentAttrValue).addClass('active').siblings().removeClass('active');
        jQuery('.tabs ' + currentAttrValue).slideDown(300).siblings().slideUp(300);
 
        // Change/remove current tab to active
        jQuery(this).parent('li').addClass('active').siblings().removeClass('active');
 
        e.preventDefault();
    });
});
</script>
