<script type="text/javascript">
$(document).ready(function(){
	$( ".select2" ).select2({dropdownAutoWidth : true});
			// Validate form
			$("#add_warehouse").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
        ignore: "",
        rules: {
        },
        errorPlacement: function (error, element) {
          if(element.is('input[type=checkbox]') || element.is('input[type=radio]')) {
            var controls = element.closest('div[class*="col-"]');
            if(controls.find(':checkbox,:radio').length > 1) controls.append(error);
            else error.insertAfter(element.nextAll('.lbl:eq(0)').eq(0));
          }
          else if(element.is('.select2')) {
            error.insertAfter(element.siblings('[class*="select2-container"]:eq(0)'));
          }
          else if(element.is('.chosen-select')) {
            error.insertAfter(element.siblings('[class*="chosen-container"]:eq(0)'));
          }
          else error.insertAfter(element.parent());
        },
        submitHandler: function(form) {
                
          var formData = new FormData($("#add_warehouse")[0]);
          
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/warehouse/addwarehouse", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: formData, // giá trị post
              cache: false,
              contentType: false,
              processData: false,
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error_warehouse').hide();
                  $('#error_warehouse').slideToggle(100); // hiển thị thẻ div success
                  $('#error_warehouse').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error_warehouse').fadeOut(10000);

              }
          });
          return false;
           
       }
					 
				 
			});

    $('#warehouse_add').keyup(function(){
        sum_cost();
    });
    $('#warehouse_weight').keyup(function(){
        sum_cost();
    });
    $('#warehouse_clean').keyup(function(){
        sum_cost();
    });
    $('#warehouse_gate').keyup(function(){
        sum_cost();
    });

	
});

function sum_cost(){
  $('#warehouse_cont').val(parseFloat(get_number('#warehouse_add') || 0) + parseFloat(get_number('#warehouse_clean') || 0) + parseFloat(get_number('#warehouse_weight') || 0) + parseFloat(get_number('#warehouse_gate') || 0) );

  $('#warehouse_cont').inputmask("numeric", {
    radixPoint: ".",
    groupSeparator: ",",
    digits: 6,
    autoGroup: true,
    rightAlign: true,
    oncleared: function () { self.Value(''); }
  });
}
function get_number(id){
    return $(id).val().replace(/\,/g,'');
}
</script>

<div id="error_warehouse" class="error"><?php echo isset($error) ? $error : null; ?></div>     
<div class="login_body">
  
    <form id="add_warehouse" method="post" action="" autocomplete="off">
      <div class="col-md-4 col-xs-6">
        <label for="warehouse_place">Kho hàng <a title="Thêm kho hàng mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("place/add") ?>','Thêm kho hàng mới','warehouse_place','<?php echo $this->url("place/getplace") ?>','add_place')"></i></a></label>
        <div class="input-group">
          <select class="form-control select2" id="warehouse_place" name="warehouse_place" required="required" tabindex="1">
            <?php foreach ($places as $place) { ?>
              <option value="<?php echo $place->place_id ?>"><?php echo $place->place_name ?></option>
            <?php } ?>
          </select>
        </div>
        <label for="warehouse_cont">Bồi dưỡng cont</label>
        <div class="input-group">
          <input class="form-control numbers" type="text" id="warehouse_cont" name="warehouse_cont" tabindex="2" readonly >
        </div>
        <label for="warehouse_ton">Bồi dưỡng tấn</label>
        <div class="input-group">
          <input class="form-control numbers" type="text" id="warehouse_ton" name="warehouse_ton" tabindex="3">
        </div>
        
     </div>
     <div class="col-md-4 col-xs-6">
        <label for="warehouse_add">Bồi dưỡng</label>
        <div class="input-group">
          <input class="form-control numbers" type="text" id="warehouse_add" name="warehouse_add" tabindex="4">
        </div>
        <label for="warehouse_weight">Cân xe</label>
        <div class="input-group">
          <input class="form-control numbers" type="text" id="warehouse_weight" name="warehouse_weight" tabindex="5">
        </div>
        <label for="warehouse_start_date">Ngày áp dụng</label>
        <div class="input-group">
          <input class="form-control start-date" type="text" id="warehouse_start_date" name="warehouse_start_date" required="required" tabindex="8">
        </div>
     </div>
     <div class="col-md-4 col-xs-6">
        <label for="warehouse_clean">Quét cont</label>
        <div class="input-group">
          <input class="form-control numbers" type="text" id="warehouse_clean" name="warehouse_clean" tabindex="6">
        </div>
        <label for="warehouse_gate">Vé cổng</label>
        <div class="input-group">
          <input class="form-control numbers" type="text" id="warehouse_gate" name="warehouse_gate" tabindex="7">
        </div>
        <label for="warehouse_end_date">Ngày hết hạn</label>
        <div class="input-group">
          <input class="form-control end-date" type="text" id="warehouse_end_date" name="warehouse_end_date" tabindex="9">
        </div>
     </div>
     
  </form>
</div>



