
<div id="error_warehouse" class="error"><?php echo isset($error) ? $error : null; ?></div>     
<div class="login_body">
  
      <div class="col-md-4 col-xs-6">
        <label for="warehouse_place">Kho hàng <a href="#" title="Thêm kho hàng mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("place/add") ?>','Thêm kho hàng mới','warehouse_place','<?php echo $this->url("place/getplace") ?>','add_place')"></i></a></label>
        <div class="input-group">
          <select class="form-control select2" id="warehouse_place" name="warehouse_place" required="required" tabindex="1">
            <?php foreach ($places as $place) { ?>
              <option value="<?php echo $place->place_id ?>" <?php echo $warehouse_data->warehouse_place==$place->place_id?'selected="selected"':null ?>><?php echo $place->place_name ?></option>
            <?php } ?>
          </select>
        </div>
        <label for="warehouse_cont">Bồi dưỡng cont</label>
        <div class="input-group">
          <input class="form-control numbers" type="text" id="warehouse_cont" name="warehouse_cont" tabindex="2" readonly value="<?php echo $lib->formatMoney($warehouse_data->warehouse_cont) ?>">
        </div>
        <label for="warehouse_ton">Bồi dưỡng tấn</label>
        <div class="input-group">
          <input class="form-control numbers" type="text" id="warehouse_ton" name="warehouse_ton" tabindex="3" value="<?php echo $lib->formatMoney($warehouse_data->warehouse_ton) ?>">
        </div>
        
     </div>
     <div class="col-md-4 col-xs-6">
        <label for="warehouse_add">Bồi dưỡng</label>
        <div class="input-group">
          <input class="form-control numbers" type="text" id="warehouse_add" name="warehouse_add" tabindex="4" value="<?php echo $lib->formatMoney($warehouse_data->warehouse_add) ?>">
        </div>
        <label for="warehouse_weight">Cân xe</label>
        <div class="input-group">
          <input class="form-control numbers" type="text" id="warehouse_weight" name="warehouse_weight" tabindex="5" value="<?php echo $lib->formatMoney($warehouse_data->warehouse_weight) ?>">
        </div>
        <label for="warehouse_start_date">Ngày áp dụng</label>
        <div class="input-group">
          <input class="form-control start-date" type="text" id="warehouse_start_date" name="warehouse_start_date" required="required" tabindex="8" value="<?php echo $lib->hien_thi_ngay_thang($warehouse_data->warehouse_start_date) ?>">
        </div>
     </div>
     <div class="col-md-4 col-xs-6">
        <label for="warehouse_clean">Quét cont</label>
        <div class="input-group">
          <input class="form-control numbers" type="text" id="warehouse_clean" name="warehouse_clean" tabindex="6" value="<?php echo $lib->formatMoney($warehouse_data->warehouse_clean) ?>">
        </div>
        <label for="warehouse_gate">Vé cổng</label>
        <div class="input-group">
          <input class="form-control numbers" type="text" id="warehouse_gate" name="warehouse_gate" tabindex="7" value="<?php echo $lib->formatMoney($warehouse_data->warehouse_gate) ?>">
        </div>
        <label for="warehouse_end_date">Ngày hết hạn</label>
        <div class="input-group">
          <input class="form-control end-date" type="text" id="warehouse_end_date" name="warehouse_end_date" tabindex="9" value="<?php echo $lib->hien_thi_ngay_thang($warehouse_data->warehouse_end_date) ?>">
        </div>
     </div>
     
</div>



