
<link rel="stylesheet" type="text/css" href="<?php BASE_URL ?>/public/css/jquery.multiselect.css" />

<script type="text/javascript" src="<?php BASE_URL ?>/public/js/jquery.multiselect.js"></script>

<script src="<?php echo BASE_URL ?>/public/js/jquery.maskedinput.js" type="text/javascript" charset="utf-8"></script>

<?php

$url_order = 'ASC';

if ($order_by == 'shipment_list_id')

    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';



elseif ($order_by == 'shipment_list_date')

    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

elseif ($order_by == 'shipment_list_number')

    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

elseif ($order_by == 'customer_name')

    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';





    $ii = $sonews*$page-($sonews-1);



?>



<div id="loading"></div>

<div id="winpopup"></div>

<section class="content-header">

    <h1>BẢNG KÊ</h1>

  <ol class="breadcrumb">

    <li><a href="<?php echo $this->url('admin') ?>"><i class="fa fa-dashboard"></i> Home</a></li>

    <li class="active"><a href="<?php echo $this->url('shipmentlist') ?>">Bảng kê</a></li>

  </ol>

</section>

<div id="content" style="padding:5px;">



    <div class="search-box">

        

        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">

        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">

        <?php if(!isset($disable_control)){ ?>

        <div class="add-box"><a class="add_button" id="btnExport" ><i class="fa fa-download"></i> Xuất</a></div>

        <div class="add-box"><a class="add_button" onClick="add_click();"><i class="fa fa-plus"></i> Thêm mới</a></div>

        <?php } ?>

    </div>

    <div class="tablenav top">

        <div class="add-box">

            <select id="sl_round" name="sl_round" style="width:90px">

             <?php 

                for ($k=1; $k < 13; $k++) { 

                    echo '<option value="'.$k.'">Tháng '.$k.'</option>';

                }

             ?>

            </select>

            <select id="sl_staff" name="sl_staff" style="width:100px">

             <?php 

                $nam = date('Y');

                for ($k=($nam-5); $k < ($nam+5); $k++) { 

                    echo '<option value="'.$k.'">Năm '.$k.'</option>';

                }

             ?>

            </select>



            <input type="button" name="xem" id="xem" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  

            

        </div>

    </div>

    <div class="tablenav top">

        <div style="clear:both"></div>

        <div class="add-box">

                  

            Từ  <input style="width:80px" type="search" name="batdau" id="batdau" placeholder="Chọn ngày" <?php if(isset($batdau)) echo "value='$batdau'"; ?> >  

            Đến  <input style="width:80px" type="search" name="ketthuc" id="ketthuc" placeholder="Chọn ngày" <?php if(isset($ketthuc)) echo "value='$ketthuc'"; ?> >  

             <input type="button" name="xem" id="xem" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  

            

        </div>



      </div>

      <div class="tablenav top">

        <div style="clear:both"></div>

        

        <div class="add-box">

            <input type="button" name="chon" id="chon" value="Chọn" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  

        </div>

        

        <div class="add-box" style="margin-right: 5px">


            <select style="width:120px" name="sl_nv" id="sl_nv">

                <option value="0">Khách hàng</option>

                <?php foreach ($customers as $sm) { ?>

                <option value="<?php echo $sm->customer_id ?>"><?php echo $sm->customer_name ?></option>

                <?php } ?>

            </select>



            

            

        </div>

        <?php if(!isset($disable_control)){ ?>

        <div class="alignleft actions">

            <select name="action" id="action">

                <option value="-1" selected="selected">Chọn</option>

                

                <option value="delete">Xóa</option>

            </select>

            <input type="button" name="" id="doaction" class="button action" value="Áp dụng" onclick="action();">

        </div>

        <?php } ?>

        <div class="alignleft actions">

        <select name="m" id="chonloc" style="width:200px">

            <option value="18446744073709">Hiển thị tất cả</option>

            <option value="50">Hiển thị 50 giá trị</option>

            <option value="100">Hiển thị 100 giá trị</option>

            <option value="150">Hiển thị 150 giá trị</option>

            <option value="200">Hiển thị 200 giá trị</option>

            <option selected="selected" value="250">Hiển thị 250 giá trị</option>

        </select>

        <input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">                               

        </div>



      </div>

</div>





<table class="table_data" id="tblExport">

<thead>

    <tr>

    	<th class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>

        <th  class="fix" >

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','shipment_list_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'shipment_list_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>

        

        <th  class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','shipment_list_date','<?php echo $url_order ?>')">Ngày <?php if ($order_by == 'shipment_list_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>

        <th  class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','shipment_list_number','<?php echo $url_order ?>')">Bảng kê số <?php if ($order_by == 'shipment_list_number'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>

        <th  class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer_name','<?php echo $url_order ?>')">Khách hàng <?php if ($order_by == 'customer_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>

        <th  class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','shipment_list_price','<?php echo $url_order ?>')">Giá trị <?php if ($order_by == 'shipment_list_price'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>

        <?php if(!isset($disable_control)){ ?>

           

        <th  class="fix">&nbsp;</th>

        <?php } ?>

    </tr>

    

   </thead>

   <tbody>

    <?php foreach ($shipment_lists as $shipment_list) : ?>

    

        

        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $shipment_list->shipment_list_id ?>" class="edit_tr">

        	<td><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $shipment_list->shipment_list_id ?>"></td>

            <td  class="fix"><?php echo $ii++; ?></td>

            <td class="fix" id="shipment_list_date_<?php echo $shipment_list->shipment_list_id; ?>"><?php echo $lib->hien_thi_ngay_thang($shipment_list->shipment_list_date); ?></td>

            <td class="fix" id="shipment_list_number_<?php echo $shipment_list->shipment_list_id; ?>"><?php echo $shipment_list->shipment_list_number; ?></td>

            <td class="fix" data="<?php echo $shipment_list->customer; ?>" id="customer_<?php echo $shipment_list->shipment_list_id; ?>"><?php echo $shipment_list->customer_name; ?></td>

            <td class="fix" id="shipment_list_price_<?php echo $shipment_list->shipment_list_id; ?>"><?php echo $lib->formatMoney($shipment_list->shipment_list_price); ?></td>

            <td class="fix" style="display:none" id="start_time_<?php echo $shipment_list->shipment_list_id; ?>"><?php echo $lib->hien_thi_ngay_thang($shipment_list->start_time); ?></td>
            <td class="fix" style="display:none" id="end_time_<?php echo $shipment_list->shipment_list_id; ?>"><?php echo $lib->hien_thi_ngay_thang($shipment_list->end_time); ?></td>
            <td class="fix" style="display:none"  id="start_work_<?php echo $shipment_list->shipment_list_id; ?>"><?php echo date('H:i:s',$shipment_list->start_work); ?></td>
            <td class="fix" style="display:none"  id="end_work_<?php echo $shipment_list->shipment_list_id; ?>"><?php echo date('H:i:s',$shipment_list->end_work); ?></td>
            <td class="fix" style="display:none" id="shipment_<?php echo $shipment_list->shipment_list_id; ?>"><?php echo $shipment_list->shipment; ?></td>
            <td class="fix" style="display:none" id="customer_type_<?php echo $shipment_list->shipment_list_id; ?>"><?php echo $shipment_list->customer_type; ?></td>

            <?php if(!isset($disable_control)){ ?>

            <td class="pull-right">

                <button class="btn btn-sm btn-flat btn-primary"><i class="fa fa-edit"></i> Sửa</button>

                <button class="btn btn-sm btn-flat btn-danger" onclick="del(<?php echo $shipment_list->shipment_list_id ?>)" ><i class="fa fa-remove"></i> Xóa</button>

            </td>

            <?php } ?>

        </tr>



    <?php endforeach; ?>

        

   </tbody>

</table>

<?php

$this->helper('slidePaginator');

?>

<div id="show_shipment"></div>


<div class="add-field">

    <section class="content">

      <div class="row">

        <!-- left column -->

        <div class="col-md-12">

          <!-- general form elements -->

          <div class="box box-primary">

            <!-- /.box-header -->

            <!-- form start -->

            <form id="add_shipment_list" role="form" method="post" action="" enctype="multipart/form-data">

              <div class="row">

                <div class="col-md-4 col-xs-6">

                  <div class="box-body">

                    <div class="form-group">

                      <label for="shipment_list_date">Ngày</label>

                      <input class="ngay" type="text" id="shipment_list_date"  name="shipment_list_date" tabindex="1" required="required" >

                    </div>

                    
                    <div class="form-group">

                      <label for="start_time">Từ ngày</label>

                      <input style="width:80px" type="text" id="start_time"  name="start_time" required="required" tabindex="5" >

                      <input style="width:50px" type="text" class="time" id="start_work" name="start_work" required="required" tabindex="6" />

                    </div>


                  </div>

                  <!-- /.box-body -->

                  

                </div>

                <div class="col-md-4 col-xs-6">

                  <div class="box-body">

                    <div class="form-group">

                      <label for="shipment_list_number">Bảng kê số</label>

                      <input type="text" id="shipment_list_number"  name="shipment_list_number" tabindex="2" required="required" >

                    </div>


                    <div class="form-group">

                      <label for="end_time">Đến ngày</label>

                      <input style="width:80px" type="text" id="end_time"  name="end_time" required="required" tabindex="7" >

                      <input style="width:50px" type="text" class="time" id="end_work" name="end_work" required="required" tabindex="8" />

                    </div>
                    

                  </div>

                  <!-- /.box-body -->

                  

                </div>

                <div class="col-md-4 col-xs-6">

                  <div class="box-body">

                    <div class="form-group">

                      <label for="customer">Khách hàng <a target="_blank" title="Thêm khách hàng" href="<?php echo $this->url('customer') ?>"><i class="fa fa-plus"></i></a></label>

                      <input type="text" autocomplete="off" id="customer"  name="customer" tabindex="3"  placeholder="Nhập tên hoặc * để chọn" required="required" >

                        <ul id="customer_list_id"></ul>

                    </div>

                    <div class="form-group">

                      <label for="customer_type">Mặt hàng</label>

                      <select style="width:180px" id="customer_type"  name="customer_type" tabindex="4" required="required" multiple ></select>

                    </div>



                  </div>

                  <!-- /.box-body -->

                  

                </div>

                <div class="col-md-12 col-xs-12">

                  <div class="box-body">


                    <div class="form-group">
                      <button id="show_shipment_list" type="button" class="btn btn-block" tabindex="9">Chọn chuyến hàng (0)</button>
                    </div>


                  </div>

                  <!-- /.box-body -->

                  

                </div>
                <div class="col-md-4 col-xs-6">

                  <div class="box-body">

                    <div class="form-group">

                      <label for="shipment_list_price">Tổng cộng</label>

                      <input type="text" class="numbers" id="shipment_list_price"  name="shipment_list_price" disabled >
                      <input type="hidden"  id="shipment"  name="shipment" >

                    </div>


                  </div>

                  <!-- /.box-body -->

                  

                </div>



              </div>

              

              <?php if(!isset($disable_control)){ ?>

              <div class="row">

                <div class="col-md-12">

                    <div class="box-footer">

                    <input type="hidden" readonly id="yes" name="yes" required="required" >

                    <button type="submit" class="btn btn-primary" tabindex="10">Hoàn thành</button>

                    <button type="reset" class="btn" tabindex="11">Nhập lại</button>

                  </div>

                  <div class="box-footer">

                    <div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>

                  </div>

                </div>

              </div>

              <?php } ?>

            </form>

          </div>

          <!-- /.box -->



        </div>

        <!--/.col (left) -->

        

      </div>

      <!-- /.row -->

    </section>

    <!-- /.content -->

       

</div>



<script type="text/javascript">

$('html').click(function(e) {

    $('#customer_list_id').slideUp(200);

});



    $('.edit_tr').click(function(e){

        if(!$('.checkbox').is(':focus') && e.target.nodeName != "A"){

            if(!$('.checkbox').is(':focus')){

                $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);

            }

            var shipment_list_number = $(this).find("#shipment_list_number_"+$(this).attr('id')).text();

            var shipment_list_price = $(this).find("#shipment_list_price_"+$(this).attr('id')).text();

            var customer_name = $(this).find("#customer_"+$(this).attr('id')).text();

            var customer = $(this).find("#customer_"+$(this).attr('id')).attr('data');

            var shipment_list_date = $(this).find("#shipment_list_date_"+$(this).attr('id')).text();

            var shipment = $(this).find("#shipment_"+$(this).attr('id')).text();

            var start_time = $(this).find("#start_time_"+$(this).attr('id')).text();

            var end_time = $(this).find("#end_time_"+$(this).attr('id')).text();

            var start_work = $(this).find("#start_work_"+$(this).attr('id')).text();

            var end_work = $(this).find("#end_work_"+$(this).attr('id')).text();

            var customer_type = $(this).find("#customer_type_"+$(this).attr('id')).text();

            var array = shipment.split(",");

            $('#show_shipment_list').html("Chọn chuyến hàng ("+array.length+")");


            $('#shipment_list_number').val(shipment_list_number);

            $('#shipment_list_price').val(shipment_list_price);

            $('#customer').val(customer_name);

            $('#customer').attr('data',customer);

            $('#customer').attr('code',true);

            $('#shipment_list_date').val(shipment_list_date.replace(/\//g,"-"));

            $('#shipment').val(shipment);

            $('#start_time').val(start_time.replace(/\//g,"-"));

            $('#end_time').val(end_time.replace(/\//g,"-"));

            $('#start_work').val(start_work);

            $('#end_work').val(end_work);



            $('#yes').val($(this).attr('id'));

            
            $.ajax({

                url: '<?php echo BASE_URL ?>/shipmentlist/getshipmentadd',

                type: 'POST',

                data: {customer:customer,customer_type:customer_type},

                success:function(data){



                    $('#customer_type').html(data);

                    $('#customer_type').multiselect( 'refresh' );


                }

            });

            
            $( ".add-field" ).dialog( "open" );

        }

    });

</script>

<script type="text/javascript">

function add_click(){

    $('#yes').val("");

    $('.add-field').slideDown(500);

     $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);   

        $('#shipment_list_number').val("");

        $('#shipment_list_price').val("");

        $('#customer').val("");

        $('#customer').attr('data',"");

        $('#customer').attr('code',false);

        $('#shipment_list_date').val("");

        
        $('#start_time').val("");

        $('#end_time').val("");

        $('#start_work').val("00:00:00");

        $('#end_work').val("23:59:59");

        $('#shipment').val("");

        $('#customer_type').html("");

        $('#customer_type').multiselect( 'refresh' );


        $('#show_shipment_list').html("Chọn chuyến hàng (0)");

        $('.number').focus(function(){

            if ( $(this).val() == '0') {

               $(this).val(""); 

            };

            

        });

        $('.number').blur(function(){

            if ( $(this).val() == "") {

                $(this).val(0);

            };

            

        });





   $( ".add-field" ).dialog( "open" );



}



$(document).ready(function(){

            // Validate form

            $("#add_shipment_list").validate({

                errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi

                rules: {

                    

                },

                submitHandler: function(form) {

                

                    if ($('#customer').attr('code') == 'false') {

                        $('#customer').val("");

                        $('#customer').focus();

                        return false;

                    };



                    var shipment_list_number = $('#shipment_list_number').attr('value');

                    var shipment_list_price = $('#shipment_list_price').attr('value');

                    var customer = $('#customer').attr('data');

                    var shipment_list_date = $('#shipment_list_date').attr('value');

                    var start_time = $('#start_time').attr('value');

                    var end_time = $('#end_time').attr('value');

                    var start_work = $('#start_work').attr('value');

                    var end_work = $('#end_work').attr('value');

                    var customer_type = $('#customer_type').val();

                    var shipment = $('#shipment').val();

                    if (shipment == "") {
                      alert('Vui lòng chọn chuyến hàng cần lập bảng kê!');
                      return false;
                    }


                    var yes = $('#yes').attr('value');

                    

                    var action      = "them";

                 

                    $.ajax({

                        type: "POST", // phương thức gởi đi

                        url: "<?php echo BASE_URL ?>/shipmentlist/add", // nơi mà dữ liệu sẽ chuyển đến khi submit

                        data: {

                            shipment_list_number: shipment_list_number,

                            shipment_list_price: shipment_list_price,

                            customer: customer,

                            shipment_list_date: shipment_list_date,

                            shipment: shipment,

                            customer_type: customer_type,

                            start_time: start_time,

                            end_time: end_time,

                            start_work: start_work,

                            end_work: end_work,

                            yes: yes,

                            }, // giá trị post

                        success: function(answer){ // if everything goes well

                            //alert(answer);

                            $('#error').hide();

                            $('#error').slideToggle(100); // hiển thị thẻ div success

                            $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success

                            $('#error').fadeOut(10000);



                            if (yes != "") {

                                if (answer.trim() != "Thông tin này đã tồn tại" ) {

                                  setTimeout(function() {

                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');

                                      }, 200);

                                    $('#export_stock_name_'+yes).text(export_stock_name);

                                    $('#province_name_'+yes).text($('#province option:selected').text());

                                }

                            }

                            else{

                                if (answer.trim() != "Thông tin này đã tồn tại") {

                                  setTimeout(function() {

                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');

                                      }, 200);

                                    var lastID = parseInt($('#lasted').html());

                                    var rowCount = parseInt($('.table_data > tbody > tr').length);

                                    $('.table_data > tbody:last')

                                    .append(

                                        '<tr onclick="HighLightTR(this,#4d90fe,cc3333);" id="'+parseInt(lastID+1)+'" class="edit_tr"><td><input name="check[]" type="checkbox" class="checkbox" value="'+parseInt(lastID+1)+'"></td><td class="fix">'+parseInt(rowCount+1)+'</td><td class="fix" id="export_stock_name_'+parseInt(lastID+1)+'">'+export_stock_name+'</td><td class="fix" data="'+province+'" id="province_name_'+parseInt(lastID+1)+'">'+$('#province option:selected').text()+'</td><td><a class="error" href="#">Sửa</a> | <a class="error" onclick="del('+parseInt(lastID+1)+')">Xóa</a></td></tr>'

                                    );



                                    $('#lasted').html(parseInt(lastID+2));

                                }

                            }

                        }

                    });

                    return false;

                     

                 }

            });



    $('#customer').keyup(function(){

      

        var keyword = $(this).val();

        $.ajax({

            url: '<?php echo BASE_URL ?>/shipmentlist/getcustomer',

            type: 'POST',

            data: {keyword:keyword},

            success:function(data){

                $('#customer_list_id').slideDown(200);

                $('#customer_list_id').html(data);

            }

        });

        if ($('#customer').val() == "" || $('#customer').attr('data') == "") {

            //$('#loc_from').val("");

            $('#customer').attr('data',"");

            $('#customer').attr('code',false);

        }

      

   });

   $('#customer').on('keydown', function() {

        var key = event.keyCode || event.charCode;



        if( key == 8 || key == 46 ){

            $('#customer').attr('data',"");

        }

            

      }); 



    $('.number').keyup(function(event) {



          // skip for arrow keys

      if(event.which >= 37 && event.which <= 40) return;



      // format number

      $(this).val(function(index, value) {

        return value

          .replace(/[^0-9-.]/g, "")

        ;

      });

    });

   

   $('.numbers').keyup(function(event) {



          // skip for arrow keys

      if(event.which >= 37 && event.which <= 40) return;



      // format number

      $(this).val(function(index, value) {

        return value

          .replace(/[^0-9-.]/g, "")

          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")

        ;

      });

    });





});

function get_number(id){

    return $(id).val().replace(/\,/g,'');

}

function set_item_customer(value,name,mst,address,sub) {

    // change input value

    $('#customer').val(name);

    $("#customer").attr("data",value);

    $("#customer").attr("code",'true');

    $('#customer_mst').val(mst);

    $('#customer_address').val(address);

    $.ajax({

        url: '<?php echo BASE_URL ?>/shipmentlist/getcustomersub',

        type: 'POST',

        data: {sub:sub},

        success:function(data){

          $('#customer_type').html(data);

          $('#customer_type').multiselect( 'refresh' );

        

        }

    });



    // hide proposition list

    $('#customer_list_id').hide();

    $('#customer').focus();

     

    $(".numbers").val(function(index, value) {

      return value
        .replace(/[^0-9-.]/g, "")
        .replace(/\B(?=(\d{3})+(?!\d))/g, ",")

      ;

    }); 

}

</script>

<script type="text/javascript">



$( ".add-field" ).dialog({

    autoOpen: false,

    modal: true,

    width: "auto",

    title: "Lập bảng kê",

    hide: 'fold',

    show: 'blind'

});

$( "#show_shipment" ).dialog({

    autoOpen: false,

    modal: true,

    width: "auto",

    maxHeight: $(window).height()-50,

    title: "Danh sách chuyến hàng",

    hide: 'fold',

    show: 'blind',

    buttons: {

        OK: function() {
          var num = 0;
          var tien = 0;
          var val = "";
          $('.tr').each(function() { 
            
              $(this).find('input[name="check_i[]"]:checked').each(function () {
                num++;
                tien += parseFloat($(this).attr('data'));
                 if (val =="")
                  val += $(this).val();
                 else
                  val += ',' + $(this).val();
              });

          });

          $('#show_shipment_list').html("Chọn chuyến hàng ("+num+")");
          $('#shipment').val(val);
          $('#shipment_list_price').val(tien);

          $(".numbers").val(function(index, value) {

            return value
              .replace(/[^0-9-.]/g, "")
              .replace(/\B(?=(\d{3})+(?!\d))/g, ",")

            ;

          }); 

          $( this ).dialog( "close" );

        },
        Export: function(){
          $("#tblExport2").battatech_excelexport({

                  containerid: "tblExport2"

                 , datatype: 'table'

              });
        } ,       


    }

});

</script>



<script type="text/javascript">

    $(function() {

    var pickerOpts = {

        closeText: "Đóng",

        currentText: "Hiện tại",

        nextText: "Tiếp",

        prevText: "Quay lại",

        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",

        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],

        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",

        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],

        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",

        "Thứ sáu", "Thứ bảy"],

        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",

        "T6", "T7"],

        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",

        "T6", "T7"],

        //defaultDate: "+1w",

        changeMonth: true,

        changeYear: true,

        dateFormat: 'dd-mm-yy',

        firstDay: 1,

        isRTL: false,

        showButtonPanel: true,

         

    };  

    $("#shipment_list_date").datepicker(pickerOpts);



    

              

            

    

});



$("#customer_type").multiselect({});



</script>







<style type="text/css">

    #ui-datepicker-div{

        font-size: 13px;

    }

</style>

<script type="text/javascript">

    $(function() {

    var pickerOpts = {

        closeText: "Đóng",

        currentText: "Hiện tại",

        nextText: "Tiếp",

        prevText: "Quay lại",

        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",

        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],

        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",

        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],

        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",

        "Thứ sáu", "Thứ bảy"],

        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",

        "T6", "T7"],

        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",

        "T6", "T7"],

        //defaultDate: "+1w",

        changeMonth: true,

        changeYear: true,

        dateFormat: 'dd-mm-yy',

        firstDay: 1,

        isRTL: false,

        showButtonPanel: true,

        onClose: function(selectedDate) {

                

                $( "#ketthuc" ).datepicker( "option", "minDate", selectedDate );



         },

         

    };  

    $("#batdau").datepicker(pickerOpts);



    var pickerOpts4 = {

        closeText: "Đóng",

        currentText: "Hiện tại",

        nextText: "Tiếp",

        prevText: "Quay lại",

        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",

        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],

        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",

        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],

        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",

        "Thứ sáu", "Thứ bảy"],

        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",

        "T6", "T7"],

        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",

        "T6", "T7"],

        //defaultDate: "+1w",

        changeMonth: true,

        changeYear: true,

        dateFormat: 'dd-mm-yy',

        firstDay: 1,

        isRTL: false,

        showButtonPanel: true,

        onClose: function(selectedDate) {

                

                $( "#batdau" ).datepicker( "option", "maxDate", selectedDate );

                

         },

         

    };  

    $("#ketthuc").datepicker(pickerOpts4);

              

            

    

});



var ch = "<?php echo $limit ?>";

$('#chonloc option[value='+ch+']').attr('selected','selected');



var kh = "<?php echo $kh ?>";

$('#sl_nv option[value='+kh+']').attr('selected','selected');



var v = "<?php echo $vong ?>";

$('#sl_round option[value='+v+']').attr('selected','selected');



var tt = "<?php echo $trangthai ?>";

$('#sl_staff option[value='+tt+']').attr('selected','selected');



</script>

<script type="text/javascript">

    

    $('#sl_round').change(function(){

        var m = $(this).val();

        var y = $('#sl_staff').val();

        var firstDay = new Date(y, m-1, 1);

        var lastDay = new Date(y, m, 0);



        $('#batdau').datepicker("setDate", firstDay );

        $('#ketthuc').datepicker("setDate", lastDay );



    });



    $('#sl_staff').change(function(){

        var y = $(this).val();

        var m = $('#sl_round').val();

        var firstDay = new Date(y, m-1, 1);

        var lastDay = new Date(y, m, 0);



        $('#batdau').datepicker("setDate", firstDay );

        $('#ketthuc').datepicker("setDate", lastDay );



    });


var pickerOpts = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+5",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onSelect: function(dateStr) {
          if ($('#end_time').val()=="") {
            var d = $.datepicker.parseDate('dd-mm-yy', dateStr);
            var month = parseInt(1, 10);

            d.setMonth(d.getMonth() + month);
            d.setDate(d.getDate() - month);

            $('#end_time').datepicker('setDate', d);
          }
            
        },
        onClose: function(selectedDate) {
                
                $( "#end_time" ).datepicker( "option", "minDate", selectedDate );

         },
    }; 
    $("#start_time").datepicker(pickerOpts);

    var pickerOpts2 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+5",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#start_time" ).datepicker( "option", "maxDate", selectedDate );

         },
    }; 
    $("#end_time").datepicker(pickerOpts2);



$('#show_shipment_list').click(function(){
  var customer = $('#customer').attr('data');
  var start_time = $('#start_time').val();
  var end_time = $('#end_time').val();
  var start_work = $('#start_work').val();
  var end_work = $('#end_work').val();
  var customer_type = $('#customer_type').val();
  var id = $('#yes').val();

  if (customer > 0 && start_time != "" && end_time != "") {
    $.ajax({

        url: '<?php echo BASE_URL ?>/shipmentlist/getshipment',

        type: 'POST',

        data: {id: id, customer:customer, start_time:start_time, end_time:end_time, start_work:start_work, end_work:end_work, customer_type: customer_type},

        success:function(data){

          $('#show_shipment').html(data);

          var ship = $('#shipment').val();
          if(ship != ""){
            var array = ship.split(",");
            $('input[name="check_i[]"]').prop("checked",false);
            for (var i = 0; i < array.length; i++) {
              $('input[name="check_i[]"][value='+array[i]+']').prop("checked",true);
            };
          }
          

          $( "#show_shipment" ).dialog( "open" );
        }

    });
  }

});

$(".time").mask("99:99:99");
</script>

<style type="text/css">

.ui-multiselect-menu {

    z-index: 9999999;

}

</style>