<script type="text/javascript" src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css">

<div id="loading"></div>
<div id="winpopup"></div>
<section class="content-header">
    <h1>BẢNG THEO DÕI LỊCH KIỂM ĐỊNH - BẢO HIỂM - PHỤ TÙNG SỬ DỤNG</h1>
  <ol class="breadcrumb">
    <li><a href="<?php echo $this->url('admin') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><a href="<?php echo $this->url('spareparttracking') ?>">Kiểm định , Bảo hiểm, Phụ tùng sử dụng</a></li>
  </ol>
</section>

<table class="table_data" id="tblExport2">
    <thead>
        <tr>
            <th class="fix">Số tháng sử dụng</th>
            <th class="fix">Dưới 3 tháng</th>
            <th class="fix">Trên 3 tháng</th>
            <th class="fix">Trên 6 tháng</th>
            <th class="fix">Trên 12 tháng</th>
            <th class="fix">Trên 24 tháng</th>
            <th class="fix">Trên 36 tháng</th>
            <th class="fix">Trên 48 tháng</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td class="fix">Số lượng phụ tùng thiết bị</td>
            <td class="fix"><span data="thang1" class="badge bg-light"><?php echo count($thang1) ?></span></td>
            <td class="fix"><span data="thang3" class="badge bg-green"><?php echo count($thang3) ?></span></td>
            <td class="fix"><span data="thang6" class="badge bg-yellow"><?php echo count($thang6) ?></span></td>
            <td class="fix"><span data="thang12" class="badge bg-red"><?php echo count($thang12) ?></span></td>
            <td class="fix"><span data="thang24" class="badge bg-red"><?php echo count($thang24) ?></span></td>
            <td class="fix"><span data="thang36" class="badge bg-red"><?php echo count($thang36) ?></span></td>
            <td class="fix"><span data="thang48" class="badge bg-red"><?php echo count($thang48) ?></span></td>
        </tr>
    </tbody>
</table>

<?php $i=1; ?>
<table class="table_data" id="tblExport3">
    <thead>
        <tr>
            <td class="text-right" colspan="25">ĐVT: 1000 km</td>
        </tr>
        <tr>
            <th class="fix" rowspan="2">STT</th>
            <th class="fix" rowspan="2">Ngày lắp vào</th>
            <th class="fix" rowspan="2">Số xe</th>
            <th class="fix" rowspan="2">Mooc</th>
            <th class="fix" rowspan="2">Tên phụ tùng</th>
            <th class="fix" colspan="19">Số km</th>
        </tr>
        <tr>
            <th class="fix">1</th>
            <th class="fix">5</th>
            <th class="fix">10</th>
            <th class="fix">15</th>
            <th class="fix">20</th>
            <th class="fix">25</th>
            <th class="fix">30</th>
            <th class="fix">40</th>
            <th class="fix">50</th>
            <th class="fix">60</th>
            <th class="fix">70</th>
            <th class="fix">80</th>
            <th class="fix">90</th>
            <th class="fix">100</th>
            <th class="fix">120</th>
            <th class="fix">140</th>
            <th class="fix">160</th>
            <th class="fix">180</th>
            <th class="fix">200</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($spares as $spare_part) : 
        $km = isset($data_vehicle[$spare_part->spare_part_id]['km'])?$data_vehicle[$spare_part->spare_part_id]['km']:0;
    ?>
        <tr>
            <td class="fix"><?php echo $i++; ?></td>
            <td class="fix" ><?php echo $lib->hien_thi_ngay_thang($data_vehicle[$spare_part->spare_part_id]['import']) ?></td>
            <td class="fix" ><?php echo isset($vehicle_data['name'][$data_vehicle[$spare_part->spare_part_id]['vehicle']])?$vehicle_data['name'][$data_vehicle[$spare_part->spare_part_id]['vehicle']]:null ?></td>
            <td class="fix" ><?php echo isset($romooc_data['name'][$data_vehicle[$spare_part->spare_part_id]['romooc']])?$romooc_data['name'][$data_vehicle[$spare_part->spare_part_id]['romooc']]:null ?></td>
            <td class="fix"  id="spare_part_name_<?php echo $spare_part->spare_part_id; ?>"><a target="_blank" href="<?php echo $this->url('sparepart/index/'.$spare_part->spare_part_id) ?>" ><?php echo $spare_part->spare_part_name.($spare_part->spare_part_seri!=""?' - ['.$spare_part->spare_part_seri.']':null) ?></a></td>
            <td <?php echo ($km >= 1000 && $km < 5000)?'class="fix masterTooltip bg-red" title="'.$km.'"':'class="fix"' ?> >
            </td>
            <td <?php echo ($km >= 5000 && $km < 10000)?'class="fix masterTooltip bg-red" title="'.$km.'"':'class="fix"' ?> >
            </td>
            <td <?php echo ($km >= 10000 && $km < 15000)?'class="fix masterTooltip bg-red" title="'.$km.'"':'class="fix"' ?> >
            </td>
            <td <?php echo ($km >= 15000 && $km < 20000)?'class="fix masterTooltip bg-red" title="'.$km.'"':'class="fix"' ?> >
            </td>
            <td <?php echo ($km >= 20000 && $km < 25000)?'class="fix masterTooltip bg-red" title="'.$km.'"':'class="fix"' ?> >
            </td>
            <td <?php echo ($km >= 25000 && $km < 30000)?'class="fix masterTooltip bg-red" title="'.$km.'"':'class="fix"' ?> >
            </td>
            <td <?php echo ($km >= 30000 && $km < 40000)?'class="fix masterTooltip bg-red" title="'.$km.'"':'class="fix"' ?> >
            </td>
            <td <?php echo ($km >= 40000 && $km < 50000)?'class="fix masterTooltip bg-red" title="'.$km.'"':'class="fix"' ?> >
            </td>
            <td <?php echo ($km >= 50000 && $km < 60000)?'class="fix masterTooltip bg-red" title="'.$km.'"':'class="fix"' ?> >
            </td>
            <td <?php echo ($km >= 60000 && $km < 70000)?'class="fix masterTooltip bg-red" title="'.$km.'"':'class="fix"' ?> >
            </td>
            <td <?php echo ($km >= 70000 && $km < 80000)?'class="fix masterTooltip bg-red" title="'.$km.'"':'class="fix"' ?> >
            </td>
            <td <?php echo ($km >= 80000 && $km < 90000)?'class="fix masterTooltip bg-red" title="'.$km.'"':'class="fix"' ?> >
            </td>
            <td <?php echo ($km >= 90000 && $km < 100000)?'class="fix masterTooltip bg-red" title="'.$km.'"':'class="fix"' ?> >
            </td>
            <td <?php echo ($km >= 100000 && $km < 120000)?'class="fix masterTooltip bg-red" title="'.$km.'"':'class="fix"' ?> >
            </td>
            <td <?php echo ($km >= 120000 && $km < 140000)?'class="fix masterTooltip bg-red" title="'.$km.'"':'class="fix"' ?> >
            </td>
            <td <?php echo ($km >= 140000 && $km < 160000)?'class="fix masterTooltip bg-red" title="'.$km.'"':'class="fix"' ?> >
            </td>
            <td <?php echo ($km >= 160000 && $km < 180000)?'class="fix masterTooltip bg-red" title="'.$km.'"':'class="fix"' ?> >
            </td>
            <td <?php echo ($km >= 180000 && $km < 200000)?'class="fix masterTooltip bg-red" title="'.$km.'"':'class="fix"' ?> >
            </td>
            <td <?php echo ($km >= 200000)?'class="fix masterTooltip bg-red" title="'.$km.'"':'class="fix"' ?> >
            </td>
            
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>


<div class="row">
    <div class="col-md-6 col-xs-12">
        <?php $i=1; ?>
        <table class="table_data" id="tblExport">
            <thead>
                <tr>
                    <th rowspan="2" class="fix">STT</th>
                    <th rowspan="2" class="fix">Xe/Mooc</th>
                    <th class="fix" colspan="3">Ngày hết hạn</th>
                </tr>
                <tr>
                    <th class="fix">Phí sử dụng đường bộ</th>
                    <th class="fix">Kiểm định</th>
                    <th class="fix">Bảo hiểm</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($vehicles as $vehicle) : ?>
                <tr>
                    <td class="fix"><?php echo $i++ ?></td>
                    <td class="fix"><a target="_blank" href="<?php echo $this->url('vehicle/index/'.$vehicle->vehicle_id) ?>"><?php echo $vehicle->vehicle_number ?></a></td>
                    <td class="fix"><?php echo isset($road_cost_data['vehicle'][$vehicle->vehicle_id])?'<span style="display:none">'.date('Ymd',$road_cost_data['vehicle'][$vehicle->vehicle_id]).'</span>'.$lib->hien_thi_ngay_thang($road_cost_data['vehicle'][$vehicle->vehicle_id]):null ?></td>
                    <td class="fix"><?php echo isset($checking_cost_data['vehicle'][$vehicle->vehicle_id])?'<span style="display:none">'.date('Ymd',$checking_cost_data['vehicle'][$vehicle->vehicle_id]).'</span>'.$lib->hien_thi_ngay_thang($checking_cost_data['vehicle'][$vehicle->vehicle_id]):null ?></td>
                    <td class="fix"><?php echo isset($insurance_cost_data['vehicle'][$vehicle->vehicle_id])?'<span style="display:none">'.date('Ymd',$insurance_cost_data['vehicle'][$vehicle->vehicle_id]).'</span>'.$lib->hien_thi_ngay_thang($insurance_cost_data['vehicle'][$vehicle->vehicle_id]):null ?></td>
                </tr>
            <?php endforeach; ?>
            <?php foreach ($romoocs as $romooc) : ?>
                <tr>
                    <td class="fix"><?php echo $i++ ?></td>
                    <td class="fix"><a target="_blank" href="<?php echo $this->url('romooc/index/'.$romooc->romooc_id) ?>"><?php echo $romooc->romooc_number ?></a></td>
                    <td class="fix"><?php echo isset($road_cost_data['romooc'][$romooc->romooc_id])?'<span style="display:none">'.date('Ymd',$road_cost_data['romooc'][$romooc->romooc_id]).'</span>'.$lib->hien_thi_ngay_thang($road_cost_data['romooc'][$romooc->romooc_id]):null ?></td>
                    <td class="fix"><?php echo isset($checking_cost_data['romooc'][$romooc->romooc_id])?'<span style="display:none">'.date('Ymd',$checking_cost_data['romooc'][$romooc->romooc_id]).'</span>'.$lib->hien_thi_ngay_thang($checking_cost_data['romooc'][$romooc->romooc_id]):null ?></td>
                    <td class="fix"><?php echo isset($insurance_cost_data['romooc'][$romooc->romooc_id])?'<span style="display:none">'.date('Ymd',$insurance_cost_data['romooc'][$romooc->romooc_id]).'</span>'.$lib->hien_thi_ngay_thang($insurance_cost_data['romooc'][$romooc->romooc_id]):null ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <div class="col-md-6 col-xs-12">
        <?php $i=1; ?>
        <table class="table_data" id="tblExport4">
            <thead>
                <tr>
                    <th rowspan="2" class="fix">STT</th>
                    <th rowspan="2" class="fix">Xe/Mooc</th>
                    <th class="fix" colspan="3">Quá hạn</th>
                </tr>
                <tr>
                    <th class="fix">Phí sử dụng đường bộ</th>
                    <th class="fix">Kiểm định</th>
                    <th class="fix">Bảo hiểm</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($vehicles as $vehicle) : 
                $r = isset($road_cost_data['end_vehicle'][$vehicle->vehicle_id])?$lib->hien_thi_ngay_thang($road_cost_data['end_vehicle'][$vehicle->vehicle_id]):null;
                $c = isset($checking_cost_data['end_vehicle'][$vehicle->vehicle_id])?$lib->hien_thi_ngay_thang($checking_cost_data['end_vehicle'][$vehicle->vehicle_id]):null;
                $in = isset($insurance_cost_data['end_vehicle'][$vehicle->vehicle_id])?$lib->hien_thi_ngay_thang($insurance_cost_data['end_vehicle'][$vehicle->vehicle_id]):null;

                if($r != null || $c != null || $in != null){
            ?>
                <tr>
                    <td class="fix"><?php echo $i++ ?></td>
                    <td class="fix"><a target="_blank" href="<?php echo $this->url('vehicle/index/'.$vehicle->vehicle_id) ?>"><?php echo $vehicle->vehicle_number ?></a></td>
                    <td class="fix"><?php echo $r ?></td>
                    <td class="fix"><?php echo $c ?></td>
                    <td class="fix"><?php echo $in ?></td>
                </tr>
            <?php 
                }
            endforeach; ?>
            <?php foreach ($romoocs as $romooc) : 
                $r = isset($road_cost_data['end_romooc'][$romooc->romooc_id])?$lib->hien_thi_ngay_thang($road_cost_data['end_romooc'][$romooc->romooc_id]):null;
                $c = isset($checking_cost_data['end_romooc'][$romooc->romooc_id])?$lib->hien_thi_ngay_thang($checking_cost_data['end_romooc'][$romooc->romooc_id]):null;
                $in = isset($insurance_cost_data['end_romooc'][$romooc->romooc_id])?$lib->hien_thi_ngay_thang($insurance_cost_data['end_romooc'][$romooc->romooc_id]):null;

                if($r != null || $c != null || $in != null){
            ?>
                <tr>
                    <td class="fix"><?php echo $i++ ?></td>
                    <td class="fix"><a target="_blank" href="<?php echo $this->url('romooc/index/'.$romooc->romooc_id) ?>"><?php echo $romooc->romooc_number ?></a></td>
                    <td class="fix"><?php echo $r ?></td>
                    <td class="fix"><?php echo $c ?></td>
                    <td class="fix"><?php echo $in ?></td>
                </tr>
            <?php 
                }
            endforeach; ?>
            </tbody>
        </table>
        <table class="table_data" id="tblExport4">
            <thead>
                <tr>
                    <th rowspan="2" class="fix">STT</th>
                    <th rowspan="2" class="fix">Xe/Mooc</th>
                    <th class="fix" colspan="3">Hết hạn trong tháng</th>
                </tr>
                <tr>
                    <th class="fix">Phí sử dụng đường bộ</th>
                    <th class="fix">Kiểm định</th>
                    <th class="fix">Bảo hiểm</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($vehicles as $vehicle) : 
                $r = isset($road_cost_data['month_vehicle'][$vehicle->vehicle_id])?$lib->hien_thi_ngay_thang($road_cost_data['month_vehicle'][$vehicle->vehicle_id]):null;
                $c = isset($checking_cost_data['month_vehicle'][$vehicle->vehicle_id])?$lib->hien_thi_ngay_thang($checking_cost_data['month_vehicle'][$vehicle->vehicle_id]):null;
                $in = isset($insurance_cost_data['month_vehicle'][$vehicle->vehicle_id])?$lib->hien_thi_ngay_thang($insurance_cost_data['month_vehicle'][$vehicle->vehicle_id]):null;

                if($r != null || $c != null || $in != null){
            ?>
                <tr>
                    <td class="fix"><?php echo $i++ ?></td>
                    <td class="fix"><a target="_blank" href="<?php echo $this->url('vehicle/index/'.$vehicle->vehicle_id) ?>"><?php echo $vehicle->vehicle_number ?></a></td>
                    <td class="fix"><?php echo $r ?></td>
                    <td class="fix"><?php echo $c ?></td>
                    <td class="fix"><?php echo $in ?></td>
                </tr>
            <?php 
                }
            endforeach; ?>
            <?php foreach ($romoocs as $romooc) : 
                $r = isset($road_cost_data['month_romooc'][$romooc->romooc_id])?$lib->hien_thi_ngay_thang($road_cost_data['month_romooc'][$romooc->romooc_id]):null;
                $c = isset($checking_cost_data['month_romooc'][$romooc->romooc_id])?$lib->hien_thi_ngay_thang($checking_cost_data['month_romooc'][$romooc->romooc_id]):null;
                $in = isset($insurance_cost_data['month_romooc'][$romooc->romooc_id])?$lib->hien_thi_ngay_thang($insurance_cost_data['month_romooc'][$romooc->romooc_id]):null;

                if($r != null || $c != null || $in != null){
            ?>
                <tr>
                    <td class="fix"><?php echo $i++ ?></td>
                    <td class="fix"><a target="_blank" href="<?php echo $this->url('romooc/index/'.$romooc->romooc_id) ?>"><?php echo $romooc->romooc_number ?></a></td>
                    <td class="fix"><?php echo $r ?></td>
                    <td class="fix"><?php echo $c ?></td>
                    <td class="fix"><?php echo $in ?></td>
                </tr>
            <?php 
                }
            endforeach; ?>
            </tbody>
        </table>
        <table class="table_data" id="tblExport4">
            <thead>
                <tr>
                    <th rowspan="2" class="fix">STT</th>
                    <th rowspan="2" class="fix">Xe/Mooc</th>
                    <th class="fix" colspan="3">Còn hạn ít hơn 3 tháng</th>
                </tr>
                <tr>
                    <th class="fix">Phí sử dụng đường bộ</th>
                    <th class="fix">Kiểm định</th>
                    <th class="fix">Bảo hiểm</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($vehicles as $vehicle) : 
                $r = isset($road_cost_data['3month_vehicle'][$vehicle->vehicle_id])?$lib->hien_thi_ngay_thang($road_cost_data['3month_vehicle'][$vehicle->vehicle_id]):null;
                $c = isset($checking_cost_data['3month_vehicle'][$vehicle->vehicle_id])?$lib->hien_thi_ngay_thang($checking_cost_data['3month_vehicle'][$vehicle->vehicle_id]):null;
                $in = isset($insurance_cost_data['3month_vehicle'][$vehicle->vehicle_id])?$lib->hien_thi_ngay_thang($insurance_cost_data['3month_vehicle'][$vehicle->vehicle_id]):null;

                if($r != null || $c != null || $in != null){
            ?>
                <tr>
                    <td class="fix"><?php echo $i++ ?></td>
                    <td class="fix"><a target="_blank" href="<?php echo $this->url('vehicle/index/'.$vehicle->vehicle_id) ?>"><?php echo $vehicle->vehicle_number ?></a></td>
                    <td class="fix"><?php echo $r ?></td>
                    <td class="fix"><?php echo $c ?></td>
                    <td class="fix"><?php echo $in ?></td>
                </tr>
            <?php 
                }
            endforeach; ?>
            <?php foreach ($romoocs as $romooc) : 
                $r = isset($road_cost_data['3month_romooc'][$romooc->romooc_id])?$lib->hien_thi_ngay_thang($road_cost_data['3month_romooc'][$romooc->romooc_id]):null;
                $c = isset($checking_cost_data['3month_romooc'][$romooc->romooc_id])?$lib->hien_thi_ngay_thang($checking_cost_data['3month_romooc'][$romooc->romooc_id]):null;
                $in = isset($insurance_cost_data['3month_romooc'][$romooc->romooc_id])?$lib->hien_thi_ngay_thang($insurance_cost_data['3month_romooc'][$romooc->romooc_id]):null;

                if($r != null || $c != null || $in != null){
            ?>
                <tr>
                    <td class="fix"><?php echo $i++ ?></td>
                    <td class="fix"><a target="_blank" href="<?php echo $this->url('romooc/index/'.$romooc->romooc_id) ?>"><?php echo $romooc->romooc_number ?></a></td>
                    <td class="fix"><?php echo $r ?></td>
                    <td class="fix"><?php echo $c ?></td>
                    <td class="fix"><?php echo $in ?></td>
                </tr>
            <?php 
                }
            endforeach; ?>
            </tbody>
        </table>
    </div>
</div>


<?php $i=1; ?>
<table style="display:none" class="table_data" id="thang1">
<thead>
    <tr>
        <th class="fix">STT</th>
        <th class="fix">Mã phụ tùng</th>
        <th class="fix">Tên phụ tùng</th>
        <th class="fix">Ngày lắp vào</th>
        <th class="fix">Số km sử dụng</th>
        <th class="fix">Số xe</th>
        <th class="fix">Mooc</th>
    </tr>
    
    
   </thead>
   <tbody>
    <?php foreach ($thang1 as $spare_part) : ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $spare_part->spare_part_id ?>" class="edit_tr">
            <td class="fix"><?php echo $i++; ?></td>
            <td class="fix"  id="spare_part_code_<?php echo $spare_part->spare_part_id; ?>"><a target="_blank" href="<?php echo $this->url('sparepart/index/'.$spare_part->spare_part_id) ?>" ><?php echo $spare_part->spare_part_code ?></a></td>
            <td class="fix"  id="spare_part_name_<?php echo $spare_part->spare_part_id; ?>"><?php echo $spare_part->spare_part_name.($spare_part->spare_part_seri!=""?' - ['.$spare_part->spare_part_seri.']':null) ?></td>
            <td class="fix" ><?php echo $lib->hien_thi_ngay_thang($data_vehicle[$spare_part->spare_part_id]['import']) ?></td>
            <td class="fix" ><?php echo isset($data_vehicle[$spare_part->spare_part_id]['km'])?$data_vehicle[$spare_part->spare_part_id]['km']:null ?></td>
            <td class="fix" ><?php echo isset($vehicle_data['name'][$data_vehicle[$spare_part->spare_part_id]['vehicle']])?$vehicle_data['name'][$data_vehicle[$spare_part->spare_part_id]['vehicle']]:null ?></td>
            <td class="fix" ><?php echo isset($romooc_data['name'][$data_vehicle[$spare_part->spare_part_id]['romooc']])?$romooc_data['name'][$data_vehicle[$spare_part->spare_part_id]['romooc']]:null ?></td>
            
        </tr>
    <?php endforeach; ?>
   </tbody>
</table>
<?php $i=1; ?>
<table style="display:none" class="table_data" id="thang3">
<thead>
    <tr>
        <th class="fix">STT</th>
        <th class="fix">Mã phụ tùng</th>
        <th class="fix">Tên phụ tùng</th>
        <th class="fix">Ngày lắp vào</th>
        <th class="fix">Số km sử dụng</th>
        <th class="fix">Số xe</th>
        <th class="fix">Mooc</th>
    </tr>
    
    
   </thead>
   <tbody>
    <?php foreach ($thang3 as $spare_part) : ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $spare_part->spare_part_id ?>" class="edit_tr">
            <td class="fix"><?php echo $i++; ?></td>
            <td class="fix"  id="spare_part_code_<?php echo $spare_part->spare_part_id; ?>"><a target="_blank" href="<?php echo $this->url('sparepart/index/'.$spare_part->spare_part_id) ?>" ><?php echo $spare_part->spare_part_code ?></a></td>
            <td class="fix"  id="spare_part_name_<?php echo $spare_part->spare_part_id; ?>"><?php echo $spare_part->spare_part_name.($spare_part->spare_part_seri!=""?' - ['.$spare_part->spare_part_seri.']':null) ?></td>
            <td class="fix" ><?php echo $lib->hien_thi_ngay_thang($data_vehicle[$spare_part->spare_part_id]['import']) ?></td>
            <td class="fix" ><?php echo isset($data_vehicle[$spare_part->spare_part_id]['km'])?$data_vehicle[$spare_part->spare_part_id]['km']:null ?></td>
            <td class="fix" ><?php echo isset($vehicle_data['name'][$data_vehicle[$spare_part->spare_part_id]['vehicle']])?$vehicle_data['name'][$data_vehicle[$spare_part->spare_part_id]['vehicle']]:null ?></td>
            <td class="fix" ><?php echo isset($romooc_data['name'][$data_vehicle[$spare_part->spare_part_id]['romooc']])?$romooc_data['name'][$data_vehicle[$spare_part->spare_part_id]['romooc']]:null ?></td>
            
        </tr>
    <?php endforeach; ?>
   </tbody>
</table>
<?php $i=1; ?>
<table style="display:none" class="table_data" id="thang6">
<thead>
    <tr>
        <th class="fix">STT</th>
        <th class="fix">Mã phụ tùng</th>
        <th class="fix">Tên phụ tùng</th>
        <th class="fix">Ngày lắp vào</th>
        <th class="fix">Số km sử dụng</th>
        <th class="fix">Số xe</th>
        <th class="fix">Mooc</th>
    </tr>
    
    
   </thead>
   <tbody>
    <?php foreach ($thang6 as $spare_part) : ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $spare_part->spare_part_id ?>" class="edit_tr">
            <td class="fix"><?php echo $i++; ?></td>
            <td class="fix"  id="spare_part_code_<?php echo $spare_part->spare_part_id; ?>"><a target="_blank" href="<?php echo $this->url('sparepart/index/'.$spare_part->spare_part_id) ?>" ><?php echo $spare_part->spare_part_code ?></a></td>
            <td class="fix"  id="spare_part_name_<?php echo $spare_part->spare_part_id; ?>"><?php echo $spare_part->spare_part_name.($spare_part->spare_part_seri!=""?' - ['.$spare_part->spare_part_seri.']':null) ?></td>
            <td class="fix" ><?php echo $lib->hien_thi_ngay_thang($data_vehicle[$spare_part->spare_part_id]['import']) ?></td>
            <td class="fix" ><?php echo isset($data_vehicle[$spare_part->spare_part_id]['km'])?$data_vehicle[$spare_part->spare_part_id]['km']:null ?></td>
            <td class="fix" ><?php echo isset($vehicle_data['name'][$data_vehicle[$spare_part->spare_part_id]['vehicle']])?$vehicle_data['name'][$data_vehicle[$spare_part->spare_part_id]['vehicle']]:null ?></td>
            <td class="fix" ><?php echo isset($romooc_data['name'][$data_vehicle[$spare_part->spare_part_id]['romooc']])?$romooc_data['name'][$data_vehicle[$spare_part->spare_part_id]['romooc']]:null ?></td>
            
        </tr>
    <?php endforeach; ?>
   </tbody>
</table>
<?php $i=1; ?>
<table style="display:none" class="table_data" id="thang12">
<thead>
    <tr>
        <th class="fix">STT</th>
        <th class="fix">Mã phụ tùng</th>
        <th class="fix">Tên phụ tùng</th>
        <th class="fix">Ngày lắp vào</th>
        <th class="fix">Số km sử dụng</th>
        <th class="fix">Số xe</th>
        <th class="fix">Mooc</th>
    </tr>
    
    
   </thead>
   <tbody>
    <?php foreach ($thang12 as $spare_part) : ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $spare_part->spare_part_id ?>" class="edit_tr">
            <td class="fix"><?php echo $i++; ?></td>
            <td class="fix"  id="spare_part_code_<?php echo $spare_part->spare_part_id; ?>"><a target="_blank" href="<?php echo $this->url('sparepart/index/'.$spare_part->spare_part_id) ?>" ><?php echo $spare_part->spare_part_code ?></a></td>
            <td class="fix"  id="spare_part_name_<?php echo $spare_part->spare_part_id; ?>"><?php echo $spare_part->spare_part_name.($spare_part->spare_part_seri!=""?' - ['.$spare_part->spare_part_seri.']':null) ?></td>
            <td class="fix" ><?php echo $lib->hien_thi_ngay_thang($data_vehicle[$spare_part->spare_part_id]['import']) ?></td>
            <td class="fix" ><?php echo isset($data_vehicle[$spare_part->spare_part_id]['km'])?$data_vehicle[$spare_part->spare_part_id]['km']:null ?></td>
            <td class="fix" ><?php echo isset($vehicle_data['name'][$data_vehicle[$spare_part->spare_part_id]['vehicle']])?$vehicle_data['name'][$data_vehicle[$spare_part->spare_part_id]['vehicle']]:null ?></td>
            <td class="fix" ><?php echo isset($romooc_data['name'][$data_vehicle[$spare_part->spare_part_id]['romooc']])?$romooc_data['name'][$data_vehicle[$spare_part->spare_part_id]['romooc']]:null ?></td>
            
        </tr>
    <?php endforeach; ?>
   </tbody>
</table>
<?php $i=1; ?>
<table style="display:none" class="table_data" id="thang24">
<thead>
    <tr>
        <th class="fix">STT</th>
        <th class="fix">Mã phụ tùng</th>
        <th class="fix">Tên phụ tùng</th>
        <th class="fix">Ngày lắp vào</th>
        <th class="fix">Số km sử dụng</th>
        <th class="fix">Số xe</th>
        <th class="fix">Mooc</th>
    </tr>
    
    
   </thead>
   <tbody>
    <?php foreach ($thang24 as $spare_part) : ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $spare_part->spare_part_id ?>" class="edit_tr">
            <td class="fix"><?php echo $i++; ?></td>
            <td class="fix"  id="spare_part_code_<?php echo $spare_part->spare_part_id; ?>"><a target="_blank" href="<?php echo $this->url('sparepart/index/'.$spare_part->spare_part_id) ?>" ><?php echo $spare_part->spare_part_code ?></a></td>
            <td class="fix"  id="spare_part_name_<?php echo $spare_part->spare_part_id; ?>"><?php echo $spare_part->spare_part_name.($spare_part->spare_part_seri!=""?' - ['.$spare_part->spare_part_seri.']':null) ?></td>
            <td class="fix" ><?php echo $lib->hien_thi_ngay_thang($data_vehicle[$spare_part->spare_part_id]['import']) ?></td>
            <td class="fix" ><?php echo isset($data_vehicle[$spare_part->spare_part_id]['km'])?$data_vehicle[$spare_part->spare_part_id]['km']:null ?></td>
            <td class="fix" ><?php echo isset($vehicle_data['name'][$data_vehicle[$spare_part->spare_part_id]['vehicle']])?$vehicle_data['name'][$data_vehicle[$spare_part->spare_part_id]['vehicle']]:null ?></td>
            <td class="fix" ><?php echo isset($romooc_data['name'][$data_vehicle[$spare_part->spare_part_id]['romooc']])?$romooc_data['name'][$data_vehicle[$spare_part->spare_part_id]['romooc']]:null ?></td>
            
        </tr>
    <?php endforeach; ?>
   </tbody>
</table>
<?php $i=1; ?>
<table style="display:none" class="table_data" id="thang36">
<thead>
    <tr>
        <th class="fix">STT</th>
        <th class="fix">Mã phụ tùng</th>
        <th class="fix">Tên phụ tùng</th>
        <th class="fix">Ngày lắp vào</th>
        <th class="fix">Số km sử dụng</th>
        <th class="fix">Số xe</th>
        <th class="fix">Mooc</th>
    </tr>
    
    
   </thead>
   <tbody>
    <?php foreach ($thang36 as $spare_part) : ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $spare_part->spare_part_id ?>" class="edit_tr">
            <td class="fix"><?php echo $i++; ?></td>
            <td class="fix"  id="spare_part_code_<?php echo $spare_part->spare_part_id; ?>"><a target="_blank" href="<?php echo $this->url('sparepart/index/'.$spare_part->spare_part_id) ?>" ><?php echo $spare_part->spare_part_code ?></a></td>
            <td class="fix"  id="spare_part_name_<?php echo $spare_part->spare_part_id; ?>"><?php echo $spare_part->spare_part_name.($spare_part->spare_part_seri!=""?' - ['.$spare_part->spare_part_seri.']':null) ?></td>
            <td class="fix" ><?php echo $lib->hien_thi_ngay_thang($data_vehicle[$spare_part->spare_part_id]['import']) ?></td>
            <td class="fix" ><?php echo isset($data_vehicle[$spare_part->spare_part_id]['km'])?$data_vehicle[$spare_part->spare_part_id]['km']:null ?></td>
            <td class="fix" ><?php echo isset($vehicle_data['name'][$data_vehicle[$spare_part->spare_part_id]['vehicle']])?$vehicle_data['name'][$data_vehicle[$spare_part->spare_part_id]['vehicle']]:null ?></td>
            <td class="fix" ><?php echo isset($romooc_data['name'][$data_vehicle[$spare_part->spare_part_id]['romooc']])?$romooc_data['name'][$data_vehicle[$spare_part->spare_part_id]['romooc']]:null ?></td>
            
        </tr>
    <?php endforeach; ?>
   </tbody>
</table>
<?php $i=1; ?>
<table style="display:none" class="table_data" id="thang48">
<thead>
    <tr>
        <th class="fix">STT</th>
        <th class="fix">Mã phụ tùng</th>
        <th class="fix">Tên phụ tùng</th>
        <th class="fix">Ngày lắp vào</th>
        <th class="fix">Số km sử dụng</th>
        <th class="fix">Số xe</th>
        <th class="fix">Mooc</th>
    </tr>
    
    
   </thead>
   <tbody>
    <?php foreach ($thang48 as $spare_part) : ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $spare_part->spare_part_id ?>" class="edit_tr">
            <td class="fix"><?php echo $i++; ?></td>
            <td class="fix"  id="spare_part_code_<?php echo $spare_part->spare_part_id; ?>"><a target="_blank" href="<?php echo $this->url('sparepart/index/'.$spare_part->spare_part_id) ?>" ><?php echo $spare_part->spare_part_code ?></a></td>
            <td class="fix"  id="spare_part_name_<?php echo $spare_part->spare_part_id; ?>"><?php echo $spare_part->spare_part_name.($spare_part->spare_part_seri!=""?' - ['.$spare_part->spare_part_seri.']':null) ?></td>
            <td class="fix" ><?php echo $lib->hien_thi_ngay_thang($data_vehicle[$spare_part->spare_part_id]['import']) ?></td>
            <td class="fix" ><?php echo isset($data_vehicle[$spare_part->spare_part_id]['km'])?$data_vehicle[$spare_part->spare_part_id]['km']:null ?></td>
            <td class="fix" ><?php echo isset($vehicle_data['name'][$data_vehicle[$spare_part->spare_part_id]['vehicle']])?$vehicle_data['name'][$data_vehicle[$spare_part->spare_part_id]['vehicle']]:null ?></td>
            <td class="fix" ><?php echo isset($romooc_data['name'][$data_vehicle[$spare_part->spare_part_id]['romooc']])?$romooc_data['name'][$data_vehicle[$spare_part->spare_part_id]['romooc']]:null ?></td>
            
        </tr>
    <?php endforeach; ?>
   </tbody>
</table>

<script type="text/javascript">
$('.badge').click(function(){
    var id = $(this).attr('data');

    $("#"+id).dialog({
        autoOpen: false,
        modal: true,
        width: "auto",
        maxHeight: $(window).height()-50,
        title: "Danh sách",
        hide: 'fold',
        show: 'blind'
    });

    $("#"+id).dialog( "open" );

});

$(document).ready(function() {
    // Tooltip only Text
    $('.masterTooltip').hover(function(){
            // Hover over code
            var title = $(this).attr('title');
            $(this).data('tipText', title).removeAttr('title');
            $('<p class="showtooltip"></p>')
            .text(title)
            .appendTo('body')
            .fadeIn('slow');
    }, function() {
            // Hover out code
            $(this).attr('title', $(this).data('tipText'));
            $('.showtooltip').remove();
    }).mousemove(function(e) {
            var mousex = e.pageX + 20; //Get X coordinates
            var mousey = e.pageY - 10; //Get Y coordinates
            $('.showtooltip')
            .css({ top: mousey, left: mousex })
    });


});


$(document).ready(function() {
    $('#tblExport').DataTable({
        "lengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "Tất cả"]],
        "order": [[ 2, "desc" ], [ 3, "desc" ], [ 4, "desc" ]],
        "fnRowCallback": function( nRow, aData, iDisplayIndex, iDisplayIndexFull ) {
          var index = iDisplayIndex +1;
            $('td:eq(0)',nRow).html(index);
            return nRow
        }
    });
    $('#tblExport3').DataTable({
        "lengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "Tất cả"]],
        "fnRowCallback": function( nRow, aData, iDisplayIndex, iDisplayIndexFull ) {
          var index = iDisplayIndex +1;
            $('td:eq(0)',nRow).html(index);
            return nRow
        }
    });
} );

</script>
<style type="text/css">
.badge:hover, .show_tr:hover{
    cursor: pointer;
}
.showtooltip {
    display:none;
    position:absolute;
    border:1px solid #333;
    background-color:#161616;
    border-radius:5px;
    padding:5px;
    color:#fff;
    font-size:12px Arial;
}

</style>