<div class="row">
  <div class="col-sm-6">
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Backup</h3>
        <span class="label label-primary pull-right"><i class="fa fa-database"></i></span>
      </div><!-- /.box-header -->
      <div class="box-body">
        <p>Tải cơ sở dữ liệu về máy tính.</p>
        <a href="<?php echo $this->url('adminbackup/backup_db') ?>" class="btn btn-primary"><i class="fa fa-download"></i> Download</a>
      </div><!-- /.box-body -->
    </div><!-- /.box -->
  </div><!-- /.col -->
  <div class="col-sm-6">
    <div class="box box-danger">
      <div class="box-header with-border">
        <h3 class="box-title">Restore</h3>
        <span class="label label-danger pull-right"><i class="fa fa-database"></i></span>
      </div><!-- /.box-header -->
      <div class="box-body">
        <p>Tải lên bản backup cơ sở dữ liệu (.sql). <b>Toàn bộ dữ liệu hiện tại sẽ bị ghi đè.</b></p>
        <a href="<?php echo $this->url('adminbackup/restore') ?>" class="btn btn-danger"><i class="fa fa-upload"></i> Upload</a>
      </div><!-- /.box-body -->
    </div><!-- /.box -->
  </div><!-- /.col -->
</div>