
<div id="loading"></div>
<div id="winpopup"></div>
<section class="content-header">
    <h1>TỔNG HỢP CÔNG NỢ PHẢI TRẢ</h1>
  <ol class="breadcrumb">
    <li><a href="<?php echo $this->url('admin') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><a href="<?php echo $this->url('payable') ?>">Nợ phải trả</a></li>
  </ol>
</section>
<div id="content" style="padding:5px;">

    <div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
        
        <div class="add-box">
            <select id="sl_round" name="sl_round" style="width:90px">
             <?php 
                for ($k=1; $k < 13; $k++) { 
                    echo '<option value="'.$k.'">Tháng '.$k.'</option>';
                }
             ?>
            </select>
            <select id="sl_staff" name="sl_staff" style="width:100px">
             <?php 
                $nam = date('Y');
                for ($k=($nam-5); $k < ($nam+5); $k++) { 
                    echo '<option value="'.$k.'">Năm '.$k.'</option>';
                }
             ?>
            </select>

            <input type="button" name="xem" id="xem" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  
            
        </div>
    </div>
    <div class="tablenav top">
        <div class="add-box">
                  
            Từ  <input style="width:80px" type="search" name="batdau" id="batdau" placeholder="Chọn ngày" <?php if(isset($batdau)) echo "value='$batdau'"; ?> >  
            Đến  <input style="width:80px" type="search" name="ketthuc" id="ketthuc" placeholder="Chọn ngày" <?php if(isset($ketthuc)) echo "value='$ketthuc'"; ?> >  
             <input type="button" name="xem" id="xem" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  
            
        </div>

      </div>
    <div class="tablenav top">
      <div style="clear:both"></div>
      <?php if(!isset($disable_control)){ ?>
        <div class="add-box"><a class="add_button" id="btnExport" ><i class="fa fa-download"></i> Xuất</a></div>
        <?php } ?>


      </div>

</div>

<div class="tabs">
  <ul class="tab-links">
    <li class="active"  ><a href="#tab1"><i class="fa fa-briefcase"></i> Khách hàng</a></li>
    <li ><a href="#tab2"><i class="fa fa-user"></i> Nhân viên</a></li>
    <li ><a href="#tab3"><i class="fa fa-user-secret"></i> Tài xế</a></li>
    <li ><a href="#tab4"><i class="fa fa-road"></i> Cầu đường</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab active" id="tab1" >
        <div class="add-box"><a class="add_button" id="btnExport" ><i class="fa fa-download"></i> Xuất</a></div>
            <table class="table_data" id="tblExport">
            <thead>
                <tr>
                    <th rowspan="2" class="fix">
                    <a>STT </a>
                    </th>
                    <th rowspan="2" class="fix">
                        <a >Mã KH</a>
                    </th>
                    <th rowspan="2" class="fix">
                        <a >Tên khách hàng</a>
                    </th>
                    <th colspan="2" class="fix">
                        <a >Số dư đầu kỳ</a>
                    </th>
                    <th colspan="2" class="fix">
                        <a >Số phát sinh</a>
                    </th>
                    <th colspan="2" class="fix">
                        <a >Số dư cuối kỳ</a>
                    </th>
                    
                </tr>
                <tr>
                    <th class="fix">
                        <a >Nợ</a>
                    </th>
                    <th class="fix">
                        <a >Có</a>
                    </th>
                    <th class="fix">
                        <a >Nợ</a>
                    </th>
                    <th class="fix">
                        <a >Có</a>
                    </th>
                    <th class="fix">
                        <a >Nợ</a>
                    </th>
                    <th class="fix">
                        <a >Có</a>
                    </th>
                </tr>
               </thead>
               <tbody>
                <?php $tongnodauky = 0; $tongcodauky = 0; $tongnophatsinh = 0; $tongcophatsinh = 0; $tongnocuoiky = 0; $tongcocuoiky = 0;
                $i = 1;
                foreach ($customers as $customer) : 

                    $nodauky = isset($data_old['customer'][$customer->customer_id])&&$data_old['customer'][$customer->customer_id]>=0?$data_old['customer'][$customer->customer_id]:null;
                    $codauky = isset($data_old['customer'][$customer->customer_id])&&$data_old['customer'][$customer->customer_id]<0?$data_old['customer'][$customer->customer_id]:null;
                    $nophatsinh = isset($data_new['customer'][$customer->customer_id]['no'])?$data_new['customer'][$customer->customer_id]['no']:null;
                    $cophatsinh = isset($data_new['customer'][$customer->customer_id]['co'])?$data_new['customer'][$customer->customer_id]['co']:null;
                    $cuoiky = $nodauky + $nophatsinh - $codauky - $cophatsinh;
                    $nocuoiky = $cuoiky>=0?$cuoiky:null;
                    $cocuoiky = $cuoiky<0?$cuoiky:null;

                    $tongnodauky += $nodauky; 
                    $tongcodauky += $codauky; 
                    $tongnophatsinh += $nophatsinh; 
                    $tongcophatsinh += $cophatsinh; 
                    $tongnocuoiky += $nocuoiky; 
                    $tongcocuoiky += $cocuoiky;

                    if ($nodauky > 0 || $codauky > 0 || $nophatsinh > 0 || $cophatsinh > 0) {
                ?>
                    <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $customer->customer_id ?>" class="edit_tr">
                        <td class="fix"><?php echo $i++; ?></td>
                        <td class="fix"  id="customer_code_<?php echo $customer->customer_id; ?>"><a target="_blank" href="<?php echo $this->url('customer/index/'.$customer->customer_id) ?>" ><?php echo $customer->customer_code ?></a></td>
                        <td class="fix"  id="customer_name_<?php echo $customer->customer_id; ?>"><?php echo $customer->customer_name ?></td>
                        <td class="fix" ><?php echo $lib->formatMoney($nodauky) ?></td>
                        <td class="fix" ><?php echo $lib->formatMoney($codauky) ?></td>
                        <td class="fix" ><?php echo $lib->formatMoney($nophatsinh) ?></td>
                        <td class="fix" ><?php echo $lib->formatMoney($cophatsinh) ?></td>
                        <td class="fix" ><?php echo $lib->formatMoney($nocuoiky) ?></td>
                        <td class="fix" ><?php echo $lib->formatMoney($cocuoiky) ?></td>
                    </tr>
                <?php 
                    }

                endforeach; 
                ?>
                <tr style="font-weight:bold">
                    <td class="fix" colspan="3" >Tổng cộng</td>
                    <td class="fix" ><?php echo $lib->formatMoney($tongnodauky) ?></td>
                    <td class="fix" ><?php echo $lib->formatMoney($tongcodauky) ?></td>
                    <td class="fix" ><?php echo $lib->formatMoney($tongnophatsinh) ?></td>
                    <td class="fix" ><?php echo $lib->formatMoney($tongcophatsinh) ?></td>
                    <td class="fix" ><?php echo $lib->formatMoney($tongnocuoiky) ?></td>
                    <td class="fix" ><?php echo $lib->formatMoney($tongcocuoiky) ?></td>
                </tr>
               </tbody>
            </table>
        </div>
        <div class="tab" id="tab2" >
            <div class="add-box"><a class="add_button" id="btnExport2" ><i class="fa fa-download"></i> Xuất</a></div>
            <table class="table_data" id="tblExport2">
            <thead>
                <tr>
                    <th rowspan="2" class="fix">
                    <a>STT </a>
                    </th>
                    <th rowspan="2" class="fix">
                        <a >Mã NV</a>
                    </th>
                    <th rowspan="2" class="fix">
                        <a >Tên nhân viên</a>
                    </th>
                    <th colspan="2" class="fix">
                        <a >Số dư đầu kỳ</a>
                    </th>
                    <th colspan="2" class="fix">
                        <a >Số phát sinh</a>
                    </th>
                    <th colspan="2" class="fix">
                        <a >Số dư cuối kỳ</a>
                    </th>
                    
                </tr>
                <tr>
                    <th class="fix">
                        <a >Nợ</a>
                    </th>
                    <th class="fix">
                        <a >Có</a>
                    </th>
                    <th class="fix">
                        <a >Nợ</a>
                    </th>
                    <th class="fix">
                        <a >Có</a>
                    </th>
                    <th class="fix">
                        <a >Nợ</a>
                    </th>
                    <th class="fix">
                        <a >Có</a>
                    </th>
                </tr>
               </thead>
               <tbody>
                <?php $tongnodauky = 0; $tongcodauky = 0; $tongnophatsinh = 0; $tongcophatsinh = 0; $tongnocuoiky = 0; $tongcocuoiky = 0;
                $i = 1;
                foreach ($staffs as $staff) : 

                    $nodauky = isset($data_old['staff'][$staff->staff_id])&&$data_old['staff'][$staff->staff_id]>=0?$data_old['staff'][$staff->staff_id]:null;
                    $codauky = isset($data_old['staff'][$staff->staff_id])&&$data_old['staff'][$staff->staff_id]<0?$data_old['staff'][$staff->staff_id]:null;
                    $nophatsinh = isset($data_new['staff'][$staff->staff_id]['no'])?$data_new['staff'][$staff->staff_id]['no']:null;
                    $cophatsinh = isset($data_new['staff'][$staff->staff_id]['co'])?$data_new['staff'][$staff->staff_id]['co']:null;
                    $cuoiky = $nodauky + $nophatsinh - $codauky - $cophatsinh;
                    $nocuoiky = $cuoiky>=0?$cuoiky:null;
                    $cocuoiky = $cuoiky<0?$cuoiky:null;

                    $tongnodauky += $nodauky; 
                    $tongcodauky += $codauky; 
                    $tongnophatsinh += $nophatsinh; 
                    $tongcophatsinh += $cophatsinh; 
                    $tongnocuoiky += $nocuoiky; 
                    $tongcocuoiky += $cocuoiky;

                    if ($nodauky > 0 || $codauky > 0 || $nophatsinh > 0 || $cophatsinh > 0) {
                ?>
                    <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $staff->staff_id ?>" class="edit_tr">
                        <td class="fix"><?php echo $i++; ?></td>
                        <td class="fix"  id="staff_code_<?php echo $staff->staff_id; ?>"><a target="_blank" href="<?php echo $this->url('staff/index/'.$staff->staff_id) ?>" ><?php echo $staff->staff_code ?></a></td>
                        <td class="fix"  id="staff_name_<?php echo $staff->staff_id; ?>"><?php echo $staff->staff_name ?></td>
                        <td class="fix" ><?php echo $lib->formatMoney($nodauky) ?></td>
                        <td class="fix" ><?php echo $lib->formatMoney($codauky) ?></td>
                        <td class="fix" ><?php echo $lib->formatMoney($nophatsinh) ?></td>
                        <td class="fix" ><?php echo $lib->formatMoney($cophatsinh) ?></td>
                        <td class="fix" ><?php echo $lib->formatMoney($nocuoiky) ?></td>
                        <td class="fix" ><?php echo $lib->formatMoney($cocuoiky) ?></td>
                    </tr>
                <?php 
                    }

                endforeach; 
                ?>
                <tr style="font-weight:bold">
                    <td class="fix" colspan="3" >Tổng cộng</td>
                    <td class="fix" ><?php echo $lib->formatMoney($tongnodauky) ?></td>
                    <td class="fix" ><?php echo $lib->formatMoney($tongcodauky) ?></td>
                    <td class="fix" ><?php echo $lib->formatMoney($tongnophatsinh) ?></td>
                    <td class="fix" ><?php echo $lib->formatMoney($tongcophatsinh) ?></td>
                    <td class="fix" ><?php echo $lib->formatMoney($tongnocuoiky) ?></td>
                    <td class="fix" ><?php echo $lib->formatMoney($tongcocuoiky) ?></td>
                </tr>
               </tbody>
            </table>
        </div>
        <div class="tab" id="tab3" >
            <div class="add-box"><a class="add_button" id="btnExport3" ><i class="fa fa-download"></i> Xuất</a></div>
            <table class="table_data" id="tblExport3">
            <thead>
                <tr>
                    <th rowspan="2" class="fix">
                    <a>STT </a>
                    </th>
                    <th rowspan="2" class="fix">
                        <a >Mã TX</a>
                    </th>
                    <th rowspan="2" class="fix">
                        <a >Tên tài xế</a>
                    </th>
                    <th colspan="2" class="fix">
                        <a >Số dư đầu kỳ</a>
                    </th>
                    <th colspan="2" class="fix">
                        <a >Số phát sinh</a>
                    </th>
                    <th colspan="2" class="fix">
                        <a >Số dư cuối kỳ</a>
                    </th>
                    
                </tr>
                <tr>
                    <th class="fix">
                        <a >Nợ</a>
                    </th>
                    <th class="fix">
                        <a >Có</a>
                    </th>
                    <th class="fix">
                        <a >Nợ</a>
                    </th>
                    <th class="fix">
                        <a >Có</a>
                    </th>
                    <th class="fix">
                        <a >Nợ</a>
                    </th>
                    <th class="fix">
                        <a >Có</a>
                    </th>
                </tr>
               </thead>
               <tbody>
                <?php $tongnodauky = 0; $tongcodauky = 0; $tongnophatsinh = 0; $tongcophatsinh = 0; $tongnocuoiky = 0; $tongcocuoiky = 0;
                $i = 1;
                foreach ($steersmans as $steersman) : 

                    $nodauky = isset($data_old['steersman'][$steersman->steersman_id])&&$data_old['steersman'][$steersman->steersman_id]>=0?$data_old['steersman'][$steersman->steersman_id]:null;
                    $codauky = isset($data_old['steersman'][$steersman->steersman_id])&&$data_old['steersman'][$steersman->steersman_id]<0?$data_old['steersman'][$steersman->steersman_id]:null;
                    $nophatsinh = isset($data_new['steersman'][$steersman->steersman_id]['no'])?$data_new['steersman'][$steersman->steersman_id]['no']:null;
                    $cophatsinh = isset($data_new['steersman'][$steersman->steersman_id]['co'])?$data_new['steersman'][$steersman->steersman_id]['co']:null;
                    $cuoiky = $nodauky + $nophatsinh - $codauky - $cophatsinh;
                    $nocuoiky = $cuoiky>=0?$cuoiky:null;
                    $cocuoiky = $cuoiky<0?$cuoiky:null;

                    $tongnodauky += $nodauky; 
                    $tongcodauky += $codauky; 
                    $tongnophatsinh += $nophatsinh; 
                    $tongcophatsinh += $cophatsinh; 
                    $tongnocuoiky += $nocuoiky; 
                    $tongcocuoiky += $cocuoiky;

                    if ($nodauky > 0 || $codauky > 0 || $nophatsinh > 0 || $cophatsinh > 0) {
                ?>
                    <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $steersman->steersman_id ?>" class="edit_tr">
                        <td class="fix"><?php echo $i++; ?></td>
                        <td class="fix"  id="steersman_code_<?php echo $steersman->steersman_id; ?>"><a target="_blank" href="<?php echo $this->url('steersman/index/'.$steersman->steersman_id) ?>" ><?php echo $steersman->steersman_code ?></a></td>
                        <td class="fix"  id="steersman_name_<?php echo $steersman->steersman_id; ?>"><?php echo $steersman->steersman_name ?></td>
                        <td class="fix" ><?php echo $lib->formatMoney($nodauky) ?></td>
                        <td class="fix" ><?php echo $lib->formatMoney($codauky) ?></td>
                        <td class="fix" ><?php echo $lib->formatMoney($nophatsinh) ?></td>
                        <td class="fix" ><?php echo $lib->formatMoney($cophatsinh) ?></td>
                        <td class="fix" ><?php echo $lib->formatMoney($nocuoiky) ?></td>
                        <td class="fix" ><?php echo $lib->formatMoney($cocuoiky) ?></td>
                    </tr>
                <?php 
                    }

                endforeach; 
                ?>
                <tr style="font-weight:bold">
                    <td class="fix" colspan="3" >Tổng cộng</td>
                    <td class="fix" ><?php echo $lib->formatMoney($tongnodauky) ?></td>
                    <td class="fix" ><?php echo $lib->formatMoney($tongcodauky) ?></td>
                    <td class="fix" ><?php echo $lib->formatMoney($tongnophatsinh) ?></td>
                    <td class="fix" ><?php echo $lib->formatMoney($tongcophatsinh) ?></td>
                    <td class="fix" ><?php echo $lib->formatMoney($tongnocuoiky) ?></td>
                    <td class="fix" ><?php echo $lib->formatMoney($tongcocuoiky) ?></td>
                </tr>
               </tbody>
            </table>
        </div>
        <div class="tab" id="tab4" >
            <div class="add-box"><a class="add_button" id="btnExport4" ><i class="fa fa-download"></i> Xuất</a></div>
            <table class="table_data" id="tblExport4">
            <thead>
                <tr>
                    <th rowspan="2" class="fix">
                    <a>STT </a>
                    </th>
                    <th rowspan="2" class="fix">
                        <a >Tên</a>
                    </th>
                    <th rowspan="2" class="fix">
                        <a >MST</a>
                    </th>
                    <th colspan="2" class="fix">
                        <a >Số dư đầu kỳ</a>
                    </th>
                    <th colspan="2" class="fix">
                        <a >Số phát sinh</a>
                    </th>
                    <th colspan="2" class="fix">
                        <a >Số dư cuối kỳ</a>
                    </th>
                    
                </tr>
                <tr>
                    <th class="fix">
                        <a >Nợ</a>
                    </th>
                    <th class="fix">
                        <a >Có</a>
                    </th>
                    <th class="fix">
                        <a >Nợ</a>
                    </th>
                    <th class="fix">
                        <a >Có</a>
                    </th>
                    <th class="fix">
                        <a >Nợ</a>
                    </th>
                    <th class="fix">
                        <a >Có</a>
                    </th>
                </tr>
               </thead>
               <tbody>
                <?php $tongnodauky = 0; $tongcodauky = 0; $tongnophatsinh = 0; $tongcophatsinh = 0; $tongnocuoiky = 0; $tongcocuoiky = 0;
                $i = 1;
                foreach ($tolls as $toll) : 

                    $nodauky = isset($data_old['toll'][$toll->toll_id])&&$data_old['toll'][$toll->toll_id]>=0?$data_old['toll'][$toll->toll_id]:null;
                    $codauky = isset($data_old['toll'][$toll->toll_id])&&$data_old['toll'][$toll->toll_id]<0?$data_old['toll'][$toll->toll_id]:null;
                    $nophatsinh = isset($data_new['toll'][$toll->toll_id]['no'])?$data_new['toll'][$toll->toll_id]['no']:null;
                    $cophatsinh = isset($data_new['toll'][$toll->toll_id]['co'])?$data_new['toll'][$toll->toll_id]['co']:null;
                    $cuoiky = $nodauky + $nophatsinh - $codauky - $cophatsinh;
                    $nocuoiky = $cuoiky>=0?$cuoiky:null;
                    $cocuoiky = $cuoiky<0?$cuoiky:null;

                    $tongnodauky += $nodauky; 
                    $tongcodauky += $codauky; 
                    $tongnophatsinh += $nophatsinh; 
                    $tongcophatsinh += $cophatsinh; 
                    $tongnocuoiky += $nocuoiky; 
                    $tongcocuoiky += $cocuoiky;

                    if ($nodauky > 0 || $codauky > 0 || $nophatsinh > 0 || $cophatsinh > 0) {
                ?>
                    <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $toll->toll_id ?>" class="edit_tr">
                        <td class="fix"><?php echo $i++; ?></td>
                        <td class="fix"  id="toll_name_<?php echo $toll->toll_id; ?>"><a target="_blank" href="<?php echo $this->url('toll/index/'.$toll->toll_id) ?>" ><?php echo $toll->toll_name ?></a></td>
                        <td class="fix"  id="toll_mst_<?php echo $toll->toll_id; ?>"><?php echo $toll->toll_mst ?></td>
                        <td class="fix" ><?php echo $lib->formatMoney($nodauky) ?></td>
                        <td class="fix" ><?php echo $lib->formatMoney($codauky) ?></td>
                        <td class="fix" ><?php echo $lib->formatMoney($nophatsinh) ?></td>
                        <td class="fix" ><?php echo $lib->formatMoney($cophatsinh) ?></td>
                        <td class="fix" ><?php echo $lib->formatMoney($nocuoiky) ?></td>
                        <td class="fix" ><?php echo $lib->formatMoney($cocuoiky) ?></td>
                    </tr>
                <?php 
                    }

                endforeach; 
                ?>
                <tr style="font-weight:bold">
                    <td class="fix" colspan="3" >Tổng cộng</td>
                    <td class="fix" ><?php echo $lib->formatMoney($tongnodauky) ?></td>
                    <td class="fix" ><?php echo $lib->formatMoney($tongcodauky) ?></td>
                    <td class="fix" ><?php echo $lib->formatMoney($tongnophatsinh) ?></td>
                    <td class="fix" ><?php echo $lib->formatMoney($tongcophatsinh) ?></td>
                    <td class="fix" ><?php echo $lib->formatMoney($tongnocuoiky) ?></td>
                    <td class="fix" ><?php echo $lib->formatMoney($tongcocuoiky) ?></td>
                </tr>
               </tbody>
            </table>
        </div>
    </div>
</div>

<style type="text/css">
    #ui-datepicker-div{
        font-size: 13px;
    }
</style>
<script type="text/javascript">
    $(function() {
    var pickerOpts = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#ketthuc" ).datepicker( "option", "minDate", selectedDate );

         },
         
    };  
    $("#batdau").datepicker(pickerOpts);

    var pickerOpts4 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#batdau" ).datepicker( "option", "maxDate", selectedDate );
                
         },
         
    };  
    $("#ketthuc").datepicker(pickerOpts4);
              
            
    
});

var v = "<?php echo $vong ?>";
$('#sl_round option[value='+v+']').attr('selected','selected');

var tt = "<?php echo $trangthai ?>";
$('#sl_staff option[value='+tt+']').attr('selected','selected');

</script>
<script type="text/javascript">
    
    $('#sl_round').change(function(){
        var m = $(this).val();
        var y = $('#sl_staff').val();
        var firstDay = new Date(y, m-1, 1);
        var lastDay = new Date(y, m, 0);

        $('#batdau').datepicker("setDate", firstDay );
        $('#ketthuc').datepicker("setDate", lastDay );

    });

    $('#sl_staff').change(function(){
        var y = $(this).val();
        var m = $('#sl_round').val();
        var firstDay = new Date(y, m-1, 1);
        var lastDay = new Date(y, m, 0);

        $('#batdau').datepicker("setDate", firstDay );
        $('#ketthuc').datepicker("setDate", lastDay );

    });


$(document).ready(function () {
    $("#btnExport2").click(function () {
        $("#tblExport2").battatech_excelexport({
            containerid: "tblExport2"
           , datatype: 'table'
        });
    });
    $("#btnExport3").click(function () {
        $("#tblExport3").battatech_excelexport({
            containerid: "tblExport3"
           , datatype: 'table'
        });
    });
    $("#btnExport4").click(function () {
        $("#tblExport4").battatech_excelexport({
            containerid: "tblExport4"
           , datatype: 'table'
        });
    });
});


jQuery(document).ready(function() {
    jQuery('.tabs .tab-links a').on('click', function(e)  {
        var currentAttrValue = jQuery(this).attr('href');

        var id = currentAttrValue.replace('#tab','');
        $('.tab_active').val(id);
        // Show/Hide Tabs
        jQuery('.tabs ' + currentAttrValue).addClass('active').siblings().removeClass('active');
        jQuery('.tabs ' + currentAttrValue).slideDown(300).siblings().slideUp(300);

 
        // Change/remove current tab to active
        jQuery(this).parent('li').addClass('active').siblings().removeClass('active');
 
        e.preventDefault();
    });

    jQuery('.tabs .tab-left a').on('click', function(e)  {
        var currentAttrValue = jQuery(this).attr('href');
 
        // Show/Hide Tabs
        jQuery('.tabs ' + currentAttrValue).addClass('active').siblings().removeClass('active');
        jQuery('.tabs ' + currentAttrValue).slideDown(300).siblings().slideUp(300);
 
        // Change/remove current tab to active
        jQuery(this).parent('li').addClass('active').siblings().removeClass('active');
 
        e.preventDefault();
    });
});
</script>