<html dir="ltr">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <style type="text/css">
            p{
                margin: 0px;
            }
        </style>
    </head>
    <body spellcheck="false">
        <div align="center" style="text-align:center">
            <span style="font-size:14.0pt;mso-bidi-font-size:13.0pt">CỘNG HOÀ XÃ HỘI CHỦ NGHĨA VIỆT NAM</span>
        </div>
        <div align="center" style="text-align:center">
            <b><span style="font-size:13.0pt">Độc lập – Tự do – Hạnh phúc</span></b>
        </div>
        <div align="center" style="text-align:center">
            <b><sup><span style="font-size:13.0pt">_______________________________</span></sup></b>
        </div>
        <div style="text-align:justify">
            <b><span style="font-size:13.0pt">&nbsp;</span></b>
        </div>
        <div align="center" style="text-align:center">
            <b><span style="font-size:18.0pt">HỢP ĐỒNG VẬN CHUYỂN</span></b>
        </div>
        <div align="center" style="text-align:center">
            <b><span style="font-size:13.0pt">Số: <span ><?php echo $contract_number ?></span></span></b>
        </div>
        <div style="text-align:justify">
            <b><span style="font-size:13.0pt">&nbsp;</span></b>
        </div>
        <div style="text-align:justify;line-height:120%">
            <span style="font-size:13.0pt;line-height:120%;mso-bidi-font-style:italic">Căn cứ Bộ Luật Dân sự của Nước Cộng Hoà Xã Hội Chủ Nghĩa Việt Nam;</span>
        </div>
        <div style="text-align:justify;line-height:120%">
            <span style="font-size:13.0pt;line-height:120%;mso-bidi-font-style:italic">Căn cứ Luật Thương Mại của Quốc hội Nước Cộng Hòa Xã Hội Chủ Nghĩa Việt Nam thông qua ngày 14/6/2005, có hiệu lực từ ngày 01/01/2006;
            </span>
        </div>
        <div style="text-align:justify;line-height:120%">
            <span style="font-size:13.0pt;line-height:120%;mso-bidi-font-style:italic">Căn cứ vào nhu cầu, khả năng của hai bên.
            </span>
        </div>
        <div style="text-align:justify;line-height:120%">
            <span style="font-size:13.0pt;line-height:120%;mso-bidi-font-style:italic">Hôm nay, ngày <span ><?php echo $contract_date[0] ?></span> tháng <span ><?php echo $contract_date[1] ?></span> năm <span ><?php echo $contract_date[2] ?></span> tại Công ty CP Tân Cảng Miền Trung chúng tôi gồm có:</span>
        </div>
        <div style="text-align:justify;tab-stops:1.0in">
            <span style="font-size:13.0pt;letter-spacing:-.3pt;layout-grid-mode:line">&nbsp;</span>
        </div>
        <div style="margin-top:6.0pt;text-align:justify;line-height:110%;tab-stops:1.0in">
            <b>
                <u>
                    <span style="font-size:13.0pt;line-height:110%;letter-spacing:-.3pt">BÊN A</span>
                </u>
            </b>
            <span style="font-size:13.0pt;line-height:110%;letter-spacing:-.3pt">: <b>CÔNG TY CỔ PHẦN TÂN CẢNG MIỀN TRUNG
(Bên cho thuê vận chuyển)</b>.<b><o:p></o:p></b></span></div><div style="text-align:justify;line-height:120%;tab-stops:1.0in"><span style="font-size:13.0pt;line-height:120%;letter-spacing:-.3pt;layout-grid-mode:
line">Địa chỉ:&nbsp;&nbsp; </span><span style="font-size:13.0pt;line-height:120%;letter-spacing:-.3pt">Khu vực 8,
Phường Hải Cảng, Thành phố Quy Nhơn, tỉnh Bình Định.<o:p></o:p></span></div><div style="text-align:justify;line-height:120%;tab-stops:1.0in 261.0pt"><span style="font-size:13.0pt;line-height:120%;letter-spacing:-.3pt;layout-grid-mode:
line">Điện thoại:&nbsp;&nbsp; 0563.891010&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Fax: 0563.891022<o:p></o:p></span></div><div style="text-align:justify;line-height:120%"><span style="font-size:13.0pt;line-height:120%;letter-spacing:-.3pt">Mã số thuế:&nbsp; 4101064504<o:p></o:p></span></div><div style="text-align:justify;line-height:120%"><span style="font-size:13.0pt;line-height:120%;letter-spacing:-.3pt">Tài khoản:&nbsp;&nbsp;&nbsp; 40111.6868.8888 tại&nbsp; NH TMCP Quân đội – CN Bình Định<o:p></o:p></span></div><div style="text-align:justify;line-height:120%;tab-stops:4.0in"><span style="font-size:13.0pt;line-height:120%;letter-spacing:-.3pt">Đại diện
(Ông/Bà):&nbsp;&nbsp;&nbsp;&nbsp; <b><i>Nguyễn Đình Khương&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </i></b>&nbsp;Chức vụ: Giám đốc<o:p></o:p></span></div><div style="text-align:justify;line-height:115%;mso-pagination:
none;tab-stops:.5in center 3.0in right 6.0in"><b><span style="font-size:13.0pt;line-height:115%;color:black;layout-grid-mode:
line">&nbsp;</span></b></div><div style="margin-top:6.0pt;text-align:justify;tab-stops:1.0in"><b><u><span style="font-size:13.0pt;letter-spacing:-.3pt">BÊN B</span></u></b><span style="font-size:13.0pt;letter-spacing:-.3pt">: </span><b><span style="font-size:13.0pt;"><?php echo $company ?></span></b><span style="font-size:10.0pt;font-family:&quot;Verdana&quot;,sans-serif;"><o:p></o:p></span></div><div style="margin-top:6.0pt;text-align:justify;tab-stops:1.0in"><span style="font-size:13.0pt;letter-spacing:-.3pt;layout-grid-mode:line">Địa
chỉ:&nbsp;&nbsp; </span><span style="font-size:13.0pt;
"><?php echo $address ?>.<o:p></o:p></span></div><div style="text-align:justify;tab-stops:78.0pt 92.15pt"><span style="font-size:13.0pt;">Điện thoại:&nbsp;&nbsp;
<?php echo $phone ?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Fax:
<?php echo $fax ?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<o:p></o:p></span></div><div style="text-align:justify;tab-stops:78.0pt 92.15pt"><span style="font-size:13.0pt;letter-spacing:-.3pt">Mã số thuế:&nbsp;&nbsp; <?php echo $mst ?><o:p></o:p></span></div><div style="text-align:justify;line-height:120%"><span style="font-size:13.0pt;line-height:120%;letter-spacing:-.3pt">Tài khoản:&nbsp;&nbsp;&nbsp; <?php if($bank_number!=""){  ?> <?php echo $bank_number ?> tại&nbsp; <?php echo $bank ?> – CN <?php echo $branch ?> <?php } ?></span></div><div style="text-align:justify;tab-stops:78.0pt 92.15pt"><span style="font-size:13.0pt;letter-spacing:-.3pt">Đại diện (Ông/Bà):&nbsp;&nbsp; <b><i><?php echo $name ?></i></b> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Chức
vụ: <?php echo $position ?><o:p></o:p></span></div><div style="text-align:justify;tab-stops:78.0pt 92.15pt"><span style="font-size:13.0pt;letter-spacing:-.3pt">&nbsp;</span></div><div style="text-align:justify;text-indent:.5in;line-height:120%"><span style="font-size:13.0pt;line-height:120%">Hai bên thỏa thuận thống nhất cùng ký
kết hợp đồng vận chuyển với nội dung như sau: <o:p></o:p></span></div><div style="text-align:justify;line-height:120%"><b><u><span style="font-size:13.0pt;
line-height:120%">ĐIỀU I</span></u></b><b><span style="font-size:13.0pt;line-height:120%">. NỘI DUNG HỢP ĐỒNG<o:p></o:p></span></b></div><div style="text-align:justify;text-indent:.5in;line-height:120%"><span style="font-size:13.0pt;line-height:120%">-&nbsp;
Bên B thuê bên A và bên A đồng ý vận chuyển hàng hóa cho bên B:<o:p></o:p></span></div><div style="text-align:justify;text-indent:.5in;line-height:120%"><span style="font-size:13.0pt;line-height:120%">-&nbsp;
Điểm đi: <span ><?php echo $from ?></span><o:p></o:p></span></div><div style="text-align:justify;text-indent:.5in;line-height:120%"><span style="font-size:13.0pt;line-height:120%">-&nbsp;
Điểm đến<span >: <?php echo $to ?></span><o:p></o:p></span></div><div style="text-align:justify;text-indent:.5in;line-height:120%"><b><i><span style="font-size:13.0pt;line-height:120%">Giá cước vận chuyển:</span></i></b><span style="font-size:13.0pt;line-height:120%"><o:p></o:p></span></div><div style="text-align:justify;text-indent:.5in;line-height:120%"><span style="font-size:13.0pt;line-height:120%">- Đơn giá: Được áp dụng trong bảng kê
xác nhận của hai bên theo từng đợt thỏa thuận.<o:p></o:p></span></div><div style="text-align:justify;text-indent:.5in;line-height:120%"><b><i><span style="font-size:13.0pt;line-height:120%">Phương thức giao nhận :<o:p></o:p></span></i></b></div><div class="MsoListParagraphCxSpFirst" style="margin-left:.75in;mso-add-space:auto;
text-align:justify;text-indent:-.25in;line-height:120%;mso-list:l0 level1 lfo1"><!--[if !supportLists]--><span style="font-size:13.0pt;line-height:120%">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span style="font-size:13.0pt;line-height:120%">Nguyên
cont, nguyên chì<b><o:p></o:p></b></span></div><div class="MsoListParagraphCxSpMiddle" style="margin-left:.75in;mso-add-space:
auto;text-align:justify;text-indent:-.25in;line-height:120%;mso-list:l0 level1 lfo1"><!--[if !supportLists]--><span style="font-size:13.0pt;line-height:120%">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span lang="VI" style="font-size:13.0pt;
line-height:120%;mso-ansi-language:VI">Công tác xếp dỡ ở cả hai đầu giao nhận
hàng do </span><span style="font-size:13.0pt;line-height:120%">bên B </span><span lang="VI" style="font-size:13.0pt;line-height:120%;mso-ansi-language:VI">chịu
trách nhiệm</span><span style="font-size:13.0pt;line-height:120%"><o:p></o:p></span></div><div class="MsoListParagraphCxSpLast" style="margin-left:.75in;mso-add-space:auto;
text-align:justify;text-indent:-.25in;line-height:120%;mso-list:l0 level1 lfo1"><!--[if !supportLists]--><span style="font-size:13.0pt;line-height:120%">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span style="font-size:13.0pt;line-height:120%">Đơn
giá tính theo chuyến tối đa 29 tấn<o:p></o:p></span></div><div style="text-align:justify;line-height:120%"><b><u><span style="font-size:13.0pt;
line-height:120%">ĐIỀU II</span></u></b><b><span style="font-size:13.0pt;line-height:120%">. PHƯƠNG THỨC THANH TOÁN<o:p></o:p></span></b></div><div style="text-align:justify;text-indent:.5in;line-height:120%"><b><span style="font-size:13.0pt;line-height:
120%">-</span></b><span style="font-size:13.0pt;line-height:120%"> Phương thức
thanh toán: Thanh toán bằng chuyển khoản qua Ngân hàng hoặc tiền mặt.<o:p></o:p></span></div><div style="text-align:justify;text-indent:.5in;line-height:120%"><span style="font-size:13.0pt;line-height:120%">- Bên B chịu trách nhiệm trả phí
thanh toán chuyển tiền qua ngân hàng.<o:p></o:p></span></div><div style="text-align:justify;text-indent:.5in;line-height:120%"><b><span style="font-size:13.0pt;line-height:
120%">- </span></b><span style="font-size:13.0pt;line-height:120%">Thời hạn
thanh toán: Bên B sẽ thanh toán cước vận chuyển cho bên A <span ><?php echo $contract_pay ?> </span>khi bên B nhận đủ hồ sơ thanh toán.&nbsp; <o:p></o:p></span></div><div style="text-align:justify;text-indent:.5in;line-height:120%"><span style="font-size:13.0pt;line-height:120%">- Sau khi giao hàng bên A gửi biên
bản xác nhận khối lượng vận chuyển cho bên B, bên&nbsp; B có trách nhiệm trả lời đối chiếu cho bên A
để làm căn cứ xuất hóa đơn GTGT.<o:p></o:p></span></div><div style="text-align:justify;text-indent:.5in;line-height:120%"><b><span style="font-size:13.0pt;line-height:
120%">-</span></b><span style="font-size:13.0pt;line-height:120%"> Hồ sơ thanh
toán bao gồm: <o:p></o:p></span></div><div style="text-align:justify;text-indent:.5in;line-height:120%"><span style="font-size:13.0pt;line-height:120%">+ Biên bản xác nhận khối lượng vận
chuyển.<o:p></o:p></span></div><div style="text-align:justify;text-indent:.5in;line-height:120%"><span style="font-size:13.0pt;line-height:120%">+ Hóa đơn VAT.<o:p></o:p></span></div><div style="text-align:justify;line-height:120%"><b><u><span style="font-size:13.0pt;
line-height:120%">ĐIỀU III</span></u></b><b><span style="font-size:13.0pt;line-height:120%">.TRÁCH NHIỆM CỦA MỖI BÊN<o:p></o:p></span></b></div><div style="text-align:justify;line-height:120%"><b><span style="font-size:13.0pt;line-height:
120%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3.1- Trách nhiệm của Bên A:<o:p></o:p></span></b></div><div style="text-align:justify;text-indent:.5in;line-height:120%"><b><span style="font-size:13.0pt;line-height:
120%">-</span></b><span style="font-size:13.0pt;line-height:120%"> Khi nhận
được yêu cầu vận chuyển của bên B, Bên A bố trí đầy đủ phương tiện đúng thời
gian theo yêu cầu của bên B. <o:p></o:p></span></div><div style="text-align:justify;line-height:120%"><span style="font-size:13.0pt;line-height:120%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <b>- </b>Chịu trách nhiệm vận chuyển hàng hóa
trong suốt lộ trình đến khi hoàn tất. Trong quá trình vận chuyển có mất mát, hư
hại về hàng hoá thì phải bồi thường giá trị của lô hàng bị thiệt hại tính theo
giá tại thời điểm xảy ra thiệt hại, khi có kết quả của cơ quan điều tra có thẩm
quyền ra quyết định.<o:p></o:p></span></div><div style="text-align:justify;text-indent:.5in;line-height:120%"><b><span style="font-size:13.0pt;line-height:
120%">- </span></b><span style="font-size:13.0pt;line-height:120%">Cung cấp và
hoàn trả cho bên B đầy đủ chứng từ hàng hóa, biên bản giao nhận hàng và các
chứng từ khác liên quan (nếu có).<o:p></o:p></span></div><div style="text-align:justify;text-indent:.5in;line-height:120%"><b><span style="font-size:13.0pt;line-height:
120%">- </span></b><span style="font-size:13.0pt;line-height:120%">Đảm bảo giấy
tờ hợp pháp của phương tiện vận chuyển theo quy định của Nhà nước.<o:p></o:p></span></div><div style="text-align:justify;text-indent:.5in;line-height:120%"><b><span style="font-size:13.0pt;line-height:
120%">-</span></b><span style="font-size:13.0pt;line-height:120%"> Cùng bên B
giải quyết các vấn đề liên quan đến từng chuyến hàng vì lợi ích của hai bên.<o:p></o:p></span></div><div style="text-align:justify;text-indent:.5in;line-height:120%"><b><span style="font-size:13.0pt;line-height:
120%">3.2- Trách nhiệm của Bên B:<o:p></o:p></span></b></div><div style="text-align:justify;text-indent:.5in;line-height:120%"><span style="font-size:13.0pt;line-height:120%">- Thông báo kế hoạch vận chuyển cho
bên A trước 48 giờ khi có nhu cầu vận chuyển để bên A sắp xếp, bố trí phương
tiện vận chuyển. Hình thức thông báo bằng văn bản, fax, điện thoại….<o:p></o:p></span></div><div style="text-align:justify;text-indent:.5in;line-height:120%"><span style="font-size:13.0pt;line-height:120%">- Mọi chi phí phát sinh về nâng
hạ, vệ sinh Con’t, bồi dưỡng (nếu có) bên A chi hộ cho bên B và Bên B có
chịu trách nhiệm thanh toán ngay các khoản phí trên sau khi vận chuyển
xong.<o:p></o:p></span></div><div style="text-align:justify;text-indent:.5in;line-height:120%"><b><span style="font-size:13.0pt;line-height:
120%">- </span></b><span style="font-size:13.0pt;line-height:120%">Chịu trách
nhiệm chuẩn bị đủ hàng hóa và đảm bảo sự hợp pháp của hàng hóa vận chuyển theo
quy định của Pháp luật hiện hành.<o:p></o:p></span></div><div style="text-align:justify;text-indent:.5in;line-height:120%"><b><span style="font-size:13.0pt;line-height:
120%">- </span></b><span style="font-size:13.0pt;line-height:120%">Tạo mọi điều
kiện cần thiết để Bên A đưa xe vào nhận và trả hàng.<o:p></o:p></span></div><div style="text-align:justify;line-height:120%"><b><span style="font-size:13.0pt;line-height:
120%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - </span></b><span style="font-size:13.0pt;line-height:120%">Cử cán bộ có đủ thẩm quyền có mặt
liên tục tại hiện trường trong thời gian giao nhận hàng tại đầu nguồn và cuối
nguồn để ký xác nhận các biên bản giao nhận và các thủ tục giấy tờ có liên
quan. Đồng thời phối hợp toàn diện với bên A để giải quyết các vướng mắc phát
sinh trong quá trình giao nhận, vận chuyển hàng hóa. Nếu quá thời gian nhận
hàng trên bên B phải trả phí lưu xe là 1.500.000 đồng/xe/ngày giá này chưa
bao gồm VAT.<o:p></o:p></span></div><div style="text-align:justify;line-height:120%"><b><span style="font-size:13.0pt;line-height:
120%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - </span></b><span style="font-size:13.0pt;line-height:120%">Chịu trách nhiệm mua bảo hiểm hàng
hóa trong quá trình vận chuyển bằng đường bộ.<o:p></o:p></span></div><div style="text-align:justify;text-indent:.5in;line-height:120%"><b><span style="font-size:13.0pt;line-height:
120%">- </span></b><span style="font-size:13.0pt;line-height:120%">Thanh toán
đầy đủ tiền cước vận chuyển theo đúng điều 2 của Hợp đồng này.<o:p></o:p></span></div><div style="text-align:justify;line-height:120%"><b><u><span style="font-size:13.0pt;
line-height:120%;letter-spacing:-.3pt">ĐIỀU IV</span></u></b><b><span style="font-size:13.0pt;line-height:
120%;letter-spacing:-.3pt">.&nbsp; NHỮNG
TRƯỜNG HỢP MIỄN TRỪ TRÁCH NHIỆM.<o:p></o:p></span></b></div><div style="text-align:justify;text-indent:.5in;line-height:120%"><span style="font-size:13.0pt;line-height:120%;letter-spacing:-.3pt">Những vi phạm
trong việc thực hiện hợp đồng mà nằm ngoài khả năng kiểm soát của các bên thì
sẽ được miễn trừ trách nhiệm trong trường hợp bất khả kháng sau:<o:p></o:p></span></div><div style="margin-left:.5in;text-align:justify;line-height:120%"><b><span style="font-size:13.0pt;line-height:
120%;letter-spacing:-.3pt">-</span></b><span style="font-size:13.0pt;
line-height:120%;letter-spacing:-.3pt"> Bão lụt và các thiên tai khác, dịch
bệnh.<o:p></o:p></span></div><div style="margin-left:.5in;text-align:justify;line-height:120%"><b><span style="font-size:13.0pt;line-height:
120%;letter-spacing:-.3pt">-</span></b><span style="font-size:13.0pt;
line-height:120%;letter-spacing:-.3pt"> Đình công, biểu tình, cháy nổ do bom
mìn, mìn còn tồn tại từ chiến tranh thì không <o:p></o:p></span></div><div style="text-align:justify;line-height:120%"><span style="font-size:13.0pt;line-height:120%;letter-spacing:-.3pt">bên nào bị xem
là đã vi phạm hợp đồng<o:p></o:p></span></div><div style="text-align:justify;line-height:120%"><b><u><span style="font-size:13.0pt;
line-height:120%">ĐIỀU V</span></u></b><b><span style="font-size:13.0pt;line-height:120%">. GIẢI QUYẾT TRANH CHẤP</span></b><span style="font-size:13.0pt;line-height:120%;letter-spacing:-.3pt"><o:p></o:p></span></div><div style="text-align:justify;text-indent:.5in;line-height:120%"><b><span style="font-size:13.0pt;line-height:
120%">- </span></b><span style="font-size:13.0pt;line-height:120%">Hai bên cam
kết thực hiện nghiêm chỉnh các điều khoản đã thoả thuận trong&nbsp; hợp đồng này. Trong quá trình thực hiện hợp
đồng, nếu có vướng mắc hai bên sẽ gặp nhau để giải quyết các tranh chấp phát
sinh thông qua thương lượng hòa giải.<o:p></o:p></span></div><div style="text-align:justify;text-indent:.5in;line-height:120%"><b><span style="font-size:13.0pt;line-height:
120%">-</span></b><span style="font-size:13.0pt;line-height:120%"> Trường hợp
xảy ra tranh chấp không thể giải quyết được bằng thương lượng hòa giải thì
tranh chấp sẽ đưa ra Tòa án Quân Đội để xét xử. Quyết định của Tòa án là phán
quyết cuối cùng mà hai bên phải thi hành. Mọi chi phí phát sinh sẽ do bên thua
kiện chịu.<o:p></o:p></span></div><div style="text-align:justify;line-height:120%"><b><u><span style="font-size:13.0pt;
line-height:120%;letter-spacing:-.3pt">ĐIỀU VI</span></u></b><b><span style="font-size:13.0pt;line-height:
120%;letter-spacing:-.3pt">. ĐIỀU KHOẢN CHUNG<o:p></o:p></span></b></div><div style="text-align:justify;line-height:120%"><b><span style="font-size:13.0pt;line-height:
120%;letter-spacing:-.3pt">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - </span></b><span style="font-size:13.0pt;line-height:120%;letter-spacing:-.3pt">Hai bên cam kết
thực hiện đúng các điều khoản trong hợp đồng. Trong trường hợp có khó khăn trở
ngại sẽ cùng nhau thương lượng giải quyết, mọi thay đổi bổ sung phải có sự
thống nhất giữa hai bên bằng văn bản.<o:p></o:p></span></div><div style="text-align:justify;line-height:120%"><span style="font-size:13.0pt;line-height:120%;letter-spacing:-.3pt">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><b><span style="font-size:13.0pt;line-height:120%">-</span></b><span style="font-size:13.0pt;line-height:120%"> Không vận chuyển hàng Quốc cấm theo
Quyết Định của Nhà Nước ban hành.&nbsp;&nbsp;&nbsp;&nbsp; <o:p></o:p></span></div><div style="text-align:justify;text-indent:.5in;line-height:120%"><b><span style="font-size:13.0pt;line-height:
120%">- </span></b><span style="font-size:13.0pt;line-height:120%">Không được
đơn phương chấm dứt Hợp đồng, nếu một bên muốn chấm dứt hợp đồng trước thời hạn
thì phải báo cho bên kia trước 30 ngày bằng văn bản.<o:p></o:p></span></div><div style="text-align:justify;text-indent:.5in;line-height:120%"><b><span style="font-size:13.0pt;line-height:
120%">-</span></b><span style="font-size:13.0pt;line-height:120%"> Hợp đồng này
có hiệu lực từ ngày ký đến ngày <span ><?php echo $contract_valid ?></span> và
sau khi hết thời gian thực hiện hợp đồng, hai bên đã thực hiện đầy đủ mọi nghĩa
vụ, quyền lợi và không còn vấn đề gì vướng mắc, phát sinh thì hợp đồng xem như
được thanh lý. Nếu hai bên có nhu cầu ký tiếp hợp đồng sẽ thống nhất bằng phụ
lục hoặc cùng lập hợp đồng mới.<o:p></o:p></span></div><div style="text-align:justify;text-indent:.5in;line-height:120%"><b><span style="font-size:13.0pt;line-height:
120%">-</span></b><span style="font-size:13.0pt;line-height:120%"> Hợp đồng này
được lập thành hai (02) bản, mỗi bên giữ 01 (một) bản có giá trị pháp lý như
nhau.&nbsp;&nbsp;&nbsp;&nbsp; <o:p></o:p></span></div><div style="text-align:justify"><span style="font-size:13.0pt">&nbsp;</span></div><div></div>
<div style="text-align:justify;tab-stops:center 373.5pt"><b><span style="font-size:13.0pt">&nbsp;ĐẠI DIỆN BÊN A&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ĐẠI
DIỆN BÊN B</span></b><span style="font-size:13.0pt"><o:p></o:p></span></div>
</body>
</html>

<?php
header("Content-type: application/x-ms-download");

header("Content-Disposition: attachment; filename=HOP DONG.doc");

header('Cache-Control: public');
?>