<?php $i=1; ?>
<center ><h1> LÔ HÀNG ĐÃ NHẬN </h1></center>

<table class="table_data">
<thead>
    <tr>
    	
        <th  class="fix" >
            <a class="sort" >STT </a>
        </th>
        
        <th  class="fix">
            <a class="sort">Ngày </a>
        </th>
        <th  class="fix">
            <a class="sort" >Số lượng xe </a>
        </th>
        <th  class="fix">
            <a class="sort" >Số lượng </a>
        </th>
        
        <th  class="fix">
            <a class="sort" >ĐVT </a>
        </th>
        <th  class="fix">
            <a class="sort" >Người nhận </a>
        </th>
        
        <th  class="fix">
            <a class="sort" >Trạng thái </a>
        </th>
    </tr>
    
   </thead>
   <tbody>
    <?php foreach ($shipment_temps as $shipment_temp) : ?>
    
        
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $shipment_temp->shipment_temp_id ?>" class="edit_tr">
            
            <td  class="fix"><?php echo $i++; ?></td>
            <td class="fix" id="shipment_temp_date_<?php echo $shipment_temp->shipment_temp_id; ?>"><?php echo $lib->hien_thi_ngay_thang($shipment_temp->shipment_temp_date); ?></td>
            
            <td class="fix" id="shipment_temp_number_<?php echo $shipment_temp->shipment_temp_id; ?>"><?php echo $shipment_temp->shipment_temp_number; ?></td>
            <td class="fix" id="shipment_temp_ton_<?php echo $shipment_temp->shipment_temp_id; ?>"><?php echo $shipment_temp->shipment_temp_ton; ?></td>
            <td class="fix" id="shipment_temp_cont_unit_<?php echo $shipment_temp->shipment_temp_id; ?>"><?php echo $shipment_temp->cont_unit_name; ?></td>
            <td class="fix" id="owner_<?php echo $shipment_temp->shipment_temp_id; ?>"><?php echo $shipment_temp->username; ?></td>
            
            <td class="fix" style="color: <?php echo $shipment_temp->shipment_temp_status==1?"red":"green"; ?>" id="shipment_temp_status_<?php echo $shipment_temp->shipment_temp_id; ?>"><?php echo $shipment_temp->shipment_temp_status==1?"Đã chạy":"Chưa chạy"; ?></td>
            
        </tr>


    <?php endforeach; ?>
     
   </tbody>
</table>
