<script type="text/javascript">
$(document).ready(function(){
	
			// Validate form
			$("#edit_user").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
        ignore: "",
        rules: {
          username: { rangelength: [2,10] }, //Chiều dài chuỗi trong khoảng từ 4 - 10 ký tự
          password: { rangelength: [4,16] },
          confirmpassword: {
            equalTo: "#password" //So sánh với trường cpassword với thành trường có id là password
          },
        },
        errorPlacement: function (error, element) {
          if(element.is('input[type=checkbox]') || element.is('input[type=radio]')) {
            var controls = element.closest('div[class*="col-"]');
            if(controls.find(':checkbox,:radio').length > 1) controls.append(error);
            else error.insertAfter(element.nextAll('.lbl:eq(0)').eq(0));
          }
          else if(element.is('.select2')) {
            error.insertAfter(element.siblings('[class*="select2-container"]:eq(0)'));
          }
          else if(element.is('.chosen-select')) {
            error.insertAfter(element.siblings('[class*="chosen-container"]:eq(0)'));
          }
          else error.insertAfter(element.parent());
        },
        submitHandler: function(form) {
                
          var user_id = "<?php echo $user_id ?>";
          var password = $('#password').val();
          var role = $('#role').val();
          var userlock = $('input[name="userlock"]:checked').val();
          var user_email = $('#user_email').val();
          
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/user/edituser", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: {
                  user_id: user_id,
                  password: password,
                  role: role,
                  userlock: userlock,
                  user_email: user_email,
                  }, // giá trị post
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error_user').hide();
                  $('#error_user').slideToggle(100); // hiển thị thẻ div success
                  $('#error_user').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error_user').fadeOut(10000);

              }
          });
          return false;
           
       }
					 
				 
			});
	
});
</script>

        <div class="login_body">
         
              <form id="edit_user" method="post" action="" autocomplete="off">
                  <table style="margin-top:20px;">
                    
                    <tr>
                        <td>Mật khẩu mới</td>
                        <td><input type="password" id="password" name="password" tabindex="1" autofocus ></td>
                        
                    </tr>
                    <tr>
                        <td>Nhập lại mật khẩu mới</td>
                        <td><input type="password" id="confirmpassword" name="confirmpassword" tabindex="2" ></td>
                    </tr>
                    <tr>
                        <td>Email khôi phục</td>
                        <td><input type="email" id="user_email" name="user_email" tabindex="3" value="<?php echo $user_email ?>" ></td>
                        
                    </tr>
                    <tr>
                        <td>Quyền </td>
                        <td>
                          <select name="role" id="role" tabindex="4" required="required">
                            <option value="<?php echo $user_role->role_id; ?>"><?php echo $user_role->role_name; ?></option>
                            <?php
                            foreach ($role as $role) {
                              echo '<option value="'.$role->role_id.'">'.$role->role_name.'</option>';
                            }
                            ?>
                          </select>
                        </td>
                    </tr>
                    <tr>
                        <td>Trạng thái</td>
                        <td>
                          <input type="radio" name="userlock" tabindex="5" value="1"> Khóa
                          <input type="radio" name="userlock" tabindex="6" value="0" checked> Mở
                        </td>
                    </tr>
                    
                </table> 
            </form>
        </div>
        <div id="error_user" class="error"><?php echo isset($error) ? $error : null; ?></div>


