<script type="text/javascript">
$(document).ready(function(){
	
			// Validate form
			$("#edit").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
				rules: {
					username: { rangelength: [2,10] }, //Chiều dài chuỗi trong khoảng từ 4 - 10 ký tự
					password: { rangelength: [4,16] },
					confirmpassword: {
            equalTo: "#password" //So sánh với trường cpassword với thành trường có id là password
          },
				}
					 
				 
			});
	
});
</script>
<div class="login_form">
        <div class="goback"><a href="<?php echo $this->url('user') ?>">&larr;</a></div>
        <div class="login_body">
          <h1>CẬP NHẬT TÀI KHOẢN</h1>
              <form id="edit" method="post" action="">
                  <table style="margin-top:20px;">
                    
                    <tr>
                        <td>Mật khẩu mới</td>
                        <td><input type="password" id="password" name="password" tabindex="1" autofocus ></td>
                        
                    </tr>
                    <tr>
                        <td>Nhập lại mật khẩu mới</td>
                        <td><input type="password" id="confirmpassword" name="confirmpassword" tabindex="2" ></td>
                    </tr>
                    
                    <tr>
                        <td>Quyền </td>
                        <td>
                          <select name="role" id="role" tabindex="4" required="required">
                            <option value="<?php echo $user_role->role_id; ?>"><?php echo $user_role->role_name; ?></option>
                            <?php
                            foreach ($role as $role) {
                              echo '<option value="'.$role->role_id.'">'.$role->role_name.'</option>';
                            }
                            ?>
                          </select>
                        </td>
                    </tr>
                    <tr>
                        <td>Trạng thái</td>
                        <td>
                          <input type="radio" name="userlock" tabindex="5" value="1"> Khóa
                          <input type="radio" name="userlock" tabindex="6" value="0" checked> Mở
                        </td>
                    </tr>
                    
                     <tr>
                        <td ><input type="reset" name="reset" value="Nhập lại" tabindex="6"></td>
                         <td><input type="submit" name="submit" value="Hoàn tất" tabindex="5"></td>
                         
                    </tr>
                </table> 
            </form>
        </div>
        <div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>
        </div>

