
<script type="text/javascript">
$(document).ready(function(){
	
			// Validate form
			$("#fogot").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
				
				}
					 
				 
			});
	
});
</script>
<div class="login_form">
        
        <div class="login_body">
          <h1>QUÊN MẬT KHẨU</h1>
           <form action="" method="post" id="fogot">
                  <table style="margin-top:20px;">
                    
                    <tr>
                        <td>Email </td>
                        <td><input type="email" id="username" name="email" tabindex="1" autofocus required="required"></td>
                    </tr>
                    
                     <tr colspan="2">
                         <td></td>
                         <td ><input type="submit" name="submit" value="Lấy lại mật khẩu" tabindex="2"></td>
                    </tr>
                </table> 
            </form>
        </div>
        <div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>
        </div>

