
<?php
$url_order = 'DESC';
if ($order_by == 'user_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
if ($order_by == 'username')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'create_time')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'role')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
$i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>
<section class="content-header">
    <h1>DANH SÁCH TÀI KHOẢN</h1>
  <ol class="breadcrumb">
    <li><a href="<?php echo $this->url('admin') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><a href="<?php echo $this->url('user') ?>">User</a></li>
  </ol>
</section>
<div id="content" style="padding:5px;">

	<div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
        <div class="add-box"><a class="add_button" href="<?php echo $this->url('user/add');?>"><i class="fa fa-plus"></i> Thêm mới</a></div>
    </div>
    <div class="tablenav top">
    
    	
    	<div class="alignleft actions">
			<select name="action" id="action">
            	<option value="-1" selected="selected">Chọn</option>
                
                <option value="delete">Xóa</option>
            </select>
            <input type="button" name="" id="doaction" class="button action" value="Áp dụng" onclick="action();">
		</div>
		<div class="alignleft actions">
		<select name="m" id="chonloc">
			<option  value="18446744073709">Hiển thị tất cả</option>
			<option value="5">Hiển thị 5 giá trị</option>
            <option value="10">Hiển thị 10 giá trị</option>
            <option value="15">Hiển thị 15 giá trị</option>
            <option selected="selected" value="20">Hiển thị 20 giá trị</option>
		</select>
		<input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">						 		
        </div>
      </div>
   
<table class="table_data">
<thead>
    <tr>
    	<th><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
        <th><a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','user_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'user_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a></th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','username','<?php echo $url_order ?>')">Username <?php if ($order_by == 'username'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','create_time','<?php echo $url_order ?>')">Ngày tạo <?php if ($order_by == 'create_time'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','role_name','<?php echo $url_order ?>')">Quyền <?php if ($order_by == 'role_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
            
           
        <th>&nbsp;</th>
    </tr>
   </thead>
   <tbody>
    <?php foreach ($users as $user) : ?>
        <tr id="<?php echo $user->user_id ?>" class="edit_tr">
        	<td><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $user->user_id ?>"></td>
            <td><?php echo $i++; ?></td>
            <td><?php echo $user->username; ?></td>
            <td><?php echo $lib->hien_thi_ngay_thang($user->create_time); ?></td>
            <td><?php echo $user->role_name; ?></td>
            
            <td class="pull-right">
                <button class="btn btn-sm btn-flat btn-primary" onclick="javascript:window.location.href='<?php echo $this->url("user/edit/$user->user_id") ?>'" ><i class="fa fa-edit"></i> Sửa</button>
                <button class="btn btn-sm btn-flat btn-danger" onclick="del(<?php echo $user->user_id ?>)" ><i class="fa fa-remove"></i> Xóa</button>
            </td>
        </tr>
    <?php endforeach; ?>
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>
</div>
<script type="text/javascript">
    var ch = "<?php echo $limit ?>";
$('#chonloc option[value='+ch+']').attr('selected','selected');
</script>