
<?php
$url_order = 'DESC';
if ($order_by == 'user_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
if ($order_by == 'username')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'create_time')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'role')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
$i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>
<div id="content" style="padding:5px;">
   
<table class="table_data">
<thead>
    <tr>
    	<th><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall" class="ace ace-checkbox-2" /><span class="lbl"></span></th>
        <th><a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','user_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'user_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a></th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','username','<?php echo $url_order ?>')">Username <?php if ($order_by == 'username'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','create_time','<?php echo $url_order ?>')">Ngày tạo <?php if ($order_by == 'create_time'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','role_name','<?php echo $url_order ?>')">Quyền <?php if ($order_by == 'role_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
            
           
        <th>
            <div class="tools action-buttons pull-right">
                <select name="m" id="chonloc" class="input-sm" onchange="limit_change($(this).val())">
                    <option value="18446744073709">All</option>
                    <option value="10">10</option>
                    <option value="20">20</option>
                    <option value="50">50</option>
                    <option value="100">100</option>
                    <option value="500">500</option>
                    <option value="1000">1000</option>
                </select>   
                <span class="ui-separator"></span>
                <a class="purpose" data-original-title="Thêm mới">
                    <i class="ace-icon fa fa-plus-circle bigger-150" onclick="add_click('<?php echo $this->url("user/add") ?>','Thêm tài khoản mới')"></i>
                </a>
                <a class="orange" data-original-title="Tìm kiếm">
                    <i class="ace-icon fa fa-search bigger-150" onclick="search_click()"></i>
                </a>
                <a class="green" data-original-title="Tải lại">
                    <i class="ace-icon fa fa-refresh bigger-150" onclick="refresh_click()"></i>
                </a>

                <a class="red" data-original-title="Xóa">
                    <i class="ace-icon fa fa-trash-o bigger-150" onclick="del_click()"></i>
                </a>                           
            </div>
        </th>
    </tr>
   </thead>
   <tbody>
    <?php foreach ($users as $user) : ?>
        <tr id="<?php echo $user->user_id ?>" class="edit_tr">
        	<td class="text-center"><input name="check[]" type="checkbox" class="checkbox ace" value="<?php echo $user->user_id ?>"><span class="lbl"></span></td>
            <td class="text-center"><?php echo $i++; ?></td>
            <td><?php echo $user->username; ?></td>
            <td><?php echo $lib->hien_thi_ngay_thang($user->create_time); ?></td>
            <td><?php echo $user->role_name; ?></td>
            
            <td class="text-right">
                <div class="tools action-buttons">
                    <a class="blue" href="<?php echo $this->url("user/edit/$user->user_id") ?>">
                        <i class="ace-icon fa fa-info-circle bigger-130"></i>
                    </a>

                    <a class="green" href="<?php echo $this->url("user/edit/$user->user_id") ?>">
                        <i class="ace-icon fa fa-pencil bigger-130"></i>
                    </a>

                    <a class="red" href="#">
                        <i class="ace-icon fa fa-trash-o bigger-130" onclick="del(<?php echo $user->user_id ?>)"></i>
                    </a>
                </div>
            </td>
        </tr>
    <?php endforeach; ?>
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>
</div>
<script type="text/javascript">
    var ch = "<?php echo $limit ?>";
$('#chonloc option[value='+ch+']').attr('selected','selected');
</script>