<script type="text/javascript">
$(document).ready(function(){
	
			// Validate form
			$("#edit").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
				rules: {
					password: { rangelength: [4,16] },
					confirmpassword: {
            equalTo: "#password" //So sánh với trường cpassword với thành trường có id là password
          },
				},
        submitHandler: function(form) {
                
          var user_id = "<?php echo $user_id ?>";
          var password = $('#password').val();
          var oldpassword = $('#oldpassword').val();
          
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/user/changepass", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: {
                  user_id: user_id,
                  password: password,
                  oldpassword: oldpassword,
                  }, // giá trị post
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error').hide();
                  $('#error').slideToggle(100); // hiển thị thẻ div success
                  $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error').fadeOut(10000);

              }
          });
          return false;
           
       }
					 
				 
			});
	
});
</script>
 
<div class="hr dotted"></div>
<div id="user-profile-2" class="user-profile">
  <div class="tabbable">
    <ul class="nav nav-tabs padding-18">
      <li class="active">
        <a data-toggle="tab" href="#home">
          <i class="green ace-icon fa fa-user bigger-120"></i>
          Thông tin tài khoản
        </a>
      </li>

      <li>
        <a data-toggle="tab" href="#feed">
          <i class="orange ace-icon fa fa-rss bigger-120"></i>
          Hoạt động
        </a>
      </li>

      <li>
        <a data-toggle="tab" href="#changepassword">
          <i class="blue ace-icon fa fa-key bigger-120"></i>
          Đổi mật khẩu
        </a>
      </li>

    </ul>

    <div class="tab-content no-border padding-24">
      <div id="home" class="tab-pane in active">
        <div class="row">
          <div class="col-xs-12 col-sm-3 center">
            <span class="profile-picture">
              <img class="editable img-responsive" alt="Alex's Avatar" id="avatar2" src="/public/assets/images/avatars/profile-pic.jpg" />
            </span>

            <div class="space space-4"></div>

            <div class="width-80 label label-info label-xlg arrowed-in arrowed-in-right">
                <div class="inline position-relative">
                  <a href="#" class="user-title-label dropdown-toggle" data-toggle="dropdown">
                    <i class="ace-icon fa fa-circle light-green"></i>
                    &nbsp;
                    <span class="white"><?php echo isset($staffs->staff_name)?$staffs->staff_name:'NONAME' ?></span>
                  </a>

                  <ul class="align-left dropdown-menu dropdown-caret dropdown-lighter">
                    <li class="dropdown-header"> Change Status </li>

                    <li>
                      <a href="#">
                        <i class="ace-icon fa fa-circle green"></i>
                        &nbsp;
                        <span class="green">Available</span>
                      </a>
                    </li>

                    <li>
                      <a href="#">
                        <i class="ace-icon fa fa-circle red"></i>
                        &nbsp;
                        <span class="red">Busy</span>
                      </a>
                    </li>

                    <li>
                      <a href="#">
                        <i class="ace-icon fa fa-circle grey"></i>
                        &nbsp;
                        <span class="grey">Invisible</span>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>

              <div class="profile-contact-info">
                <div class="profile-contact-links align-center">
                  <a href="#" class="btn btn-link">
                    <i class="ace-icon fa fa-black-tie bigger-120 green"></i>
                    <?php echo isset($positions)?$positions->position_name:null ?>
                  </a>

                  <a href="#" class="btn btn-link">
                    <i class="ace-icon fa fa-building bigger-120 pink"></i>
                    Phòng <?php echo isset($departments)?$departments->department_name:null ?>
                  </a>

                </div>

                <div class="space-6"></div>

                <div class="profile-social-links align-center">
                  <a href="#" class="tooltip-info" title="" data-original-title="Visit my Facebook">
                    <i class="middle ace-icon fa fa-facebook-square fa-2x blue"></i>
                  </a>

                  <a href="#" class="tooltip-info" title="" data-original-title="Visit my Twitter">
                    <i class="middle ace-icon fa fa-twitter-square fa-2x light-blue"></i>
                  </a>

                  <a href="#" class="tooltip-error" title="" data-original-title="Visit my G+">
                    <i class="middle ace-icon fa fa-google-plus-square fa-2x red"></i>
                  </a>
                </div>
              </div>
          </div><!-- /.col -->

          <div class="col-xs-12 col-sm-9">
            <div class="profile-user-info profile-user-info-striped">
              <div class="profile-info-row">
                <div class="profile-info-name"> Tên đăng nhập </div>

                <div class="profile-info-value">
                  <span class="editable" id="username"><?php echo $user_data->username ?></span>
                </div>
              </div>

              <div class="profile-info-row">
                <div class="profile-info-name"> Địa chỉ </div>

                <div class="profile-info-value">
                  <i class="fa fa-map-marker light-orange bigger-110"></i>
                  <span class="editable" id="address"><?php echo isset($staffs->staff_address)?$staffs->staff_address:null ?></span>
                </div>
              </div>

              <div class="profile-info-row">
                <div class="profile-info-name"> Ngày sinh </div>

                <div class="profile-info-value">
                  <span class="editable" id="age"><?php echo isset($staffs->staff_birthday)?$lib->hien_thi_ngay_thang($staffs->staff_birthday):null ?></span>
                </div>
              </div>
              <div class="profile-info-row">
                <div class="profile-info-name"> Điện thoại </div>

                <div class="profile-info-value">
                  <span class="editable" id="phone"><?php echo isset($staffs->staff_phone)?$staffs->staff_phone:null ?></span>
                </div>
              </div>
              <div class="profile-info-row">
                <div class="profile-info-name"> Email </div>

                <div class="profile-info-value">
                  <span class="editable" id="email"><?php echo isset($staffs->staff_email)?$staffs->staff_email:null ?></span>
                </div>
              </div>
              <div class="profile-info-row">
                <div class="profile-info-name"> Tham gia </div>

                <div class="profile-info-value">
                  <span class="editable" id="signup"><?php echo isset($staffs->staff_start_date)?$lib->hien_thi_ngay_thang($staffs->staff_start_date):null ?></span>
                </div>
              </div>

              <div class="profile-info-row">
                <div class="profile-info-name"> Truy cập lần cuối </div>

                <div class="profile-info-value">
                  <span class="editable" id="login"><?php echo $lib->time_elapsed_string(date('d-m-Y h:m:s',$user_data->lasted_online),2,'vi') ?></span>
                </div>
              </div>
            </div>

          </div><!-- /.col -->
        </div><!-- /.row -->

        <div class="space-20"></div>

        <div class="row">
          <div class="col-xs-12 col-sm-6">
            <div class="widget-box transparent">
              <div class="widget-header widget-header-small">
                <h4 class="widget-title smaller">
                  <i class="ace-icon fa fa-check-square-o bigger-110"></i>
                  Little About Me
                </h4>
              </div>

              <div class="widget-body">
                <div class="widget-main">
                  <span class="editable" id="about">
                    <p>
                      My job is mostly lorem ipsuming and dolor sit ameting as long as consectetur adipiscing elit.
                    </p>
                    <p>
                      Sometimes quisque commodo massa gets in the way and sed ipsum porttitor facilisis.
                    </p>
                    <p>
                      The best thing about my job is that vestibulum id ligula porta felis euismod and nullam quis risus eget urna mollis ornare.
                    </p>
                    <p>
                      Thanks for visiting my profile.
                    </p>
                  </span>
                </div>
              </div>
            </div>
          </div>

          <div class="col-xs-12 col-sm-6">
            <div class="widget-box transparent">
              <div class="widget-header widget-header-small header-color-blue2">
                <h4 class="widget-title smaller">
                  <i class="ace-icon fa fa-lightbulb-o bigger-120"></i>
                  My Skills
                </h4>
              </div>

              <div class="widget-body">
                <div class="widget-main padding-16">
                  <div class="clearfix">
                    <div class="grid3 center">
                      <div class="easy-pie-chart percentage" data-percent="45" data-color="#CA5952">
                        <span class="percent">45</span>%
                      </div>

                      <div class="space-2"></div>
                      Graphic Design
                    </div>

                    <div class="grid3 center">
                      <div class="center easy-pie-chart percentage" data-percent="90" data-color="#59A84B">
                        <span class="percent">90</span>%
                      </div>

                      <div class="space-2"></div>
                      HTML5 & CSS3
                    </div>

                    <div class="grid3 center">
                      <div class="center easy-pie-chart percentage" data-percent="80" data-color="#9585BF">
                        <span class="percent">80</span>%
                      </div>

                      <div class="space-2"></div>
                      Javascript/jQuery
                    </div>
                  </div>

                  <div class="hr hr-16"></div>

                  <div class="profile-skills">
                    <div class="progress">
                      <div class="progress-bar" style="width:80%">
                        <span class="pull-left">HTML5 & CSS3</span>
                        <span class="pull-right">80%</span>
                      </div>
                    </div>

                    <div class="progress">
                      <div class="progress-bar progress-bar-success" style="width:72%">
                        <span class="pull-left">Javascript & jQuery</span>

                        <span class="pull-right">72%</span>
                      </div>
                    </div>

                    <div class="progress">
                      <div class="progress-bar progress-bar-purple" style="width:70%">
                        <span class="pull-left">PHP & MySQL</span>

                        <span class="pull-right">70%</span>
                      </div>
                    </div>

                    <div class="progress">
                      <div class="progress-bar progress-bar-warning" style="width:50%">
                        <span class="pull-left">Wordpress</span>

                        <span class="pull-right">50%</span>
                      </div>
                    </div>

                    <div class="progress">
                      <div class="progress-bar progress-bar-danger" style="width:38%">
                        <span class="pull-left">Photoshop</span>

                        <span class="pull-right">38%</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div><!-- /#home -->

      <div id="feed" class="tab-pane">
        <div class="profile-feed row">
          <?php foreach ($user_logs as $log) { ?>
            <div class="col-sm-6">
              <div class="profile-activity clearfix">
                <div>
                  <img class="pull-left" src="/public/assets/images/avatars/avatar5.png" alt="Alex Doe's avatar">
                  <a class="user" href="#"> <?php echo $log->username ?> </a>
                  <?php echo $log->user_log_action ?>
                  <a href="#"><?php echo $log->user_log_table_name ?></a>

                  <div class="time">
                    <i class="ace-icon fa fa-clock-o bigger-110"></i>
                    <?php echo $lib->time_elapsed_string(date('d-m-Y h:m:s',$log->user_log_date),2,'vi') ?>
                  </div>
                </div>

                <div class="tools action-buttons">
                  <a href="#" class="blue">
                    <i class="ace-icon fa fa-pencil bigger-125"></i>
                  </a>

                  <a href="#" class="red">
                    <i class="ace-icon fa fa-times bigger-125"></i>
                  </a>
                </div>
              </div>
            </div><!-- /.col -->
          <?php } ?>
          
        </div><!-- /.row -->

        <div class="space-12"></div>

        <div class="center">
          <button type="button" class="btn btn-sm btn-primary btn-white btn-round">
            <i class="ace-icon fa fa-rss bigger-150 middle orange2"></i>
            <span class="bigger-110">View more activities</span>

            <i class="icon-on-right ace-icon fa fa-arrow-right"></i>
          </button>
        </div>
      </div><!-- /#feed -->

      <div id="changepassword" class="tab-pane">
        <div class="profile-users clearfix">
          <div class="login_body">
                <form id="edit" method="post" action="">
                    <table style="margin-top:20px;">
                      <tr>
                          <td>Mật khẩu cũ</td>
                          <td><input type="password" id="oldpassword" name="oldpassword" tabindex="1" autofocus ></td>
                          
                      </tr>
                      <tr>
                          <td>Mật khẩu mới</td>
                          <td><input type="password" id="password" name="password" tabindex="2" ></td>
                          
                      </tr>
                      <tr>
                          <td>Nhập lại mật khẩu mới</td>
                          <td><input type="password" id="confirmpassword" name="confirmpassword" tabindex="3" ></td>
                      </tr>
                      
                      
                       <tr>
                          <td ><input type="reset" name="reset" value="Nhập lại" tabindex="5"></td>
                           <td><input type="submit" name="submit" value="Hoàn tất" tabindex="4"></td>
                           
                      </tr>
                  </table> 
              </form>
          </div>
          <div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>
        </div>

        <div class="hr hr10 hr-double"></div>

      </div><!-- /#friends -->

    </div>
  </div>
</div>

<script type="text/javascript">
  jQuery(function($) {
  
    $(document).on("focus", ".input-mask-date", function () {
      $(this).mask('99/99/9999');
    });
    //editables 
    
    //text editable
    $('#username')
    .editable({
      type: 'text',
      name: 'username'    
      });
  
    $('#email')
    .editable({
      type: 'text',
      name: 'email'    
      });

    $('#phone')
    .editable({
      type: 'text',
      name: 'email'    
      });

    $('#address')
    .editable({
      type: 'text',
      name: 'email'    
      });
 
    
    //custom date editable
    $('#age').editable({
      type: 'adate',
      date: {
        //datepicker plugin options
            format: 'dd/mm/yyyy',
        viewformat: 'dd/mm/yyyy',
         weekStart: 1
         
         
        //,nativeUI: true//if true and browser support input[type=date], native browser control will be used
        //,format: 'yyyy-mm-dd',
        //viewformat: 'yyyy-mm-dd'
      },
      tpl: '<div class="input-group input-group-compact"><input type="text" class="input-medium date input-mask-date"><span class="input-group-addon"><i class="fa fa-calendar"></i></span></div>'
    });

    $('#signup').editable({
      type: 'adate',
      date: {
        //datepicker plugin options
            format: 'dd/mm/yyyy',
        viewformat: 'dd/mm/yyyy',
         weekStart: 1
         
         
        //,nativeUI: true//if true and browser support input[type=date], native browser control will be used
        //,format: 'yyyy-mm-dd',
        //viewformat: 'yyyy-mm-dd'
      },
      tpl: '<div class="input-group input-group-compact"><input type="text" class="input-medium date input-mask-date"><span class="input-group-addon"><i class="fa fa-calendar"></i></span></div>'
    });
  
  
    $('#about').editable({
      mode: 'inline',
          type: 'wysiwyg',
      name : 'about',
  
      wysiwyg : {
        //css : {'max-width':'300px'}
      },
      success: function(response, newValue) {
      }
    });
    
    
    
    // *** editable avatar *** //
    try {//ie8 throws some harmless exceptions, so let's catch'em
  
      //first let's add a fake appendChild method for Image element for browsers that have a problem with this
      //because editable plugin calls appendChild, and it causes errors on IE at unpredicted points
      try {
        document.createElement('IMG').appendChild(document.createElement('B'));
      } catch(e) {
        Image.prototype.appendChild = function(el){}
      }
  
      var last_gritter
      $('#avatar').editable({
        type: 'image',
        name: 'avatar',
        value: null,
        //onblur: 'ignore',  //don't reset or hide editable onblur?!
        image: {
          //specify ace file input plugin's options here
          btn_choose: 'Change Avatar',
          droppable: true,
          maxSize: 110000,//~100Kb
  
          //and a few extra ones here
          name: 'avatar',//put the field name here as well, will be used inside the custom plugin
          on_error : function(error_type) {//on_error function will be called when the selected file has a problem
            if(last_gritter) $.gritter.remove(last_gritter);
            if(error_type == 1) {//file format error
              last_gritter = $.gritter.add({
                title: 'File is not an image!',
                text: 'Please choose a jpg|gif|png image!',
                class_name: 'gritter-error gritter-center'
              });
            } else if(error_type == 2) {//file size rror
              last_gritter = $.gritter.add({
                title: 'File too big!',
                text: 'Image size should not exceed 100Kb!',
                class_name: 'gritter-error gritter-center'
              });
            }
            else {//other error
            }
          },
          on_success : function() {
            $.gritter.removeAll();
          }
        },
          url: function(params) {
          // ***UPDATE AVATAR HERE*** //
          //for a working upload example you can replace the contents of this function with 
          //examples/profile-avatar-update.js
  
          var deferred = new $.Deferred
  
          var value = $('#avatar').next().find('input[type=hidden]:eq(0)').val();
          if(!value || value.length == 0) {
            deferred.resolve();
            return deferred.promise();
          }
  
  
          //dummy upload
          setTimeout(function(){
            if("FileReader" in window) {
              //for browsers that have a thumbnail of selected image
              var thumb = $('#avatar').next().find('img').data('thumb');
              if(thumb) $('#avatar').get(0).src = thumb;
            }
            
            deferred.resolve({'status':'OK'});
  
            if(last_gritter) $.gritter.remove(last_gritter);
            last_gritter = $.gritter.add({
              title: 'Avatar Updated!',
              text: 'Uploading to server can be easily implemented. A working example is included with the template.',
              class_name: 'gritter-info gritter-center'
            });
            
           } , parseInt(Math.random() * 800 + 800))
  
          return deferred.promise();
          
          // ***END OF UPDATE AVATAR HERE*** //
        },
        
        success: function(response, newValue) {
        }
      })
    }catch(e) {}
    
    /**
    //let's display edit mode by default?
    var blank_image = true;//somehow you determine if image is initially blank or not, or you just want to display file input at first
    if(blank_image) {
      $('#avatar').editable('show').on('hidden', function(e, reason) {
        if(reason == 'onblur') {
          $('#avatar').editable('show');
          return;
        }
        $('#avatar').off('hidden');
      })
    }
    */
  
    //another option is using modals
    $('#avatar2').on('click', function(){
      var modal = 
      '<div class="modal fade">\
        <div class="modal-dialog">\
         <div class="modal-content">\
        <div class="modal-header">\
          <button type="button" class="close" data-dismiss="modal">&times;</button>\
          <h4 class="blue">Change Avatar</h4>\
        </div>\
        \
        <form class="no-margin">\
         <div class="modal-body">\
          <div class="space-4"></div>\
          <div style="width:75%;margin-left:12%;"><input type="file" name="file-input" /></div>\
         </div>\
        \
         <div class="modal-footer center">\
          <button type="submit" class="btn btn-sm btn-success"><i class="ace-icon fa fa-check"></i> Submit</button>\
          <button type="button" class="btn btn-sm" data-dismiss="modal"><i class="ace-icon fa fa-times"></i> Cancel</button>\
         </div>\
        </form>\
        </div>\
       </div>\
      </div>';
      
      
      var modal = $(modal);
      modal.modal("show").on("hidden", function(){
        modal.remove();
      });
  
      var working = false;
  
      var form = modal.find('form:eq(0)');
      var file = form.find('input[type=file]').eq(0);
      file.ace_file_input({
        style:'well',
        btn_choose:'Click to choose new avatar',
        btn_change:null,
        no_icon:'ace-icon fa fa-picture-o',
        thumbnail:'small',
        before_remove: function() {
          //don't remove/reset files while being uploaded
          return !working;
        },
        allowExt: ['jpg', 'jpeg', 'png', 'gif'],
        allowMime: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']
      });
  
      form.on('submit', function(){
        if(!file.data('ace_input_files')) return false;
        
        file.ace_file_input('disable');
        form.find('button').attr('disabled', 'disabled');
        form.find('.modal-body').append("<div class='center'><i class='ace-icon fa fa-spinner fa-spin bigger-150 orange'></i></div>");
        
        var deferred = new $.Deferred;
        working = true;
        deferred.done(function() {
          form.find('button').removeAttr('disabled');
          form.find('input[type=file]').ace_file_input('enable');
          form.find('.modal-body > :last-child').remove();
          
          modal.modal("hide");
  
          var thumb = file.next().find('img').data('thumb');
          if(thumb) $('#avatar2').get(0).src = thumb;
  
          working = false;
        });
        
        
        setTimeout(function(){
          deferred.resolve();
        } , parseInt(Math.random() * 800 + 800));
  
        return false;
      });
          
    });
  
    
  
    
    ///////////////////////////////////////////
  
    //right & left position
    //show the user info on right or left depending on its position
    $('#user-profile-2 .memberdiv').on('mouseenter touchstart', function(){
      var $this = $(this);
      var $parent = $this.closest('.tab-pane');
  
      var off1 = $parent.offset();
      var w1 = $parent.width();
  
      var off2 = $this.offset();
      var w2 = $this.width();
  
      var place = 'left';
      if( parseInt(off2.left) < parseInt(off1.left) + parseInt(w1 / 2) ) place = 'right';
      
      $this.find('.popover').removeClass('right left').addClass(place);
    }).on('click', function(e) {
      e.preventDefault();
    });
  
  
  
    ////////////////////
    //change profile
    $('[data-toggle="buttons"] .btn').on('click', function(e){
      var target = $(this).find('input[type=radio]');
      var which = parseInt(target.val());
      $('.user-profile').parent().addClass('hide');
      $('#user-profile-'+which).parent().removeClass('hide');
    });
    
    
    
    /////////////////////////////////////
    $(document).one('ajaxloadstart.page', function(e) {
      //in ajax mode, remove remaining elements before leaving page
      try {
        $('.editable').editable('destroy');
      } catch(e) {}
      $('[class*=select2]').remove();
    });
  });
</script>