
<?php


    $i = 1;

?>

<div id="loading"></div>
<div id="winpopup"></div>
<section class="content-header">
    <h1>BẢNG LƯƠNG TÀI XẾ</h1>
  <ol class="breadcrumb">
    <li><a href="<?php echo $this->url('admin') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><a href="<?php echo $this->url('salary/driver') ?>">Lương tài xế</a></li>
  </ol>
</section>
<div id="content" style="padding:5px;">

    
<form id="report" name="report" action method="post">
<div >
    
    
    <select style="width:100px" name="batdau" id="batdau">
        <option value="01">Tháng 1</option>
        <option value="02">Tháng 2</option>
        <option value="03">Tháng 3</option>
        <option value="04">Tháng 4</option>
        <option value="05">Tháng 5</option>
        <option value="06">Tháng 6</option>
        <option value="07">Tháng 7</option>
        <option value="08">Tháng 8</option>
        <option value="09">Tháng 9</option>
        <option value="10">Tháng 10</option>
        <option value="11">Tháng 11</option>
        <option value="12">Tháng 12</option>
    </select>
    <select style="width:100px" name="ketthuc" id="ketthuc">
        <option value="<?php echo date('Y')-2 ?>">Năm <?php echo date('Y')-2 ?></option>
        <option value="<?php echo date('Y')-1 ?>">Năm <?php echo date('Y')-1 ?></option>
        <option selected value="<?php echo date('Y') ?>">Năm <?php echo date('Y') ?></option>
    </select>
     <input type="submit" name="submit" id="xem" value="Xem">  
                             
</div>
<div >
    <div class="add-box">
        <a class="add_button" id="export_excel" href="<?php echo BASE_URL.'/salary/exportdriver/'.$batdau.'/'.$ketthuc.'/'.$trangthai ?>"><i class="fa fa-download"></i> Xuất</a>
    </div>
    
    <select style="width:100px" name="sl_trangthai" id="sl_trangthai">
        <option value="-1">Tài xế</option>
        <?php foreach ($steersmans_data as $driver) { ?>
        <option value="<?php echo $driver->steersman_id ?>"><?php echo $driver->steersman_name ?></option>
        <?php } ?>
    </select>
     <input type="submit" name="submit" id="xem" value="Xem">  
                             
</div
</form> 
<table class="table_data">
<thead>
    <tr>
    	
        <th rowspan="2" class="fix">
            <a >STT </a>
        </th>
        <th rowspan="2" class="fix">
            <a >Mã NV </a>
        </th>
        <th rowspan="2" class="fix">
            <a >Xe </a>
        </th>
        <th rowspan="2" class="fix">
            <a >Họ tên </a>
        </th>
        <th rowspan="2" class="fix">
            <a >Ngày công </a>
        </th>
        <th colspan="5" class="fix">
            <a >Lương </a>
        </th>
        <th colspan="3" class="fix">
            <a >Phụ cấp </a>
        </th>
        <th colspan="3" class="fix">
            <a >Khấu trừ </a>
        </th>
        <th rowspan="2" class="fix">
            <a >Tổng cộng </a>
        </th>
    </tr>
    <tr>
        <th  class="fix">
            <a >Tổng DT </a>
        </th>
        <th  class="fix">
            <a >CP 0 VAT</a>
        </th>
        <th  class="fix">
            <a >DT tính lương</a>
        </th>
        <th  class="fix">
            <a >Lương CĐ </a>
        </th>
        <th  class="fix">
            <a >Lương SP </a>
        </th>
        <th  class="fix">
            <a >Ăn ca  </a>
        </th>
        <th  class="fix">
            <a >Làm đêm  </a>
        </th>
        <th  class="fix">
            <a >Độc hại  </a>
        </th>
        <th  class="fix">
            <a >Bảo hiểm </a>
        </th>
        <th  class="fix">
            <a >Thuế </a>
        </th>
        <th  class="fix">
            <a >Công đoàn  </a>
        </th>
        
           
    </tr>
    
   </thead>
   <tbody>
    <?php $tongdoanhthu = 0; $tongchiphi=0; $tongluongsp=0; $tongluongcd=0; $tongbh=0; $tongthue=0; $tongcongdoan=0; $tongsk=0; $tongphucap=0; $tongcong=0; $tongthuong=0; $tonghoahong=0;  $tonganca=0; $tonglamdem=0; $tongdochai=0;
           $luongt13 =  0; $bh =  640000; $thue =  175729; $sk =  130417;
        $tongdoanhthuthem=0; $tongdoanhthutinhluong=0;
    ?>

    <?php foreach ($drivers as $driver) : ?>

        <?php 

        
        $chiphi = isset($road['police_cost'][$driver->steersman_id][$driver->vehicle])?$road['police_cost'][$driver->steersman_id][$driver->vehicle]:0;
        $chiphi += isset($road['tire_cost'][$driver->steersman_id][$driver->vehicle])?$road['tire_cost'][$driver->steersman_id][$driver->vehicle]:0;
        $chiphi += isset($chiphiphatsinh[$driver->steersman_id][$driver->vehicle])?$chiphiphatsinh[$driver->steersman_id][$driver->vehicle]:0;
        
        $chiphi += isset($hoahong[$driver->steersman_id][$driver->vehicle])?$hoahong[$driver->steersman_id][$driver->vehicle]:0;
        
        $chiphi += isset($warehouse['boiduong'][$driver->steersman_id][$driver->vehicle])?$warehouse['boiduong'][$driver->steersman_id][$driver->vehicle]:0;
        $chiphi += isset($warehouse['canxe'][$driver->steersman_id][$driver->vehicle])?$warehouse['canxe'][$driver->steersman_id][$driver->vehicle]:0;
        $chiphi += isset($warehouse['quetcont'][$driver->steersman_id][$driver->vehicle])?$warehouse['quetcont'][$driver->steersman_id][$driver->vehicle]:0;
        $chiphi += isset($warehouse['vecong'][$driver->steersman_id][$driver->vehicle])?$warehouse['vecong'][$driver->steersman_id][$driver->vehicle]:0;

        $tongdoanhthu += isset($doanhthu[$driver->steersman_id][$driver->vehicle])?$doanhthu[$driver->steersman_id][$driver->vehicle]:0 ;
        $tongdoanhthuthem += isset($doanhthuthem[$driver->steersman_id][$driver->vehicle])?$doanhthuthem[$driver->steersman_id][$driver->vehicle]:0;
        $tongchiphi += $chiphi; 
        

        $bh = isset($insurances[$driver->steersman_id][$driver->vehicle]->money)?$insurances[$driver->steersman_id][$driver->vehicle]->money:0;
        $thue = isset($taxs[$driver->steersman_id][$driver->vehicle]->money)?$taxs[$driver->steersman_id][$driver->vehicle]->money:0;
        $lamdem = isset($overtimes[$driver->steersman_id][$driver->vehicle]->money)?$overtimes[$driver->steersman_id][$driver->vehicle]->money:0;
        $dochai = isset($toxics[$driver->steersman_id][$driver->vehicle]->money)?$toxics[$driver->steersman_id][$driver->vehicle]->money:0;

        $tongbh += $bh;
        $tongthue += $thue;
        $tonglamdem += $lamdem;
        $tongdochai += $dochai;
        
        $tongsk += $sk;

        $ngaycong = round(isset($road['road_time'][$driver->steersman_id][$driver->vehicle])?$road['road_time'][$driver->steersman_id][$driver->vehicle]:0);

        $ngayvaocang = $driver->steersman_start_time;

        $timeDiff = strtotime(date('t-m-Y',strtotime('01-'.$batdau.'-'.$ketthuc))) - $ngayvaocang;

        $numberDays = $timeDiff/86400;  // 86400 seconds in one day

        // and you might want to convert to integer
        $numberDays = intval($numberDays); 

        $timeDiff2 = strtotime(date('t-m-Y',strtotime('01-'.$batdau.'-'.$ketthuc))) - $driver->start_work;

        $numberDays2 = $timeDiff2/86400;  // 86400 seconds in one day

        // and you might want to convert to integer
        $numberDays2 = intval($numberDays2); 

        if ($numberDays >= 30) {
            $luongcd = 2000000;
        }
        else{
            $luongcd = $numberDays2>0?round(2000000*$numberDays2/26):0;
        }

        if($luongcd>2000000)
            $luongcd = 2000000;

        $tongluongcd += $luongcd;

        $doanhthutinhluong = (isset($doanhthu[$driver->steersman_id][$driver->vehicle])?$doanhthu[$driver->steersman_id][$driver->vehicle]:0)+(isset($doanhthuthem[$driver->steersman_id][$driver->vehicle])?$doanhthuthem[$driver->steersman_id][$driver->vehicle]:0)-$chiphi;
        $tongdoanhthutinhluong += $doanhthutinhluong;
        $luongsp = round($doanhthutinhluong*0.1);
        $tongluongsp += $luongsp;
        $congdoan = round((($luongcd+$luongsp-$bh-$thue)*0.01)>115000?115000:(($luongcd+$luongsp-$bh-$thue)*0.01));
        $tongcongdoan += $congdoan;
        $anca = $ngaycong*25000;
        $tonganca += $anca;

        /*$tongluongt13 += isset($doanhthu[$driver->steersman_id][$driver->vehicle])?round(($doanhthu[$driver->steersman_id][$driver->vehicle]+(isset($doanhthuthem[$driver->steersman_id][$driver->vehicle])?$doanhthuthem[$driver->steersman_id][$driver->vehicle]:0))*0.015):0 ;
        $luongt13 = isset($doanhthu[$driver->steersman_id][$driver->vehicle])?round(($doanhthu[$driver->steersman_id][$driver->vehicle]+(isset($doanhthuthem[$driver->steersman_id][$driver->vehicle])?$doanhthuthem[$driver->steersman_id][$driver->vehicle]:0))*0.015):0 ;

        $luong = 0;
        $thuong = 0;

        if (isset($doanhthu[$driver->steersman_id][$driver->vehicle])) {

            $luong = ($doanhthu[$driver->steersman_id][$driver->vehicle])<50000000?3000000:round(($doanhthu[$driver->steersman_id][$driver->vehicle]-$chiphi-$cphoahong+(isset($doanhthuthem[$driver->steersman_id][$driver->vehicle])?$doanhthuthem[$driver->steersman_id][$driver->vehicle]:0))*0.09);

            $tongluong += ($doanhthu[$driver->steersman_id][$driver->vehicle])<50000000?3000000:round(($doanhthu[$driver->steersman_id][$driver->vehicle]-$chiphi-$cphoahong+(isset($doanhthuthem[$driver->steersman_id][$driver->vehicle])?$doanhthuthem[$driver->steersman_id][$driver->vehicle]:0))*0.09);

            if ($doanhthu[$driver->steersman_id][$driver->vehicle] >= 50000000 && $doanhthu[$driver->steersman_id][$driver->vehicle] <= 100000000) {
                $thuong = 3000000;
            }
            else if ($doanhthu[$driver->steersman_id][$driver->vehicle] > 100000000 && $doanhthu[$driver->steersman_id][$driver->vehicle] <= 150000000) {
                $thuong = 4000000;
            }
            else if ($doanhthu[$driver->steersman_id][$driver->vehicle] > 150000000 && $doanhthu[$driver->steersman_id][$driver->vehicle] <= 200000000) {
                $thuong = 5000000;
            }
            else if ($doanhthu[$driver->steersman_id][$driver->vehicle] > 200000000) {
                $thuong = 6000000;
            }
        }

        $tongthuong += $thuong;*/

        $style = null;
        
        

            if ($doanhthutinhluong > 50000000 && $doanhthutinhluong <= 100000000) {
                $style = 'style="color:#FFB300"';
            }
            else if ($doanhthutinhluong > 100000000) {
                $style = 'style="color:red"';
            }
        

        ?>

        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $driver->steersman_id ?>" class="edit_tr view" href="<?= $this->url('salary/view/'.$driver->steersman_id.'/'.$batdau.'/'.$ketthuc)?>" >
            <td class="fix"><?php echo $i++; ?></td>
            <td class="fix" ><?php echo $driver->steersman_code; ?></td>
            <td class="fix" ><?php echo $vehicle_data[$driver->vehicle]; ?></td>
            <td class="fix" ><?php echo $driver->steersman_name; ?></td>
            <td class="fix" ><?php echo $ngaycong; ?></td>
            <td class="fix" ><?php echo $lib->formatMoney($dt = isset($doanhthu[$driver->steersman_id][$driver->vehicle])?$doanhthu[$driver->steersman_id][$driver->vehicle]:0) ?></td>
            <td class="fix" ><?php echo $lib->formatMoney($chiphi) ?></td>
            <td class="fix" <?php echo $style  ?> ><?php echo $lib->formatMoney($doanhthutinhluong) ?></td>
            <td class="fix" ><?php echo $lib->formatMoney($luongcd) ?></td>
            <td class="fix" ><?php echo $lib->formatMoney($luongsp) ?></td>
            <td class="fix" ><?php echo $lib->formatMoney($anca) ?></td>
            <td class="fix view_overtime" >
                <span id="overtime_<?php echo $driver->steersman_id ?>"><?php echo $lib->formatMoney($lamdem) ?></span><br>
                <button type="button" style="display:none" alt="<?php echo '01-'.$batdau.'-'.$ketthuc ?>" name="<?php echo $driver->steersman_name; ?>" data="<?php echo $lib->formatMoney($lamdem) ?>" value="<?php echo $driver->steersman_id ?>" class="overtime">Sửa</button>
            </td>
            <td class="fix view_toxic" >
                <span id="toxic_<?php echo $driver->steersman_id ?>"><?php echo $lib->formatMoney($dochai) ?></span><br>
                <button type="button" style="display:none" alt="<?php echo '01-'.$batdau.'-'.$ketthuc ?>" name="<?php echo $driver->steersman_name; ?>" data="<?php echo $lib->formatMoney($dochai) ?>" value="<?php echo $driver->steersman_id ?>" class="toxic">Sửa</button>
            </td>
            <td class="fix view_insurance" >
                <span id="insurance_<?php echo $driver->steersman_id ?>"><?php echo $lib->formatMoney($bh) ?></span><br>
                <button type="button" style="display:none" alt="<?php echo '01-'.$batdau.'-'.$ketthuc ?>" name="<?php echo $driver->steersman_name; ?>" data="<?php echo $lib->formatMoney($bh) ?>" value="<?php echo $driver->steersman_id ?>" class="insurance">Sửa</button>
            </td>
            <td class="fix view_tax" >
                <span id="tax_<?php echo $driver->steersman_id ?>"><?php echo $lib->formatMoney($thue) ?></span><br>
                <button type="button" style="display:none" alt="<?php echo '01-'.$batdau.'-'.$ketthuc ?>" name="<?php echo $driver->steersman_name; ?>" data="<?php echo $lib->formatMoney($thue) ?>" value="<?php echo $driver->steersman_id ?>" class="tax">Sửa</button>
            </td>
            <td class="fix" ><?php echo $lib->formatMoney($congdoan) ?></td>
            <td class="fix" id="total_<?php echo $driver->steersman_id ?>" ><?php echo $lib->formatMoney($luongcd + $luongsp + $anca + $lamdem + $dochai - $thue - $bh - $congdoan) ?></td>
            
        </tr>

   
    <?php endforeach; ?>

        <tr  style="font-weight: bold; color: rgb(23, 119, 226);" >
            
            <th colspan="4" style="border-right: 1px solid rgb(236, 235, 235);border-top: 1px solid #80C8E5;padding: 7px; text-align: right;" >
                Tổng cộng
            </th>
            <td class="fix " ></td>
            <td class="fix " ><?php echo $lib->formatMoney($tongdoanhthu) ?></td>
            <td class="fix " ><?php echo $lib->formatMoney($tongchiphi) ?></td>
            <td class="fix " ><?php echo $lib->formatMoney($tongdoanhthu-$tongchiphi+$tongdoanhthuthem) ?></td>
            <td class="fix " ><?php echo $lib->formatMoney($tongluongcd) ?></td>
            <td class="fix" ><?php echo $lib->formatMoney($tongluongsp) ?></td>
            <td class="fix" ><?php echo $lib->formatMoney($tonganca) ?></td>
            <td class="fix" ><?php echo $lib->formatMoney($tonglamdem) ?></td>
            <td class="fix" ><?php echo $lib->formatMoney($tongdochai) ?></td>
            <td class="fix" ><?php echo $lib->formatMoney($tongbh) ?></td>
            <td class="fix" ><?php echo $lib->formatMoney($tongthue) ?></td>
            <td class="fix" ><?php echo $lib->formatMoney($tongcongdoan) ?></td>
            <td class="fix " ><?php echo $lib->formatMoney($tongluongcd + $tongluongsp + $tonganca + $tonglamdem + $tongdochai - $tongbh - $tongthue - $tongcongdoan) ?></td>
            
        </tr>

   </tbody>
</table>



</div>

<div id="dialogContent" title="Bảo hiểm">
    
    
    <form action="#" method="post" id="editForm">
        <label>
            <span class="add-on"><i class="icon-user" ></i></span>
            <span>Tài xế: </span>
            <input type="text" id="i_name" name="i_name" value="" disabled />
        </label>
        <label>
            <span class="add-on"><i class="icon-retweet" ></i></span>
            <span>Số tiền: </span>
            <input type="text" id="i_money" name="i_money" value="" class="numbers" required="required" />
            <input type="hidden" id="i_driver" name="i_driver" value="" />
            <input type="hidden" id="i_date" name="i_date" value="" />
        </label>
    </form>
</div>
<div id="dialogContent2" title="Thuế">
    
    
    <form action="#" method="post" id="editForm2">
        <label>
            <span class="add-on"><i class="icon-user" ></i></span>
            <span>Tài xế: </span>
            <input type="text" id="t_name" name="t_name" value="" disabled />
        </label>
        <label>
            <span class="add-on"><i class="icon-retweet" ></i></span>
            <span>Số tiền: </span>
            <input type="text" id="t_money" name="t_money" value="" class="numbers" required="required" />
            <input type="hidden" id="t_driver" name="t_driver" value="" />
            <input type="hidden" id="t_date" name="t_date" value="" />
        </label>
    </form>
</div>
<div id="dialogContent3" title="Phụ cấp làm đêm">
    
    
    <form action="#" method="post" id="editForm3">
        <label>
            <span class="add-on"><i class="icon-user" ></i></span>
            <span>Tài xế: </span>
            <input type="text" id="l_name" name="l_name" value="" disabled />
        </label>
        <label>
            <span class="add-on"><i class="icon-retweet" ></i></span>
            <span>Số tiền: </span>
            <input type="text" id="l_money" name="l_money" value="" class="numbers" required="required" />
            <input type="hidden" id="l_driver" name="l_driver" value="" />
            <input type="hidden" id="l_date" name="l_date" value="" />
        </label>
    </form>
</div>
<div id="dialogContent4" title="Phụ cấp độc hại">
    
    
    <form action="#" method="post" id="editForm4">
        <label>
            <span class="add-on"><i class="icon-user" ></i></span>
            <span>Tài xế: </span>
            <input type="text" id="d_name" name="d_name" value="" disabled />
        </label>
        <label>
            <span class="add-on"><i class="icon-retweet" ></i></span>
            <span>Số tiền: </span>
            <input type="text" id="d_money" name="d_money" value="" class="numbers" required="required" />
            <input type="hidden" id="d_driver" name="d_driver" value="" />
            <input type="hidden" id="d_date" name="d_date" value="" />
        </label>
    </form>
</div>

<script type="text/javascript">
 

var ch = "<?php echo $batdau ?>";
$('#batdau option[value='+ch+']').attr('selected','selected');

var ch2 = "<?php echo $ketthuc ?>";
$('#ketthuc option[value='+ch2+']').attr('selected','selected');

var ch3 = "<?php echo $trangthai ?>";
$('#sl_trangthai option[value='+ch3+']').attr('selected','selected');

$(".view").click(function(e){
    if(e.target != '[object HTMLButtonElement]' && e.target != '[object HTMLSpanElement]' && !$('.checkbox').is(':focus') && e.target.nodeName != "A"){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            width: "90%",
            height: 500,
            resizable: false,
            position: "top",
            title:'Chi tiết',
            buttons: {
                OK: function() {
                    $( this ).dialog( "close" );
                },
                Cancel: function() {
                    $( this ).dialog( "close" );
                }
            }
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
        return false;
    }
});


function get_number(id){
    return $(id).val().replace(/[^0-9\.-]+/g,"");
}

</script>
<style type="text/css">
    #ui-datepicker-div{
        font-size: 13px;
    }

.showtooltip {
        display:none;
        position:absolute;
        border:1px solid #333;
        background-color:#161616;
        border-radius:5px;
        padding:10px;
        color:#fff;
        font-size:12px Arial;
    }
</style>

<script type="text/javascript">
    $('.insurance')
    .button({ icons: { primary: "ui-icon-document" }})
    .click(function() {
        $('#i_name').val($(this).attr('name'));
        $('#i_driver').val($(this).attr('value'));
        $('#i_date').val($(this).attr('alt'));
        $('#i_money').val($(this).attr('data'));
        $( "#dialogContent" ).dialog( "open" )
    });


//set up the dialog box.
$( "#dialogContent" ).dialog({
    autoOpen: false,
    modal: true,
    buttons: {
        OK: function() {
            var driver = $('#i_driver').val();
            var insurance_date = $('#i_date').val();
            var money = $('#i_money').val();
                
                $.post("<?php echo BASE_URL ?>/salary/insurance", {driver: driver, insurance_date: insurance_date, money: money},
                   function(data){
                    $("html, body").animate({ scrollTop: 0 }, 100);
                        $('#insurance_'+driver).text(money);
                        $('#total_'+driver).val(
                            Math.round(
                            parseFloat(get_number('#total_'+driver)) - (parseFloat(get_number('#insurance_'+driver)))
                                
                            )
                        );
                        $('#total_'+driver).val(function(index, value) {
                            return value
                              .replace(/\D/g, "")
                              .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
                            ;
                          });
                   }); 
              
            $( this ).dialog( "close" );
        },        
        Cancel: function() {
            $( this ).dialog( "close" );
        }
    }
});

$('.tax')
    .button({ icons: { primary: "ui-icon-document" }})
    .click(function() {
        $('#t_name').val($(this).attr('name'));
        $('#t_driver').val($(this).attr('value'));
        $('#t_date').val($(this).attr('alt'));
        $('#t_money').val($(this).attr('data'));

        $( "#dialogContent2" ).dialog( "open" )
    });


//set up the dialog box.
$( "#dialogContent2" ).dialog({
    autoOpen: false,
    modal: true,
    buttons: {
        OK: function() {
            var driver = $('#t_driver').val();
            var tax_date = $('#t_date').val();
            var money = $('#t_money').val();
                
                $.post("<?php echo BASE_URL ?>/salary/tax", {driver: driver, tax_date: tax_date, money: money},
                   function(data){
                    $("html, body").animate({ scrollTop: 0 }, 100);
                        $('#tax_'+driver).text(money);
                        $('#total_'+driver).val(
                            Math.round(
                            parseFloat(get_number('#total_'+driver)) - (parseFloat(get_number('#tax_'+driver)))
                                
                            )
                        );
                        $('#total_'+driver).val(function(index, value) {
                            return value
                              .replace(/\D/g, "")
                              .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
                            ;
                          });
                   }); 
              
            $( this ).dialog( "close" );
        },        
        Cancel: function() {
            $( this ).dialog( "close" );
        }
    }
});

$('.overtime')
    .button({ icons: { primary: "ui-icon-document" }})
    .click(function() {
        $('#l_name').val($(this).attr('name'));
        $('#l_driver').val($(this).attr('value'));
        $('#l_date').val($(this).attr('alt'));
        $('#l_money').val($(this).attr('data'));

        $( "#dialogContent3" ).dialog( "open" )
    });


//set up the dialog box.
$( "#dialogContent3" ).dialog({
    autoOpen: false,
    modal: true,
    buttons: {
        OK: function() {
            var driver = $('#l_driver').val();
            var overtime_date = $('#l_date').val();
            var money = $('#l_money').val();
                
                $.post("<?php echo BASE_URL ?>/salary/overtime", {driver: driver, overtime_date: overtime_date, money: money},
                   function(data){
                    $("html, body").animate({ scrollTop: 0 }, 100);
                        $('#overtime_'+driver).text(money);
                        $('#total_'+driver).val(
                            Math.round(
                            parseFloat(get_number('#total_'+driver)) + (parseFloat(get_number('#overtime_'+driver)))
                                
                            )
                        );
                        $('#total_'+driver).val(function(index, value) {
                            return value
                              .replace(/\D/g, "")
                              .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
                            ;
                          });
                   }); 
              
            $( this ).dialog( "close" );
        },        
        Cancel: function() {
            $( this ).dialog( "close" );
        }
    }
});

$('.toxic')
    .button({ icons: { primary: "ui-icon-document" }})
    .click(function() {
        $('#d_name').val($(this).attr('name'));
        $('#d_driver').val($(this).attr('value'));
        $('#d_date').val($(this).attr('alt'));
        $('#d_money').val($(this).attr('data'));

        $( "#dialogContent4" ).dialog( "open" )
    });


//set up the dialog box.
$( "#dialogContent4" ).dialog({
    autoOpen: false,
    modal: true,
    buttons: {
        OK: function() {
            var driver = $('#d_driver').val();
            var toxic_date = $('#d_date').val();
            var money = $('#d_money').val();
                
                $.post("<?php echo BASE_URL ?>/salary/toxic", {driver: driver, toxic_date: toxic_date, money: money},
                   function(data){
                    $("html, body").animate({ scrollTop: 0 }, 100);
                        $('#toxic_'+driver).text(money);
                        $('#total_'+driver).val(
                            Math.round(
                            parseFloat(get_number('#total_'+driver)) + (parseFloat(get_number('#toxic_'+driver)))
                                
                            )
                        );
                        $('#total_'+driver).val(function(index, value) {
                            return value
                              .replace(/\D/g, "")
                              .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
                            ;
                          });
                   }); 
              
            $( this ).dialog( "close" );
        },        
        Cancel: function() {
            $( this ).dialog( "close" );
        }
    }
});

$('.numbers').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-.]/g, "")
          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
        ;
      });
    });

jQuery(".view_insurance").hover(
   function() {
      jQuery(this).find(".insurance").css("display","block");
   },
   function() {
      jQuery(this).find(".insurance").css("display","none");
      jQuery(this).find(".tax").css("display","none");
      jQuery(this).find(".overtime").css("display","none");
      jQuery(this).find(".toxic").css("display","none");
   }
);
jQuery(".view_tax").hover(
   function() {
      jQuery(this).find(".tax").css("display","block");
   },
   function() {
      jQuery(this).find(".insurance").css("display","none");
      jQuery(this).find(".tax").css("display","none");
      jQuery(this).find(".overtime").css("display","none");
      jQuery(this).find(".toxic").css("display","none");
   }
);
jQuery(".view_overtime").hover(
   function() {
      jQuery(this).find(".overtime").css("display","block");
   },
   function() {
      jQuery(this).find(".insurance").css("display","none");
      jQuery(this).find(".tax").css("display","none");
      jQuery(this).find(".overtime").css("display","none");
      jQuery(this).find(".toxic").css("display","none");
   }
);
jQuery(".view_toxic").hover(
   function() {
      jQuery(this).find(".toxic").css("display","block");
   },
   function() {
      jQuery(this).find(".insurance").css("display","none");
      jQuery(this).find(".tax").css("display","none");
      jQuery(this).find(".overtime").css("display","none");
      jQuery(this).find(".toxic").css("display","none");
   }
);

</script>
