
<?php


    $i = 1;

?>

<div id="loading"></div>
<div id="winpopup"></div>
<section class="content-header">
    <h1>BẢNG LƯƠNG TÀI XẾ</h1>
  <ol class="breadcrumb">
    <li><a href="<?php echo $this->url('admin') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><a href="<?php echo $this->url('salary/driver') ?>">Lương tài xế</a></li>
  </ol>
</section>
<div id="content" style="padding:5px;">

    
<form id="report" name="report" action method="post">
<div >
    
    
    <select style="width:100px" name="batdau" id="batdau">
        <option value="01">Tháng 1</option>
        <option value="02">Tháng 2</option>
        <option value="03">Tháng 3</option>
        <option value="04">Tháng 4</option>
        <option value="05">Tháng 5</option>
        <option value="06">Tháng 6</option>
        <option value="07">Tháng 7</option>
        <option value="08">Tháng 8</option>
        <option value="09">Tháng 9</option>
        <option value="10">Tháng 10</option>
        <option value="11">Tháng 11</option>
        <option value="12">Tháng 12</option>
    </select>
    <select style="width:100px" name="ketthuc" id="ketthuc">
        <option value="<?php echo date('Y')-2 ?>">Năm <?php echo date('Y')-2 ?></option>
        <option value="<?php echo date('Y')-1 ?>">Năm <?php echo date('Y')-1 ?></option>
        <option selected value="<?php echo date('Y') ?>">Năm <?php echo date('Y') ?></option>
    </select>
     <input type="submit" name="submit" id="xem" value="Xem">  
                             
</div>
<div >
    <div class="add-box">
        <a class="add_button" id="export_excel" href="<?php echo BASE_URL.'/salary/exportdriver/'.$batdau.'/'.$ketthuc.'/'.$trangthai ?>"><i class="fa fa-download"></i> Xuất</a>
    </div>
    
    <select style="width:200px" name="sl_vehicle" id="sl_vehicle">
        <option value="-1">Tài xế</option>
        <?php foreach ($steersmans_data as $driver) { ?>
        <option value="<?php echo $driver->steersman_id ?>"><?php echo $driver->steersman_name ?></option>
        <?php } ?>
    </select>
     <input type="submit" name="submit" id="xem" value="Xem">  
                             
</div
</form> 
<table class="table_data">
<thead>
    <tr>
    	
        <th rowspan="2" class="fix">
            <a >STT </a>
        </th>
        <th rowspan="2" class="fix">
            <a >Họ tên </a>
        </th>
        <th rowspan="2" class="fix">
            <a >Tổng lương chuyến </a>
        </th>
        <th rowspan="2" class="fix">
            <a >Tổng dầu định mức </a>
        </th>
        <th rowspan="2" class="fix">
            <a >Tổng dầu thực lãnh </a>
        </th>
        <th colspan="3" class="fix">
            <a >Chênh lệch </a>
        </th>
        <th rowspan="2" class="fix">
            <a >Tiền lương thực lãnh </a>
        </th>
        <th rowspan="2" class="fix">
            <a >Ghi chú </a>
        </th>
    </tr>
    <tr>
        <th  class="fix">
            <a >SL </a>
        </th>
        <th  class="fix">
            <a >Đơn giá</a>
        </th>
        <th  class="fix">
            <a >Thành tiền</a>
        </th>
        
           
    </tr>
    
   </thead>
   <tbody>
    <?php $tongluongchuyen = 0; $tongdaudinhmuc=0; $tongdauthuclanh=0; $tongsl=0; $tongthanhtien=0; $tonglanh=0;
    ?>

    <?php foreach ($steersmans as $driver) : ?>

        <?php 

        
        $lc = (isset($luongchuyen[$driver->steersman_id])?$luongchuyen[$driver->steersman_id]:0);
        $dm = (isset($daudinhmuc[$driver->steersman_id])?$daudinhmuc[$driver->steersman_id]:0);
        $dl = (isset($dauthuclanh[$driver->steersman_id])?$dauthuclanh[$driver->steersman_id]:0);
        $sl = $dm-$dl;
        $tp = $sl<0?$thuongphat['phat']:($sl>0?$thuongphat['thuong']:0);
        $tt = $sl*$tp;
        $lanh = $lc+$tt;

        $tongluongchuyen += $lc;
        $tongdaudinhmuc += $dm;
        $tongdauthuclanh += $dl;
        $tongsl += $sl;
        $tongthanhtien += $tt;
        $tonglanh += $lanh;

        ?>

        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $driver->steersman_id ?>" class="edit_tr view" href="<?= $this->url('salary/shipment/'.$driver->steersman_id.'/'.$batdau.'/'.$ketthuc)?>" >
            <td class="fix"><?php echo $i++; ?></td>
            <td class="fix" ><a target="_blank" href="<?php echo $this->url('steersman/index/'.$driver->steersman_id) ?>" ><?php echo $driver->steersman_name; ?></a></td>
            <td class="fix" ><?php echo $lib->formatMoney($lc) ?></td>
            <td class="fix" ><?php echo $dm ?></td>
            <td class="fix" ><?php echo $dl ?></td>
            <td class="fix" ><?php echo $sl ?></td>
            <td class="fix" ><?php echo $lib->formatMoney($tp) ?></td>
            <td class="fix" ><?php echo $lib->formatMoney($tt) ?></td>
            <td class="fix" ><?php echo $lib->formatMoney($lanh) ?></td>
            <td class="fix" ></td>
            
            
        </tr>

   
    <?php endforeach; ?>

        <tr  style="font-weight: bold; color: rgb(23, 119, 226);" >
            
            <th colspan="2" style="border-right: 1px solid rgb(236, 235, 235);border-top: 1px solid #80C8E5;padding: 7px; text-align: right;" >
                Tổng cộng
            </th>
            <td class="fix " ><?php echo $lib->formatMoney($tongluongchuyen) ?></td>
            <td class="fix " ><?php echo $lib->formatMoney($tongdaudinhmuc) ?></td>
            <td class="fix " ><?php echo $lib->formatMoney($tongdauthuclanh) ?></td>
            <td class="fix " ><?php echo $lib->formatMoney($tongsl) ?></td>
            <td class="fix" ></td>
            <td class="fix" ><?php echo $lib->formatMoney($tongthanhtien) ?></td>
            <td class="fix" ><?php echo $lib->formatMoney($tonglanh) ?></td>
            <td class="fix" ></td>
        </tr>

   </tbody>
</table>



</div>



<script type="text/javascript">
 

var ch = "<?php echo $batdau ?>";
$('#batdau option[value='+ch+']').attr('selected','selected');

var ch2 = "<?php echo $ketthuc ?>";
$('#ketthuc option[value='+ch2+']').attr('selected','selected');

var ch3 = "<?php echo $trangthai ?>";
$('#sl_vehicle option[value='+ch3+']').attr('selected','selected');

$(".view").click(function(e){
    if(e.target != '[object HTMLButtonElement]' && e.target != '[object HTMLSpanElement]' && !$('.checkbox').is(':focus') && e.target.nodeName != "A"){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            width: "90%",
            height: 500,
            resizable: false,
            position: "top",
            title:'Chi tiết',
            buttons: {
                OK: function() {
                    $( this ).dialog( "close" );
                },
                Cancel: function() {
                    $( this ).dialog( "close" );
                }
            }
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
        return false;
    }
});


function get_number(id){
    return $(id).val().replace(/[^0-9\.-]+/g,"");
}

</script>
<style type="text/css">
    #ui-datepicker-div{
        font-size: 13px;
    }

.showtooltip {
        display:none;
        position:absolute;
        border:1px solid #333;
        background-color:#161616;
        border-radius:5px;
        padding:10px;
        color:#fff;
        font-size:12px Arial;
    }
</style>

