
<?php


    $i = 1;

?>

<div id="loading"></div>
<div id="winpopup"></div>
<div id="content" style="padding:5px;">

 
<table class="table_data">
<thead>
    
    <tr>
        <th  class="fix">
            <a >STT</a>
        </th>
        <th  class="fix">
            <a >Ngày </a>
        </th>
        <th  class="fix">
            <a >Kho đi  </a>
        </th>
        <th  class="fix">
            <a >Kho đến </a>
        </th>
        <th  class="fix">
            <a >Sản lượng </a>
        </th>
        <th  class="fix">
            <a >ĐVT </a>
        </th>
        <th  class="fix">
            <a >Doanh thu </a>
        </th>
        <th  class="fix">
            <a >Chi phí  </a>
        </th>
        <th  class="fix">
            <a >Lương sản phẩm </a>
        </th>
           
    </tr>
    
   </thead>
   <tbody>
    <?php $tongdoanhthu = 0; $tongchiphi=0; $tongluong=0; $tongtrongtai=0; $quyluong=0; $tongdoanhthuthem=0; $doanhthuthem=0;
    ?>
    <?php foreach ($drivers as $driver) : ?>

    <?php foreach ($shipments as $shipment) : ?>

        <?php 
        if($driver->end_work > $shipment->shipment_date && $shipment->shipment_date >= $driver->start_work){
        
        $chiphi = isset($road['police_cost'][$shipment->shipment_id])?$road['police_cost'][$shipment->shipment_id]:0;
        $chiphi += isset($road['tire_cost'][$shipment->shipment_id])?$road['tire_cost'][$shipment->shipment_id]:0;
        $chiphi += (($shipment->approve==1)?$shipment->cost_add:0);
        
        $chiphi += ($shipment->commission*$shipment->commission_number);
        
        $chiphi += isset($warehouse['boiduong'][$shipment->shipment_id])?$warehouse['boiduong'][$shipment->shipment_id]:0;
        $chiphi += isset($warehouse['canxe'][$shipment->shipment_id])?$warehouse['canxe'][$shipment->shipment_id]:0;
        $chiphi += isset($warehouse['quetcont'][$shipment->shipment_id])?$warehouse['quetcont'][$shipment->shipment_id]:0;
        $chiphi += isset($warehouse['vecong'][$shipment->shipment_id])?$warehouse['vecong'][$shipment->shipment_id]:0;

        $tongdoanhthu += ($shipment->shipment_revenue+$shipment->revenue_other+$shipment->shipment_charge_excess) ;
        $tongchiphi += $chiphi; 
        $tongtrongtai += $shipment->shipment_ton;

        

        $quyluong += round((($shipment->shipment_revenue+$shipment->revenue_other+$shipment->shipment_charge_excess)-$chiphi+$doanhthuthem)*0.1);

        
        ?>

        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $driver->driver_id ?>" class="edit_tr"  >
            <td class="fix"><?php echo $i++; ?></td>
            <td class="fix" ><?php echo $lib->hien_thi_ngay_thang($shipment->shipment_date); ?></td>
            <td class="fix" ><?php echo $place['place_name'][$shipment->shipment_from]; ?></td>
            <td class="fix" ><?php echo $place['place_name'][$shipment->shipment_to]; ?></td>
            <td class="fix" ><?php echo $lib->formatMoney($shipment->shipment_ton) ?></td>
            <td class="fix" ><?php echo $shipment->cont_unit_name ?></td>
            
            <td class="fix" ><?php echo $lib->formatMoney($shipment->shipment_revenue+$shipment->revenue_other+$shipment->shipment_charge_excess) ?></td>
            <td class="fix" ><?php echo $lib->formatMoney($chiphi) ?></td>
            <td class="fix" style="font-weight: bold;" ><?php echo $lib->formatMoney($quyluong) ?></td>
        </tr>

    <?php } ?>
    <?php endforeach; ?>
    <?php endforeach; ?>
   
        
        <tr  style="font-weight: bold; color: rgb(23, 119, 226);" >
            
            <th colspan="6" style="border-right: 1px solid rgb(236, 235, 235);border-top: 1px solid #80C8E5;padding: 7px; text-align: right;" >
                Tổng cộng
            </th>
            <td class="fix " ><?php echo $lib->formatMoney($tongdoanhthu) ?></td>
            <td class="fix " ><?php echo $lib->formatMoney($tongchiphi) ?></td>
            <td class="fix " ><?php echo $lib->formatMoney(round(($tongdoanhthu-$tongchiphi+$tongdoanhthuthem)*0.1)) ?></td>
            
            
        </tr>

   </tbody>
</table>



</div>

