<script type="text/javascript">
$(document).ready(function(){
	$( ".select2" ).select2({dropdownAutoWidth : true});
			// Validate form
			$("#add_dispatch").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
				rules: {
				},
        submitHandler: function(form) {
          var dispatch_romooc = $('#dispatch_romooc').attr('data');
          var dispatch_staff = $('#dispatch_staff').attr('data');
          
          var formData = new FormData($("#add_dispatch")[0]);
          formData.append('dispatch_romooc', dispatch_romooc);
          formData.append('dispatch_staff', dispatch_staff);
          
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/dispatch/adddispatch", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: formData, // giá trị post
              cache: false,
              contentType: false,
              processData: false,
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error_dispatch').hide();
                  $('#error_dispatch').slideToggle(100); // hiển thị thẻ div success
                  $('#error_dispatch').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error_dispatch').fadeOut(10000);

              }
          });
          return false;
           
       }
					 
				 
			});

	
});

</script>

<div id="error_dispatch" class="error"><?php echo isset($error) ? $error : null; ?></div>     
<div class="tabbable">
  <form id="add_dispatch" method="post" action="" autocomplete="off">
    <ul class="nav nav-tabs padding-18">
      <li class="active">
        <a data-toggle="tab" href="#homedispatch">
          <i class="green ace-icon fa fa-file-text-o bigger-120"></i>
          Thông tin
        </a>
      </li>

      <li>
        <a data-toggle="tab" href="#subdispatch">
          <i class="blue ace-icon fa fa-th bigger-120"></i>
          Lô hàng phụ
        </a>
      </li>
    </ul>
    <div class="tab-content no-border ">
      <div id="homedispatch" class="tab-pane in active">
        <div class="col-md-2 col-xs-6">
          <label for="dispatch_date">Ngày</label>
          <div class="input-group">
            <input class="form-control input-mask-date" type="text" id="dispatch_date" name="dispatch_date" tabindex="1" required="required" value="<?php echo date('d/m/Y') ?>">
          </div>
          <div class="hr hr-8 dotted hr-double"></div>
          <label for="dispatch_shipment_temp">Lô hàng nhận</label>
          <div class="input-group">
            <select class="form-control select2" id="dispatch_shipment_temp" name="dispatch_shipment_temp" tabindex="6">
              <option value="">Chọn</option>
              <?php foreach ($shipment_temps as $shipment_temp) { ?>
                <option data="<?php echo $shipment_temp->shipment_temp_booking ?>" alt="<?php echo $shipment_temp->booking_number.'-['.$shipment_temp->booking_code.']' ?>" value="<?php echo $shipment_temp->shipment_temp_id ?>"><?php echo '['.$shipment_temp->booking_code.']-'.$shipment_temp->booking_number.': '.(isset($place_data[$shipment_temp->booking_place_from])?$place_data[$shipment_temp->booking_place_from]:null).'~'.(isset($place_data[$shipment_temp->booking_place_to])?$place_data[$shipment_temp->booking_place_to]:null).' |'.date('d/m/Y',$shipment_temp->shipment_temp_date) ?></option>
              <?php } ?>
            </select>
          </div>
          
          
        </div>
        <div class="col-md-2 col-xs-6">
          <label for="dispatch_code">Số lệnh</label>
          <div class="input-group">
            <input class="form-control" type="text" id="dispatch_code" name="dispatch_code" tabindex="2" value="<?php echo $lastID ?>">
          </div>
          <div class="hr hr-8 dotted hr-double"></div>
          <label for="dispatch_customer">Khách hàng </label>
          <div class="input-group">
            <select class="form-control select2" id="dispatch_customer" name="dispatch_customer" tabindex="7">
              <option value="">Chọn</option>
              <?php foreach ($customers as $customer) { ?>
                <option value="<?php echo $customer->customer_id ?>"><?php echo $customer->customer_name ?></option>
              <?php } ?>
            </select>
          </div>  
          <label for="dispatch_place_from">Nơi lấy <a title="Thêm kho hàng mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("place/add") ?>','Thêm kho hàng mới','dispatch_place_from','<?php echo $this->url("place/getplace") ?>','add_place')"></i></a></label>
          <div class="input-group">
            <select class="form-control select2" id="dispatch_place_from" name="dispatch_place_from" required="required" tabindex="11">
              <option value="">Chọn</option>
              <?php foreach ($places as $place) { ?>
                <option value="<?php echo $place->place_id ?>"><?php echo $place->place_name ?></option>
              <?php } ?>
            </select>
          </div>  
          <label for="dispatch_port_from">Lấy rỗng <a title="Thêm cảng mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("port/add") ?>','Thêm cảng mới','dispatch_port_from','<?php echo $this->url("port/getport") ?>','add_port')"></i></a></label>
          <div class="input-group">
            <select class="form-control select2" id="dispatch_port_from" name="dispatch_port_from" tabindex="15">
              <option value="">Chọn</option>
              <?php foreach ($ports as $port) { ?>
                <option value="<?php echo $port->port_id ?>"><?php echo $port->port_name ?></option>
              <?php } ?>
            </select>
          </div> 
        </div>
        <div class="col-md-2 col-xs-6">
          <label for="dispatch_vehicle">Xe <a title="Thêm xe mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("vehicle/add") ?>','Thêm xe mới','dispatch_vehicle','<?php echo $this->url("vehicle/getvehicle") ?>','add_vehicle')"></i></a></label>
          <div class="input-group">
            <select class="form-control select2" id="dispatch_vehicle" name="dispatch_vehicle" required="required" tabindex="3">
              <option value="">Chọn</option>
              <?php foreach ($vehicles as $vehicle) { ?>
                <option value="<?php echo $vehicle->vehicle_id ?>"><?php echo $vehicle->vehicle_number ?></option>
              <?php } ?>
            </select>
          </div>  
          <div class="hr hr-8 dotted hr-double"></div>
          <label for="dispatch_booking_type">Loại hàng</label>
          <div class="input-group">
            <select class="form-control" id="dispatch_booking_type" name="dispatch_booking_type" tabindex="8">
              <option value="">Chọn</option>
              <option value="1">Hàng nhập</option>
              <option value="2">Hàng xuất</option>
              <option value="3">Khác</option>
            </select>
          </div>
          <label for="dispatch_place_to">Nơi hạ <a title="Thêm kho hàng mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("place/add") ?>','Thêm kho hàng mới','dispatch_place_to','<?php echo $this->url("place/getplace") ?>','add_place')"></i></a></label>
          <div class="input-group">
            <select class="form-control select2" id="dispatch_place_to" name="dispatch_place_to" required="required" tabindex="12">
              <option value="">Chọn</option>
              <?php foreach ($places as $place) { ?>
                <option value="<?php echo $place->place_id ?>"><?php echo $place->place_name ?></option>
              <?php } ?>
            </select>
          </div>  
          <label for="dispatch_port_to">Trả rỗng <a title="Thêm cảng mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("port/add") ?>','Thêm cảng mới','dispatch_port_to','<?php echo $this->url("port/getport") ?>','add_port')"></i></a></label>
          <div class="input-group">
            <select class="form-control select2" id="dispatch_port_to" name="dispatch_port_to" tabindex="16">
              <option value="">Chọn</option>
              <?php foreach ($ports as $port) { ?>
                <option value="<?php echo $port->port_id ?>"><?php echo $port->port_name ?></option>
              <?php } ?>
            </select>
          </div> 
       </div>
       <div class="col-md-2 col-xs-6">
          <label for="dispatch_romooc">Mooc <a title="Thay lắp mooc" id="vehicle_romooc"><i class="ace-icon fa fa-exchange blue"></i></a></label>
          <div class="input-group">
            <input class="form-control" type="text" id="dispatch_romooc" name="dispatch_romooc" tabindex="4" readonly="" >
          </div>
          <div class="hr hr-8 dotted hr-double"></div>
          <label for="dispatch_booking">Số BK/BL </label>
          <div class="input-group">
            <select class="form-control" id="dispatch_booking" name="dispatch_booking" tabindex="9">
              
            </select>
          </div> 
          <label for="dispatch_start_date">Ngày lấy</label>
          <div class="input-group">
            <input class="form-control start-date" type="text" id="dispatch_start_date" name="dispatch_start_date" tabindex="13" >
          </div>
        </div>
        <div class="col-md-2 col-xs-6">
          <label for="dispatch_staff">Tài xế <a title="Tài xế" id="vehicle_driver"><i class="ace-icon fa fa-user blue"></i></a></label>
          <div class="input-group">
            <input class="form-control" type="text" id="dispatch_staff" name="dispatch_staff" tabindex="5" readonly="">
          </div>
          <div class="hr hr-8 dotted hr-double"></div>
          <label for="dispatch_comment">Ghi chú</label>
          <div class="input-group">
            <input class="form-control" type="text" id="dispatch_comment" name="dispatch_comment" tabindex="10">
          </div>
          <label for="dispatch_end_date">Ngày hạ</label>
          <div class="input-group">
            <input class="form-control end-date" type="text" id="dispatch_end_date" name="dispatch_end_date" tabindex="14" >
          </div>
        </div>
      </div>
      <div id="subdispatch" class="tab-pane">
      <div class="col-md-2 col-xs-6">
          <label for="dispatch_shipment_temp_sub">Lô hàng nhận</label>
          <div class="input-group">
            <select class="form-control select2" id="dispatch_shipment_temp_sub" name="dispatch_shipment_temp_sub" tabindex="15">
              <option value="">Chọn</option>
              <?php foreach ($shipment_temps as $shipment_temp) { ?>
                <option data="<?php echo $shipment_temp->shipment_temp_booking ?>" alt="<?php echo $shipment_temp->booking_number.'-['.$shipment_temp->booking_code.']' ?>" value="<?php echo $shipment_temp->shipment_temp_id ?>"><?php echo '['.$shipment_temp->booking_code.']-'.$shipment_temp->booking_number.': '.(isset($place_data[$shipment_temp->booking_place_from])?$place_data[$shipment_temp->booking_place_from]:null).'~'.(isset($place_data[$shipment_temp->booking_place_to])?$place_data[$shipment_temp->booking_place_to]:null).' |'.date('d/m/Y',$shipment_temp->shipment_temp_date) ?></option>
              <?php } ?>
            </select>
          </div>
          <label for="dispatch_place_from_sub">Nơi lấy <a title="Thêm kho hàng mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("place/add") ?>','Thêm kho hàng mới','dispatch_place_from_sub','<?php echo $this->url("place/getplace") ?>','add_place')"></i></a></label>
          <div class="input-group">
            <select class="form-control select2" id="dispatch_place_from_sub" name="dispatch_place_from_sub" tabindex="20">
              <option value="">Chọn</option>
              <?php foreach ($places as $place) { ?>
                <option value="<?php echo $place->place_id ?>"><?php echo $place->place_name ?></option>
              <?php } ?>
            </select>
          </div>  
          <label for="dispatch_port_from_sub">Lấy rỗng <a title="Thêm cảng mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("port/add") ?>','Thêm cảng mới','dispatch_port_from_sub','<?php echo $this->url("port/getport") ?>','add_port')"></i></a></label>
          <div class="input-group">
            <select class="form-control select2" id="dispatch_port_from_sub" name="dispatch_port_from_sub" tabindex="24">
              <option value="">Chọn</option>
              <?php foreach ($ports as $port) { ?>
                <option value="<?php echo $port->port_id ?>"><?php echo $port->port_name ?></option>
              <?php } ?>
            </select>
          </div> 
        </div>
        <div class="col-md-2 col-xs-6">
          <label for="dispatch_customer_sub">Khách hàng </label>
          <div class="input-group">
            <select class="form-control select2" id="dispatch_customer_sub" name="dispatch_customer_sub" tabindex="16">
              <option value="">Chọn</option>
              <?php foreach ($customers as $customer) { ?>
                <option value="<?php echo $customer->customer_id ?>"><?php echo $customer->customer_name ?></option>
              <?php } ?>
            </select>
          </div>  
          <label for="dispatch_place_to_sub">Nơi hạ <a title="Thêm kho hàng mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("place/add") ?>','Thêm kho hàng mới','dispatch_place_to_sub','<?php echo $this->url("place/getplace") ?>','add_place')"></i></a></label>
          <div class="input-group">
            <select class="form-control select2" id="dispatch_place_to_sub" name="dispatch_place_to_sub" tabindex="21">
              <option value="">Chọn</option>
              <?php foreach ($places as $place) { ?>
                <option value="<?php echo $place->place_id ?>"><?php echo $place->place_name ?></option>
              <?php } ?>
            </select>
          </div>  
          <label for="dispatch_port_to_sub">Trả rỗng <a title="Thêm cảng mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("port/add") ?>','Thêm cảng mới','dispatch_port_to_sub','<?php echo $this->url("port/getport") ?>','add_port')"></i></a></label>
          <div class="input-group">
            <select class="form-control select2" id="dispatch_port_to_sub" name="dispatch_port_to_sub" tabindex="16">
              <option value="">Chọn</option>
              <?php foreach ($ports as $port) { ?>
                <option value="<?php echo $port->port_id ?>"><?php echo $port->port_name ?></option>
              <?php } ?>
            </select>
          </div>
          
        </div>
        <div class="col-md-2 col-xs-6">
          <label for="dispatch_booking_type_sub">Loại hàng</label>
          <div class="input-group">
            <select class="form-control" id="dispatch_booking_type_sub" name="dispatch_booking_type_sub" tabindex="17">
              <option value="">Chọn</option>
              <option value="1">Hàng nhập</option>
              <option value="2">Hàng xuất</option>
              <option value="3">Khác</option>
            </select>
          </div>
          <label for="dispatch_start_date_sub">Ngày lấy</label>
          <div class="input-group">
            <input class="form-control input-mask-date" type="text" id="dispatch_start_date_sub" name="dispatch_start_date_sub" tabindex="22" >
          </div>
          
          
       </div>
       <div class="col-md-2 col-xs-6">
          <label for="dispatch_booking_sub">Số BK/BL </label>
          <div class="input-group">
            <select class="form-control" id="dispatch_booking_sub" name="dispatch_booking_sub" tabindex="18">
              
            </select>
          </div> 
          <label for="dispatch_end_date_sub">Ngày hạ</label>
          <div class="input-group">
            <input class="form-control input-mask-date" type="text" id="dispatch_end_date_sub" name="dispatch_end_date_sub" tabindex="23" >
          </div>
          
        </div>
        <div class="col-md-2 col-xs-6">
          <label for="dispatch_comment_sub">Ghi chú</label>
          <div class="input-group">
            <input class="form-control" type="text" id="dispatch_comment_sub" name="dispatch_comment_sub" tabindex="19">
          </div>
          
          
        </div>
      </div>
    </div>
      
  </form>
</div>

<script type="text/javascript">
  $('#dispatch_shipment_temp').change(function(){
    var booking = $('#dispatch_shipment_temp option:selected').attr('data');
     if (booking>0) {
        $.ajax({
          type: "GET",
          url: "<?php echo BASE_URL ?>/booking/getbookingdetail",
          data: {booking:booking}, 
          success: function(answer){
             var data = $.parseJSON(answer);
             $('#dispatch_booking_detail').html(data.container);
             $("#dispatch_booking_type").val(data.type).change();
             $("#dispatch_place_from").val(data.from).change();
             $("#dispatch_place_to").val(data.to).change();
             $("#dispatch_customer").val(data.customer).change();
             $('#dispatch_start_date').val(data.start);
             $('#dispatch_end_date').val(data.end);

             var detail = $('#dispatch_booking_detail').val();
             $.ajax({
                type: "GET",
                url: "<?php echo BASE_URL ?>/booking/getbookingcont",
                data: {detail:detail}, 
                success: function(answer){
                   var data = $.parseJSON(answer);
                   $('#dispatch_booking_detail_number').val(data.number);
                   $('#dispatch_booking_detail_number').attr('max',data.number);
                   $('#booking_detail_unit').val(data.unit);
                }
            });
          }
      });

      $('#dispatch_booking').html('<option value="'+booking+'">'+$('#dispatch_shipment_temp option:selected').attr('alt')+'</option>');
      $('#dispatch_booking').attr('readonly',true);
      $('#dispatch_customer').select2({'disabled':true});
      $('#dispatch_booking_type').attr('readonly',true);
     }
     
  });
  $('#dispatch_customer').on("select2:select", function(e) { 
      var customer = $('#dispatch_customer').val();
      var type = $('#dispatch_booking_type').val();
      if (customer>0) {
        $.ajax({
            type: "GET",
            url: "<?php echo BASE_URL ?>/booking/getbooking",
            data: {customer:customer,type:type}, 
            success: function(answer){
               var data = $.parseJSON(answer);
               $('#dispatch_booking').html(data.booking);

               var booking = $('#dispatch_booking').val();
               if (booking>0) {
                  $.ajax({
                    type: "GET",
                    url: "<?php echo BASE_URL ?>/booking/getbookingdetail",
                    data: {booking:booking}, 
                    success: function(answer){
                       var data = $.parseJSON(answer);
                       $('#dispatch_booking_detail').html(data.container);
                       $("#dispatch_booking_type").val(data.type).change();
                       $("#dispatch_place_from").val(data.from).change();
                       $("#dispatch_place_to").val(data.to).change();
                       $("#dispatch_customer").val(data.customer).change();
                       $('#dispatch_start_date').val(data.start);
                       $('#dispatch_end_date').val(data.end);

                       var detail = $('#dispatch_booking_detail').val();
                       $.ajax({
                          type: "GET",
                          url: "<?php echo BASE_URL ?>/booking/getbookingcont",
                          data: {detail:detail}, 
                          success: function(answer){
                             var data = $.parseJSON(answer);
                             $('#dispatch_booking_detail_number').val(data.number);
                             $('#dispatch_booking_detail_number').attr('max',data.number);
                             $('#booking_detail_unit').val(data.unit);
                          }
                      });
                    }
                });
               }
               else{
                $('#dispatch_booking_detail').html("");
                $('#dispatch_booking_detail_number').val("");
                $('#booking_detail_unit').val("");
               }
            }
        });
      }
    });
  
  $('#dispatch_booking_type').change(function(e){
    if (e.originalEvent) {
      var customer = $('#dispatch_customer').val();
      var type = $('#dispatch_booking_type').val();
      if (type>0) {
        $.ajax({
            type: "GET",
            url: "<?php echo BASE_URL ?>/booking/getbooking",
            data: {customer:customer,type:type}, 
            success: function(answer){
               var data = $.parseJSON(answer);
               $('#dispatch_booking').html(data.booking);

               var booking = $('#dispatch_booking').val();
               if (booking>0) {
                  $.ajax({
                    type: "GET",
                    url: "<?php echo BASE_URL ?>/booking/getbookingdetail",
                    data: {booking:booking}, 
                    success: function(answer){
                       var data = $.parseJSON(answer);
                       $('#dispatch_booking_detail').html(data.container);
                       $("#dispatch_booking_type").val(data.type).change();
                       $("#dispatch_place_from").val(data.from).change();
                       $("#dispatch_place_to").val(data.to).change();
                       $("#dispatch_customer").val(data.customer).change();
                       $('#dispatch_start_date').val(data.start);
                       $('#dispatch_end_date').val(data.end);

                       var detail = $('#dispatch_booking_detail').val();
                       $.ajax({
                          type: "GET",
                          url: "<?php echo BASE_URL ?>/booking/getbookingcont",
                          data: {detail:detail}, 
                          success: function(answer){
                             var data = $.parseJSON(answer);
                             $('#dispatch_booking_detail_number').val(data.number);
                             $('#dispatch_booking_detail_number').attr('max',data.number);
                             $('#booking_detail_unit').val(data.unit);
                          }
                      });
                    }
                });
               }
               else{
                $('#dispatch_booking_detail').html("");
                $('#dispatch_booking_detail_number').val("");
                $('#booking_detail_unit').val("");
               }
            }
        });
      }
    }
  });
  $('#dispatch_booking').change(function(e){
    if (e.originalEvent) {
      var booking = $('#dispatch_booking').val();
       $.ajax({
          type: "GET",
          url: "<?php echo BASE_URL ?>/booking/getbookingdetail",
          data: {booking:booking}, 
          success: function(answer){
             var data = $.parseJSON(answer);
             $('#dispatch_booking_detail').html(data.container);
             $("#dispatch_booking_type").val(data.type).change();
             $("#dispatch_place_from").val(data.from).change();
             $("#dispatch_place_to").val(data.to).change();
             $("#dispatch_customer").val(data.customer).change();
             $('#dispatch_start_date').val(data.start);
             $('#dispatch_end_date').val(data.end);

             var detail = $('#dispatch_booking_detail').val();
             $.ajax({
                type: "GET",
                url: "<?php echo BASE_URL ?>/booking/getbookingcont",
                data: {detail:detail}, 
                success: function(answer){
                   var data = $.parseJSON(answer);
                   $('#dispatch_booking_detail_number').val(data.number);
                   $('#dispatch_booking_detail_number').attr('max',data.number);
                   $('#booking_detail_unit').val(data.unit);
                }
            });
          }
      });
     }
  });
  $('#dispatch_booking_detail').change(function(e){
    if (e.originalEvent) {
      var detail = $('#dispatch_booking_detail').val();
       $.ajax({
          type: "GET",
          url: "<?php echo BASE_URL ?>/booking/getbookingcont",
          data: {detail:detail}, 
          success: function(answer){
             var data = $.parseJSON(answer);
             $('#dispatch_booking_detail_number').val(data.number);
             $('#dispatch_booking_detail_number').attr('max',data.number);
             $('#booking_detail_unit').val(data.unit);
          }
      });
     }
  });

  $('#dispatch_shipment_temp_sub').change(function(){
    var booking = $('#dispatch_shipment_temp_sub option:selected').attr('data');
     if (booking>0) {
        $.ajax({
          type: "GET",
          url: "<?php echo BASE_URL ?>/booking/getbookingdetail",
          data: {booking:booking}, 
          success: function(answer){
             var data = $.parseJSON(answer);
             $('#dispatch_booking_detail_sub').html(data.container);
             $("#dispatch_booking_type_sub").val(data.type).change();
             $("#dispatch_place_from_sub").val(data.from).change();
             $("#dispatch_place_to_sub").val(data.to).change();
             $("#dispatch_customer_sub").val(data.customer).change();
             $('#dispatch_start_date_sub').val(data.start);
             $('#dispatch_end_date_sub').val(data.end);

             var detail = $('#dispatch_booking_detail_sub').val();
             $.ajax({
                type: "GET",
                url: "<?php echo BASE_URL ?>/booking/getbookingcont",
                data: {detail:detail}, 
                success: function(answer){
                   var data = $.parseJSON(answer);
                   $('#dispatch_booking_detail_number_sub').val(data.number);
                   $('#dispatch_booking_detail_number_sub').attr('max',data.number);
                   $('#booking_detail_unit_sub').val(data.unit);
                }
            });
          }
      });

      $('#dispatch_booking_sub').html('<option value="'+booking+'">'+$('#dispatch_shipment_temp_sub option:selected').attr('alt')+'</option>');
      $('#dispatch_booking_sub').attr('readonly',true);
      $('#dispatch_customer_sub').select2({'disabled':true});
      $('#dispatch_booking_type_sub').attr('readonly',true);
     }
     
  });
  $('#dispatch_customer_sub').on("select2:select", function(e) { 
    var customer = $('#dispatch_customer_sub').val();
    var type = $('#dispatch_booking_type_sub').val();
    if (customer>0) {
      $.ajax({
          type: "GET",
          url: "<?php echo BASE_URL ?>/booking/getbooking",
          data: {customer:customer,type:type}, 
          success: function(answer){
             var data = $.parseJSON(answer);
             $('#dispatch_booking_sub').html(data.booking);

             var booking = $('#dispatch_booking_sub').val();
             if (booking>0) {
                $.ajax({
                  type: "GET",
                  url: "<?php echo BASE_URL ?>/booking/getbookingdetail",
                  data: {booking:booking}, 
                  success: function(answer){
                     var data = $.parseJSON(answer);
                     $('#dispatch_booking_detail_sub').html(data.container);
                     $("#dispatch_booking_type_sub").val(data.type).change();
                     $("#dispatch_place_from_sub").val(data.from).change();
                     $("#dispatch_place_to_sub").val(data.to).change();
                     $("#dispatch_customer_sub").val(data.customer).change();
                     $('#dispatch_start_date_sub').val(data.start);
                     $('#dispatch_end_date_sub').val(data.end);

                     var detail = $('#dispatch_booking_detail_sub').val();
                     $.ajax({
                        type: "GET",
                        url: "<?php echo BASE_URL ?>/booking/getbookingcont",
                        data: {detail:detail}, 
                        success: function(answer){
                           var data = $.parseJSON(answer);
                           $('#dispatch_booking_detail_number_sub').val(data.number);
                           $('#dispatch_booking_detail_number_sub').attr('max',data.number);
                           $('#booking_detail_unit_sub').val(data.unit);
                        }
                    });
                  }
              });
             }
             else{
              $('#dispatch_booking_detail_sub').html("");
              $('#dispatch_booking_detail_number_sub').val("");
              $('#booking_detail_unit_sub').val("");
             }
          }
      });
    }
  });
  $('#dispatch_booking_type_sub').change(function(e){
    if (e.originalEvent) {
      var customer = $('#dispatch_customer_sub').val();
      var type = $('#dispatch_booking_type_sub').val();
      if (type>0) {
        $.ajax({
            type: "GET",
            url: "<?php echo BASE_URL ?>/booking/getbooking",
            data: {customer:customer,type:type}, 
            success: function(answer){
               var data = $.parseJSON(answer);
               $('#dispatch_booking_sub').html(data.booking);

               var booking = $('#dispatch_booking_sub').val();
               if (booking>0) {
                  $.ajax({
                    type: "GET",
                    url: "<?php echo BASE_URL ?>/booking/getbookingdetail",
                    data: {booking:booking}, 
                    success: function(answer){
                       var data = $.parseJSON(answer);
                       $('#dispatch_booking_detail_sub').html(data.container);
                       $("#dispatch_booking_type_sub").val(data.type).change();
                       $("#dispatch_place_from_sub").val(data.from).change();
                       $("#dispatch_place_to_sub").val(data.to).change();
                       $("#dispatch_customer_sub").val(data.customer).change();
                       $('#dispatch_start_date_sub').val(data.start);
                       $('#dispatch_end_date_sub').val(data.end);

                       var detail = $('#dispatch_booking_detail_sub').val();
                       $.ajax({
                          type: "GET",
                          url: "<?php echo BASE_URL ?>/booking/getbookingcont",
                          data: {detail:detail}, 
                          success: function(answer){
                             var data = $.parseJSON(answer);
                             $('#dispatch_booking_detail_number_sub').val(data.number);
                             $('#dispatch_booking_detail_number_sub').attr('max',data.number);
                             $('#booking_detail_unit_sub').val(data.unit);
                          }
                      });
                    }
                });
               }
               else{
                $('#dispatch_booking_detail_sub').html("");
                $('#dispatch_booking_detail_number_sub').val("");
                $('#booking_detail_unit_sub').val("");
               }
            }
        });
      }
    }
  });
  $('#dispatch_booking_sub').change(function(e){
    if (e.originalEvent) {
      var booking = $('#dispatch_booking_sub').val();
       $.ajax({
          type: "GET",
          url: "<?php echo BASE_URL ?>/booking/getbookingdetail",
          data: {booking:booking}, 
          success: function(answer){
             var data = $.parseJSON(answer);
             $('#dispatch_booking_detail_sub').html(data.container);
             $("#dispatch_booking_type_sub").val(data.type).change();
             $("#dispatch_place_from_sub").val(data.from).change();
             $("#dispatch_place_to_sub").val(data.to).change();
             $("#dispatch_customer_sub").val(data.customer).change();
             $('#dispatch_start_date_sub').val(data.start);
             $('#dispatch_end_date_sub').val(data.end);

             var detail = $('#dispatch_booking_detail_sub').val();
             $.ajax({
                type: "GET",
                url: "<?php echo BASE_URL ?>/booking/getbookingcont",
                data: {detail:detail}, 
                success: function(answer){
                   var data = $.parseJSON(answer);
                   $('#dispatch_booking_detail_number_sub').val(data.number);
                   $('#dispatch_booking_detail_number_sub').attr('max',data.number);
                   $('#booking_detail_unit_sub').val(data.unit);
                }
            });
          }
      });
    }
  });
  $('#dispatch_booking_detail_sub').change(function(e){
    if (e.originalEvent) {
      var detail = $('#dispatch_booking_detail_sub').val();
       $.ajax({
          type: "GET",
          url: "<?php echo BASE_URL ?>/booking/getbookingcont",
          data: {detail:detail}, 
          success: function(answer){
             var data = $.parseJSON(answer);
             $('#dispatch_booking_detail_number_sub').val(data.number);
             $('#dispatch_booking_detail_number_sub').attr('max',data.number);
             $('#booking_detail_unit_sub').val(data.unit);
          }
      });
     }
  });

  $('#dispatch_vehicle').change(function(){
    var vehicle = $('#dispatch_vehicle').val();
    var date = $('#dispatch_date').val();
    if (vehicle>0) {
      $.ajax({
          type: "GET",
          url: "<?php echo BASE_URL ?>/vehicleromooc/getromooc",
          data: {vehicle:vehicle,date:date}, 
          success: function(answer){
             var data = $.parseJSON(answer);
             $('#dispatch_romooc').val(data.romooc_number);
             $('#dispatch_romooc').attr('data',data.romooc_id);
          }
      });
      $.ajax({
          type: "GET",
          url: "<?php echo BASE_URL ?>/driver/getdriver",
          data: {vehicle:vehicle,date:date}, 
          success: function(answer){
             var data = $.parseJSON(answer);
             $('#dispatch_staff').val(data.staff_name);
             $('#dispatch_staff').attr('data',data.staff_id);
          }
      });
    }
  });

  $('#vehicle_romooc').click(function(){
    var vehicle = $('#dispatch_vehicle').val();
    var date = $('#dispatch_date').val();
    if (vehicle>0) {
      view_click_other('<?php echo $this->url("vehicleromooc/viewromooc/?id=") ?>','Thông tin mooc',vehicle+'~'+date,'none');
    }
    
  });
  $('#vehicle_driver').click(function(){
    var vehicle = $('#dispatch_vehicle').val();
    var date = $('#dispatch_date').val();
    if (vehicle>0) {
      view_click_other('<?php echo $this->url("driver/viewdriver/?id=") ?>','Thông tin tài xế',vehicle+'~'+date,'none');
    }
  });
</script>