<script type="text/javascript">
$(document).ready(function(){
	$( ".select2" ).select2({dropdownAutoWidth : true});
			// Validate form
			$("#add_dispatch").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
				rules: {
				},
        submitHandler: function(form) {
          var formData = new FormData($("#add_dispatch")[0]);
          
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/dispatch/adddispatch", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: formData, // giá trị post
              cache: false,
              contentType: false,
              processData: false,
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error_dispatch').hide();
                  $('#error_dispatch').slideToggle(100); // hiển thị thẻ div success
                  $('#error_dispatch').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error_dispatch').fadeOut(10000);

              }
          });
          return false;
           
       }
					 
				 
			});

	
});

</script>

<div id="error_dispatch" class="error"><?php echo isset($error) ? $error : null; ?></div>     
<div class="login_body">
  <form id="add_dispatch" method="post" action="" autocomplete="off">
      <div class="col-md-2 col-xs-6">
        <label for="dispatch_date">Ngày</label>
        <div class="input-group">
          <input class="form-control input-mask-date" type="text" id="dispatch_date" name="dispatch_date" tabindex="1" required="required" value="<?php echo date('d/m/Y') ?>">
        </div>
        <div class="hr hr-8 dotted hr-double"></div>
        <label for="booking_customer">Khách hàng </label>
        <div class="input-group">
          <select class="form-control select2" id="booking_customer" name="booking_customer" required="required" tabindex="3">
            <option value="">Chọn</option>
            <?php foreach ($customers as $customer) { ?>
              <option value="<?php echo $customer->customer_id ?>"><?php echo $customer->customer_name ?></option>
            <?php } ?>
          </select>
        </div>  
        <label for="dispatch_place_from">Nơi lấy <a title="Thêm kho hàng mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("place/add") ?>','Thêm kho hàng mới','dispatch_place_from','<?php echo $this->url("place/getplace") ?>','add_place')"></i></a></label>
        <div class="input-group">
          <select class="form-control select2" id="dispatch_place_from" name="dispatch_place_from" required="required" tabindex="3">
            <option value="">Chọn</option>
            <?php foreach ($places as $place) { ?>
              <option value="<?php echo $place->place_id ?>"><?php echo $place->place_name ?></option>
            <?php } ?>
          </select>
        </div>  
      </div>
      <div class="col-md-2 col-xs-6">
        <label for="dispatch_code">Số lệnh</label>
        <div class="input-group">
          <input class="form-control" type="text" id="dispatch_code" name="dispatch_code" tabindex="2" value="<?php echo $lastID ?>">
        </div>
        <div class="hr hr-8 dotted hr-double"></div>
        <label for="booking_type">Loại hàng</label>
        <div class="input-group">
          <select class="form-control" id="booking_type" name="booking_type" required="required" tabindex="4">
            <option value="">Chọn</option>
            <option value="1">Hàng nhập</option>
            <option value="2">Hàng xuất</option>
            <option value="3">Khác</option>
          </select>
        </div>
        <label for="dispatch_place_to">Nơi hạ <a title="Thêm kho hàng mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("place/add") ?>','Thêm kho hàng mới','dispatch_place_to','<?php echo $this->url("place/getplace") ?>','add_place')"></i></a></label>
        <div class="input-group">
          <select class="form-control select2" id="dispatch_place_to" name="dispatch_place_to" required="required" tabindex="3">
            <option value="">Chọn</option>
            <?php foreach ($places as $place) { ?>
              <option value="<?php echo $place->place_id ?>"><?php echo $place->place_name ?></option>
            <?php } ?>
          </select>
        </div>  
      </div>
      <div class="col-md-2 col-xs-6">
        <label for="dispatch_vehicle">Xe <a title="Thêm xe mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("vehicle/add") ?>','Thêm xe mới','dispatch_vehicle','<?php echo $this->url("vehicle/getvehicle") ?>','add_vehicle')"></i></a></label>
        <div class="input-group">
          <select class="form-control select2" id="dispatch_vehicle" name="dispatch_vehicle" required="required" tabindex="3">
            <option value="">Chọn</option>
            <?php foreach ($vehicles as $vehicle) { ?>
              <option value="<?php echo $vehicle->vehicle_id ?>"><?php echo $vehicle->vehicle_number ?></option>
            <?php } ?>
          </select>
        </div>  
        <div class="hr hr-8 dotted hr-double"></div>
        <label for="dispatch_booking">Số BK/BL </label>
        <div class="input-group">
          <select class="form-control select2" id="dispatch_booking" name="dispatch_booking" required="required" tabindex="3">
            <option value="">Chọn</option>
            <?php foreach ($bookings as $booking) { ?>
              <option value="<?php echo $booking->booking_id ?>"><?php echo $booking->booking_number ?></option>
            <?php } ?>
          </select>
        </div> 
        <label for="dispatch_start_date">Ngày lấy</label>
        <div class="input-group">
          <input class="form-control start-date" type="text" id="dispatch_start_date" name="dispatch_start_date" tabindex="1" >
        </div>
     </div>
     <div class="col-md-2 col-xs-6">
        <label for="dispatch_romooc">Mooc <a title="Thay lắp mooc" id="vehicle_romooc"><i class="ace-icon fa fa-exchange blue"></i></a></label>
        <div class="input-group">
          <input class="form-control" type="text" id="dispatch_romooc" name="dispatch_romooc" tabindex="4" readonly="" >
        </div>
        <div class="hr hr-8 dotted hr-double"></div>
        <label for="dispatch_booking_detail">Số cont</label>
        <div class="input-group">
          <select class="form-control" id="dispatch_booking_detail" name="dispatch_booking_detail" tabindex="4"></select>
        </div>
        <label for="dispatch_end_date">Ngày hạ</label>
        <div class="input-group">
          <input class="form-control end-date" type="text" id="dispatch_end_date" name="dispatch_end_date" tabindex="1" >
        </div>
      </div>
      <div class="col-md-2 col-xs-6">
        <label for="dispatch_staff">Tài xế <a title="Tài xế" id="vehicle_driver"><i class="ace-icon fa fa-user blue"></i></a></label>
        <div class="input-group">
          <input class="form-control" type="text" id="dispatch_staff" name="dispatch_staff" tabindex="5" readonly="">
        </div>
        <div class="hr hr-8 dotted hr-double"></div>
        <label for="booking_detail_number">Sản lượng</label>
        <div class="input-group">
          <input class="form-control" type="text" id="booking_detail_number" name="booking_detail_number" tabindex="5" readonly="">
        </div>
      </div>
      
      <div class="col-md-2 col-xs-6">
        <label for="dispatch_comment">Ghi chú</label>
        <div class="input-group">
          <input class="form-control" type="text" id="dispatch_comment" name="dispatch_comment" tabindex="5">
        </div>
        <div class="hr hr-8 dotted hr-double"></div>
        <label for="booking_detail_unit">ĐVT</label>
        <div class="input-group">
          <input class="form-control" type="text" id="booking_detail_unit" name="booking_detail_unit" tabindex="5" readonly="">
        </div>
      </div>
  </form>
</div>

<script type="text/javascript">
  $('#dispatch_vehicle').change(function(){
    var vehicle = $('#dispatch_vehicle').val();
    var date = $('#dispatch_date').val();
    if (vehicle>0) {
      $.ajax({
          type: "GET",
          url: "<?php echo BASE_URL ?>/vehicleromooc/getromooc",
          data: {vehicle:vehicle,date:date}, 
          success: function(answer){
             var data = $.parseJSON(answer);
             $('#dispatch_romooc').val(data.romooc_number);
             $('#dispatch_romooc').attr('data',data.romooc_id);
          }
      });
      $.ajax({
          type: "GET",
          url: "<?php echo BASE_URL ?>/driver/getdriver",
          data: {vehicle:vehicle,date:date}, 
          success: function(answer){
             var data = $.parseJSON(answer);
             $('#dispatch_staff').val(data.staff_name);
             $('#dispatch_staff').attr('data',data.staff_id);
          }
      });
    }
  });

  $('#vehicle_romooc').click(function(){
    var vehicle = $('#dispatch_vehicle').val();
    var date = $('#dispatch_date').val();
    if (vehicle>0) {
      view_click_other('<?php echo $this->url("vehicleromooc/viewromooc/?id=") ?>','Thông tin mooc',vehicle+'~'+date,'none');
    }
    
  });
  $('#vehicle_driver').click(function(){
    var vehicle = $('#dispatch_vehicle').val();
    var date = $('#dispatch_date').val();
    if (vehicle>0) {
      view_click_other('<?php echo $this->url("driver/viewdriver/?id=") ?>','Thông tin tài xế',vehicle+'~'+date,'none');
    }
  });
</script>