<script type="text/javascript">
$(document).ready(function(){
  $( ".select2" ).select2({dropdownAutoWidth : true});
      // Validate form
      $("#edit_dispatch").validate({
        errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
        rules: {
        },
        submitHandler: function(form) {
          var dispatch_romooc = $('#dispatch_romooc').attr('data');
          var dispatch_staff = $('#dispatch_staff').attr('data');
          
          var formData = new FormData($("#edit_dispatch")[0]);
          formData.append('dispatch_id', '<?php echo $dispatch_data->dispatch_id ?>');
          formData.append('dispatch_romooc', dispatch_romooc);
          formData.append('dispatch_staff', dispatch_staff);
          
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/dispatch/editdispatch", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: formData, // giá trị post
              cache: false,
              contentType: false,
              processData: false,
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error_dispatch').hide();
                  $('#error_dispatch').slideToggle(100); // hiển thị thẻ div success
                  $('#error_dispatch').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error_dispatch').fadeOut(10000);

              }
          });
          return false;
           
       }
           
         
      });

  
});

</script>

<div id="error_dispatch" class="error"><?php echo isset($error) ? $error : null; ?></div>     
<div class="login_body">
  <form id="edit_dispatch" method="post" action="" autocomplete="off">
      <div class="col-md-2 col-xs-6">
        <label for="dispatch_date">Ngày</label>
        <div class="input-group">
          <input class="form-control input-mask-date" type="text" id="dispatch_date" name="dispatch_date" tabindex="1" required="required" value="<?php echo $lib->hien_thi_ngay_thang($dispatch_data->dispatch_date) ?>">
        </div>
        <div class="hr hr-8 dotted hr-double"></div>
        <label for="booking_customer">Khách hàng </label>
        <div class="input-group">
          <select class="form-control select2" id="booking_customer" name="booking_customer" tabindex="7" readonly="">
              <option value="<?php echo $customers->customer_id ?>"><?php echo $customers->customer_name ?></option>
          </select>
        </div>  
        <label for="dispatch_place_from">Nơi lấy <a title="Thêm kho hàng mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("place/add") ?>','Thêm kho hàng mới','dispatch_place_from','<?php echo $this->url("place/getplace") ?>','add_place')"></i></a></label>
        <div class="input-group">
          <select class="form-control select2" id="dispatch_place_from" name="dispatch_place_from" required="required" tabindex="13">
            <option value="">Chọn</option>
            <?php foreach ($places as $place) { ?>
              <option <?php echo $dispatch_data->dispatch_place_from==$place->place_id?'selected="selected"':null ?> value="<?php echo $place->place_id ?>"><?php echo $place->place_name ?></option>
            <?php } ?>
          </select>
        </div>  
      </div>
      <div class="col-md-2 col-xs-6">
        <label for="dispatch_code">Số lệnh</label>
        <div class="input-group">
          <input class="form-control" type="text" id="dispatch_code" name="dispatch_code" tabindex="2" value="<?php echo $dispatch_data->dispatch_code ?>">
        </div>
        <div class="hr hr-8 dotted hr-double"></div>
        <label for="booking_type">Loại hàng</label>
        <div class="input-group">
          <select class="form-control" id="booking_type" name="booking_type" tabindex="8" readonly="">
            <option value="">Chọn</option>
            <option <?php echo $bookings->booking_type==1?'selected="selected"':null ?> value="1">Hàng nhập</option>
            <option <?php echo $bookings->booking_type==2?'selected="selected"':null ?> value="2">Hàng xuất</option>
            <option <?php echo $bookings->booking_type==3?'selected="selected"':null ?> value="3">Khác</option>
          </select>
        </div>
        <label for="dispatch_place_to">Nơi hạ <a title="Thêm kho hàng mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("place/add") ?>','Thêm kho hàng mới','dispatch_place_to','<?php echo $this->url("place/getplace") ?>','add_place')"></i></a></label>
        <div class="input-group">
          <select class="form-control select2" id="dispatch_place_to" name="dispatch_place_to" required="required" tabindex="14">
            <option value="">Chọn</option>
            <?php foreach ($places as $place) { ?>
              <option <?php echo $dispatch_data->dispatch_place_to==$place->place_id?'selected="selected"':null ?> value="<?php echo $place->place_id ?>"><?php echo $place->place_name ?></option>
            <?php } ?>
          </select>
        </div>  
      </div>
      <div class="col-md-2 col-xs-6">
        <label for="dispatch_vehicle">Xe <a title="Thêm xe mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("vehicle/add") ?>','Thêm xe mới','dispatch_vehicle','<?php echo $this->url("vehicle/getvehicle") ?>','add_vehicle')"></i></a></label>
        <div class="input-group">
          <select class="form-control select2" id="dispatch_vehicle" name="dispatch_vehicle" required="required" tabindex="3">
            <option value="">Chọn</option>
            <?php foreach ($vehicles as $vehicle) { ?>
              <option <?php echo $dispatch_data->dispatch_vehicle==$vehicle->vehicle_id?'selected="selected"':null ?> value="<?php echo $vehicle->vehicle_id ?>"><?php echo $vehicle->vehicle_number ?></option>
            <?php } ?>
          </select>
        </div>  
        <div class="hr hr-8 dotted hr-double"></div>
        <label for="dispatch_booking">Số BK/BL </label>
        <div class="input-group">
          <select class="form-control" id="dispatch_booking" name="dispatch_booking" tabindex="9" readonly="">
              <option value="<?php echo $bookings->booking_id ?>"><?php echo $bookings->booking_number ?></option>
          </select>
        </div> 
        <label for="dispatch_start_date">Ngày lấy</label>
        <div class="input-group">
          <input class="form-control start-date" type="text" id="dispatch_start_date" name="dispatch_start_date" tabindex="15" value="<?php echo $lib->hien_thi_ngay_thang($dispatch_data->dispatch_start_date) ?>" >
        </div>
     </div>
     <div class="col-md-2 col-xs-6">
        <label for="dispatch_romooc">Mooc <a title="Thay lắp mooc" id="vehicle_romooc"><i class="ace-icon fa fa-exchange blue"></i></a></label>
        <div class="input-group">
          <input class="form-control" type="text" id="dispatch_romooc" name="dispatch_romooc" tabindex="4" readonly="" data="<?php echo $romoocs->romooc_id ?>" value="<?php echo $romoocs->romooc_number ?>" >
        </div>
        <div class="hr hr-8 dotted hr-double"></div>
        <label for="dispatch_booking_detail">Số cont</label>
        <div class="input-group">
          <select class="form-control" id="dispatch_booking_detail" name="dispatch_booking_detail" tabindex="10" required="required" readonly="">
              <option value="<?php echo $details->booking_detail_id ?>"><?php echo $details->booking_detail_container ?></option>
          </select>
        </div>
        <label for="dispatch_end_date">Ngày hạ</label>
        <div class="input-group">
          <input class="form-control end-date" type="text" id="dispatch_end_date" name="dispatch_end_date" tabindex="16" value="<?php echo $lib->hien_thi_ngay_thang($dispatch_data->dispatch_end_date) ?>" >
        </div>
      </div>
      <div class="col-md-2 col-xs-6">
        <label for="dispatch_staff">Tài xế <a title="Tài xế" id="vehicle_driver"><i class="ace-icon fa fa-user blue"></i></a></label>
        <div class="input-group">
          <input class="form-control" type="text" id="dispatch_staff" name="dispatch_staff" tabindex="5" readonly="" data="<?php echo $staffs->staff_id ?>" value="<?php echo $staffs->staff_name ?>">
        </div>
        <div class="hr hr-8 dotted hr-double"></div>
        <label for="dispatch_booking_detail_number">Sản lượng</label>
        <div class="input-group">
          <input class="form-control text-right" type="text" id="dispatch_booking_detail_number" name="dispatch_booking_detail_number" tabindex="11" required="required" value="<?php echo $dispatch_data->dispatch_booking_detail_number ?>">
        </div>
        <label for="dispatch_comment">Ghi chú</label>
        <div class="input-group">
          <input class="form-control" type="text" id="dispatch_comment" name="dispatch_comment" tabindex="17" value="<?php echo $dispatch_data->dispatch_comment ?>">
        </div>
      </div>
      
      <div class="col-md-2 col-xs-6">
        <label for="dispatch_shipment_temp">Lô hàng nhận</label>
        <div class="input-group">
          <select class="form-control" id="dispatch_shipment_temp" name="dispatch_shipment_temp" tabindex="6" readonly="">
            <?php foreach ($shipment_temps as $shipment_temp) { ?>
              <option data="<?php echo $shipment_temp->shipment_temp_booking ?>" alt="<?php echo '['.$shipment_temp->booking_code.'] - '.$shipment_temp->booking_number ?>" value="<?php echo $shipment_temp->shipment_temp_id ?>"><?php echo '['.$shipment_temp->booking_code.']-'.$shipment_temp->booking_number.': '.(isset($place_data[$shipment_temp->booking_place_from])?$place_data[$shipment_temp->booking_place_from]:null).'~'.(isset($place_data[$shipment_temp->booking_place_to])?$place_data[$shipment_temp->booking_place_to]:null).' |'.date('d/m/Y',$shipment_temp->shipment_temp_date) ?></option>
            <?php } ?>
          </select>
        </div>
        <div class="hr hr-8 dotted hr-double"></div>
        <label for="booking_detail_unit">ĐVT</label>
        <div class="input-group">
          <input class="form-control" type="text" id="booking_detail_unit" name="booking_detail_unit" tabindex="12" readonly="" value="<?php echo $units->unit_name ?>">
        </div>
      </div>
  </form>
</div>

<script type="text/javascript">
  $('#dispatch_shipment_temp').change(function(){
    var booking = $('#dispatch_shipment_temp option:selected').attr('data');
     if (booking>0) {
        $.ajax({
          type: "GET",
          url: "<?php echo BASE_URL ?>/booking/getbookingdetail",
          data: {booking:booking}, 
          success: function(answer){
             var data = $.parseJSON(answer);
             $('#dispatch_booking_detail').html(data.container);
             $('#booking_type option[value='+data.type+']').attr('selected','selected');
             $('#booking_customer option[value='+data.customer+']').attr('selected','selected');
             $('#booking_customer').select2();
             $('#dispatch_place_from option[value='+data.from+']').attr('selected','selected');
             $('#dispatch_place_from').select2();
             $('#dispatch_place_to option[value='+data.to+']').attr('selected','selected');
             $('#dispatch_place_to').select2();
             $('#dispatch_start_date').val(data.start);
             $('#dispatch_end_date').val(data.end);

             var detail = $('#dispatch_booking_detail').val();
             $.ajax({
                type: "GET",
                url: "<?php echo BASE_URL ?>/booking/getbookingcont",
                data: {detail:detail}, 
                success: function(answer){
                   var data = $.parseJSON(answer);
                   $('#dispatch_booking_detail_number').val(data.number);
                   $('#dispatch_booking_detail_number').attr('max',data.number);
                   $('#booking_detail_unit').val(data.unit);
                }
            });
          }
      });

      $('#dispatch_booking').html('<option value="'+booking+'">'+$('#dispatch_shipment_temp option:selected').attr('alt')+'</option>');
      $('#dispatch_booking').attr('readonly',true);
      $('#booking_customer').select2({'disabled':true});
      $('#booking_type').attr('readonly',true);
     }
     
  });
  $('#booking_customer').change(function(){
    var customer = $('#booking_customer').val();
    var type = $('#booking_type').val();
    if (customer>0) {
      $.ajax({
          type: "GET",
          url: "<?php echo BASE_URL ?>/booking/getbooking",
          data: {customer:customer,type:type}, 
          success: function(answer){
             var data = $.parseJSON(answer);
             $('#dispatch_booking').html(data.booking);

             var booking = $('#dispatch_booking').val();
             if (booking>0) {
                $.ajax({
                  type: "GET",
                  url: "<?php echo BASE_URL ?>/booking/getbookingdetail",
                  data: {booking:booking}, 
                  success: function(answer){
                     var data = $.parseJSON(answer);
                     $('#dispatch_booking_detail').html(data.container);
                     $('#booking_type option[value='+data.type+']').attr('selected','selected');
                     $('#booking_customer option[value='+data.customer+']').attr('selected','selected');
                     $('#booking_customer').select2();
                     $('#dispatch_place_from option[value='+data.from+']').attr('selected','selected');
                     $('#dispatch_place_from').select2();
                     $('#dispatch_place_to option[value='+data.to+']').attr('selected','selected');
                     $('#dispatch_place_to').select2();
                     $('#dispatch_start_date').val(data.start);
                     $('#dispatch_end_date').val(data.end);

                     var detail = $('#dispatch_booking_detail').val();
                     $.ajax({
                        type: "GET",
                        url: "<?php echo BASE_URL ?>/booking/getbookingcont",
                        data: {detail:detail}, 
                        success: function(answer){
                           var data = $.parseJSON(answer);
                           $('#dispatch_booking_detail_number').val(data.number);
                           $('#dispatch_booking_detail_number').attr('max',data.number);
                           $('#booking_detail_unit').val(data.unit);
                        }
                    });
                  }
              });
             }
             else{
              $('#dispatch_booking_detail').html("");
              $('#dispatch_booking_detail_number').val("");
              $('#booking_detail_unit').val("");
             }
          }
      });
    }
  });
  $('#booking_type').change(function(){
    var customer = $('#booking_customer').val();
    var type = $('#booking_type').val();
    if (type>0) {
      $.ajax({
          type: "GET",
          url: "<?php echo BASE_URL ?>/booking/getbooking",
          data: {customer:customer,type:type}, 
          success: function(answer){
             var data = $.parseJSON(answer);
             $('#dispatch_booking').html(data.booking);

             var booking = $('#dispatch_booking').val();
             if (booking>0) {
                $.ajax({
                  type: "GET",
                  url: "<?php echo BASE_URL ?>/booking/getbookingdetail",
                  data: {booking:booking}, 
                  success: function(answer){
                     var data = $.parseJSON(answer);
                     $('#dispatch_booking_detail').html(data.container);
                     $('#booking_type option[value='+data.type+']').attr('selected','selected');
                     $('#booking_customer option[value='+data.customer+']').attr('selected','selected');
                     $('#booking_customer').select2();
                     $('#dispatch_place_from option[value='+data.from+']').attr('selected','selected');
                     $('#dispatch_place_from').select2();
                     $('#dispatch_place_to option[value='+data.to+']').attr('selected','selected');
                     $('#dispatch_place_to').select2();
                     $('#dispatch_start_date').val(data.start);
                     $('#dispatch_end_date').val(data.end);

                     var detail = $('#dispatch_booking_detail').val();
                     $.ajax({
                        type: "GET",
                        url: "<?php echo BASE_URL ?>/booking/getbookingcont",
                        data: {detail:detail}, 
                        success: function(answer){
                           var data = $.parseJSON(answer);
                           $('#dispatch_booking_detail_number').val(data.number);
                           $('#dispatch_booking_detail_number').attr('max',data.number);
                           $('#booking_detail_unit').val(data.unit);
                        }
                    });
                  }
              });
             }
             else{
              $('#dispatch_booking_detail').html("");
              $('#dispatch_booking_detail_number').val("");
              $('#booking_detail_unit').val("");
             }
          }
      });
    }
  });
  $('#dispatch_booking').change(function(){
    var booking = $('#dispatch_booking').val();
     $.ajax({
        type: "GET",
        url: "<?php echo BASE_URL ?>/booking/getbookingdetail",
        data: {booking:booking}, 
        success: function(answer){
           var data = $.parseJSON(answer);
           $('#dispatch_booking_detail').html(data.container);
           $('#booking_type option[value='+data.type+']').attr('selected','selected');
           $('#booking_customer option[value='+data.customer+']').attr('selected','selected');
           $('#booking_customer').select2();
           $('#dispatch_place_from option[value='+data.from+']').attr('selected','selected');
           $('#dispatch_place_from').select2();
           $('#dispatch_place_to option[value='+data.to+']').attr('selected','selected');
           $('#dispatch_place_to').select2();
           $('#dispatch_start_date').val(data.start);
           $('#dispatch_end_date').val(data.end);

           var detail = $('#dispatch_booking_detail').val();
           $.ajax({
              type: "GET",
              url: "<?php echo BASE_URL ?>/booking/getbookingcont",
              data: {detail:detail}, 
              success: function(answer){
                 var data = $.parseJSON(answer);
                 $('#dispatch_booking_detail_number').val(data.number);
                 $('#dispatch_booking_detail_number').attr('max',data.number);
                 $('#booking_detail_unit').val(data.unit);
              }
          });
        }
    });
  });
  $('#dispatch_booking_detail').change(function(){
    var detail = $('#dispatch_booking_detail').val();
     $.ajax({
        type: "GET",
        url: "<?php echo BASE_URL ?>/booking/getbookingcont",
        data: {detail:detail}, 
        success: function(answer){
           var data = $.parseJSON(answer);
           $('#dispatch_booking_detail_number').val(data.number);
           $('#dispatch_booking_detail_number').attr('max',data.number);
           $('#booking_detail_unit').val(data.unit);
        }
    });
  });

  $('#dispatch_vehicle').change(function(){
    var vehicle = $('#dispatch_vehicle').val();
    var date = $('#dispatch_date').val();
    if (vehicle>0) {
      $.ajax({
          type: "GET",
          url: "<?php echo BASE_URL ?>/vehicleromooc/getromooc",
          data: {vehicle:vehicle,date:date}, 
          success: function(answer){
             var data = $.parseJSON(answer);
             $('#dispatch_romooc').val(data.romooc_number);
             $('#dispatch_romooc').attr('data',data.romooc_id);
          }
      });
      $.ajax({
          type: "GET",
          url: "<?php echo BASE_URL ?>/driver/getdriver",
          data: {vehicle:vehicle,date:date}, 
          success: function(answer){
             var data = $.parseJSON(answer);
             $('#dispatch_staff').val(data.staff_name);
             $('#dispatch_staff').attr('data',data.staff_id);
          }
      });
    }
  });

  $('#vehicle_romooc').click(function(){
    var vehicle = $('#dispatch_vehicle').val();
    var date = $('#dispatch_date').val();
    if (vehicle>0) {
      view_click_other('<?php echo $this->url("vehicleromooc/viewromooc/?id=") ?>','Thông tin mooc',vehicle+'~'+date,'none');
    }
    
  });
  $('#vehicle_driver').click(function(){
    var vehicle = $('#dispatch_vehicle').val();
    var date = $('#dispatch_date').val();
    if (vehicle>0) {
      view_click_other('<?php echo $this->url("driver/viewdriver/?id=") ?>','Thông tin tài xế',vehicle+'~'+date,'none');
    }
  });
</script>