<div class="col-md-4">
  <div class="widget-box transparent">
    <div class="widget-header widget-header-small">
      <h5 class="widget-title blue smaller">
        <i class="ace-icon fa fa-location-arrow orange"></i>
        <?php echo $km.' km - '.$oil.' lit - '.$time.'h' ?>
      </h4>
    </div>
    <div class="widget-body">
      <div class="widget-main padding-8">
        <div id="profile-feed-1" class="profile-feed">
          <?php $m=0; foreach ($roads as $road) { ?>
            <div class="profile-activity clearfix">
              <div>
                <div class="pull-left">
                  <input name="shipment_road[]" type="checkbox" class="checkbox_road ace" value="<?php echo $road->road_id ?>" checked><span class="lbl"></span>
                </div>
                <a class="user marker-link" markerid="<?php echo $m++ ?>"> <?php echo $route_data[$road->road_route_from] ?> </a> - <a class="user marker-link" markerid="<?php echo $m++ ?>"> <?php echo $route_data[$road->road_route_to] ?> </a>
                <div class="time">
                  <i class="ace-icon fa fa-map-signs bigger-110"></i>
                  <?php echo $road->road_km ?> km
                  <i class="ace-icon fa fa-tint bigger-110"></i>
                  <?php echo $road->road_oil ?> lit
                  <i class="ace-icon fa fa-clock-o bigger-110"></i>
                  <?php echo $road->road_time ?>h
                  
                </div>
              </div>

              <div class="tools action-buttons">
                <a class="blue" onclick="view_click_other('<?php echo $this->url("road/view/") ?>','Thông tin định mức tuyến đường',<?php echo $road->road_id ?>,'none')">
                  <i class="ace-icon fa fa-info-circle bigger-125"></i>
                </a>
              </div>
            </div>
          <?php } ?>

        </div>
      </div>
    </div>
  </div>
</div>
<div class="col-md-8">
  <div id="map_canvas" style="min-width:490px;width:100%;height:300px;"></div>
</div>

<script src="https://maps.googleapis.com/maps/api/js?v=3&key=<?php echo MAP_KEY ?>&callback=initialize"></script>
<script>
var markers = new Array();
var locations = <?php echo json_encode($road_data ); ?>;

function initialize() {
  var bounds = new google.maps.LatLngBounds();
  var infowindow = new google.maps.InfoWindow();
  var directionsDisplay = new google.maps.DirectionsRenderer({preserveViewport: true});
  var directionsService = new google.maps.DirectionsService();

  var map = new google.maps.Map(document.getElementById('map_canvas'), {
    zoom: 10,
    gestureHandling: 'greedy',
    center: new google.maps.LatLng(10.8470055, 106.6500569),
    mapTypeId: google.maps.MapTypeId.ROADMAP
  });
  directionsDisplay.setMap(map);
  
  var marker, i;
  var request = {
    travelMode: google.maps.TravelMode.DRIVING
  };
  for (i = 0; i < locations.length; i++) {
    marker = new google.maps.Marker({
      position: new google.maps.LatLng(locations[i][1], locations[i][2]),
      map: map,
      title: locations[i][0]
    });

    
    google.maps.event.addListener(marker, 'click', (function(marker, i) {
      return function() {
        infowindow.setContent(locations[i][0]);
        infowindow.open(map, marker);
      }
    })(marker, i));

    // Add marker to markers array
    markers.push(marker);
    bounds.extend(marker.position);

    if (i == 0) request.origin = marker.getPosition();
    else if (i == locations.length - 1) request.destination = marker.getPosition();
    else {
      if (!request.waypoints) request.waypoints = [];
      request.waypoints.push({
        location: marker.getPosition(),
        stopover: true
      });
    }

  }

  //now fit the map to the newly inclusive bounds
  map.fitBounds(bounds);

  directionsService.route(request, function(result, status) {
    if (status == google.maps.DirectionsStatus.OK) {
      var map = directionsDisplay.getMap();
      directionsDisplay.setDirections(result);
      map.setZoom(9);
    }
  });

}

$('.marker-link').click(function(){
  google.maps.event.trigger(markers[$(this).attr('markerid')], 'click');
});
</script>
<script>
  $('#profile-feed-1').ace_scroll({
    height: '400px',
    mouseWheelLock: true,
    alwaysVisible : true
  });
</script>