<script type="text/javascript">
$(document).ready(function(){
  $( ".select2" ).select2({dropdownAutoWidth : true});
      // Validate form
      $("#shipment_dispatch").validate({
        errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
        rules: {
        },
        submitHandler: function(form) {
          var dispatch_romooc = $('#dispatch_romooc').attr('data');
          var dispatch_staff = $('#dispatch_staff').attr('data');
          
          var formData = new FormData($("#shipment_dispatch")[0]);
          formData.append('dispatch_id', '<?php echo $dispatch_data->dispatch_id ?>');
          formData.append('dispatch_romooc', dispatch_romooc);
          formData.append('dispatch_staff', dispatch_staff);
          
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/dispatch/shipmentdispatch", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: formData, // giá trị post
              cache: false,
              contentType: false,
              processData: false,
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error_dispatch').hide();
                  $('#error_dispatch').slideToggle(100); // hiển thị thẻ div success
                  $('#error_dispatch').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error_dispatch').fadeOut(10000);

              }
          });
          return false;
           
       }
           
         
      });

  
});

</script>

<div id="error_dispatch" class="error"><?php echo isset($error) ? $error : null; ?></div>     
<div class="tabbable">
  <form id="shipment_dispatch" method="post" action="" autocomplete="off">
    <ul class="nav nav-tabs padding-18">
      <li class="active">
        <a data-toggle="tab" href="#homeshipment">
          <i class="green ace-icon fa fa-file-text-o bigger-120"></i>
          Thông tin
        </a>
      </li>

      <li>
        <a data-toggle="tab" href="#costshipment">
          <i class="blue ace-icon fa fa-th bigger-120"></i>
          Chi phí
        </a>
      </li>
    </ul>
    <div class="tab-content no-border ">
      <div id="homeshipment" class="tab-pane in active">
        <div class="col-md-2 col-xs-6">
          <label for="dispatch_code">Lệnh điều xe</label>
          <div class="input-group">
            <input class="form-control" type="text" id="dispatch_code" name="dispatch_code" tabindex="2" readonly="" value="<?php echo $dispatch_data->dispatch_code ?>">
          </div>
          <div class="hr hr-8 dotted hr-double"></div>
          <label for="booking_customer">Khách hàng </label>
          <div class="input-group">
            <select class="form-control" id="booking_customer" name="booking_customer" tabindex="7" readonly="">
                <option value="<?php echo $customers->customer_id ?>"><?php echo $customers->customer_name ?></option>
            </select>
          </div>  
          <label for="shipment_do">Số DO</label>
          <div class="input-group">
            <input class="form-control" type="text" id="shipment_do" name="shipment_do" tabindex="2" >
          </div>
            
        </div>
        <div class="col-md-2 col-xs-6">
          <label for="dispatch_date">Ngày</label>
          <div class="input-group">
            <input class="form-control input-mask-date" type="text" id="dispatch_date" name="dispatch_date" tabindex="1" required="required" value="<?php echo $lib->hien_thi_ngay_thang($dispatch_data->dispatch_date) ?>">
          </div>
          <div class="hr hr-8 dotted hr-double"></div>
          <label for="booking_type">Loại hàng</label>
          <div class="input-group">
            <select class="form-control" id="booking_type" name="booking_type" tabindex="8" readonly="">
              <option value="">Chọn</option>
              <option <?php echo $bookings->booking_type==1?'selected="selected"':null ?> value="1">Hàng nhập</option>
              <option <?php echo $bookings->booking_type==2?'selected="selected"':null ?> value="2">Hàng xuất</option>
              <option <?php echo $bookings->booking_type==3?'selected="selected"':null ?> value="3">Khác</option>
            </select>
          </div>
          <label for="shipment_container">Số container</label>
          <div class="input-group">
            <input class="form-control" type="text" id="shipment_container" name="shipment_container" tabindex="2" >
          </div>
           
        </div>
        <div class="col-md-2 col-xs-6">
          <label for="dispatch_vehicle">Xe <a title="Thêm xe mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("vehicle/add") ?>','Thêm xe mới','dispatch_vehicle','<?php echo $this->url("vehicle/getvehicle") ?>','add_vehicle')"></i></a></label>
          <div class="input-group">
            <select class="form-control select2" id="dispatch_vehicle" name="dispatch_vehicle" required="required" tabindex="3">
              <option value="">Chọn</option>
              <?php foreach ($vehicles as $vehicle) { ?>
                <option <?php echo $dispatch_data->dispatch_vehicle==$vehicle->vehicle_id?'selected="selected"':null ?> value="<?php echo $vehicle->vehicle_id ?>"><?php echo $vehicle->vehicle_number ?></option>
              <?php } ?>
            </select>
          </div>  
          <div class="hr hr-8 dotted hr-double"></div>
          <label for="dispatch_booking">Số BK/BL </label>
          <div class="input-group">
            <select class="form-control" id="dispatch_booking" name="dispatch_booking" tabindex="9" readonly="">
                <option value="<?php echo $bookings->booking_id ?>"><?php echo $bookings->booking_number ?></option>
            </select>
          </div> 
          <label for="shipment_ton">Sản lượng nhận</label>
          <div class="input-group">
            <input class="form-control numbers" type="text" id="shipment_ton" name="shipment_ton" tabindex="2" >
          </div>
          
       </div>
       <div class="col-md-2 col-xs-6">
          <label for="dispatch_romooc">Mooc <a title="Thay lắp mooc" id="vehicle_romooc"><i class="ace-icon fa fa-exchange blue"></i></a></label>
          <div class="input-group">
            <input class="form-control" type="text" id="dispatch_romooc" name="dispatch_romooc" tabindex="4" readonly="" data="<?php echo $romoocs->romooc_id ?>" value="<?php echo $romoocs->romooc_number ?>" >
          </div>
          <div class="hr hr-8 dotted hr-double"></div>
          <label for="dispatch_place_from">Nơi lấy <a title="Thêm kho hàng mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("place/add") ?>','Thêm kho hàng mới','dispatch_place_from','<?php echo $this->url("place/getplace") ?>','add_place')"></i></a></label>
          <div class="input-group">
            <select class="form-control select2" id="dispatch_place_from" name="dispatch_place_from" required="required" tabindex="11">
              <option value="">Chọn</option>
              <?php foreach ($places as $place) { ?>
                <option <?php echo $dispatch_data->dispatch_place_from==$place->place_id?'selected="selected"':null ?> value="<?php echo $place->place_id ?>"><?php echo $place->place_name ?></option>
              <?php } ?>
            </select>
          </div>
          
          <label for="shipment_ton">Sản lượng giao</label>
          <div class="input-group">
            <input class="form-control numbers" type="text" id="shipment_ton" name="shipment_ton" tabindex="2" >
          </div>
          
        </div>
        <div class="col-md-2 col-xs-6">
          <label for="dispatch_staff">Tài xế <a title="Tài xế" id="vehicle_driver"><i class="ace-icon fa fa-user blue"></i></a></label>
          <div class="input-group">
            <input class="form-control" type="text" id="dispatch_staff" name="dispatch_staff" tabindex="5" readonly="" data="<?php echo $staffs->staff_id ?>" value="<?php echo $staffs->staff_name ?>">
          </div>
          <div class="hr hr-8 dotted hr-double"></div>
          <label for="dispatch_place_to">Nơi hạ <a title="Thêm kho hàng mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("place/add") ?>','Thêm kho hàng mới','dispatch_place_to','<?php echo $this->url("place/getplace") ?>','add_place')"></i></a></label>
          <div class="input-group">
            <select class="form-control select2" id="dispatch_place_to" name="dispatch_place_to" required="required" tabindex="12">
              <option value="">Chọn</option>
              <?php foreach ($places as $place) { ?>
                <option <?php echo $dispatch_data->dispatch_place_to==$place->place_id?'selected="selected"':null ?> value="<?php echo $place->place_id ?>"><?php echo $place->place_name ?></option>
              <?php } ?>
            </select>
          </div> 
          <label for="shipment_unit">ĐVT</label>
          <div class="input-group">
            <input class="form-control" type="text" id="shipment_unit" name="shipment_unit" tabindex="2" readonly="" >
          </div>
          
        </div>
        <div class="col-md-2 col-xs-6">
          <label for="dispatch_comment">Ghi chú</label>
          <div class="input-group">
            <input class="form-control" type="text" id="dispatch_comment" name="dispatch_comment" tabindex="10" value="<?php echo $dispatch_data->dispatch_comment ?>">
          </div>
          <div class="hr hr-8 dotted hr-double"></div>
          <label for="dispatch_start_date">Ngày lấy</label>
          <div class="input-group">
            <input class="form-control input-mask-datetime" type="text" id="dispatch_start_date" name="dispatch_start_date" tabindex="13" value="<?php echo $lib->hien_thi_ngay_thang($dispatch_data->dispatch_start_date) ?>" >
          </div>
          <label for="dispatch_end_date">Ngày hạ</label>
          <div class="input-group">
            <input class="form-control end-date" type="text" id="dispatch_end_date" name="dispatch_end_date" tabindex="14" value="<?php echo $lib->hien_thi_ngay_thang($dispatch_data->dispatch_end_date) ?>" >
          </div>
        </div>
      </div>
      <div id="costshipment" class="tab-pane">
        <div class="col-xs-12">
            <table id="dataTable_booking" style="width: 100%;">
                <tbody>
                <tr>
                    <td style="padding-right: 10px;"><input type="checkbox" name="chk"></td>
                    <td>
                        <table style="width:100%;">
                            <tbody>
                              <tr>
                                <td>
                                  <label>Sản lượng</label>
                                  <div class="input-group">
                                    <input type="text" class="booking_detail_number numbers" name="booking_detail_number[]" tabindex="16" required="required">
                                  </div>
                                </td>
                                <td>
                                  <label>ĐVT <a title="Thêm đơn vị tính mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("unit/add") ?>','Thêm đơn vị tính mới','.booking_detail_unit','<?php echo $this->url("unit/getunit") ?>','add_unit')"></i></a></label>
                                  <div class="input-group">
                                    <select class="form-control booking_detail_unit" name="booking_detail_unit[]" tabindex="17">
                                      <?php foreach ($units as $unit) { ?>
                                        <option value="<?php echo $unit->unit_id ?>" ><?php echo $unit->unit_name ?></option>
                                      <?php } ?>
                                    </select>
                                  </div>
                                </td>
                                <td>
                                  <label>Đơn giá</label>
                                  <div class="input-group">
                                    <input type="text" class="booking_detail_price numbers" name="booking_detail_price[]" tabindex="20">
                                  </div>
                                </td>
                              </tr>
                              <tr>
                                <td>
                                  <label>Số container</label>
                                  <div class="input-group">
                                    <input type="text" class="booking_detail_container" name="booking_detail_container[]" tabindex="18">
                                  </div>
                                </td>
                                <td>
                                  <label>Số seal</label>
                                  <div class="input-group">
                                    <input type="text" class="booking_detail_seal" name="booking_detail_seal[]" tabindex="19">
                                  </div>
                                </td>
                                <td>
                                  <label>Mặt hàng</label>
                                  <div class="input-group">
                                    <input type="text" class="booking_detail_customer_sub" name="booking_detail_customer_sub[]" tabindex="21">
                                  </div>
                                </td>
                              </tr>
                              
                        </tbody></table>
                        <div class="hr hr-8 dotted hr-double"></div>
                    </td>
                    
                </tr>
            </tbody>
            </table>
        
            <input type="button" value="Thêm" onclick="addRow_booking('dataTable_booking')">

            <input type="button" value="Xóa" onclick="deleteRow_booking('dataTable_booking')">
        </div>
      </div>
    </div>
      
  </form>
</div>

<script type="text/javascript">
  $('#dispatch_shipment_temp').change(function(){
    var booking = $('#dispatch_shipment_temp option:selected').attr('data');
     if (booking>0) {
        $.ajax({
          type: "GET",
          url: "<?php echo BASE_URL ?>/booking/getbookingdetail",
          data: {booking:booking}, 
          success: function(answer){
             var data = $.parseJSON(answer);
             $('#dispatch_booking_detail').html(data.container);
             $('#booking_type option[value='+data.type+']').attr('selected','selected');
             $('#booking_customer option[value='+data.customer+']').attr('selected','selected');
             $('#booking_customer').select2();
             $('#dispatch_place_from option[value='+data.from+']').attr('selected','selected');
             $('#dispatch_place_from').select2();
             $('#dispatch_place_to option[value='+data.to+']').attr('selected','selected');
             $('#dispatch_place_to').select2();
             $('#dispatch_start_date').val(data.start);
             $('#dispatch_end_date').val(data.end);

             var detail = $('#dispatch_booking_detail').val();
             $.ajax({
                type: "GET",
                url: "<?php echo BASE_URL ?>/booking/getbookingcont",
                data: {detail:detail}, 
                success: function(answer){
                   var data = $.parseJSON(answer);
                   $('#dispatch_booking_detail_number').val(data.number);
                   $('#dispatch_booking_detail_number').attr('max',data.number);
                   $('#booking_detail_unit').val(data.unit);
                }
            });
          }
      });

      $('#dispatch_booking').html('<option value="'+booking+'">'+$('#dispatch_shipment_temp option:selected').attr('alt')+'</option>');
      $('#dispatch_booking').attr('readonly',true);
      $('#booking_customer').select2({'disabled':true});
      $('#booking_type').attr('readonly',true);
     }
     
  });
  $('#booking_customer').change(function(){
    var customer = $('#booking_customer').val();
    var type = $('#booking_type').val();
    if (customer>0) {
      $.ajax({
          type: "GET",
          url: "<?php echo BASE_URL ?>/booking/getbooking",
          data: {customer:customer,type:type}, 
          success: function(answer){
             var data = $.parseJSON(answer);
             $('#dispatch_booking').html(data.booking);

             var booking = $('#dispatch_booking').val();
             if (booking>0) {
                $.ajax({
                  type: "GET",
                  url: "<?php echo BASE_URL ?>/booking/getbookingdetail",
                  data: {booking:booking}, 
                  success: function(answer){
                     var data = $.parseJSON(answer);
                     $('#dispatch_booking_detail').html(data.container);
                     $('#booking_type option[value='+data.type+']').attr('selected','selected');
                     $('#booking_customer option[value='+data.customer+']').attr('selected','selected');
                     $('#booking_customer').select2();
                     $('#dispatch_place_from option[value='+data.from+']').attr('selected','selected');
                     $('#dispatch_place_from').select2();
                     $('#dispatch_place_to option[value='+data.to+']').attr('selected','selected');
                     $('#dispatch_place_to').select2();
                     $('#dispatch_start_date').val(data.start);
                     $('#dispatch_end_date').val(data.end);

                     var detail = $('#dispatch_booking_detail').val();
                     $.ajax({
                        type: "GET",
                        url: "<?php echo BASE_URL ?>/booking/getbookingcont",
                        data: {detail:detail}, 
                        success: function(answer){
                           var data = $.parseJSON(answer);
                           $('#dispatch_booking_detail_number').val(data.number);
                           $('#dispatch_booking_detail_number').attr('max',data.number);
                           $('#booking_detail_unit').val(data.unit);
                        }
                    });
                  }
              });
             }
             else{
              $('#dispatch_booking_detail').html("");
              $('#dispatch_booking_detail_number').val("");
              $('#booking_detail_unit').val("");
             }
          }
      });
    }
  });
  $('#booking_type').change(function(){
    var customer = $('#booking_customer').val();
    var type = $('#booking_type').val();
    if (type>0) {
      $.ajax({
          type: "GET",
          url: "<?php echo BASE_URL ?>/booking/getbooking",
          data: {customer:customer,type:type}, 
          success: function(answer){
             var data = $.parseJSON(answer);
             $('#dispatch_booking').html(data.booking);

             var booking = $('#dispatch_booking').val();
             if (booking>0) {
                $.ajax({
                  type: "GET",
                  url: "<?php echo BASE_URL ?>/booking/getbookingdetail",
                  data: {booking:booking}, 
                  success: function(answer){
                     var data = $.parseJSON(answer);
                     $('#dispatch_booking_detail').html(data.container);
                     $('#booking_type option[value='+data.type+']').attr('selected','selected');
                     $('#booking_customer option[value='+data.customer+']').attr('selected','selected');
                     $('#booking_customer').select2();
                     $('#dispatch_place_from option[value='+data.from+']').attr('selected','selected');
                     $('#dispatch_place_from').select2();
                     $('#dispatch_place_to option[value='+data.to+']').attr('selected','selected');
                     $('#dispatch_place_to').select2();
                     $('#dispatch_start_date').val(data.start);
                     $('#dispatch_end_date').val(data.end);

                     var detail = $('#dispatch_booking_detail').val();
                     $.ajax({
                        type: "GET",
                        url: "<?php echo BASE_URL ?>/booking/getbookingcont",
                        data: {detail:detail}, 
                        success: function(answer){
                           var data = $.parseJSON(answer);
                           $('#dispatch_booking_detail_number').val(data.number);
                           $('#dispatch_booking_detail_number').attr('max',data.number);
                           $('#booking_detail_unit').val(data.unit);
                        }
                    });
                  }
              });
             }
             else{
              $('#dispatch_booking_detail').html("");
              $('#dispatch_booking_detail_number').val("");
              $('#booking_detail_unit').val("");
             }
          }
      });
    }
  });
  $('#dispatch_booking').change(function(){
    var booking = $('#dispatch_booking').val();
     $.ajax({
        type: "GET",
        url: "<?php echo BASE_URL ?>/booking/getbookingdetail",
        data: {booking:booking}, 
        success: function(answer){
           var data = $.parseJSON(answer);
           $('#dispatch_booking_detail').html(data.container);
           $('#booking_type option[value='+data.type+']').attr('selected','selected');
           $('#booking_customer option[value='+data.customer+']').attr('selected','selected');
           $('#booking_customer').select2();
           $('#dispatch_place_from option[value='+data.from+']').attr('selected','selected');
           $('#dispatch_place_from').select2();
           $('#dispatch_place_to option[value='+data.to+']').attr('selected','selected');
           $('#dispatch_place_to').select2();
           $('#dispatch_start_date').val(data.start);
           $('#dispatch_end_date').val(data.end);

           var detail = $('#dispatch_booking_detail').val();
           $.ajax({
              type: "GET",
              url: "<?php echo BASE_URL ?>/booking/getbookingcont",
              data: {detail:detail}, 
              success: function(answer){
                 var data = $.parseJSON(answer);
                 $('#dispatch_booking_detail_number').val(data.number);
                 $('#dispatch_booking_detail_number').attr('max',data.number);
                 $('#booking_detail_unit').val(data.unit);
              }
          });
        }
    });
  });
  $('#dispatch_booking_detail').change(function(){
    var detail = $('#dispatch_booking_detail').val();
     $.ajax({
        type: "GET",
        url: "<?php echo BASE_URL ?>/booking/getbookingcont",
        data: {detail:detail}, 
        success: function(answer){
           var data = $.parseJSON(answer);
           $('#dispatch_booking_detail_number').val(data.number);
           $('#dispatch_booking_detail_number').attr('max',data.number);
           $('#booking_detail_unit').val(data.unit);
        }
    });
  });

  $('#dispatch_vehicle').change(function(){
    var vehicle = $('#dispatch_vehicle').val();
    var date = $('#dispatch_date').val();
    if (vehicle>0) {
      $.ajax({
          type: "GET",
          url: "<?php echo BASE_URL ?>/vehicleromooc/getromooc",
          data: {vehicle:vehicle,date:date}, 
          success: function(answer){
             var data = $.parseJSON(answer);
             $('#dispatch_romooc').val(data.romooc_number);
             $('#dispatch_romooc').attr('data',data.romooc_id);
          }
      });
      $.ajax({
          type: "GET",
          url: "<?php echo BASE_URL ?>/driver/getdriver",
          data: {vehicle:vehicle,date:date}, 
          success: function(answer){
             var data = $.parseJSON(answer);
             $('#dispatch_staff').val(data.staff_name);
             $('#dispatch_staff').attr('data',data.staff_id);
          }
      });
    }
  });

  $('#vehicle_romooc').click(function(){
    var vehicle = $('#dispatch_vehicle').val();
    var date = $('#dispatch_date').val();
    if (vehicle>0) {
      view_click_other('<?php echo $this->url("vehicleromooc/viewromooc/?id=") ?>','Thông tin mooc',vehicle+'~'+date,'none');
    }
    
  });
  $('#vehicle_driver').click(function(){
    var vehicle = $('#dispatch_vehicle').val();
    var date = $('#dispatch_date').val();
    if (vehicle>0) {
      view_click_other('<?php echo $this->url("driver/viewdriver/?id=") ?>','Thông tin tài xế',vehicle+'~'+date,'none');
    }
  });
</script>