<script type="text/javascript">
$(document).ready(function(){
  $( ".select2" ).select2({dropdownAutoWidth : true});
      // Validate form
      $("#shipment_dispatch").validate({
        errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
        rules: {
        },
        submitHandler: function(form) {
          var shipment_romooc = $('#shipment_romooc').attr('data');
          var shipment_staff = $('#shipment_staff').attr('data');
          var shipment_container = $('#shipment_booking_detail option:selected').text();
          var shipment_price = $('#shipment_ton').attr('data');
          
          var formData = new FormData($("#shipment_dispatch")[0]);
          formData.append('shipment_dispatch', '<?php echo $dispatch_data->dispatch_id ?>');
          formData.append('shipment_romooc', shipment_romooc);
          formData.append('shipment_staff', shipment_staff);
          formData.append('shipment_container', shipment_container);
          formData.append('shipment_price', shipment_price);
          
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/shipment/addshipment", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: formData, // giá trị post
              cache: false,
              contentType: false,
              processData: false,
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error_shipment').hide();
                  $('#error_shipment').slideToggle(100); // hiển thị thẻ div success
                  $('#error_shipment').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error_shipment').fadeOut(10000);

              }
          });
          return false;
           
       }
           
         
      });

  
});

</script>

<div id="error_shipment" class="error"><?php echo isset($error) ? $error : null; ?></div>     
<div class="tabbable">
  <form id="shipment_dispatch" method="post" action="" autocomplete="off">
    <ul class="nav nav-tabs padding-18">
      <li class="active">
        <a data-toggle="tab" href="#homeshipment">
          <i class="green ace-icon fa fa-file-text-o bigger-120"></i>
          Thông tin
        </a>
      </li>

      <li>
        <a data-toggle="tab" href="#costshipment">
          <i class="blue ace-icon fa fa-th bigger-120"></i>
          Chi phí
        </a>
      </li>
    </ul>
    <div class="tab-content no-border ">
      <div id="homeshipment" class="tab-pane in active">
        <div class="col-md-2 col-xs-6">
          <label for="dispatch_code">Lệnh điều xe</label>
          <div class="input-group">
            <input class="form-control" type="text" id="dispatch_code" name="dispatch_code" tabindex="1" readonly="" value="<?php echo $dispatch_data->dispatch_code ?>">
          </div>
          <div class="hr hr-8 dotted hr-double"></div>
          <label for="shipment_customer">Khách hàng </label>
          <div class="input-group">
            <select class="form-control" id="shipment_customer" name="shipment_customer" tabindex="7" readonly="">
                <option value="<?php echo $customers->customer_id ?>"><?php echo $customers->customer_name ?></option>
            </select>
          </div>  
          <label for="shipment_do">Số DO</label>
          <div class="input-group">
            <input class="form-control" type="text" id="shipment_do" name="shipment_do" tabindex="14" >
          </div>
            
        </div>
        <div class="col-md-2 col-xs-6">
          <label for="shipment_date">Ngày</label>
          <div class="input-group">
            <input class="form-control input-mask-date" type="text" id="shipment_date" name="shipment_date" tabindex="2" required="required" value="<?php echo $lib->hien_thi_ngay_thang($dispatch_data->dispatch_date) ?>">
          </div>
          <div class="hr hr-8 dotted hr-double"></div>
          <label for="shipment_type">Loại hàng</label>
          <div class="input-group">
            <select class="form-control" id="shipment_type" name="shipment_type" tabindex="8" readonly="">
              <option value="">Chọn</option>
              <option <?php echo $bookings->booking_type==1?'selected="selected"':null ?> value="1">Hàng nhập</option>
              <option <?php echo $bookings->booking_type==2?'selected="selected"':null ?> value="2">Hàng xuất</option>
              <option <?php echo $bookings->booking_type==3?'selected="selected"':null ?> value="3">Khác</option>
            </select>
          </div>
          <label for="shipment_booking_detail">Số container</label>
          <div class="input-group">
            <select class="form-control" id="shipment_booking_detail" name="shipment_booking_detail" tabindex="15" required="required">
                <option value="">Chọn</option>
              <?php foreach ($booking_details as $booking_detail) { ?>
                <option value="<?php echo $booking_detail->booking_detail_id ?>"><?php echo $booking_detail->booking_detail_container ?></option>
              <?php } ?>
            </select>
          </div>
           
        </div>
        <div class="col-md-2 col-xs-6">
          <label for="shipment_vehicle">Xe <a title="Thêm xe mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("vehicle/add") ?>','Thêm xe mới','shipment_vehicle','<?php echo $this->url("vehicle/getvehicle") ?>','add_vehicle')"></i></a></label>
          <div class="input-group">
            <select class="form-control select2" id="shipment_vehicle" name="shipment_vehicle" required="required" tabindex="3">
              <option value="">Chọn</option>
              <?php foreach ($vehicles as $vehicle) { ?>
                <option <?php echo $dispatch_data->dispatch_vehicle==$vehicle->vehicle_id?'selected="selected"':null ?> value="<?php echo $vehicle->vehicle_id ?>"><?php echo $vehicle->vehicle_number ?></option>
              <?php } ?>
            </select>
          </div>  
          <div class="hr hr-8 dotted hr-double"></div>
          <label for="shipment_booking">Số BK/BL </label>
          <div class="input-group">
            <select class="form-control" id="shipment_booking" name="shipment_booking" tabindex="9" readonly="">
                <option value="<?php echo $bookings->booking_id ?>"><?php echo $bookings->booking_number ?></option>
            </select>
          </div> 
          <label for="shipment_ton_receive">Sản lượng nhận</label>
          <div class="input-group">
            <input class="form-control numbers" type="text" id="shipment_ton_receive" name="shipment_ton_receive" tabindex="16" >
          </div>
          
       </div>
       <div class="col-md-2 col-xs-6">
          <label for="shipment_romooc">Mooc <a title="Thay lắp mooc" id="vehicle_romooc"><i class="ace-icon fa fa-exchange blue"></i></a></label>
          <div class="input-group">
            <input class="form-control" type="text" id="shipment_romooc" name="shipment_romooc" tabindex="4" readonly="" data="<?php echo $romoocs->romooc_id ?>" value="<?php echo $romoocs->romooc_number ?>" >
          </div>
          <div class="hr hr-8 dotted hr-double"></div>
          <label for="shipment_place_from">Nơi lấy <a title="Thêm kho hàng mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("place/add") ?>','Thêm kho hàng mới','shipment_place_from','<?php echo $this->url("place/getplace") ?>','add_place')"></i></a></label>
          <div class="input-group">
            <select class="form-control select2" id="shipment_place_from" name="shipment_place_from" required="required" tabindex="10">
              <option value="">Chọn</option>
              <?php foreach ($places as $place) { ?>
                <option <?php echo $dispatch_data->dispatch_place_from==$place->place_id?'selected="selected"':null ?> value="<?php echo $place->place_id ?>"><?php echo $place->place_name ?></option>
              <?php } ?>
            </select>
          </div>
          
          <label for="shipment_ton">Sản lượng giao</label>
          <div class="input-group">
            <input class="form-control numbers" type="text" id="shipment_ton" name="shipment_ton" tabindex="17" required="required" >
          </div>
          
        </div>
        <div class="col-md-2 col-xs-6">
          <label for="shipment_staff">Tài xế <a title="Tài xế" id="vehicle_driver"><i class="ace-icon fa fa-user blue"></i></a></label>
          <div class="input-group">
            <input class="form-control" type="text" id="shipment_staff" name="shipment_staff" tabindex="5" readonly="" data="<?php echo $staffs->staff_id ?>" value="<?php echo $staffs->staff_name ?>">
          </div>
          <div class="hr hr-8 dotted hr-double"></div>
          <label for="shipment_place_to">Nơi hạ <a title="Thêm kho hàng mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("place/add") ?>','Thêm kho hàng mới','shipment_place_to','<?php echo $this->url("place/getplace") ?>','add_place')"></i></a></label>
          <div class="input-group">
            <select class="form-control select2" id="shipment_place_to" name="shipment_place_to" required="required" tabindex="11">
              <option value="">Chọn</option>
              <?php foreach ($places as $place) { ?>
                <option <?php echo $dispatch_data->dispatch_place_to==$place->place_id?'selected="selected"':null ?> value="<?php echo $place->place_id ?>"><?php echo $place->place_name ?></option>
              <?php } ?>
            </select>
          </div> 
          <label for="shipment_unit">ĐVT</label>
          <div class="input-group">
            <select class="form-control" id="shipment_unit" name="shipment_unit" tabindex="18" required="required">
              <?php foreach ($units as $unit) { ?>
                <option value="<?php echo $unit->unit_id ?>"><?php echo $unit->unit_name ?></option>
              <?php } ?>
            </select>
          </div>
          
        </div>
        <div class="col-md-2 col-xs-6">
          <label for="shipment_comment">Ghi chú</label>
          <div class="input-group">
            <input class="form-control" type="text" id="shipment_comment" name="shipment_comment" tabindex="6" value="<?php echo $dispatch_data->dispatch_comment ?>">
          </div>
          <div class="hr hr-8 dotted hr-double"></div>
          <label for="shipment_start_date">Ngày lấy</label>
          <div class="input-group">
            <input class="form-control input-mask-datetime" type="text" id="shipment_start_date" name="shipment_start_date" tabindex="12" value="<?php echo $lib->hien_thi_ngay_thang($dispatch_data->dispatch_start_date) ?>" >
          </div>
          <label for="shipment_end_date">Ngày hạ</label>
          <div class="input-group">
            <input class="form-control input-mask-datetime" type="text" id="shipment_end_date" name="shipment_end_date" tabindex="13" value="<?php echo $lib->hien_thi_ngay_thang($dispatch_data->dispatch_end_date) ?>" >
          </div>
        </div>
      </div>
      <div id="costshipment" class="tab-pane">
        <div class="col-xs-12">
            <table id="dataTable_booking" style="width: 100%;">
                <tbody>
                <tr>
                    <td style="padding-right: 10px;"><input type="checkbox" name="chk"></td>
                    <td>
                        <table style="width:100%;">
                            <tbody>
                              <tr>
                                <td>
                                  <label>Sản lượng</label>
                                  <div class="input-group">
                                    <input type="text" class="booking_detail_number numbers" name="booking_detail_number[]" tabindex="16" required="required">
                                  </div>
                                </td>
                                <td>
                                  <label>ĐVT <a title="Thêm đơn vị tính mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("unit/add") ?>','Thêm đơn vị tính mới','.booking_detail_unit','<?php echo $this->url("unit/getunit") ?>','add_unit')"></i></a></label>
                                  <div class="input-group">
                                    <select class="form-control booking_detail_unit" name="booking_detail_unit[]" tabindex="17">
                                      <?php foreach ($units as $unit) { ?>
                                        <option value="<?php echo $unit->unit_id ?>" ><?php echo $unit->unit_name ?></option>
                                      <?php } ?>
                                    </select>
                                  </div>
                                </td>
                                <td>
                                  <label>Đơn giá</label>
                                  <div class="input-group">
                                    <input type="text" class="booking_detail_price numbers" name="booking_detail_price[]" tabindex="20">
                                  </div>
                                </td>
                              </tr>
                              <tr>
                                <td>
                                  <label>Số container</label>
                                  <div class="input-group">
                                    <input type="text" class="booking_detail_container" name="booking_detail_container[]" tabindex="18">
                                  </div>
                                </td>
                                <td>
                                  <label>Số seal</label>
                                  <div class="input-group">
                                    <input type="text" class="booking_detail_seal" name="booking_detail_seal[]" tabindex="19">
                                  </div>
                                </td>
                                <td>
                                  <label>Mặt hàng</label>
                                  <div class="input-group">
                                    <input type="text" class="booking_detail_customer_sub" name="booking_detail_customer_sub[]" tabindex="21">
                                  </div>
                                </td>
                              </tr>
                              
                        </tbody></table>
                        <div class="hr hr-8 dotted hr-double"></div>
                    </td>
                    
                </tr>
            </tbody>
            </table>
        
            <input type="button" value="Thêm" onclick="addRow_booking('dataTable_booking')">

            <input type="button" value="Xóa" onclick="deleteRow_booking('dataTable_booking')">
        </div>
      </div>
    </div>
      
  </form>
</div>

<script type="text/javascript">
  
  $('#shipment_booking_detail').change(function(){
    var detail = $('#shipment_booking_detail').val();
     $.ajax({
        type: "GET",
        url: "<?php echo BASE_URL ?>/booking/getbookingcont",
        data: {detail:detail}, 
        success: function(answer){
           var data = $.parseJSON(answer);
           $('#shipment_ton_receive').val(data.number);
           $('#shipment_ton').val(data.number);
           $('#shipment_ton').attr('data',data.price);
           $('#shipment_unit option[value='+data.unit+']').attr('selected','selected');
        }
    });
  });

  $('#shipment_vehicle').change(function(){
    var vehicle = $('#shipment_vehicle').val();
    var date = $('#shipment_date').val();
    if (vehicle>0) {
      $.ajax({
          type: "GET",
          url: "<?php echo BASE_URL ?>/vehicleromooc/getromooc",
          data: {vehicle:vehicle,date:date}, 
          success: function(answer){
             var data = $.parseJSON(answer);
             $('#shipment_romooc').val(data.romooc_number);
             $('#shipment_romooc').attr('data',data.romooc_id);
          }
      });
      $.ajax({
          type: "GET",
          url: "<?php echo BASE_URL ?>/driver/getdriver",
          data: {vehicle:vehicle,date:date}, 
          success: function(answer){
             var data = $.parseJSON(answer);
             $('#shipment_staff').val(data.staff_name);
             $('#shipment_staff').attr('data',data.staff_id);
          }
      });
    }
  });

  $('#vehicle_romooc').click(function(){
    var vehicle = $('#shipment_vehicle').val();
    var date = $('#shipment_date').val();
    if (vehicle>0) {
      view_click_other('<?php echo $this->url("vehicleromooc/viewromooc/?id=") ?>','Thông tin mooc',vehicle+'~'+date,'none');
    }
    
  });
  $('#vehicle_driver').click(function(){
    var vehicle = $('#shipment_vehicle').val();
    var date = $('#shipment_date').val();
    if (vehicle>0) {
      view_click_other('<?php echo $this->url("driver/viewdriver/?id=") ?>','Thông tin tài xế',vehicle+'~'+date,'none');
    }
  });
</script>