
<div id="error_dispatch" class="error"><?php echo isset($error) ? $error : null; ?></div>     
<div class="login_body">
  
      <div class="col-md-2 col-xs-6">
        <label for="dispatch_date">Ngày</label>
        <div class="input-group">
          <input class="form-control input-mask-date" type="text" id="dispatch_date" name="dispatch_date" tabindex="1" required="required" value="<?php echo $lib->hien_thi_ngay_thang($dispatch_data->dispatch_date) ?>">
        </div>
        <div class="hr hr-8 dotted hr-double"></div>
        <label for="booking_customer">Khách hàng </label>
        <div class="input-group">
          <select class="form-control select2" id="booking_customer" name="booking_customer" tabindex="7" readonly="">
              <option value="<?php echo $customers->customer_id ?>"><?php echo $customers->customer_name ?></option>
          </select>
        </div>  
        <label for="dispatch_place_from">Nơi lấy <a title="Thêm kho hàng mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("place/add") ?>','Thêm kho hàng mới','dispatch_place_from','<?php echo $this->url("place/getplace") ?>','add_place')"></i></a></label>
        <div class="input-group">
          <select class="form-control select2" id="dispatch_place_from" name="dispatch_place_from" required="required" tabindex="13">
            <option value="">Chọn</option>
            <?php foreach ($places as $place) { ?>
              <option <?php echo $dispatch_data->dispatch_place_from==$place->place_id?'selected="selected"':null ?> value="<?php echo $place->place_id ?>"><?php echo $place->place_name ?></option>
            <?php } ?>
          </select>
        </div>  
      </div>
      <div class="col-md-2 col-xs-6">
        <label for="dispatch_code">Số lệnh</label>
        <div class="input-group">
          <input class="form-control" type="text" id="dispatch_code" name="dispatch_code" tabindex="2" value="<?php echo $dispatch_data->dispatch_code ?>">
        </div>
        <div class="hr hr-8 dotted hr-double"></div>
        <label for="booking_type">Loại hàng</label>
        <div class="input-group">
          <select class="form-control" id="booking_type" name="booking_type" tabindex="8" readonly="">
            <option value="">Chọn</option>
            <option <?php echo $bookings->booking_type==1?'selected="selected"':null ?> value="1">Hàng nhập</option>
            <option <?php echo $bookings->booking_type==2?'selected="selected"':null ?> value="2">Hàng xuất</option>
            <option <?php echo $bookings->booking_type==3?'selected="selected"':null ?> value="3">Khác</option>
          </select>
        </div>
        <label for="dispatch_place_to">Nơi hạ <a title="Thêm kho hàng mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("place/add") ?>','Thêm kho hàng mới','dispatch_place_to','<?php echo $this->url("place/getplace") ?>','add_place')"></i></a></label>
        <div class="input-group">
          <select class="form-control select2" id="dispatch_place_to" name="dispatch_place_to" required="required" tabindex="14">
            <option value="">Chọn</option>
            <?php foreach ($places as $place) { ?>
              <option <?php echo $dispatch_data->dispatch_place_to==$place->place_id?'selected="selected"':null ?> value="<?php echo $place->place_id ?>"><?php echo $place->place_name ?></option>
            <?php } ?>
          </select>
        </div>  
      </div>
      <div class="col-md-2 col-xs-6">
        <label for="dispatch_vehicle">Xe <a title="Thêm xe mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("vehicle/add") ?>','Thêm xe mới','dispatch_vehicle','<?php echo $this->url("vehicle/getvehicle") ?>','add_vehicle')"></i></a></label>
        <div class="input-group">
          <select class="form-control select2" id="dispatch_vehicle" name="dispatch_vehicle" required="required" tabindex="3">
            <option value="">Chọn</option>
            <?php foreach ($vehicles as $vehicle) { ?>
              <option <?php echo $dispatch_data->dispatch_vehicle==$vehicle->vehicle_id?'selected="selected"':null ?> value="<?php echo $vehicle->vehicle_id ?>"><?php echo $vehicle->vehicle_number ?></option>
            <?php } ?>
          </select>
        </div>  
        <div class="hr hr-8 dotted hr-double"></div>
        <label for="dispatch_booking">Số BK/BL </label>
        <div class="input-group">
          <select class="form-control" id="dispatch_booking" name="dispatch_booking" tabindex="9" readonly="">
              <option value="<?php echo $bookings->booking_id ?>"><?php echo $bookings->booking_number ?></option>
          </select>
        </div> 
        <label for="dispatch_start_date">Ngày lấy</label>
        <div class="input-group">
          <input class="form-control start-date" type="text" id="dispatch_start_date" name="dispatch_start_date" tabindex="15" value="<?php echo $lib->hien_thi_ngay_thang($dispatch_data->dispatch_start_date) ?>" >
        </div>
     </div>
     <div class="col-md-2 col-xs-6">
        <label for="dispatch_romooc">Mooc <a title="Thay lắp mooc" id="vehicle_romooc"><i class="ace-icon fa fa-exchange blue"></i></a></label>
        <div class="input-group">
          <input class="form-control" type="text" id="dispatch_romooc" name="dispatch_romooc" tabindex="4" readonly="" data="<?php echo $romoocs->romooc_id ?>" value="<?php echo $romoocs->romooc_number ?>" >
        </div>
        <div class="hr hr-8 dotted hr-double"></div>
        <label for="dispatch_booking_detail">Số cont</label>
        <div class="input-group">
          <select class="form-control" id="dispatch_booking_detail" name="dispatch_booking_detail" tabindex="10" required="required" readonly="">
              <option value="<?php echo $details->booking_detail_id ?>"><?php echo $details->booking_detail_container ?></option>
          </select>
        </div>
        <label for="dispatch_end_date">Ngày hạ</label>
        <div class="input-group">
          <input class="form-control end-date" type="text" id="dispatch_end_date" name="dispatch_end_date" tabindex="16" value="<?php echo $lib->hien_thi_ngay_thang($dispatch_data->dispatch_end_date) ?>" >
        </div>
      </div>
      <div class="col-md-2 col-xs-6">
        <label for="dispatch_staff">Tài xế <a title="Tài xế" id="vehicle_driver"><i class="ace-icon fa fa-user blue"></i></a></label>
        <div class="input-group">
          <input class="form-control" type="text" id="dispatch_staff" name="dispatch_staff" tabindex="5" readonly="" data="<?php echo $staffs->staff_id ?>" value="<?php echo $staffs->staff_name ?>">
        </div>
        <div class="hr hr-8 dotted hr-double"></div>
        <label for="dispatch_booking_detail_number">Sản lượng</label>
        <div class="input-group">
          <input class="form-control text-right" type="text" id="dispatch_booking_detail_number" name="dispatch_booking_detail_number" tabindex="11" required="required" value="<?php echo $dispatch_data->dispatch_booking_detail_number ?>">
        </div>
        <label for="dispatch_comment">Ghi chú</label>
        <div class="input-group">
          <input class="form-control" type="text" id="dispatch_comment" name="dispatch_comment" tabindex="17" value="<?php echo $dispatch_data->dispatch_comment ?>">
        </div>
      </div>
      
      <div class="col-md-2 col-xs-6">
        <label for="dispatch_shipment_temp">Lô hàng nhận</label>
        <div class="input-group">
          <select class="form-control" id="dispatch_shipment_temp" name="dispatch_shipment_temp" tabindex="6" readonly="">
            <?php foreach ($shipment_temps as $shipment_temp) { ?>
              <option data="<?php echo $shipment_temp->shipment_temp_booking ?>" alt="<?php echo '['.$shipment_temp->booking_code.'] - '.$shipment_temp->booking_number ?>" value="<?php echo $shipment_temp->shipment_temp_id ?>"><?php echo '['.$shipment_temp->booking_code.']-'.$shipment_temp->booking_number.': '.(isset($place_data[$shipment_temp->booking_place_from])?$place_data[$shipment_temp->booking_place_from]:null).'~'.(isset($place_data[$shipment_temp->booking_place_to])?$place_data[$shipment_temp->booking_place_to]:null).' |'.date('d/m/Y',$shipment_temp->shipment_temp_date) ?></option>
            <?php } ?>
          </select>
        </div>
        <div class="hr hr-8 dotted hr-double"></div>
        <label for="booking_detail_unit">ĐVT</label>
        <div class="input-group">
          <input class="form-control" type="text" id="booking_detail_unit" name="booking_detail_unit" tabindex="12" readonly="" value="<?php echo $units->unit_name ?>">
        </div>
      </div>
  
</div>
