
<?php
$url_order = 'ASC';
if ($order_by == 'import_stock_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'import_stock_code')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'import_stock_date')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'import_stock_total')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'import_stock_price')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'username')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'invoice_number')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';


    $i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>
<section class="content-header">
    <h1>NHẬP KHO</h1>
  <ol class="breadcrumb">
    <li><a href="<?php echo $this->url('admin') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><a href="<?php echo $this->url('importstock') ?>">Nhập kho</a></li>
  </ol>
</section>
<div id="content" style="padding:5px;">

    <div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
        <?php if(!isset($disable_control)){ ?>
        <div class="add-box"><a class="add_button" id="export_excel" href="<?= $this->url('importstock/export/'.strtotime($batdau).'/'.strtotime($ketthuc))?>" ><i class="fa fa-download"></i> Xuất</a></div>
        <div class="add-box"><a class="add_button" onClick="add_click();"><i class="fa fa-plus"></i> Thêm mới</a></div>
        <?php } ?>
    </div>
    <div class="tablenav top">
        <div class="add-box">
            <select id="sl_round" name="sl_round" style="width:90px">
             <?php 
                for ($k=1; $k < 13; $k++) { 
                    echo '<option value="'.$k.'">Tháng '.$k.'</option>';
                }
             ?>
            </select>
            <select id="sl_staff" name="sl_staff" style="width:100px">
             <?php 
                $nam = date('Y');
                for ($k=($nam-5); $k < ($nam+5); $k++) { 
                    echo '<option value="'.$k.'">Năm '.$k.'</option>';
                }
             ?>
            </select>

            <input type="button" name="xem" id="xem" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  
            
        </div>
    </div>
    <div class="tablenav top">
        <div style="clear:both"></div>
        <div class="add-box">
                  
            Từ  <input style="width:80px" type="search" name="batdau" id="batdau" placeholder="Chọn ngày" <?php if(isset($batdau)) echo "value='$batdau'"; ?> >  
            Đến  <input style="width:80px" type="search" name="ketthuc" id="ketthuc" placeholder="Chọn ngày" <?php if(isset($ketthuc)) echo "value='$ketthuc'"; ?> >  
             <input type="button" name="xem" id="xem" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  
            
        </div>

      </div>
    <div class="tablenav top">
        <?php if(!isset($disable_control)){ ?>
        <div class="alignleft actions">
            <select name="action" id="action">
                <option value="-1" selected="selected">Chọn</option>
                
                <option value="delete">Xóa</option>
            </select>
            <input type="button" name="" id="doaction" class="button action" value="Áp dụng" onclick="action();">
        </div>
        <?php } ?>
        <div class="alignleft actions">
        <select name="m" id="chonloc">
          <option  value="18446744073709">Hiển thị tất cả</option>
          <option value="50">Hiển thị 50 giá trị</option>
                <option value="100">Hiển thị 100 giá trị</option>
                <option value="150">Hiển thị 150 giá trị</option>
                <option selected="selected" value="200">Hiển thị 200 giá trị</option>
        </select>
        <input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">                               
        </div>

      </div>

</div>

<input type="hidden" value="<?php echo $tab_active ?>" id="sl_tha">

<div class="tabs">
  <ul class="tab-links">
    <?php foreach ($houses as $house) { ?>
    <li <?php echo $tab_active==$house->house_id?'class="active"':null ?> ><a href="#tab<?php echo $house->house_id ?>"><?php echo $house->house_name ?></a></li>
    <?php } ?>
  </ul>
  <div class="tab-content">
    <?php foreach ($houses as $house) { ?>
    <div class="tab <?php echo $tab_active==$house->house_id?"active":null ?>" id="tab<?php echo $house->house_id ?>" >
      <table class="table_data" id="tblExport<?php echo $house->house_id ?>">
        <thead>
            <tr>
                <th class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
                <th class="fix">
                    <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','import_stock_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'import_stock_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                </th>
                <th  class="fix">
                    <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','import_stock_code','<?php echo $url_order ?>')">Phiếu nhập kho <?php if ($order_by == 'import_stock_code'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                </th>
                <th  class="fix">
                    <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','import_stock_date','<?php echo $url_order ?>')">Ngày <?php if ($order_by == 'import_stock_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                </th>
                <th  class="fix">
                    <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','import_stock_total','<?php echo $url_order ?>')">Số lượng <?php if ($order_by == 'import_stock_total'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                </th>
                <th  class="fix">
                    <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','import_stock_price','<?php echo $url_order ?>')">Giá trị <?php if ($order_by == 'import_stock_price'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                </th>
                <th  class="fix">
                    <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','invoice_number','<?php echo $url_order ?>')">Số hóa đơn <?php if ($order_by == 'invoice_number'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                </th>
                <th  class="fix">
                    <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','import_stock_comment','<?php echo $url_order ?>')">Nội dung <?php if ($order_by == 'import_stock_comment'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                </th>
                <th  class="fix">
                    <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','username','<?php echo $url_order ?>')">Người lập <?php if ($order_by == 'username'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                </th>
                
                   
                <?php if(!isset($disable_control)){ ?>
                   
                <th  class="fix">&nbsp;</th>
                <?php } ?>
            </tr>
            
           </thead>
           <tbody>
            <?php $tong = 0;
            foreach ($imports[$house->house_id] as $import_stock) : 
              $tong += $import_stock->import_stock_total;
            ?>
                <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $import_stock->import_stock_id ?>" class="edit_tr">
                    <td><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $import_stock->import_stock_id ?>"></td>
                    <td class="fix"><?php echo $i++; ?></td>
                    <td class="fix"  id="import_stock_code_<?php echo $import_stock->import_stock_id; ?>"><?php echo $import_stock->import_stock_code ?></td>
                    <td class="fix" id="import_stock_date_<?php echo $import_stock->import_stock_id; ?>"><?php echo $lib->hien_thi_ngay_thang($import_stock->import_stock_date) ?></td>
                    <td class="fix"  id="import_stock_total_<?php echo $import_stock->import_stock_id; ?>"><?php echo $import_stock->import_stock_total ?></td>
                    <td class="fix"  id="import_stock_price_<?php echo $import_stock->import_stock_id; ?>"><?php echo $lib->formatMoney($import_stock->import_stock_price) ?></td>
                    <td class="fix"  id="invoice_number_<?php echo $import_stock->import_stock_id; ?>"><?php echo $import_stock->invoice_number ?></td>
                    <td class="fix"  id="import_stock_comment_<?php echo $import_stock->import_stock_id; ?>"><?php echo $import_stock->import_stock_comment ?></td>
                    <td class="fix"  id="username_<?php echo $import_stock->import_stock_id; ?>"><?php echo $import_stock->username ?></td>
                    <td class="fix" style="display:none" id="invoice_date_<?php echo $import_stock->import_stock_id; ?>"><?php echo $import_stock->invoice_date>0?$lib->hien_thi_ngay_thang($import_stock->invoice_date):null ?></td>
                    <td class="fix" style="display:none" data="<?php echo $import_stock->invoice_customer ?>" id="invoice_customer_<?php echo $import_stock->import_stock_id; ?>"><?php echo isset($customer_data['customer_id'][$import_stock->invoice_customer])?$customer_data['customer_name'][$import_stock->invoice_customer]:null ?></td>
                    <td class="fix" style="display:none" id="deliver_<?php echo $import_stock->import_stock_id; ?>"><?php echo $import_stock->deliver ?></td>
                    <td class="fix" style="display:none" id="deliver_address_<?php echo $import_stock->import_stock_id; ?>"><?php echo $import_stock->deliver_address ?></td>
                    <td class="fix" style="display:none" data="<?php echo $import_stock->house ?>" id="house_<?php echo $import_stock->import_stock_id; ?>"><?php echo $import_stock->house_name ?></td>
                
                    <?php if(!isset($disable_control)){ ?>
                    <td class="pull-right">
                        <button class="btn btn-sm btn-flat btn-primary"><i class="fa fa-edit"></i> Sửa</button>
                        <button class="btn btn-sm btn-flat btn-danger" onclick="del(<?php echo $import_stock->import_stock_id ?>)" ><i class="fa fa-remove"></i> Xóa</button>
                    </td>
                    <?php } ?>
                </tr>
            <?php endforeach; ?>
            <tr  style="font-weight: bold; color: rgb(23, 119, 226);" >
            
                <th colspan="4" style="border-right: 1px solid rgb(236, 235, 235);border-top: 1px solid #80C8E5;padding: 7px; text-align: right;" >
                    Tổng cộng
                </th>
                <td class="fix" ><?php echo $lib->formatMoney($tong) ?></td>
                <td class="fix" ></td>
                <td class="fix" ></td>
                <td class="fix" ></td>
                <td class="fix" ></td>
            </tr>
           </tbody>
        </table>
    </div>
    <?php } ?>
  </div>
</div>


<?php
$this->helper('slidePaginator');
?>
<div class="add-field">
    <section class="content">
      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- general form elements -->
          
            <!-- /.box-header -->
            <!-- form start -->
            <form id="add_import_stock" role="form" method="post" action="" enctype="multipart/form-data">
              <div class="tabs">
                <ul class="tab-links">
                    <li class="active"><a href="#tab100">Thông tin</a></li>
                    <li><a href="#tab200">Chi phí</a></li>
                    
                </ul>
             
                <div class="tab-content">
                    <div id="tab100" class="tab active">
                      <div class="row">
                        <div class="col-md-4 col-xs-6">
                          <div class="box-body">
                            <div class="form-group">
                              <label for="import_stock_date">Ngày nhập kho</label>
                              <input class="ngay" type="text" id="import_stock_date"  name="import_stock_date" tabindex="1" required="required" >
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-6 col-xs-6">
                                      <label for="invoice_number">Hóa đơn số</label>
                                      <input style="width:100px" type="text" id="invoice_number"  name="invoice_number" tabindex="3"  >
                                  </div>
                                  <div class="col-md-6 col-xs-6">
                                    <label for="invoice_date">Ngày</label>
                                      <input style="width:60px" class="ngay" type="text" id="invoice_date"  name="invoice_date" tabindex="4"  >
                                  </div>
                              </div>
                            </div>
                            <div class="form-group">
                              <label for="deliver">Người giao hàng</label>
                              <input type="text" id="deliver"  name="deliver" tabindex="6" >
                            </div>
                            
                          </div>
                          <!-- /.box-body -->
                          
                        </div>
                        <div class="col-md-4 col-xs-6">
                          <div class="box-body">
                            <div class="form-group">
                              <label for="import_stock_code">Số phiếu</label>
                              <input type="text" id="import_stock_code"  name="import_stock_code" tabindex="2" required="required" >
                            </div>
                            <div class="form-group">
                              <label for="invoice_customer">Đơn vị bán <a target="_blank" title="Thêm khách hàng" href="<?php echo $this->url('customer/newcus') ?>"><i class="fa fa-plus"></i></a></label>
                              <input type="text" autocomplete="off" id="invoice_customer"  name="invoice_customer" tabindex="5"  placeholder="Nhập tên hoặc * để chọn"  >
                                <ul id="customer_list_id"></ul>
                            </div>
                            <div class="form-group">
                              <label for="deliver_address">Địa chỉ</label>
                              <input type="text" id="deliver_address"  name="deliver_address" tabindex="7" >
                            </div>
                            
                          </div>
                          <!-- /.box-body -->
                          
                        </div>
                        <div class="col-md-4 col-xs-6">
                          <div class="box-body">
                            <div class="form-group">
                              <label for="import_stock_comment">Nội dung</label>
                              <input type="text" id="import_stock_comment"  name="import_stock_comment" tabindex="6" required="required" >
                            </div>
                            <div class="form-group">
                              <label for="house">Kho nhập <a target="_blank" title="Thêm kho" href="<?php echo $this->url('house') ?>"><i class="fa fa-plus"></i></a></label>
                              <select id="house" name="house" tabindex="8">
                                <?php foreach ($houses as $house) { ?>
                                    <option value="<?php echo $house->house_id ?>"><?php echo $house->house_name.' ['.$house->house_place.']' ?></option>
                                <?php } ?>
                              </select>
                            </div>
                            
                          </div>
                          <!-- /.box-body -->
                          
                        </div>

                      </div>
                      <div class="row">
                        <div class="col-md-12">
                          <fieldset class="groupbox">
                            <legend>
                                <span><h3>Sản phẩm</h3></span>
                            </legend>

                            <table id="dataTable" border="1" style="width: 100%; border: 1px solid rgb(221, 217, 217); margin-bottom: 10px" >
                                <tbody>
                                <tr>
                                    <td><input type="checkbox" name="chk"></td>
                                    <td>
                                        <table style="width:100%">
                                            <tr>
                                                <td>Tên sản phẩm</td>
                                                <td>
                                                    <input type="text" autocomplete="off" class="spare_part" name="spare_part[]" placeholder="Nhập tên hoặc * để chọn" tabindex="3" >
                                                    <ul class="name_list_id"></ul>
                                                </td>
                                                
                                                <td>
                                                    Mã sản phẩm
                                                </td>
                                                <td>
                                                    <input autocomplete="off" type="text" class="spare_part_code" name="spare_part_code[]" tabindex="4" placeholder="Nhập tên hoặc * để chọn" >
                                                    <ul class="name_list_id_2"></ul>
                                                </td>
                                                
                                            </tr>
                                            <tr>
                                              <td>
                                                    Nhà sản xuất
                                                </td>
                                                <td>
                                                    <input type="text" class="spare_part_brand" name="spare_part_brand[]" tabindex="5" >
                                                </td>
                                                <td>
                                                    Ngày sản xuất
                                                </td>
                                                <td>
                                                    <input type="text" class="spare_part_date_manufacture ngay" name="spare_part_date_manufacture[]" tabindex="6" >
                                                </td>
                                                
                                            </tr>
                                            <tr>
                                                
                                                <td>
                                                    Đơn vị tính
                                                </td>
                                                <td>
                                                    <input type="text" class="spare_stock_unit" name="spare_stock_unit[]" tabindex="7" >
                                                </td>
                                                <td>Đơn giá</td>
                                                <td>
                                                    <input type="text" class="spare_stock_price numbers" name="spare_stock_price[]" tabindex="8" >
                                                </td>
                                            </tr>
                                            <tr>
                                                
                                                <td>Số lượng</td>
                                                <td>
                                                  <input style="width:50px" type="text" class="spare_stock_number number" name="spare_stock_number[]" tabindex="10" value="1" min="1" >
                                                  <input type="checkbox" name="check_seri[]" class="check_seri" > Có số seri
                                                </td>
                                                <td>VAT</td>
                                                <td>
                                                  <input style="width:50px" type="text" class="spare_stock_vat_percent number" name="spare_stock_vat_percent[]" tabindex="9" placeholder="%" >
                                                    <input style="width:120px" type="text" class="spare_stock_vat_price numbers" name="spare_stock_vat_price[]" tabindex="9" placeholder="Tổng tiền thuế" >
                                                    
                                                </td>
                                            </tr>
                                            <tr class="tr_seri" style="display:none">
                                                <td></td>
                                                <td colspan="4">
                                                    
                                                    <table class="dataTb" id="dataTb0" border="1" style="width: 100%; border: 1px solid rgb(221, 217, 217); margin-bottom: 10px" >
                                                      <tbody>
                                                        <tr>
                                                          <td><input type="checkbox" name="chk3" class="chk3"></td>
                                                          <td>
                                                            <table style="width:100%">
                                                              <tr>
                                                                <td>Số seri</td>
                                                                <td>
                                                                  <input code="" data="0" type="text" class="spare_part_seri2" name="spare_part_seri2[]" tabindex="6" >
                                                                  <span class="dem" data="1">(1)</span>
                                                                </td>
                                                                
                                                              </tr>
                                                            </table>
                                                          </td>
                                                        </tr>
                                                      </tbody>
                                                    </table>
                                                    <input type="button" value="Thêm" class="addRow3" onclick="addRow3('dataTb0')">

                                                    <input type="button" value="Xóa" class="deleteRow3" onclick="deleteRow3('dataTb0')">
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                            </tbody>
                            </table>
                        </fieldset>
                            <input type="button" value="Thêm" onclick="addRow('dataTable')">

                            <input type="button" value="Xóa" onclick="deleteRow('dataTable')">
                        </div>
                      </div>
                    </div>
                    <div id="tab200" class="tab">
                      <div class="row">
                        <div class="col-md-12">
                            <div class="box-body">
                                <fieldset class="groupbox">
                                        <legend>
                                            <span><h3>Chi phí</h3></span>
                                        </legend>

                                        <table id="dataTable2" border="1" style="width: 100%; border: 1px solid rgb(221, 217, 217); margin-bottom: 10px" >
                                            <tbody>
                                                <tr>
                                                    <td><input type="checkbox" name="chk2" data=""></td>
                                                    <td>
                                                        <table style="width:100%">
                                                            <tr>
                                                                <td>Chi phí <a target="_blank" title="Thêm chi phí" href="<?php echo $this->url('costlist') ?>"><i class="fa fa-plus"></i></a></td>
                                                                <td>
                                                                    <select style="width:150px" name="cost_list[]" class="cost_list" >
                                                                        <?php foreach ($cost_lists as $cost) { ?>
                                                                            <option value="<?php echo $cost->cost_list_id ?>"><?php echo $cost->cost_list_name ?></option>
                                                                        <?php } ?>
                                                                    </select>
                                                                </td>
                                                                <td>Số tiền</td>
                                                                <td>
                                                                    <input type="text" class="cost numbers" name="cost[]" style="width:120px">
                                                                    <input type="checkbox" class="check_vat" name="check_vat[]" value="1"> VAT
                                                                </td>
                                                            </tr>
                                                            <tr>
                                                                <td>Nội dung</td>
                                                                <td>
                                                                    <textarea class="comment" name="comment[]"></textarea>
                                                                </td>
                                                                <td>Người nhận <a target="_blank" title="Thêm người nhận" href="<?php echo $this->url('customer/newcus') ?>"><i class="fa fa-plus"></i></a></td>
                                                                <td>
                                                                    <input type="text" autocomplete="off" class="receiver" name="receiver[]" placeholder="Nhập tên hoặc * để chọn" >
                                                                    <ul class="name_list_id_3"></ul>
                                                                </td>
                                                                
                                                            </tr>
                                                            <tr>
                                                                <td>Số Hóa đơn chứng từ</td>
                                                                <td>
                                                                    <input type="text" class="cost_document" name="cost_document[]" style="width:100px" > Ngày <input type="text" class="cost_document_date ngay" name="cost_document_date[]" style="width:60px">
                                                                </td>
                                                            </tr>
                                                        </table>
                                                    </td>
                                                </tr>
                                                
                                            </tbody>
                                        </table>
                                        <input type="button" value="Thêm" onclick="addRow2('dataTable2')">
                                        <input type="button" value="Xóa" onclick="deleteRow2('dataTable2')">

                                    </fieldset>
                            </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              
              <?php if(!isset($disable_control)){ ?>
              <div class="row">
                <div class="col-md-12">
                    <div class="box-footer">
                    <input type="hidden" readonly id="yes" name="yes" required="required" >
                    <button type="submit" class="btn btn-primary" tabindex="9">Hoàn thành</button>
                    <button type="reset" class="btn" tabindex="10">Nhập lại</button>
                  </div>
                  <div class="box-footer">
                    <div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>
                  </div>
                </div>
              </div>
              <?php } ?>
            </form>
          
          <!-- /.box -->

        </div>
        <!--/.col (left) -->
        
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
       
</div>


<script type="text/javascript">
$('html').click(function(e) {
    
    $('.name_list_id').slideUp(200);
    $('.name_list_id_2').slideUp(200);
    $('.name_list_id_3').slideUp(200);
    $('#customer_list_id').slideUp(200);
});

    $('.edit_tr').click(function(e){
        if(!$('.checkbox').is(':focus') && e.target.nodeName != "A"){
            if(!$('.checkbox').is(':focus')){
                $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);
            }
            var import_stock_code = $(this).find("#import_stock_code_"+$(this).attr('id')).text();
            var import_stock_date = $(this).find("#import_stock_date_"+$(this).attr('id')).text();
            var invoice_number = $(this).find("#invoice_number_"+$(this).attr('id')).text();
            var invoice_date = $(this).find("#invoice_date_"+$(this).attr('id')).text();
            var invoice_customer = $(this).find("#invoice_customer_"+$(this).attr('id')).attr('data');
            var invoice_customer_name = $(this).find("#invoice_customer_"+$(this).attr('id')).text();
            var import_stock_comment = $(this).find("#import_stock_comment_"+$(this).attr('id')).text();

            var deliver = $(this).find("#deliver_"+$(this).attr('id')).text();
            var deliver_address = $(this).find("#deliver_address_"+$(this).attr('id')).text();
            var house = $(this).find("#house_"+$(this).attr('id')).attr('data');
            
            //alert(import_stock_code);
            $('#yes').val($(this).attr('id'));
            
            $('#import_stock_date').val(import_stock_date.replace(/\//g,"-"));
            $('#import_stock_code').val(import_stock_code);

            $('#invoice_date').val(invoice_date.replace(/\//g,"-"));
            $('#invoice_number').val(invoice_number);
            $('#invoice_customer').attr('data',invoice_customer);
            $('#invoice_customer').val(invoice_customer_name);
            $('#import_stock_comment').val(import_stock_comment);

            $('#deliver').val(deliver);
            $('#deliver_address').val(deliver_address);
            $('#house option[value='+house+']').attr('selected','selected');

            $('#dataTable tbody tr').remove();
        
            var import_stock_id = $(this).attr('id');
            $.ajax({
                url: '<?php echo BASE_URL ?>/importstock/spare',
                type: 'POST',
                data: {import_stock:import_stock_id},
                success:function(data){
                    //alert(data);
                    $('#dataTable tbody').append(data);
                    $('.spare_part').keyup(function(){
                        var row = $(this).parent().parent().parent().parent().parent().parent();
                        var rowIndex = row[0].rowIndex;

                        var keyword = $(this).val();
                        $.ajax({
                            url: '<?php echo BASE_URL ?>/importstock/getSpare',
                            type: 'POST',
                            data: {keyword:keyword, offset:rowIndex},
                            success:function(data){
                                $('.name_list_id:eq('+rowIndex+')').slideDown(200);
                                $('.name_list_id:eq('+rowIndex+')').html(data);
                            }
                        });
                        if ($('.spare_part:eq('+rowIndex+')').val() == "" || $('.spare_part:eq('+rowIndex+')').attr('data') == "") {
                            
                            $('.spare_part:eq('+rowIndex+')').attr('data',"");
                        }

                        
                    });

                $('.spare_part').on('keydown', function() {
                        var row = $(this).parent().parent().parent().parent().parent().parent();
                        var rowIndex = row[0].rowIndex;

                        var key = event.keyCode || event.charCode;

                        if( key == 8 || key == 46 ){
                            $('.spare_part:eq('+rowIndex+')').attr('data',"");
                        }
                            
                      }); 

                $('.spare_part_code').keyup(function(){
                      var row = $(this).parent().parent().parent().parent().parent().parent();
                      var rowIndex = row[0].rowIndex;

                      var keyword = $(this).val();
                      $.ajax({
                          url: '<?php echo BASE_URL ?>/importstock/getSpare',
                          type: 'POST',
                          data: {keyword:keyword, offset:rowIndex},
                          success:function(data){
                              $('.name_list_id_2:eq('+rowIndex+')').slideDown(200);
                              $('.name_list_id_2:eq('+rowIndex+')').html(data);
                          }
                      });
                      if ($('.spare_part:eq('+rowIndex+')').val() == "" || $('.spare_part:eq('+rowIndex+')').attr('data') == "") {
                          
                          $('.spare_part:eq('+rowIndex+')').attr('data',"");
                      }

                      
                  });

              

              $('.spare_stock_vat_percent').keyup(function(){
                          var row = $(this).parent().parent().parent().parent().parent().parent();
                          var rowIndex = row[0].rowIndex;

                          var percent = parseFloat($(this).val());
                          var number = parseFloat(get_number('.spare_stock_number:eq('+rowIndex+')')) || 0;

                          $('.spare_stock_vat_price:eq('+rowIndex+')').val(
                              Math.round(
                              (parseFloat(get_number('.spare_stock_price:eq('+rowIndex+')'))*percent/100)*number
                              )
                          );

                          $('.spare_stock_vat_price:eq('+rowIndex+')').val(function(index, value) {
                              return value
                                .replace(/\D/g, "")
                                .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
                              ;
                            });
                          
                      });
                    $('.spare_stock_price').keyup(function(){
                          var row = $(this).parent().parent().parent().parent().parent().parent();
                          var rowIndex = row[0].rowIndex;

                          var percent = parseFloat(get_number('.spare_stock_vat_percent:eq('+rowIndex+')')) || 0;
                          var price = parseFloat($(this).val().replace(/\,/g,''));
                          var number = parseFloat(get_number('.spare_stock_number:eq('+rowIndex+')')) || 0;

                          $('.spare_stock_vat_price:eq('+rowIndex+')').val(
                              Math.round(
                              (price*percent/100)*number
                              )
                          );

                          $('.spare_stock_vat_price:eq('+rowIndex+')').val(function(index, value) {
                              return value
                                .replace(/\D/g, "")
                                .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
                              ;
                            });
                          
                      });
                      $('.spare_stock_number').keyup(function(){
                        var row = $(this).parent().parent().parent().parent().parent().parent();
                        var rowIndex = row[0].rowIndex;

                        var number = parseFloat($(this).val());
                        if (number == 0 || number == "") {
                          $(this).val("1");
                        }
                        var percent = parseFloat(get_number('.spare_stock_vat_percent:eq('+rowIndex+')')) || 0;

                        $('.spare_stock_vat_price:eq('+rowIndex+')').val(
                            Math.round(
                            (parseFloat(get_number('.spare_stock_price:eq('+rowIndex+')'))*percent/100)*number
                            )
                        );

                        $('.spare_stock_vat_price:eq('+rowIndex+')').val(function(index, value) {
                            return value
                              .replace(/\D/g, "")
                              .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
                            ;
                          });

                        if ($('.check_seri:eq('+rowIndex+')').is(':checked')) {
                          var ns = parseInt($('.dem:last').attr("data"));
                          $('.tr_seri:eq('+rowIndex+')').show();
                          var table=document.getElementById('dataTb'+rowIndex);
                          var rowCount=table.rows.length;
                          var val_add = parseInt($(this).val());
                          if (rowCount < val_add) {
                            var num_row = val_add-rowCount;
                            for (var i = 0; i < num_row; i++) {
                              var row=table.insertRow(rowCount);
                              var colCount=table.rows[0].cells.length;
                              for(var j=0;j<colCount;j++){
                                  var newcell=row.insertCell(j);
                                  newcell.innerHTML=table.rows[0].cells[j].innerHTML;
                                  switch(newcell.childNodes[0].type){
                                      case"text":newcell.childNodes[0].value="";
                                      break;
                                      case"checkbox":newcell.childNodes[0].checked=false;
                                      break;
                                      case"select-one":newcell.childNodes[0].selectedIndex=0;
                                      break;
                                  }
                              }

                              $('.spare_part_seri2:last').val("");
                              $('.spare_part_seri2:last').attr('code',"");
                              
                              $('input[name="chk3"]:last').attr('data',"");
                              $('input[name="chk3"]:last').attr('tabindex',0);
                              $('input[name="chk3"]:last').attr('title',"");
                              $('input[name="chk3"]:last').attr('class',"");
                              $('input[name="chk3"]:last').attr('alt',0);

                              ns++;
            
                              $('.dem:last').attr("data",ns);
                              $('.dem:last').html("("+ns+")");

                              rowCount++;
                            }
                          }
                          else if(rowCount > val_add){
                           
                            for(var i=rowCount;i>val_add;i--){
                                  if(rowCount>1){
                                    table.deleteRow(rowCount-1);
                                    rowCount--;
                                  }
                                  
                              }
                          }
                          
                        }
                        
                    });

                  $('.check_seri').click(function(){
                    var row = $(this).parent().parent().parent().parent().parent().parent();
                    var rowIndex = row[0].rowIndex;

                      if($(this).is(':checked')){
                        var ns = parseInt($('.dem:last').attr("data"));
                        $('.tr_seri:eq('+rowIndex+')').show();
                          var table=document.getElementById('dataTb'+rowIndex);
                          var rowCount=table.rows.length;
                          var val_add = parseInt($('.spare_stock_number:eq('+rowIndex+')').val());
                          if (rowCount < val_add) {
                            var num_row = val_add-rowCount;
                            for (var j = 0; j < num_row; j++) {
                              var row=table.insertRow(rowCount);
                              var colCount=table.rows[0].cells.length;
                              for(var i=0;i<colCount;i++){
                                  var newcell=row.insertCell(i);
                                  newcell.innerHTML=table.rows[0].cells[i].innerHTML;
                                  switch(newcell.childNodes[0].type){
                                      case"text":newcell.childNodes[0].value="";
                                      break;
                                      case"checkbox":newcell.childNodes[0].checked=false;
                                      break;
                                      case"select-one":newcell.childNodes[0].selectedIndex=0;
                                      break;
                                  }
                              }

                              $('.spare_part_seri2:last').val("");
                              $('.spare_part_seri2:last').attr('code',"");
                              
                              $('input[name="chk3"]:last').attr('data',"");
                              $('input[name="chk3"]:last').attr('tabindex',0);
                              $('input[name="chk3"]:last').attr('title',"");
                              $('input[name="chk3"]:last').attr('class',"");
                              $('input[name="chk3"]:last').attr('alt',0);

                              ns++;
            
                              $('.dem:last').attr("data",ns);
                              $('.dem:last').html("("+ns+")");

                              rowCount++;
                            }
                          }
                      }
                      else{
                        $('.tr_seri:eq('+rowIndex+')').hide();
                      }
                    });

                

                   
                    $('.number').keyup(function(event) {

                          // skip for arrow keys
                      if(event.which >= 37 && event.which <= 40) return;

                      // format number
                      $(this).val(function(index, value) {
                        return value
                          .replace(/[^0-9-.]/g, "")
                        ;
                      });
                    });
                   
                   $('.numbers').keyup(function(event) {

                          // skip for arrow keys
                      if(event.which >= 37 && event.which <= 40) return;

                      // format number
                      $(this).val(function(index, value) {
                        return value
                          .replace(/[^0-9]/g, "")
                          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
                        ;
                      });
                    });

                   function get_number(id){
                    return $(id).val().replace(/\,/g,'');
                  }
                  function set_item_other(item,value,code,date,brand,vitri,unit,price) {
                      // change input value
                      $('.spare_part:eq('+vitri+')').val(value);
                      $('.spare_part:eq('+vitri+')').attr("data",item);
                      $('.spare_part_code:eq('+vitri+')').val(code);
                      $('.spare_part_date_manufacture:eq('+vitri+')').val(date);
                      $('.spare_part_brand:eq('+vitri+')').val(brand);
                      $('.spare_stock_unit:eq('+vitri+')').val(unit);
                      $('.spare_stock_price:eq('+vitri+')').val(price);

                      var percent = parseFloat(get_number('.spare_stock_vat_percent:eq('+vitri+')')) || 0;
                      var number = parseFloat($('.spare_stock_number:eq('+vitri+')').val()) || 0;
                      $('.spare_stock_vat_price:eq('+vitri+')').val(
                            Math.round(
                            (parseFloat(get_number('.spare_stock_price:eq('+vitri+')'))*percent/100)*number
                            )
                        );
                      
                      // hide proposition list
                      $('.name_list_id').hide();
                      $('.name_list_id_2').hide();
                      $('.spare_part:eq('+vitri+')').focus();

                      $(".numbers").val(function(index, value) {
                      return value
                        .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
                      ;
                    });

                  }

                  $(".ngay").datepicker(
                  {
                    closeText: "Đóng",
                    currentText: "Hiện tại",
                    nextText: "Tiếp",
                    prevText: "Quay lại",
                    monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
                    monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
                    dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
                    dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
                    dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
                    dateFormat: 'dd-mm-yy',
                    changeMonth: true,
                    changeYear: true,
                    yearRange: "-100:+0",
                    firstDay: 1,
                    isRTL: false,
                    showButtonPanel: true
                }
                  );

                }
            });

            $('#dataTable2 tbody tr').remove();
        
            var import_stock_id = $(this).attr('id');
            $.ajax({
                url: '<?php echo BASE_URL ?>/importstock/getcost',
                type: 'POST',
                data: {import_stock:import_stock_id},
                success:function(data){
                    //alert(data);
                    $('#dataTable2 tbody').append(data);

                    

                    $('.receiver').keyup(function(){
                        var row = $(this).parent().parent().parent().parent().parent().parent();
                        var rowIndex = row[0].rowIndex;

                        var keyword = $(this).val();
                        $.ajax({
                            url: '<?php echo BASE_URL ?>/shipment/getreceiver',
                            type: 'POST',
                            data: {keyword:keyword, offset:rowIndex},
                            success:function(data){
                                $('.name_list_id_3:eq('+rowIndex+')').slideDown(200);
                                $('.name_list_id_3:eq('+rowIndex+')').html(data);
                            }
                        });
                        if ($('.receiver:eq('+rowIndex+')').val() == "" || $('.receiver:eq('+rowIndex+')').attr('data') == "") {
                            
                            $('.receiver:eq('+rowIndex+')').attr('data',"");
                        }

                        
                    });

                    $('.receiver').on('keydown', function() {
                        var row = $(this).parent().parent().parent().parent().parent().parent();
                        var rowIndex = row[0].rowIndex;

                        var key = event.keyCode || event.charCode;

                        if( key == 8 || key == 46 ){
                            $('.receiver:eq('+rowIndex+')').attr('data',"");
                        }
                            
                      });

                    function set_item_receiver(value,name,vitri) {
                        // change input value
                        $('.receiver:eq('+vitri+')').val(name);
                        $('.receiver:eq('+vitri+')').attr("data",value);
                        
                        // hide proposition list
                        $('.name_list_id_3').hide();
                        $('.receiver:eq('+vitri+')').focus();
                         
                         
                    }


                        $('.number').keyup(function(event) {

                            // skip for arrow keys
                        if(event.which >= 37 && event.which <= 40) return;

                        // format number
                        $(this).val(function(index, value) {
                          return value
                            .replace(/[^0-9-.]/g, "")
                          ;
                        });
                      });
                     
                     $('.numbers').keyup(function(event) {

                            // skip for arrow keys
                        if(event.which >= 37 && event.which <= 40) return;

                        // format number
                        $(this).val(function(index, value) {
                          return value
                            .replace(/[^0-9]/g, "")
                            .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
                          ;
                        });
                      });

                     $(".ngay").datepicker(
                    {
                      closeText: "Đóng",
                      currentText: "Hiện tại",
                      nextText: "Tiếp",
                      prevText: "Quay lại",
                      monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
                      monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
                      dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
                      dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
                      dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
                      dateFormat: 'dd-mm-yy',
                      changeMonth: true,
                      changeYear: true,
                      yearRange: "-100:+0",
                      firstDay: 1,
                      isRTL: false,
                      showButtonPanel: true
                  }
                    );
                }
            });

            $( ".add-field" ).dialog( "open" );
        }
    });
</script>
<script type="text/javascript">

function add_click(){
    $('#yes').val("");
    $('.add-field').slideDown(500);
     $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);   
        $('#import_stock_code').val("");
        $('#import_stock_date').val("");
        $('#invoice_date').val("");
            $('#invoice_number').val("");
            $('#invoice_customer').attr('data',"");
            $('#invoice_customer').val("");
        $('#import_stock_comment').val("");

         $('#deliver').val("");
            $('#deliver_address').val("");
        
        $('input[name="chk"]').attr('data',"");
        $('input[name="chk2"]').attr('data',"");
        $('input[name="chk3"]').attr('data',"");
        $('input[type="text"]').attr('disabled',false);

        $('.number').focus(function(){
            if ( $(this).val() == '0') {
               $(this).val(""); 
            };
            
        });
        $('.number').blur(function(){
            if ( $(this).val() == "") {
                $(this).val(0);
            };
            
        });


   $( ".add-field" ).dialog( "open" );

}


$(document).ready(function(){
            // Validate form
            $("#add_import_stock").validate({
                errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
                rules: {
                    
                },
                submitHandler: function(form) {
                
                    var import_stock_code = $('#import_stock_code').attr('value');
                    var import_stock_date = $('#import_stock_date').attr('value');
                    var invoice_number = $('#invoice_number').attr('value');
                    var invoice_date = $('#invoice_date').attr('value');
                    var invoice_customer = $('#invoice_customer').attr('data');
                    var import_stock_comment = $('#import_stock_comment').attr('value');
                    var deliver = $('#deliver').attr('value');
                    var deliver_address = $('#deliver_address').attr('value');
                    var house = $('#house').attr('value');

                    var spare_part = [];

                    var check_seri = [];

                    var spare_part_name = [];
                    var spare_part_id = [];
                    var spare_part_seri = [];

                    var spare_part_code_id = [];

                    var spare_part_code2 = [];
                    var spare_part_brand2 = [];
                    var spare_part_date_manufacture2 = [];
                    var spare_stock_unit2 = [];
                    var spare_stock_number2 = [];
                    var spare_stock_price2 = [];
                    var spare_stock_vat_percent2 = [];
                    var spare_stock_vat_price2 = [];

                    var spare_part_code = [];
                    var spare_part_brand = [];
                    var spare_part_date_manufacture = [];
                    var spare_stock_unit = [];
                    var spare_stock_number = [];
                    var spare_stock_price = [];
                    var spare_stock_vat_percent = [];
                    var spare_stock_vat_price = [];

                    $('.check_seri').each(function() { 
                        
                        if ($(this).is(':checked')) {
                          check_seri.push(1);
                        }
                        else{
                          check_seri.push(0);
                        }
                    });
                    
                    var err = 0;

                    $('.spare_part_code').each(function() { 
                      if ($(this).val().trim() == "") {
                        alert('Vui lòng nhập vào Mã sản phẩm');
                        err = 1;
                        return false;
                      }
                        spare_part_code2.push($(this).val());
                    });

                    if (err == 1) {
                      return false;
                    }

                    $('.spare_part_brand').each(function() { 
                        spare_part_brand2.push($(this).val());
                    });

                    $('.spare_part_date_manufacture').each(function() { 
                        spare_part_date_manufacture2.push($(this).val());
                    });

                    $('.spare_stock_unit').each(function() { 
                        spare_stock_unit2.push($(this).val());
                    });

                    $('.spare_stock_number').each(function() { 
                        spare_stock_number2.push($(this).val());
                    });

                    $('.spare_stock_price').each(function() { 
                        spare_stock_price2.push($(this).val());
                    });
                    $('.spare_stock_vat_percent').each(function() { 
                        spare_stock_vat_percent2.push($(this).val());
                    });
                    $('.spare_stock_vat_price').each(function() { 
                        spare_stock_vat_price2.push($(this).val());
                    });

                    $('.spare_part').each(function(index) { 
                      var $this = $(this);
                      if(check_seri[index] == 1){
                        $('.spare_part_seri2[data='+index+']').each(function() { 
                          spare_part_seri.push($(this).val());
                          spare_part_name.push($this.val());
                          spare_part_code_id.push($this.attr('data'));
                          spare_part_id.push($(this).attr('code'));
                          spare_part_code.push(spare_part_code2[index]);
                          spare_part_brand.push(spare_part_brand2[index]);
                          spare_part_date_manufacture.push(spare_part_date_manufacture2[index]);
                          spare_stock_unit.push(spare_stock_unit2[index]);
                          spare_stock_number.push(1);
                          spare_stock_price.push(spare_stock_price2[index]);
                          spare_stock_vat_percent.push(spare_stock_vat_percent2[index]);
                          spare_stock_vat_price.push(parseInt(spare_stock_vat_price2[index].replace(/\,/g,'')/spare_stock_number2[index]));
                        });
                      }
                      else{
                        $('.spare_part_seri2[data='+index+']').each(function() { 
                          spare_part_seri.push("");
                          spare_part_name.push($this.val());
                          spare_part_code_id.push($this.attr('data'));
                          spare_part_id.push($(this).attr('code'));
                          spare_part_code.push(spare_part_code2[index]);
                          spare_part_brand.push(spare_part_brand2[index]);
                          spare_part_date_manufacture.push(spare_part_date_manufacture2[index]);
                          spare_stock_number.push(spare_stock_number2[index]);
                          spare_stock_unit.push(spare_stock_unit2[index]);
                          spare_stock_price.push(spare_stock_price2[index]);
                          spare_stock_vat_percent.push(spare_stock_vat_percent2[index]);
                          spare_stock_vat_price.push(spare_stock_vat_price2[index]);
                        });
                      }
                        
                    });


                    for (var i = 0; i < spare_part_name.length; i++) {
                        spare_part.push({'spare_part_code_id':spare_part_code_id[i],'spare_part_name':spare_part_name[i], 'spare_part_id':spare_part_id[i], 'spare_part_code':spare_part_code[i], 'spare_part_seri':spare_part_seri[i], 'spare_part_brand':spare_part_brand[i], 'spare_part_date_manufacture':spare_part_date_manufacture[i], 'spare_stock_unit':spare_stock_unit[i], 'spare_stock_number':spare_stock_number[i], 'spare_stock_price':spare_stock_price[i], 'spare_stock_vat_percent':spare_stock_vat_percent[i], 'spare_stock_vat_price':spare_stock_vat_price[i]});
                        
                        
                    };

                    

                    var import_stock_cost = [];

                    var import_stock_cost_id = [];
                    var cost_list = [];
                    var cost = [];
                    var check_vat = [];
                    var comment = [];
                    var receiver = [];
                    var cost_document = [];
                    var cost_document_date = [];

                    $("input[name='chk2']").each( function () {
                        import_stock_cost_id.push($(this).attr('data'));
                    });
                    $('.cost_list').each(function() { 
                        cost_list.push($(this).val());
                    });
                    $('.cost').each(function() { 
                        cost.push($(this).val());
                    });
                    $('.check_vat').each(function() { 
                        if($(this).is(':checked'))
                            check_vat.push($(this).val());
                        else
                            check_vat.push(0);
                    });
                    $('.comment').each(function() { 
                        comment.push($(this).val());
                    });
                    $('.receiver').each(function() { 
                        if ($(this).attr('data') != "") {
                            receiver.push($(this).attr('data'));
                        }
                        else{
                            receiver.push(0);
                        }
                        
                    });
                    $('.cost_document').each(function() { 
                        cost_document.push($(this).val());
                    });
                    $('.cost_document_date').each(function() { 
                        cost_document_date.push($(this).val());
                    });

                    for (var i = 0; i < receiver.length; i++) {
                        import_stock_cost.push({'import_stock_cost_id':import_stock_cost_id[i], 'cost_list':cost_list[i], 'cost':cost[i], 'check_vat':check_vat[i], 'comment':comment[i], 'receiver':receiver[i], 'cost_document':cost_document[i], 'cost_document_date':cost_document_date[i]});
                        
                        
                    };

                    
                    var yes = $('#yes').attr('value');
                    
                    var action      = "them";
                 
                    $.ajax({
                        type: "POST", // phương thức gởi đi
                        url: "<?php echo BASE_URL ?>/importstock/add", // nơi mà dữ liệu sẽ chuyển đến khi submit
                        data: {
                            import_stock_code: import_stock_code,
                            import_stock_date: import_stock_date,
                            invoice_date: invoice_date,
                            invoice_number: invoice_number,
                            invoice_customer: invoice_customer,
                            import_stock_comment: import_stock_comment,
                            spare_part: spare_part,
                            deliver: deliver,
                            deliver_address: deliver_address,
                            house: house,
                            import_stock_cost: import_stock_cost,
                            yes: yes,
                            }, // giá trị post
                        success: function(answer){ // if everything goes well
                            //alert(answer);
                            $('#error').hide();
                            $('#error').slideToggle(100); // hiển thị thẻ div success
                            $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                            $('#error').fadeOut(10000);

                            if (yes != "") {
                                if (answer.trim() != "Thông tin này đã tồn tại" ) {
                                  setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);
                                    $('#import_stock_name_'+yes).text(import_stock_name);
                                    $('#province_name_'+yes).text($('#province option:selected').text());
                                }
                            }
                            else{
                                if (answer.trim() != "Thông tin này đã tồn tại") {
                                  setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);
                                    var lastID = parseInt($('#lasted').html());
                                    var rowCount = parseInt($('.table_data > tbody > tr').length);
                                    $('.table_data > tbody:last')
                                    .append(
                                        '<tr onclick="HighLightTR(this,#4d90fe,cc3333);" id="'+parseInt(lastID+1)+'" class="edit_tr"><td><input name="check[]" type="checkbox" class="checkbox" value="'+parseInt(lastID+1)+'"></td><td class="fix">'+parseInt(rowCount+1)+'</td><td class="fix" id="import_stock_name_'+parseInt(lastID+1)+'">'+import_stock_name+'</td><td class="fix" data="'+province+'" id="province_name_'+parseInt(lastID+1)+'">'+$('#province option:selected').text()+'</td><td><a class="error" href="#">Sửa</a> | <a class="error" onclick="del('+parseInt(lastID+1)+')">Xóa</a></td></tr>'
                                    );

                                    $('#lasted').html(parseInt(lastID+2));
                                }
                            }
                        }
                    });
                    return false;
                     
                 }
            });
   
   $('#invoice_customer').keyup(function(){
      
        var keyword = $(this).val();
        $.ajax({
            url: '<?php echo BASE_URL ?>/importstock/getcustomer',
            type: 'POST',
            data: {keyword:keyword},
            success:function(data){
                $('#customer_list_id').slideDown(200);
                $('#customer_list_id').html(data);
            }
        });
        if ($('#invoice_customer').val() == "" || $('#invoice_customer').attr('data') == "") {
            //$('#loc_from').val("");
            $('#invoice_customer').attr('data',"");
            $('#invoice_customer').attr('code',false);
        }
      
   });

   $('.spare_part').keyup(function(){
        var row = $(this).parent().parent().parent().parent().parent().parent();
        var rowIndex = row[0].rowIndex;

        var keyword = $(this).val();
        $.ajax({
            url: '<?php echo BASE_URL ?>/importstock/getSpare',
            type: 'POST',
            data: {keyword:keyword, offset:rowIndex},
            success:function(data){
                $('.name_list_id:eq('+rowIndex+')').slideDown(200);
                $('.name_list_id:eq('+rowIndex+')').html(data);
            }
        });
        if ($('.spare_part:eq('+rowIndex+')').val() == "" || $('.spare_part:eq('+rowIndex+')').attr('data') == "") {
            
            $('.spare_part:eq('+rowIndex+')').attr('data',"");
        }

        
    });

$('.spare_part').on('keydown', function() {
        var row = $(this).parent().parent().parent().parent().parent().parent();
        var rowIndex = row[0].rowIndex;

        var key = event.keyCode || event.charCode;

        if( key == 8 || key == 46 ){
            $('.spare_part:eq('+rowIndex+')').attr('data',"");
        }
            
      }); 

$('.spare_part_code').keyup(function(){
        var row = $(this).parent().parent().parent().parent().parent().parent();
        var rowIndex = row[0].rowIndex;

        var keyword = $(this).val();
        $.ajax({
            url: '<?php echo BASE_URL ?>/importstock/getSpare',
            type: 'POST',
            data: {keyword:keyword, offset:rowIndex},
            success:function(data){
                $('.name_list_id_2:eq('+rowIndex+')').slideDown(200);
                $('.name_list_id_2:eq('+rowIndex+')').html(data);
            }
        });
        if ($('.spare_part:eq('+rowIndex+')').val() == "" || $('.spare_part:eq('+rowIndex+')').attr('data') == "") {
            
            $('.spare_part:eq('+rowIndex+')').attr('data',"");
        }

        
    });




$('.spare_part_code').blur(function(){
    var row = $(this).parent().parent().parent().parent().parent().parent();
    var rowIndex = row[0].rowIndex;

    var check_type = 0;

    var val = $(this).val().trim();
    
    $('.spare_part_code').each(function() { 
        if (val != "" && val == $(this).val().trim()) {
            check_type ++;
        }
    });

    

    if (check_type >= 2) {
        alert('Sản phẩm này đã có!');
        $(this).val("");
        $('.spare_part:eq('+rowIndex+')').attr('data',"");
        $('.spare_part:eq('+rowIndex+')').val("");
        $('.spare_part_brand:eq('+rowIndex+')').val("");
        $('.spare_part_seri:eq('+rowIndex+')').val("");
        $('.spare_part_date_manufacture:eq('+rowIndex+')').val("");
        
    };
    
});
$('.spare_part').blur(function(){
    var row = $(this).parent().parent().parent().parent().parent().parent();
    var rowIndex = row[0].rowIndex;

    var check_type = 0;

    var val = $(this).val().trim();
    
    $('.spare_part').each(function() { 
        if (val != "" && val == $(this).val().trim()) {
            check_type ++;
        }
    });

    

    if (check_type >= 2) {
        alert('Sản phẩm này đã có!');
        $(this).val("");
        $('.spare_part:eq('+rowIndex+')').attr('data',"");
        $('.spare_part_code:eq('+rowIndex+')').val("");
        $('.spare_part_brand:eq('+rowIndex+')').val("");
        $('.spare_part_seri:eq('+rowIndex+')').val("");
        $('.spare_part_date_manufacture:eq('+rowIndex+')').val("");
        
    };
    
});
$('.spare_part_seri2').blur(function(){
    var row = $(this).parent().parent().parent().parent().parent().parent().parent().parent().parent().parent().parent().parent().parent().parent();
    var rowIndex = row[0].rowIndex;

    var check_type = 0;

    var val = $(this).val().trim();
    
    $('.tr_seri:eq('+rowIndex+') input[type=text]').each(function() { 
        if (val != "" && val == $(this).val().trim()) {
            check_type ++;
        }
    });

    

    if (check_type >= 2) {
        alert('Sản phẩm này đã có!');
        $(this).val("");
        
    };
    
});


$('.spare_stock_vat_percent').keyup(function(){
      var row = $(this).parent().parent().parent().parent().parent().parent();
      var rowIndex = row[0].rowIndex;

      var percent = parseFloat($(this).val());
      var number = parseFloat(get_number('.spare_stock_number:eq('+rowIndex+')')) || 0;

      $('.spare_stock_vat_price:eq('+rowIndex+')').val(
          Math.round(
          (parseFloat(get_number('.spare_stock_price:eq('+rowIndex+')'))*percent/100)*number
          )
      );

      $('.spare_stock_vat_price:eq('+rowIndex+')').val(function(index, value) {
          return value
            .replace(/\D/g, "")
            .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
          ;
        });
      
  });
$('.spare_stock_price').keyup(function(){
      var row = $(this).parent().parent().parent().parent().parent().parent();
      var rowIndex = row[0].rowIndex;

      var percent = parseFloat(get_number('.spare_stock_vat_percent:eq('+rowIndex+')')) || 0;
      var price = parseFloat($(this).val().replace(/\,/g,''));
      var number = parseFloat(get_number('.spare_stock_number:eq('+rowIndex+')')) || 0;

      $('.spare_stock_vat_price:eq('+rowIndex+')').val(
          Math.round(
          (price*percent/100)*number
          )
      );

      $('.spare_stock_vat_price:eq('+rowIndex+')').val(function(index, value) {
          return value
            .replace(/\D/g, "")
            .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
          ;
        });
      
  });

  
  $('.spare_stock_number').keyup(function(){
      var row = $(this).parent().parent().parent().parent().parent().parent();
      var rowIndex = row[0].rowIndex;

      var number = parseFloat($(this).val());
      if (number == 0 || number == "") {
        $(this).val("1");
      }
      var percent = parseFloat(get_number('.spare_stock_vat_percent:eq('+rowIndex+')')) || 0;

      $('.spare_stock_vat_price:eq('+rowIndex+')').val(
          Math.round(
          (parseFloat(get_number('.spare_stock_price:eq('+rowIndex+')'))*percent/100)*number
          )
      );

      $('.spare_stock_vat_price:eq('+rowIndex+')').val(function(index, value) {
          return value
            .replace(/\D/g, "")
            .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
          ;
        });

      if ($('.check_seri:eq('+rowIndex+')').is(':checked')) {
        var ns = parseInt($('.dem:last').attr("data"));
        $('.tr_seri:eq('+rowIndex+')').show();
        var table=document.getElementById('dataTb'+rowIndex);
        var rowCount=table.rows.length;
        var val_add = parseInt($(this).val());
        if (rowCount < val_add) {
          var num_row = val_add-rowCount;
          for (var i = 0; i < num_row; i++) {
            var row=table.insertRow(rowCount);
            var colCount=table.rows[0].cells.length;
            for(var j=0;j<colCount;j++){
                var newcell=row.insertCell(j);
                newcell.innerHTML=table.rows[0].cells[j].innerHTML;
                switch(newcell.childNodes[0].type){
                    case"text":newcell.childNodes[0].value="";
                    break;
                    case"checkbox":newcell.childNodes[0].checked=false;
                    break;
                    case"select-one":newcell.childNodes[0].selectedIndex=0;
                    break;
                }
            }

            $('.spare_part_seri2:last').val("");
            $('.spare_part_seri2:last').attr('code',"");
            
            $('input[name="chk3"]:last').attr('data',"");
            $('input[name="chk3"]:last').attr('tabindex',0);
            $('input[name="chk3"]:last').attr('title',"");
            $('input[name="chk3"]:last').attr('class',"");
            $('input[name="chk3"]:last').attr('alt',0);

            ns++;
            
            $('.dem:last').attr("data",ns);
            $('.dem:last').html("("+ns+")");

            rowCount++;
          }
        }
        else if(rowCount > val_add){
         
          for(var i=rowCount;i>val_add;i--){
                if(rowCount>1){
                  table.deleteRow(rowCount-1);
                  rowCount--;
                }
                
            }
        }
        
      }
      
  });

$('.check_seri').click(function(){
  var row = $(this).parent().parent().parent().parent().parent().parent();
  var rowIndex = row[0].rowIndex;

    if($(this).is(':checked')){
      var ns = parseInt($('.dem:last').attr("data"));
      $('.tr_seri:eq('+rowIndex+')').show();
        var table=document.getElementById('dataTb'+rowIndex);
        var rowCount=table.rows.length;
        var val_add = parseInt($('.spare_stock_number:eq('+rowIndex+')').val());
        if (rowCount < val_add) {
          var num_row = val_add-rowCount;
          for (var j = 0; j < num_row; j++) {
            var row=table.insertRow(rowCount);
            var colCount=table.rows[0].cells.length;
            for(var i=0;i<colCount;i++){
                var newcell=row.insertCell(i);
                newcell.innerHTML=table.rows[0].cells[i].innerHTML;
                switch(newcell.childNodes[0].type){
                    case"text":newcell.childNodes[0].value="";
                    break;
                    case"checkbox":newcell.childNodes[0].checked=false;
                    break;
                    case"select-one":newcell.childNodes[0].selectedIndex=0;
                    break;
                }
            }

            $('.spare_part_seri2:last').val("");
            $('.spare_part_seri2:last').attr('code',"");
            
            $('input[name="chk3"]:last').attr('data',"");
            $('input[name="chk3"]:last').attr('tabindex',0);
            $('input[name="chk3"]:last').attr('title',"");
            $('input[name="chk3"]:last').attr('class',"");
            $('input[name="chk3"]:last').attr('alt',0);

            ns++;
            
            $('.dem:last').attr("data",ns);
            $('.dem:last').html("("+ns+")");

            rowCount++;
          }
        }
    }
    else{
      $('.tr_seri:eq('+rowIndex+')').hide();
    }
  });

$('.receiver').keyup(function(){
        var row = $(this).parent().parent().parent().parent().parent().parent();
        var rowIndex = row[0].rowIndex;

        var keyword = $(this).val();
        $.ajax({
            url: '<?php echo BASE_URL ?>/shipment/getreceiver',
            type: 'POST',
            data: {keyword:keyword, offset:rowIndex},
            success:function(data){
                $('.name_list_id_3:eq('+rowIndex+')').slideDown(200);
                $('.name_list_id_3:eq('+rowIndex+')').html(data);
            }
        });
        if ($('.receiver:eq('+rowIndex+')').val() == "" || $('.receiver:eq('+rowIndex+')').attr('data') == "") {
            
            $('.receiver:eq('+rowIndex+')').attr('data',"");
        }

        
    });

    $('.receiver').on('keydown', function() {
        var row = $(this).parent().parent().parent().parent().parent().parent();
        var rowIndex = row[0].rowIndex;

        var key = event.keyCode || event.charCode;

        if( key == 8 || key == 46 ){
            $('.receiver:eq('+rowIndex+')').attr('data',"");
        }
            
      });

    

   
    $('.number').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-.]/g, "")
        ;
      });
    });
   
   $('.numbers').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9]/g, "")
          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
        ;
      });
    });
    

});
function get_number(id){
    return $(id).val().replace(/\,/g,'');
}
function set_item_other(item,value,code,date,brand,vitri,unit,price) {
      // change input value
      $('.spare_part:eq('+vitri+')').val(value);
      $('.spare_part:eq('+vitri+')').attr("data",item);
      $('.spare_part_code:eq('+vitri+')').val(code);
      $('.spare_part_date_manufacture:eq('+vitri+')').val(date);
      $('.spare_part_brand:eq('+vitri+')').val(brand);
      $('.spare_stock_unit:eq('+vitri+')').val(unit);
      $('.spare_stock_price:eq('+vitri+')').val(price);

      var percent = parseFloat(get_number('.spare_stock_vat_percent:eq('+vitri+')')) || 0;
      var number = parseFloat($('.spare_stock_number:eq('+vitri+')').val()) || 0;
      $('.spare_stock_vat_price:eq('+vitri+')').val(
            Math.round(
            (parseFloat(get_number('.spare_stock_price:eq('+vitri+')'))*percent/100)*number
            )
        );
      
      // hide proposition list
      $('.name_list_id').hide();
      $('.name_list_id_2').hide();
      $('.spare_part:eq('+vitri+')').focus();

      $(".numbers").val(function(index, value) {
      return value
        .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
      ;
    });

  }
  function set_item_customer(value,name) {
    // change input value
    $('#invoice_customer').val(name);
    $("#invoice_customer").attr("data",value);
    $("#invoice_customer").attr("code",'true');
    
    // hide proposition list
    $('#customer_list_id').hide();
    $('#invoice_customer').focus();
     
}
function set_item_receiver(value,name,vitri) {
        // change input value
        $('.receiver:eq('+vitri+')').val(name);
        $('.receiver:eq('+vitri+')').attr("data",value);
        
        // hide proposition list
        $('.name_list_id_3').hide();
        $('.receiver:eq('+vitri+')').focus();
         
         
    }
</script>
<div style="display:none" id="lasted"></div>
<script type="text/javascript">
    var count = parseInt(<?php echo $lastID ?>);
    $('#lasted').html(count);

$("#import_excel").click(function(){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:300,
            width:400,
            resizable: false,
            title:'Import Excel',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        return false;
    });
</script>
</div>

<script type="text/javascript">
var l = "<?php echo $limit ?>";
$('#chonloc option[value='+l+']').attr('selected','selected');

$( ".add-field" ).dialog({
    autoOpen: false,
    modal: true,
    width: "auto",
    title: "Nhập kho",
    hide: 'fold',
    show: 'blind'
});


var pickerOpay2 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+0",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true
    }; 
    $(".ngay").datepicker(pickerOpay2);


function addRow(tableID){
  var checked = 0;
  if ($('.check_seri:first').is(':checked')) {
    checked = 1;
  }

    var table=document.getElementById(tableID);
    var rowCount=table.rows.length;
    var row=table.insertRow(rowCount);
    var colCount=table.rows[0].cells.length;
    for(var i=0;i<colCount;i++){
        var newcell=row.insertCell(i);
        newcell.innerHTML=table.rows[0].cells[i].innerHTML;
        switch(newcell.childNodes[0].type){
            case"text":newcell.childNodes[0].value="";
            break;
            case"checkbox":newcell.childNodes[0].checked=false;
            break;
            case"select-one":newcell.childNodes[0].selectedIndex=0;
            break;
        }
    }

    $('.spare_part:last').attr('disabled',false);
    $('.spare_part_code:last').attr('disabled',false);
    $('.spare_part:last').attr('data',"");
    $('.spare_part:last').val("");
    $('.spare_part_code:last').val("");
    $('.spare_stock_unit:last').val("");
    $('.spare_stock_price:last').val("");
    $('.spare_part_brand:last').val("");
    $('.spare_part_date_manufacture:last').val("");
    $('.spare_part_date_manufacture:last').removeClass("hasDatepicker");
    $('.spare_part_date_manufacture:last').attr("id","");
    
    $('.spare_stock_vat_percent:last').val("");
    $('.spare_stock_vat_price:last').val("");
    
    $('input[name="chk"]:last').attr('data',"");
    $('input[name="chk"]:last').attr('tabindex',0);
    $('input[name="chk"]:last').attr('title',"");
    $('input[name="chk"]:last').attr('class',"");
    $('input[name="chk"]:last').attr('alt',0);

    $('.tr_seri:last input').attr('code',"");
    $('.tr_seri:last input').attr('data',"");
    $('.tr_seri:last input').attr('alt',"");
    $('.tr_seri:last').find(":input:not([type=button])").val("");

    $('.spare_stock_number:last').val($('.spare_stock_number:first').val());

    if (checked == 1) {
      $('.check_seri:last').attr('checked','checked');
    }

    $('.dataTb:last').attr('id',"dataTb"+parseInt(rowCount));
    $('.addRow3:last').attr('onClick','addRow3("dataTb'+(parseInt(rowCount))+'")');
    $('.deleteRow3:last').attr('onClick','deleteRow3("dataTb'+(parseInt(rowCount))+'")');
    
    $('#dataTb'+parseInt(rowCount)).find('input[type="text"]').each(function () {
       $(this).attr('data',rowCount);
    });

    $('.spare_part').keyup(function(){
        var row = $(this).parent().parent().parent().parent().parent().parent();
        var rowIndex = row[0].rowIndex;

        var keyword = $(this).val();
        $.ajax({
            url: '<?php echo BASE_URL ?>/importstock/getSpare',
            type: 'POST',
            data: {keyword:keyword, offset:rowIndex},
            success:function(data){
                $('.name_list_id:eq('+rowIndex+')').slideDown(200);
                $('.name_list_id:eq('+rowIndex+')').html(data);
            }
        });
        if ($('.spare_part:eq('+rowIndex+')').val() == "" || $('.spare_part:eq('+rowIndex+')').attr('data') == "") {
            
            $('.spare_part:eq('+rowIndex+')').attr('data',"");
        }

        
    });

$('.spare_part').on('keydown', function() {
        var row = $(this).parent().parent().parent().parent().parent().parent();
        var rowIndex = row[0].rowIndex;

        var key = event.keyCode || event.charCode;

        if( key == 8 || key == 46 ){
            $('.spare_part:eq('+rowIndex+')').attr('data',"");
        }
            
      }); 

$('.spare_part_code').keyup(function(){
        var row = $(this).parent().parent().parent().parent().parent().parent();
        var rowIndex = row[0].rowIndex;

        var keyword = $(this).val();
        $.ajax({
            url: '<?php echo BASE_URL ?>/importstock/getSpare',
            type: 'POST',
            data: {keyword:keyword, offset:rowIndex},
            success:function(data){
                $('.name_list_id_2:eq('+rowIndex+')').slideDown(200);
                $('.name_list_id_2:eq('+rowIndex+')').html(data);
            }
        });
        if ($('.spare_part:eq('+rowIndex+')').val() == "" || $('.spare_part:eq('+rowIndex+')').attr('data') == "") {
            
            $('.spare_part:eq('+rowIndex+')').attr('data',"");
        }

        
    });



$('.spare_part_code').blur(function(){
    var row = $(this).parent().parent().parent().parent().parent().parent();
    var rowIndex = row[0].rowIndex;

    var check_type = 0;

    var val = $(this).val().trim();
    
    $('.spare_part_code').each(function() { 
        if ( val != "" && val == $(this).val().trim()) {
            check_type ++;
        }
    });

    

    if (check_type >= 2) {
        alert('Sản phẩm này đã có!');
        $(this).val("");
        $('.spare_part:eq('+rowIndex+')').attr('data',"");
        $('.spare_part:eq('+rowIndex+')').val("");
        $('.spare_part_brand:eq('+rowIndex+')').val("");
        $('.spare_part_seri:eq('+rowIndex+')').val("");
        $('.spare_part_date_manufacture:eq('+rowIndex+')').val("");
        
    };
    
});
$('.spare_part').blur(function(){
    var row = $(this).parent().parent().parent().parent().parent().parent();
    var rowIndex = row[0].rowIndex;

    var check_type = 0;

    var val = $(this).val().trim();
    
    $('.spare_part').each(function() { 
        if (val != "" && val == $(this).val().trim()) {
            check_type ++;
        }
    });

    

    if (check_type >= 2) {
        alert('Sản phẩm này đã có!');
        $(this).val("");
        $('.spare_part:eq('+rowIndex+')').attr('data',"");
        $('.spare_part_code:eq('+rowIndex+')').val("");
        $('.spare_part_brand:eq('+rowIndex+')').val("");
        $('.spare_part_seri:eq('+rowIndex+')').val("");
        $('.spare_part_date_manufacture:eq('+rowIndex+')').val("");
        
    };
    
});
$('.spare_part_seri2').blur(function(){
    var row = $(this).parent().parent().parent().parent().parent().parent().parent().parent().parent().parent().parent().parent().parent().parent();
    var rowIndex = row[0].rowIndex;

    var check_type = 0;

    var val = $(this).val().trim();
    
    $('.tr_seri:eq('+rowIndex+') input[type=text]').each(function() { 
        if (val != "" && val == $(this).val().trim()) {
            check_type ++;
        }
    });

    

    if (check_type >= 2) {
        alert('Sản phẩm này đã có!');
        $(this).val("");
        
    };
    
});

$('.spare_stock_vat_percent').keyup(function(){
      var row = $(this).parent().parent().parent().parent().parent().parent();
      var rowIndex = row[0].rowIndex;

      var percent = parseFloat($(this).val());
      var number = parseFloat(get_number('.spare_stock_number:eq('+rowIndex+')')) || 0;

      $('.spare_stock_vat_price:eq('+rowIndex+')').val(
          Math.round(
          (parseFloat(get_number('.spare_stock_price:eq('+rowIndex+')'))*percent/100)*number
          )
      );

      $('.spare_stock_vat_price:eq('+rowIndex+')').val(function(index, value) {
          return value
            .replace(/\D/g, "")
            .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
          ;
        });
      
  });
$('.spare_stock_price').keyup(function(){
      var row = $(this).parent().parent().parent().parent().parent().parent();
      var rowIndex = row[0].rowIndex;

      var percent = parseFloat(get_number('.spare_stock_vat_percent:eq('+rowIndex+')')) || 0;
      var price = parseFloat($(this).val().replace(/\,/g,''));
      var number = parseFloat(get_number('.spare_stock_number:eq('+rowIndex+')')) || 0;

      $('.spare_stock_vat_price:eq('+rowIndex+')').val(
          Math.round(
          (price*percent/100)*number
          )
      );

      $('.spare_stock_vat_price:eq('+rowIndex+')').val(function(index, value) {
          return value
            .replace(/\D/g, "")
            .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
          ;
        });
      
  });
  $('.spare_stock_number').keyup(function(){
      var row = $(this).parent().parent().parent().parent().parent().parent();
      var rowIndex = row[0].rowIndex;

      var number = parseFloat($(this).val());
      if (number == 0 || number == "") {
        $(this).val("1");
      }
      var percent = parseFloat(get_number('.spare_stock_vat_percent:eq('+rowIndex+')')) || 0;

      $('.spare_stock_vat_price:eq('+rowIndex+')').val(
          Math.round(
          (parseFloat(get_number('.spare_stock_price:eq('+rowIndex+')'))*percent/100)*number
          )
      );

      $('.spare_stock_vat_price:eq('+rowIndex+')').val(function(index, value) {
          return value
            .replace(/\D/g, "")
            .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
          ;
        });

      if ($('.check_seri:eq('+rowIndex+')').is(':checked')) {
        var ns = parseInt($('.dem:last').attr("data"));
        $('.tr_seri:eq('+rowIndex+')').show();
        var table=document.getElementById('dataTb'+rowIndex);
        var rowCount=table.rows.length;
        var val_add = parseInt($(this).val());
        if (rowCount < val_add) {
          var num_row = val_add-rowCount;
          for (var i = 0; i < num_row; i++) {
            var row=table.insertRow(rowCount);
            var colCount=table.rows[0].cells.length;
            for(var j=0;j<colCount;j++){
                var newcell=row.insertCell(j);
                newcell.innerHTML=table.rows[0].cells[j].innerHTML;
                switch(newcell.childNodes[0].type){
                    case"text":newcell.childNodes[0].value="";
                    break;
                    case"checkbox":newcell.childNodes[0].checked=false;
                    break;
                    case"select-one":newcell.childNodes[0].selectedIndex=0;
                    break;
                }
            }

            $('.spare_part_seri2:last').val("");
            $('.spare_part_seri2:last').val('code',"");
            
            $('input[name="chk3"]:last').attr('data',"");
            $('input[name="chk3"]:last').attr('tabindex',0);
            $('input[name="chk3"]:last').attr('title',"");
            $('input[name="chk3"]:last').attr('class',"");
            $('input[name="chk3"]:last').attr('alt',0);

            ns++;
            
            $('.dem:last').attr("data",ns);
            $('.dem:last').html("("+ns+")");

            rowCount++;
          }
        }
        else if(rowCount > val_add){
         
          for(var i=rowCount;i>val_add;i--){
                if(rowCount>1){
                  table.deleteRow(rowCount-1);
                  rowCount--;
                }
                
            }
        }
        
      }
      
  });

$('.check_seri').click(function(){
  var row = $(this).parent().parent().parent().parent().parent().parent();
  var rowIndex = row[0].rowIndex;

    if($(this).is(':checked')){
      var ns = parseInt($('.dem:last').attr("data"));
      $('.tr_seri:eq('+rowIndex+')').show();
        var table=document.getElementById('dataTb'+rowIndex);
        var rowCount=table.rows.length;
        var val_add = parseInt($('.spare_stock_number:eq('+rowIndex+')').val());
        if (rowCount < val_add) {
          var num_row = val_add-rowCount;
          for (var j = 0; j < num_row; j++) {
            var row=table.insertRow(rowCount);
            var colCount=table.rows[0].cells.length;
            for(var i=0;i<colCount;i++){
                var newcell=row.insertCell(i);
                newcell.innerHTML=table.rows[0].cells[i].innerHTML;
                switch(newcell.childNodes[0].type){
                    case"text":newcell.childNodes[0].value="";
                    break;
                    case"checkbox":newcell.childNodes[0].checked=false;
                    break;
                    case"select-one":newcell.childNodes[0].selectedIndex=0;
                    break;
                }
            }

            $('.spare_part_seri2:last').val("");
            $('.spare_part_seri2:last').attr('code',"");
            
            $('input[name="chk3"]:last').attr('data',"");
            $('input[name="chk3"]:last').attr('tabindex',0);
            $('input[name="chk3"]:last').attr('title',"");
            $('input[name="chk3"]:last').attr('class',"");
            $('input[name="chk3"]:last').attr('alt',0);

            ns++;
            
            $('.dem:last').attr("data",ns);
            $('.dem:last').html("("+ns+")");

            rowCount++;
          }
        }
    }
    else{
      $('.tr_seri:eq('+rowIndex+')').hide();
    }
  });

   
    $('.number').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-.]/g, "")
        ;
      });
    });
   
   $('.numbers').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9]/g, "")
          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
        ;
      });
    });

   function get_number(id){
    return $(id).val().replace(/\,/g,'');
  }
  function set_item_other(item,value,code,date,brand,vitri,unit,price) {
      // change input value
      $('.spare_part:eq('+vitri+')').val(value);
      $('.spare_part:eq('+vitri+')').attr("data",item);
      $('.spare_part_code:eq('+vitri+')').val(code);
      $('.spare_part_date_manufacture:eq('+vitri+')').val(date);
      $('.spare_part_brand:eq('+vitri+')').val(brand);
      $('.spare_stock_unit:eq('+vitri+')').val(unit);
      $('.spare_stock_price:eq('+vitri+')').val(price);

      var percent = parseFloat(get_number('.spare_stock_vat_percent:eq('+vitri+')')) || 0;
      var number = parseFloat($('.spare_stock_number:eq('+vitri+')').val()) || 0;
      $('.spare_stock_vat_price:eq('+vitri+')').val(
            Math.round(
            (parseFloat(get_number('.spare_stock_price:eq('+vitri+')'))*percent/100)*number
            )
        );
      
      // hide proposition list
      $('.name_list_id').hide();
      $('.name_list_id_2').hide();
      $('.spare_part:eq('+vitri+')').focus();

      $(".numbers").val(function(index, value) {
      return value
        .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
      ;
    });

  }

    $(".ngay").datepicker(
      {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+0",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true
    }
      );

}
function deleteRow(tableID){
    try{
        var table=document.getElementById(tableID);
        var rowCount=table.rows.length;

        var r = confirm("Bạn có chắc chắn không?");
        if (r == true){
            for(var i=0;i<rowCount;i++){
                var row=table.rows[i];
                var chkbox=row.cells[0].childNodes[0];
                if(null!=chkbox&&true==chkbox.checked){
                  if(rowCount<=1){
                        alert("Cannot delete all the rows.");
                        break;
                    }
                    else if(chkbox.getAttribute("data") > 0){
                        
                            var import_stock = chkbox.getAttribute("data");
                            var spare_part_code = chkbox.getAttribute("alt");
                            $.post("<?php echo BASE_URL ?>/importstock/deletesparecode", {import_stock: import_stock, spare_part_code: spare_part_code},
                               function(data){
                                //alert(data);
                               }); 
                        
                    }
                    
                    table.deleteRow(i);
                    rowCount--;
                    i--;
                }
            }
        }
    }
    catch(e){
        alert(e);
    }
}

function addRow2(tableID){
    var table=document.getElementById(tableID);
    var rowCount=table.rows.length;
    var row=table.insertRow(rowCount);
    var colCount=table.rows[0].cells.length;
    for(var i=0;i<colCount;i++){
        var newcell=row.insertCell(i);
        newcell.innerHTML=table.rows[0].cells[i].innerHTML;
        switch(newcell.childNodes[0].type){
            case"text":newcell.childNodes[0].value="";
            break;
            case"checkbox":newcell.childNodes[0].checked=false;
            break;
            case"select-one":newcell.childNodes[0].selectedIndex=0;
            break;
        }
    }

    $('.cost_list:last').attr('disabled',false);
    $('.receiver:last').attr('disabled',false);
    $('.receiver:last').attr('data',"");
    $('.receiver:last').val("");
    $('.cost:last').val("");
    $('.comment:last').val("");
    $('.cost_document:last').val("");
    $('.cost_document_date:last').val("");
    $('.cost_document_date:last').removeClass("hasDatepicker");
    $('.cost_document_date:last').attr("id","");
    $('.check_vat:last').attr('checked',false);
    
    $('input[name="chk2"]:last').attr('data',"");
    $('input[name="chk2"]:last').attr('tabindex',0);
    $('input[name="chk2"]:last').attr('title',"");
    $('input[name="chk2"]:last').attr('class',"");
    $('input[name="chk2"]:last').attr('alt',0);

    $('.receiver').keyup(function(){
        var row = $(this).parent().parent().parent().parent().parent().parent();
        var rowIndex = row[0].rowIndex;

        var keyword = $(this).val();
        $.ajax({
            url: '<?php echo BASE_URL ?>/shipment/getreceiver',
            type: 'POST',
            data: {keyword:keyword, offset:rowIndex},
            success:function(data){
                $('.name_list_id_3:eq('+rowIndex+')').slideDown(200);
                $('.name_list_id_3:eq('+rowIndex+')').html(data);
            }
        });
        if ($('.receiver:eq('+rowIndex+')').val() == "" || $('.receiver:eq('+rowIndex+')').attr('data') == "") {
            
            $('.receiver:eq('+rowIndex+')').attr('data',"");
        }

        
    });

    $('.receiver').on('keydown', function() {
        var row = $(this).parent().parent().parent().parent().parent().parent();
        var rowIndex = row[0].rowIndex;

        var key = event.keyCode || event.charCode;

        if( key == 8 || key == 46 ){
            $('.receiver:eq('+rowIndex+')').attr('data',"");
        }
            
      });

    function set_item_receiver(value,name,vitri) {
        // change input value
        $('.receiver:eq('+vitri+')').val(name);
        $('.receiver:eq('+vitri+')').attr("data",value);
        
        // hide proposition list
        $('.name_list_id_3').hide();
        $('.receiver:eq('+vitri+')').focus();
         
         
    }

    function get_number(id){
        return $(id).val().replace(/[^0-9\.-]+/g,"");
    }

    $('.number').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-.]/g, "")
        ;
      });
    });
   
   $('.numbers').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9]/g, "")
          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
        ;
      });
    });

   $(".ngay").datepicker(
      {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+0",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true
    }
      );

}
function deleteRow2(tableID){
    try{
        var table=document.getElementById(tableID);
        var rowCount=table.rows.length;

        var r = confirm("Bạn có chắc chắn không?");
        if (r == true){
            for(var i=0;i<rowCount;i++){
                var row=table.rows[i];
                var chkbox=row.cells[0].childNodes[0];
                if(null!=chkbox&&true==chkbox.checked){
                  if(rowCount<=1){
                        alert("Cannot delete all the rows.");
                        break;
                    }
                    else if(chkbox.getAttribute("data") > 0){
                        
                            var import_stock_cost_id = chkbox.getAttribute("data");
                            $.post("<?php echo BASE_URL ?>/importstock/deletecost", {import_stock_cost_id: import_stock_cost_id},
                               function(data){
                                //alert(data);
                               }); 
                        
                    }
                    
                    table.deleteRow(i);
                    rowCount--;
                    i--;
                }
            }
        }
    }
    catch(e){
        alert(e);
    }
}

function addRow3(tableID){
  var ns = parseInt($('.dem:last').attr("data"));
    var table=document.getElementById(tableID);
    var rowCount=table.rows.length;
    var row=table.insertRow(rowCount);
    var colCount=table.rows[0].cells.length;
    for(var i=0;i<colCount;i++){
        var newcell=row.insertCell(i);
        newcell.innerHTML=table.rows[0].cells[i].innerHTML;
        switch(newcell.childNodes[0].type){
            case"text":newcell.childNodes[0].value="";
            break;
            case"checkbox":newcell.childNodes[0].checked=false;
            break;
            case"select-one":newcell.childNodes[0].selectedIndex=0;
            break;
        }
    }

    $('.spare_part_seri2:last').val("");
    $('.spare_part_seri2:last').attr('code',"");
    
    $('input[name="chk3"]:last').attr('data',"");
    $('input[name="chk3"]:last').attr('tabindex',0);
    $('input[name="chk3"]:last').attr('title',"");
    $('input[name="chk3"]:last').attr('class',"");
    $('input[name="chk3"]:last').attr('alt',0);

    ns++;
            
    $('.dem:last').attr("data",ns);
    $('.dem:last').html("("+ns+")");

    var rowIndex = parseInt(tableID.replace('dataTb',''));

    $('.spare_stock_number:eq('+rowIndex+')').val(rowCount+1);

    var number = parseFloat(rowCount+1);

    var percent = parseFloat(get_number('.spare_stock_vat_percent:eq('+rowIndex+')')) || 0;

    $('.spare_stock_vat_price:eq('+rowIndex+')').val(
        Math.round(
        (parseFloat(get_number('.spare_stock_price:eq('+rowIndex+')'))*percent/100)*number
        )
    );

    $('.spare_stock_vat_price:eq('+rowIndex+')').val(function(index, value) {
        return value
          .replace(/\D/g, "")
          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
        ;
      });

    $('.spare_part_seri2').blur(function(){
      var row = $(this).parent().parent().parent().parent().parent().parent().parent().parent().parent().parent().parent().parent().parent().parent();
      var rowIndex = row[0].rowIndex;

      var check_type = 0;

      var val = $(this).val().trim();
      
      $('.tr_seri:eq('+rowIndex+') input[type=text]').each(function() { 
          if (val != "" && val == $(this).val().trim()) {
              check_type ++;
          }
      });

      

      if (check_type >= 2) {
          alert('Sản phẩm này đã có!');
          $(this).val("");
          
      };
      
  });
   
    $('.number').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-.]/g, "")
        ;
      });
    });
   
   $('.numbers').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9]/g, "")
          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
        ;
      });
    });


}
function deleteRow3(tableID){
    try{
        var table=document.getElementById(tableID);
        var rowCount=table.rows.length;

        var r = confirm("Bạn có chắc chắn không?");
        if (r == true){
            for(var i=0;i<rowCount;i++){
                var row=table.rows[i];
                var chkbox=row.cells[0].childNodes[0];
                if(null!=chkbox&&true==chkbox.checked){
                    if(rowCount<=1){
                        alert("Cannot delete all the rows.");
                        break;
                    }
                    else if(chkbox.getAttribute("data") > 0){
                        
                            var import_stock = chkbox.getAttribute("data");
                            var spare_part = chkbox.getAttribute("alt");
                            $.post("<?php echo BASE_URL ?>/importstock/deletespare", {import_stock: import_stock, spare_part: spare_part},
                               function(data){
                                //alert(data);
                               }); 
                        
                    }
                    
                    table.deleteRow(i);
                    rowCount--;
                    i--;

                    var rowIndex = parseInt(tableID.replace('dataTb',''));

                    $('.spare_stock_number:eq('+rowIndex+')').val(rowCount);

                    var number = parseFloat(rowCount);

                    var percent = parseFloat(get_number('.spare_stock_vat_percent:eq('+rowIndex+')')) || 0;

                    $('.spare_stock_vat_price:eq('+rowIndex+')').val(
                        Math.round(
                        (parseFloat(get_number('.spare_stock_price:eq('+rowIndex+')'))*percent/100)*number
                        )
                    );

                    $('.spare_stock_vat_price:eq('+rowIndex+')').val(function(index, value) {
                        return value
                          .replace(/\D/g, "")
                          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
                        ;
                      });
                }
            }
        }
    }
    catch(e){
        alert(e);
    }
}
</script>

<style type="text/css">
    #ui-datepicker-div{
        font-size: 13px;
    }
</style>
<script type="text/javascript">
    $(function() {
    var pickerOpts = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#ketthuc" ).datepicker( "option", "minDate", selectedDate );

         },
         
    };  
    $("#batdau").datepicker(pickerOpts);

    var pickerOpts4 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#batdau" ).datepicker( "option", "maxDate", selectedDate );
                
         },
         
    };  
    $("#ketthuc").datepicker(pickerOpts4);
              
            
    
});

var ch = "<?php echo $limit ?>";
$('#chonloc option[value='+ch+']').attr('selected','selected');

var v = "<?php echo $vong ?>";
$('#sl_round option[value='+v+']').attr('selected','selected');

var tt = "<?php echo $trangthai ?>";
$('#sl_staff option[value='+tt+']').attr('selected','selected');

</script>
<script type="text/javascript">
    
    $('#sl_round').change(function(){
        var m = $(this).val();
        var y = $('#sl_staff').val();
        var firstDay = new Date(y, m-1, 1);
        var lastDay = new Date(y, m, 0);

        $('#batdau').datepicker("setDate", firstDay );
        $('#ketthuc').datepicker("setDate", lastDay );

    });

    $('#sl_staff').change(function(){
        var y = $(this).val();
        var m = $('#sl_round').val();
        var firstDay = new Date(y, m-1, 1);
        var lastDay = new Date(y, m, 0);

        $('#batdau').datepicker("setDate", firstDay );
        $('#ketthuc').datepicker("setDate", lastDay );

    });

jQuery(document).ready(function() {
    jQuery('.tabs .tab-links a').on('click', function(e)  {
        var currentAttrValue = jQuery(this).attr('href');

        var id = currentAttrValue.replace('#tab','');
        $('#sl_tha').val(id);
        // Show/Hide Tabs
        jQuery('.tabs ' + currentAttrValue).slideDown(300).siblings().slideUp(300);
 
        // Change/remove current tab to active
        jQuery(this).parent('li').addClass('active').siblings().removeClass('active');
 
        e.preventDefault();
    });

    jQuery('.tabs .tab-left a').on('click', function(e)  {
        var currentAttrValue = jQuery(this).attr('href');
 
        // Show/Hide Tabs
        jQuery('.tabs ' + currentAttrValue).slideDown(300).siblings().slideUp(300);
 
        // Change/remove current tab to active
        jQuery(this).parent('li').addClass('active').siblings().removeClass('active');
 
        e.preventDefault();
    });
});
</script>