
<div id="winpopup"></div>
<section class="content-header">
    <h1>THÔNG TIN DOANH NGHIỆP</h1>
  <ol class="breadcrumb">
    <li><a href="<?php echo $this->url('admin') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><a href="<?php echo $this->url('info') ?>">Thông tin</a></li>
  </ol>
</section>
<!-- Main content -->
<?php 
if(count($infos)>0){
  foreach ($infos as $info) { ?>
    <section class="content">
      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Thông tin</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form id="addinfo" role="form" method="post" action="" enctype="multipart/form-data">
              <div class="row">
                <div class="col-md-4 col-xs-6">
                  <div class="box-body">
                    <div class="form-group">
                      <label for="info_name">Tên công ty</label>
                      <input type="text" id="info_company" placeholder="Tên công ty" required="required" tabindex="1" value="<?php echo $info->info_company ?>">
                    </div>
                    <div class="form-group">
                      <label for="info_address">Địa chỉ</label>
                      <input type="text" id="info_address" placeholder="Địa chỉ" required="required" tabindex="2" value="<?php echo $info->info_address ?>">
                    </div>
                    
                    <div class="form-group">
                      <label for="info_from">Mã số thuế</label>
                      <input type="text" id="info_mst" class="number" placeholder="Mã số thuế" required="required" tabindex="3" value="<?php echo $info->info_mst ?>">
                    </div>
                    
                    
                  </div>
                  <!-- /.box-body -->
                  
                  
                </div>
                <div class="col-md-4 col-xs-6">
                  <div class="box-body">
                    <div class="form-group">
                      <label for="info_phone">Điện thoại</label>
                      <input type="text" id="info_phone" class="numbers" placeholder="Điện thoại" tabindex="4" value="<?php echo $info->info_phone ?>">
                    </div>
                    <div class="form-group">
                      <label for="info_email">Email</label>
                      <input type="email" id="info_email" placeholder="Email" tabindex="5" value="<?php echo $info->info_email ?>">
                    </div>
                    
                  </div>
                  <!-- /.box-body -->
                  
                  
                </div>

            

              </div>
            <?php if(!isset($disable_control)){ ?>
            <div class="row">
              <div class="box-footer">
                <input type="hidden" id="yes" value="<?php echo $info->info_id ?>" >
                <button type="submit" class="btn btn-primary" tabindex="6">Hoàn thành</button>
                <button type="reset" class="btn" tabindex="7">Nhập lại</button>
              </div>
              <div class="box-footer">
                <div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>
              </div>
            </div>
            <?php } ?>
            </form>
          </div>
          <!-- /.box -->

        </div>
        <!--/.col (left) -->
        
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
<?php } }else{?>
    <section class="content">
      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Thông tin</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form id="addinfo" role="form" method="post" action="" enctype="multipart/form-data">
              <div class="row">
                <div class="col-md-4 col-xs-6">
                  <div class="box-body">
                    <div class="form-group">
                      <label for="info_name">Tên công ty</label>
                      <input type="text" id="info_company" placeholder="Tên công ty" required="required" tabindex="1" >
                    </div>
                    <div class="form-group">
                      <label for="info_address">Địa chỉ</label>
                      <input type="text" id="info_address" placeholder="Địa chỉ" required="required" tabindex="2" >
                    </div>
                    
                    <div class="form-group">
                      <label for="info_from">Mã số thuế</label>
                      <input type="text" id="info_mst" class="number" placeholder="Mã số thuế" required="required" tabindex="3" >
                    </div>
                    
                    
                  </div>
                  <!-- /.box-body -->
                  
                  
                </div>
                <div class="col-md-4 col-xs-6">
                  <div class="box-body">
                    <div class="form-group">
                      <label for="info_phone">Điện thoại</label>
                      <input type="text" id="info_phone" class="numbers" placeholder="Điện thoại" tabindex="4" >
                    </div>
                    <div class="form-group">
                      <label for="info_email">Email</label>
                      <input type="email" id="info_email" placeholder="Email" tabindex="5" >
                    </div>
                    
                  </div>
                  <!-- /.box-body -->
                  
                  
                </div>

            

              </div>
            <?php if(!isset($disable_control)){ ?>
            <div class="row">
              <div class="box-footer">
                <input type="hidden" id="yes" value="" >
                <button type="submit" class="btn btn-primary" tabindex="6">Hoàn thành</button>
                <button type="reset" class="btn" tabindex="7">Nhập lại</button>
              </div>
              <div class="box-footer">
                <div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>
              </div>
            </div>
            <?php } ?>
            </form>
          </div>
          <!-- /.box -->

        </div>
        <!--/.col (left) -->
        
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
<?php } ?>
<script type="text/javascript">
  $(document).ready(function() {
      $('.numbers').keyup(function(event) {

            // skip for arrow keys
        if(event.which >= 37 && event.which <= 40) return;

        // format number
        $(this).val(function(index, value) {
          return value
            .replace(/[^0-9]/g, "")
            .replace(/(\d{3})(\d{3})(\d{4})/, "$1 $2 $3")
          ;
        });
      });
      $('.number').keyup(function(event) {

            // skip for arrow keys
        if(event.which >= 37 && event.which <= 40) return;

        // format number
        $(this).val(function(index, value) {
          return value
            .replace(/[^0-9]/g, "")
          ;
        });
      });

      

    $("#addinfo").validate({
        errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
        rules: {
            
        },
        submitHandler: function(form) {
            var info_company = $('#info_company').attr('value');
            var info_address = $('#info_address').attr('value');
            var info_mst = $('#info_mst').attr('value');
            var info_phone = $('#info_phone').attr('value');
            var info_email = $('#info_email').attr('value');
            

            
            var yes = $('#yes').attr('value');
         
            $.ajax({
                type: "POST", // phương thức gởi đi
                url: "<?php echo BASE_URL ?>/info/add", // nơi mà dữ liệu sẽ chuyển đến khi submit
                
                data: {
                    info_company: info_company,
                    info_address: info_address,
                    info_mst: info_mst,
                    info_phone: info_phone,
                    info_email: info_email,
                    yes: yes,
                }, // giá trị post
                success: function(answer){ // if everything goes well
                    //alert(answer);
                    var data = JSON.parse(answer);

                    $('#show').html(data.msg);
                    $('#winpopup').show();
                    $('#error').hide();
                    $('#error').slideToggle(100); // hiển thị thẻ div success
                    $('#error').html('<div class="successbox">'+data.msg+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                    $('#error').fadeOut(10000);

                    $('#yes').val(data.id);

                }
            });
            return false;
             
         }
    });
  });


</script>