
<?php


    $j = 1;

?>

<div id="loading"></div>
<div id="winpopup"></div>
<section class="content-header">
    <h1>TỔNG HỢP CHI HOA HỒNG</h1>
  <ol class="breadcrumb">
    <li><a href="<?php echo $this->url('admin') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><a href="<?php echo $this->url('commission') ?>">Hoa hồng</a></li>
  </ol>
</section>
<div id="content" style="padding:5px;">

    
<form id="report" name="report" action method="post">
<div class="search-box">
    <div class="add-box">
        <a class="add_button" id="ex" href="<?php echo BASE_URL.'/commission/export/'.strtotime($batdau).'/'.strtotime($ketthuc).'/'.$kh ?>" ><i class="fa fa-download"></i> Xuất</a>
    </div>

    
    
    <select id="sl_round" name="sl_round" style="width:90px; margin-left:5px;">
     <?php 
        for ($i=1; $i < 13; $i++) { 
            echo '<option value="'.$i.'">Tháng '.$i.'</option>';
        }
     ?>
    </select>
    <select id="sl_trangthai" name="sl_trangthai" style="width:100px">
     <?php 
        $nam = date('Y');
        for ($i=($nam-5); $i < ($nam+5); $i++) { 
            echo '<option value="'.$i.'">Năm '.$i.'</option>';
        }
     ?>
    </select>
    <input type="submit" name="submit" id="xem" value="Xem">  
    
</div>
<div >
    
    Từ  <input style="width:100px" type="search" name="batdau" id="batdau" placeholder="Chọn ngày" <?php if(isset($batdau)) echo "value='$batdau'"; ?> >  
    Đến  <input style="width:100px" type="search" name="ketthuc" id="ketthuc" placeholder="Chọn ngày" <?php if(isset($ketthuc)) echo "value='$ketthuc'"; ?> >  
     <input type="submit" name="submit" id="xem" value="Xem">  
                             
</div>
<div class="add-box">
        <select id="sl_vehicle" name="sl_vehicle" style="width:120px">
            <option value="0">Khách hàng</option>
         <?php 
            foreach ($customer_lists as $cu) { ?>
                <option value="<?php echo $cu->customer_id ?>"><?php echo $cu->customer_name ?></option>
         <?php   }
         ?>
        </select>
        <input type="submit" name="submit" id="chon" value="Chọn">  
    </div>
</form> 

<table class="table_data">
<thead>
    <tr>
    	
        <th class="fix">
            <a >STT </a>
        </th>
        <th  class="fix">
            <a >Ngày </a>
        </th>
        <th  class="fix">
            <a >Khách hàng </a>
        </th>
        <th  class="fix">
            <a >Tổng doanh thu </a>
        </th>
        <th  class="fix">
            <a >Sản lượng </a>
        </th>
        <th  class="fix">
            <a >Đơn giá </a>
        </th>
        <th  class="fix">
            <a >Tổng tiền  </a>
        </th>
        <th  class="fix">
            <a >Người nhận  </a>
        </th>
        <th  class="fix">
            <a >Người đề nghị </a>
        </th>
           
    </tr>
    
   </thead>
   <tbody>
    <?php $tongcong=0; $tongdt=0;   ?>
    <?php foreach ($commission_data as $com) : ?>
    <?php $kt = $com['end'] != "" ? ' - '.$lib->hien_thi_ngay_thang($com['end']) : null; ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');"  class="edit_tr">
            <td class="fix"><?php echo $j++; ?></td>
            <td class="fix" ><?php echo $lib->hien_thi_ngay_thang($com['date']).$kt; ?></td>
            <td class="fix" ><?php echo $com['customer']; ?></td>
            <td class="fix" ><?php echo $lib->formatMoney($com['revenue']); ?></td>
            <td class="fix" ><?php echo $com['commission_number']; ?></td>
            <td class="fix" ><?php echo $lib->formatMoney($com['commission']); ?></td>
            <td class="fix" ><?php echo $lib->formatMoney($com['commission_number']*$com['commission']); ?></td>
            <td class="fix" ></td>
            <td class="fix" ><?php echo $com['username']; ?></td>
            
            
        </tr>
    <?php
            $tongcong += $com['commission_number']*$com['commission'];
            $tongdt += $com['revenue'];
    ?>
    <?php endforeach; ?>
    
        <tr  style="font-weight: bold; color: rgb(23, 119, 226);" >
            
            <th colspan="3" style="border-right: 1px solid rgb(236, 235, 235);border-top: 1px solid #80C8E5;padding: 7px; text-align: right;" >
                Tổng cộng
            </th>
            <td class="fix " ><?php echo $lib->formatMoney($tongdt) ?></td>
            <td class="fix " ></td>
            <td class="fix " ></td>
            <td class="fix " ><?php echo $lib->formatMoney($tongcong) ?></td>
            <td class="fix " ></td>
            <td class="fix " ></td>
        </tr>

   </tbody>
</table>



</div>

<script type="text/javascript">
    $(function() {

        var w = $(".report").width();

      $(".report-right-fix").width(w-375);


    var pickerOpts = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#ketthuc" ).datepicker( "option", "minDate", selectedDate );

         },
         
    };  
    $("#batdau").datepicker(pickerOpts);

    var pickerOpts4 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#batdau" ).datepicker( "option", "maxDate", selectedDate );
                
         },
         
    };  
    $("#ketthuc").datepicker(pickerOpts4);
              
            
    
});


var v = "<?php echo $vong ?>";
$('#sl_round option[value='+v+']').attr('selected','selected');

var tt = "<?php echo $trangthai ?>";
$('#sl_trangthai option[value='+tt+']').attr('selected','selected');

var kh = "<?php echo $kh ?>";
$('#sl_vehicle option[value='+kh+']').attr('selected','selected');


</script>

<style type="text/css">
    #ui-datepicker-div{
        font-size: 13px;
    }

.showtooltip {
        display:none;
        position:absolute;
        border:1px solid #333;
        background-color:#161616;
        border-radius:5px;
        padding:10px;
        color:#fff;
        font-size:12px Arial;
    }
</style>



<script type="text/javascript">
    
    $('#sl_round').change(function(){
        var m = $(this).val();
        var y = $('#sl_trangthai').val();
        var firstDay = new Date(y, m-1, 1);
        var lastDay = new Date(y, m, 0);

        $('#batdau').datepicker("setDate", firstDay );
        $('#ketthuc').datepicker("setDate", lastDay );

    });

    $('#sl_trangthai').change(function(){
        var y = $(this).val();
        var m = $('#sl_round').val();
        var firstDay = new Date(y, m-1, 1);
        var lastDay = new Date(y, m, 0);

        $('#batdau').datepicker("setDate", firstDay );
        $('#ketthuc').datepicker("setDate", lastDay );

    });

</script>