<script type="text/javascript">
$(document).ready(function(){
	$( ".select2" ).select2({dropdownAutoWidth : true});
			// Validate form
			$("#add_place").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
				rules: {
				},
        submitHandler: function(form) {
                
          var formData = new FormData($("#add_place")[0]);
          
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/place/addplace", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: formData, // giá trị post
              cache: false,
              contentType: false,
              processData: false,
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error_place').hide();
                  $('#error_place').slideToggle(100); // hiển thị thẻ div success
                  $('#error_place').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error_place').fadeOut(10000);

              }
          });
          return false;
           
       }
					 
				 
			});
	
});
</script>
     
<div class="login_body">
  
      <form id="add_place" method="post" action="" autocomplete="off">
        <div class="col-xs-4">
          <table style="margin-top:20px;">
            <tr>
                <td>Mã kho hàng </td>
                <td><input type="text" id="place_code" name="place_code" tabindex="1" autofocus required="required"></td>
                
            </tr>
            <tr>
                <td>Tên kho hàng </td>
                <td><input type="text" id="place_name" name="place_name" tabindex="2" required="required"></td>
                
            </tr>
            <tr>
                <td>Tỉnh/TP </td>
                <td>
                  <select class="form-control select2" id="place_province" name="place_province" required="required" tabindex="3">
                    <?php foreach ($provinces as $province) { ?>
                      <option value="<?php echo $province->province_id ?>"><?php echo $province->province_name ?></option>
                    <?php } ?>
                  </select>
                </td>
            </tr>
            
        </table> 
        </div>
        <div class="col-xs-8">
          <div id="map_canvas" style="width:500px;height:200px;"></div>
          <table>
            <tr>
              <td>Lat</td>
              <td><input type="text" id="place_lat" name="place_lat" tabindex="4"></td>
            
              <td>Long</td>
              <td><input type="text" id="place_long" name="place_long" tabindex="5"></td>
            </tr>
          </table>
          
        </div>
          
    </form>
</div>

<div id="error_place" class="error"><?php echo isset($error) ? $error : null; ?></div>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&callback=initialize"></script>
<script>
var directionsDisplay,
    directionsService,
    map;

function initialize() {
  var directionsService = new google.maps.DirectionsService();
  directionsDisplay = new google.maps.DirectionsRenderer();
  var chicago = new google.maps.LatLng(41.850033, -87.6500523);
  var mapOptions = { zoom:7, mapTypeId: google.maps.MapTypeId.ROADMAP, center: chicago }
  map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
  directionsDisplay.setMap(map);
   google.maps.event.addListener(map, 'click', function(event) {
     marker = new google.maps.Marker({position: event.latLng, map: map});
     console.log(event.latLng);   // Get latlong info as object.
     console.log( "Latitude: "+event.latLng.lat()+" "+", longitude: "+event.latLng.lng()); // Get separate lat long.
 });
}

</script>