<script type="text/javascript">
$(document).ready(function(){
	$( ".select2" ).select2();
			// Validate form
			$("#edit").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
				rules: {
				},
        submitHandler: function(form) {
          
          var formData = new FormData($("#edit")[0]);
          formData.append('place_id', '<?php echo $place_data->place_id ?>');
          
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/place/editplace", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: formData, // giá trị post
              cache: false,
              contentType: false,
              processData: false,
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error').hide();
                  $('#error').slideToggle(100); // hiển thị thẻ div success
                  $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error').fadeOut(10000);

              }
          });
          return false;
           
       }
					 
				 
			});
	
});
</script>

        <div class="login_body">
         
              <form id="edit" method="post" action="" autocomplete="off">
                  <table style="margin-top:20px;">
                    <tr>
                        <td>Mã kho hàng </td>
                        <td><input type="text" id="place_code" name="place_code" tabindex="1" autofocus required="required" value="<?php echo $place_data->place_code ?>"></td>
                        
                    </tr>
                    <tr>
                        <td>Tên kho hàng</td>
                        <td><input type="text" id="place_name" name="place_name" tabindex="2" required="required" value="<?php echo $place_data->place_name ?>"></td>
                    </tr>
                    <tr>
                        <td>Tỉnh/TP</td>
                        <td>
                          <select class="form-control select2" id="place_province" name="place_province" required="required" tabindex="2">
                            <?php foreach ($provinces as $province) { ?>
                              <option value="<?php echo $province->province_id ?>" <?php echo $place_data->place_province==$province->province_id?'selected="selected"':null ?> ><?php echo $province->province_name ?></option>
                            <?php } ?>
                          </select>
                        </td>
                        
                    </tr>
                </table> 
            </form>
        </div>
        <div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>


