
        <div class="login_body">
         
                  <table style="margin-top:20px;">
                    <tr>
                        <td>Mã kho hàng </td>
                        <td><input type="text" id="place_code" name="place_code" tabindex="1" autofocus required="required" value="<?php echo $place_data->place_code ?>"></td>
                        
                    </tr>
                    <tr>
                        <td>Tên kho hàng</td>
                        <td><input type="text" id="place_name" name="place_name" tabindex="2" required="required" value="<?php echo $place_data->place_name ?>"></td>
                    </tr>
                    <tr>
                        <td>Tỉnh/TP</td>
                        <td>
                          <select class="form-control select2" id="place_province" name="place_province" required="required" tabindex="2">
                            <?php foreach ($provinces as $province) { ?>
                              <option value="<?php echo $province->province_id ?>" <?php echo $place_data->place_province==$province->province_id?'selected="selected"':null ?> ><?php echo $province->province_name ?></option>
                            <?php } ?>
                          </select>
                        </td>
                        
                    </tr>
                </table> 
            
        </div>
        <div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>


