
<?php
$url_order = 'ASC';
if ($order_by == 'shipment_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

elseif ($order_by == 'bill_number')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'bill_receive_date')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'bill_delivery_date')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'bill_receive_ton')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'bill_receive_unit')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'bill_delivery_ton')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'bill_delivery_unit')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'shipment_oil')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'shipment_from')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'shipment_to')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'vehicle')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'romooc')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'customer')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'shipment_charge')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'shipment_ton')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'oil_add')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'cost_add')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'shipment_revenue')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'shipment_cost')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'shipment_profit')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'shipment_date')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'shipment_round')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'shipment_excess')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'road_oil')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'oil_excess')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

    $i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>
<section class="content-header">
    <h1>TỔNG HỢP PHIẾU VẬN CHUYỂN</h1>
  <ol class="breadcrumb">
    <li><a href="<?php echo $this->url('admin') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><a href="<?php echo $this->url('trucking') ?>">Phiếu vận chuyển</a></li>
  </ol>
</section>
<div id="content" style="padding:5px;">

    <div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
        <?php if(!isset($disable_control)){ ?>
        <div class="add-box"><a class="add_button" id="btnExport" ><i class="fa fa-download"></i> Xuất</a></div>
        <?php } ?>
    </div>
    <div class="tablenav top">
        <div class="add-box">
            <select id="sl_round" name="sl_round" style="width:90px">
             <?php 
                for ($k=1; $k < 13; $k++) { 
                    echo '<option value="'.$k.'">Tháng '.$k.'</option>';
                }
             ?>
            </select>
            <select id="sl_staff" name="sl_staff" style="width:100px">
             <?php 
                $nam = date('Y');
                for ($k=($nam-5); $k < ($nam+5); $k++) { 
                    echo '<option value="'.$k.'">Năm '.$k.'</option>';
                }
             ?>
            </select>

            <input type="button" name="xem" id="xem" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  
            
        </div>
    </div>
    <div class="tablenav top">
        <div style="clear:both"></div>
        <div class="add-box">
                  
            Từ  <input style="width:80px" type="search" name="batdau" id="batdau" placeholder="Chọn ngày" <?php if(isset($batdau)) echo "value='$batdau'"; ?> >  
            Đến  <input style="width:80px" type="search" name="ketthuc" id="ketthuc" placeholder="Chọn ngày" <?php if(isset($ketthuc)) echo "value='$ketthuc'"; ?> >  
             <input type="button" name="xem" id="xem" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  
            
        </div>
        <div style="clear:both"></div>
        
        <div class="add-box">
            <input type="button" name="chon" id="chon" value="Chọn" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  
        </div>
        <div class="add-box" style="margin-right: 5px">
            <select style="width:120px" name="sl_vehicle" id="sl_vehicle">
                <option selected="selected" value="0">Xe</option>
                <?php foreach ($vehicles as $sm) { ?>
                <option value="<?php echo $sm->vehicle_id ?>"><?php echo $sm->vehicle_number ?></option>
                <?php } ?>
            </select>
            <select style="width:120px" name="sl_nv" id="sl_nv">
                <option value="0">Khách hàng</option>
                <?php foreach ($customers as $sm) { ?>
                <option value="<?php echo $sm->customer_id ?>"><?php echo $sm->customer_name ?></option>
                <?php } ?>
            </select>
            
            
        </div>
        <div class="alignleft actions">
        <select name="m" id="chonloc">
            <option  value="18446744073709">Hiển thị tất cả</option>
            <option value="50">Hiển thị 50 giá trị</option>
            <option value="100">Hiển thị 100 giá trị</option>
            <option value="150">Hiển thị 150 giá trị</option>
            <option selected="selected" value="200">Hiển thị 200 giá trị</option>
        </select>
        <input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">                               
        </div>

      </div>

</div>


<table class="table_data" id="tblExport">
<thead>
    <tr>
        <th rowspan="2" class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','shipment_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'shipment_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        <th rowspan="2"  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','bill_number','<?php echo $url_order ?>')">Số DO <?php if ($order_by == 'bill_number'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th rowspan="2"  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','bill_receive_date','<?php echo $url_order ?>')">Ngày nhận <?php if ($order_by == 'bill_receive_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th rowspan="2"  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','bill_delivery_date','<?php echo $url_order ?>')">Ngày giao <?php if ($order_by == 'bill_delivery_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th rowspan="2"  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','vehicle','<?php echo $url_order ?>')">Xe <?php if ($order_by == 'vehicle'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th rowspan="2"  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','romooc','<?php echo $url_order ?>')">Mooc <?php if ($order_by == 'romooc'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th rowspan="2"  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','steersman_name','<?php echo $url_order ?>')">Tài xế <?php if ($order_by == 'steersman_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        <th rowspan="2"  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','shipment_from','<?php echo $url_order ?>')">Nơi nhận <?php if ($order_by == 'shipment_from'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th rowspan="2"  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','shipment_to','<?php echo $url_order ?>')">Nơi giao <?php if ($order_by == 'shipment_to'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th rowspan="2"  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer','<?php echo $url_order ?>')">Khách hàng <?php if ($order_by == 'customer'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th rowspan="2"  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','road_km','<?php echo $url_order ?>')">Chiều dài (km)<?php if ($order_by == 'road_km'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th rowspan="2"  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','shipment_oil','<?php echo $url_order ?>')">Dầu thực lãnh<?php if ($order_by == 'shipment_oil'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th rowspan="2"  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','road_oil','<?php echo $url_order ?>')">Dầu định mức <?php if ($order_by == 'road_oil'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th rowspan="2"  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','shipment_cost','<?php echo $url_order ?>')">Chi phí đi đường <?php if ($order_by == 'shipment_cost'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th colspan="<?php echo count($loan_units) ?>"  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','shipment_loan','<?php echo $url_order ?>')">Chi hộ <?php if ($order_by == 'shipment_loan'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th rowspan="2"  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','bridge_cost','<?php echo $url_order ?>')">Cầu đường <?php if ($order_by == 'bridge_cost'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        <th rowspan="2"  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','police_cost','<?php echo $url_order ?>')">Công an <?php if ($order_by == 'police_cost'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        <th rowspan="2"  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','warehouse_add','<?php echo $url_order ?>')">Bồi dưỡng <?php if ($order_by == 'warehouse_add'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        <th rowspan="2"  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer_type','<?php echo $url_order ?>')">Mặt hàng <?php if ($order_by == 'customer_type'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th colspan="<?php echo count($cont_units) ?>" class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','bill_receive_ton','<?php echo $url_order ?>')">Số lượng nhận <?php if ($order_by == 'bill_receive_ton'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th colspan="<?php echo count($cont_units) ?>" class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','bill_delivery_ton','<?php echo $url_order ?>')">Số lượng giao <?php if ($order_by == 'bill_delivery_ton'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th rowspan="2"  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','bill_in','<?php echo $url_order ?>')">Giờ vào <?php if ($order_by == 'bill_in'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th rowspan="2"  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','bill_out','<?php echo $url_order ?>')">Giờ ra <?php if ($order_by == 'bill_out'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
       
    </tr>
    <tr>
        <?php foreach ($loan_units as $loan) { ?>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','cost_list','<?php echo $url_order ?>')"><?php echo $loan->cost_list_name ?> <?php if ($order_by == 'cost_list'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <?php } ?>
        <?php foreach ($cont_units as $cont) { ?>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','bill_receive_unit','<?php echo $url_order ?>')"><?php echo $cont->cont_unit_name ?> <?php if ($order_by == 'bill_receive_unit'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <?php } ?>
        <?php foreach ($cont_units as $cont) { ?>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','bill_delivery_unit','<?php echo $url_order ?>')"><?php echo $cont->cont_unit_name ?> <?php if ($order_by == 'bill_delivery_unit'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <?php } ?>
    </tr>
    
   </thead>
   <tbody>
    <?php $v = array(); $doanhthu = array(); $chiphi = array(); $loinhuan = array(); $litdau = array(); ?>
    <?php foreach ($shipments as $shipment) : 
        $dau = ($shipment->shipment_road_oil>0?$shipment->shipment_road_oil:(isset($road['road_oil'][$shipment->shipment_id])?$road['road_oil'][$shipment->shipment_id]:0))+$shipment->shipment_road_oil_add;
    ?>
    
    
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $shipment->shipment_id ?>" class="edit_tr" >
        	
            <td class="fix" id="shipment_id_<?php echo $shipment->shipment_id; ?>"><?php echo $i++; ?></td>
            <td class="fix" id="bill_number_<?php echo $shipment->shipment_id; ?>"><a target="_blank" href="<?php echo $this->url('shipment/index/'.$shipment->shipment_id) ?>" ><?php echo $shipment->bill_number; ?></a></td>

            <td class="fix" id="bill_receive_date_<?php echo $shipment->shipment_id; ?>"><?php echo $lib->hien_thi_ngay_thang($shipment->bill_receive_date); ?></td>
            <td class="fix" id="bill_delivery_date_<?php echo $shipment->shipment_id; ?>"><?php echo $lib->hien_thi_ngay_thang($shipment->bill_delivery_date); ?></td>
            <td class="fix" data="<?php echo $shipment->vehicle; ?>" id="vehicle_<?php echo $shipment->shipment_id; ?>"><a target="_blank" href="<?php echo $this->url('vehicle/index/'.$shipment->vehicle) ?>" ><?php echo $shipment->vehicle_number; ?></a></td>
            <td class="fix" data="<?php echo $shipment->romooc; ?>" id="romooc_<?php echo $shipment->shipment_id; ?>"><a target="_blank" href="<?php echo $this->url('romooc/index/'.$shipment->romooc) ?>" ><?php echo isset($romooc_data['romooc_number'][$shipment->romooc])?$romooc_data['romooc_number'][$shipment->romooc]:null; ?></a></td>
            <td class="fix" id="steersman_name_<?php echo $shipment->shipment_id; ?>" data="<?php echo $shipment->steersman; ?>"><a target="_blank" href="<?php echo $this->url('steersman/index/'.$shipment->steersman) ?>" ><?php echo $shipment->steersman_name; ?></a></td>
            <td class="fix" data="<?php echo $shipment->shipment_from; ?>" id="shipment_from_<?php echo $shipment->shipment_id; ?>"><a target="_blank" href="<?php echo $this->url('place/view/'.$shipment->shipment_from) ?>" ><?php echo $shipment->shipment_from==$place['place_id'][$shipment->shipment_from]?$place['place_name'][$shipment->shipment_from]:null ?></a></td>
            <td class="fix" data="<?php echo $shipment->shipment_to; ?>" id="shipment_to_<?php echo $shipment->shipment_id; ?>"><a target="_blank" href="<?php echo $this->url('place/view/'.$shipment->shipment_to) ?>" ><?php echo $shipment->shipment_to==$place['place_id'][$shipment->shipment_to]?$place['place_name'][$shipment->shipment_to]:null ?></a></td>
            
            <td class="fix" data="<?php echo $shipment->customer; ?>" id="customer_<?php echo $shipment->shipment_id; ?>"><a target="_blank" href="<?php echo $this->url('customer/index/'.$shipment->customer) ?>" ><?php echo $shipment->customer_name; ?></a></td>
            <td class="fix" id="road_km_<?php echo $shipment->shipment_id; ?>"><?php echo $lib->formatMoney(isset($road['road_km'][$shipment->shipment_id])?$road['road_km'][$shipment->shipment_id]:null); ?></td>
            <td class="fix" id="shipment_oil_<?php echo $shipment->shipment_id; ?>"><?php echo $shipment->shipment_oil; ?></td>
            <td class="fix" id="road_oil_<?php echo $shipment->shipment_id; ?>"><?php echo $dau; ?></td>
            <td class="fix" id="shipment_cost_<?php echo $shipment->shipment_id; ?>"><?php echo $lib->formatMoney($shipment->shipment_road_add); ?></td>
            <?php foreach ($loan_units as $loan) { ?>
            <td class="fix" id="shipment_loan_<?php echo $shipment->shipment_id; ?>"><?php echo isset($loan_shipment_data[$shipment->shipment_id][$loan->cost_list_id])?$lib->formatMoney($loan_shipment_data[$shipment->shipment_id][$loan->cost_list_id]):null; ?></td>
            <?php } ?>
            <td class="fix" ><?php echo $lib->formatMoney(isset($road['bridge_cost'][$shipment->shipment_id])?$road['bridge_cost'][$shipment->shipment_id]:null); ?></td>
            <td class="fix" ><?php echo $lib->formatMoney(isset($road['police_cost'][$shipment->shipment_id])?$road['police_cost'][$shipment->shipment_id]:null); ?></td>
            <td class="fix" ><?php echo $lib->formatMoney(isset($warehouse['boiduong_cn'][$shipment->shipment_id])?$warehouse['boiduong_cn'][$shipment->shipment_id]:null); ?></td>
            <td  class="fix" id="customer_type_<?php echo $shipment->shipment_id; ?>"><?php echo $customer_types[$shipment->shipment_id]; ?></td>
            <?php foreach ($cont_units as $cont) { ?>
            <td class="fix" id="bill_receive_ton_<?php echo $shipment->shipment_id; ?>"><?php echo $shipment->bill_receive_unit==$cont->cont_unit_id?$shipment->bill_receive_ton:null; ?></td>
            <?php } ?>
            <?php foreach ($cont_units as $cont) { ?>
            <td class="fix" id="bill_delivery_ton_<?php echo $shipment->shipment_id; ?>"><?php echo $shipment->bill_delivery_unit==$cont->cont_unit_id?$shipment->bill_delivery_ton:null; ?></td>
            <?php } ?>
            <td class="fix" id="bill_in_<?php echo $shipment->shipment_id; ?>"><?php echo date('H:i:s',$shipment->bill_in); ?></td>
            <td class="fix" id="bill_out_<?php echo $shipment->shipment_id; ?>"><?php echo date('H:i:s',$shipment->bill_out); ?></td>

        </tr>

    <?php endforeach; ?>
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>



<style type="text/css">
    .ui-dialog .ui-dialog-content{
        padding: 3px;
    }

    .showtooltip {
        display:none;
        position:absolute;
        border:1px solid #333;
        background-color:#161616;
        border-radius:5px;
        padding:10px;
        color:#fff;
        font-size:12px Arial;
    }
    
    .ok{
        color: green;
        float: right;
    }
    .no{
        color: red;
    }


.table_data td {
    font-size: 13px;
}
.ui-front {
  z-index: 1031;
}

</style>


<script type="text/javascript">
$(document).ready(function() {
// Tooltip only Text
$('.masterTooltip').hover(function(){
        // Hover over code
        var title = $(this).attr('title');
        $(this).data('tipText', title).removeAttr('title');
        $('<p class="showtooltip"></p>')
        .text(title)
        .appendTo('body')
        .fadeIn('slow');
}, function() {
        // Hover out code
        $(this).attr('title', $(this).data('tipText'));
        $('.showtooltip').remove();
}).mousemove(function(e) {
        var mousex = e.pageX + 20; //Get X coordinates
        var mousey = e.pageY + 10; //Get Y coordinates
        $('.showtooltip')
        .css({ top: mousey, left: mousex })
});


});

</script>


<style type="text/css">
    #ui-datepicker-div{
        font-size: 13px;
    }
    .table_data td {
        font-size: 11px;
        padding: 3px;
    }
</style>
<script type="text/javascript">
    $(function() {
    var pickerOpts = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#ketthuc" ).datepicker( "option", "minDate", selectedDate );

         },
         
    };  
    $("#batdau").datepicker(pickerOpts);

    var pickerOpts4 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#batdau" ).datepicker( "option", "maxDate", selectedDate );
                
         },
         
    };  
    $("#ketthuc").datepicker(pickerOpts4);
              
            
    
});

var x = "<?php echo $xe ?>";
$('#sl_vehicle option[value='+x+']').attr('selected','selected');
var ch = "<?php echo $limit ?>";
$('#chonloc option[value='+ch+']').attr('selected','selected');
var tt = "<?php echo $kh ?>";
$('#sl_nv option[value='+tt+']').attr('selected','selected');

var v = "<?php echo $vong ?>";
$('#sl_round option[value='+v+']').attr('selected','selected');

var tt = "<?php echo $trangthai ?>";
$('#sl_staff option[value='+tt+']').attr('selected','selected');
</script>
<script type="text/javascript">
    
    $('#sl_round').change(function(){
        var m = $(this).val();
        var y = $('#sl_staff').val();
        var firstDay = new Date(y, m-1, 1);
        var lastDay = new Date(y, m, 0);

        $('#batdau').datepicker("setDate", firstDay );
        $('#ketthuc').datepicker("setDate", lastDay );

    });

    $('#sl_staff').change(function(){
        var y = $(this).val();
        var m = $('#sl_round').val();
        var firstDay = new Date(y, m-1, 1);
        var lastDay = new Date(y, m, 0);

        $('#batdau').datepicker("setDate", firstDay );
        $('#ketthuc').datepicker("setDate", lastDay );

    });

</script>