<script type="text/javascript">
$(document).ready(function(){
	$( ".select2" ).select2({dropdownAutoWidth : true});
			// Validate form
			$("#add_vehicle").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
				rules: {
				},
        submitHandler: function(form) {
                
          var formData = new FormData($("#add_vehicle")[0]);
          
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/vehicle/addvehicle", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: formData, // giá trị post
              cache: false,
              contentType: false,
              processData: false,
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error_vehicle').hide();
                  $('#error_vehicle').slideToggle(100); // hiển thị thẻ div success
                  $('#error_vehicle').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error_vehicle').fadeOut(10000);

              }
          });
          return false;
           
       }
					 
				 
			});
	
});
</script>
     
<div id="error_vehicle" class="error"><?php echo isset($error) ? $error : null; ?></div>
<div class="login_body">
  
      <form id="add_vehicle" method="post" action="" autocomplete="off">
        <div class="col-xs-7">
          <label for="vehicle_number">Số xe</label>
          <div class="input-group">
            <input type="text" id="vehicle_number" name="vehicle_number" tabindex="1" autofocus required="required">
          </div>
          <label for="vehicle_model">Model</label>
          <div class="input-group">
            <input type="text" id="vehicle_model" name="vehicle_model" tabindex="4">
          </div>
          <label for="vehicle_year">Năm sản xuất</label>
          <div class="input-group">
            <input type="text" id="vehicle_year" name="vehicle_year" tabindex="5">
          </div>
          
        </div>
        <div class="col-xs-5">
          <label for="vehicle_brand">Nhãn hiệu</label>
          <div class="input-group">
            <select class="form-control select2" id="vehicle_brand" name="vehicle_brand" required="required" tabindex="2">
              <?php foreach ($brands as $brand) { ?>
                <option value="<?php echo $brand->brand_id ?>"><?php echo $brand->brand_name ?></option>
              <?php } ?>
            </select>
          </div>
          <label for="vehicle_country">Xuất xứ</label>
          <div class="input-group">
            <select class="form-control select2" id="vehicle_country" name="vehicle_country" tabindex="3">
              <?php foreach ($countrys as $country) { ?>
                <option value="<?php echo $country->country_id ?>" <?php echo $country->country_name=='Việt Nam'?'selected="selected"':null ?> ><?php echo $country->country_name ?></option>
              <?php } ?>
            </select>
          </div>
          
          <label for="vehicle_owner">Xe thuê</label>
          <div class="input-group">
            <input type="checkbox" id="vehicle_owner" name="vehicle_owner" tabindex="6" class="ace ace-switch ace-switch-6" value="1"><span class="lbl"></span>
          </div>
        </div>
    </form>
</div>



