<script type="text/javascript">
$(document).ready(function(){
	$( ".select2" ).select2({dropdownAutoWidth : true});
			// Validate form
			$("#add_shipping").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
        ignore: "",
        rules: {
        },
        errorPlacement: function (error, element) {
          if(element.is('input[type=checkbox]') || element.is('input[type=radio]')) {
            var controls = element.closest('div[class*="col-"]');
            if(controls.find(':checkbox,:radio').length > 1) controls.append(error);
            else error.insertAfter(element.nextAll('.lbl:eq(0)').eq(0));
          }
          else if(element.is('.select2')) {
            error.insertAfter(element.siblings('[class*="select2-container"]:eq(0)'));
          }
          else if(element.is('.chosen-select')) {
            error.insertAfter(element.siblings('[class*="chosen-container"]:eq(0)'));
          }
          else error.insertAfter(element.parent());
        },
        submitHandler: function(form) {
                
          var formData = new FormData($("#add_shipping")[0]);
          
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/shipping/addshipping", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: formData, // giá trị post
              cache: false,
              contentType: false,
              processData: false,
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error_shipping').hide();
                  $('#error_shipping').slideToggle(100); // hiển thị thẻ div success
                  $('#error_shipping').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error_shipping').fadeOut(10000);

              }
          });
          return false;
           
       }
					 
				 
			});
	
});
</script>
     
<div class="login_body">
  
      <form id="add_shipping" method="post" action="" autocomplete="off">
          <table style="margin-top:20px;">
            <tr>
                <td>Tên hãng tàu </td>
                <td><input type="text" id="shipping_name" name="shipping_name" tabindex="1" autofocus required="required"></td>
                
            </tr>
            <tr>
                <td>Quốc gia </td>
                <td>
                  <select class="form-control select2" id="shipping_country" name="shipping_country" required="required" tabindex="2">
                    <?php foreach ($countrys as $country) { ?>
                      <option value="<?php echo $country->country_id ?>"><?php echo $country->country_name ?></option>
                    <?php } ?>
                  </select>
                </td>
            </tr>
        </table> 
    </form>
</div>
<div id="error_shipping" class="error"><?php echo isset($error) ? $error : null; ?></div>


