<script type="text/javascript">
$(document).ready(function(){
	$( ".select2" ).select2({dropdownAutoWidth : true});
			// Validate form
			$("#edit").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
				rules: {
				},
        submitHandler: function(form) {
          
          var formData = new FormData($("#edit")[0]);
          formData.append('shipping_id', '<?php echo $shipping_data->shipping_id ?>');
          
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/shipping/editshipping", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: formData, // giá trị post
              cache: false,
              contentType: false,
              processData: false,
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error').hide();
                  $('#error').slideToggle(100); // hiển thị thẻ div success
                  $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error').fadeOut(10000);

              }
          });
          return false;
           
       }
					 
				 
			});
	
});
</script>

        <div class="login_body">
         
              <form id="edit" method="post" action="" autocomplete="off">
                  <table style="margin-top:20px;">
                    <tr>
                        <td>Tên hãng tàu</td>
                        <td><input type="text" id="shipping_name" name="shipping_name" tabindex="1" required="required" value="<?php echo $shipping_data->shipping_name ?>"></td>
                    </tr>
                    <tr>
                        <td>Quốc gia</td>
                        <td>
                          <select class="form-control select2" id="shipping_country" name="shipping_country" required="required" tabindex="2">
                            <?php foreach ($countrys as $country) { ?>
                              <option value="<?php echo $country->country_id ?>" <?php echo $shipping_data->shipping_country==$country->country_id?'selected="selected"':null ?> ><?php echo $country->country_name ?></option>
                            <?php } ?>
                          </select>
                        </td>
                        
                    </tr>
                </table> 
            </form>
        </div>
        <div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>


