
<?php
$url_order = 'DESC';
if ($order_by == 'shipping_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'shipping_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'country_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
$i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>
<div id="content" style="padding:5px;">
   
<table class="table_data" id="tblexport" >
<thead>
    <tr>
    	<th><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall" class="ace ace-checkbox-2" /><span class="lbl"></span></th>
        <th><a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','shipping_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'shipping_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a></th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','shipping_name','<?php echo $url_order ?>')">Tên hãng tàu <?php if ($order_by == 'shipping_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','country_name','<?php echo $url_order ?>')">Quốc gia <?php if ($order_by == 'country_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
           
        <th>
            <div class="tools action-buttons pull-right">
                <select name="m" id="chonloc" class="input-sm" onchange="limit_change($(this).val(),'<?php echo $order_by ?>','<?php echo $order ?>','<?php echo $keyword ?>')">
                    <option value="18446744073709">All</option>
                    <option value="10">10</option>
                    <option value="20">20</option>
                    <option value="50">50</option>
                    <option value="100">100</option>
                    <option value="500">500</option>
                </select>
                <a class="purpose" data-original-title="Thêm mới">
                    <i class="ace-icon fa fa-plus-circle bigger-150" onclick="add_click('<?php echo $this->url("shipping/add") ?>','Thêm hãng tàu mới')"></i>
                </a> 
                <div class="pull-right pos-rel dropdown-hover">
                    <button class="btn btn-minier bigger" style="line-height: 26px">
                        <i class="ace-icon fa fa-windows icon-only bigger-120"></i>
                    </button>

                    <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-caret dropdown-close dropdown-menu-right">
                        <li>
                            <a class="tooltip-warning" data-rel="tooltip" data-original-title="Tìm">
                                <span class="orange">
                                    <i class="ace-icon fa fa-search bigger-150" onclick="search_click()"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a class="tooltip-success" data-rel="tooltip" data-original-title="Tải lại">
                                <span class="green">
                                    <i class="ace-icon fa fa-refresh bigger-150" onclick="refresh_click()"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a class="tooltip-error" data-rel="tooltip" data-original-title="Xóa">
                                <span class="red">
                                    <i class="ace-icon fa fa-trash-o bigger-150" onclick="del_click()"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a class="tooltip-info" data-rel="tooltip" data-original-title="Nhập">
                                <span class="purple">
                                    <i class="ace-icon fa fa-cloud-upload bigger-150" onclick="import_click('<?php echo $this->url("shipping/import") ?>','Nhập dữ liệu từ file Excel')"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            
                            <div class="text-center pos-rel dropdown-hover">
                                <a class="tooltip-info" data-rel="tooltip" data-original-title="Xuất">
                                    <span class="blue">
                                        <i class="ace-icon fa fa-cloud-download bigger-150"></i>
                                    </span>
                                </a>
                                <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-caret dropdown-close dropdown-menu-right">
                                    <li>
                                        <a class="tooltip-success" data-rel="tooltip" data-original-title="Excel">
                                            <span class="green">
                                                <i class="ace-icon fa fa-file-excel-o bigger-130" onclick="export_click('excel','tblexport')"></i>
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a class="tooltip-error" data-rel="tooltip" data-original-title="PDF">
                                            <span class="red">
                                                <i class="ace-icon fa fa-file-pdf-o bigger-130" onclick="export_click('pdf','tblexport')"></i>
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a class="tooltip-info" data-rel="tooltip" data-original-title="Word">
                                            <span class="blue">
                                                <i class="ace-icon fa fa-file-word-o bigger-130" onclick="export_click('word','tblexport')"></i>
                                            </span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        
                    </ul>
                </div>                        
            </div>
        </th>
    </tr>
   </thead>
   <tbody>
    <?php foreach ($shippings as $shipping) : ?>
        <tr id="<?php echo $shipping->shipping_id ?>" class="edit_tr">
        	<td class="text-center"><input name="check[]" type="checkbox" class="checkbox ace" value="<?php echo $shipping->shipping_id ?>"><span class="lbl"></span></td>
            <td class="text-center"><?php echo $i++; ?></td>
            <td><?php echo $shipping->shipping_name; ?></td>
            <td><?php echo $shipping->country_name; ?></td>
            
            
            <td class="text-right">
                <div class="tools action-buttons">
                    <a class="blue"  onclick="view_click('<?php echo $this->url("shipping/view/") ?>','Thông tin hãng tàu',<?php echo $shipping->shipping_id ?>)">
                        <i class="ace-icon fa fa-info-circle bigger-130"></i>
                    </a>
                    <a class="green"  onclick="edit_click('<?php echo $this->url("shipping/edit/") ?>','Cập nhật hãng tàu',<?php echo $shipping->shipping_id ?>)">
                        <i class="ace-icon fa fa-pencil bigger-130"></i>
                    </a>

                    <a class="red" >
                        <i class="ace-icon fa fa-trash-o bigger-130" onclick="del(<?php echo $shipping->shipping_id ?>)"></i>
                    </a>
                </div>
            </td>
        </tr>
    <?php endforeach; ?>
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>
</div>
<script type="text/javascript">
    var ch = "<?php echo $limit ?>";
$('#chonloc option[value='+ch+']').attr('selected','selected');
</script>