
<?php

$url_order = 'ASC';

if ($order_by == 'sell_id')

    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';



elseif ($order_by == 'sell_date')

    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

elseif ($order_by == 'sell_comment')

    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

elseif ($order_by == 'sell_money')

    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

elseif ($order_by == 'customer_name')

    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';



    $ii = $sonews*$page-($sonews-1);



?>



<div id="loading"></div>

<div id="winpopup"></div>

<section class="content-header">

    <h1>XUẤT BÁN</h1>

  <ol class="breadcrumb">

    <li><a href="<?php echo $this->url('admin') ?>"><i class="fa fa-dashboard"></i> Home</a></li>

    <li class="active"><a href="<?php echo $this->url('sell') ?>">Xuất bán</a></li>

  </ol>

</section>

<div id="content" style="padding:5px;">



    <div class="search-box">

        

        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">

        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">

        <?php if(!isset($disable_control)){ ?>

        <div class="add-box"><a class="add_button" id="btnExport" ><i class="fa fa-download"></i> Xuất</a></div>

        <div class="add-box"><a class="add_button" onClick="add_click();"><i class="fa fa-plus"></i> Thêm mới</a></div>

        <?php } ?>

    </div>

    <div class="tablenav top">

        <div class="add-box">

            <select id="sl_round" name="sl_round" style="width:90px">

             <?php 

                for ($k=1; $k < 13; $k++) { 

                    echo '<option value="'.$k.'">Tháng '.$k.'</option>';

                }

             ?>

            </select>

            <select id="sl_staff" name="sl_staff" style="width:100px">

             <?php 

                $nam = date('Y');

                for ($k=($nam-5); $k < ($nam+5); $k++) { 

                    echo '<option value="'.$k.'">Năm '.$k.'</option>';

                }

             ?>

            </select>



            <input type="button" name="xem" id="xem" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  

            

        </div>

    </div>

    <div class="tablenav top">

        <div style="clear:both"></div>

        <div class="add-box">

                  

            Từ  <input style="width:80px" type="search" name="batdau" id="batdau" placeholder="Chọn ngày" <?php if(isset($batdau)) echo "value='$batdau'"; ?> >  

            Đến  <input style="width:80px" type="search" name="ketthuc" id="ketthuc" placeholder="Chọn ngày" <?php if(isset($ketthuc)) echo "value='$ketthuc'"; ?> >  

             <input type="button" name="xem" id="xem" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  

            

        </div>

        <div style="clear:both"></div>
        
        <div class="add-box">
            <input type="button" name="chon" id="chon" value="Chọn" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  
        </div>
        <div class="add-box" style="margin-right: 5px">
            <select style="width:120px" name="sl_nv" id="sl_nv">
                <option value="0">Khách hàng</option>
                <?php foreach ($customers as $sm) { ?>
                <option value="<?php echo $sm->customer_id ?>"><?php echo $sm->customer_name ?></option>
                <?php } ?>
            </select>
            
            
        </div>

      </div>

      <div class="tablenav top">


        <?php if(!isset($disable_control)){ ?>

        <div class="alignleft actions">

            <select name="action" id="action">

                <option value="-1" selected="selected">Chọn</option>

                

                <option value="delete">Xóa</option>

            </select>

            <input type="button" name="" id="doaction" class="button action" value="Áp dụng" onclick="action();">

        </div>

        <?php } ?>

        <div class="alignleft actions">

        <select name="m" id="chonloc" style="width:200px">

            <option value="18446744073709">Hiển thị tất cả</option>

            <option value="50">Hiển thị 50 giá trị</option>

            <option value="100">Hiển thị 100 giá trị</option>

            <option value="150">Hiển thị 150 giá trị</option>

            <option value="200">Hiển thị 200 giá trị</option>

            <option selected="selected" value="250">Hiển thị 250 giá trị</option>

        </select>

        <input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">                               

        </div>



      </div>

</div>





<table class="table_data" id="tblExport">

<thead>

    <tr>

    	<th class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>

        <th  class="fix" >

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','sell_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'sell_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>

        

        <th  class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','sell_date','<?php echo $url_order ?>')">Ngày <?php if ($order_by == 'sell_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>

        <th  class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer_name','<?php echo $url_order ?>')">Khách hàng <?php if ($order_by == 'customer_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>

        <th  class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','sell_money','<?php echo $url_order ?>')">Số tiền <?php if ($order_by == 'sell_money'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>

        <th  class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','sell_comment','<?php echo $url_order ?>')">Nội dung <?php if ($order_by == 'sell_comment'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>

        <?php if(!isset($disable_control)){ ?>

           

        <th  class="fix">&nbsp;</th>

        <?php } ?>

    </tr>

    

   </thead>

   <tbody>

    <?php 
    $tongthanhtien = 0;
    foreach ($sells as $sell) : 
      $tongthanhtien += $sell->sell_money;
    ?>

    

        

        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $sell->sell_id ?>" class="edit_tr" >

        	<td><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $sell->sell_id ?>"></td>

            <td  class="fix"><?php echo $ii++; ?></td>

            <td class="fix" id="sell_date_<?php echo $sell->sell_id; ?>"><?php echo $lib->hien_thi_ngay_thang($sell->sell_date); ?></td>

            <td class="fix" data="<?php echo $sell->sell_customer; ?>" id="sell_customer_<?php echo $sell->sell_id; ?>"><?php echo $sell->customer_name; ?></td>

            <td class="fix" id="sell_money_<?php echo $sell->sell_id; ?>"><?php echo $lib->formatMoney($sell->sell_money); ?></td>

            <td class="fix" id="sell_comment_<?php echo $sell->sell_id; ?>"><?php echo $sell->sell_comment; ?></td>


            <?php if(!isset($disable_control)){ ?>

            <td class="pull-right">

                <button class="btn btn-sm btn-flat btn-primary"><i class="fa fa-edit"></i> Sửa</button>

                <button class="btn btn-sm btn-flat btn-danger" onclick="del(<?php echo $sell->sell_id ?>)" ><i class="fa fa-remove"></i> Xóa</button>

            </td>

            <?php } ?>

        </tr>



    <?php endforeach; ?>
        <tr  style="font-weight: bold; color: rgb(23, 119, 226);" >
            
            <th colspan="4" style="border-right: 1px solid rgb(236, 235, 235);border-top: 1px solid #80C8E5;padding: 7px; text-align: right;" >
                Tổng cộng
            </th>
            <td class="fix" ><?php echo $lib->formatMoney($tongthanhtien) ?></td>
            <td class="fix" ></td>
        </tr>
        

   </tbody>

</table>

<?php

$this->helper('slidePaginator');

?>



<div class="add-field">

    <section class="content">

      <div class="row">

        <!-- left column -->

        <div class="col-md-12">

          <!-- general form elements -->
          <div class="box box-primary">

                    <!-- /.box-header -->

                    <!-- form start -->
                    <form id="add_sell" role="form" method="post" action="" enctype="multipart/form-data">

                      <div class="row">


                        <div class="col-md-3 col-xs-6">

                          <div class="box-body">

                            <div class="form-group">

                              <label for="sell_date">Ngày</label>

                              <input class="ngay" type="text" id="sell_date"  name="sell_date" tabindex="1" required="required" >

                            </div>

                          </div>

                          <!-- /.box-body -->

                          

                        </div>

                        <div class="col-md-3 col-xs-6">

                          <div class="box-body">

                            <div class="form-group">

                              <label for="sell_customer">Khách hàng <a target="_blank" title="Thêm khách hàng" href="<?php echo $this->url('customer') ?>"><i class="fa fa-plus"></i></a></label>

                              <input type="text" autocomplete="off" id="sell_customer"  name="sell_customer" tabindex="2"  placeholder="Nhập tên hoặc * để chọn" required="required" >

                                <ul id="customer_list_id"></ul>

                            </div>

                            

                            
                            

                          </div>

                          <!-- /.box-body -->

                          

                        </div>
                        <div class="col-md-3 col-xs-6">

                          <div class="box-body">

                            <div class="form-group">

                              <label for="sell_comment">Nội dung</label>

                              <input type="text" id="sell_comment"  name="sell_comment" tabindex="3" required="required">

                            </div>
                            
                            

                          </div>

                          <!-- /.box-body -->

                          

                        </div>

                        <div class="col-md-3 col-xs-6">

                          <div class="box-body">

                            
                            <div class="form-group">

                              <label for="sell_money">Số tiền</label>

                              <input type="text" class="numbers" id="sell_money"  name="sell_money" tabindex="4" required="required" >

                            </div>

                          </div>

                          <!-- /.box-body -->

                          

                        </div>


                      </div>

                      <?php if(!isset($disable_control)){ ?>

                      <div class="row">

                        <div class="col-md-12">

                            <div class="box-footer">

                            <input type="hidden" readonly id="yes" name="yes" required="required" >

                            <button type="submit" class="btn btn-primary" tabindex="5">Hoàn thành</button>

                            <button type="reset" class="btn" tabindex="6">Nhập lại</button>

                          </div>

                          <div class="box-footer">

                            <div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>

                          </div>

                        </div>

                      </div>

                      <?php } ?>

                    </form>

                  </div>

          <!-- /.box -->



        </div>

        <!--/.col (left) -->

        

      </div>

      <!-- /.row -->

    </section>

    <!-- /.content -->

       

</div>



<script type="text/javascript">
$('html').click(function(e) {

    $('#customer_list_id').slideUp(200);

});
    $('.edit_tr').click(function(e){


        if(!$('.checkbox').is(':focus') && e.target.nodeName != "A"){

            if(!$('.checkbox').is(':focus')){

                $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);

            }

            var sell_customer = $(this).find("#sell_customer_"+$(this).attr('id')).attr('data');
            var sell_customer_name = $(this).find("#sell_customer_"+$(this).attr('id')).text();

            var sell_date = $(this).find("#sell_date_"+$(this).attr('id')).text();

            var sell_money = $(this).find("#sell_money_"+$(this).attr('id')).text();

            var sell_comment = $(this).find("#sell_comment_"+$(this).attr('id')).text();


            $('#yes').val($(this).attr('id'));
            
            $('#sell_customer').attr('data',sell_customer);
            $('#sell_customer').val(sell_customer_name);
            $('#sell_customer').attr('code',true);

            $('#sell_date').val(sell_date.replace(/\//g,"-"));

            $('#sell_money').val(sell_money);

            $('#sell_comment').val(sell_comment);
            


            $( ".add-field" ).dialog( "open" );

        }

    });

</script>

<script type="text/javascript">

function add_click(){

    $('#yes').val("");

    $('.add-field').slideDown(500);

     $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);   

        

        $('#sell_customer').attr('data',"");
        $('#sell_customer').val("");
        $('#sell_customer').attr('code',false);

        $('#sell_date').val("");

        $('#sell_money').val("");

        $('#sell_comment').val("");

        
        

        $('.number').focus(function(){

            if ( $(this).val() == '0') {

               $(this).val(""); 

            };

            

        });

        $('.number').blur(function(){

            if ( $(this).val() == "") {

                $(this).val(0);

            };

            

        });





   $( ".add-field" ).dialog( "open" );



}



$(document).ready(function(){

            // Validate form

            $("#add_sell").validate({

                errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi

                rules: {

                    

                },

                submitHandler: function(form) {

                  if ($('#sell_customer').attr('code') == 'false') {

                        $('#sell_customer').val("");

                        $('#sell_customer').focus();

                        return false;

                    };

                    var sell_customer = $('#sell_customer').attr('data');

                    var sell_date = $('#sell_date').attr('value');

                    var sell_money = $('#sell_money').attr('value');

                    var sell_comment = $('#sell_comment').attr('value');

                    

                    var yes = $('#yes').attr('value');

                    

                    var action      = "them";

                 

                    $.ajax({

                        type: "POST", // phương thức gởi đi

                        url: "<?php echo BASE_URL ?>/sell/add", // nơi mà dữ liệu sẽ chuyển đến khi submit

                        data: {

                            sell_customer: sell_customer,

                            sell_date: sell_date,

                            sell_money: sell_money,

                            sell_comment: sell_comment,

                            yes: yes,

                            }, // giá trị post

                        success: function(answer){ // if everything goes well

                            //alert(answer);

                            $('#error').hide();

                            $('#error').slideToggle(100); // hiển thị thẻ div success

                            $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success

                            $('#error').fadeOut(10000);



                            if (yes != "") {

                                if (answer.trim() != "Thông tin này đã tồn tại" ) {

                                  setTimeout(function() {

                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');

                                      }, 200);

                                    $('#export_stock_name_'+yes).text(export_stock_name);

                                    $('#province_name_'+yes).text($('#province option:selected').text());

                                }

                            }

                            else{

                                if (answer.trim() != "Thông tin này đã tồn tại") {

                                  setTimeout(function() {

                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');

                                      }, 200);

                                    var lastID = parseInt($('#lasted').html());

                                    var rowCount = parseInt($('.table_data > tbody > tr').length);

                                    $('.table_data > tbody:last')

                                    .append(

                                        '<tr onclick="HighLightTR(this,#4d90fe,cc3333);" id="'+parseInt(lastID+1)+'" class="edit_tr"><td><input name="check[]" type="checkbox" class="checkbox" value="'+parseInt(lastID+1)+'"></td><td class="fix">'+parseInt(rowCount+1)+'</td><td class="fix" id="export_stock_name_'+parseInt(lastID+1)+'">'+export_stock_name+'</td><td class="fix" data="'+province+'" id="province_name_'+parseInt(lastID+1)+'">'+$('#province option:selected').text()+'</td><td><a class="error" href="#">Sửa</a> | <a class="error" onclick="del('+parseInt(lastID+1)+')">Xóa</a></td></tr>'

                                    );



                                    $('#lasted').html(parseInt(lastID+2));

                                }

                            }

                        }

                    });

                    return false;

                     

                 }

            });


      $('.numbers').val(function(index, value) {

          return value

            .replace(/\D/g, "")

            .replace(/\B(?=(\d{3})+(?!\d))/g, ",")

          ;

        });



    $('#sell_customer').keyup(function(){
      
        var keyword = $(this).val();
        $.ajax({
            url: '<?php echo BASE_URL ?>/sell/getcustomer',
            type: 'POST',
            data: {keyword:keyword},
            success:function(data){
                $('#customer_list_id').slideDown(200);
                $('#customer_list_id').html(data);
            }
        });
        if ($('#sell_customer').val() == "" || $('#sell_customer').attr('data') == "") {
            //$('#loc_from').val("");
            $('#sell_customer').attr('data',"");
            $('#sell_customer').attr('code',false);
        }
      
   });



    $('.number').keyup(function(event) {



          // skip for arrow keys

      if(event.which >= 37 && event.which <= 40) return;



      // format number

      $(this).val(function(index, value) {

        return value

          .replace(/[^0-9-.]/g, "")

        ;

      });

    });

   

   $('.numbers').keyup(function(event) {



          // skip for arrow keys

      if(event.which >= 37 && event.which <= 40) return;



      // format number

      $(this).val(function(index, value) {

        return value

          .replace(/[^0-9]/g, "")

          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")

        ;

      });

    });





});

function set_item_customer(value,name) {
    // change input value
    $('#sell_customer').val(name);
    $("#sell_customer").attr("data",value);
    $("#sell_customer").attr("code",'true');
    
    // hide proposition list
    $('#customer_list_id').hide();
    $('#sell_customer').focus();
     
}
function get_number(id){

    return $(id).val().replace(/\,/g,'');

}


</script>

<script type="text/javascript">



$( ".add-field" ).dialog({

    autoOpen: false,

    modal: true,

    width: "auto",

    title: "Xuất bán",

    hide: 'fold',

    show: 'blind'

});



</script>



<script type="text/javascript">

    $(function() {

    var pickerOpts = {

        closeText: "Đóng",

        currentText: "Hiện tại",

        nextText: "Tiếp",

        prevText: "Quay lại",

        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",

        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],

        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",

        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],

        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",

        "Thứ sáu", "Thứ bảy"],

        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",

        "T6", "T7"],

        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",

        "T6", "T7"],

        //defaultDate: "+1w",

        changeMonth: true,

        changeYear: true,

        dateFormat: 'dd-mm-yy',

        firstDay: 1,

        isRTL: false,

        showButtonPanel: true,

         

    };  

    $(".ngay").datepicker(pickerOpts);



    

              

            

    

});



</script>







<style type="text/css">

    #ui-datepicker-div{

        font-size: 13px;

    }

</style>

<script type="text/javascript">

    $(function() {

    var pickerOpts = {

        closeText: "Đóng",

        currentText: "Hiện tại",

        nextText: "Tiếp",

        prevText: "Quay lại",

        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",

        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],

        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",

        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],

        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",

        "Thứ sáu", "Thứ bảy"],

        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",

        "T6", "T7"],

        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",

        "T6", "T7"],

        //defaultDate: "+1w",

        changeMonth: true,

        changeYear: true,

        dateFormat: 'dd-mm-yy',

        firstDay: 1,

        isRTL: false,

        showButtonPanel: true,

        onClose: function(selectedDate) {

                

                $( "#ketthuc" ).datepicker( "option", "minDate", selectedDate );



         },

         

    };  

    $("#batdau").datepicker(pickerOpts);



    var pickerOpts4 = {

        closeText: "Đóng",

        currentText: "Hiện tại",

        nextText: "Tiếp",

        prevText: "Quay lại",

        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",

        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],

        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",

        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],

        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",

        "Thứ sáu", "Thứ bảy"],

        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",

        "T6", "T7"],

        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",

        "T6", "T7"],

        //defaultDate: "+1w",

        changeMonth: true,

        changeYear: true,

        dateFormat: 'dd-mm-yy',

        firstDay: 1,

        isRTL: false,

        showButtonPanel: true,

        onClose: function(selectedDate) {

                

                $( "#batdau" ).datepicker( "option", "maxDate", selectedDate );

                

         },

         

    };  

    $("#ketthuc").datepicker(pickerOpts4);

              

            

    

});



var ch = "<?php echo $limit ?>";

$('#chonloc option[value='+ch+']').attr('selected','selected');

var tt = "<?php echo $kh ?>";
$('#sl_nv option[value='+tt+']').attr('selected','selected');


var v = "<?php echo $vong ?>";

$('#sl_round option[value='+v+']').attr('selected','selected');



var tt = "<?php echo $trangthai ?>";

$('#sl_staff option[value='+tt+']').attr('selected','selected');



</script>

<script type="text/javascript">

    

    $('#sl_round').change(function(){

        var m = $(this).val();

        var y = $('#sl_staff').val();

        var firstDay = new Date(y, m-1, 1);

        var lastDay = new Date(y, m, 0);



        $('#batdau').datepicker("setDate", firstDay );

        $('#ketthuc').datepicker("setDate", lastDay );



    });



    $('#sl_staff').change(function(){

        var y = $(this).val();

        var m = $('#sl_round').val();

        var firstDay = new Date(y, m-1, 1);

        var lastDay = new Date(y, m, 0);



        $('#batdau').datepicker("setDate", firstDay );

        $('#ketthuc').datepicker("setDate", lastDay );



    });




</script>
