
<?php
    $i = 1;
    $j = 1;
?>

<div id="loading"></div>
<div id="winpopup"></div>
<section class="content-header">
    <h1>QUÁ TRÌNH HOẠT ĐỘNG</h1>
  <ol class="breadcrumb">
    <li><a href="<?php echo $this->url('admin') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><a href="<?php echo $this->url('vehicleanalytics') ?>">Hoạt động</a></li>
  </ol>
</section>
<div id="content" style="padding:5px;">

    <div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">

        <div class="add-box">
            <input type="button" name="chon" id="chon" value="Chọn" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  
        </div>

        <div class="add-box" style="margin-right: 5px">
            <select style="width:100px" name="sl_vehicle" id="sl_vehicle">
                <option selected="selected" value="0">Xe</option>
                <?php foreach ($vehicle_lists as $sm) { ?>
                <option value="<?php echo $sm->vehicle_id ?>"><?php echo $sm->vehicle_number ?></option>
                <?php } ?>
            </select>

            <select style="width:100px" name="sl_status" id="sl_status">
                <option selected="selected" value="0">Mooc</option>
                <?php foreach ($romooc_lists as $sm) { ?>
                <option value="<?php echo $sm->romooc_id ?>"><?php echo $sm->romooc_number ?></option>
                <?php } ?>
            </select>
            
        </div>
    </div>

</div>

<div class="tabs">
  <ul class="tab-links">
    <li class="active"  ><a href="#tab1"><i class="fa fa-truck"></i> Đầu xe</a></li>
    <li ><a href="#tab2"><i class="fa fa-eraser"></i> Mooc</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab active" id="tab1" >
        <div class="add-box"><a class="add_button" id="btnExport" ><i class="fa fa-download"></i> Xuất</a></div>
        <table class="table_data" id="tblExport">
        <thead>
            <tr>
                <th class="fix">
                    <a>STT </a>
                </th>
                
                <th class="fix">
                    <a >Xe</a>
                </th>
                <th class="fix">
                    <a >Ngày</a>
                </th>
                <th class="fix">
                    <a >Lắp vào</a>
                </th>
                <th class="fix">
                    <a >Thay ra</a>
                </th>
                <th class="fix">
                    <a >Km sử dụng</a>
                </th>
            </tr>
            
           </thead>
           <tbody>
            <?php foreach ($vehicles as $vehicle) : ?>
            <tr style="font-weight: bold;" onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $vehicle->vehicle_id ?>" class="edit_tr vehicle">
                <td class="fix"><?php echo $i++; ?></td>
                <td class="fix" id="vehicle_number_<?php echo $vehicle->vehicle_id; ?>"><a target="_blank" href="<?php echo $this->url('vehicle/index/'.$vehicle->vehicle_id) ?>" ><?php echo $vehicle->vehicle_number ?></a></td>
                <td class="fix" colspan="4"></td>
            </tr>
            
                <?php 
                $m = 1;
                foreach ($data_vehicle[$vehicle->vehicle_id] as $v) : 
                    if ($v->start_time>0) {
                ?>
                    <tr style="display: none; font-style: italic;" onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $v->spare_vehicle_id ?>" class="edit_tr vehicle_<?php echo $vehicle->vehicle_id ?>">
                        <td class="fix"></td>
                        <td class="fix"><?php echo $m++; ?></td>
                        <td class="fix"><?php echo $lib->hien_thi_ngay_thang($v->start_time); ?></td>
                        <td class="fix"><a target="_blank" href="<?php echo $this->url('sparepart/index/'.$v->spare_part) ?>" ><?php echo $spare_data[$v->spare_part]['name'].' ['.$spare_data[$v->spare_part]['seri'].']' ?></a></td>
                        <td class="fix"></td>
                        <td class="fix"></td>
                    </tr>
                <?php
                    }
                    elseif ($v->end_time>0) {
                ?>
                    <tr style="display: none; font-style: italic;" onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $v->spare_vehicle_id ?>" class="edit_tr vehicle_<?php echo $vehicle->vehicle_id ?>">
                        <td class="fix"></td>
                        <td class="fix"><?php echo $m++; ?></td>
                        <td class="fix"><?php echo $lib->hien_thi_ngay_thang($v->end_time); ?></td>
                        <td class="fix"></td>
                        <td class="fix"><a target="_blank" href="<?php echo $this->url('sparepart/index/'.$v->spare_part) ?>" ><?php echo $spare_data[$v->spare_part]['name'].' ['.$spare_data[$v->spare_part]['seri'].']' ?></a></td>
                        <td class="fix"><?php echo isset($spare_data[$v->spare_part]['km']['vehicle'])?$lib->formatMoney($spare_data[$v->spare_part]['km']['vehicle']):null ?></td>
                    </tr>
                <?php
                    }
                ?>
                <?php endforeach; ?>
            
            <?php endforeach; ?>
           </tbody>
        </table>
    </div>
    <div class="tab" id="tab2" >
        <div class="add-box"><a class="add_button" id="btnExport2" ><i class="fa fa-download"></i> Xuất</a></div>
            <table class="table_data" id="tblExport2">
            <thead>
                <tr>
                    <th class="fix">
                        <a>STT </a>
                    </th>
                    
                    <th class="fix">
                        <a >Mooc</a>
                    </th>
                    <th class="fix">
                        <a >Ngày</a>
                    </th>
                    <th class="fix">
                        <a >Lắp vào</a>
                    </th>
                    <th class="fix">
                        <a >Thay ra</a>
                    </th>
                    <th class="fix">
                        <a >Km sử dụng</a>
                    </th>
                </tr>
                
               </thead>
               <tbody>
                <?php foreach ($romoocs as $romooc) : ?>
                <tr style="font-weight: bold;" onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $romooc->romooc_id ?>" class="edit_tr romooc">
                    <td class="fix"><?php echo $j++; ?></td>
                    <td class="fix" id="romooc_number_<?php echo $romooc->romooc_id; ?>"><a target="_blank" href="<?php echo $this->url('romooc/index/'.$romooc->romooc_id) ?>" ><?php echo $romooc->romooc_number ?></a></td>
                    <td class="fix" colspan="4"></td>
                </tr>
                    <?php 
                    $m = 1;
                    foreach ($data_romooc[$romooc->romooc_id] as $v) : 
                        if ($v->start_time>0) {
                    ?>
                        <tr style="display: none; font-style: italic;" onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $v->spare_vehicle_id ?>" class="edit_tr romooc_<?php echo $romooc->romooc_id ?>">
                            <td class="fix"></td>
                            <td class="fix"><?php echo $m++; ?></td>
                            <td class="fix"><?php echo $lib->hien_thi_ngay_thang($v->start_time); ?></td>
                            <td class="fix"><a target="_blank" href="<?php echo $this->url('sparepart/index/'.$v->spare_part) ?>" ><?php echo $spare_data[$v->spare_part]['name'].' ['.$spare_data[$v->spare_part]['seri'].']' ?></a></td>
                            <td class="fix"></td>
                            <td class="fix"></td>
                        </tr>
                    <?php
                        }
                        elseif ($v->end_time>0) {
                    ?>
                        <tr style="display: none; font-style: italic;" onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $v->spare_vehicle_id ?>" class="edit_tr romooc_<?php echo $romooc->romooc_id ?>">
                            <td class="fix"></td>
                            <td class="fix"><?php echo $m++; ?></td>
                            <td class="fix"><?php echo $lib->hien_thi_ngay_thang($v->end_time); ?></td>
                            <td class="fix"></td>
                            <td class="fix"><a target="_blank" href="<?php echo $this->url('sparepart/index/'.$v->spare_part) ?>" ><?php echo $spare_data[$v->spare_part]['name'].' ['.$spare_data[$v->spare_part]['seri'].']' ?></a></td>
                            <td class="fix"><?php echo isset($spare_data[$v->spare_part]['km']['romooc'])?$lib->formatMoney($spare_data[$v->spare_part]['km']['romooc']):null ?></td>
                        </tr>
                    <?php
                        }
                    ?>
                    <?php endforeach; ?>
                <?php endforeach; ?>
               </tbody>
            </table>
        </div>
    </div>
</div>

<style type="text/css">
.table_data td {
    vertical-align: middle;
    text-align: center;
}
</style>


<style type="text/css">
    .ui-dialog .ui-dialog-content{
        padding: 3px;
    }

    .showtooltip {
        display:none;
        position:absolute;
        border:1px solid #333;
        background-color:#161616;
        border-radius:5px;
        padding:10px;
        color:#fff;
        font-size:12px Arial;
    }
    
    .ok{
        color: green;
        float: right;
    }
    .no{
        color: red;
    }


.table_data td {
    font-size: 13px;
}
.ui-front {
  z-index: 1031;
}

</style>



<style type="text/css">
    #ui-datepicker-div{
        font-size: 13px;
    }
</style>
<script type="text/javascript">
    $(function() {
    var pickerOpts = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#ketthuc" ).datepicker( "option", "minDate", selectedDate );

         },
         
    };  
    $("#batdau").datepicker(pickerOpts);

    var pickerOpts4 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#batdau" ).datepicker( "option", "maxDate", selectedDate );
                
         },
         
    };  
    $("#ketthuc").datepicker(pickerOpts4);
              
            
    
});

$('.vehicle').toggle(function(){
    var val = $(this).attr('id');
    $('.vehicle_'+val).show();
},function(){
    var val = $(this).attr('id');
    $('.vehicle_'+val).hide();
});

$('.romooc').toggle(function(){
    var val = $(this).attr('id');
    $('.romooc_'+val).show();
},function(){
    var val = $(this).attr('id');
    $('.romooc_'+val).hide();
});

var x = "<?php echo $xe ?>";
$('#sl_vehicle option[value='+x+']').attr('selected','selected');

var m = "<?php echo $mooc ?>";
$('#sl_status option[value='+m+']').attr('selected','selected');


$(document).ready(function () {
    $("#btnExport2").click(function () {
        $("#tblExport2").battatech_excelexport({
            containerid: "tblExport2"
           , datatype: 'table'
        });
    });
});


jQuery(document).ready(function() {
    jQuery('.tabs .tab-links a').on('click', function(e)  {
        var currentAttrValue = jQuery(this).attr('href');

        var id = currentAttrValue.replace('#tab','');
        $('.tab_active').val(id);
        // Show/Hide Tabs
        jQuery('.tabs ' + currentAttrValue).addClass('active').siblings().removeClass('active');
        jQuery('.tabs ' + currentAttrValue).slideDown(300).siblings().slideUp(300);

 
        // Change/remove current tab to active
        jQuery(this).parent('li').addClass('active').siblings().removeClass('active');
 
        e.preventDefault();
    });

    jQuery('.tabs .tab-left a').on('click', function(e)  {
        var currentAttrValue = jQuery(this).attr('href');
 
        // Show/Hide Tabs
        jQuery('.tabs ' + currentAttrValue).addClass('active').siblings().removeClass('active');
        jQuery('.tabs ' + currentAttrValue).slideDown(300).siblings().slideUp(300);
 
        // Change/remove current tab to active
        jQuery(this).parent('li').addClass('active').siblings().removeClass('active');
 
        e.preventDefault();
    });
});
</script>
