<?php
$url_order = 'ASC';
if ($order_by == 'bank_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'bank_code')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'bank_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'account_number')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

    $i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>
<section class="content-header">
    <h1>TIỀN MẶT - NGÂN HÀNG</h1>
  <ol class="breadcrumb">
    <li><a href="<?php echo $this->url('admin') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><a href="<?php echo $this->url('bank') ?>">Tài khoản</a></li>
  </ol>
</section>
<div id="content" style="padding:5px;">

    <div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
        <?php if(!isset($disable_control)){ ?>
        <div class="add-box"><a class="add_button" id="btnExport" ><i class="fa fa-download"></i> Xuất</a></div>
        <div class="add-box"><a class="add_button" onClick="add_click();"><i class="fa fa-plus"></i> Thêm mới</a></div>
        <?php } ?>
    </div>
    <div class="tablenav top">
        <?php if(!isset($disable_control)){ ?>
        <div class="alignleft actions">
            <select name="action" id="action">
                <option value="-1" selected="selected">Chọn</option>
                
                <option value="delete">Xóa</option>
            </select>
            <input type="button" name="" id="doaction" class="button action" value="Áp dụng" onclick="action();">
        </div>
        <?php } ?>
        <div class="alignleft actions">
        <select name="m" id="chonloc">
          <option  value="18446744073709">Hiển thị tất cả</option>
          <option value="50">Hiển thị 50 giá trị</option>
                <option value="100">Hiển thị 100 giá trị</option>
                <option value="150">Hiển thị 150 giá trị</option>
                <option selected="selected" value="200">Hiển thị 200 giá trị</option>
        </select>
        <input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">                               
        </div>

      </div>

</div>


<table class="table_data" id="tblExport">
<thead>
    <tr>
        <th class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
        <th  class="fix" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','bank_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'bank_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','bank_code','<?php echo $url_order ?>')">Mã tài khoản <?php if ($order_by == 'bank_code'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','bank_name','<?php echo $url_order ?>')">Tên tài khoản <?php if ($order_by == 'bank_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','account_number','<?php echo $url_order ?>')">Số tài khoản <?php if ($order_by == 'account_number'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','account_bank','<?php echo $url_order ?>')">Tên ngân hàng <?php if ($order_by == 'account_bank'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','account_bank_branch','<?php echo $url_order ?>')">Chi nhánh <?php if ($order_by == 'account_bank_branch'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <?php if(!isset($disable_control)){ ?>
        <th class="fix"></th>
        <?php } ?>
    </tr>
    
   </thead>
   <tbody>
    <?php foreach ($banks as $bank) : ?>
    
        
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $bank->bank_id ?>" class="edit_tr" >
            
            <td>
                <input name="check[]" type="checkbox" class="checkbox" value="<?php echo $bank->bank_id ?>">
            </td>
            
            <td  class="fix"><?php echo $i++; ?></td>
            <td class="fix" id="bank_code_<?php echo $bank->bank_id; ?>"><?php echo $bank->bank_code; ?></td>
            <td class="fix" id="bank_name_<?php echo $bank->bank_id; ?>"><?php echo $bank->bank_name; ?></td>
            <td class="fix" id="account_number_<?php echo $bank->bank_id; ?>"><?php echo $bank->account_number; ?></td>
            <td class="fix" id="account_bank_<?php echo $bank->bank_id; ?>"><?php echo $bank->account_bank; ?></td>
            <td class="fix" id="account_bank_branch_<?php echo $bank->bank_id; ?>"><?php echo $bank->account_bank_branch; ?></td>
            
            
            <?php if(!isset($disable_control)){ ?>
            <td class="pull-right">
                <button class="btn btn-sm btn-flat btn-primary"><i class="fa fa-edit"></i> Sửa</button>
                <button class="btn btn-sm btn-flat btn-danger" onclick="del(<?php echo $bank->bank_id ?>)" ><i class="fa fa-remove"></i> Xóa</button>
            </td>
            <?php } ?>
        </tr>


    <?php endforeach; ?>
     
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>

<div class="add-field">
    <section class="content">
      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
            <!-- /.box-header -->
            <!-- form start -->
            <form id="add_bank" role="form" method="post" action="" enctype="multipart/form-data">
              <div class="row">
                <div class="col-md-4 col-xs-6">
                  <div class="box-body">
                    <div class="form-group">
                      <label for="bank_code">Mã tài khoản </label>
                      <input  type="text" id="bank_code"  name="bank_code" tabindex="1"  required="required" >
                    </div>
                    <div class="form-group">
                      <label for="account_bank">Ngân hàng </label>
                      <input  type="text" id="account_bank"  name="account_bank" tabindex="4"  >
                    </div>
                  </div>
                  <!-- /.box-body -->
                  
                </div>
                <div class="col-md-4 col-xs-6">
                  <div class="box-body">
                    <div class="form-group">
                      <label for="bank_name">Tên tài khoản</label>
                      <input   type="text" id="bank_name"  name="bank_name" tabindex="2"  required="required" >
                    </div>
                    <div class="form-group">
                      <label for="account_bank_branch">Chi nhánh </label>
                      <input  type="text" id="account_bank_branch"  name="account_bank_branch" tabindex="5"  >
                    </div>
                  </div>
                  <!-- /.box-body -->
                  
                </div>
                <div class="col-md-4 col-xs-6">
                  <div class="box-body">
                    <div class="form-group">
                      <label for="account_number">Số tài khoản</label>
                      <input   type="text" id="account_number"  name="account_number" tabindex="3"   >
                    </div>
                    
                  </div>
                  <!-- /.box-body -->
                  
                </div>
                

              </div>
              <?php if(!isset($disable_control)){ ?>
              <div class="row">
                <div class="col-md-12">
                    <div class="box-footer">
                    <input type="hidden" readonly id="yes" name="yes" required="required" >
                    <button type="submit" class="btn btn-primary" tabindex="6">Hoàn thành</button>
                    <button type="reset" class="btn" tabindex="7">Nhập lại</button>
                  </div>
                  <div class="box-footer">
                    <div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>
                  </div>
                </div>
              </div>
              <?php } ?>
            </form>
          </div>
          <!-- /.box -->

        </div>
        <!--/.col (left) -->
        
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
       
</div>

<script type="text/javascript">


  
$('.add-field').hide();  



    $('.edit_tr').click(function(e){
        if(e.target != '[object HTMLButtonElement]' && e.target != '[object HTMLSpanElement]' && !$('.checkbox').is(':focus')) { 
            if(!$('.checkbox').is(':focus')){
                $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);
            }
            
            var bank_code = $(this).find("#bank_code_"+$(this).attr('id')).text();
            var bank_name = $(this).find("#bank_name_"+$(this).attr('id')).text();
            var account_number = $(this).find("#account_number_"+$(this).attr('id')).text();
            var account_bank = $(this).find("#account_bank_"+$(this).attr('id')).text();
            var account_bank_branch = $(this).find("#account_bank_branch_"+$(this).attr('id')).text();

            //alert(cost_code);
            $('#yes').val($(this).attr('id'));
            $('#bank_code').val(bank_code);
            $('#bank_name').val(bank_name);
            $('#account_number').val(account_number);
            $('#account_bank').val(account_bank);
            $('#account_bank_branch').val(account_bank_branch);

            $( ".add-field" ).dialog( "open" );
        }

        
        
    });


</script>
<script type="text/javascript">

function add_click(){
    $('#yes').val("");
    $('.add-field').slideDown(500);
     $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);   
     
        $('#bank_code').val("");
        $('#bank_name').val("");
        $('#account_number').val("");
          $('#account_bank').val("");
          $('#account_bank_branch').val("");
                
        $('.numbers').focus(function(){
            if ( $(this).val() == '0') {
               $(this).val(""); 
            };
            
        });
        $('.numbers').blur(function(){
            if ( $(this).val() == "") {
                $(this).val(0);
            };
            
        });

    $( ".add-field" ).dialog( "open" );
}


$(document).ready(function(){
            // Validate form
            $("#add_bank").validate({
                errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
                rules: {
                    
                },
                submitHandler: function(form) {
                
                    var bank_code = $('#bank_code').attr('value');
                    var bank_name = $('#bank_name').attr('value');
                    var account_number = $('#account_number').attr('value');
                    var account_bank_branch = $('#account_bank_branch').attr('value');
                    var account_bank = $('#account_bank').attr('value');
                    
                    var yes = $('#yes').attr('value');
                    
                    var action      = "them";
                 
                    $.ajax({
                        type: "POST", // phương thức gởi đi
                        url: "<?php echo BASE_URL ?>/bank/add", // nơi mà dữ liệu sẽ chuyển đến khi submit
                        data: {
                            
                            bank_code: bank_code,
                            bank_name: bank_name,
                            account_number: account_number,
                            account_bank_branch: account_bank_branch,
                            account_bank: account_bank,
                            yes: yes,

                            }, // giá trị post
                        success: function(answer){ // if everything goes well
                            //alert(answer);
                            $('#error').hide();
                            $('#error').slideToggle(100); // hiển thị thẻ div success
                            $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                            $('#error').fadeOut(10000);

                            if (yes != "") {
                                if (answer.trim() != "Tài khoản đã tồn tại") {
                                    setTimeout(function() {
                                            sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                          }, 200);
                                }
                            }
                            else{
                                if (answer.trim() != "Tài khoản đã tồn tại") {
                                    setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);
                                }
                                
                            }
                        }
                    });
                    return false;
                     
                 }
            });




   $('.numbers').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-.]/g, "")
          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
        ;
      });
    });

    $('.number').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-]/g, "")
        ;
      });
    });
    

});

function get_number(id){
    return $(id).val().replace(/\,/g,'');
}
function set_item(item,name) {
    // change input value
    $('#work_code').val(item);
    $("#work_code").attr("data",name);
    
    $('#code_list_id').hide();
    $('#work_code').focus();
}

</script>
<div style="display:none" id="lasted"></div>
<script type="text/javascript">
    var count = parseInt(<?php echo $lastID ?>);
    $('#lasted').html(count);

$("#import_excel").click(function(){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:300,
            width:400,
            resizable: false,
            title:'Import Excel',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        return false;
    });


 
var x = "<?php echo $limit ?>";
$('#chonloc option[value='+x+']').attr('selected','selected');


</script>
</div>

<script type="text/javascript">


$( ".add-field" ).dialog({
    autoOpen: false,
    modal: true,
    width: "auto",
    title: "Danh mục chi phí",
    hide: 'fold',
    show: 'blind'
});



$(".show").click(function(){
    $("#winpopup").dialog({
        draggable:true,
        modal: true,
        autoOpen: false,
        width: "90%",
        resizable: false,
        position: "top",
        title:'Chi tiết',
        buttons: {
            OK: function() {
                $( this ).dialog( "close" );
            },
            Cancel: function() {
                $( this ).dialog( "close" );
            }
        }
    });
    $("#winpopup").load($(this).attr('href'));
    $("#winpopup").dialog("open");
    return false;
});

</script>

