
<script type="text/javascript">
$(document).ready(function(){
	$('#import').ace_file_input({
          style: 'well',
          btn_choose: 'Drop files here or click to choose',
          btn_change: null,
          no_icon: 'ace-icon fa fa-cloud-upload',
          droppable: true,
          thumbnail: 'small',//large | fit
          allowExt: ["xls", "xlsx"],
          allowMime: ["application/vnd.ms-excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"]
          //,icon_remove:null//set null, to hide remove/reset button
          /**,before_change:function(files, dropped) {
            //Check an example below
            //or examples/file-upload.html
            return true;
          }*/
          /**,before_remove : function() {
            return true;
          }*/
          ,
          preview_error : function(filename, error_code) {
            //name of the file that failed
            //error_code values
            //1 = 'FILE_LOAD_FAILED',
            //2 = 'IMAGE_LOAD_FAILED',
            //3 = 'THUMBNAIL_FAILED'
            //alert(error_code);
          }
      
        }).on('change', function(){
          //console.log($(this).data('ace_input_files'));
          //console.log($(this).data('ace_input_method'));
        });

			// Validate form
			$("#add").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
        ignore: "",
        rules: {
        },
        errorPlacement: function (error, element) {
          if(element.is('input[type=checkbox]') || element.is('input[type=radio]')) {
            var controls = element.closest('div[class*="col-"]');
            if(controls.find(':checkbox,:radio').length > 1) controls.append(error);
            else error.insertAfter(element.nextAll('.lbl:eq(0)').eq(0));
          }
          else if(element.is('.select2')) {
            error.insertAfter(element.siblings('[class*="select2-container"]:eq(0)'));
          }
          else if(element.is('.chosen-select')) {
            error.insertAfter(element.siblings('[class*="chosen-container"]:eq(0)'));
          }
          else error.insertAfter(element.parent());
        },
        submitHandler: function(form) {  
          var formData = new FormData($("#add")[0]);
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/checkingcost/importcheckingcost", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: formData, // giá trị post
              cache: false,
              contentType: false,
              processData: false,
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('.ace-file-input .remove').click();
                  
                  $('#error').hide();
                  $('#error').slideToggle(100); // hiển thị thẻ div success
                  $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error').fadeOut(10000);
              }
          });
          return false;
           
       }
					 
				 
			});
	
});
</script>
<div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>
<div class="login_body">
  <form id="add" method="post" action="" enctype="multipart/form-data">
    <div class="form-group">
      <div class="col-xs-12">
        <input multiple="" type="file" id="import" name="import[]" required="required" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" />
      </div>
    </div>
  </form>   
</div>  



