
<?php

$url_order = 'ASC';

if ($order_by == 'road_cost_id')

    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';



elseif ($order_by == 'road_cost_date')

    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

elseif ($order_by == 'road_cost_number')

    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';


elseif ($order_by == 'road_cost_vat')

    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'road_cost_price')

    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

elseif ($order_by == 'start_time')

    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

elseif ($order_by == 'end_time')

    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';


    $ii = $sonews*$page-($sonews-1);



?>



<div id="loading"></div>

<div id="winpopup"></div>

<section class="content-header">

    <h1>PHÍ SỬ DỤNG ĐƯỜNG BỘ</h1>

  <ol class="breadcrumb">

    <li><a href="<?php echo $this->url('admin') ?>"><i class="fa fa-dashboard"></i> Home</a></li>

    <li class="active"><a href="<?php echo $this->url('roadcostlist') ?>">Phí sử dụng đường bộ</a></li>

  </ol>

</section>

<div id="content" style="padding:5px;">



    <div class="search-box">

        

        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">

        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">

        <?php if(!isset($disable_control)){ ?>

        <div class="add-box"><a class="add_button" id="btnExport" ><i class="fa fa-download"></i> Xuất</a></div>

        <?php } ?>

    </div>

    <div class="tablenav top">

        <div class="add-box">

            <select id="sl_round" name="sl_round" style="width:90px">

             <?php 

                for ($k=1; $k < 13; $k++) { 

                    echo '<option value="'.$k.'">Tháng '.$k.'</option>';

                }

             ?>

            </select>

            <select id="sl_staff" name="sl_staff" style="width:100px">

             <?php 

                $nam = date('Y');

                for ($k=($nam-5); $k < ($nam+5); $k++) { 

                    echo '<option value="'.$k.'">Năm '.$k.'</option>';

                }

             ?>

            </select>



            <input type="button" name="xem" id="xem" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  

            

        </div>

    </div>

    <div class="tablenav top">

        <div style="clear:both"></div>

        <div class="add-box">

                  

            Từ  <input style="width:80px" type="search" name="batdau" id="batdau" placeholder="Chọn ngày" <?php if(isset($batdau)) echo "value='$batdau'"; ?> >  

            Đến  <input style="width:80px" type="search" name="ketthuc" id="ketthuc" placeholder="Chọn ngày" <?php if(isset($ketthuc)) echo "value='$ketthuc'"; ?> >  

             <input type="button" name="xem" id="xem" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  

            

        </div>



      </div>

      <div class="tablenav top">

        <div style="clear:both"></div>

        

        <div class="add-box">

            <input type="button" name="chon" id="chon" value="Chọn" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  

        </div>

        
        <div class="add-box" style="margin-right: 5px">
            <select name="sl_nv" id="sl_nv">
                <option selected="selected" value="">Mooc</option>
                <?php foreach ($romoocs as $sm) { ?>
                <option value="<?php echo $sm->romooc_id ?>"><?php echo $sm->romooc_number ?></option>
                <?php } ?>
            </select>

            
            
        </div>
        <div class="add-box" style="margin-right: 5px">


            <select style="width:120px" name="sl_vehicle" id="sl_vehicle">

                <option value="0">Xe</option>

                <?php foreach ($vehicles as $sm) { ?>

                <option value="<?php echo $sm->vehicle_id ?>"><?php echo $sm->vehicle_number ?></option>

                <?php } ?>

            </select>



            

            

        </div>
        <div class="alignleft actions">

        <select name="m" id="chonloc" style="width:200px">

            <option value="18446744073709">Hiển thị tất cả</option>

            <option value="50">Hiển thị 50 giá trị</option>

            <option value="100">Hiển thị 100 giá trị</option>

            <option value="150">Hiển thị 150 giá trị</option>

            <option value="200">Hiển thị 200 giá trị</option>

            <option selected="selected" value="250">Hiển thị 250 giá trị</option>

        </select>

        <input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">                               

        </div>



      </div>

</div>





<table class="table_data" id="tblExport">

<thead>

    <tr>

    	<th class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>

        <th  class="fix" >

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','road_cost_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'road_cost_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>

        

        <th  class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','road_cost_date','<?php echo $url_order ?>')">Ngày <?php if ($order_by == 'road_cost_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>

        <th  class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','road_cost_number','<?php echo $url_order ?>')">Số hóa đơn <?php if ($order_by == 'road_cost_number'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>

        <th  class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','road_cost_comment','<?php echo $url_order ?>')">Nội dung <?php if ($order_by == 'road_cost_comment'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>

        <th  class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','vehicle','<?php echo $url_order ?>')">Số xe <?php if ($order_by == 'vehicle'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>

        <th  class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','romooc','<?php echo $url_order ?>')">Mooc <?php if ($order_by == 'romooc'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>


        <th  class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','road_cost_price','<?php echo $url_order ?>')">Chi phí <?php if ($order_by == 'road_cost_price'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>
        <th  class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','road_cost_vat','<?php echo $url_order ?>')">Thuế GTGT <?php if ($order_by == 'road_cost_vat'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>
        <th  class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','start_time','<?php echo $url_order ?>')">Hiệu lực từ <?php if ($order_by == 'start_time'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>
        <th  class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','end_time','<?php echo $url_order ?>')">Hết hiệu lực <?php if ($order_by == 'end_time'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>

    </tr>

    

   </thead>

   <tbody>

    <?php 
      $tongthanhtien = 0; $tongvat = 0;
    foreach ($road_costs as $road_cost) : 

      $arr_vehicle = explode(',', $road_cost->vehicle);
      $arr_romooc = explode(',', $road_cost->romooc);

      if ($road_cost->vehicle == "") {
          $arr_vehicle = array();
      }
      if ($road_cost->romooc == "") {
          $arr_romooc = array();
      }

      $k=0;
      if ($xe > 0) {
        $arr_romooc = array();
        foreach ($arr_vehicle as $key) {
          if ($key != $xe){
            unset($arr_vehicle[$k]);
          }
          $k++;
        }
      }

      $k=0;
      if ($romooc > 0) {
        $arr_vehicle = array();
        foreach ($arr_romooc as $key) {
          if ($key != $romooc){
            unset($arr_romooc[$k]);
          }
          $k++;
        }
      }

      foreach ($arr_vehicle as $key) {

      $thanhtien = round($road_cost->road_cost_price/$road_cost->total_number);
      $vat = round($road_cost->road_cost_vat/$road_cost->total_number);

      $tongthanhtien += $thanhtien;
      $tongvat += $vat;
    ?>


        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $road_cost->road_cost_id ?>" class="edit_tr">

        	<td><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $road_cost->road_cost_id ?>"></td>

            <td  class="fix"><?php echo $ii++; ?></td>

            <td class="fix" id="road_cost_date_<?php echo $road_cost->road_cost_id; ?>"><?php echo $lib->hien_thi_ngay_thang($road_cost->road_cost_date); ?></td>
            <td class="fix" id="road_cost_number_<?php echo $road_cost->road_cost_id; ?>"><a target="_blank" href="<?php echo $this->url('roadcost/index/'.$road_cost->road_cost_id) ?>" ><?php echo $road_cost->road_cost_number; ?></a></td>
            <td class="fix" id="road_cost_comment_<?php echo $road_cost->road_cost_id; ?>"><?php echo $road_cost->road_cost_comment; ?></td>
            <td class="fix" id="vehicle_<?php echo $road_cost->road_cost_id; ?>"><a target="_blank" href="<?php echo $this->url('vehicle/index/'.$key) ?>" ><?php echo isset($vehicle_data['id'][$key])?$vehicle_data['name'][$key]:null; ?></a></td>
            <td class="fix" id="romooc_<?php echo $road_cost->road_cost_id; ?>"></td>

            <td class="fix" id="road_cost_price_<?php echo $road_cost->road_cost_id; ?>"><?php echo $lib->formatMoney($thanhtien); ?></td>

            <td class="fix" id="road_cost_vat_<?php echo $road_cost->road_cost_id; ?>"><?php echo $lib->formatMoney($vat); ?></td>

            <td class="fix" id="start_time_<?php echo $road_cost->road_cost_id; ?>"><?php echo $lib->hien_thi_ngay_thang($road_cost->start_time); ?></td>

            <td class="fix" id="end_time_<?php echo $road_cost->road_cost_id; ?>"><?php echo $lib->hien_thi_ngay_thang($road_cost->end_time); ?></td>

        </tr>

      <?php } 
      foreach ($arr_romooc as $key) {

      $thanhtien = round($road_cost->road_cost_price/$road_cost->total_number);
      $vat = round($road_cost->road_cost_vat/$road_cost->total_number);

      $tongthanhtien += $thanhtien;
      $tongvat += $vat;
      ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $road_cost->road_cost_id ?>" class="edit_tr">

          <td><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $road_cost->road_cost_id ?>"></td>

            <td  class="fix"><?php echo $ii++; ?></td>

            <td class="fix" id="road_cost_date_<?php echo $road_cost->road_cost_id; ?>"><?php echo $lib->hien_thi_ngay_thang($road_cost->road_cost_date); ?></td>
            <td class="fix" id="road_cost_number_<?php echo $road_cost->road_cost_id; ?>"><a target="_blank" href="<?php echo $this->url('roadcost/index/'.$road_cost->road_cost_id) ?>" ><?php echo $road_cost->road_cost_number; ?></a></td>
            <td class="fix" id="road_cost_comment_<?php echo $road_cost->road_cost_id; ?>"><?php echo $road_cost->road_cost_comment; ?></td>
            <td class="fix" id="vehicle_<?php echo $road_cost->road_cost_id; ?>"></td>
            <td class="fix" id="romooc_<?php echo $road_cost->road_cost_id; ?>"><a target="_blank" href="<?php echo $this->url('romooc/index/'.$key) ?>" ><?php echo isset($romooc_data['id'][$key])?$romooc_data['name'][$key]:null; ?></td>

            <td class="fix" id="road_cost_price_<?php echo $road_cost->road_cost_id; ?>"><?php echo $lib->formatMoney($thanhtien); ?></td>

            <td class="fix" id="road_cost_vat_<?php echo $road_cost->road_cost_id; ?>"><?php echo $lib->formatMoney($vat); ?></td>

            <td class="fix" id="start_time_<?php echo $road_cost->road_cost_id; ?>"><?php echo $lib->hien_thi_ngay_thang($road_cost->start_time); ?></td>

            <td class="fix" id="end_time_<?php echo $road_cost->road_cost_id; ?>"><?php echo $lib->hien_thi_ngay_thang($road_cost->end_time); ?></td>

        </tr>
      <?php } ?>

    <?php endforeach; ?>

        <tr  style="font-weight: bold; color: rgb(23, 119, 226);" >
            
            <th colspan="7" style="border-right: 1px solid rgb(236, 235, 235);border-top: 1px solid #80C8E5;padding: 7px; text-align: right;" >
                Tổng cộng
            </th>
            <td class="fix" ><?php echo $lib->formatMoney($tongthanhtien) ?></td>
            <td class="fix" ><?php echo $lib->formatMoney($tongvat) ?></td>
            <td class="fix" ></td>
            <td class="fix" ></td>
        </tr>

   </tbody>

</table>

<?php

$this->helper('slidePaginator');

?>


<style type="text/css">

    #ui-datepicker-div{

        font-size: 13px;

    }

</style>

<script type="text/javascript">

    $(function() {

    var pickerOpts = {

        closeText: "Đóng",

        currentText: "Hiện tại",

        nextText: "Tiếp",

        prevText: "Quay lại",

        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",

        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],

        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",

        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],

        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",

        "Thứ sáu", "Thứ bảy"],

        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",

        "T6", "T7"],

        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",

        "T6", "T7"],

        //defaultDate: "+1w",

        changeMonth: true,

        changeYear: true,

        dateFormat: 'dd-mm-yy',

        firstDay: 1,

        isRTL: false,

        showButtonPanel: true,

        onClose: function(selectedDate) {

                

                $( "#ketthuc" ).datepicker( "option", "minDate", selectedDate );



         },

         

    };  

    $("#batdau").datepicker(pickerOpts);



    var pickerOpts2 = {

        closeText: "Đóng",

        currentText: "Hiện tại",

        nextText: "Tiếp",

        prevText: "Quay lại",

        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",

        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],

        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",

        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],

        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",

        "Thứ sáu", "Thứ bảy"],

        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",

        "T6", "T7"],

        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",

        "T6", "T7"],

        //defaultDate: "+1w",

        changeMonth: true,

        changeYear: true,

        dateFormat: 'dd-mm-yy',

        firstDay: 1,

        isRTL: false,

        showButtonPanel: true,

        onClose: function(selectedDate) {

                

                $( "#batdau" ).datepicker( "option", "maxDate", selectedDate );

                

         },

         

    };  

    $("#ketthuc").datepicker(pickerOpts2);

              

            
    var pickerOpts3 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+5",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onSelect: function(dateStr) {
          if ($('#end_time').val()=="") {
            var d = $.datepicker.parseDate('dd-mm-yy', dateStr);
            var years = parseInt(1, 10);

            d.setFullYear(d.getFullYear() + years);

            $('#end_time').datepicker('setDate', d);
          }
            
        },
        onClose: function(selectedDate) {
                
                $( "#end_time" ).datepicker( "option", "minDate", selectedDate );

         },
    }; 
    $("#start_time").datepicker(pickerOpts3);

    var pickerOpts4 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+5",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#start_time" ).datepicker( "option", "maxDate", selectedDate );

         },
    }; 
    $("#end_time").datepicker(pickerOpts4);
    

});



var ch = "<?php echo $limit ?>";

$('#chonloc option[value='+ch+']').attr('selected','selected');



var xe = "<?php echo $xe ?>";

$('#sl_vehicle option[value='+xe+']').attr('selected','selected');

var m = "<?php echo $romooc ?>";
$('#sl_nv option[value='+m+']').attr('selected','selected');



var v = "<?php echo $vong ?>";

$('#sl_round option[value='+v+']').attr('selected','selected');



var tt = "<?php echo $trangthai ?>";

$('#sl_staff option[value='+tt+']').attr('selected','selected');



</script>

<script type="text/javascript">

    

    $('#sl_round').change(function(){

        var m = $(this).val();

        var y = $('#sl_staff').val();

        var firstDay = new Date(y, m-1, 1);

        var lastDay = new Date(y, m, 0);



        $('#batdau').datepicker("setDate", firstDay );

        $('#ketthuc').datepicker("setDate", lastDay );



    });



    $('#sl_staff').change(function(){

        var y = $(this).val();

        var m = $('#sl_round').val();

        var firstDay = new Date(y, m-1, 1);

        var lastDay = new Date(y, m, 0);



        $('#batdau').datepicker("setDate", firstDay );

        $('#ketthuc').datepicker("setDate", lastDay );



    });


$('#sl_vehicle').change(function(){
  $('#sl_nv option[value=""]').attr('selected','selected');
});
$('#sl_nv').change(function(){
  $('#sl_vehicle option[value=""]').attr('selected','selected');
});

</script>