<link rel="stylesheet" type="text/css" href="<?php BASE_URL ?>/public/css/jquery.multiselect.css" />
<script type="text/javascript" src="<?php BASE_URL ?>/public/js/jquery.multiselect.js"></script>
<?php
$url_order = 'ASC';
if ($order_by == 'export_stock_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'export_stock_code')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'export_stock_date')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'export_stock_total')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'export_stock_price')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'username')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';


    $i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>
<section class="content-header">
    <h1>XUẤT KHO</h1>
  <ol class="breadcrumb">
    <li><a href="<?php echo $this->url('admin') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><a href="<?php echo $this->url('exportstock') ?>">Xuất kho</a></li>
  </ol>
</section>
<div id="content" style="padding:5px;">

    <div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
        <?php if(!isset($disable_control)){ ?>
        <div class="add-box"><a class="add_button" id="export_excel" href="<?= $this->url('exportstock/export/'.strtotime($batdau).'/'.strtotime($ketthuc))?>" ><i class="fa fa-download"></i> Xuất</a></div>
        <div class="add-box"><a class="add_button" onClick="add_click();"><i class="fa fa-plus"></i> Thêm mới</a></div>
        <?php } ?>
    </div>
    <div class="tablenav top">
        <div class="add-box">
            <select id="sl_round" name="sl_round" style="width:90px">
             <?php 
                for ($k=1; $k < 13; $k++) { 
                    echo '<option value="'.$k.'">Tháng '.$k.'</option>';
                }
             ?>
            </select>
            <select id="sl_staff" name="sl_staff" style="width:100px">
             <?php 
                $nam = date('Y');
                for ($k=($nam-5); $k < ($nam+5); $k++) { 
                    echo '<option value="'.$k.'">Năm '.$k.'</option>';
                }
             ?>
            </select>

            <input type="button" name="xem" id="xem" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  
            
        </div>
    </div>
    <div class="tablenav top">
        <div style="clear:both"></div>
        <div class="add-box">
                  
            Từ  <input style="width:80px" type="search" name="batdau" id="batdau" placeholder="Chọn ngày" <?php if(isset($batdau)) echo "value='$batdau'"; ?> >  
            Đến  <input style="width:80px" type="search" name="ketthuc" id="ketthuc" placeholder="Chọn ngày" <?php if(isset($ketthuc)) echo "value='$ketthuc'"; ?> >  
             <input type="button" name="xem" id="xem" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  
            
        </div>

      </div>
    <div class="tablenav top">
        <?php if(!isset($disable_control)){ ?>
        <div class="alignleft actions">
            <select name="action" id="action">
                <option value="-1" selected="selected">Chọn</option>
                
                <option value="delete">Xóa</option>
            </select>
            <input type="button" name="" id="doaction" class="button action" value="Áp dụng" onclick="action();">
        </div>
        <?php } ?>
        <div class="alignleft actions">
        <select name="m" id="chonloc">
            <option  value="18446744073709">Hiển thị tất cả</option>
            <option value="50">Hiển thị 50 giá trị</option>
            <option value="100">Hiển thị 100 giá trị</option>
            <option value="150">Hiển thị 150 giá trị</option>
            <option selected="selected" value="200">Hiển thị 200 giá trị</option>
        </select>
        <input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">                               
        </div>

      </div>

</div>

<input type="hidden" value="<?php echo $tab_active ?>" id="sl_tha">

<div class="tabs">
  <ul class="tab-links">
    <?php foreach ($houses as $house) { ?>
    <li <?php echo $tab_active==$house->house_id?'class="active"':null ?> ><a href="#tab<?php echo $house->house_id ?>"><?php echo $house->house_name ?></a></li>
    <?php } ?>
  </ul>
  <div class="tab-content">
    <?php foreach ($houses as $house) { ?>
    <div class="tab <?php echo $tab_active==$house->house_id?"active":null ?>" id="tab<?php echo $house->house_id ?>" >
      <table class="table_data" id="tblExport<?php echo $house->house_id ?>">
        <thead>
            <tr>
                <th class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
                <th class="fix">
                    <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','export_stock_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'export_stock_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                </th>
                <th  class="fix">
                    <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','export_stock_code','<?php echo $url_order ?>')">Phiếu xuất kho <?php if ($order_by == 'export_stock_code'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                </th>
                <th  class="fix">
                    <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','export_stock_date','<?php echo $url_order ?>')">Ngày <?php if ($order_by == 'export_stock_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                </th>
                <th  class="fix">
                    <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','export_stock_total','<?php echo $url_order ?>')">Số lượng <?php if ($order_by == 'export_stock_total'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                </th>
                <th  class="fix">
                    <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','export_stock_price','<?php echo $url_order ?>')">Giá trị <?php if ($order_by == 'export_stock_price'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                </th>
                <th  class="fix">
                    <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','export_stock_comment','<?php echo $url_order ?>')">Nội dung <?php if ($order_by == 'export_stock_comment'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                </th>
                <th  class="fix">
                    <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','username','<?php echo $url_order ?>')">Người lập <?php if ($order_by == 'username'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                </th>
                
                   
                <?php if(!isset($disable_control)){ ?>
                   
                <th  class="fix">&nbsp;</th>
                <?php } ?>
            </tr>
            
           </thead>
           <tbody>
            <?php $tong = 0;
            foreach ($exports[$house->house_id] as $export_stock) : 
              $tong += $export_stock->export_stock_total;
              ?>
                <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $export_stock->export_stock_id ?>" class="edit_tr">
                    <td><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $export_stock->export_stock_id ?>"></td>
                    <td class="fix"><?php echo $i++; ?></td>
                    <td class="fix"  id="export_stock_code_<?php echo $export_stock->export_stock_id; ?>"><?php echo $export_stock->export_stock_code ?></td>
                    <td class="fix" id="export_stock_date_<?php echo $export_stock->export_stock_id; ?>"><?php echo $lib->hien_thi_ngay_thang($export_stock->export_stock_date) ?></td>
                    <td class="fix"  id="export_stock_total_<?php echo $export_stock->export_stock_id; ?>"><?php echo $export_stock->export_stock_total ?></td>
                    <td class="fix"  id="export_stock_price_<?php echo $export_stock->export_stock_id; ?>"><?php echo $lib->formatMoney($export_stock->export_stock_price) ?></td>
                    <td class="fix"  id="export_stock_comment_<?php echo $export_stock->export_stock_id; ?>"><?php echo $export_stock->export_stock_comment ?></td>
                    <td class="fix"  id="username_<?php echo $export_stock->export_stock_id; ?>"><?php echo $export_stock->username ?></td>

                    <td class="fix" style="display:none" data="<?php echo $export_stock->steersman ?>"  id="steersman_<?php echo $export_stock->export_stock_id; ?>"><?php echo $export_stock->steersman_name ?></td>
                    <td class="fix" style="display:none" data="<?php echo $export_stock->house ?>" id="house_<?php echo $export_stock->export_stock_id; ?>"><?php echo $export_stock->house_name ?></td>
                    <td class="fix" style="display:none" id="vehicle_<?php echo $export_stock->export_stock_id; ?>"><?php echo $export_stock->vehicle ?></td>
                    <td class="fix" style="display:none" id="romooc_<?php echo $export_stock->export_stock_id; ?>"><?php echo $export_stock->romooc ?></td>
                
                    <?php if(!isset($disable_control)){ ?>
                    <td class="pull-right">
                        <button class="btn btn-sm btn-flat btn-primary"><i class="fa fa-edit"></i> Sửa</button>
                        <button class="btn btn-sm btn-flat btn-danger" onclick="del(<?php echo $export_stock->export_stock_id ?>)" ><i class="fa fa-remove"></i> Xóa</button>
                    </td>
                    <?php } ?>
                </tr>
            <?php endforeach; ?>
            <tr  style="font-weight: bold; color: rgb(23, 119, 226);" >
            
                <th colspan="4" style="border-right: 1px solid rgb(236, 235, 235);border-top: 1px solid #80C8E5;padding: 7px; text-align: right;" >
                    Tổng cộng
                </th>
                <td class="fix" ><?php echo $lib->formatMoney($tong) ?></td>
                <td class="fix" ></td>
                <td class="fix" ></td>
                <td class="fix" ></td>
            </tr>
           </tbody>
      </table>
    </div>
    <?php } ?>
  </div>
</div>

<?php
$this->helper('slidePaginator');
?>
<div class="add-field">
    <section class="content">
      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
            <!-- /.box-header -->
            <!-- form start -->
            <form id="add_export_stock" role="form" method="post" action="" enctype="multipart/form-data">
              <div class="row">
                <div class="col-md-4 col-xs-6">
                  <div class="box-body">
                    <div class="form-group">
                      <label for="export_stock_date">Ngày</label>
                      <input class="ngay" type="text" id="export_stock_date"  name="export_stock_date" tabindex="1" required="required" >
                    </div>
                    <div class="form-group">
                      <div class="col-md-6 col-xs-6">
                        <label for="vehicle">Xe <a title="Bàn giao xe" target="_blank" href="<?php echo $this->url('driver') ?>"><i class="fa fa-th-list"></i></a></label>
                        <select style="width:85px" name="vehicle" id="vehicle">
                          <option selected="selected" value="">Chọn</option>
                          <?php foreach ($vehicles as $sm) { ?>
                          <option value="<?php echo $sm->vehicle_id ?>"><?php echo $sm->vehicle_number ?></option>
                          <?php } ?>
                      </select>
                      </div>
                      <div class="col-md-6 col-xs-6">
                        <label for="romooc">Mooc</label>
                        <select style="width:85px" name="romooc" id="romooc">
                          <option selected="selected" value="">Chọn</option>
                          <?php foreach ($romoocs as $sm) { ?>
                          <option value="<?php echo $sm->romooc_id ?>"><?php echo $sm->romooc_number ?></option>
                          <?php } ?>
                      </select>
                      </div>
                    </div>
                    
                  </div>
                  <!-- /.box-body -->
                  
                </div>
                <div class="col-md-4 col-xs-6">
                  <div class="box-body">
                    <div class="form-group">
                      <label for="export_stock_code">Số phiếu</label>
                      <input type="text" id="export_stock_code"  name="export_stock_code" tabindex="2" required="required" >
                    </div>
                    <div class="form-group">
                      <label for="steersman">Người nhận <a target="_blank" title="Thêm tài xế" href="<?php echo $this->url('steersman') ?>"><i class="fa fa-plus"></i></a></label>
                      <input type="text" autocomplete="off" id="steersman"  name="steersman" tabindex="4"  placeholder="Nhập tên hoặc * để chọn" required="required" >
                        <ul id="customer_list_id"></ul>
                    </div>
                    
                  </div>
                  <!-- /.box-body -->
                  
                </div>
                <div class="col-md-4 col-xs-6">
                  <div class="box-body">
                    <div class="form-group">
                      <label for="export_stock_comment">Nội dung</label>
                      <input type="text" id="export_stock_comment"  name="export_stock_comment" tabindex="3" required="required" >
                    </div>
                    <div class="form-group">
                      <label for="house">Kho xuất <a target="_blank" title="Thêm kho" href="<?php echo $this->url('house') ?>"><i class="fa fa-plus"></i></a></label>
                      <select id="house" name="house" tabindex="5">
                        <?php foreach ($houses as $house) { ?>
                            <option value="<?php echo $house->house_id ?>"><?php echo $house->house_name.' ['.$house->house_place.']' ?></option>
                        <?php } ?>
                      </select>
                    </div>
                    
                  </div>
                  <!-- /.box-body -->
                  
                </div>

              </div>
              <div class="row">
                <div class="col-md-12">
                  <fieldset class="groupbox">
                    <legend>
                        <span><h3>Chi tiết</h3></span>
                    </legend>

                    <table id="dataTable" border="1" style="width: 100%; border: 1px solid rgb(221, 217, 217); margin-bottom: 10px" >
                        <tbody>
                        <tr>
                            <td><input type="checkbox" name="chk"></td>
                            <td>
                                <table style="width:100%">
                                    <tr>
                                        <td>Tên sản phẩm</td>
                                        <td>
                                            <input type="text" autocomplete="off" class="spare_part" name="spare_part[]" placeholder="Nhập tên hoặc * để chọn" tabindex="3" >
                                            <ul class="name_list_id"></ul>
                                        </td>
                                        
                                        <td>
                                            Mã sản phẩm
                                        </td>
                                        <td>
                                            <input autocomplete="off" type="text" class="spare_part_code" name="spare_part_code[]" tabindex="4" placeholder="Nhập tên hoặc * để chọn" >
                                            <ul class="name_list_id_2"></ul>
                                        </td>
                                        
                                    </tr>
                                    <tr class="show_seri">
                                        <td>Chọn 1 sản phẩm</td>
                                        <td>
                                            <select class="choose_seri" name="choose_seri[]" multiple="multiple" tabindex="11" data="0">
                                    
                                            </select>
                                        </td>
                                    </tr>
                                    <tr>
                                        
                                        <td>
                                            Đơn vị tính
                                        </td>
                                        <td>
                                            <input type="text" class="spare_stock_unit" name="spare_stock_unit[]" tabindex="7" >
                                        </td>
                                        <td>Đơn giá</td>
                                        <td>
                                            <input type="text" class="spare_stock_price numbers" name="spare_stock_price[]" tabindex="8" >
                                        </td>
                                    </tr>
                                    <tr>
                                        
                                        <td>Số lượng</td>
                                        <td>
                                          <input style="width:80px" type="number" step="any" class="spare_stock_number number" name="spare_stock_number[]" tabindex="10" value="0" max="0" >
                                        </td>
                                        <td>VAT</td>
                                        <td>
                                          <input style="width:50px" type="text" class="spare_stock_vat_percent number" name="spare_stock_vat_percent[]" tabindex="9" placeholder="%" >
                                            <input style="width:120px" type="text" class="spare_stock_vat_price numbers" name="spare_stock_vat_price[]" tabindex="9" placeholder="Tổng tiền thuế" >
                                            
                                        </td>
                                    </tr>
                                    
                                </table>
                            </td>
                        </tr>
                    </tbody>
                    </table>
                </fieldset>
                    <input type="button" value="Thêm" onclick="addRow('dataTable')">

                    <input type="button" value="Xóa" onclick="deleteRow('dataTable')">
                </div>
              </div>
              <?php if(!isset($disable_control)){ ?>
              <div class="row">
                <div class="col-md-12">
                    <div class="box-footer">
                    <input type="hidden" readonly id="yes" name="yes" required="required" >
                    <button type="submit" class="btn btn-primary" tabindex="6">Hoàn thành</button>
                    <button type="reset" class="btn" tabindex="7">Nhập lại</button>
                  </div>
                  <div class="box-footer">
                    <div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>
                  </div>
                </div>
              </div>
              <?php } ?>
            </form>
          </div>
          <!-- /.box -->

        </div>
        <!--/.col (left) -->
        
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
       
</div>


<script type="text/javascript">
$('html').click(function(e) {
    $('#customer_list_id').slideUp(200);
    $('.name_list_id').slideUp(200);
    $('.name_list_id_2').slideUp(200);
});

    $('.edit_tr').click(function(e){
        if(!$('.checkbox').is(':focus') && e.target.nodeName != "A"){
            if(!$('.checkbox').is(':focus')){
                $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);
            }
            var export_stock_code = $(this).find("#export_stock_code_"+$(this).attr('id')).text();
            var export_stock_date = $(this).find("#export_stock_date_"+$(this).attr('id')).text();
            var export_stock_comment = $(this).find("#export_stock_comment_"+$(this).attr('id')).text();

            var steersman = $(this).find("#steersman_"+$(this).attr('id')).attr('data');
            var steersman_name = $(this).find("#steersman_"+$(this).attr('id')).text();
            var house = $(this).find("#house_"+$(this).attr('id')).attr('data');
            var vehicle = $(this).find("#vehicle_"+$(this).attr('id')).text();
            var romooc = $(this).find("#romooc_"+$(this).attr('id')).text();
            
            //alert(export_stock_code);
            $('#yes').val($(this).attr('id'));
            
            $('#export_stock_date').val(export_stock_date.replace(/\//g,"-"));
            $('#export_stock_code').val(export_stock_code);
            $('#export_stock_comment').val(export_stock_comment);

            $('#steersman').val(steersman_name);
            $('#steersman').attr('data',steersman);
            $('#house option[value='+house+']').attr('selected','selected');
            $('#vehicle option[value='+vehicle+']').attr('selected','selected');
            $('#romooc option[value='+romooc+']').attr('selected','selected');

            $('#dataTable tbody tr').remove();
        
            var export_stock_id = $(this).attr('id');
            $.ajax({
                url: '<?php echo BASE_URL ?>/exportstock/spare',
                type: 'POST',
                data: {export_stock:export_stock_id},
                success:function(data){
                    //alert(data);
                    $('#dataTable tbody').append(data);

                    $(".choose_seri").multiselect({});

                    $('.spare_part').keyup(function(){
                        var row = $(this).parent().parent().parent().parent().parent().parent();
                        var rowIndex = row[0].rowIndex;

                        var keyword = $(this).val();
                        $.ajax({
                            url: '<?php echo BASE_URL ?>/exportstock/getSpare',
                            type: 'POST',
                            data: {keyword:keyword, offset:rowIndex},
                            success:function(data){
                                $('.name_list_id:eq('+rowIndex+')').slideDown(200);
                                $('.name_list_id:eq('+rowIndex+')').html(data);
                            }
                        });
                        if ($('.spare_part:eq('+rowIndex+')').val() == "" || $('.spare_part:eq('+rowIndex+')').attr('data') == "") {
                            
                            $('.spare_part:eq('+rowIndex+')').attr('data',"");
                        }

                        
                    });

                $('.spare_part').on('keydown', function() {
                        var row = $(this).parent().parent().parent().parent().parent().parent();
                        var rowIndex = row[0].rowIndex;

                        var key = event.keyCode || event.charCode;

                        if( key == 8 || key == 46 ){
                            $('.spare_part:eq('+rowIndex+')').attr('data',"");
                        }
                            
                      }); 

                $('.spare_part_code').keyup(function(){
                      var row = $(this).parent().parent().parent().parent().parent().parent();
                      var rowIndex = row[0].rowIndex;

                      var keyword = $(this).val();
                      $.ajax({
                          url: '<?php echo BASE_URL ?>/exportstock/getSpare',
                          type: 'POST',
                          data: {keyword:keyword, offset:rowIndex},
                          success:function(data){
                              $('.name_list_id_2:eq('+rowIndex+')').slideDown(200);
                              $('.name_list_id_2:eq('+rowIndex+')').html(data);
                          }
                      });
                      if ($('.spare_part:eq('+rowIndex+')').val() == "" || $('.spare_part:eq('+rowIndex+')').attr('data') == "") {
                          
                          $('.spare_part:eq('+rowIndex+')').attr('data',"");
                      }

                      
                  });

             

              $('.spare_stock_vat_percent').keyup(function(){
                          var row = $(this).parent().parent().parent().parent().parent().parent();
                          var rowIndex = row[0].rowIndex;

                          var percent = parseFloat($(this).val());
                          var number = parseFloat(get_number('.spare_stock_number:eq('+rowIndex+')')) || 0;

                          $('.spare_stock_vat_price:eq('+rowIndex+')').val(
                              Math.round(
                              (parseFloat(get_number('.spare_stock_price:eq('+rowIndex+')'))*percent/100)*number
                              )
                          );

                          $('.spare_stock_vat_price:eq('+rowIndex+')').val(function(index, value) {
                              return value
                                .replace(/\D/g, "")
                                .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
                              ;
                            });
                          
                      });
                    $('.spare_stock_price').keyup(function(){
                          var row = $(this).parent().parent().parent().parent().parent().parent();
                          var rowIndex = row[0].rowIndex;

                          var percent = parseFloat(get_number('.spare_stock_vat_percent:eq('+rowIndex+')')) || 0;
                          var price = parseFloat($(this).val().replace(/\,/g,''));
                          var number = parseFloat(get_number('.spare_stock_number:eq('+rowIndex+')')) || 0;

                          $('.spare_stock_vat_price:eq('+rowIndex+')').val(
                              Math.round(
                              (price*percent/100)*number
                              )
                          );

                          $('.spare_stock_vat_price:eq('+rowIndex+')').val(function(index, value) {
                              return value
                                .replace(/\D/g, "")
                                .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
                              ;
                            });
                          
                      });
                      $('.spare_stock_number').keyup(function(){
                          var row = $(this).parent().parent().parent().parent().parent().parent();
                          var rowIndex = row[0].rowIndex;

                          var seri = $('.spare_part_seri:eq('+rowIndex+')').val().trim();
                          if (seri != "") {
                            $(this).val(1);
                          }

                          var number = parseFloat($(this).val());
                          var percent = parseFloat(get_number('.spare_stock_vat_percent:eq('+rowIndex+')')) || 0;

                          $('.spare_stock_vat_price:eq('+rowIndex+')').val(
                              Math.round(
                              (parseFloat(get_number('.spare_stock_price:eq('+rowIndex+')'))*percent/100)*number
                              )
                          );

                          $('.spare_stock_vat_price:eq('+rowIndex+')').val(function(index, value) {
                              return value
                                .replace(/\D/g, "")
                                .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
                              ;
                            });
                          
                      });

                   
                    $('.number').keyup(function(event) {

                          // skip for arrow keys
                      if(event.which >= 37 && event.which <= 40) return;

                      // format number
                      $(this).val(function(index, value) {
                        return value
                          .replace(/[^0-9-.]/g, "")
                        ;
                      });
                    });
                   
                   $('.numbers').keyup(function(event) {

                          // skip for arrow keys
                      if(event.which >= 37 && event.which <= 40) return;

                      // format number
                      $(this).val(function(index, value) {
                        return value
                          .replace(/[^0-9]/g, "")
                          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
                        ;
                      });
                    });

                   function get_number(id){
                    return $(id).val().replace(/\,/g,'');
                  }
                  function set_item_other(item,value,code,vitri,unit,price) {
                      // change input value
                      $('.spare_part:eq('+vitri+')').val(value);
                      $('.spare_part:eq('+vitri+')').attr("data",item);
                      $('.spare_part_code:eq('+vitri+')').val(code);
                      $('.spare_stock_unit:eq('+vitri+')').val(unit);
                      $('.spare_stock_price:eq('+vitri+')').val(price);
                      $('.spare_stock_number:eq('+vitri+')').val(0);
                      $('.spare_stock_vat_price:eq('+vitri+')').val(0);


                      $.ajax({
                            url: '<?php echo BASE_URL ?>/exportstock/getseri',
                            type: 'POST',
                            data: {data:item},
                            success:function(data){
                                $(".choose_seri:eq("+vitri+")").html(data);
                                  $(".choose_seri:eq("+vitri+")").multiselect( 'refresh' );
                                  $(".choose_seri:eq("+vitri+")").multiselect({
                                    click: function(event, ui){
                                        var percent = parseFloat(get_number('.spare_stock_vat_percent:eq('+vitri+')')) || 0;
                                        var number = parseFloat($('.spare_stock_number:eq('+vitri+')').val()) || 0;
                                        var new_num = parseFloat(ui.text);
                                        if(ui.checked == 1){
                                            $('.spare_stock_number:eq('+vitri+')').val(number+new_num);
                                            $('.spare_stock_number:eq('+vitri+')').attr('max',number+new_num);

                                            $('.spare_stock_vat_price:eq('+vitri+')').val(
                                                  Math.round(
                                                  (parseFloat(get_number('.spare_stock_price:eq('+vitri+')'))*percent/100)*(number+new_num)
                                                  )
                                              );
                                        }
                                        else{
                                            $('.spare_stock_number:eq('+vitri+')').val(number-new_num);
                                            $('.spare_stock_number:eq('+vitri+')').attr('max',number-new_num);

                                            $('.spare_stock_vat_price:eq('+vitri+')').val(
                                                  Math.round(
                                                  (parseFloat(get_number('.spare_stock_price:eq('+vitri+')'))*percent/100)*(number-new_num)
                                                  )
                                              );
                                        }
                                        
                                          $('.spare_stock_vat_price:eq('+vitri+')').val(function(index, value) {
                                              return value
                                                .replace(/\D/g, "")
                                                .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
                                              ;
                                            });
                                    },
                                    checkAll: function(){
                                        var percent = parseFloat(get_number('.spare_stock_vat_percent:eq('+vitri+')')) || 0;
                                        var number = parseFloat($('.spare_stock_number:eq('+vitri+')').val()) || 0;
                                        var new_num = 0;
                                        $(".choose_seri:eq("+vitri+")").multiselect("widget").find(":checkbox").each(function(){
                                           new_num += parseFloat(this.title);
                                        });

                                        $('.spare_stock_number:eq('+vitri+')').val(number+new_num);
                                        $('.spare_stock_number:eq('+vitri+')').attr('max',number+new_num);

                                        $('.spare_stock_vat_price:eq('+vitri+')').val(
                                              Math.round(
                                              (parseFloat(get_number('.spare_stock_price:eq('+vitri+')'))*percent/100)*(number+new_num)
                                              )
                                          );
                                        $('.spare_stock_vat_price:eq('+vitri+')').val(function(index, value) {
                                              return value
                                                .replace(/\D/g, "")
                                                .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
                                              ;
                                            });
                                    },
                                    uncheckAll: function(){
                                        $('.spare_stock_number:eq('+vitri+')').val(0);
                                        $('.spare_stock_number:eq('+vitri+')').attr('max',0);
                                        $('.spare_stock_vat_price:eq('+vitri+')').val(0);
                                    }
                                  });
                            }
                        });
                      
                      // hide proposition list
                      $('.name_list_id').hide();
                      $('.name_list_id_2').hide();
                      $('.spare_part:eq('+vitri+')').focus();

                      $(".numbers").val(function(index, value) {
                      return value
                        .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
                      ;
                    });

                  }
                }
            });

            $( ".add-field" ).dialog( "open" );
        }
    });
</script>
<script type="text/javascript">

function add_click(){
    $('#yes').val("");
    $('.add-field').slideDown(500);
     $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);   
        $('#export_stock_code').val("");
        $('#export_stock_date').val("");
        $('#export_stock_comment').val("");

        $('#steersman').val("");
        $('#steersman').attr('data',"");

        $('#vehicle option[value=""]').attr('selected','selected');
        $('#romooc option[value=""]').attr('selected','selected');
        
        $('input[name="chk"]').attr('data',"");
        $('input[type="text"]').attr('disabled',false);
        
        $('.number').focus(function(){
            if ( $(this).val() == '0') {
               $(this).val(""); 
            };
            
        });
        $('.number').blur(function(){
            if ( $(this).val() == "") {
                $(this).val(0);
            };
            
        });


   $( ".add-field" ).dialog( "open" );

}


$(document).ready(function(){
            // Validate form
            $("#add_export_stock").validate({
                errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
                rules: {
                    
                },
                submitHandler: function(form) {
                
                    if ($('#steersman').attr('code') == 'false') {
                        $('#steersman').val("");
                        $('#steersman').focus();
                        return false;
                    };

                    var export_stock_code = $('#export_stock_code').attr('value');
                    var export_stock_date = $('#export_stock_date').attr('value');
                    var export_stock_comment = $('#export_stock_comment').attr('value');
                    var steersman = $('#steersman').attr('data');
                    var house = $('#house').attr('value');
                    var vehicle = $('#vehicle').attr('value');
                    var romooc = $('#romooc').attr('value');

                    var spare_part = [];

                    var spare_part_code_id = [];
                    var spare_part_id = [];
                    var spare_stock_unit = [];
                    var spare_stock_number = [];
                    var spare_stock_price = [];
                    var spare_stock_vat_percent = [];
                    var spare_stock_vat_price = [];

                    var spare_stock_number2 = [];
                    var spare_stock_vat_price2 = [];

                    $('.spare_stock_unit').each(function() { 
                        spare_stock_unit.push($(this).val());
                    });

                    $('.spare_stock_number').each(function() { 
                        spare_stock_number.push($(this).val());
                        spare_stock_number2.push($(this).val());
                    });

                    $('.spare_stock_price').each(function() { 
                        spare_stock_price.push($(this).val());
                    });
                    $('.spare_stock_vat_percent').each(function() { 
                        spare_stock_vat_percent.push($(this).val());
                    });
                    $('.spare_stock_vat_price').each(function() { 
                        spare_stock_vat_price2.push($(this).val());
                    });

                    $('.spare_part').each(function(index) { 
                      var $this = $(this);
                      spare_part_code_id.push($this.attr('data'));
                      spare_stock_vat_price.push(parseInt(spare_stock_vat_price2[index].replace(/\,/g,'')/spare_stock_number2[index]));
                      spare_part_id.push($('.choose_seri[data='+index+']').val());  
                    });


                    for (var i = 0; i < spare_part_code_id.length; i++) {
                        spare_part.push({'spare_part_code_id':spare_part_code_id[i],'spare_stock_unit':spare_stock_unit[i], 'spare_stock_number':spare_stock_number[i], 'spare_stock_price':spare_stock_price[i], 'spare_stock_vat_percent':spare_stock_vat_percent[i], 'spare_stock_vat_price':spare_stock_vat_price[i], 'spare_part_id':spare_part_id[i]});
                        
                        
                    };

                   
                    
                    var yes = $('#yes').attr('value');
                    
                    var action      = "them";
                 
                    $.ajax({
                        type: "POST", // phương thức gởi đi
                        url: "<?php echo BASE_URL ?>/exportstock/add", // nơi mà dữ liệu sẽ chuyển đến khi submit
                        data: {
                            export_stock_code: export_stock_code,
                            export_stock_date: export_stock_date,
                            export_stock_comment: export_stock_comment,
                            spare_part: spare_part,
                            steersman: steersman,
                            house: house,
                            vehicle: vehicle,
                            romooc: romooc,
                            yes: yes,
                            }, // giá trị post
                        success: function(answer){ // if everything goes well
                            //alert(answer);
                            $('#error').hide();
                            $('#error').slideToggle(100); // hiển thị thẻ div success
                            $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                            $('#error').fadeOut(10000);

                            if (yes != "") {
                                if (answer.trim() != "Thông tin này đã tồn tại" ) {
                                  setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);
                                    $('#export_stock_name_'+yes).text(export_stock_name);
                                    $('#province_name_'+yes).text($('#province option:selected').text());
                                }
                            }
                            else{
                                if (answer.trim() != "Thông tin này đã tồn tại") {
                                  setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);
                                    var lastID = parseInt($('#lasted').html());
                                    var rowCount = parseInt($('.table_data > tbody > tr').length);
                                    $('.table_data > tbody:last')
                                    .append(
                                        '<tr onclick="HighLightTR(this,#4d90fe,cc3333);" id="'+parseInt(lastID+1)+'" class="edit_tr"><td><input name="check[]" type="checkbox" class="checkbox" value="'+parseInt(lastID+1)+'"></td><td class="fix">'+parseInt(rowCount+1)+'</td><td class="fix" id="export_stock_name_'+parseInt(lastID+1)+'">'+export_stock_name+'</td><td class="fix" data="'+province+'" id="province_name_'+parseInt(lastID+1)+'">'+$('#province option:selected').text()+'</td><td><a class="error" href="#">Sửa</a> | <a class="error" onclick="del('+parseInt(lastID+1)+')">Xóa</a></td></tr>'
                                    );

                                    $('#lasted').html(parseInt(lastID+2));
                                }
                            }
                        }
                    });
                    return false;
                     
                 }
            });
   
   $('#steersman').keyup(function(){
        var ngay = $('#export_stock_date').val();
        if (ngay == "") {
            ngay = "<?php echo date('d-m-Y') ?>";
        }
        var keyword = $(this).val();
        $.ajax({
            url: '<?php echo BASE_URL ?>/exportstock/getsteersman',
            type: 'POST',
            data: {keyword:keyword,ngay:ngay},
            success:function(data){
                $('#customer_list_id').slideDown(200);
                $('#customer_list_id').html(data);
            }
        });
        if ($('#steersman').val() == "" || $('#steersman').attr('data') == "") {
            //$('#loc_from').val("");
            $('#steersman').attr('data',"");
            $('#steersman').attr('code',false);
        }
      
   });
   
   $('.spare_part').keyup(function(){
        var row = $(this).parent().parent().parent().parent().parent().parent();
        var rowIndex = row[0].rowIndex;

        var keyword = $(this).val();
        $.ajax({
            url: '<?php echo BASE_URL ?>/exportstock/getSpare',
            type: 'POST',
            data: {keyword:keyword, offset:rowIndex},
            success:function(data){
                $('.name_list_id:eq('+rowIndex+')').slideDown(200);
                $('.name_list_id:eq('+rowIndex+')').html(data);
            }
        });
        if ($('.spare_part:eq('+rowIndex+')').val() == "" || $('.spare_part:eq('+rowIndex+')').attr('data') == "") {
            
            $('.spare_part:eq('+rowIndex+')').attr('data',"");
        }

        
    });

$('.spare_part').on('keydown', function() {
        var row = $(this).parent().parent().parent().parent().parent().parent();
        var rowIndex = row[0].rowIndex;

        var key = event.keyCode || event.charCode;

        if( key == 8 || key == 46 ){
            $('.spare_part:eq('+rowIndex+')').attr('data',"");
        }
            
      }); 

$('.spare_part_code').keyup(function(){
        var row = $(this).parent().parent().parent().parent().parent().parent();
        var rowIndex = row[0].rowIndex;

        var keyword = $(this).val();
        $.ajax({
            url: '<?php echo BASE_URL ?>/exportstock/getSpare',
            type: 'POST',
            data: {keyword:keyword, offset:rowIndex},
            success:function(data){
                $('.name_list_id_2:eq('+rowIndex+')').slideDown(200);
                $('.name_list_id_2:eq('+rowIndex+')').html(data);
            }
        });
        if ($('.spare_part:eq('+rowIndex+')').val() == "" || $('.spare_part:eq('+rowIndex+')').attr('data') == "") {
            
            $('.spare_part:eq('+rowIndex+')').attr('data',"");
        }

        
    });



$('.spare_part_code').blur(function(){
    var row = $(this).parent().parent().parent().parent().parent().parent();
    var rowIndex = row[0].rowIndex;

    var check_type = 0;

    var val = $(this).val().trim();
    
    $('.spare_part_code').each(function() { 
        if (val != "" && val == $(this).val().trim()) {
            check_type ++;
        }
    });

    

    if (check_type >= 2) {
        alert('Sản phẩm này đã có!');
        $(this).val("");
        $('.spare_part:eq('+rowIndex+')').attr('data',"");
        $('.spare_part:eq('+rowIndex+')').val("");
        $('.spare_part_brand:eq('+rowIndex+')').val("");
        $('.spare_part_seri:eq('+rowIndex+')').val("");
        $('.spare_part_date_manufacture:eq('+rowIndex+')').val("");
        
    };
    
});
$('.spare_part').blur(function(){
    var row = $(this).parent().parent().parent().parent().parent().parent();
    var rowIndex = row[0].rowIndex;

    var check_type = 0;

    var val = $(this).val().trim();
    
    $('.spare_part').each(function() { 
        if (val != "" && val == $(this).val().trim()) {
            check_type ++;
        }
    });

    

    if (check_type >= 2) {
        alert('Sản phẩm này đã có!');
        $(this).val("");
        $('.spare_part:eq('+rowIndex+')').attr('data',"");
        $('.spare_part_code:eq('+rowIndex+')').val("");
        $('.spare_part_brand:eq('+rowIndex+')').val("");
        $('.spare_part_seri:eq('+rowIndex+')').val("");
        $('.spare_part_date_manufacture:eq('+rowIndex+')').val("");
        
    };
    
});

$('.spare_stock_vat_percent').keyup(function(){
      var row = $(this).parent().parent().parent().parent().parent().parent();
      var rowIndex = row[0].rowIndex;

      var percent = parseFloat($(this).val());
      var number = parseFloat(get_number('.spare_stock_number:eq('+rowIndex+')')) || 0;

      $('.spare_stock_vat_price:eq('+rowIndex+')').val(
          Math.round(
          (parseFloat(get_number('.spare_stock_price:eq('+rowIndex+')'))*percent/100)*number
          )
      );

      $('.spare_stock_vat_price:eq('+rowIndex+')').val(function(index, value) {
          return value
            .replace(/\D/g, "")
            .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
          ;
        });
      
  });
$('.spare_stock_price').keyup(function(){
      var row = $(this).parent().parent().parent().parent().parent().parent();
      var rowIndex = row[0].rowIndex;

      var percent = parseFloat(get_number('.spare_stock_vat_percent:eq('+rowIndex+')')) || 0;
      var price = parseFloat($(this).val().replace(/\,/g,''));
      var number = parseFloat(get_number('.spare_stock_number:eq('+rowIndex+')')) || 0;

      $('.spare_stock_vat_price:eq('+rowIndex+')').val(
          Math.round(
          (price*percent/100)*number
          )
      );

      $('.spare_stock_vat_price:eq('+rowIndex+')').val(function(index, value) {
          return value
            .replace(/\D/g, "")
            .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
          ;
        });
      
  });
  $('.spare_stock_number').keyup(function(){
      var row = $(this).parent().parent().parent().parent().parent().parent();
      var rowIndex = row[0].rowIndex;

      var seri = $('.spare_part_seri:eq('+rowIndex+')').val().trim();
      if (seri != "") {
        $(this).val(1);
      }

      var number = parseFloat($(this).val());
      var percent = parseFloat(get_number('.spare_stock_vat_percent:eq('+rowIndex+')')) || 0;

      $('.spare_stock_vat_price:eq('+rowIndex+')').val(
          Math.round(
          (parseFloat(get_number('.spare_stock_price:eq('+rowIndex+')'))*percent/100)*number
          )
      );

      $('.spare_stock_vat_price:eq('+rowIndex+')').val(function(index, value) {
          return value
            .replace(/\D/g, "")
            .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
          ;
        });
      
  });
   
    $('.number').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-.]/g, "")
        ;
      });
    });
   
   $('.numbers').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9]/g, "")
          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
        ;
      });
    });
    

});
function get_number(id){
    return $(id).val().replace(/\,/g,'');
}
function set_item_other(item,value,code,vitri,unit,price) {
      // change input value
      $('.spare_part:eq('+vitri+')').val(value);
      $('.spare_part:eq('+vitri+')').attr("data",item);
      $('.spare_part_code:eq('+vitri+')').val(code);
      $('.spare_stock_unit:eq('+vitri+')').val(unit);
      $('.spare_stock_price:eq('+vitri+')').val(price);
      $('.spare_stock_number:eq('+vitri+')').val(0);
      $('.spare_stock_vat_price:eq('+vitri+')').val(0);


      $.ajax({
            url: '<?php echo BASE_URL ?>/exportstock/getseri',
            type: 'POST',
            data: {data:item},
            success:function(data){
                $(".choose_seri:eq("+vitri+")").html(data);
                  $(".choose_seri:eq("+vitri+")").multiselect( 'refresh' );
                  $(".choose_seri:eq("+vitri+")").multiselect({
                    click: function(event, ui){
                        var percent = parseFloat(get_number('.spare_stock_vat_percent:eq('+vitri+')')) || 0;
                        var number = parseFloat($('.spare_stock_number:eq('+vitri+')').val()) || 0;
                        var new_num = parseFloat(ui.text);
                        if(ui.checked == 1){
                            $('.spare_stock_number:eq('+vitri+')').val(number+new_num);
                            $('.spare_stock_number:eq('+vitri+')').attr('max',number+new_num);

                            $('.spare_stock_vat_price:eq('+vitri+')').val(
                                  Math.round(
                                  (parseFloat(get_number('.spare_stock_price:eq('+vitri+')'))*percent/100)*(number+new_num)
                                  )
                              );
                        }
                        else{
                            $('.spare_stock_number:eq('+vitri+')').val(number-new_num);
                            $('.spare_stock_number:eq('+vitri+')').attr('max',number-new_num);

                            $('.spare_stock_vat_price:eq('+vitri+')').val(
                                  Math.round(
                                  (parseFloat(get_number('.spare_stock_price:eq('+vitri+')'))*percent/100)*(number-new_num)
                                  )
                              );
                        }
                        
                          $('.spare_stock_vat_price:eq('+vitri+')').val(function(index, value) {
                              return value
                                .replace(/\D/g, "")
                                .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
                              ;
                            });
                    },
                    checkAll: function(){
                        var percent = parseFloat(get_number('.spare_stock_vat_percent:eq('+vitri+')')) || 0;
                        var number = parseFloat($('.spare_stock_number:eq('+vitri+')').val()) || 0;
                        var new_num = 0;
                        $(".choose_seri:eq("+vitri+")").multiselect("widget").find(":checkbox").each(function(){
                           new_num += parseFloat(this.title);
                        });

                        $('.spare_stock_number:eq('+vitri+')').val(number+new_num);
                        $('.spare_stock_number:eq('+vitri+')').attr('max',number+new_num);

                        $('.spare_stock_vat_price:eq('+vitri+')').val(
                              Math.round(
                              (parseFloat(get_number('.spare_stock_price:eq('+vitri+')'))*percent/100)*(number+new_num)
                              )
                          );
                        $('.spare_stock_vat_price:eq('+vitri+')').val(function(index, value) {
                              return value
                                .replace(/\D/g, "")
                                .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
                              ;
                            });
                    },
                    uncheckAll: function(){
                        $('.spare_stock_number:eq('+vitri+')').val(0);
                        $('.spare_stock_number:eq('+vitri+')').attr('max',0);
                        $('.spare_stock_vat_price:eq('+vitri+')').val(0);
                    }
                  });
            }
        });
      
      // hide proposition list
      $('.name_list_id').hide();
      $('.name_list_id_2').hide();
      $('.spare_part:eq('+vitri+')').focus();

      $(".numbers").val(function(index, value) {
      return value
        .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
      ;
    });

  }
function set_item_steersman(value,name,vehicle) {
    // change input value
    $('#steersman').val(name);
    $("#steersman").attr("data",value);
    $("#steersman").attr("code",'true');

    if ($('#romooc').val() == "")
      $("#vehicle option[value="+vehicle+"]").attr("selected","selected");
    
    // hide proposition list
    $('#customer_list_id').hide();
    $('#steersman').focus();
     
}
</script>
<div style="display:none" id="lasted"></div>
<script type="text/javascript">
    var count = parseInt(<?php echo $lastID ?>);
    $('#lasted').html(count);


</script>
</div>

<script type="text/javascript">
var l = "<?php echo $limit ?>";
$('#chonloc option[value='+l+']').attr('selected','selected');

$( ".add-field" ).dialog({
    autoOpen: false,
    modal: true,
    width: "auto",
    title: "Xuất kho",
    hide: 'fold',
    show: 'blind'
});


var pickerOpay2 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+0",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true
    }; 
    $(".ngay").datepicker(pickerOpay2);


function addRow(tableID){
    var table=document.getElementById(tableID);
    var rowCount=table.rows.length;
    var row=table.insertRow(rowCount);
    var colCount=table.rows[0].cells.length;
    for(var i=0;i<colCount;i++){
        var newcell=row.insertCell(i);
        newcell.innerHTML=table.rows[0].cells[i].innerHTML;
        switch(newcell.childNodes[0].type){
            case"text":newcell.childNodes[0].value="";
            break;
            case"checkbox":newcell.childNodes[0].checked=false;
            break;
            case"select-one":newcell.childNodes[0].selectedIndex=0;
            break;
        }
    }

    $('.spare_part:last').attr('disabled',false);
    $('.spare_part_code:last').attr('disabled',false);
    $('.spare_part:last').attr('data',"");
    $('.spare_part:last').val("");
    $('.spare_part_code:last').val("");
    $('.spare_stock_unit:last').val("");
    $('.spare_stock_price:last').val("");
    $('.spare_stock_number:last').val("");
    $('.spare_stock_number:last').attr('max',0);
    $('.spare_stock_vat_percent:last').val("");
    $('.spare_stock_vat_price:last').val("");
    
    $('input[name="chk"]:last').attr('data',"");
    $('input[name="chk"]:last').attr('tabindex',0);
    $('input[name="chk"]:last').attr('title',"");
    $('input[name="chk"]:last').attr('class',"");
    $('input[name="chk"]:last').attr('alt',0);

    $('.choose_seri:last').attr('data',rowCount);
    $(".choose_seri:last").multiselect({});
    $(".choose_seri:last").empty();
    $(".choose_seri:last").multiselect( 'refresh' );
    $(".ui-multiselect:last").remove();

    $('.spare_part').keyup(function(){
        var row = $(this).parent().parent().parent().parent().parent().parent();
        var rowIndex = row[0].rowIndex;

        var keyword = $(this).val();
        $.ajax({
            url: '<?php echo BASE_URL ?>/exportstock/getSpare',
            type: 'POST',
            data: {keyword:keyword, offset:rowIndex},
            success:function(data){
                $('.name_list_id:eq('+rowIndex+')').slideDown(200);
                $('.name_list_id:eq('+rowIndex+')').html(data);
            }
        });
        if ($('.spare_part:eq('+rowIndex+')').val() == "" || $('.spare_part:eq('+rowIndex+')').attr('data') == "") {
            
            $('.spare_part:eq('+rowIndex+')').attr('data',"");
        }

        
    });

$('.spare_part').on('keydown', function() {
        var row = $(this).parent().parent().parent().parent().parent().parent();
        var rowIndex = row[0].rowIndex;

        var key = event.keyCode || event.charCode;

        if( key == 8 || key == 46 ){
            $('.spare_part:eq('+rowIndex+')').attr('data',"");
        }
            
      }); 

$('.spare_part_code').keyup(function(){
        var row = $(this).parent().parent().parent().parent().parent().parent();
        var rowIndex = row[0].rowIndex;

        var keyword = $(this).val();
        $.ajax({
            url: '<?php echo BASE_URL ?>/exportstock/getSpare',
            type: 'POST',
            data: {keyword:keyword, offset:rowIndex},
            success:function(data){
                $('.name_list_id_2:eq('+rowIndex+')').slideDown(200);
                $('.name_list_id_2:eq('+rowIndex+')').html(data);
            }
        });
        if ($('.spare_part:eq('+rowIndex+')').val() == "" || $('.spare_part:eq('+rowIndex+')').attr('data') == "") {
            
            $('.spare_part:eq('+rowIndex+')').attr('data',"");
        }

        
    });



    $('.spare_part_code').blur(function(){
    var row = $(this).parent().parent().parent().parent().parent().parent();
    var rowIndex = row[0].rowIndex;

    var check_type = 0;

    var val = $(this).val().trim();
    
    $('.spare_part_code').each(function() { 
        if (val != "" && val == $(this).val().trim()) {
            check_type ++;
        }
    });

    

    if (check_type >= 2) {
        alert('Sản phẩm này đã có!');
        $(this).val("");
        $('.spare_part:eq('+rowIndex+')').attr('data',"");
        $('.spare_part:eq('+rowIndex+')').val("");
        $('.spare_part_brand:eq('+rowIndex+')').val("");
        $('.spare_part_seri:eq('+rowIndex+')').val("");
        $('.spare_part_date_manufacture:eq('+rowIndex+')').val("");
        
    };
    
});
$('.spare_part').blur(function(){
    var row = $(this).parent().parent().parent().parent().parent().parent();
    var rowIndex = row[0].rowIndex;

    var check_type = 0;

    var val = $(this).val().trim();
    
    $('.spare_part').each(function() { 
        if (val != "" && val == $(this).val().trim()) {
            check_type ++;
        }
    });

    

    if (check_type >= 2) {
        alert('Sản phẩm này đã có!');
        $(this).val("");
        $('.spare_part:eq('+rowIndex+')').attr('data',"");
        $('.spare_part_code:eq('+rowIndex+')').val("");
        $('.spare_part_brand:eq('+rowIndex+')').val("");
        $('.spare_part_seri:eq('+rowIndex+')').val("");
        $('.spare_part_date_manufacture:eq('+rowIndex+')').val("");
        
    };
    
});

$('.spare_stock_vat_percent').keyup(function(){
      var row = $(this).parent().parent().parent().parent().parent().parent();
      var rowIndex = row[0].rowIndex;

      var percent = parseFloat($(this).val());
      var number = parseFloat(get_number('.spare_stock_number:eq('+rowIndex+')')) || 0;

      $('.spare_stock_vat_price:eq('+rowIndex+')').val(
          Math.round(
          (parseFloat(get_number('.spare_stock_price:eq('+rowIndex+')'))*percent/100)*number
          )
      );

      $('.spare_stock_vat_price:eq('+rowIndex+')').val(function(index, value) {
          return value
            .replace(/\D/g, "")
            .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
          ;
        });
      
  });
$('.spare_stock_price').keyup(function(){
      var row = $(this).parent().parent().parent().parent().parent().parent();
      var rowIndex = row[0].rowIndex;

      var percent = parseFloat(get_number('.spare_stock_vat_percent:eq('+rowIndex+')')) || 0;
      var price = parseFloat($(this).val().replace(/\,/g,''));
      var number = parseFloat(get_number('.spare_stock_number:eq('+rowIndex+')')) || 0;

      $('.spare_stock_vat_price:eq('+rowIndex+')').val(
          Math.round(
          (price*percent/100)*number
          )
      );

      $('.spare_stock_vat_price:eq('+rowIndex+')').val(function(index, value) {
          return value
            .replace(/\D/g, "")
            .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
          ;
        });
      
  });
  $('.spare_stock_number').keyup(function(){
      var row = $(this).parent().parent().parent().parent().parent().parent();
      var rowIndex = row[0].rowIndex;

      var seri = $('.spare_part_seri:eq('+rowIndex+')').val().trim();
      if (seri != "") {
        $(this).val(1);
      }

      var number = parseFloat($(this).val());
      var percent = parseFloat(get_number('.spare_stock_vat_percent:eq('+rowIndex+')')) || 0;

      $('.spare_stock_vat_price:eq('+rowIndex+')').val(
          Math.round(
          (parseFloat(get_number('.spare_stock_price:eq('+rowIndex+')'))*percent/100)*number
          )
      );

      $('.spare_stock_vat_price:eq('+rowIndex+')').val(function(index, value) {
          return value
            .replace(/\D/g, "")
            .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
          ;
        });
      
  });
   
    $('.number').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-.]/g, "")
        ;
      });
    });
   
   $('.numbers').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9]/g, "")
          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
        ;
      });
    });

   function get_number(id){
    return $(id).val().replace(/\,/g,'');
  }
  function set_item_other(item,value,code,vitri,unit,price) {
      // change input value
      $('.spare_part:eq('+vitri+')').val(value);
      $('.spare_part:eq('+vitri+')').attr("data",item);
      $('.spare_part_code:eq('+vitri+')').val(code);
      $('.spare_stock_unit:eq('+vitri+')').val(unit);
      $('.spare_stock_price:eq('+vitri+')').val(price);
      $('.spare_stock_number:eq('+vitri+')').val(0);
      $('.spare_stock_vat_price:eq('+vitri+')').val(0);


      $.ajax({
            url: '<?php echo BASE_URL ?>/exportstock/getseri',
            type: 'POST',
            data: {data:item},
            success:function(data){
                $(".choose_seri:eq("+vitri+")").html(data);
                  $(".choose_seri:eq("+vitri+")").multiselect( 'refresh' );
                  $(".choose_seri:eq("+vitri+")").multiselect({
                    click: function(event, ui){
                        var percent = parseFloat(get_number('.spare_stock_vat_percent:eq('+vitri+')')) || 0;
                        var number = parseFloat($('.spare_stock_number:eq('+vitri+')').val()) || 0;
                        var new_num = parseFloat(ui.text);
                        if(ui.checked == 1){
                            $('.spare_stock_number:eq('+vitri+')').val(number+new_num);
                            $('.spare_stock_number:eq('+vitri+')').attr('max',number+new_num);

                            $('.spare_stock_vat_price:eq('+vitri+')').val(
                                  Math.round(
                                  (parseFloat(get_number('.spare_stock_price:eq('+vitri+')'))*percent/100)*(number+new_num)
                                  )
                              );
                        }
                        else{
                            $('.spare_stock_number:eq('+vitri+')').val(number-new_num);
                            $('.spare_stock_number:eq('+vitri+')').attr('max',number-new_num);

                            $('.spare_stock_vat_price:eq('+vitri+')').val(
                                  Math.round(
                                  (parseFloat(get_number('.spare_stock_price:eq('+vitri+')'))*percent/100)*(number-new_num)
                                  )
                              );
                        }
                        
                          $('.spare_stock_vat_price:eq('+vitri+')').val(function(index, value) {
                              return value
                                .replace(/\D/g, "")
                                .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
                              ;
                            });
                    },
                    checkAll: function(){
                        var percent = parseFloat(get_number('.spare_stock_vat_percent:eq('+vitri+')')) || 0;
                        var number = parseFloat($('.spare_stock_number:eq('+vitri+')').val()) || 0;
                        var new_num = 0;
                        $(".choose_seri:eq("+vitri+")").multiselect("widget").find(":checkbox").each(function(){
                           new_num += parseFloat(this.title);
                        });

                        $('.spare_stock_number:eq('+vitri+')').val(number+new_num);
                        $('.spare_stock_number:eq('+vitri+')').attr('max',number+new_num);

                        $('.spare_stock_vat_price:eq('+vitri+')').val(
                              Math.round(
                              (parseFloat(get_number('.spare_stock_price:eq('+vitri+')'))*percent/100)*(number+new_num)
                              )
                          );
                        $('.spare_stock_vat_price:eq('+vitri+')').val(function(index, value) {
                              return value
                                .replace(/\D/g, "")
                                .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
                              ;
                            });
                    },
                    uncheckAll: function(){
                        $('.spare_stock_number:eq('+vitri+')').val(0);
                        $('.spare_stock_number:eq('+vitri+')').attr('max',0);
                        $('.spare_stock_vat_price:eq('+vitri+')').val(0);
                    }
                  });
            }
        });
      
      // hide proposition list
      $('.name_list_id').hide();
      $('.name_list_id_2').hide();
      $('.spare_part:eq('+vitri+')').focus();

      $(".numbers").val(function(index, value) {
      return value
        .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
      ;
    });

  }

  var pickerOpay2 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+0",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true
    }; 
    $(".ngay").datepicker(pickerOpay2);

}
function deleteRow(tableID){
    try{
        var table=document.getElementById(tableID);
        var rowCount=table.rows.length;

        var r = confirm("Bạn có chắc chắn không?");
        if (r == true){
            for(var i=0;i<rowCount;i++){
                var row=table.rows[i];
                var chkbox=row.cells[0].childNodes[0];
                if(null!=chkbox&&true==chkbox.checked){
                    if(rowCount<=1){
                        alert("Cannot delete all the rows.");
                        break;
                    }
                    else if(chkbox.getAttribute("data") > 0){
                        
                            var export_stock = chkbox.getAttribute("data");
                            var spare_part_code = chkbox.getAttribute("alt");
                            $.post("<?php echo BASE_URL ?>/exportstock/deletesparecode", {export_stock: export_stock, spare_part_code: spare_part_code},
                               function(data){
                                //alert(data);
                               }); 
                        
                    }
                    
                    table.deleteRow(i);
                    rowCount--;
                    i--;
                }
            }
        }
    }
    catch(e){
        alert(e);
    }
}
</script>
<style type="text/css">
    #ui-datepicker-div{
        font-size: 13px;
    }
</style>
<script type="text/javascript">
    $(function() {
    var pickerOpts = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#ketthuc" ).datepicker( "option", "minDate", selectedDate );

         },
         
    };  
    $("#batdau").datepicker(pickerOpts);

    var pickerOpts4 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#batdau" ).datepicker( "option", "maxDate", selectedDate );
                
         },
         
    };  
    $("#ketthuc").datepicker(pickerOpts4);
              
            
    
});

var ch = "<?php echo $limit ?>";
$('#chonloc option[value='+ch+']').attr('selected','selected');

var v = "<?php echo $vong ?>";
$('#sl_round option[value='+v+']').attr('selected','selected');

var tt = "<?php echo $trangthai ?>";
$('#sl_staff option[value='+tt+']').attr('selected','selected');

</script>
<script type="text/javascript">
    
    $('#sl_round').change(function(){
        var m = $(this).val();
        var y = $('#sl_staff').val();
        var firstDay = new Date(y, m-1, 1);
        var lastDay = new Date(y, m, 0);

        $('#batdau').datepicker("setDate", firstDay );
        $('#ketthuc').datepicker("setDate", lastDay );

    });

    $('#sl_staff').change(function(){
        var y = $(this).val();
        var m = $('#sl_round').val();
        var firstDay = new Date(y, m-1, 1);
        var lastDay = new Date(y, m, 0);

        $('#batdau').datepicker("setDate", firstDay );
        $('#ketthuc').datepicker("setDate", lastDay );

    });
$(".choose_seri").multiselect({});

jQuery(document).ready(function() {
    jQuery('.tabs .tab-links a').on('click', function(e)  {
        var currentAttrValue = jQuery(this).attr('href');

        var id = currentAttrValue.replace('#tab','');
        $('#sl_tha').val(id);
        // Show/Hide Tabs
        jQuery('.tabs ' + currentAttrValue).slideDown(300).siblings().slideUp(300);
 
        // Change/remove current tab to active
        jQuery(this).parent('li').addClass('active').siblings().removeClass('active');
 
        e.preventDefault();
    });

    jQuery('.tabs .tab-left a').on('click', function(e)  {
        var currentAttrValue = jQuery(this).attr('href');
 
        // Show/Hide Tabs
        jQuery('.tabs ' + currentAttrValue).slideDown(300).siblings().slideUp(300);
 
        // Change/remove current tab to active
        jQuery(this).parent('li').addClass('active').siblings().removeClass('active');
 
        e.preventDefault();
    });
});

$('#vehicle').change(function(){
    var vehicle = $(this).val();
    var ngay = $('#export_stock_date').val();
    if (ngay == "") {
        ngay = "<?php echo date('d-m-Y') ?>";
    }
    $.ajax({

        url: '<?php echo BASE_URL ?>/exportstock/getvehicle',

        type: 'POST',

        data: {vehicle:vehicle,ngay:ngay},

        success:function(answer){

            var data = JSON.parse(answer);
            $('#steersman').val(data.name);
            $('#steersman').attr('data',data.id);

        }

    });
});

</script>
<style type="text/css">
.ui-multiselect-menu {
    z-index: 9999999;
}
.ui-widget .ui-widget {
    max-width: 205px;
}
</style>