
<?php
$url_order = 'DESC';
if ($order_by == 'export_stock_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'export_stock_date')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'export_stock_code')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'export_stock_price')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'export_stock_total')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
$i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>
<div class="col-xs-7">
    <div class="pull-left">
      <select id="sl_nv" name="sl_nv" style="width:70px">
       <option value="1">Quý I</option>
       <option value="2">Quý II</option>
       <option value="3">Quý III</option>
       <option value="4">Quý IV</option>
      </select>
      <select id="sl_tha" name="sl_tha" style="width:80px">
       <?php 
          for ($k=1; $k < 13; $k++) { 
              echo '<option value="'.$k.'">Tháng '.$k.'</option>';
          }
       ?>
      </select>
      <select id="sl_na" name="sl_na" style="width:90px">
       <?php 
          $nam = date('Y');
          for ($k=($nam-5); $k < ($nam+5); $k++) { 
              echo '<option value="'.$k.'">Năm '.$k.'</option>';
          }
       ?>
      </select>
      <span class="input-icon">
        <input style="width:120px" autocomplete="off" type="search" class="start-date" name="batdau" id="batdau" placeholder="Chọn ngày" <?php if(isset($batdau)) echo "value='$batdau'"; ?> > 
        <i class="ace-icon fa fa-calendar blue"></i>
      </span>
      <span class="input-icon">
        <input style="width:120px" autocomplete="off" type="search" class="end-date" name="ketthuc" id="ketthuc" placeholder="Chọn ngày" <?php if(isset($ketthuc)) echo "value='$ketthuc'"; ?> >
        <i class="ace-icon fa fa-calendar blue"></i>
      </span>
        
      <input class="btn btn-white btn-primary" type="button" name="xem" id="xem" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  
      
    </div>
</div>
<div class="col-xs-5">
    <div class="tools action-buttons pull-right">
        <?php
        if (isset($filter)) {
            echo '<a class="tooltip-warning" data-rel="tooltip" data-original-title="Dữ liệu đã được lọc bớt"><span class="green"><i class="ace-icon fa fa-filter bigger-150"></i></span></a>';
        }
        ?>
        <select name="m" id="chonloc" class="input-sm" onchange="limit_change($(this).val(),'<?php echo $order_by ?>','<?php echo $order ?>','<?php echo $keyword ?>')">
            <option value="18446744073709">All</option>
            <option value="10">10</option>
            <option value="20">20</option>
            <option value="50">50</option>
            <option value="100">100</option>
            <option value="500">500</option>
        </select>
        <a class="purpose" data-original-title="Thêm mới">
            <i class="ace-icon fa fa-plus-circle bigger-150" onclick="add_click('<?php echo $this->url("exportstock/add") ?>','Thêm phiếu xuất kho mới')"></i>
        </a> 
        <div class="pull-right pos-rel dropdown-hover">
            <button class="btn btn-minier bigger" style="line-height: 26px">
                <i class="ace-icon fa fa-windows icon-only bigger-120"></i>
            </button>

            <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-caret dropdown-close dropdown-menu-right">
                <li>
                    <a class="tooltip-warning" data-rel="tooltip" data-original-title="Tìm">
                        <span class="orange">
                            <i class="ace-icon fa fa-search bigger-150" onclick="search_click()"></i>
                        </span>
                    </a>
                </li>
                <li>
                    <a class="tooltip-success" data-rel="tooltip" data-original-title="Lọc">
                        <span class="green">
                            <i class="ace-icon fa fa-filter bigger-150" onclick="filter_click('<?php echo $this->url("exportstock/filter?page=".$page."&order_by=".$order_by."&order=".$order."&limit=".$limit."&keyword=".$keyword) ?>','Lọc dữ liệu')"></i>
                        </span>
                    </a>
                </li>
                <li>
                    <a class="tooltip-error" data-rel="tooltip" data-original-title="Xóa">
                        <span class="red">
                            <i class="ace-icon fa fa-trash-o bigger-150" onclick="del_click()"></i>
                        </span>
                    </a>
                </li>
                <li>
                    <a class="tooltip-info" data-rel="tooltip" data-original-title="Nhập">
                        <span class="purple">
                            <i class="ace-icon fa fa-cloud-upload bigger-150" onclick="import_click('<?php echo $this->url("exportstock/import") ?>','Nhập dữ liệu từ file Excel')"></i>
                        </span>
                    </a>
                </li>
                <li>
                    
                    <div class="text-center pos-rel dropdown-hover">
                        <a class="tooltip-info" data-rel="tooltip" data-original-title="Xuất">
                            <span class="blue">
                                <i class="ace-icon fa fa-cloud-download bigger-150"></i>
                            </span>
                        </a>
                        <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-caret dropdown-close dropdown-menu-right">
                            <li>
                                <a class="tooltip-success" data-rel="tooltip" data-original-title="Excel">
                                    <span class="green">
                                        <i class="ace-icon fa fa-file-excel-o bigger-130" onclick="export_click('excel','tblexport')"></i>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a class="tooltip-error" data-rel="tooltip" data-original-title="PDF">
                                    <span class="red">
                                        <i class="ace-icon fa fa-file-pdf-o bigger-130" onclick="export_click('pdf','tblexport')"></i>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a class="tooltip-info" data-rel="tooltip" data-original-title="Word">
                                    <span class="blue">
                                        <i class="ace-icon fa fa-file-word-o bigger-130" onclick="export_click('word','tblexport')"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                
            </ul>
        </div>                        
    </div>
</div>
<div class="clearfix"></div>
<div id="content" style="padding:5px;">
   
<table class="table_data" id="tblexport" >
<thead>
    <tr>
    	<th><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall" class="ace ace-checkbox-2" /><span class="lbl"></span></th>
        <th><a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','export_stock_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'export_stock_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a></th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','export_stock_date','<?php echo $url_order ?>')">Ngày <?php if ($order_by == 'export_stock_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','export_stock_code','<?php echo $url_order ?>')">Số phiếu <?php if ($order_by == 'export_stock_code'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','export_stock_total','<?php echo $url_order ?>')">Số lượng <?php if ($order_by == 'export_stock_total'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>  
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','export_stock_price','<?php echo $url_order ?>')">Giá trị <?php if ($order_by == 'export_stock_price'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th> 
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','export_stock_price','<?php echo $url_order ?>')">Nội dung <?php if ($order_by == 'export_stock_price'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            
        </th>
    </tr>
   </thead>
   <tbody>
    <?php foreach ($exportstocks as $exportstock) : ?>
        <tr id="<?php echo $exportstock->export_stock_id ?>" class="edit_tr">
            <td class="text-center"><input name="check[]" type="checkbox" class="checkbox ace" value="<?php echo $exportstock->export_stock_id ?>"><span class="lbl"></span></td>
            <td class="text-center"><?php echo $i++; ?></td>
            <td><?php echo $lib->hien_thi_ngay_thang($exportstock->export_stock_date); ?></td>
            <td><?php echo $exportstock->export_stock_code; ?></td>
            <td><?php echo $lib->formatMoney($exportstock->export_stock_total); ?></td>
            <td><?php echo $lib->formatMoney($exportstock->export_stock_price+$exportstock->export_stock_vat); ?></td>
            <td><?php echo $exportstock->export_stock_comment; ?></td>
            
            <td class="text-right">
                <div class="tools action-buttons">
                    <a class="blue"  onclick="view_click('<?php echo $this->url("exportstock/view/") ?>','Thông tin phiếu xuất kho',<?php echo $exportstock->export_stock_id ?>)">
                        <i class="ace-icon fa fa-info-circle bigger-130"></i>
                    </a>
                    <a class="green"  onclick="edit_click('<?php echo $this->url("exportstock/edit/") ?>','Cập nhật phiếu xuất kho',<?php echo $exportstock->export_stock_id ?>)">
                        <i class="ace-icon fa fa-pencil bigger-130"></i>
                    </a>

                    <a class="red" >
                        <i class="ace-icon fa fa-trash-o bigger-130" onclick="del(<?php echo $exportstock->export_stock_id ?>)"></i>
                    </a>
                </div>
            </td>
        </tr>
    <?php endforeach; ?>
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>
</div>
<script type="text/javascript">
    var ch = "<?php echo $limit ?>";
$('#chonloc option[value='+ch+']').attr('selected','selected');
var nv = "<?php echo $nv ?>";
$('#sl_nv option[value='+nv+']').attr('selected','selected');
var tha = "<?php echo $tha ?>";
$('#sl_tha option[value='+tha+']').attr('selected','selected');
var na = "<?php echo $na ?>";
$('#sl_na option[value='+na+']').attr('selected','selected');

$(document).ready(function(){
    $('#batdau').datepicker({
        format: 'dd/mm/yyyy',
        autoclose: true,
        calendarWeeks: true,
        weekStart: 1, 
        todayHighlight: true
      });
    $('#ketthuc').datepicker({
        format: 'dd/mm/yyyy',
        autoclose: true,
        calendarWeeks: true,
        weekStart: 1, 
        todayHighlight: true
      });
});

$('#sl_nv').change(function(){
      var q = $(this).val();
      var y = $('#sl_na').val();
      var m,n;
      
      switch(q) {
        case "1":
            m=1;
            n=3;
            break;
        case "2":
            m=4;
            n=6;
            break;
        case "3":
            m=7;
            n=9;
            break;
        case "4":
            m=10;
            n=12;
            break;
      }

      var firstDay = new Date(y, m-1, 1);
      var lastDay = new Date(y, n, 0);

      $('#batdau').datepicker("setDate", firstDay );
      $('#ketthuc').datepicker("setDate", lastDay );

  });

$('#sl_tha').change(function(){
      var m = $(this).val();
      var y = $('#sl_na').val();
      var firstDay = new Date(y, m-1, 1);
      var lastDay = new Date(y, m, 0);

      $('#batdau').datepicker("setDate", firstDay );
      $('#ketthuc').datepicker("setDate", lastDay );

  });

  $('#sl_na').change(function(){
      var y = $(this).val();
      var m = $('#sl_tha').val();
      var firstDay = new Date(y, m-1, 1);
      var lastDay = new Date(y, m, 0);

      $('#batdau').datepicker("setDate", firstDay );
      $('#ketthuc').datepicker("setDate", lastDay );

  });
</script>