
<div class="tabbable">
  
    <div class="col-md-3 col-xs-6">
          <label for="export_stock_date">Ngày</label>
          <div class="input-group">
            <input class="input-mask-date" type="text" id="export_stock_date" name="export_stock_date" tabindex="1" required="required" value="<?php echo $lib->hien_thi_ngay_thang($export_stock_data->export_stock_date) ?>">
          </div>
          
          
        </div>
        <div class="col-md-3 col-xs-6">
          <label for="export_stock_code">Số phiếu</label>
          <div class="input-group">
            <input type="text" id="export_stock_code" name="export_stock_code" tabindex="2" value="<?php echo $export_stock_data->export_stock_code ?>" required="required">
          </div>
        </div>
        <div class="col-md-3 col-xs-6">
          <label for="export_stock_comment">Nội dung </label>
          <div class="input-group">
            <input type="text" id="export_stock_comment" name="export_stock_comment" tabindex="3" value="<?php echo $export_stock_data->export_stock_comment ?>">
          </div>
          
        </div>
        <div class="col-md-3 col-xs-6">
          <label for="export_stock_house">Kho xuất <a title="Thêm kho mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("house/add") ?>','Thêm kho mới','export_stock_house','<?php echo $this->url("house/gethouse") ?>','add_house')"></i></a></label>
          <div class="input-group">
            <select class="form-control select2" id="export_stock_house" name="export_stock_house" tabindex="4">
              <?php foreach ($houses as $house) { ?>
                <option value="<?php echo $export_stock_data->export_stock_house==$house->house_id?'selected="selected"':null ?>" value="<?php echo $house->house_id ?>"><?php echo $house->house_name ?></option>
              <?php } ?>
            </select>
          </div>
          
        </div>

        <div class="clearfix"></div>
        <div class="hr hr-8 dotted hr-double"></div>
        <div style="background: #73737326; max-height: 500px; overflow: auto;">
            <table id="dataTable_exportstock" style="width: 100%;">
                <tbody>
                <?php if (count($spare_part_codes)>0) { ?>
                <?php foreach ($spare_part_codes as $spare_part_code) { 
                  $sl = $spare_part_data[$spare_part_code->spare_part_code_id]['sl'];
                ?>
                <tr>
                    <td style="padding-right: 10px;"><input type="checkbox" name="chk" data="<?php echo $spare_part_code->spare_part_code_id ?>" title="<?php echo $export_stock_data->export_stock_id ?>"></td>
                    <td>
                      
                        <table style="width:100%;">
                            <tbody>
                              <tr>
                                <td>
                                  <label>Mã sản phẩm</label>
                                  <div class="input-group">
                                    <input type="text" class="spare_part_code" name="spare_part_code[]" tabindex="5" required="required" value="<?php echo $spare_part_code->code ?>">
                                    <ul class="name_list_id"></ul>
                                  </div>
                                </td>
                                <td>
                                  <label>Tên sản phẩm</label>
                                  <div class="input-group">
                                    <input type="text" class="spare_part_name" name="spare_part_name[]" tabindex="6" required="required" value="<?php echo $spare_part_code->name ?>" data="<?php echo $spare_part_code->spare_part_code_id ?>">
                                    <ul class="name_list_id_2"></ul>
                                  </div>
                                </td>
                                <td colspan="2">
                                  <label>Chọn 1 sản phẩm</label>
                                  <div class="input-group">
                                    <select class="choose_seri multiselect" name="choose_seri[]" tabindex="7" required="required" multiple="" data="0">
                                      <?php foreach ($spare_parts[$spare_part_code->spare_part_code_id] as $spare_part) { ?>
                                        <option selected="selected" title="<?php echo $spare_part->spare_stock_number ?>" value="<?php echo $spare_part->spare_part_id ?>"><?php echo $spare_part->spare_part_seri ?> [<?php echo $spare_part->spare_stock_number ?>]</option>
                                      <?php } ?>
                                      <?php echo isset($stock[$spare_part_code->spare_part_code_id])?$stock[$spare_part_code->spare_part_code_id]:null ?>
                                    </select>
                                  </div>
                                </td>
                                
                              </tr>
                              <tr>
                                <td>
                                  <label>Số lượng</label>
                                  <div class="input-group">
                                    <input min="0" max="<?php echo $sl ?>" type="text" class="spare_stock_number numbers" name="spare_stock_number[]" tabindex="8" value="<?php echo $sl ?>">
                                  </div>
                                </td>
                                <td>
                                  <label>Đơn vị tính</label>
                                  <div class="input-group">
                                    <input type="text" class="spare_part_unit" name="spare_part_unit[]" tabindex="9" value="<?php echo $spare_part_data[$spare_part_code->spare_part_code_id]['unit'] ?>">
                                  </div>
                                </td>
                                <td>
                                  <label>Đơn giá</label>
                                  <div class="input-group">
                                    <input type="text" class="spare_stock_price numbers" name="spare_stock_price[]" tabindex="10" value="<?php echo $lib->formatMoney($spare_part_data[$spare_part_code->spare_part_code_id]['price']) ?>">
                                  </div>
                                </td>
                                <td>
                                  <label>VAT</label>
                                  <div class="input-group">
                                    <input style="width: 50px" type="text" class="spare_stock_vat_percent numbers" name="spare_stock_vat_percent[]" tabindex="11" placeholder="%" value="<?php echo $lib->formatMoney($spare_part_data[$spare_part_code->spare_part_code_id]['percent']) ?>">
                                    <input style="width: 100px" type="text" class="spare_stock_vat_price numbers" name="spare_stock_vat_price[]" tabindex="12" value="<?php echo $lib->formatMoney($spare_part_data[$spare_part_code->spare_part_code_id]['vat']*$sl) ?>">
                                  </div>
                                </td>
                                
                                
                              </tr>
                              
                        </tbody></table>
                        <div class="hr hr-8 dotted hr-double"></div>
                    </td>
                    
                </tr>
              <?php 
              }}else{ ?>
                <tr>
                  <td style="padding-right: 10px;"><input type="checkbox" name="chk"></td>
                  <td>
                    
                      <table style="width:100%;">
                          <tbody>
                            <tr>
                              <td>
                                <label>Mã sản phẩm</label>
                                <div class="input-group">
                                  <input type="text" class="spare_part_code" name="spare_part_code[]" tabindex="5" required="required">
                                  <ul class="name_list_id"></ul>
                                </div>
                              </td>
                              <td>
                                <label>Tên sản phẩm</label>
                                <div class="input-group">
                                  <input type="text" class="spare_part_name" name="spare_part_name[]" tabindex="6" required="required">
                                  <ul class="name_list_id_2"></ul>
                                </div>
                              </td>
                              <td colspan="2">
                                <label>Chọn 1 sản phẩm</label>
                                <div class="input-group">
                                  <select class="choose_seri multiselect" name="choose_seri[]" tabindex="7" required="required" multiple="" data="0">
                                    
                                  </select>
                                </div>
                              </td>
                              
                            </tr>
                            <tr>
                              <td>
                                <label>Số lượng</label>
                                <div class="input-group">
                                  <input min="0" max="0" type="text" class="spare_stock_number numbers" name="spare_stock_number[]" tabindex="8" value="0">
                                </div>
                              </td>
                              <td>
                                <label>Đơn vị tính</label>
                                <div class="input-group">
                                  <input type="text" class="spare_part_unit" name="spare_part_unit[]" tabindex="9">
                                </div>
                              </td>
                              <td>
                                <label>Đơn giá</label>
                                <div class="input-group">
                                  <input type="text" class="spare_stock_price numbers" name="spare_stock_price[]" tabindex="10" >
                                </div>
                              </td>
                              <td>
                                <label>VAT</label>
                                <div class="input-group">
                                  <input style="width: 50px" type="text" class="spare_stock_vat_percent numbers" name="spare_stock_vat_percent[]" tabindex="11" placeholder="%">
                                  <input style="width: 100px" type="text" class="spare_stock_vat_price numbers" name="spare_stock_vat_price[]" tabindex="12" >
                                </div>
                              </td>
                              
                              
                            </tr>
                            
                      </tbody></table>
                      <div class="hr hr-8 dotted hr-double"></div>
                  </td>
                  
              </tr>
              <?php } ?>
            </tbody>
            </table>
         
        </div>
            <input type="button" value="Thêm" onclick="addRow_exportstock('dataTable_exportstock')">

            <input type="button" value="Xóa" onclick="deleteRow_exportstock('dataTable_exportstock')">
 
</div>
<script type="text/javascript">
  $(document).ready(function(){
  $('.multiselect').multiselect({
   enableFiltering: true,
   enableCaseInsensitiveFiltering: true,
   maxHeight: 350,
   enableHTML: true,
   nonSelectedText: 'Chọn',
   includeSelectAllOption: true,
   buttonClass: 'btn btn-white btn-primary',
   templates: {
    button: '<button type="button" class="multiselect dropdown-toggle" data-toggle="dropdown"><span class="multiselect-selected-text"></span> &nbsp;<b class="fa fa-caret-down"></b></button>',
    ul: '<ul class="multiselect-container dropdown-menu"></ul>',
    filter: '<li class="multiselect-item filter"><div class="input-group"><span class="input-group-addon"><i class="fa fa-search"></i></span><input class="form-control multiselect-search" type="text"></div></li>',
    filterClearBtn: '<span class="input-group-btn"><button class="btn btn-default btn-white btn-grey multiselect-clear-filter" type="button"><i class="fa fa-times-circle red2"></i></button></span>',
    li: '<li><a tabindex="0"><label></label></a></li>',
        divider: '<li class="multiselect-item divider"></li>',
        liGroup: '<li class="multiselect-item multiselect-group"><label></label></li>'
   }
  });
});
</script>