<script type="text/javascript">
$(document).ready(function(){
	
			// Validate form
			$("#add_spare_part_code").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
				rules: {
				},
        submitHandler: function(form) {
                
          var formData = new FormData($("#add_spare_part_code")[0]);
          
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/sparepartcode/addsparepartcode", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: formData, // giá trị post
              cache: false,
              contentType: false,
              processData: false,
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error_spare_part_code').hide();
                  $('#error_spare_part_code').slideToggle(100); // hiển thị thẻ div success
                  $('#error_spare_part_code').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error_spare_part_code').fadeOut(10000);

              }
          });
          return false;
           
       }
					 
				 
			});
	
});
</script>
     
<div class="login_body">
  
      <form id="add_spare_part_code" method="post" action="" autocomplete="off">
          <table style="margin-top:20px;">
            <tr>
                <td>Mã </td>
                <td><input type="text" id="code" name="code" tabindex="1" required="required"></td>
            </tr>
            <tr>
                <td>Tên </td>
                <td><input type="text" id="name" name="name" tabindex="2" required="required"></td>
            </tr>
        </table> 
    </form>
</div>
<div id="error_spare_part_code" class="error"><?php echo isset($error) ? $error : null; ?></div>


