<script type="text/javascript">
$(document).ready(function(){
	
			// Validate form
			$("#edit_shipmenttemp").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
        ignore: "",
        rules: {
        },
        errorPlacement: function (error, element) {
          if(element.is('input[type=checkbox]') || element.is('input[type=radio]')) {
            var controls = element.closest('div[class*="col-"]');
            if(controls.find(':checkbox,:radio').length > 1) controls.append(error);
            else error.insertAfter(element.nextAll('.lbl:eq(0)').eq(0));
          }
          else if(element.is('.select2')) {
            error.insertAfter(element.siblings('[class*="select2-container"]:eq(0)'));
          }
          else if(element.is('.chosen-select')) {
            error.insertAfter(element.siblings('[class*="chosen-container"]:eq(0)'));
          }
          else error.insertAfter(element.parent());
        },
        submitHandler: function(form) {
          var formData = new FormData($("#edit_shipmenttemp")[0]);
          formData.append('shipment_temp_id', '<?php echo $shipment_temp_data->shipment_temp_id ?>');
          
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/shipmenttemp/editshipmenttemp", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: formData, // giá trị post
              cache: false,
              contentType: false,
              processData: false,
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error_shipmenttemp').hide();
                  $('#error_shipmenttemp').slideToggle(100); // hiển thị thẻ div success
                  $('#error_shipmenttemp').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error_shipmenttemp').fadeOut(10000);

              }
          });
          return false;
           
       }
					 
				 
			});
	
});
</script>

        <div class="login_body">
         
              <form id="edit_shipmenttemp" method="post" action="" autocomplete="off">
                  <table style="margin-top:20px;">
                    
                    <tr>
                        <td>Sản lượng nhận</td>
                        <td><input type="text" class="numbers" id="shipment_temp_ton" name="shipment_temp_ton" tabindex="1" required="required" autofocus value="<?php echo $shipment_temp_data->shipment_temp_ton ?>"></td>
                        
                    </tr>
                    <tr>
                        <td>Số lượng xe</td>
                        <td><input type="text" class="numbers" id="shipment_temp_number" name="shipment_temp_number" tabindex="2" value="<?php echo $shipment_temp_data->shipment_temp_number ?>"></td>
                    </tr>
                </table> 
            </form>
        </div>
        <div id="error_shipmenttemp" class="error"><?php echo isset($error) ? $error : null; ?></div>


