
        <div class="login_body">
         
                  <table>
                    
                    <tr>
                        <td>Sản lượng nhận</td>
                        <td><input type="text" class="numbers" id="shipment_temp_ton" name="shipment_temp_ton" tabindex="1" required="required" autofocus value="<?php echo $shipment_temp_data->shipment_temp_ton ?>"></td>
                        
                    </tr>
                    <tr>
                        <td>Số lượng xe</td>
                        <td><input type="text" class="numbers" id="shipment_temp_number" name="shipment_temp_number" tabindex="2" value="<?php echo $shipment_temp_data->shipment_temp_number ?>"></td>
                    </tr>
                </table> 
            
        </div>
        <div id="error_shipmenttemp" class="error"><?php echo isset($error) ? $error : null; ?></div>


