<script type="text/javascript">
$(document).ready(function(){
	$( ".select2" ).select2({dropdownAutoWidth : true});
			// Validate form
			$("#add_costlist").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
        ignore: "",
        rules: {
        },
        errorPlacement: function (error, element) {
          if(element.is('input[type=checkbox]') || element.is('input[type=radio]')) {
            var controls = element.closest('div[class*="col-"]');
            if(controls.find(':checkbox,:radio').length > 1) controls.append(error);
            else error.insertAfter(element.nextAll('.lbl:eq(0)').eq(0));
          }
          else if(element.is('.select2')) {
            error.insertAfter(element.siblings('[class*="select2-container"]:eq(0)'));
          }
          else if(element.is('.chosen-select')) {
            error.insertAfter(element.siblings('[class*="chosen-container"]:eq(0)'));
          }
          else error.insertAfter(element.parent());
        },
        submitHandler: function(form) {
                
          var formData = new FormData($("#add_costlist")[0]);
          
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/costlist/addcostlist", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: formData, // giá trị post
              cache: false,
              contentType: false,
              processData: false,
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error_costlist').hide();
                  $('#error_costlist').slideToggle(100); // hiển thị thẻ div success
                  $('#error_costlist').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error_costlist').fadeOut(10000);

              }
          });
          return false;
           
       }
					 
				 
			});
	
});
</script>
<div id="error_costlist" class="error"><?php echo isset($error) ? $error : null; ?></div>
<div class="login_body">
  
      <form id="add_costlist" method="post" action="" autocomplete="off">
        <div class="col-xs-12">
          <table>
            <tr>
                <td>Mã chi phí </td>
                <td><input type="text" id="cost_list_code" name="cost_list_code" tabindex="1" autofocus required="required"></td>
                
            </tr>
            <tr>
                <td>Tên chi phí </td>
                <td><input type="text" id="cost_list_name" name="cost_list_name" tabindex="2" required="required"></td>
                
            </tr>
            <tr>
                <td>Loại chi phí </td>
                <td>
                  <select class="form-control select2" id="cost_list_type" name="cost_list_type" required="required" tabindex="3">
                    <?php foreach ($cost_types as $cost_type) { ?>
                      <option value="<?php echo $cost_type->cost_type_id ?>"><?php echo $cost_type->cost_type_name ?></option>
                    <?php } ?>
                  </select>
                </td>
            </tr>
            
        </table> 
        </div>
          
    </form>
</div>