<script type="text/javascript">
$(document).ready(function(){
	
			// Validate form
			$("#add_unit").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
				rules: {
				},
        submitHandler: function(form) {
                
          var formData = new FormData($("#add_unit")[0]);
          
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/unit/addunit", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: formData, // giá trị post
              cache: false,
              contentType: false,
              processData: false,
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error_unit').hide();
                  $('#error_unit').slideToggle(100); // hiển thị thẻ div success
                  $('#error_unit').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error_unit').fadeOut(10000);

              }
          });
          return false;
           
       }
					 
				 
			});
	
});
</script>
     
<div class="login_body">
  
      <form id="add_unit" method="post" action="" autocomplete="off">
          <table style="margin-top:20px;">
            <tr>
                <td>Tên đơn vị tính </td>
                <td><input type="text" id="unit_name" name="unit_name" tabindex="1" required="required"></td>
            </tr>
        </table> 
    </form>
</div>
<div id="error_unit" class="error"><?php echo isset($error) ? $error : null; ?></div>


