<script type="text/javascript">
$(document).ready(function(){
	
			// Validate form
			$("#edit_unit").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
        ignore: "",
        rules: {
        },
        errorPlacement: function (error, element) {
          if(element.is('input[type=checkbox]') || element.is('input[type=radio]')) {
            var controls = element.closest('div[class*="col-"]');
            if(controls.find(':checkbox,:radio').length > 1) controls.append(error);
            else error.insertAfter(element.nextAll('.lbl:eq(0)').eq(0));
          }
          else if(element.is('.select2')) {
            error.insertAfter(element.siblings('[class*="select2-container"]:eq(0)'));
          }
          else if(element.is('.chosen-select')) {
            error.insertAfter(element.siblings('[class*="chosen-container"]:eq(0)'));
          }
          else error.insertAfter(element.parent());
        },
        submitHandler: function(form) {
          
          var formData = new FormData($("#edit_unit")[0]);
          formData.append('unit_id', '<?php echo $unit_data->unit_id ?>');
          
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/unit/editunit", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: formData, // giá trị post
              cache: false,
              contentType: false,
              processData: false,
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error_unit').hide();
                  $('#error_unit').slideToggle(100); // hiển thị thẻ div success
                  $('#error_unit').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error_unit').fadeOut(10000);

              }
          });
          return false;
           
       }
					 
				 
			});
	
});
</script>

        <div class="login_body">
         
              <form id="edit_unit" method="post" action="" autocomplete="off">
                  <table style="margin-top:20px;">
                    
                    <tr>
                        <td>Tên đơn vị tính</td>
                        <td><input type="text" id="unit_name" name="unit_name" tabindex="1" required="required" value="<?php echo $unit_data->unit_name ?>"></td>
                    </tr>
                </table> 
            </form>
        </div>
        <div id="error_unit" class="error"><?php echo isset($error) ? $error : null; ?></div>


