
        <div class="login_body">
         
                  <table style="margin-top:20px;">
                    
                    <tr>
                        <td>Tên đơn vị tính</td>
                        <td><input type="text" id="unit_name" name="unit_name" tabindex="1" required="required" value="<?php echo $unit_data->unit_name ?>"></td>
                    </tr>
                </table> 
           
        </div>
        <div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>


