<script src="https://apis.google.com/js/platform.js" async defer></script>
<div class="tabbable">
  <ul class="nav nav-tabs padding-18 tab-size-bigger" id="myTab">
    <li class="active">
      <a data-toggle="tab" href="#faq-tab-1">
        <i class="blue ace-icon fa fa-question-circle bigger-120"></i>
        General
      </a>
    </li>

    <li>
      <a data-toggle="tab" href="#faq-tab-2">
        <i class="green ace-icon fa fa-user bigger-120"></i>
        Account
      </a>
    </li>

    <li>
      <a data-toggle="tab" href="#faq-tab-3">
        <i class="orange ace-icon fa fa-credit-card bigger-120"></i>
        Payments
      </a>
    </li>

    <li class="dropdown">
      <a data-toggle="dropdown" class="dropdown-toggle" href="#">
        <i class="purple ace-icon fa fa-magic bigger-120"></i>

        Misc
        <i class="ace-icon fa fa-caret-down"></i>
      </a>

      <ul class="dropdown-menu dropdown-lighter dropdown-125">
        <li>
          <a data-toggle="tab" href="#faq-tab-4"> Affiliates </a>
        </li>

        <li>
          <a data-toggle="tab" href="#faq-tab-4"> Merchants </a>
        </li>
      </ul>
    </li><!-- /.dropdown -->
  </ul>

  <div class="tab-content no-border padding-24">
    <div id="faq-tab-1" class="tab-pane fade in active">
      <h4 class="blue">
        <i class="ace-icon fa fa-check bigger-110"></i>
        General Questions
      </h4>

      <div class="space-8"></div>

      <div id="faq-list-1" class="panel-group accordion-style1 accordion-style2">
        <div class="panel panel-default">
          <div class="panel-heading">
            <a href="#faq-1-1" data-parent="#faq-list-1" data-toggle="collapse" class="accordion-toggle collapsed">
              <i class="ace-icon fa fa-chevron-left pull-right" data-icon-hide="ace-icon fa fa-chevron-down" data-icon-show="ace-icon fa fa-chevron-left"></i>

              <i class="ace-icon fa fa-user bigger-130"></i>
              &nbsp; High life accusamus terry richardson ad squid?
            </a>
          </div>

          <div class="panel-collapse collapse" id="faq-1-1">
            <div class="panel-body">
              Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.
            </div>
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading">
            <a href="#faq-1-2" data-parent="#faq-list-1" data-toggle="collapse" class="accordion-toggle collapsed">
              <i class="ace-icon fa fa-chevron-left pull-right" data-icon-hide="ace-icon fa fa-chevron-down" data-icon-show="ace-icon fa fa-chevron-left"></i>

              <i class="ace-icon fa fa-sort-amount-desc"></i>
              &nbsp; Can I have nested questions?
            </a>
          </div>

          <div class="panel-collapse collapse" id="faq-1-2">
            <div class="panel-body">
              <div id="faq-list-nested-1" class="panel-group accordion-style1 accordion-style2">
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <a href="#faq-list-1-sub-1" data-parent="#faq-list-nested-1" data-toggle="collapse" class="accordion-toggle collapsed">
                      <i class="ace-icon fa fa-plus smaller-80 middle" data-icon-hide="ace-icon fa fa-minus" data-icon-show="ace-icon fa fa-plus"></i>&nbsp;
     Enim eiusmod high life accusamus terry?
                    </a>
                  </div>

                  <div class="panel-collapse collapse" id="faq-list-1-sub-1">
                    <div class="panel-body">
                      Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.
                    </div>
                  </div>
                </div>

                <div class="panel panel-default">
                  <div class="panel-heading">
                    <a href="#faq-list-1-sub-2" data-parent="#faq-list-nested-1" data-toggle="collapse" class="accordion-toggle collapsed">
                      <i class="ace-icon fa fa-plus smaller-80 middle" data-icon-hide="ace-icon fa fa-minus" data-icon-show="ace-icon fa fa-plus"></i>&nbsp;
    Food truck quinoa nesciunt laborum eiusmod?
                    </a>
                  </div>

                  <div class="panel-collapse collapse" id="faq-list-1-sub-2">
                    <div class="panel-body">
                      Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.
                    </div>
                  </div>
                </div>

                <div class="panel panel-default">
                  <div class="panel-heading">
                    <a href="#faq-list-1-sub-3" data-parent="#faq-list-nested-1" data-toggle="collapse" class="accordion-toggle collapsed">
                      <i class="ace-icon fa fa-plus smaller-80 middle" data-icon-hide="ace-icon fa fa-minus" data-icon-show="ace-icon fa fa-plus"></i>&nbsp;
    Cupidatat skateboard dolor brunch?
                    </a>
                  </div>

                  <div class="panel-collapse collapse" id="faq-list-1-sub-3">
                    <div class="panel-body">
                      Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et.
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading">
            <a href="#faq-1-3" data-parent="#faq-list-1" data-toggle="collapse" class="accordion-toggle collapsed">
              <i class="ace-icon fa fa-chevron-left pull-right" data-icon-hide="ace-icon fa fa-chevron-down" data-icon-show="ace-icon fa fa-chevron-left"></i>

              <i class="ace-icon fa fa-credit-card bigger-130"></i>
              &nbsp; Single-origin coffee nulla assumenda shoreditch et?
            </a>
          </div>

          <div class="panel-collapse collapse" id="faq-1-3">
            <div class="panel-body">
              Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et.
            </div>
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading">
            <a href="#faq-1-4" data-parent="#faq-list-1" data-toggle="collapse" class="accordion-toggle collapsed">
              <i class="ace-icon fa fa-chevron-left pull-right" data-icon-hide="ace-icon fa fa-chevron-down" data-icon-show="ace-icon fa fa-chevron-left"></i>

              <i class="ace-icon fa fa-files-o bigger-130"></i>
              &nbsp; Sunt aliqua put a bird on it squid?
            </a>
          </div>

          <div class="panel-collapse collapse" id="faq-1-4">
            <div class="panel-body">
              Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et.
            </div>
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading">
            <a href="#faq-1-5" data-parent="#faq-list-1" data-toggle="collapse" class="accordion-toggle collapsed">
              <i class="ace-icon fa fa-chevron-left pull-right" data-icon-hide="ace-icon fa fa-chevron-down" data-icon-show="ace-icon fa fa-chevron-left"></i>

              <i class="ace-icon fa fa-cog bigger-130"></i>
              &nbsp; Brunch 3 wolf moon tempor sunt aliqua put?
            </a>
          </div>

          <div class="panel-collapse collapse" id="faq-1-5">
            <div class="panel-body">
              Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et.
            </div>
          </div>
        </div>
      </div>
    </div>

    <div id="faq-tab-2" class="tab-pane fade">
      <h4 class="blue">
        <i class="green ace-icon fa fa-user bigger-110"></i>
        Account Questions
      </h4>

      <div class="space-8"></div>

      <div id="faq-list-2" class="panel-group accordion-style1 accordion-style2">
        <div class="panel panel-default">
          <div class="panel-heading">
            <a href="#faq-2-1" data-parent="#faq-list-2" data-toggle="collapse" class="accordion-toggle collapsed">
              <i class="ace-icon fa fa-chevron-right smaller-80" data-icon-hide="ace-icon fa fa-chevron-down align-top" data-icon-show="ace-icon fa fa-chevron-right"></i>&nbsp;
Enim eiusmod high life accusamus terry richardson?
            </a>
          </div>

          <div class="panel-collapse collapse" id="faq-2-1">
            <div class="panel-body">
              Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et.
            </div>
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading">
            <a href="#faq-2-2" data-parent="#faq-list-2" data-toggle="collapse" class="accordion-toggle collapsed">
              <i class="ace-icon fa fa-chevron-right smaller-80" data-icon-hide="ace-icon fa fa-chevron-down align-top" data-icon-show="ace-icon fa fa-chevron-right"></i>&nbsp;
Single-origin coffee nulla assumenda shoreditch et?
            </a>
          </div>

          <div class="panel-collapse collapse" id="faq-2-2">
            <div class="panel-body">
              Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et.
            </div>
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading">
            <a href="#faq-2-3" data-parent="#faq-list-2" data-toggle="collapse" class="accordion-toggle collapsed">
              <i class="ace-icon fa fa-chevron-right middle smaller-80" data-icon-hide="ace-icon fa fa-chevron-down align-top" data-icon-show="ace-icon fa fa-chevron-right"></i>&nbsp;
Sunt aliqua put a bird on it squid?
            </a>
          </div>

          <div class="panel-collapse collapse" id="faq-2-3">
            <div class="panel-body">
              Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et.
            </div>
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading">
            <a href="#faq-2-4" data-parent="#faq-list-2" data-toggle="collapse" class="accordion-toggle collapsed">
              <i class="ace-icon fa fa-chevron-right smaller-80" data-icon-hide="ace-icon fa fa-chevron-down align-top" data-icon-show="ace-icon fa fa-chevron-right"></i>&nbsp;
Brunch 3 wolf moon tempor sunt aliqua put?
            </a>
          </div>

          <div class="panel-collapse collapse" id="faq-2-4">
            <div class="panel-body">
              Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et.
            </div>
          </div>
        </div>
      </div>
    </div>

    <div id="faq-tab-3" class="tab-pane fade">
      <h4 class="blue">
        <i class="orange ace-icon fa fa-credit-card bigger-110"></i>
        Payment Questions
      </h4>

      <div class="space-8"></div>

      <div id="faq-list-3" class="panel-group accordion-style1 accordion-style2">
        <div class="panel panel-default">
          <div class="panel-heading">
            <a href="#faq-3-1" data-parent="#faq-list-3" data-toggle="collapse" class="accordion-toggle collapsed">
              <i class="ace-icon fa fa-plus smaller-80" data-icon-hide="ace-icon fa fa-minus" data-icon-show="ace-icon fa fa-plus"></i>&nbsp;
Enim eiusmod high life accusamus terry richardson?
            </a>
          </div>

          <div class="panel-collapse collapse" id="faq-3-1">
            <div class="panel-body">
              Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et.
            </div>
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading">
            <a href="#faq-3-2" data-parent="#faq-list-3" data-toggle="collapse" class="accordion-toggle collapsed">
              <i class="ace-icon fa fa-plus smaller-80" data-icon-hide="ace-icon fa fa-minus" data-icon-show="ace-icon fa fa-plus"></i>&nbsp;
Single-origin coffee nulla assumenda shoreditch et?
            </a>
          </div>

          <div class="panel-collapse collapse" id="faq-3-2">
            <div class="panel-body">
              Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et.
            </div>
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading">
            <a href="#faq-3-3" data-parent="#faq-list-3" data-toggle="collapse" class="accordion-toggle collapsed">
              <i class="ace-icon fa fa-plus smaller-80" data-icon-hide="ace-icon fa fa-minus" data-icon-show="ace-icon fa fa-plus"></i>&nbsp;
Sunt aliqua put a bird on it squid?
            </a>
          </div>

          <div class="panel-collapse collapse" id="faq-3-3">
            <div class="panel-body">
              Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et.
            </div>
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading">
            <a href="#faq-3-4" data-parent="#faq-list-3" data-toggle="collapse" class="accordion-toggle collapsed">
              <i class="ace-icon fa fa-plus smaller-80" data-icon-hide="ace-icon fa fa-minus" data-icon-show="ace-icon fa fa-plus"></i>&nbsp;
Brunch 3 wolf moon tempor sunt aliqua put?
            </a>
          </div>

          <div class="panel-collapse collapse" id="faq-3-4">
            <div class="panel-body">
              Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et.
            </div>
          </div>
        </div>
      </div>
    </div>

    <div id="faq-tab-4" class="tab-pane fade">
      <h4 class="blue">
        <i class="purple ace-icon fa fa-magic bigger-110"></i>
        Miscellaneous Questions
      </h4>

      <div class="space-8"></div>

      <div id="faq-list-4" class="panel-group accordion-style1 accordion-style2">
        <div class="panel panel-default">
          <div class="panel-heading">
            <a href="#faq-4-1" data-parent="#faq-list-4" data-toggle="collapse" class="accordion-toggle collapsed">
              <i class="ace-icon fa fa-hand-o-right" data-icon-hide="ace-icon fa fa-hand-o-down" data-icon-show="ace-icon fa fa-hand-o-right"></i>&nbsp;
Enim eiusmod high life accusamus terry richardson?
            </a>
          </div>

          <div class="panel-collapse collapse" id="faq-4-1">
            <div class="panel-body">
              Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et.
            </div>
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading">
            <a href="#faq-4-2" data-parent="#faq-list-4" data-toggle="collapse" class="accordion-toggle collapsed">
              <i class="ace-icon fa fa-frown-o bigger-120" data-icon-hide="ace-icon fa fa-smile-o" data-icon-show="ace-icon fa fa-frown-o"></i>&nbsp;
Single-origin coffee nulla assumenda shoreditch et?
            </a>
          </div>

          <div class="panel-collapse collapse" id="faq-4-2">
            <div class="panel-body">
              Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et.
            </div>
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading">
            <a href="#faq-4-3" data-parent="#faq-list-4" data-toggle="collapse" class="accordion-toggle collapsed">
              <i class="ace-icon fa fa-plus smaller-80" data-icon-hide="ace-icon fa fa-minus" data-icon-show="ace-icon fa fa-plus"></i>&nbsp;
Sunt aliqua put a bird on it squid?
            </a>
          </div>

          <div class="panel-collapse collapse" id="faq-4-3">
            <div class="panel-body">
              Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et.
            </div>
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading">
            <a href="#faq-4-4" data-parent="#faq-list-4" data-toggle="collapse" class="accordion-toggle collapsed">
              <i class="ace-icon fa fa-plus smaller-80" data-icon-hide="ace-icon fa fa-minus" data-icon-show="ace-icon fa fa-plus"></i>&nbsp;
Brunch 3 wolf moon tempor sunt aliqua put?
            </a>
          </div>

          <div class="panel-collapse collapse" id="faq-4-4">
            <div class="panel-body">
              Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et.
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <div class="help-block text-center">
      <button type="button" class="btn btn-danger btn-arrow-right"><i class="fa fa-line-chart"></i> SALES</button>
      <button type="button" class="btn btn-default btn-arrow-right"><i class="fa fa-truck"></i> TRANSPORT</button>
      <button type="button" class="btn btn-info btn-arrow-right"><i class="fa fa-gear"></i> WAREHOUSE</button>
      <button type="button" class="btn btn-primary btn-arrow-right"><i class="fa fa-dollar"></i> FINANCE</button>
      <button type="button" class="btn btn-success btn-arrow-right"><i class="fa fa-user"></i> HUMAN RESOURCES</button>
    </div>
    
    <div class="text-center">
      SUPPORT CENTER <br>
      <i class="fa fa-phone"></i> +84 129 279 1234  &nbsp; &nbsp; &nbsp; &nbsp; <i class="fa fa-commenting"></i> +84 902 085 911 <br>
      <i class="fa fa-envelope"></i> ngoton@tinhoctainha.com - ngoton.it@gmail.com <br>
      <i class="fa fa-globe"></i> www.tinhoctainha.com
    </div>

    <div class="lockscreen-footer text-center">
      Copyright &copy; <?php echo date('Y') ?> <b><a href="http://www.tinhoctainha.com" class="text-black">TMS</a></b>
    </div>
  </div><!-- /.col -->
</div>


<div class="hisella-messages">

  <div class="hisella-messages-outer">
    
    <div class="hangout-messages">
      <g:hangout render="createhangout"
        invites="[{ id : 'ngoton.it@gmail.com', invite_type : 'EMAIL' }]">
      </g:hangout>
    </div>
    <div id="hisella-minimize">Facebook chat</div>
    <div id="hisella-facebook" class='fb-page' data-adapt-container-width='true' data-height='300' data-hide-cover='false' data-href='https://www.facebook.com/tinhoctainha/' data-show-facepile='true' data-show-posts='false' data-small-header='false' data-tabs='messages' data-width='250'></div>
  </div>
</div>
<style type="text/css">

.hisella-messages { position: fixed; bottom: 0; right: 0; z-index: 999999; }

.hisella-messages-outer { position: relative; }

#hisella-minimize { background: #3b5998; font-size: 14px; color: #fff; padding: 3px 10px; position: absolute; top: -34px; left: -1px; border: 1px solid #E9EAED; cursor: pointer; }

#hisella-facebook { opacity:0; } .hisella-messages { bottom: -300px; right: -100px; }

</style>

<div id='fb-root'></div>

<script>

(function($) { $(document).ready(function(){ $( '#hisella-minimize' ).click( function() { if( $( '#hisella-facebook' ).css( 'opacity' ) == 0 ) { $( '#hisella-facebook' ).css( 'opacity', 1 ); $( '.hisella-messages' ).animate( { right: '0' } ).animate( { bottom: '0' } ); } else { $( '.hisella-messages' ).animate( { bottom: '-300px' } ).animate( { right: '-100px' }, 400, function(){ $( '#hisella-facebook' ).css( 'opacity', 0 ) } ); } } ) }); })(jQuery);

(function(d, s, id) {



  var js, fjs = d.getElementsByTagName(s)[0];



  if (d.getElementById(id)) return;



  js = d.createElement(s); js.id = id;



  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.4";



  fjs.parentNode.insertBefore(js, fjs);



}(document, 'script', 'facebook-jssdk'));

</script>






<style type="text/css">
.btn { /* just for this demo. */
    margin-top: 5px;
}
.btn-arrow-right,
.btn-arrow-left {
    position: relative;
    padding-left: 18px;
    padding-right: 18px;
}
.btn-arrow-right {
    padding-left: 36px;
}
.btn-arrow-left {
    padding-right: 36px;
}
.btn-arrow-right:before,
.btn-arrow-right:after,
.btn-arrow-left:before,
.btn-arrow-left:after { /* make two squares (before and after), looking similar to the button */
    content:"";
    position: absolute;
    top: 5px; /* move it down because of rounded corners */
    width: 22px; /* same as height */
    height: 22px; /* button_outer_height / sqrt(2) */
    background: inherit; /* use parent background */
    border: inherit; /* use parent border */
    border-left-color: transparent; /* hide left border */
    border-bottom-color: transparent; /* hide bottom border */
    border-radius: 0px 4px 0px 0px; /* round arrow corner, the shorthand property doesn't accept "inherit" so it is set to 4px */
    -webkit-border-radius: 0px 4px 0px 0px;
    -moz-border-radius: 0px 4px 0px 0px;
}
.btn-arrow-right:before,
.btn-arrow-right:after {
    transform: rotate(45deg); /* rotate right arrow squares 45 deg to point right */
    -webkit-transform: rotate(45deg);
    -moz-transform: rotate(45deg);
    -o-transform: rotate(45deg);
    -ms-transform: rotate(45deg);
}
.btn-arrow-left:before,
.btn-arrow-left:after {
    transform: rotate(225deg); /* rotate left arrow squares 225 deg to point left */
    -webkit-transform: rotate(225deg);
    -moz-transform: rotate(225deg);
    -o-transform: rotate(225deg);
    -ms-transform: rotate(225deg);
}
.btn-arrow-right:before,
.btn-arrow-left:before { /* align the "before" square to the left */
    left: -11px;
}
.btn-arrow-right:after,
.btn-arrow-left:after { /* align the "after" square to the right */
    right: -11px;
}
.btn-arrow-right:after,
.btn-arrow-left:before { /* bring arrow pointers to front */
    z-index: 1;
}
.btn-arrow-right:before,
.btn-arrow-left:after { /* hide arrow tails background */
    background-color: #ecf0f5;
}
</style>