
<div class="tabbable">
  <form id="edit_booking" method="post" action="" autocomplete="off">
    <div class="col-md-3 col-xs-6">
        <label for="booking_date">Ngày</label>
        <div class="input-group">
          <input class="form-control input-mask-date" type="text" id="booking_date" name="booking_date" tabindex="1" required="required" value="<?php echo $lib->hien_thi_ngay_thang($booking_data->booking_date) ?>">
        </div>
        <label for="booking_number">Số BK/BL</label>
        <div class="input-group">
          <input class="form-control" type="text" id="booking_number" name="booking_number" tabindex="5" value="<?php echo $booking_data->booking_number ?>">
        </div>
      </div>
      <div class="col-md-3 col-xs-6">
        <label for="booking_customer">Khách hàng <a title="Thêm khách hàng mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("customer/add") ?>','Thêm khách hàng mới','booking_customer','<?php echo $this->url("customer/getcustomer") ?>','add_customer')"></i></a></label>
        <div class="input-group">
          <select class="form-control select2" id="booking_customer" name="booking_customer" required="required" tabindex="2">
            <?php foreach ($customers as $customer) { ?>
              <option value="<?php echo $customer->customer_id ?>" <?php echo $booking_data->booking_customer==$customer->customer_id?'selected="selected"':null ?>><?php echo $customer->customer_name ?></option>
            <?php } ?>
          </select>
        </div>
        <label for="booking_shipping">Hãng tàu <a title="Thêm hãng tàu mới" ><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("shipping/add") ?>','Thêm hãng tàu mới','booking_shipping','<?php echo $this->url("shipping/getshipping") ?>','add_shipping')"></i> </a></label>
        <div class="input-group">
          <select class="form-control select2" id="booking_shipping" name="booking_shipping" tabindex="6">
            <option value="">Chọn</option>
            <?php foreach ($shippings as $shipping) { ?>
              <option value="<?php echo $shipping->shipping_id ?>" <?php echo $booking_data->booking_shipping==$shipping->shipping_id?'selected="selected"':null ?>><?php echo $shipping->shipping_name ?></option>
            <?php } ?>
          </select>
        </div>
      </div>
      <div class="col-md-3 col-xs-6">
        <label for="booking_type">Loại hàng</label>
        <div class="input-group">
          <select class="form-control" id="booking_type" name="booking_type" required="required" tabindex="3">
            <option value="1" <?php echo $booking_data->booking_type==1?'selected="selected"':null ?>>Hàng nhập</option>
            <option value="2" <?php echo $booking_data->booking_type==2?'selected="selected"':null ?>>Hàng xuất</option>
            <option value="3" <?php echo $booking_data->booking_type==3?'selected="selected"':null ?>>Khác</option>
          </select>
        </div>
        <label for="booking_shipping_name">Tên tàu</label>
        <div class="input-group">
          <input class="form-control" type="text" id="booking_shipping_name" name="booking_shipping_name" tabindex="7" value="<?php echo $booking_data->booking_shipping_name ?>">
        </div>
     </div>
     <div class="col-md-3 col-xs-6">
        
        <label for="booking_comment">Diễn giải</label>
        <div class="input-group">
          <input class="form-control" type="text" id="booking_comment" name="booking_comment" tabindex="4" value="<?php echo $booking_data->booking_comment ?>">
        </div>
        <label for="booking_shipping_number">Số hiệu</label>
        <div class="input-group">
          <input class="form-control" type="text" id="booking_shipping_number" name="booking_shipping_number" tabindex="8" value="<?php echo $booking_data->booking_shipping_number ?>">
        </div>
     </div>
     
  </form>
</div>

