<script type="text/javascript">
$(document).ready(function(){
	$( ".select2" ).select2({dropdownAutoWidth : true});
			// Validate form
			$("#add_toll").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
        ignore: "",
        rules: {
        },
        errorPlacement: function (error, element) {
          if(element.is('input[type=checkbox]') || element.is('input[type=radio]')) {
            var controls = element.closest('div[class*="col-"]');
            if(controls.find(':checkbox,:radio').length > 1) controls.append(error);
            else error.insertAfter(element.nextAll('.lbl:eq(0)').eq(0));
          }
          else if(element.is('.select2')) {
            error.insertAfter(element.siblings('[class*="select2-container"]:eq(0)'));
          }
          else if(element.is('.chosen-select')) {
            error.insertAfter(element.siblings('[class*="chosen-container"]:eq(0)'));
          }
          else error.insertAfter(element.parent());
        },
        submitHandler: function(form) {
                
          var formData = new FormData($("#add_toll")[0]);
          
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/toll/addtoll", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: formData, // giá trị post
              cache: false,
              contentType: false,
              processData: false,
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error_toll').hide();
                  $('#error_toll').slideToggle(100); // hiển thị thẻ div success
                  $('#error_toll').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error_toll').fadeOut(10000);

              }
          });
          return false;
           
       }
					 
				 
			});
	
});
</script>
<div id="error_toll" class="error"><?php echo isset($error) ? $error : null; ?></div>
<div class="login_body">
  
      <form id="add_toll" method="post" action="" autocomplete="off">
        <div class="col-xs-6">
          <table>
            <tr>
                <td>Tên trạm thu phí </td>
                <td><input type="text" id="toll_code" name="toll_code" tabindex="1" autofocus required="required"></td>
                
            </tr>
            <tr>
                <td>Tên đơn vị </td>
                <td><input type="text" id="toll_name" name="toll_name" tabindex="2" ></td>
                
            </tr>
            <tr>
                <td>Mã số thuế </td>
                <td><input type="text" id="toll_mst" name="toll_mst" tabindex="3"></td>
                
            </tr>
            
        </table> 
        </div>
        <div class="col-xs-6">
          <table>
            <tr>
                <td>Loại vé </td>
                <td>
                  <label>
                    <input class="form-control ace" type="radio" name="toll_type" checked="checked" tabindex="4" value="1"> <span class="lbl">Vé thu phí</span>
                  </label>
                  &nbsp;
                  <label>
                    <input class="form-control ace" type="radio" name="toll_type" tabindex="5" value="2"> <span class="lbl">Cước đường bộ</span>
                  </label>
                </td>
                
            </tr>
            <tr>
                <td>Mẫu số </td>
                <td><input type="text" id="toll_symbol" name="toll_symbol" tabindex="6" ></td>
                
            </tr>
            <tr>
                <td>Tỉnh/TP </td>
                <td>
                  <select class="form-control select2" id="toll_province" name="toll_province" required="required" tabindex="7">
                    <?php foreach ($provinces as $province) { ?>
                      <option value="<?php echo $province->province_id ?>"><?php echo $province->province_name ?></option>
                    <?php } ?>
                  </select>
                </td>
            </tr>
            
        </table> 
        </div>
        <div class="col-xs-12">
          <div id="map_canvas" style="width:100%;height:200px;"></div>
          <table>
            <tr>
              <td>Latitude</td>
              <td><input type="text" id="toll_lat" name="toll_lat" tabindex="8"></td>
            
              <td>Longitude</td>
              <td><input type="text" id="toll_long" name="toll_long" tabindex="9"></td>
            </tr>
          </table>
          
        </div>
          
    </form>
</div>


<script src="https://maps.googleapis.com/maps/api/js?v=3&key=<?php echo MAP_KEY ?>&callback=initialize"></script>
<script>
var styles = [
  {
    "featureType": "administrative.province",
    "elementType": "geometry.stroke",
    "stylers": [
      { "visibility": "on" },
      { "weight": 2.5 },
      { "color": "#24b0e2" }
    ]
  },{
    "featureType": "road",
    "elementType": "geometry",
    "stylers": [
      { "visibility": "on" }
    ]
  },{
    "featureType": "administrative.locality",
    "stylers": [
      { "visibility": "on" }
    ]
  },{
    "featureType": "road",
    "elementType": "labels",
    "stylers": [
      { "visibility": "on" }
    ]
  }
];
var lat = null;
var lng = null;
var map = null;
var geocoder = null;
var marker = null;
var myListener = null;

$(document).ready(function() {
  lat = $('#toll_lat').val();
  lng = $('#toll_long').val();
  $('#toll_province').on('select2:select', function (e) {
    var data = e.params.data;
    codeAddress($('#toll_name').val()+", "+data.text);
  });
  $('#toll_name').keyup(function(){
    codeAddress($(this).val()+", "+$('#toll_province option:selected').text());
  });
  $('#toll_long').keyup(function(){
    lat = $('#toll_lat').val();
    lng = $('#toll_long').val();
    var myLatlng = new google.maps.LatLng(lat, lng);
    map.setCenter(myLatlng);
    marker.setPosition(myLatlng);
    updatePosition(myLatlng);

    google.maps.event.addListener(marker, 'dragend', function() {
      updatePosition(marker.getPosition());
    });
  });
  $('#toll_lat').keyup(function(){
    lat = $('#toll_lat').val();
    lng = $('#toll_long').val();
    var myLatlng = new google.maps.LatLng(lat, lng);
    map.setCenter(myLatlng);
    marker.setPosition(myLatlng);
    updatePosition(myLatlng);

    google.maps.event.addListener(marker, 'dragend', function() {
      updatePosition(marker.getPosition());
    });
  });
});

function initialize() {

  geocoder = new google.maps.Geocoder();

  if (lat != '' && lng != '') {
    var latLng = new google.maps.LatLng(lat, lng);
  } else {
    var latLng = new google.maps.LatLng(10.5215836, 105.1258955);
  }
  var myOptions = {
    center: latLng,
    zoom: 9,
    gestureHandling: 'greedy',
    styles:styles,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };
  map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

  marker = new google.maps.Marker({
    map: map,
    position: latLng,
    draggable: true
  });
  google.maps.event.addListener(marker, 'dragend', function() {
    updatePosition(marker.getPosition());
  });
  updatePosition(latLng);
  google.maps.event.addListener(map, 'click', function(event) {
    if (marker) {
      marker.setPosition(event.latLng)
    } else {
      marker = new google.maps.Marker({
        map: map,
        position: event.latLng,
        draggable: true
      });
    }
    updatePosition(event.latLng);
  });

}

function codeAddress(value) {

  var address = value;
  geocoder.geocode({
    'address': address
  }, function(results, status) {

    if (status == google.maps.GeocoderStatus.OK) {
      map.setCenter(results[0].geometry.location);
      marker.setPosition(results[0].geometry.location);
      updatePosition(results[0].geometry.location);

      google.maps.event.addListener(marker, 'dragend', function() {
        updatePosition(marker.getPosition());
      });
    } 
  });
}

function updatePosition(latLng) {

  $('#toll_lat').val(latLng.lat());
  $('#toll_long').val(latLng.lng());

}
</script>