
<?php
$url_order = 'DESC';
if ($order_by == 'customer_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'customer_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'customer_code')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'customer_company')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'customer_type')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'customer_phone')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'customer_mst')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'customer_mobile')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'customer_email')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'province_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
$i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>
<div class="tools action-buttons pull-right">
    <?php
    if (isset($filter)) {
        echo '<a class="tooltip-warning" data-rel="tooltip" data-original-title="Dữ liệu đã được lọc bớt"><span class="green"><i class="ace-icon fa fa-filter bigger-150"></i></span></a>';
    }
    ?>
    <select name="m" id="chonloc" class="input-sm" onchange="limit_change($(this).val(),'<?php echo $order_by ?>','<?php echo $order ?>','<?php echo $keyword ?>')">
        <option value="18446744073709">All</option>
        <option value="10">10</option>
        <option value="20">20</option>
        <option value="50">50</option>
        <option value="100">100</option>
        <option value="500">500</option>
    </select>
    <a class="purpose" data-original-title="Thêm mới">
        <i class="ace-icon fa fa-plus-circle bigger-150" onclick="add_click('<?php echo $this->url("customer/add") ?>','Thêm khách hàng - đối tác mới')"></i>
    </a> 
    <div class="pull-right pos-rel dropdown-hover">
        <button class="btn btn-minier bigger" style="line-height: 26px">
            <i class="ace-icon fa fa-windows icon-only bigger-120"></i>
        </button>

        <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-caret dropdown-close dropdown-menu-right">
            <li>
                <a class="tooltip-warning" data-rel="tooltip" data-original-title="Tìm">
                    <span class="orange">
                        <i class="ace-icon fa fa-search bigger-150" onclick="search_click()"></i>
                    </span>
                </a>
            </li>
            <li>
                <a class="tooltip-success" data-rel="tooltip" data-original-title="Lọc">
                    <span class="green">
                        <i class="ace-icon fa fa-filter bigger-150" onclick="filter_click('<?php echo $this->url("customer/filter?page=".$page."&order_by=".$order_by."&order=".$order."&limit=".$limit."&keyword=".$keyword) ?>','Lọc dữ liệu')"></i>
                    </span>
                </a>
            </li>
            <li>
                <a class="tooltip-error" data-rel="tooltip" data-original-title="Xóa">
                    <span class="red">
                        <i class="ace-icon fa fa-trash-o bigger-150" onclick="del_click()"></i>
                    </span>
                </a>
            </li>
            <li>
                <a class="tooltip-info" data-rel="tooltip" data-original-title="Nhập">
                    <span class="purple">
                        <i class="ace-icon fa fa-cloud-upload bigger-150" onclick="import_click('<?php echo $this->url("customer/import") ?>','Nhập dữ liệu từ file Excel')"></i>
                    </span>
                </a>
            </li>
            <li>
                
                <div class="text-center pos-rel dropdown-hover">
                    <a class="tooltip-info" data-rel="tooltip" data-original-title="Xuất">
                        <span class="blue">
                            <i class="ace-icon fa fa-cloud-download bigger-150"></i>
                        </span>
                    </a>
                    <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-caret dropdown-close dropdown-menu-right">
                        <li>
                            <a class="tooltip-success" data-rel="tooltip" data-original-title="Excel">
                                <span class="green">
                                    <i class="ace-icon fa fa-file-excel-o bigger-130" onclick="export_click('excel','tblExport')"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a class="tooltip-error" data-rel="tooltip" data-original-title="PDF">
                                <span class="red">
                                    <i class="ace-icon fa fa-file-pdf-o bigger-130" onclick="export_click('pdf','tblExport')"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a class="tooltip-info" data-rel="tooltip" data-original-title="Word">
                                <span class="blue">
                                    <i class="ace-icon fa fa-file-word-o bigger-130" onclick="export_click('word','tblExport')"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            
        </ul>
    </div>                        
</div>
<div class="clearfix"></div>
<div id="content" style="padding:5px;">
   
<table class="table_data" id="tblExport" >
<thead>
    <tr>
    	<th><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall" class="ace ace-checkbox-2" /><span class="lbl"></span></th>
        <th><a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'customer_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a></th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer_code','<?php echo $url_order ?>')">Mã <?php if ($order_by == 'customer_code'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer_name','<?php echo $url_order ?>')">Tên <?php if ($order_by == 'customer_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer_company','<?php echo $url_order ?>')">Công ty <?php if ($order_by == 'customer_company'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer_mst','<?php echo $url_order ?>')">MST <?php if ($order_by == 'customer_mst'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','province_name','<?php echo $url_order ?>')">Địa chỉ <?php if ($order_by == 'province_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer_phone','<?php echo $url_order ?>')">Điện thoại <?php if ($order_by == 'customer_phone'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer_mobile','<?php echo $url_order ?>')">Di động <?php if ($order_by == 'customer_mobile'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer_email','<?php echo $url_order ?>')">Email <?php if ($order_by == 'customer_email'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer_type','<?php echo $url_order ?>')">Loại <?php if ($order_by == 'customer_type'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        
           
        <th>
            
        </th>
    </tr>
   </thead>
   <tbody>
    <?php foreach ($customers as $customer) : ?>
        <tr id="<?php echo $customer->customer_id ?>" class="edit_tr">
        	<td class="text-center"><input name="check[]" type="checkbox" class="checkbox ace" value="<?php echo $customer->customer_id ?>"><span class="lbl"></span></td>
            <td class="text-center"><?php echo $i++; ?></td>
            <td><?php echo $customer->customer_code; ?></td>
            <td><?php echo $customer->customer_name; ?></td>
            <td><?php echo $customer->customer_company; ?></td>
            <td><?php echo $customer->customer_mst; ?></td>
            <td><?php echo $customer->province_name; ?></td>
            <td><?php echo $customer->customer_phone; ?></td>
            <td><?php echo $customer->customer_mobile; ?></td>
            <td><?php echo $customer->customer_email; ?></td>
            <td><?php echo $customer->customer_type==1?'Khách hàng':($customer->customer_type==2?'Đối tác':'Cá nhân'); ?></td>
            
            
            
            
            
            <td class="text-right">
                <div class="tools action-buttons">
                    <a class="blue"  onclick="view_click('<?php echo $this->url("customer/view/") ?>','Thông tin khách hàng - đối tác',<?php echo $customer->customer_id ?>)">
                        <i class="ace-icon fa fa-info-circle bigger-130"></i>
                    </a>
                    <a class="green"  onclick="edit_click('<?php echo $this->url("customer/edit/") ?>','Cập nhật khách hàng - đối tác',<?php echo $customer->customer_id ?>)">
                        <i class="ace-icon fa fa-pencil bigger-130"></i>
                    </a>

                    <a class="red" >
                        <i class="ace-icon fa fa-trash-o bigger-130" onclick="del(<?php echo $customer->customer_id ?>)"></i>
                    </a>
                </div>
            </td>
        </tr>
    <?php endforeach; ?>
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>
</div>
<script type="text/javascript">
    var ch = "<?php echo $limit ?>";
$('#chonloc option[value='+ch+']').attr('selected','selected');
</script>