<script type="text/javascript">
$(document).ready(function(){

  $( ".select2" ).select2({dropdownAutoWidth : true});
      // Validate form
      

  $('input[name="customer_type"]').click(function(){
    var val = $(this).val();
    $.ajax({
        type: "GET",
        url: "<?php echo $this->url('customer/getlastcustomercode') ?>",
        data: {customer_type:val},
        success: function(answer){
          $('#customer_code').val(answer);
        }
    });
  });

  var tag_input = $('#customer_sub');
  try{
    tag_input.tag(
      {
      placeholder:tag_input.attr('placeholder'),
      //enable typeahead by specifying the source array
      //source: ace.vars['US_STATES'],//defined in ace.js >> ace.enable_search_ahead
      
      //or fetch data from database, fetch those that match "query"
      source: function(query, process) {
        $.ajax({url: '<?php echo $this->url("customer/getcustomersub") ?>?q='+encodeURIComponent(query)})
        .done(function(result_items){
        process($.parseJSON(result_items));
        });
      }
      
      }
    )

    //programmatically add/remove a tag
    //var $tag_obj = $('#customer_sub').data('tag');
    //$tag_obj.add('Programmatically Added');
    
    //var index = $tag_obj.inValues('some tag');
    //$tag_obj.remove(index);
  }
  catch(e) {
    //display a textarea for old IE, because it doesn't support this plugin or another one I tried!
    tag_input.after('<textarea id="'+tag_input.attr('id')+'" name="'+tag_input.attr('name')+'" rows="3">'+tag_input.val()+'</textarea>').remove();
    //autosize($('#form-field-tags'));
  }
  
});
</script>
     
<div id="error_customer" class="error"><?php echo isset($error) ? $error : null; ?></div>
<div class="tabbable">
    <ul class="nav nav-tabs padding-18">
      <li class="active">
        <a data-toggle="tab" href="#home">
          <i class="green ace-icon fa fa-home bigger-120"></i>
          Thông tin
        </a>
      </li>

      <li>
        <a data-toggle="tab" href="#contact">
          <i class="orange ace-icon fa fa-user bigger-120"></i>
          Liên hệ
        </a>
      </li>

    </ul>
    <div class="tab-content no-border ">
      <div id="home" class="tab-pane in active">
        <div class="col-md-3 col-xs-6">
          <label for="customer_code">Mã</label>
          <div class="input-group">
            <input class="form-control" type="text" id="customer_code" name="customer_code" required="required" tabindex="1" value="<?php echo $customer_data->customer_code ?>">
          </div>
          <label for="customer_name">Tên</label>
          <div class="input-group">
            <input class="form-control" type="text" id="customer_name" name="customer_name" required="required" tabindex="2" value="<?php echo $customer_data->customer_name ?>">
          </div>
          <label for="customer_company">Công ty</label>
          <div class="input-group">
            <input class="form-control" type="text" id="customer_company" name="customer_company" tabindex="3" value="<?php echo $customer_data->customer_company ?>">
          </div>
          <label for="customer_code">Loại</label>
          <div class="input-group">
            <label>
              <input class="form-control ace" type="radio" name="customer_type" tabindex="4" value="1" <?php echo $customer_data->customer_type==1?'checked="checked"':null ?> > <span class="lbl">Khách hàng</span>
            </label>
            &nbsp;
            <label>
              <input class="form-control ace" type="radio" name="customer_type" tabindex="5" value="2" <?php echo $customer_data->customer_type==2?'checked="checked"':null ?> > <span class="lbl">Đối tác</span>
            </label>
            &nbsp;
            <label>
              <input class="form-control ace" type="radio" name="customer_type" tabindex="6" value="3" <?php echo $customer_data->customer_type==3?'checked="checked"':null ?> > <span class="lbl">Cá nhân</span>
            </label>
          </div>
       </div>
       <div class="col-md-3 col-xs-6">
          <label for="customer_phone">Số điện thoại</label>
          <div class="input-group">
            <input class="form-control input-mask-phone" type="text" id="customer_phone" name="customer_phone" tabindex="10" value="<?php echo $customer_data->customer_phone ?>">
          </div>
          <label for="customer_mst">MST</label>
          <div class="input-group">
            <input class="form-control" type="text" id="customer_mst" name="customer_mst" tabindex="7" value="<?php echo $customer_data->customer_mst ?>">
          </div>
          <label for="customer_address">Địa chỉ</label>
          <div class="input-group">
            <input class="form-control" type="text" id="customer_address" name="customer_address" tabindex="8" value="<?php echo $customer_data->customer_address ?>">
          </div>
          <label for="customer_province">Tỉnh/TP</label>
          <div class="input-group">
            <select class="form-control select2" id="customer_province" name="customer_province" required="required" tabindex="9">
              <?php foreach ($provinces as $province) { ?>
                <option value="<?php echo $province->province_id ?>" <?php echo $customer_data->customer_province==$province->province_id?'selected="selected"':null ?>><?php echo $province->province_name ?></option>
              <?php } ?>
            </select>
          </div>
          
       </div>
       <div class="col-md-3 col-xs-6">
          <label for="customer_mobile">Di động</label>
          <div class="input-group">
            <input class="form-control input-mask-phone" type="text" id="customer_mobile" name="customer_mobile" tabindex="11" value="<?php echo $customer_data->customer_mobile ?>">
          </div>
          <label for="customer_email">Email</label>
          <div class="input-group">
            <input class="form-control" type="email" id="customer_email" name="customer_email" tabindex="12" value="<?php echo $customer_data->customer_email ?>">
          </div>
          <label for="customer_bank_account">Số tài khoản</label>
          <div class="input-group input-daterange">
            <input class="form-control input-sm" type="text" id="customer_bank_account" name="customer_bank_account" tabindex="13" value="<?php echo $customer_data->customer_bank_account ?>">
            <span class="input-group-addon">
              <i class="fa fa-bank"></i>
            </span>
            <input class="form-control input-sm" type="text" id="customer_bank_name" name="customer_bank_name" tabindex="14" placeholder="Tại Ngân hàng" value="<?php echo $customer_data->customer_bank_name ?>">
          </div>
          <label for="customer_bank_branch">Chi nhánh</label>
          <div class="input-group">
            <input class="form-control" type="text" id="customer_bank_branch" name="customer_bank_branch" tabindex="15" value="<?php echo $customer_data->customer_bank_branch ?>">
          </div>
       </div>
       <div class="col-md-3 col-xs-6">
          
          <label for="customer_sub">Mặt hàng</label>
          <div class="input-group">
            <input class="form-control" type="text" id="customer_sub" name="customer_sub" tabindex="16" value="<?php echo $customer_sub ?>">
          </div>
       </div>
      </div>
      <div id="contact" class="tab-pane">
        <div class="col-xs-12">
            <table id="dataTable_customer" style="width: 100%;">
                <tbody>
                  <?php if(count($contact_persons) > 0){ ?>
                  <?php foreach ($contact_persons as $contact) { ?>
                  <tr>
                    <td>
                        <table style="width:100%">
                            <tbody><tr>
                                <td>
                                  <label>Họ tên</label>
                                  <div class="input-group">
                                    <input type="text" class="contact_person_name" name="contact_person_name[]" tabindex="17" value="<?php echo $contact->contact_person_name ?>" data="<?php echo $contact->contact_person_id ?>">
                                  </div>
                                </td>
                                <td>
                                  <label>SĐT</label>
                                  <div class="input-group">
                                    <input type="text" class="contact_person_phone input-mask-phone" name="contact_person_phone[]" tabindex="20" value="<?php echo $contact->contact_person_phone ?>">
                                  </div>
                                </td>
                                <td>
                                  <label>Chức vụ</label>
                                  <div class="input-group">
                                    <input type="text" class="contact_person_position" name="contact_person_position[]" tabindex="23" value="<?php echo $contact->contact_person_position ?>">
                                  </div>
                                </td>
                              </tr>
                              <tr>
                                
                                <td>
                                  <label>Email</label>
                                  <div class="input-group">
                                    <input type="email" class="contact_person_email" name="contact_person_email[]" tabindex="18" value="<?php echo $contact->contact_person_email ?>">
                                  </div>
                                </td>
                                <td>
                                  <label>Ngày sinh</label>
                                  <div class="input-group">
                                    <input type="text" class="contact_person_birthday input-mask-date" name="contact_person_birthday[]" tabindex="21" value="<?php echo $lib->hien_thi_ngay_thang($contact->contact_person_birthday) ?>">
                                  </div>
                                </td>
                                <td>
                                  <label>Bộ phận</label>
                                  <div class="input-group">
                                    <input type="text" class="contact_person_department" name="contact_person_department[]" tabindex="24" value="<?php echo $contact->contact_person_department ?>">
                                  </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                  <label>Di động</label>
                                  <div class="input-group">
                                    <input type="text" class="contact_person_mobile input-mask-phone" name="contact_person_mobile[]" tabindex="19" value="<?php echo $contact->contact_person_mobile ?>">
                                  </div>
                                </td>
                                <td>
                                  <label>Địa chỉ</label>
                                  <div class="input-group">
                                    <input type="text" class="contact_person_address" name="contact_person_address[]" tabindex="22" value="<?php echo $contact->contact_person_address ?>">
                                  </div>
                                </td>
                              
                                
                            </tr>
                        </tbody></table>
                        <div class="hr hr-8 dotted hr-double"></div>
                    </td>
                  </tr>
                <?php }}else{ ?>
                  <tr>
                    <td>
                        <table style="width:100%">
                            <tbody><tr>
                                <td>
                                  <label>Họ tên</label>
                                  <div class="input-group">
                                    <input type="text" class="contact_person_name" name="contact_person_name[]" tabindex="17">
                                  </div>
                                </td>
                                <td>
                                  <label>SĐT</label>
                                  <div class="input-group">
                                    <input type="text" class="contact_person_phone input-mask-phone" name="contact_person_phone[]" tabindex="20">
                                  </div>
                                </td>
                                <td>
                                  <label>Chức vụ</label>
                                  <div class="input-group">
                                    <input type="text" class="contact_person_position" name="contact_person_position[]" tabindex="23">
                                  </div>
                                </td>
                              </tr>
                              <tr>
                                
                                <td>
                                  <label>Email</label>
                                  <div class="input-group">
                                    <input type="email" class="contact_person_email" name="contact_person_email[]" tabindex="18">
                                  </div>
                                </td>
                                <td>
                                  <label>Ngày sinh</label>
                                  <div class="input-group">
                                    <input type="text" class="contact_person_birthday input-mask-date" name="contact_person_birthday[]" tabindex="21">
                                  </div>
                                </td>
                                <td>
                                  <label>Bộ phận</label>
                                  <div class="input-group">
                                    <input type="text" class="contact_person_department" name="contact_person_department[]" tabindex="24">
                                  </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                  <label>Di động</label>
                                  <div class="input-group">
                                    <input type="text" class="contact_person_mobile input-mask-phone" name="contact_person_mobile[]" tabindex="19">
                                  </div>
                                </td>
                                <td>
                                  <label>Địa chỉ</label>
                                  <div class="input-group">
                                    <input type="text" class="contact_person_address" name="contact_person_address[]" tabindex="22">
                                  </div>
                                </td>
                              
                                
                            </tr>
                        </tbody></table>
                        <div class="hr hr-8 dotted hr-double"></div>
                    </td>
                  </tr>
                <?php } ?>
            </tbody>
            </table>
        
        </div>
      </div>
    </div>
 
</div>
