<script type="text/javascript">
$(document).ready(function(){
  $( ".select2" ).select2({dropdownAutoWidth : true});
      // Validate form
      $("#add_shipment").validate({
        errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
        rules: {
        },
        submitHandler: function(form) {
          var shipment_romooc = $('#shipment_romooc').attr('data');
          var shipment_staff = $('#shipment_staff').attr('data');
          var shipment_container = $('#shipment_booking_detail option:selected').text();
          var shipment_price = $('#shipment_ton').attr('data');

          var shipment_cost = [];  

          var shipment_cost_list = [];  
          var shipment_cost_comment = [];  
          var shipment_cost_money = [];  
          var shipment_cost_money_vat = [];  
          var shipment_cost_customer = [];  
          var shipment_cost_invoice = [];  
          var shipment_cost_invoice_date = [];  
          var id_shipment_cost = [];  

          $('.shipment_cost_money').each(function() { 
              shipment_cost_money.push($(this).val());
              id_shipment_cost.push($(this).attr('data') || "");
          });
          $('.shipment_cost_list').each(function() { 
              shipment_cost_list.push($(this).val());
          });
          $('.shipment_cost_comment').each(function() { 
              shipment_cost_comment.push($(this).val());
          });
          $('.shipment_cost_money_vat').each(function() { 
            if ($(this).is(':checked'))
              shipment_cost_money_vat.push(1);
            else
              shipment_cost_money_vat.push(0);
          });
          $('.shipment_cost_customer').each(function() { 
              shipment_cost_customer.push($(this).val());
          });
          $('.shipment_cost_invoice').each(function() { 
              shipment_cost_invoice.push($(this).val());
          });
          $('.shipment_cost_invoice_date').each(function() { 
              shipment_cost_invoice_date.push($(this).val());
          });

          for (var i = 0; i < shipment_cost_money.length; i++) {
              shipment_cost.push({'shipment_cost_money':shipment_cost_money[i], 'shipment_cost_list':shipment_cost_list[i], 'shipment_cost_comment':shipment_cost_comment[i], 'shipment_cost_money_vat':shipment_cost_money_vat[i], 'shipment_cost_customer':shipment_cost_customer[i], 'shipment_cost_invoice':shipment_cost_invoice[i], 'shipment_cost_invoice_date':shipment_cost_invoice_date[i], 'id_shipment_cost':id_shipment_cost[i]});
          };
          
          var formData = new FormData($("#add_shipment")[0]);
          formData.append('shipment_romooc', shipment_romooc);
          formData.append('shipment_staff', shipment_staff);
          formData.append('shipment_container', shipment_container);
          formData.append('shipment_price', shipment_price);
          formData.append('shipment_cost', JSON.stringify(shipment_cost));
          
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/shipment/addshipment", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: formData, // giá trị post
              cache: false,
              contentType: false,
              processData: false,
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error_shipment').hide();
                  $('#error_shipment').slideToggle(100); // hiển thị thẻ div success
                  $('#error_shipment').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error_shipment').fadeOut(10000);

              }
          });
          return false;
           
       }
           
         
      });

  
});

</script>

<div id="error_shipment" class="error"><?php echo isset($error) ? $error : null; ?></div>     
<div class="tabbable">
  <form id="add_shipment" method="post" action="" autocomplete="off">
    <ul class="nav nav-tabs padding-18">
      <li class="active">
        <a data-toggle="tab" href="#homeshipment">
          <i class="green ace-icon fa fa-file-text-o bigger-120"></i>
          Thông tin
        </a>
      </li>
      <li>
        <a data-toggle="tab" href="#roadshipment">
          <i class="blue ace-icon fa fa-road bigger-120"></i>
          Lộ trình
        </a>
      </li>
      <li>
        <a data-toggle="tab" href="#costshipment">
          <i class="orange ace-icon fa fa-money bigger-120"></i>
          Chi phí
        </a>
      </li>
    </ul>
    <div class="tab-content no-border ">
      <div id="homeshipment" class="tab-pane in active">
        <div>
          <label>
            <input name="shipment_sub" type="radio" class="ace" value="0" checked="">
            <span class="lbl blue"> Lô hàng chính</span>
          </label>
          <label>
            <input name="shipment_sub" type="radio" class="ace" value="1">
            <span class="lbl blue"> Lô hàng phụ</span>
          </label>
        </div>
        <div class="col-md-2 col-xs-6">
          <label for="dispatch_code">Lệnh điều xe</label>
          <div class="input-group">
            <select class="form-control select2" id="shipment_dispatch" name="shipment_dispatch" tabindex="1" required="required">
                <option value="">Chọn</option>
              <?php foreach ($dispatchs as $dispatch) { ?>
                <option value="<?php echo $dispatch->dispatch_id ?>"><?php echo $dispatch->dispatch_code ?></option>
              <?php } ?>
            </select>
          </div>
          <div class="hr hr-8 dotted hr-double"></div>
          <label for="shipment_do">Số DO</label>
          <div class="input-group">
            <input class="form-control" type="text" id="shipment_do" name="shipment_do" tabindex="7" >
          </div>
          <label for="shipment_customer">Khách hàng </label>
          <div class="input-group">
            <select class="form-control" id="shipment_customer" name="shipment_customer" tabindex="14" readonly="">
            </select>
          </div>  
          
            
        </div>
        <div class="col-md-2 col-xs-6">
          <label for="shipment_date">Ngày</label>
          <div class="input-group">
            <input class="form-control input-mask-date" type="text" id="shipment_date" name="shipment_date" tabindex="2" required="required" value="<?php echo date('d/m/Y') ?>">
          </div>
          <div class="hr hr-8 dotted hr-double"></div>
          <label for="shipment_booking_detail">Số container</label>
          <div class="input-group">
            <select class="form-control" id="shipment_booking_detail" name="shipment_booking_detail" tabindex="8" required="required">
            </select>
          </div>
          <label for="shipment_type">Loại hàng</label>
          <div class="input-group">
            <select class="form-control" id="shipment_type" name="shipment_type" tabindex="15" readonly="">
              <option value="">Chọn</option>
              <option value="1">Hàng nhập</option>
              <option value="2">Hàng xuất</option>
              <option value="3">Khác</option>
            </select>
          </div>
          
           
        </div>
        <div class="col-md-2 col-xs-6">
          <label for="shipment_vehicle">Xe <a title="Thêm xe mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("vehicle/add") ?>','Thêm xe mới','shipment_vehicle','<?php echo $this->url("vehicle/getvehicle") ?>','add_vehicle')"></i></a></label>
          <div class="input-group">
            <select class="form-control select2" id="shipment_vehicle" name="shipment_vehicle" required="required" tabindex="3">
              <option value="">Chọn</option>
              <?php foreach ($vehicles as $vehicle) { ?>
                <option value="<?php echo $vehicle->vehicle_id ?>"><?php echo $vehicle->vehicle_number ?></option>
              <?php } ?>
            </select>
          </div>  
          <div class="hr hr-8 dotted hr-double"></div>
          <label for="shipment_ton_receive">Sản lượng nhận</label>
          <div class="input-group">
            <input class="form-control numbers" type="text" id="shipment_ton_receive" name="shipment_ton_receive" tabindex="9" >
          </div>
          <label for="shipment_booking">Số BK/BL </label>
          <div class="input-group">
            <select class="form-control" id="shipment_booking" name="shipment_booking" tabindex="16" readonly="">
            </select>
          </div> 
          
          
       </div>
       <div class="col-md-2 col-xs-6">
          <label for="shipment_romooc">Mooc <a title="Thay lắp mooc" id="vehicle_romooc"><i class="ace-icon fa fa-exchange blue"></i></a></label>
          <div class="input-group">
            <input class="form-control" type="text" id="shipment_romooc" name="shipment_romooc" tabindex="4" readonly="" >
          </div>
          <div class="hr hr-8 dotted hr-double"></div>
          <label for="shipment_ton">Sản lượng giao</label>
          <div class="input-group">
            <input class="form-control numbers" type="text" id="shipment_ton" name="shipment_ton" tabindex="10" required="required" >
          </div>
          <label for="shipment_place_from">Nơi lấy <a title="Thêm kho hàng mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("place/add") ?>','Thêm kho hàng mới','shipment_place_from','<?php echo $this->url("place/getplace") ?>','add_place')"></i></a></label>
          <div class="input-group">
            <select class="form-control select2" id="shipment_place_from" name="shipment_place_from" required="required" tabindex="17">
              <option value="">Chọn</option>
              <?php foreach ($places as $place) { ?>
                <option value="<?php echo $place->place_id ?>"><?php echo $place->place_name ?></option>
              <?php } ?>
            </select>
          </div>
          <label for="shipment_port_from">Lấy rỗng <a title="Thêm cảng mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("port/add") ?>','Thêm cảng mới','shipment_port_from','<?php echo $this->url("port/getport") ?>','add_port')"></i></a></label>
          <div class="input-group">
            <select class="form-control select2" id="shipment_port_from" name="shipment_port_from" tabindex="19">
              <option value="">Chọn</option>
              <?php foreach ($ports as $port) { ?>
                <option value="<?php echo $port->place_id ?>"><?php echo $port->place_name ?></option>
              <?php } ?>
            </select>
          </div> 
          
          
        </div>
        <div class="col-md-2 col-xs-6">
          <label for="shipment_staff">Tài xế <a title="Tài xế" id="vehicle_driver"><i class="ace-icon fa fa-user blue"></i></a></label>
          <div class="input-group">
            <input class="form-control" type="text" id="shipment_staff" name="shipment_staff" tabindex="5" readonly="" >
          </div>
          <div class="hr hr-8 dotted hr-double"></div>
          <label for="shipment_unit">ĐVT</label>
          <div class="input-group">
            <select class="form-control" id="shipment_unit" name="shipment_unit" tabindex="11" required="required">
              <?php foreach ($units as $unit) { ?>
                <option value="<?php echo $unit->unit_id ?>"><?php echo $unit->unit_name ?></option>
              <?php } ?>
            </select>
          </div>
          <label for="shipment_place_to">Nơi hạ <a title="Thêm kho hàng mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("place/add") ?>','Thêm kho hàng mới','shipment_place_to','<?php echo $this->url("place/getplace") ?>','add_place')"></i></a></label>
          <div class="input-group">
            <select class="form-control select2" id="shipment_place_to" name="shipment_place_to" required="required" tabindex="18">
              <option value="">Chọn</option>
              <?php foreach ($places as $place) { ?>
                <option value="<?php echo $place->place_id ?>"><?php echo $place->place_name ?></option>
              <?php } ?>
            </select>
          </div> 
          <label for="shipment_port_to">Trả rỗng <a title="Thêm cảng mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("port/add") ?>','Thêm cảng mới','shipment_port_to','<?php echo $this->url("port/getport") ?>','add_port')"></i></a></label>
          <div class="input-group">
            <select class="form-control select2" id="shipment_port_to" name="shipment_port_to" tabindex="20">
              <option value="">Chọn</option>
              <?php foreach ($ports as $port) { ?>
                <option value="<?php echo $port->place_id ?>"><?php echo $port->place_name ?></option>
              <?php } ?>
            </select>
          </div> 
          
        </div>
        <div class="col-md-2 col-xs-6">
          <label for="shipment_comment">Ghi chú</label>
          <div class="input-group">
            <input class="form-control" type="text" id="shipment_comment" name="shipment_comment" tabindex="6" >
          </div>
          <div class="hr hr-8 dotted hr-double"></div>
          <label for="shipment_start_date">Ngày lấy</label>
          <div class="input-group">
            <input class="form-control input-mask-datetime" type="text" id="shipment_start_date" name="shipment_start_date" tabindex="12" >
          </div>
          <label for="shipment_end_date">Ngày hạ</label>
          <div class="input-group">
            <input class="form-control input-mask-datetime" type="text" id="shipment_end_date" name="shipment_end_date" tabindex="13" >
          </div>
        </div>
      </div>
      <div id="roadshipment" class="tab-pane">
        
      </div>
      <div id="costshipment" class="tab-pane">
        <div class="col-xs-12">
            <table id="dataTable_shipment" style="width: 100%;">
                <tbody>
                <tr>
                    <td style="padding-right: 10px;"><input type="checkbox" name="chk"></td>
                    <td>
                        <table style="width:100%;">
                            <tbody>
                              <tr>
                                <td>
                                  <label>Chi phí <a title="Thêm chi phí mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("costlist/add") ?>','Thêm chi phí mới','.shipment_cost_list','<?php echo $this->url("costlist/getcostlist") ?>','add_costlist')"></i></a></label>
                                  <div class="input-group">
                                    <select class="form-control shipment_cost_list" name="shipment_cost_list[]" tabindex="14">
                                      <?php foreach ($cost_lists as $cost_list) { ?>
                                        <option value="<?php echo $cost_list->cost_list_id ?>" ><?php echo $cost_list->cost_list_name ?></option>
                                      <?php } ?>
                                    </select>
                                  </div>
                                </td>
                                <td>
                                  <label>Nội dung</label>
                                  <div class="input-group">
                                    <input type="text" class="shipment_cost_comment" name="shipment_cost_comment[]" tabindex="15">
                                  </div>
                                </td>
                                
                                <td>
                                  <label>Số tiền <input name="shipment_cost_money_vat[]" type="checkbox" class="shipment_cost_money_vat ace" value="1" checked><span class="lbl"></span> VAT</label>
                                  <div class="input-group">
                                    <input type="text" class="shipment_cost_money numbers" name="shipment_cost_money[]" tabindex="16">
                                  </div>
                                  
                                </td>
                              </tr>
                              <tr>
                                <td>
                                  <label>Người nhận <a title="Thêm người nhận mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("customer/add") ?>','Thêm người nhận mới','.shipment_cost_customer','<?php echo $this->url("customer/getcustomer") ?>','add_customer')"></i></a></label>
                                  <div class="input-group">
                                    <select class="form-control shipment_cost_customer select2" name="shipment_cost_customer[]" tabindex="17">
                                      <?php foreach ($customer_lists as $customer_list) { ?>
                                        <option value="<?php echo $customer_list->customer_id ?>" ><?php echo $customer_list->customer_code.'-'.$customer_list->customer_name ?></option>
                                      <?php } ?>
                                    </select>
                                  </div>
                                </td>
                                <td>
                                  <label>Số hóa đơn chứng từ</label>
                                  <div class="input-group">
                                    <input type="text" class="shipment_cost_invoice" name="shipment_cost_invoice[]" tabindex="18">
                                  </div>
                                </td>
                                <td>
                                  <label>Ngày</label>
                                  <div class="input-group">
                                    <input type="text" class="shipment_cost_invoice_date input-mask-date" name="shipment_cost_invoice_date[]" tabindex="19">
                                  </div>
                                </td>
                              </tr>
                              
                        </tbody></table>
                        <div class="hr hr-8 dotted hr-double"></div>
                    </td>
                    
                </tr>
            </tbody>
            </table>
        
            <input type="button" value="Thêm" onclick="addRow_shipment('dataTable_shipment')">

            <input type="button" value="Xóa" onclick="deleteRow_shipment('dataTable_shipment')">
        </div>
      </div>
    </div>
      
  </form>
</div>

<script type="text/javascript">
  $('#shipment_dispatch').change(function(){
    var type = $('input[name=shipment_sub]:checked').val();
    var dispatch = $('#shipment_dispatch').val();
    if (dispatch>0) {
      $.ajax({
        type: "GET",
        url: "<?php echo BASE_URL ?>/shipment/getdispatch",
        data: {dispatch:dispatch,type:type}, 
        success: function(answer){
           var data = $.parseJSON(answer);
           $("#shipment_vehicle").val(data.vehicle).change();

           $("#shipment_type").val(data.booking_type).change();
           $("#shipment_place_from").val(data.place_from).change();
           $("#shipment_place_to").val(data.place_to).change();
           $("#shipment_port_from").val(data.port_from).change();
           $("#shipment_port_to").val(data.port_to).change();

           $('#shipment_customer').html(data.customer);
           $('#shipment_booking').html(data.booking);
           $('#shipment_start_date').val(data.start_date);
           $('#shipment_end_date').val(data.end_date);
           $('#shipment_comment').val(data.comment);
           $('#shipment_booking_detail').html(data.container);
        }
      });
    }
    else{
     $('#shipment_customer').html("");
     $('#shipment_booking').html("");
     $('#shipment_start_date').val("");
     $('#shipment_end_date').val("");
     $('#shipment_comment').val("");
     $('#shipment_booking_detail').html("");
    }
     
  });

  $('input[name=shipment_sub]').change(function(){
    var type = $(this).val();
    var data = $('#shipment_dispatch').val();
    $.ajax({
        type: "GET",
        url: "<?php echo BASE_URL ?>/dispatch/getdispatch",
        data: {data:data, type:type}, 
        success: function(answer){
           var data = $.parseJSON(answer);

           $("#shipment_type").val(data.booking_type).change();
           $("#shipment_place_from").val(data.place_from).change();
           $("#shipment_place_to").val(data.place_to).change();
           $("#shipment_port_from").val(data.port_from).change();
           $("#shipment_port_to").val(data.port_to).change();

           $('#shipment_customer').html(data.customer);
           $('#shipment_booking').html(data.booking);
           $('#shipment_start_date').val(data.start_date);
           $('#shipment_end_date').val(data.end_date);
           $('#shipment_comment').val(data.comment);
           $('#shipment_booking_detail').html(data.container);
        }
    });
  });

  $('#shipment_booking_detail').change(function(){
    var detail = $('#shipment_booking_detail').val();
     $.ajax({
        type: "GET",
        url: "<?php echo BASE_URL ?>/booking/getbookingcont",
        data: {detail:detail}, 
        success: function(answer){
           var data = $.parseJSON(answer);
           $('#shipment_ton_receive').val(data.number);
           $('#shipment_ton').val(data.number);
           $('#shipment_ton').attr('data',data.price);
           $('#shipment_unit option[value='+data.unit+']').attr('selected','selected');
        }
    });
  });

  $('#shipment_vehicle').change(function(){
    var vehicle = $('#shipment_vehicle').val();
    var date = $('#shipment_date').val();
    if (vehicle>0) {
      $.ajax({
          type: "GET",
          url: "<?php echo BASE_URL ?>/vehicleromooc/getromooc",
          data: {vehicle:vehicle,date:date}, 
          success: function(answer){
             var data = $.parseJSON(answer);
             $('#shipment_romooc').val(data.romooc_number);
             $('#shipment_romooc').attr('data',data.romooc_id);
          }
      });
      $.ajax({
          type: "GET",
          url: "<?php echo BASE_URL ?>/driver/getdriver",
          data: {vehicle:vehicle,date:date}, 
          success: function(answer){
             var data = $.parseJSON(answer);
             $('#shipment_staff').val(data.staff_name);
             $('#shipment_staff').attr('data',data.staff_id);
          }
      });
    }
  });

  $('#vehicle_romooc').click(function(){
    var vehicle = $('#shipment_vehicle').val();
    var date = $('#shipment_date').val();
    if (vehicle>0) {
      view_click_other('<?php echo $this->url("vehicleromooc/viewromooc/?id=") ?>','Thông tin mooc',vehicle+'~'+date,'none');
    }
    
  });
  $('#vehicle_driver').click(function(){
    var vehicle = $('#shipment_vehicle').val();
    var date = $('#shipment_date').val();
    if (vehicle>0) {
      view_click_other('<?php echo $this->url("driver/viewdriver/?id=") ?>','Thông tin tài xế',vehicle+'~'+date,'none');
    }
  });
</script>


<script type="text/javascript">
$(document).ready( function() {
  $('#shipment_place_from').change(function(e) { 
    var from = $('#shipment_place_from').val();
    var to = $('#shipment_place_to').val();
    var date = $('#shipment_date').val();

    $("#roadshipment").load("<?php echo $this->url('dispatch') ?>/getroad?from="+from+"&to="+to+"&date="+date);
  });
  $('#shipment_place_to').change(function(e) { 
    var from = $('#shipment_place_from').val();
    var to = $('#shipment_place_to').val();
    var date = $('#shipment_date').val();

    $("#roadshipment").load("<?php echo $this->url('dispatch') ?>/getroad?from="+from+"&to="+to+"&date="+date);
  });
});

function addRow_shipment(tableID){
    var table=document.getElementById(tableID);
    var rowCount=table.rows.length;
    var row=table.insertRow(rowCount);
    var colCount=table.rows[0].cells.length;
    for(var i=0;i<colCount;i++){
        var newcell=row.insertCell(i);
        newcell.innerHTML=table.rows[0].cells[i].innerHTML;
        switch(newcell.childNodes[0].type){
            case"text":newcell.childNodes[0].value="";
            break;
            case"checkbox":newcell.childNodes[0].checked=false;
            break;
            case"select-one":newcell.childNodes[0].selectedIndex=0;
            break;
        }
    }

    $('.shipment_cost_money:last').val("");
    $('.shipment_cost_comment:last').val("");
    $('.shipment_cost_invoice:last').val("");
    $('.shipment_cost_invoice_date:last').val("");

    $('input[name="chk"]:last').attr('data',"");
    $('input[name="chk"]:last').attr('title',"");

    $('.select2-container:last').remove();
    $('.shipment_cost_customer:last').removeClass('select2-hidden-accessible');
    $('.shipment_cost_customer:last').select2();

}
function deleteRow_shipment(tableID){
    try{
        var table=document.getElementById(tableID);
        var rowCount=table.rows.length;

        bootbox.confirm("Bạn có chắc chắn muốn xóa không?", function(result) {
          if(result) {
            for(var i=0;i<rowCount;i++){
                var row=table.rows[i];
                var chkbox=row.cells[0].childNodes[0];
                if(null!=chkbox&&true==chkbox.checked){
                  if(rowCount<=1){
                        alert_form("Không thể xóa hết.");
                        break;
                    }
                    else if(chkbox.getAttribute("title") > 0){
                        
                            var data = chkbox.getAttribute("data");
                            var shipment = chkbox.getAttribute("title");

                            $.post("<?php echo BASE_URL ?>/shipment/deleteshipmentcost", {data: data, shipment: shipment},
                               function(data){
                                
                               }); 
                        
                    }
                    
                    table.deleteRow(i);
                    rowCount--;
                    i--;

                }
            }
          }
        });
    }
    catch(e){
        alert(e);
    }
}
</script>