<div class="tabbable tabs-below">
  <div class="tab-content">
    <div id="costloan" class="tab-pane active">
      <div class="col-md-6">
        <label for="shipment_cost_lift_on">Nâng cont</label>
        <div class="input-group">
          <input class="form-control numbers" type="text" id="shipment_cost_lift_on" name="shipment_cost_lift_on" tabindex="15" value="<?php echo $lib->formatMoney($lift_on) ?>">
        </div>
        <label for="shipment_cost_lift_off">Hạ cont</label>
        <div class="input-group">
          <input class="form-control numbers" type="text" id="shipment_cost_lift_off" name="shipment_cost_lift_off" tabindex="15" value="<?php echo $lib->formatMoney($lift_off) ?>">
        </div>
        <label for="shipment_cost_lift_on_null">Nâng cont rỗng</label>
        <div class="input-group">
          <input class="form-control numbers" type="text" id="shipment_cost_lift_on_null" name="shipment_cost_lift_on_null" tabindex="15" value="<?php echo $lib->formatMoney($lift_on_null) ?>">
        </div>
        <label for="shipment_cost_lift_off_null">Hạ cont rỗng</label>
        <div class="input-group">
          <input class="form-control numbers" type="text" id="shipment_cost_lift_off_null" name="shipment_cost_lift_off_null" tabindex="15" value="<?php echo $lib->formatMoney($lift_off_null) ?>">
        </div>
      </div>
      <div class="col-md-6">
        <label for="shipment_cost_deposit">Cược cont</label>
        <div class="input-group">
          <input class="form-control numbers" type="text" id="shipment_cost_deposit" name="shipment_cost_deposit" tabindex="15" value="<?php echo $lib->formatMoney($deposit) ?>">
        </div>
        <label for="shipment_cost_clean">Rửa cont</label>
        <div class="input-group">
          <input class="form-control numbers" type="text" id="shipment_cost_clean" name="shipment_cost_clean" tabindex="15" value="<?php echo $lib->formatMoney($clean) ?>">
        </div>
        <label for="shipment_cost_trans">Chuyển cont</label>
        <div class="input-group">
          <input class="form-control numbers" type="text" id="shipment_cost_trans" name="shipment_cost_trans" tabindex="15" value="<?php echo $lib->formatMoney($trans) ?>">
        </div>
        <label for="shipment_cost_weight">Cân xe</label>
        <div class="input-group">
          <input class="form-control numbers" type="text" id="shipment_cost_weight" name="shipment_cost_weight" tabindex="15" value="<?php echo $lib->formatMoney($weight) ?>">
        </div>
        <label for="shipment_cost_document">Lấy hồ sơ</label>
        <div class="input-group">
          <input class="form-control numbers" type="text" id="shipment_cost_document" name="shipment_cost_document" tabindex="15" value="<?php echo $lib->formatMoney($document) ?>">
        </div>
      </div>
      <div class="clearfix"></div>
      
      
    </div>

    <div id="costtoll" class="tab-pane">
      <label for="shipment_cost_toll">Số tiền</label>
      <div class="input-group">
        <input class="form-control numbers" type="text" id="shipment_cost_toll" name="shipment_cost_toll" tabindex="15" value="<?php echo $lib->formatMoney($roadtoll) ?>">
      </div>
    </div>
    <div id="costwarehouse" class="tab-pane">
      
      <label for="shipment_cost_cont">Bồi dưỡng cont</label>
      <div class="input-group">
        <input class="form-control numbers" type="text" id="shipment_cost_cont" name="shipment_cost_cont" tabindex="15" value="<?php echo $lib->formatMoney($warehouse_cont) ?>">
      </div>
    
      <label for="shipment_cost_ton">Bồi dưỡng tấn</label>
      <div class="input-group">
        <input class="form-control numbers" type="text" id="shipment_cost_ton" name="shipment_cost_ton" tabindex="15" value="<?php echo $lib->formatMoney($warehouse_ton) ?>">
      </div>
    </div>
    <div id="costpolice" class="tab-pane">
      <label for="shipment_cost_police">Số tiền</label>
      <div class="input-group">
        <input class="form-control numbers" type="text" id="shipment_cost_police" name="shipment_cost_police" tabindex="15" value="<?php echo $lib->formatMoney($police) ?>">
      </div>
    </div>
    <div id="costtire" class="tab-pane">
      <label for="shipment_cost_tire">Số tiền</label>
      <div class="input-group">
        <input class="form-control numbers" type="text" id="shipment_cost_tire" name="shipment_cost_tire" tabindex="15" value="<?php echo $lib->formatMoney($tire) ?>">
      </div>
    </div>

    <div id="othercost" class="tab-pane">
      <table id="dataTable_shipment" style="width: 100%;">
        <tbody>
          <tr>
              <td style="padding-right: 10px;"><input type="checkbox" name="chk"></td>
              <td>
                  <table style="width:100%;">
                      <tbody>
                        <tr>
                          <td>
                            <label>Chi phí <a title="Thêm chi phí mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("costlist/add") ?>','Thêm chi phí mới','.shipment_cost_list','<?php echo $this->url("costlist/getcostlist") ?>','add_costlist')"></i></a></label>
                            <div class="input-group">
                              <select class="form-control shipment_cost_list" name="shipment_cost_list[]" tabindex="14">
                                <?php foreach ($cost_lists as $cost_list) { ?>
                                  <option value="<?php echo $cost_list->cost_list_id ?>" ><?php echo $cost_list->cost_list_name ?></option>
                                <?php } ?>
                              </select>
                            </div>
                          </td>
                          <td>
                            <label>Nội dung</label>
                            <div class="input-group">
                              <input type="text" class="shipment_cost_comment" name="shipment_cost_comment[]" tabindex="15">
                            </div>
                          </td>
                          
                          <td>
                            <label>Số tiền <input name="shipment_cost_money_vat[]" type="checkbox" class="shipment_cost_money_vat ace" value="1" checked><span class="lbl"></span> VAT</label>
                            <div class="input-group">
                              <input type="text" class="shipment_cost_money numbers" name="shipment_cost_money[]" tabindex="16">
                            </div>
                            
                          </td>
                        </tr>
                        <tr>
                          <td>
                            <label>Người nhận <a title="Thêm người nhận mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("customer/add") ?>','Thêm người nhận mới','.shipment_cost_customer','<?php echo $this->url("customer/getcustomer") ?>','add_customer')"></i></a></label>
                            <div class="input-group">
                              <select class="form-control shipment_cost_customer select2" name="shipment_cost_customer[]" tabindex="17">
                                <?php foreach ($customer_lists as $customer_list) { ?>
                                  <option value="<?php echo $customer_list->customer_id ?>" ><?php echo $customer_list->customer_code.'-'.$customer_list->customer_name ?></option>
                                <?php } ?>
                              </select>
                            </div>
                          </td>
                          <td>
                            <label>Số hóa đơn chứng từ</label>
                            <div class="input-group">
                              <input type="text" class="shipment_cost_invoice" name="shipment_cost_invoice[]" tabindex="18">
                            </div>
                          </td>
                          <td>
                            <label>Ngày</label>
                            <div class="input-group">
                              <input type="text" class="shipment_cost_invoice_date input-mask-date" name="shipment_cost_invoice_date[]" tabindex="19">
                            </div>
                          </td>
                        </tr>
                        
                  </tbody></table>
                  <div class="hr hr-8 dotted hr-double"></div>
              </td>
              
          </tr>
      </tbody>
      </table>
  
      <input type="button" value="Thêm" onclick="addRow_shipment('dataTable_shipment')">

      <input type="button" value="Xóa" onclick="deleteRow_shipment('dataTable_shipment')">
    </div>
  </div>
  <ul class="nav nav-tabs" id="myTab3">
    <li class="active">
      <a data-toggle="tab" href="#costloan" aria-expanded="false">
        <i class="red ace-icon fa fa-exchange bigger-110"></i>
        Chi hộ
      </a>
    </li>
    <li class="">
      <a data-toggle="tab" href="#costtoll" aria-expanded="false">
        <i class="pink ace-icon fa fa-car bigger-110"></i>
        Cầu đường
      </a>
    </li>

    <li class="">
      <a data-toggle="tab" href="#costwarehouse" aria-expanded="false">
        <i class="blue ace-icon fa fa-home bigger-110"></i>
        Bồi dưỡng
      </a>
    </li>
    <li class="">
      <a data-toggle="tab" href="#costpolice" aria-expanded="false">
        <i class="orange ace-icon fa fa-user-secret bigger-110"></i>
       Công an
      </a>
    </li>
    <li class="">
      <a data-toggle="tab" href="#costtire" aria-expanded="false">
        <i class="green ace-icon fa fa-support bigger-110"></i>
       Vá vỏ - Rửa xe
      </a>
    </li>
    <li class="">
      <a data-toggle="tab" href="#othercost" aria-expanded="true">
        <i class="ace-icon fa fa-rocket"></i>
        Khác
      </a>
    </li>
  </ul>

  
</div>
<div class="text-right"><b>Tổng chi phí: <span id="sumcost"><?php echo $lib->formatMoney($sumcost) ?></span></b></div>
<script type="text/javascript">
$(document).ready(function(){
  $( ".select2" ).select2({dropdownAutoWidth : true});
});

  $('#costshipment .numbers').keyup(function(){
    var total = 0;
    $('#costshipment .numbers').each(function(){
      total += parseFloat($(this).val().replace(/\,/g,'')) || 0;
    });
    $('#sumcost').text(total);
    $('#sumcost').text(function(index, value) {
      return value
        .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
      ;
    });
  });

  function addRow_shipment(tableID){
      var table=document.getElementById(tableID);
      var rowCount=table.rows.length;
      var row=table.insertRow(rowCount);
      var colCount=table.rows[0].cells.length;
      for(var i=0;i<colCount;i++){
          var newcell=row.insertCell(i);
          newcell.innerHTML=table.rows[0].cells[i].innerHTML;
          switch(newcell.childNodes[0].type){
              case"text":newcell.childNodes[0].value="";
              break;
              case"checkbox":newcell.childNodes[0].checked=false;
              break;
              case"select-one":newcell.childNodes[0].selectedIndex=0;
              break;
          }
      }

      $('.shipment_cost_money:last').val("");
      $('.shipment_cost_comment:last').val("");
      $('.shipment_cost_invoice:last').val("");
      $('.shipment_cost_invoice_date:last').val("");

      $('input[name="chk"]:last').attr('data',"");
      $('input[name="chk"]:last').attr('title',"");

      $('.select2-container:last').remove();
      $('.shipment_cost_customer:last').removeClass('select2-hidden-accessible');
      $('.shipment_cost_customer:last').select2();

      $('#costshipment .numbers').keyup(function(){
        var total = 0;
        $('#costshipment .numbers').each(function(){
          total += parseFloat($(this).val().replace(/\,/g,'')) || 0;
        });
        $('#sumcost').text(total);
        $('#sumcost').text(function(index, value) {
          return value
            .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
          ;
        });
      });

  }
  function deleteRow_shipment(tableID){
      try{
          var table=document.getElementById(tableID);
          var rowCount=table.rows.length;

          bootbox.confirm("Bạn có chắc chắn muốn xóa không?", function(result) {
            if(result) {
              for(var i=0;i<rowCount;i++){
                  var row=table.rows[i];
                  var chkbox=row.cells[0].childNodes[0];
                  if(null!=chkbox&&true==chkbox.checked){
                    if(rowCount<=1){
                          alert_form("Không thể xóa hết.");
                          break;
                      }
                      else if(chkbox.getAttribute("title") > 0){
                          
                              var data = chkbox.getAttribute("data");
                              var shipment = chkbox.getAttribute("title");

                              $.post("<?php echo BASE_URL ?>/shipment/deleteshipmentcost", {data: data, shipment: shipment},
                                 function(data){
                                  
                                 }); 

                      }
                      
                      table.deleteRow(i);
                      rowCount--;
                      i--;

                      var total = 0;
                      $('#costshipment .numbers').each(function(){
                        total += parseFloat($(this).val().replace(/\,/g,'')) || 0;
                      });
                      $('#sumcost').text(total);
                      $('#sumcost').text(function(index, value) {
                        return value
                          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
                        ;
                      });
                  }
              }
            }
          });
      }
      catch(e){
          alert(e);
      }
  }
  </script>