<?php $j=1; ?>
<style type="text/css">
    .approve{
        color: green;
    }
</style>
<table class="table_data" id="tblExport3" style="font-size: 12px;">
<thead>
    <tr>
        
        <th rowspan="2"  class="fix">
            STT
        </th>
        <th rowspan="2"  class="fix">
            Số DO 
        </th>
        <th rowspan="2"  class="fix">
            Ngày nhận 
        </th>
        <th rowspan="2"  class="fix">
            Ngày giao 
        </th>
        <th rowspan="2"  class="fix">
            Xe 
        </th>
        <th rowspan="2"  class="fix">
            Mooc 
        </th>
        <th rowspan="2"  class="fix">
            Tài xế 
        </th>
        
        <th rowspan="2"  class="fix">
            Nơi nhận 
        </th>
        <th rowspan="2"  class="fix">
            Nơi giao 
        </th>
        <th rowspan="2"  class="fix">
            Khách hàng 
        </th>
        <th rowspan="2"  class="fix">
            Chiều dài (km)
        </th>
        <th rowspan="2"  class="fix">
            Dầu thực lãnh
        </th>
        <th rowspan="2"  class="fix">
            Dầu định mức 
        </th>
        <th rowspan="2"  class="fix">
            Chi phí đi đường 
        </th>
        <th colspan="<?php echo count($loan_units) ?>"  class="fix">
            Chi hộ 
        </th>
        <th rowspan="2"  class="fix">
            Cầu đường 
        </th>
        
        <th rowspan="2"  class="fix">
            Công an 
        </th>
        
        <th rowspan="2"  class="fix">
            Bồi dưỡng 
        </th>
        
        <th rowspan="2"  class="fix">
            Mặt hàng 
        </th>
        <th colspan="<?php echo count($cont_units) ?>" class="fix">
            Số lượng nhận 
        </th>
        <th colspan="<?php echo count($cont_units) ?>" class="fix">
            Số lượng giao 
        </th>
        <th rowspan="2"  class="fix">
            Giờ vào 
        </th>
        <th rowspan="2"  class="fix">
            Giờ ra 
        </th>
       
    </tr>
    <tr>
        <?php foreach ($loan_units as $loan) { ?>
        <th class="fix">
            <?php echo $loan->cost_list_name ?> 
        </th>
        <?php } ?>
        <?php foreach ($cont_units as $cont) { ?>
        <th class="fix">
            <?php echo $cont->cont_unit_name ?> 
        </th>
        <?php } ?>
        <?php foreach ($cont_units as $cont) { ?>
        <th class="fix">
            <?php echo $cont->cont_unit_name ?> 
        </th>
        <?php } ?>
    </tr>
    
   </thead>
   <tbody>
    <?php 
    $v = array(); $daulanh=0; $km=0; $dinhmucdau=0; $boiduong=0; $cauduong=0; $congan=0; $diduong=0; 
    $vdaulanh=array(); $vkm=array(); $vdinhmucdau=array(); $vboiduong=array(); $vcauduong=array(); $vcongan=array(); $vdiduong=array(); 
    ?>
    <?php foreach ($shipments as $shipment) : ?>
    
    <?php
        $dau = ($shipment->shipment_road_oil>0?$shipment->shipment_road_oil:(isset($road['road_oil'][$shipment->shipment_id])?$road['road_oil'][$shipment->shipment_id]:0))+$shipment->shipment_road_oil_add;

        $way = isset($road['way_name'][$shipment->shipment_id])?$road['way_name'][$shipment->shipment_id]:null;
        $kms = isset($road['road_km'][$shipment->shipment_id])?$road['road_km'][$shipment->shipment_id]:null;
        $oil = isset($road['road_oil'][$shipment->shipment_id])?$road['road_oil'][$shipment->shipment_id]:null;
        $bd = isset($warehouse['boiduong_cn'][$shipment->shipment_id])?$warehouse['boiduong_cn'][$shipment->shipment_id]:null;
        $cd = isset($road['bridge_cost'][$shipment->shipment_id])?$road['bridge_cost'][$shipment->shipment_id]:null;
        $ca = isset($road['police_cost'][$shipment->shipment_id])?$road['police_cost'][$shipment->shipment_id]:null;
        

        $month = intval(date('m',$shipment->shipment_date));
        $year = date('Y',$shipment->shipment_date);

    ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" data="<?php echo $shipment->vehicle_id.$shipment->shipment_round ?>" id="<?php echo $shipment->shipment_id ?>" class="edit_tr">
            <td class="fix" id="shipment_id_<?php echo $shipment->shipment_id; ?>"><?php echo $j++; ?></td>
            <td class="fix" id="bill_number_<?php echo $shipment->shipment_id; ?>"><a target="_blank" href="<?php echo $this->url('shipment/index/'.$shipment->shipment_id) ?>" ><?php echo $shipment->bill_number; ?></a></td>

            <td class="fix" id="bill_receive_date_<?php echo $shipment->shipment_id; ?>"><?php echo $lib->hien_thi_ngay_thang($shipment->bill_receive_date); ?></td>
            <td class="fix" id="bill_delivery_date_<?php echo $shipment->shipment_id; ?>"><?php echo $lib->hien_thi_ngay_thang($shipment->bill_delivery_date); ?></td>
            <td class="fix" data="<?php echo $shipment->vehicle; ?>" id="vehicle_<?php echo $shipment->shipment_id; ?>"><a target="_blank" href="<?php echo $this->url('vehicle/index/'.$shipment->vehicle) ?>" ><?php echo $shipment->vehicle_number; ?></a></td>
            <td class="fix" data="<?php echo $shipment->romooc; ?>" id="romooc_<?php echo $shipment->shipment_id; ?>"><a target="_blank" href="<?php echo $this->url('romooc/index/'.$shipment->romooc) ?>" ><?php echo isset($romooc_data['romooc_number'][$shipment->romooc])?$romooc_data['romooc_number'][$shipment->romooc]:null; ?></a></td>
            <td class="fix" id="steersman_name_<?php echo $shipment->shipment_id; ?>" data="<?php echo $shipment->steersman; ?>"><a target="_blank" href="<?php echo $this->url('steersman/index/'.$shipment->steersman) ?>" ><?php echo $shipment->steersman_name; ?></a></td>
            <td class="fix" data="<?php echo $shipment->shipment_from; ?>" id="shipment_from_<?php echo $shipment->shipment_id; ?>"><a target="_blank" href="<?php echo $this->url('place/view/'.$shipment->shipment_from) ?>" ><?php echo $shipment->shipment_from==$place['place_id'][$shipment->shipment_from]?$place['place_name'][$shipment->shipment_from]:null ?></a></td>
            <td class="fix" data="<?php echo $shipment->shipment_to; ?>" id="shipment_to_<?php echo $shipment->shipment_id; ?>"><a target="_blank" href="<?php echo $this->url('place/view/'.$shipment->shipment_to) ?>" ><?php echo $shipment->shipment_to==$place['place_id'][$shipment->shipment_to]?$place['place_name'][$shipment->shipment_to]:null ?></a></td>
            
            <td class="fix" data="<?php echo $shipment->customer; ?>" id="customer_<?php echo $shipment->shipment_id; ?>"><a target="_blank" href="<?php echo $this->url('customer/index/'.$shipment->customer) ?>" ><?php echo $shipment->customer_name; ?></a></td>
            <td class="fix" id="road_km_<?php echo $shipment->shipment_id; ?>"><?php echo $lib->formatMoney(isset($road['road_km'][$shipment->shipment_id])?$road['road_km'][$shipment->shipment_id]:null); ?></td>
            <td class="fix" id="shipment_oil_<?php echo $shipment->shipment_id; ?>"><?php echo $shipment->shipment_oil; ?></td>
            <td class="fix" id="road_oil_<?php echo $shipment->shipment_id; ?>"><?php echo $dau; ?></td>
            <td class="fix" id="shipment_cost_<?php echo $shipment->shipment_id; ?>"><?php echo $lib->formatMoney($shipment->shipment_road_add); ?></td>
            <?php foreach ($loan_units as $loan) { 
                $chiho = isset($loan_shipment_data[$shipment->shipment_id][$loan->cost_list_id])?$loan_shipment_data[$shipment->shipment_id][$loan->cost_list_id]:null;

                $phatsinh[$loan->cost_list_id][$shipment->vehicle_id][$shipment->shipment_round.$month.$year] = isset($phatsinh[$loan->cost_list_id][$shipment->vehicle_id][$shipment->shipment_round.$month.$year])?$phatsinh[$loan->cost_list_id][$shipment->vehicle_id][$shipment->shipment_round.$month.$year]+$chiho:$chiho;
                $chiphi[$loan->cost_list_id] = isset($chiphi[$loan->cost_list_id])?$chiphi[$loan->cost_list_id]+$chiho:$chiho;
            ?>
            <td class="fix" id="shipment_loan_<?php echo $shipment->shipment_id; ?>"><?php echo $lib->formatMoney($chiho); ?></td>
            <?php } ?>
            <td class="fix" ><?php echo $lib->formatMoney(isset($road['bridge_cost'][$shipment->shipment_id])?$road['bridge_cost'][$shipment->shipment_id]:null); ?></td>
            <td class="fix" ><?php echo $lib->formatMoney(isset($road['police_cost'][$shipment->shipment_id])?$road['police_cost'][$shipment->shipment_id]:null); ?></td>
            <td class="fix" ><?php echo $lib->formatMoney(isset($warehouse['boiduong_cn'][$shipment->shipment_id])?$warehouse['boiduong_cn'][$shipment->shipment_id]:null); ?></td>
            <td  class="fix" id="customer_type_<?php echo $shipment->shipment_id; ?>"><?php echo $customer_types[$shipment->shipment_id]; ?></td>
            <?php foreach ($cont_units as $cont) { ?>
            <td class="fix" id="bill_receive_ton_<?php echo $shipment->shipment_id; ?>"><?php echo $shipment->bill_receive_unit==$cont->cont_unit_id?$shipment->bill_receive_ton:null; ?></td>
            <?php } ?>
            <?php foreach ($cont_units as $cont) { ?>
            <td class="fix" id="bill_delivery_ton_<?php echo $shipment->shipment_id; ?>"><?php echo $shipment->bill_delivery_unit==$cont->cont_unit_id?$shipment->bill_delivery_ton:null; ?></td>
            <?php } ?>
            <td class="fix" id="bill_in_<?php echo $shipment->shipment_id; ?>"><?php echo date('H:i:s',$shipment->bill_in); ?></td>
            <td class="fix" id="bill_out_<?php echo $shipment->shipment_id; ?>"><?php echo date('H:i:s',$shipment->bill_out); ?></td>
            
        </tr>

    
            <?php

            
        

        $v[$shipment->vehicle.$shipment->shipment_round.$month.$year] = isset($v[$shipment->vehicle.$shipment->shipment_round.$month.$year])?($v[$shipment->vehicle.$shipment->shipment_round.$month.$year] + 1) : (0+1) ;


                $daulanh += $shipment->shipment_oil;
                $km += $kms;
                $dinhmucdau += $dau;
                $boiduong += $bd;
                $cauduong += $cd+$shipment->bridge_cost_add;
                $congan += $ca;
                $diduong += $shipment->shipment_road_add;
                


                ///////

                $vdaulanh[$shipment->vehicle_id][$shipment->shipment_round.$month.$year] = isset($vdaulanh[$shipment->vehicle_id][$shipment->shipment_round.$month.$year])?($vdaulanh[$shipment->vehicle_id][$shipment->shipment_round.$month.$year] + $shipment->shipment_oil):(0+$shipment->shipment_oil);
                $vkm[$shipment->vehicle_id][$shipment->shipment_round.$month.$year] = isset($vkm[$shipment->vehicle_id][$shipment->shipment_round.$month.$year])?($vkm[$shipment->vehicle_id][$shipment->shipment_round.$month.$year] + $kms):(0+$kms);
                $vdinhmucdau[$shipment->vehicle_id][$shipment->shipment_round.$month.$year] = isset($vdinhmucdau[$shipment->vehicle_id][$shipment->shipment_round.$month.$year])?($vdinhmucdau[$shipment->vehicle_id][$shipment->shipment_round.$month.$year] + $dau):(0+$dau);
                $vboiduong[$shipment->vehicle_id][$shipment->shipment_round.$month.$year] = isset($vboiduong[$shipment->vehicle_id][$shipment->shipment_round.$month.$year])?($vboiduong[$shipment->vehicle_id][$shipment->shipment_round.$month.$year] + $bd):(0+$bd);
                $vcauduong[$shipment->vehicle_id][$shipment->shipment_round.$month.$year] = isset($vcauduong[$shipment->vehicle_id][$shipment->shipment_round.$month.$year])?($vcauduong[$shipment->vehicle_id][$shipment->shipment_round.$month.$year] + $cd+$shipment->bridge_cost_add):(0+$cd+$shipment->bridge_cost_add);
                $vcongan[$shipment->vehicle_id][$shipment->shipment_round.$month.$year] = isset($vcongan[$shipment->vehicle_id][$shipment->shipment_round.$month.$year])?($vcongan[$shipment->vehicle_id][$shipment->shipment_round.$month.$year] + $ca):(0+$ca);
                $vdiduong[$shipment->vehicle_id][$shipment->shipment_round.$month.$year] = isset($vdiduong[$shipment->vehicle_id][$shipment->shipment_round.$month.$year])?($vdiduong[$shipment->vehicle_id][$shipment->shipment_round.$month.$year] + $shipment->shipment_road_add):(0+$shipment->shipment_road_add);
                
                ////////

            if($arr[$shipment->vehicle.$shipment->shipment_round.$month.$year] == $v[$shipment->vehicle.$shipment->shipment_round.$month.$year]){
            ?>
            
            <tr style="background-color: rgb(236, 215, 215);">
                <td class="fix" colspan="8"></td>
                <th style="border-right: 1px solid rgb(236, 235, 235);border-top: 1px solid #80C8E5;padding: 7px;" colspan="2">
                    Tổng cộng
                </th>
                
                <td class="fix warning" ><?php echo $lib->formatMoney($vkm[$shipment->vehicle_id][$shipment->shipment_round.$month.$year]) ?></td>
                <td class="fix warning" ><?php echo $lib->formatMoney($vdaulanh[$shipment->vehicle_id][$shipment->shipment_round.$month.$year]) ?></td>
                <td class="fix warning" ><?php echo $lib->formatMoney($vdinhmucdau[$shipment->vehicle_id][$shipment->shipment_round.$month.$year]) ?></td>
                <td class="fix warning" ><?php echo $lib->formatMoney($vdiduong[$shipment->vehicle_id][$shipment->shipment_round.$month.$year]) ?></td>
                
                <?php foreach ($loan_units as $loan) { ?>
                <td class="fix warning" ><?php echo $lib->formatMoney(isset($phatsinh[$loan->cost_list_id][$shipment->vehicle_id][$shipment->shipment_round.$month.$year])?$phatsinh[$loan->cost_list_id][$shipment->vehicle_id][$shipment->shipment_round.$month.$year]:null) ?></td>
                <?php } ?>

                <td class="fix warning" ><?php echo $lib->formatMoney($vcauduong[$shipment->vehicle_id][$shipment->shipment_round.$month.$year]) ?></td>
                <td class="fix warning" ><?php echo $lib->formatMoney($vcongan[$shipment->vehicle_id][$shipment->shipment_round.$month.$year]) ?></td>
                <td class="fix warning" ><?php echo $lib->formatMoney($vboiduong[$shipment->vehicle_id][$shipment->shipment_round.$month.$year]) ?></td>
                <td class="fix" colspan="9"></td>
                
            </tr>

            <?php } ?>

    <?php endforeach; ?>

        <tr>
            <td colspan="30"></td>
        </tr>
        <tr style="font-weight: bold;background-color: rgb(214, 249, 246);">
            <td class="fix" colspan="8"></td>
            <th style="border-right: 1px solid rgb(236, 235, 235);border-top: 1px solid #80C8E5;padding: 7px;" colspan="2">
                Tổng cộng
            </th>
            <td class="fix " ><?php echo $lib->formatMoney($km) ?></td>
            <td class="fix " ><?php echo $lib->formatMoney($daulanh) ?></td>
            <td class="fix " ><?php echo $lib->formatMoney($dinhmucdau) ?></td>
            <td class="fix " ><?php echo $lib->formatMoney($diduong) ?></td>
            
            <?php foreach ($loan_units as $loan) { ?>
            <td class="fix " ><?php echo $lib->formatMoney(isset($chiphi[$loan->cost_list_id])?$chiphi[$loan->cost_list_id]:null) ?></td>
            <?php } ?>
            
            <td class="fix " ><?php echo $lib->formatMoney($cauduong) ?></td>
            <td class="fix " ><?php echo $lib->formatMoney($congan) ?></td>
            <td class="fix " ><?php echo $lib->formatMoney($boiduong) ?></td>
            <td class="fix" colspan="9"></td>
            
        </tr>
   </tbody>
</table>

<div style="margin-top: 20px"><div class="add-box"><a class="add_button" id="btnExport3" ><i class="fa fa-download"></i> Xuất</a></div></div>

<script type="text/javascript">
$(document).ready(function () {

    $("#btnExport3").click(function () {

        $("#tblExport3").battatech_excelexport({

            containerid: "tblExport3"

           , datatype: 'table'

        });

    });

});
</script>