<!DOCTYPE html>
<html lang="vi">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta charset="utf-8" />
    <title><?php echo isset($title) ? $title : null ?></title>

    <meta name="description" content="Transportation Management System - TMS" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
    <link href="/public/images/logo.png" rel="shortcut icon" type="image/vnd.microsoft.icon">

    <!-- bootstrap & fontawesome -->
    <link rel="stylesheet" href="/public/assets/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/public/assets/font-awesome/4.5.0/css/font-awesome.min.css" />

    <!-- page specific plugin styles -->
    <link rel="stylesheet" href="/public/assets/css/jquery-ui.min.css" />

    <!-- text fonts -->
    <link rel="stylesheet" href="/public/assets/css/fonts.googleapis.com.css" />

    <!-- ace styles -->
    <link rel="stylesheet" href="/public/assets/css/ace.min.css" class="ace-main-stylesheet" id="main-ace-style" />

    <!--[if lte IE 9]>
      <link rel="stylesheet" href="/public/assets/css/ace-part2.min.css" class="ace-main-stylesheet" />
    <![endif]-->
    <link rel="stylesheet" href="/public/assets/css/ace-skins.min.css" />
    <link rel="stylesheet" href="/public/assets/css/ace-rtl.min.css" />

    <!--[if lte IE 9]>
      <link rel="stylesheet" href="/public/assets/css/ace-ie.min.css" />
    <![endif]-->

    <!-- inline styles related to this page -->

    <!-- ace settings handler -->
    <script src="/public/assets/js/ace-extra.min.js"></script>

    <!-- HTML5shiv and Respond.js for IE8 to support HTML5 elements and media queries -->

    <!--[if lte IE 8]>
    <script src="/public/assets/js/html5shiv.min.js"></script>
    <script src="/public/assets/js/respond.min.js"></script>
    <![endif]-->

    <!--[if !IE]> -->
    <script src="/public/assets/js/jquery-2.1.4.min.js"></script>
    <script src="/public/assets/js/jquery.validate.min.js"></script>
    
    <link rel="stylesheet" href="/public/assets/css/bootstrap-multiselect.min.css" />
    <link rel="stylesheet" href="/public/assets/css/select2.min.css" />
    <link rel="stylesheet" href="/public/assets/css/bootstrap-editable.min.css" />
    <link rel="stylesheet" href="/public/assets/css/bootstrap-datepicker3.min.css">
    <link rel="stylesheet" href="/public/assets/css/bootstrap-timepicker.min.css">

    <!-- <![endif]-->
    <link rel="stylesheet" href="/public/css/style.css?v=2">
    <link rel="stylesheet" href="/public/css/head.css">
    <script type="text/javascript" src="/public/js/head.js?v=2"></script>
    
    <script type="text/javascript">
    $("#ajax_loader").fadeIn(200);

    var check_lock_user = 0;

      $.ajax({

        type: "POST",

        url: "/admin/checklockuser",

        data: "data=<?php echo isset($_SESSION['userid_logined'])?$_SESSION['userid_logined']:0 ?>", // or any data you want to send

        cache: false,

        success: function(html){

          check_lock_user = html;

          if (check_lock_user==1) {

            $.ajax({

              type: "GET",

              url: "/user/logout",

              data: "data=1", // or any data you want to send

              cache: false,

              success: function(html){

                window.location.href = "";

              }

            });

          };

        }

      });
      
    </script>
  </head>
  <body class="no-skin">
    <div id="navbar" class="navbar navbar-default          ace-save-state">
      <div class="navbar-container ace-save-state" id="navbar-container">
        <button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler" data-target="#sidebar">
          <span class="sr-only">Toggle sidebar</span>

          <span class="icon-bar"></span>

          <span class="icon-bar"></span>

          <span class="icon-bar"></span>
        </button>

        <div class="navbar-header pull-left">
          <a href="<?php echo BASE_URL ?>" class="navbar-brand">
            <small>
              <img width="25" height="25" src="/public/images/logo.png" alt="Avatar" />
              TMS
            </small>
          </a>
        </div>

        <div class="navbar-buttons navbar-header pull-right" role="navigation">
          <ul class="nav ace-nav">
            <li class="grey dropdown-modal">
              <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                <i class="ace-icon fa fa-tasks"></i>
                <span class="badge badge-grey">4</span>
              </a>

              <ul class="dropdown-menu-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close">
                <li class="dropdown-header">
                  <i class="ace-icon fa fa-check"></i>
                  4 Tasks to complete
                </li>

                <li class="dropdown-content">
                  <ul class="dropdown-menu dropdown-navbar">
                    <li>
                      <a href="#">
                        <div class="clearfix">
                          <span class="pull-left">Software Update</span>
                          <span class="pull-right">65%</span>
                        </div>

                        <div class="progress progress-mini">
                          <div style="width:65%" class="progress-bar"></div>
                        </div>
                      </a>
                    </li>

                    <li>
                      <a href="#">
                        <div class="clearfix">
                          <span class="pull-left">Hardware Upgrade</span>
                          <span class="pull-right">35%</span>
                        </div>

                        <div class="progress progress-mini">
                          <div style="width:35%" class="progress-bar progress-bar-danger"></div>
                        </div>
                      </a>
                    </li>

                    <li>
                      <a href="#">
                        <div class="clearfix">
                          <span class="pull-left">Unit Testing</span>
                          <span class="pull-right">15%</span>
                        </div>

                        <div class="progress progress-mini">
                          <div style="width:15%" class="progress-bar progress-bar-warning"></div>
                        </div>
                      </a>
                    </li>

                    <li>
                      <a href="#">
                        <div class="clearfix">
                          <span class="pull-left">Bug Fixes</span>
                          <span class="pull-right">90%</span>
                        </div>

                        <div class="progress progress-mini progress-striped active">
                          <div style="width:90%" class="progress-bar progress-bar-success"></div>
                        </div>
                      </a>
                    </li>
                  </ul>
                </li>

                <li class="dropdown-footer">
                  <a href="#">
                    See tasks with details
                    <i class="ace-icon fa fa-arrow-right"></i>
                  </a>
                </li>
              </ul>
            </li>

            <li class="purple dropdown-modal">
              <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                <i class="ace-icon fa fa-bell icon-animated-bell"></i>
                <span class="badge badge-important">8</span>
              </a>

              <ul class="dropdown-menu-right dropdown-navbar navbar-pink dropdown-menu dropdown-caret dropdown-close">
                <li class="dropdown-header">
                  <i class="ace-icon fa fa-exclamation-triangle"></i>
                  8 Notifications
                </li>

                <li class="dropdown-content">
                  <ul class="dropdown-menu dropdown-navbar navbar-pink">
                    <li>
                      <a href="#">
                        <div class="clearfix">
                          <span class="pull-left">
                            <i class="btn btn-xs no-hover btn-pink fa fa-comment"></i>
                            New Comments
                          </span>
                          <span class="pull-right badge badge-info">+12</span>
                        </div>
                      </a>
                    </li>

                    <li>
                      <a href="#">
                        <i class="btn btn-xs btn-primary fa fa-user"></i>
                        Bob just signed up as an editor ...
                      </a>
                    </li>

                    <li>
                      <a href="#">
                        <div class="clearfix">
                          <span class="pull-left">
                            <i class="btn btn-xs no-hover btn-success fa fa-shopping-cart"></i>
                            New Orders
                          </span>
                          <span class="pull-right badge badge-success">+8</span>
                        </div>
                      </a>
                    </li>

                    <li>
                      <a href="#">
                        <div class="clearfix">
                          <span class="pull-left">
                            <i class="btn btn-xs no-hover btn-info fa fa-twitter"></i>
                            Followers
                          </span>
                          <span class="pull-right badge badge-info">+11</span>
                        </div>
                      </a>
                    </li>
                  </ul>
                </li>

                <li class="dropdown-footer">
                  <a href="#">
                    See all notifications
                    <i class="ace-icon fa fa-arrow-right"></i>
                  </a>
                </li>
              </ul>
            </li>

            <li class="green dropdown-modal">
              <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                <i class="ace-icon fa fa-envelope icon-animated-vertical"></i>
                <span class="badge badge-success">5</span>
              </a>

              <ul class="dropdown-menu-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close">
                <li class="dropdown-header">
                  <i class="ace-icon fa fa-envelope-o"></i>
                  5 Messages
                </li>

                <li class="dropdown-content">
                  <ul class="dropdown-menu dropdown-navbar">
                    <li>
                      <a href="#" class="clearfix">
                        <img src="/public/assets/images/avatars/avatar.png" class="msg-photo" alt="Alex's Avatar" />
                        <span class="msg-body">
                          <span class="msg-title">
                            <span class="blue">Alex:</span>
                            Ciao sociis natoque penatibus et auctor ...
                          </span>

                          <span class="msg-time">
                            <i class="ace-icon fa fa-clock-o"></i>
                            <span>a moment ago</span>
                          </span>
                        </span>
                      </a>
                    </li>

                    <li>
                      <a href="#" class="clearfix">
                        <img src="/public/assets/images/avatars/avatar3.png" class="msg-photo" alt="Susan's Avatar" />
                        <span class="msg-body">
                          <span class="msg-title">
                            <span class="blue">Susan:</span>
                            Vestibulum id ligula porta felis euismod ...
                          </span>

                          <span class="msg-time">
                            <i class="ace-icon fa fa-clock-o"></i>
                            <span>20 minutes ago</span>
                          </span>
                        </span>
                      </a>
                    </li>

                    <li>
                      <a href="#" class="clearfix">
                        <img src="/public/assets/images/avatars/avatar4.png" class="msg-photo" alt="Bob's Avatar" />
                        <span class="msg-body">
                          <span class="msg-title">
                            <span class="blue">Bob:</span>
                            Nullam quis risus eget urna mollis ornare ...
                          </span>

                          <span class="msg-time">
                            <i class="ace-icon fa fa-clock-o"></i>
                            <span>3:15 pm</span>
                          </span>
                        </span>
                      </a>
                    </li>

                    <li>
                      <a href="#" class="clearfix">
                        <img src="/public/assets/images/avatars/avatar2.png" class="msg-photo" alt="Kate's Avatar" />
                        <span class="msg-body">
                          <span class="msg-title">
                            <span class="blue">Kate:</span>
                            Ciao sociis natoque eget urna mollis ornare ...
                          </span>

                          <span class="msg-time">
                            <i class="ace-icon fa fa-clock-o"></i>
                            <span>1:33 pm</span>
                          </span>
                        </span>
                      </a>
                    </li>

                    <li>
                      <a href="#" class="clearfix">
                        <img src="/public/assets/images/avatars/avatar5.png" class="msg-photo" alt="Fred's Avatar" />
                        <span class="msg-body">
                          <span class="msg-title">
                            <span class="blue">Fred:</span>
                            Vestibulum id penatibus et auctor  ...
                          </span>

                          <span class="msg-time">
                            <i class="ace-icon fa fa-clock-o"></i>
                            <span>10:09 am</span>
                          </span>
                        </span>
                      </a>
                    </li>
                  </ul>
                </li>

                <li class="dropdown-footer">
                  <a href="inbox.html">
                    See all messages
                    <i class="ace-icon fa fa-arrow-right"></i>
                  </a>
                </li>
              </ul>
            </li>

            <li class="light-blue dropdown-modal">
              <a data-toggle="dropdown" href="#" class="dropdown-toggle">
                <img class="nav-user-photo" src="/public/assets/images/avatars/avatar.png" alt="Avatar" />
                <span class="user-info">
                  <small>Welcome,</small>
                  <?php echo $_SESSION['user_logined']; ?>
                </span>

                <i class="ace-icon fa fa-caret-down"></i>
              </a>

              <ul class="user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
                <li>
                  <a href="<?php echo BASE_URL.'/user/info/'.$_SESSION['userid_logined'] ?>">
                    <i class="ace-icon fa fa-cog"></i>
                    Cài đặt
                  </a>
                </li>

                <li class="divider"></li>

                <li>
                  <a href="<?php echo $this->url('user/logout') ?>">
                    <i class="ace-icon fa fa-power-off"></i>
                    Logout
                  </a>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div><!-- /.navbar-container -->
    </div>

    <div class="main-container ace-save-state" id="main-container">
      <script type="text/javascript">
        try{ace.settings.loadState('main-container')}catch(e){}
      </script>

      <div id="sidebar" class="sidebar                  responsive                    ace-save-state">
        <script type="text/javascript">
          try{ace.settings.loadState('sidebar')}catch(e){}
        </script>

        <!-- <div class="sidebar-shortcuts" id="sidebar-shortcuts">
          <div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
            <button class="btn btn-success">
              <i class="ace-icon fa fa-signal"></i>
            </button>

            <button class="btn btn-info">
              <i class="ace-icon fa fa-pencil"></i>
            </button>

            <button class="btn btn-warning">
              <i class="ace-icon fa fa-users"></i>
            </button>

            <button class="btn btn-danger">
              <i class="ace-icon fa fa-cogs"></i>
            </button>
          </div>

          <div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
            <span class="btn btn-success"></span>

            <span class="btn btn-info"></span>

            <span class="btn btn-warning"></span>

            <span class="btn btn-danger"></span>
          </div>
        </div> --><!-- /.sidebar-shortcuts -->

        <ul class="nav nav-list">
          <li class="">
            <a data="admin" data-role="admin" href="<?php echo $this->url('admin') ?>">
              <i class="menu-icon fa fa-tachometer"></i>
              <span class="menu-text"> Dashboard </span>
            </a>

            <b class="arrow"></b>
          </li>

          <li class="">
            <a data="#" href="#" class="dropdown-toggle">
              <i class="menu-icon fa fa-pie-chart"></i>
              <span class="menu-text">
                Báo cáo
              </span>

              <b class="arrow fa fa-angle-down"></b>
            </a>

            <b class="arrow"></b>

            <ul class="submenu">
              
              <li class="">
                <a data="#" href="#" >
                  <i class="menu-icon fa fa-caret-right"></i>

                  Phiếu vận chuyển
                </a>

                <b class="arrow"></b>
              </li>
              <li class="">
                <a data="#" href="#" class="dropdown-toggle">
                  <i class="menu-icon fa fa-caret-right"></i>

                  Tổng hợp sản lượng
                  <b class="arrow fa fa-angle-down"></b>
                </a>

                <b class="arrow"></b>

                <ul class="submenu">
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Bảng kê sản lượng
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Sản lượng khách hàng
                    </a>

                    <b class="arrow"></b>
                  </li>
                  
                </ul>
              </li>
              <li class="">
                <a data="#" href="#" class="dropdown-toggle">
                  <i class="menu-icon fa fa-caret-right"></i>

                  Chi phí xe
                  <b class="arrow fa fa-angle-down"></b>
                </a>

                <b class="arrow"></b>

                <ul class="submenu">
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Sửa chữa bảo dưỡng
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Phí sử dụng đường bộ
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Phí kiểm định
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Bảo hiểm
                    </a>

                    <b class="arrow"></b>
                  </li>
                </ul>
              </li>
              <li class="">
                <a data="#" href="#" >
                  <i class="menu-icon fa fa-caret-right"></i>

                  Báo cáo dầu
                </a>

                <b class="arrow"></b>
              </li>
              <li class="">
                <a data="#" href="#" >
                  <i class="menu-icon fa fa-caret-right"></i>

                  Hoa hồng
                </a>

                <b class="arrow"></b>
              </li>
              <li class="">
                <a data="#" href="#" >
                  <i class="menu-icon fa fa-caret-right"></i>

                  Tạm ứng
                </a>

                <b class="arrow"></b>
              </li>
              <li class="">
                <a data="#" href="#" >
                  <i class="menu-icon fa fa-caret-right"></i>

                  Chi phí hành chính
                </a>

                <b class="arrow"></b>
              </li>
              <li class="">
                <a data="#" href="#" >
                  <i class="menu-icon fa fa-caret-right"></i>

                  Quá trình hoạt động
                </a>

                <b class="arrow"></b>
              </li>
              <li class="">
                <a data="#" href="#" >
                  <i class="menu-icon fa fa-caret-right"></i>

                  Kết quả kinh doanh
                </a>

                <b class="arrow"></b>
              </li>
            </ul>
          </li>
          <li class="">
            <a data="#" href="#" class="dropdown-toggle">
              <i class="menu-icon fa fa-dollar"></i>
              <span class="menu-text">
                Kế toán
              </span>

              <b class="arrow fa fa-angle-down"></b>
            </a>

            <b class="arrow"></b>

            <ul class="submenu">
              <li class="">
                <a data="#" href="#" class="dropdown-toggle">
                  <i class="menu-icon fa fa-money"></i>

                  Quỹ
                  <b class="arrow fa fa-angle-down"></b>
                </a>

                <b class="arrow"></b>

                <ul class="submenu">
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Phiếu thu
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Phiếu chi
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Chuyển tiền nội bộ
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Sổ quỹ
                    </a>

                    <b class="arrow"></b>
                  </li>
                </ul>
              </li>
              <li class="">
                <a data="#" href="#" class="dropdown-toggle">
                  <i class="menu-icon fa fa-bank"></i>

                  Tiền gửi
                  <b class="arrow fa fa-angle-down"></b>
                </a>

                <b class="arrow"></b>

                <ul class="submenu">
                  
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Thu tiền
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Thanh toán
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Sổ tiền gửi
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Tài khoản ngân hàng
                    </a>

                    <b class="arrow"></b>
                  </li>
                </ul>
              </li>
              <li class="">
                <a data="#" href="#" class="dropdown-toggle">
                  <i class="menu-icon fa fa-truck"></i>

                  Lô hàng
                  <b class="arrow fa fa-angle-down"></b>
                </a>

                <b class="arrow"></b>

                <ul class="submenu">
                  
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Xuất hóa đơn
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Doanh thu
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="#" href="#" class="dropdown-toggle">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Chi phí
                      <b class="arrow fa fa-angle-down"></b>
                    </a>

                    <b class="arrow"></b>

                    <ul class="submenu">
                      <li class="">
                        <a data="#" href="#">
                          <i class="menu-icon fa fa-caret-right"></i>
                          Tổng hợp
                        </a>

                        <b class="arrow"></b>
                      </li>

                      <li class="">
                        <a data="#" href="#">
                          <i class="menu-icon fa fa-caret-right"></i>
                          Không hóa đơn
                        </a>

                        <b class="arrow"></b>
                      </li>
                      <li class="">
                        <a data="#" href="#">
                          <i class="menu-icon fa fa-caret-right"></i>
                          Phí cầu đường
                        </a>

                        <b class="arrow"></b>
                      </li>
                    </ul>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Danh mục chi phí
                    </a>

                    <b class="arrow"></b>
                  </li>
                </ul>
              </li>
              <li class="">
                <a data="#" href="#" class="dropdown-toggle">
                  <i class="menu-icon fa fa-user"></i>

                  Công nợ
                  <b class="arrow fa fa-angle-down"></b>
                </a>

                <b class="arrow"></b>

                <ul class="submenu">
                  
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Phải thu
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Phải trả
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Chi hộ
                    </a>

                    <b class="arrow"></b>
                  </li>
                </ul>
              </li>
              <li class="">
                <a data="#" href="#" class="dropdown-toggle">
                  <i class="menu-icon fa fa-database"></i>

                  Kho
                  <b class="arrow fa fa-angle-down"></b>
                </a>

                <b class="arrow"></b>

                <ul class="submenu">
                  
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Chi tiết hàng hóa
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Tổng hợp tồn kho
                    </a>

                    <b class="arrow"></b>
                  </li>
                </ul>
              </li>
              <li class="">
                <a data="#" href="#" class="dropdown-toggle">
                  <i class="menu-icon fa fa-file-text-o"></i>

                  Tổng hợp
                  <b class="arrow fa fa-angle-down"></b>
                </a>

                <b class="arrow"></b>

                <ul class="submenu">
                  
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Danh mục tài khoản
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Phiếu kế toán
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Nhật ký chung
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Sổ chi tiết
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Kết chuyển lãi lỗ
                    </a>

                    <b class="arrow"></b>
                  </li>
                </ul>
              </li>
              <li class="">
                <a data="#" href="#" class="dropdown-toggle">
                  <i class="menu-icon fa fa-calculator"></i>

                  Báo cáo thuế
                  <b class="arrow fa fa-angle-down"></b>
                </a>

                <b class="arrow"></b>

                <ul class="submenu">
                  
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Bảng kê HĐ mua vào
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Bảng kê HĐ bán ra
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Tờ khai thuế GTGT
                    </a>

                    <b class="arrow"></b>
                  </li>
                  
                </ul>
              </li>
              <li class="">
                <a data="#" href="#" class="dropdown-toggle">
                  <i class="menu-icon fa fa-line-chart"></i>

                  Báo cáo tài chính
                  <b class="arrow fa fa-angle-down"></b>
                </a>

                <b class="arrow"></b>

                <ul class="submenu">
                  
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Bảng cân đối phát sinh
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Bảng cân đối kế toán
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Báo cáo KQHĐKD
                    </a>

                    <b class="arrow"></b>
                  </li>
                  
                </ul>
              </li>
            </ul>
          </li>
          <li class="">
            <a data="#" href="#" class="dropdown-toggle">
              <i class="menu-icon fa fa-clipboard"></i>
              <span class="menu-text">
                Kinh doanh
              </span>

              <b class="arrow fa fa-angle-down"></b>
            </a>

            <b class="arrow"></b>

            <ul class="submenu">
              
              <li class="">
                <a data="#" href="#" >
                  <i class="menu-icon fa fa-book"></i>

                  Booking
                </a>

                <b class="arrow"></b>
              </li>
              <li class="">
                <a data="#" href="#" >
                  <i class="menu-icon fa fa-file-text-o"></i>

                  Bảng kê vận chuyển
                </a>

                <b class="arrow"></b>
              </li>
              <li class="">
                <a data="#" href="#" >
                  <i class="menu-icon fa fa-file-text-o"></i>

                  Bảng kê chi hộ
                </a>

                <b class="arrow"></b>
              </li>
              <li class="">
                <a data="#" href="#" >
                  <i class="menu-icon fa fa-money"></i>

                  Hoa hồng
                </a>

                <b class="arrow"></b>
              </li>
            </ul>
          </li>
          <li class="">
            <a data="#" href="#" class="dropdown-toggle">
              <i class="menu-icon fa fa-truck"></i>
              <span class="menu-text">
                Điều độ
              </span>

              <b class="arrow fa fa-angle-down"></b>
            </a>

            <b class="arrow"></b>

            <ul class="submenu">
              
              <li class="">
                <a data="#" href="#" class="dropdown-toggle">
                  <i class="menu-icon fa fa-cubes"></i>

                  Lô hàng
                  <b class="arrow fa fa-angle-down"></b>
                </a>

                <b class="arrow"></b>

                <ul class="submenu">
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-clock-o orange"></i>

                      Đang chờ
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-check green"></i>

                      Đã nhận
                    </a>

                    <b class="arrow"></b>
                  </li>
                </ul>
              </li>
              <li class="">
                <a data="#" href="#" >
                  <i class="menu-icon fa fa-road"></i>

                  Điều xe
                </a>

                <b class="arrow"></b>
              </li>
              <li class="">
                <a data="#" href="#" >
                  <i class="menu-icon fa fa-file-text-o"></i>

                  Phiếu cầu đường
                </a>

                <b class="arrow"></b>
              </li>
              <li class="">
                <a data="#" href="#" >
                  <i class="menu-icon fa fa-arrow-circle-up"></i>

                  Nâng hạ cont
                </a>

                <b class="arrow"></b>
              </li>
              <li class="">
                <a data="#" href="#" >
                  <i class="menu-icon fa fa-exchange"></i>

                  Bàn giao xe
                </a>

                <b class="arrow"></b>
              </li>
              <li class="">
                <a data="#" href="#" >
                  <i class="menu-icon fa fa-pause-circle-o"></i>

                  Tạm dừng xe
                </a>

                <b class="arrow"></b>
              </li>
              <li class="">
                <a data="#" href="#" class="dropdown-toggle">
                  <i class="menu-icon fa fa-eraser"></i>

                  Mooc
                  <b class="arrow fa fa-angle-down"></b>
                </a>

                <b class="arrow"></b>

                <ul class="submenu">
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Thay mooc
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Quản lý mooc
                    </a>

                    <b class="arrow"></b>
                  </li>
                </ul>
              </li>
            </ul>
          </li>
          <li class="">
            <a data="#" href="#" class="dropdown-toggle">
              <i class="menu-icon fa fa-gear"></i>
              <span class="menu-text">
                Vật tư
              </span>

              <b class="arrow fa fa-angle-down"></b>
            </a>

            <b class="arrow"></b>

            <ul class="submenu">
              <li class="">
                <a data="backup" data-role="backup" href="<?php echo $this->url('backup') ?>">
                  <i class="menu-icon fa fa-tachometer"></i>

                  Bảng theo dõi
                </a>

                <b class="arrow"></b>
              </li>
              <li class="">
                <a data="#" href="#" class="dropdown-toggle">
                  <i class="menu-icon fa fa-database"></i>

                  Kho
                  <b class="arrow fa fa-angle-down"></b>
                </a>

                <b class="arrow"></b>

                <ul class="submenu">
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Nhập kho
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Xuất kho
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Tồn kho
                    </a>

                    <b class="arrow"></b>
                  </li>
                </ul>
              </li>
              <li class="">
                <a data="#" href="#" class="dropdown-toggle">
                  <i class="menu-icon fa fa-calendar"></i>

                  Kiểm định, bảo hiểm
                  <b class="arrow fa fa-angle-down"></b>
                </a>

                <b class="arrow"></b>

                <ul class="submenu">
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Phí sử dụng đường bộ
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Phí kiểm định
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Phí bảo hiểm
                    </a>

                    <b class="arrow"></b>
                  </li>
                </ul>
              </li>
              <li class="">
                <a data="#" href="#" class="dropdown-toggle">
                  <i class="menu-icon fa fa-wrench"></i>

                  Thay thế phụ tùng
                  <b class="arrow fa fa-angle-down"></b>
                </a>

                <b class="arrow"></b>

                <ul class="submenu">
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Tháo lắp phụ tùng
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Chuyển đổi phụ tùng
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Phụ tùng thay ra
                    </a>

                    <b class="arrow"></b>
                  </li>
                </ul>
              </li>
              <li class="">
                <a data="user" data-role="user" href="<?php echo $this->url('user') ?>">
                  <i class="menu-icon fa fa-calendar-check-o"></i>

                  Sửa chữa bảo dưỡng
                </a>

                <b class="arrow"></b>
              </li>
              <li class="">
                <a data="permission" data-role="permission" href="<?php echo $this->url('permission') ?>">
                  <i class="menu-icon fa fa-tint"></i>

                  Đổ dầu
                </a>

                <b class="arrow"></b>
              </li>
              <li class="">
                <a data="user" data-role="user" href="<?php echo $this->url('user') ?>">
                  <i class="menu-icon fa fa-home"></i>

                  Danh sách kho vật tư
                </a>

                <b class="arrow"></b>
              </li>
              <li class="">
                <a data="user" data-role="user" href="<?php echo $this->url('user') ?>">
                  <i class="menu-icon fa fa-dropbox"></i>

                  Danh sách vật tư
                </a>

                <b class="arrow"></b>
              </li>
            </ul>
          </li>
          <li class="">
            <a data="#" href="#" class="dropdown-toggle">
              <i class="menu-icon fa fa-users"></i>
              <span class="menu-text">
                Nhân sự
              </span>

              <b class="arrow fa fa-angle-down"></b>
            </a>

            <b class="arrow"></b>

            <ul class="submenu">
              
              <li class="">
                <a data="#" href="#" class="dropdown-toggle">
                  <i class="menu-icon fa fa-table"></i>

                  Bảng lương
                  <b class="arrow fa fa-angle-down"></b>
                </a>

                <b class="arrow"></b>

                <ul class="submenu">
                  <li class="">
                    <a data="salary/driver" data-role="salary" href="<?php echo $this->url('salary/driver') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Lương tài xế
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="salary/staff" data-role="salary" href="<?php echo $this->url('salary/staff') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Lương nhân viên
                    </a>

                    <b class="arrow"></b>
                  </li>
                </ul>
              </li>
              <li class="">
                <a data="staff" data-role="staff" href="<?php echo $this->url('staff') ?>">
                  <i class="menu-icon fa fa-user"></i>

                  Danh sách nhân viên
                </a>

                <b class="arrow"></b>
              </li>
              <li class="">
                <a data="department" data-role="department" href="<?php echo $this->url('department') ?>">
                  <i class="menu-icon fa fa-archive"></i>

                  Danh sách phòng ban
                </a>

                <b class="arrow"></b>
              </li>
              <li class="">
                <a data="position" data-role="position" href="<?php echo $this->url('position') ?>">
                  <i class="menu-icon fa fa-user-secret"></i>

                  Danh sách chức vụ
                </a>

                <b class="arrow"></b>
              </li>
            </ul>
          </li>
          <li class="">
            <a data="#" href="#" class="dropdown-toggle">
              <i class="menu-icon fa fa-th-list"></i>
              <span class="menu-text">
                Danh mục
              </span>

              <b class="arrow fa fa-angle-down"></b>
            </a>

            <b class="arrow"></b>

            <ul class="submenu">
              <li class="">
                <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                  <i class="menu-icon fa fa-user"></i>

                  Khách hàng - Đối tác
                </a>

                <b class="arrow"></b>
              </li>
              <li class="">
                <a data="vehicle" data-role="vehicle" href="<?php echo $this->url('vehicle') ?>">
                  <i class="menu-icon fa fa-car"></i>

                  Danh sách xe
                </a>

                <b class="arrow"></b>
              </li>
              <li class="">
                <a data="romooc" data-role="romooc" href="<?php echo $this->url('romooc') ?>">
                  <i class="menu-icon fa fa-eraser"></i>

                  Danh sách mooc
                </a>

                <b class="arrow"></b>
              </li>
              <li class="">
                <a data="place" data-role="place" href="<?php echo $this->url('place') ?>">
                  <i class="menu-icon fa fa-home"></i>

                  Danh sách kho hàng
                </a>

                <b class="arrow"></b>
              </li>
              <li class="">
                <a data="route" data-role="route" href="<?php echo $this->url('route') ?>">
                  <i class="menu-icon fa fa-map-marker"></i>

                  Danh sách địa điểm
                </a>

                <b class="arrow"></b>
              </li>
              <li class="">
                <a data="shipping" data-role="shipping" href="<?php echo $this->url('shipping') ?>">
                  <i class="menu-icon fa fa-ship"></i>

                  Hãng tàu
                </a>

                <b class="arrow"></b>
              </li>
              <li class="">
                <a data="port" data-role="port" href="<?php echo $this->url('port') ?>">
                  <i class="menu-icon fa fa-anchor"></i>

                  Cảng
                </a>

                <b class="arrow"></b>
              </li>
              <li class="">
                <a data="#" href="#" class="dropdown-toggle">
                  <i class="menu-icon fa fa-flask"></i>

                  Định mức
                  <b class="arrow fa fa-angle-down"></b>
                </a>

                <b class="arrow"></b>

                <ul class="submenu">
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Định mức dầu
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Định mức tuyến đường
                    </a>

                    <b class="arrow"></b>
                  </li>
                  <li class="">
                    <a data="update" data-role="update" href="<?php echo $this->url('update') ?>">
                      <i class="menu-icon fa fa-caret-right"></i>

                      Bồi dưỡng kho
                    </a>

                    <b class="arrow"></b>
                  </li>
                </ul>
              </li>
              
              <li class="">
                <a data="bonus" data-role="bonus" href="<?php echo $this->url('bonus') ?>">
                  <i class="menu-icon fa fa-tint"></i>

                  Thưởng phạt dầu
                </a>

                <b class="arrow"></b>
              </li>
              <li class="">
                <a data="unit" data-role="unit" href="<?php echo $this->url('unit') ?>">
                  <i class="menu-icon fa fa-info-circle"></i>

                  Đơn vị tính
                </a>

                <b class="arrow"></b>
              </li>
            </ul>
          </li>
          <li class="">
            <a data="#" href="#" class="dropdown-toggle">
              <i class="menu-icon fa fa-cogs"></i>
              <span class="menu-text">
                Hệ thống
              </span>

              <b class="arrow fa fa-angle-down"></b>
            </a>

            <b class="arrow"></b>

            <ul class="submenu">
              
              <li class="">
                <a data="info" data-role="info" href="<?php echo $this->url('info') ?>">
                  <i class="menu-icon fa fa-info-circle"></i>

                  Thông tin doanh nghiệp
                </a>

                <b class="arrow"></b>
              </li>
              <li class="">
                <a data="user" data-role="user" href="<?php echo $this->url('user') ?>">
                  <i class="menu-icon fa fa-user"></i>

                  Tài khoản
                </a>

                <b class="arrow"></b>
              </li>
              <li class="">
                <a data="permission" data-role="permission" href="<?php echo $this->url('permission') ?>">
                  <i class="menu-icon fa fa-lock"></i>

                  Phân quyền
                </a>

                <b class="arrow"></b>
              </li>
              <li class="">
                <a data="adminbackup" data-role="adminbackup" href="<?php echo $this->url('adminbackup') ?>">
                  <i class="menu-icon fa fa-refresh"></i>

                  Sao lưu & Phục hồi
                </a>

                <b class="arrow"></b>
              </li>
              <li class="">
                <a data="adminupdate" data-role="adminupdate" href="<?php echo $this->url('adminupdate') ?>">
                  <i class="menu-icon fa fa-hdd-o"></i>

                  Cập nhật phần mềm
                </a>

                <b class="arrow"></b>
              </li>
            </ul>
          </li>
          <li class="">
            <a data="support" data-role="support" href="<?php echo $this->url('support') ?>">
              <i class="menu-icon fa fa-question-circle"></i>
              <span class="menu-text"> Hỗ trợ </span>
            </a>

            <b class="arrow"></b>
          </li>
        </ul><!-- /.nav-list -->

        <div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
          <i id="sidebar-toggle-icon" class="ace-icon fa fa-angle-double-left ace-save-state" data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
        </div>
      </div>

      <div class="main-content">
        <div class="main-content-inner">
          <div class="ace-settings-container" id="ace-settings-container">
            <div class="btn btn-app btn-xs btn-warning ace-settings-btn" id="ace-settings-btn">
              <i class="ace-icon fa fa-cog bigger-130"></i>
            </div>

            <div class="ace-settings-box clearfix" id="ace-settings-box">
              <div class="pull-left width-50">
                <div class="ace-settings-item">
                  <div class="pull-left">
                    <select id="skin-colorpicker" class="hide">
                      <option data-skin="no-skin" value="#438EB9">#438EB9</option>
                      <option data-skin="skin-1" value="#222A2D">#222A2D</option>
                      <option data-skin="skin-2" value="#C6487E">#C6487E</option>
                      <option data-skin="skin-3" value="#D0D0D0">#D0D0D0</option>
                    </select>
                  </div>
                  <span>&nbsp; Choose Skin</span>
                </div>

                <div class="ace-settings-item">
                  <input type="checkbox" class="ace ace-checkbox-2 ace-save-state" id="ace-settings-navbar" autocomplete="off" />
                  <label class="lbl" for="ace-settings-navbar"> Fixed Navbar</label>
                </div>

                <div class="ace-settings-item">
                  <input type="checkbox" class="ace ace-checkbox-2 ace-save-state" id="ace-settings-sidebar" autocomplete="off" />
                  <label class="lbl" for="ace-settings-sidebar"> Fixed Sidebar</label>
                </div>

                <div class="ace-settings-item">
                  <input type="checkbox" class="ace ace-checkbox-2 ace-save-state" id="ace-settings-breadcrumbs" autocomplete="off" />
                  <label class="lbl" for="ace-settings-breadcrumbs"> Fixed Breadcrumbs</label>
                </div>

                <div class="ace-settings-item">
                  <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-rtl" autocomplete="off" />
                  <label class="lbl" for="ace-settings-rtl"> Right To Left (rtl)</label>
                </div>

                <div class="ace-settings-item">
                  <input type="checkbox" class="ace ace-checkbox-2 ace-save-state" id="ace-settings-add-container" autocomplete="off" />
                  <label class="lbl" for="ace-settings-add-container">
                    Inside
                    <b>.container</b>
                  </label>
                </div>
              </div><!-- /.pull-left -->

              <div class="pull-left width-50">
                <div class="ace-settings-item">
                  <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-hover" autocomplete="off" />
                  <label class="lbl" for="ace-settings-hover"> Submenu on Hover</label>
                </div>

                <div class="ace-settings-item">
                  <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-compact" autocomplete="off" />
                  <label class="lbl" for="ace-settings-compact"> Compact Sidebar</label>
                </div>

                <div class="ace-settings-item">
                  <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-highlight" autocomplete="off" />
                  <label class="lbl" for="ace-settings-highlight"> Alt. Active Item</label>
                </div>
              </div><!-- /.pull-left -->
            </div><!-- /.ace-settings-box -->
          </div><!-- /.ace-settings-container -->
          <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
              <li>
                <i class="ace-icon fa fa-home home-icon"></i>
                <a href="#" onclick="javascript:window.history.back();" >Trang trước</a>
              </li>
              <li class="active"><?php echo isset($title)?$title:null ?></li>
            </ul><!-- /.breadcrumb -->

            <!-- <div class="nav-search" id="nav-search">
              <form class="form-search">
                <span class="input-icon">
                  <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                  <i class="ace-icon fa fa-search nav-search-icon"></i>
                </span>
              </form>
            </div> --><!-- /.nav-search -->

          </div>

          <div class="page-content">
            

            

            <div class="row">
              <div class="col-xs-12">
                <div class="widget-box widget-color-grey" id="widget-box">
                  <div class="widget-header text-uppercase widget-header-small ">
                    <h5 class="widget-title bigger lighter">
                      <i class="ace-icon fa fa-table"></i>
                      <?php echo isset($title)?$title:null ?>
                    </h5>

                    <div class="widget-toolbar">
                      <a href="#" data-action="reload" class="green">
                        <i class="ace-icon fa fa-refresh"></i>
                      </a>
                      <a href="#" data-action="fullscreen" class="orange2">
                        <i class="ace-icon fa fa-expand"></i>
                      </a>
                      <a href="#" data-action="collapse">
                        <i class="ace-icon fa fa-chevron-up"></i>
                      </a>
                    </div>
                  </div>

                  <div class="widget-body">
                    <div class="widget-main no-padding">
                        <!-- PAGE CONTENT BEGINS -->
                        <?php echo $content; ?>
                        <!-- PAGE CONTENT ENDS -->
                    </div>
                  </div>
                </div>
              </div><!-- /.col -->
            </div><!-- /.row -->
          </div><!-- /.page-content -->
        </div>
      </div><!-- /.main-content -->

      <div class="footer">
        <div class="footer-inner">
          <div class="footer-content">
            <span class="bigger-120">
              &copy; <?php echo date('Y') ?>
              <span class="blue bolder">TMS</span>
              v.4.0 
            </span>

            &nbsp; &nbsp;
            <span class="action-buttons">
              <a href="http://www.tinhoctainha.com" target="_blank">
                <i class="ace-icon fa fa-globe light-blue bigger-150"></i>
              </a>
              <a href="https://www.facebook.com/tinhoctainha" target="_blank">
                <i class="ace-icon fa fa-facebook-square text-primary bigger-150"></i>
              </a>
              <a href="https://twitter.com/tinhoctainha" target="_blank">
                <i class="ace-icon fa fa-twitter-square light-blue bigger-150"></i>
              </a>
            </span>
          </div>
        </div>
      </div>

      <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
        <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
      </a>
    </div><!-- /.main-container -->
    <div id="ajax_loader" style="position: absolute; left: calc(50% - 80px); top: calc(50vh - 80px); z-index:999999;">
      <img src="/public/images/loader-car.gif">
    </div>
    <div id="dialog-message" class="hide"></div><!-- #dialog-message -->
    <div id="dialog-message-other" class="hide"></div><!-- #dialog-message -->
    <!-- basic scripts -->

    

    <!--[if IE]>
<script src="/public/assets/js/jquery-1.11.3.min.js"></script>
<![endif]-->
    <script type="text/javascript">
      if('ontouchstart' in document.documentElement) document.write("<script src='/public/assets/js/jquery.mobile.custom.min.js'>"+"<"+"/script>");
    </script>
    <script src="/public/assets/js/bootstrap.min.js"></script>

    <!-- page specific plugin scripts -->

    <!--[if lte IE 8]>
      <script src="/public/assets/js/excanvas.min.js"></script>
    <![endif]-->
    <script src="/public/assets/js/jquery-ui.custom.min.js"></script>
    <script src="/public/assets/js/jquery.ui.touch-punch.min.js"></script>
    <script src="/public/assets/js/bootbox.js"></script>
    <script src="/public/assets/js/jquery.easypiechart.min.js"></script>
    <script src="/public/assets/js/jquery.sparkline.index.min.js"></script>
    <script src="/public/assets/js/jquery.flot.min.js"></script>
    <script src="/public/assets/js/jquery.flot.pie.min.js"></script>
    <script src="/public/assets/js/jquery.flot.resize.min.js"></script>
    
    <script src="/public/assets/js/bootstrap-wysiwyg.min.js"></script>
    <script src="/public/assets/js/bootstrap-multiselect.min.js"></script>
    <script src="/public/assets/js/select2.min.js"></script>
    <script src="/public/assets/js/spinbox.min.js"></script>
    <script src="/public/assets/js/bootstrap-editable.min.js"></script>
    <script src="/public/assets/js/ace-editable.min.js"></script>
    <script src="/public/assets/js/jquery.maskedinput.min.js"></script>
    <script src="/public/js/jquery.inputmask.bundle.js"></script>
    <script src="/public/assets/js/bootstrap-tag.min.js"></script>

    <script src="/public/js/jquery.battatech.excelexport.js"></script>
    <script src="/public/js/export/libs/FileSaver/FileSaver.min.js"></script>
    <script src="/public/js/export/libs/js-xlsx/xlsx.core.min.js"></script>
    <script src="/public/js/export/libs/jsPDF/jspdf.min.js"></script>
    <script src="/public/js/export/libs/jsPDF-AutoTable/jspdf.plugin.autotable.js"></script>
    <script src="/public/js/export/libs/html2canvas/html2canvas.min.js"></script>
    <script src="/public/js/export/tableExport.min.js"></script>

    <!-- ace scripts -->
    <script src="/public/assets/js/ace-elements.min.js"></script>
    <script src="/public/assets/js/ace.min.js"></script>

    <script type="text/javascript">
      $('a[ data-original-title]').tooltip();
    </script>


    <script src="/public/assets/js/jquery-ui.min.js"></script>
    <script src="/public/assets/js/bootstrap-datepicker.min.js"></script>
    
    <script type="text/javascript">
      //override dialog's title function to allow for HTML titles
        $.widget("ui.dialog", $.extend({}, $.ui.dialog.prototype, {
          _title: function(title) {
            var $title = this.options.title || '&nbsp;'
            if( ("title_html" in this.options) && this.options.title_html == true )
              title.html($title);
            else title.text($title);
          }
        }));
        // jqueryui defaults
        $.extend($.ui.dialog.prototype.options, { 
            create: function() {
                var $this = $(this);

                // focus first button and bind enter to it
                $this.parent().find('.ui-dialog-buttonpane button:first').focus();
                $this.keypress(function(e) {
                    if( e.keyCode == $.ui.keyCode.ENTER ) {
                        $this.parent().find('.ui-dialog-buttonpane button:first').click();
                        return false;
                    }
                });
            } 
        });

      //editables on first profile page
        $.fn.editable.defaults.mode = 'inline';
        $.fn.editableform.loading = "<div class='editableform-loading'><i class='ace-icon fa fa-spinner fa-spin fa-2x light-blue'></i></div>";
        $.fn.editableform.buttons = '<button type="submit" class="btn btn-info editable-submit"><i class="ace-icon fa fa-check"></i></button>'+
                                      '<button type="button" class="btn editable-cancel"><i class="ace-icon fa fa-times"></i></button>'; 

      $(window).load(function() { 

        $("#ajax_loader").fadeOut(200);

        <?php if ($_SESSION["user_permission"] != '["all"]') { ?>
          var data_permission = jQuery.parseJSON('<?php echo $_SESSION["user_permission"] ?>');

          $('#sidebar a:not([data="#"])').hide();
          $.each(data_permission, function(i, item) {
              $('#sidebar a[data-role="'+data_permission[i]+'"]').show();
          });
          $('#sidebar a[data-role="admin"]').show();
          $('#sidebar a[data-role="support"]').show();
        <?php } ?>

      });

      </script>
  </body>
</html>