<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

  <title><?php echo isset($title) ? $title : null ?></title>

  <meta name="keywords" content="Logistics, Xuất Khẩu, Nhập Khẩu, Xuất Nhập Khẩu, Vận Chuyển Hàng Hóa, Vận Chuyển, Hàng Siêu Trọng, Salan, Xà Lan, Sà Lan, Vận Chuyển Sà Lan, Thủ Tục Hải Quan, Hải Quan, Thông Quan, Mở Tờ Khai, Hun Trùng, Đóng Cont, Đóng Hàng, Forwarder, Stufffing, Unstuffing, Export, Import, Terminal, Port, Sea Port, Transhit, Transhipment, OOG, Over Weight, Over Hight, Over Length, Barge, Barging, Barge team, Barge Fleet, Inland Water Way, IWW, Ship, Vessel, Canoe, River, Channal, Pilot, Boarding Agent, Đại lý tàu, Husbanding Agent, Cambudia, Barging Service, Customs, Customs transhipment, Customs Clearance, EDI, Manifest, E-Manifest, chỉnh sửa Manifest, Adjust Manifest, Inbound, Outbound, Cargo, container, 20', 40', Reefer container, Flatrach, Tank, Hàng Quá Khổ, Cấm Tải, Chất lượng,">

  <meta name="description" content="<?php echo isset($title) ? $title.' - ' : null ?>Logistics - Vận chuyển - Thủ tục hải quan - Manifest - Container">

  <meta name="generator" content="Tan Cang Mien Trung">

  <link href="<?php BASE_URL ?>/public/img/logo.png" rel="shortcut icon" type="image/vnd.microsoft.icon">

  <!-- Tell the browser to be responsive to screen width -->

  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

  <!-- Bootstrap 3.3.6 -->

  <link rel="stylesheet" href="<?php BASE_URL ?>/public/js/adminbar/bootstrap/css/bootstrap.min.css">

  <!-- Font Awesome -->

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <!-- Ionicons -->

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

  <!-- Morris chart -->

  <link rel="stylesheet" href="<?php BASE_URL ?>/public/js/adminbar/plugins/morris/morris.css">

  <!-- Theme style -->

  <link rel="stylesheet" href="<?php BASE_URL ?>/public/js/adminbar/dist/css/AdminLTE.min.css">

  <!-- AdminLTE Skins. Choose a skin from the css/skins

       folder instead of downloading all of them to reduce the load. -->

  <link rel="stylesheet" href="<?php BASE_URL ?>/public/js/adminbar/dist/css/skins/_all-skins.min.css">



  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->

  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->

  <!--[if lt IE 9]>

  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>

  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

  <![endif]-->

  <link rel="stylesheet" type="text/css" href="<?php BASE_URL ?>/public/css/style.css">

  <link rel="stylesheet" type="text/css" href="<?php BASE_URL ?>/public/js/ui/jquery-ui.css">

  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/jquery-1.7.2.min.js"></script>

  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/ui/jquery-ui.js"></script>

  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/html5.js"></script>

  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/jquery.form.js"></script>

  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/jquery.validate.min.js"></script>

  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/custom.js"></script>

  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/localization/messages_vi.js"></script>

  <script type="text/javascript" src="<?php echo BASE_URL ?>/public/js/jquery.battatech.excelexport.js"></script>

  <link rel="stylesheet" href="<?php BASE_URL ?>/public/js/chosen/chosen.css">
  <script src="<?php echo BASE_URL ?>/public/js/chosen/chosen.jquery.js" type="text/javascript"></script>

  <link rel="stylesheet" href="<?php BASE_URL ?>/public/css/component.css">
  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/jquery.stickyheader.js"></script>
  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/jquery.ba-throttle-debounce.min.js"></script>



  <link rel="stylesheet" href="<?php BASE_URL ?>/public/css/head.css">
  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/head.js"></script>
  <script type="text/javascript">
  var check_lock_user = 0;

    $.ajax({

      type: "POST",

      url: "<?php echo BASE_URL ?>/admin/checklockuser",

      data: "data=<?php echo isset($_SESSION['userid_logined'])?$_SESSION['userid_logined']:0 ?>", // or any data you want to send

      cache: false,

      success: function(html){

        check_lock_user = html;

        if (check_lock_user==1) {

          $.ajax({

            type: "GET",

            url: "<?php echo BASE_URL ?>/user/logout",

            data: "data=1", // or any data you want to send

            cache: false,

            success: function(html){

              window.location.href = "<?php echo BASE_URL ?>";

            }

          });

        };

      }

    });
    
  <?php if (isset($_SESSION['userid_logined']) && ($_SESSION['role_logined'] != 1 && $_SESSION['role_logined'] != 2) ) { ?>

      $(document).ready(function(){
          $('#doaction').attr('disabled',true);
          $('#action').attr('disabled',true);
          $('.btn-danger').each(function(){
            if ($(this).attr("onclick")) {
              $(this).hide();
            }
          });

      });
    <?php } ?>
  </script>
</head>

<body class="hold-transition skin-blue sidebar-mini">

<div class="wrapper">

  <div id="ajax_loader" style="position: fixed; left: 50%; top: 50%; margin-left : -16px; margin-top : -16px; z-index:999999;">

      <img src="<?php echo BASE_URL ?>/public/img/loader-gears.gif">

  </div>

  <header class="main-header">

    <!-- Logo -->

    <a href="<?php echo BASE_URL ?>" class="logo">

      <!-- mini logo for sidebar mini 50x50 pixels -->

      <span class="logo-mini"><b>TMS</b></span>

      <!-- logo for regular state and mobile devices -->

      <span class="logo-lg"><b>TMS</b></span>

    </a>

    <!-- Header Navbar: style can be found in header.less -->

    <nav class="navbar navbar-static-top">

      <!-- Sidebar toggle button-->

      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">

        <span class="sr-only">Toggle navigation</span>

      </a>



      <div class="navbar-custom-menu">

        

          <!-- Messages: style can be found in dropdown.less-->

          

          <!-- Notifications: style can be found in dropdown.less -->

          

          <!-- Tasks: style can be found in dropdown.less -->

          

          <!-- User Account: style can be found in dropdown.less -->

          <ul class="nav navbar-nav">

          <!-- Messages: style can be found in dropdown.less-->

          <li class="dropdown messages-menu">

            <a href="#" class="dropdown-toggle" data-toggle="dropdown">

              <i class="fa fa-envelope-o"></i>

              <span class="label label-success">4</span>

            </a>

          </li>

          <!-- Notifications: style can be found in dropdown.less -->

          <li class="dropdown notifications-menu">

            <a href="#" class="dropdown-toggle" data-toggle="dropdown">

              <i class="fa fa-bell-o"></i>

              <span class="label label-warning">10</span>

            </a>

          </li>

          <!-- Tasks: style can be found in dropdown.less -->

          <li class="dropdown tasks-menu">

            <a href="#" class="dropdown-toggle" data-toggle="dropdown">

              <i class="fa fa-flag-o"></i>

              <span class="label label-danger">9</span>

            </a>

          </li>

          <!-- User Account: style can be found in dropdown.less -->

          <li class="dropdown user user-menu">

            <!-- Kiem tra dang nhap -->

            <?php 

            if ($_SESSION) {

              ?>

              <a class="logined" href="<?php echo $this->url('user/logout') ?>">&nbsp; | Logout</a><a class="logined" href="<?php echo BASE_URL.'/user/info/'.$_SESSION['userid_logined'] ?>"><b><i><?php echo $_SESSION['user_logined']; ?> </i></b></a>

              <?php

            }

            else{

              ?>

              <a class="logined" href="<?php echo $this->url('user/login') ?>">Login</a>

              <?php

            }

            ?>

            <!-- end -->

          </li>

          <!-- Control Sidebar Toggle Button -->

        </ul>

          

          <!-- Control Sidebar Toggle Button -->

          

      </div>

    </nav>

  </header>

  <!-- Left side column. contains the logo and sidebar -->

  <aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->

    <section class="sidebar">

      <div class="user-panel">

          <button type="button" class="btn btn-block btn-primary" onClick="javascript:window.location.href='<?php echo $this->url('shipment') ?>'">

            <i class="fa  fa-pencil-square-o"></i>

          </button>

      </div>

      <!-- sidebar menu: : style can be found in sidebar.less -->

      <ul class="sidebar-menu">

        <?php if ($_SESSION) { ?>

        <li class="header">QUẢN TRỊ</li>

        <li class="treeview">

          <a data="admin" data-role="admin" href="<?php echo $this->url('admin') ?>">

            <i class="fa fa-home"></i> <span>Trang chủ</span>

          </a>

        </li>

        <li class="treeview">

          <a  data="#" href="#">

            <i class="fa fa-pie-chart"></i>

            <span>Tổng hợp - Báo cáo</span>

            <span class="pull-right-container">

              <i class="fa fa-angle-right pull-right"></i>

            </span>

          </a>

          <ul class="treeview-menu">

            <li><a data="trucking" data-role="trucking" href="<?php echo $this->url('trucking') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Phiếu vận chuyển</a></li>

            <li><a data="customership" data-role="customership" href="<?php echo $this->url('customership') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Sản lượng khách hàng</a></li>

            <li><a data="truckinglist" data-role="truckinglist" href="<?php echo $this->url('truckinglist') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Bảng kê sản lượng</a></li>

            <li><a data="#" href="#"><i class="fa fa-fw fa-caret-right text-aqua"></i>Chi phí xe</a>

              <ul class="treeview-menu">

                <li><a data="repairlist" data-role="repairlist" href="<?php echo $this->url('repairlist') ?>"><i class="fa fa-circle-o text-aqua"></i>Sửa chữa bảo dưỡng</a></li>

                <li><a data="roadcostlist" data-role="roadcostlist" href="<?php echo $this->url('roadcostlist') ?>"><i class="fa fa-circle-o text-aqua"></i>Phí sử dụng đường bộ</a></li>

                <li><a data="checkingcostlist" data-role="checkingcostlist" href="<?php echo $this->url('checkingcostlist') ?>"><i class="fa fa-circle-o text-aqua"></i>Phí kiểm định</a></li>

                <li><a data="insurancecostlist" data-role="insurancecostlist" href="<?php echo $this->url('insurancecostlist') ?>"><i class="fa fa-circle-o text-aqua"></i>Bảo hiểm</a></li>

              </ul>

            </li>

            <li><a data="oilreport" data-role="oilreport" href="<?php echo $this->url('oilreport') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Báo cáo dầu</a></li>

            <li><a data="advance" data-role="advance" href="<?php echo $this->url('advance') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Tạm ứng</a></li>

            <li><a data="commission" data-role="commission" href="<?php echo $this->url('commission') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Hoa hồng</a></li>

            <li><a data="#" href="#"><i class="fa fa-fw fa-caret-right text-aqua"></i>Doanh thu - Chi phí</a>

              <ul class="treeview-menu">

                <li><a data="quantity" data-role="quantity" href="<?php echo $this->url('quantity') ?>"><i class="fa fa-circle-o text-aqua"></i>Theo tuyến</a></li>

                <li><a data="profit" data-role="profit" href="<?php echo $this->url('profit') ?>"><i class="fa fa-circle-o text-aqua"></i>Theo vòng</a></li>

                <li><a data="round" data-role="round" href="<?php echo $this->url('round') ?>"><i class="fa fa-circle-o text-aqua"></i>Chi phí vòng</a></li>

              </ul>

            </li>

            <li><a data="officecost" data-role="officecost" href="<?php echo $this->url('officecost') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Chi phí hành chính</a></li>

            <li><a data="vehicleanalytics" data-role="vehicleanalytics" href="<?php echo $this->url('vehicleanalytics') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Quá trình hoạt động</a></li>

            <li><a data="report" data-role="report" href="<?php echo $this->url('report') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Kết quả hoạt động đội xe</a></li>

          </ul>

        </li>

        

        <li class="treeview">

          <a  data="#" href="#">

            <i class="fa fa-dollar"></i>

            <span>Kế toán</span>

            <span class="pull-right-container">

              <i class="fa fa-angle-right pull-right"></i>

            </span>

          </a>

          <ul class="treeview-menu">

            <li>

              <a data="#" href="#">

                <i class="fa fa-fw fa-money text-aqua"></i>

                <span>Tiền mặt - Tiền gửi</span>

                <span class="pull-right-container">

                  <i class="fa fa-angle-right pull-right"></i>

                </span>

              </a>

              <ul class="treeview-menu">

                <li><a data="receiptvoucher" data-role="receiptvoucher" href="<?php echo $this->url('receiptvoucher') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Thu</a></li>
                <li><a data="paymentvoucher" data-role="paymentvoucher" href="<?php echo $this->url('paymentvoucher') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Chi</a></li>
                <li><a data="internaltransfer" data-role="internaltransfer" href="<?php echo $this->url('internaltransfer') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Chuyển tiền nội bộ</a></li>
                <li><a data="bankbalance" data-role="bankbalance" href="<?php echo $this->url('bankbalance') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Số dư tài khoản</a></li>

              </ul>

            </li>

            <li>

              <a data="#" href="#">

                <i class="fa fa-fw fa-user-secret text-aqua"></i>

                <span>Công nợ</span>

                <span class="pull-right-container">

                  <i class="fa fa-angle-right pull-right"></i>

                </span>

              </a>

              <ul class="treeview-menu">

                <li>
                  <a data="receivable" data-role="receivable" href="<?php echo $this->url('receivable') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Phải thu</a>
                  <ul class="treeview-menu">
                    <li><a data="receivable" data-role="receivable" href="<?php echo $this->url('receivable') ?>"><i class="fa fa-fw fa-angle-right text-aqua"></i>Tổng hợp</a></li>
                    <li><a data="receivable/customer" data-role="receivable" href="<?php echo $this->url('receivable/customer') ?>"><i class="fa fa-fw fa-angle-right text-aqua"></i>Khách hàng</a></li>
                    <li><a data="receivable/staff" data-role="receivable" href="<?php echo $this->url('receivable/staff') ?>"><i class="fa fa-fw fa-angle-right text-aqua"></i>Nhân viên</a></li>
                    <li><a data="receivable/steersman" data-role="receivable" href="<?php echo $this->url('receivable/steersman') ?>"><i class="fa fa-fw fa-angle-right text-aqua"></i>Tài xế</a></li>
                  </ul>
                </li>
                <li>
                  <a data="payable" data-role="payable" href="<?php echo $this->url('payable') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Phải trả</a>
                  <ul class="treeview-menu">
                    <li><a data="payable" data-role="payable" href="<?php echo $this->url('payable') ?>"><i class="fa fa-fw fa-angle-right text-aqua"></i>Tổng hợp</a></li>
                    <li><a data="payable/customer" data-role="payable" href="<?php echo $this->url('payable/customer') ?>"><i class="fa fa-fw fa-angle-right text-aqua"></i>Khách hàng</a></li>
                    <li><a data="payable/staff" data-role="payable" href="<?php echo $this->url('payable/staff') ?>"><i class="fa fa-fw fa-angle-right text-aqua"></i>Nhân viên</a></li>
                    <li><a data="payable/steersman" data-role="payable" href="<?php echo $this->url('payable/steersman') ?>"><i class="fa fa-fw fa-angle-right text-aqua"></i>Tài xế</a></li>
                    <li><a data="payable/toll" data-role="payable" href="<?php echo $this->url('payable/toll') ?>"><i class="fa fa-fw fa-angle-right text-aqua"></i>Phí cầu đường</a></li>
                  </ul>
                </li>
                <li><a data="loan" data-role="loan" href="<?php echo $this->url('loan') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Chi hộ</a></li>

              </ul>

            </li>

            <li>

              <a data="#" href="#">

                <i class="fa fa-fw fa-home text-aqua"></i>

                <span>Kho</span>

                <span class="pull-right-container">

                  <i class="fa fa-angle-right pull-right"></i>

                </span>

              </a>

              <ul class="treeview-menu">

                <li><a data="importstock" data-role="importstock" href="<?php echo $this->url('importstock') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Nhập</a></li>

                <li><a data="exportstock" data-role="exportstock" href="<?php echo $this->url('exportstock') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Xuất</a></li>

                <li><a data="stock" data-role="stock" href="<?php echo $this->url('stock') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Tồn</a></li>

              </ul>

            </li>

            <li>

              <a data="#" href="#">

                <i class="fa fa-fw fa-wpforms text-aqua"></i>

                <span>Thuế</span>

                <span class="pull-right-container">

                  <i class="fa fa-angle-right pull-right"></i>

                </span>

              </a>

              <ul class="treeview-menu">

                <li><a data="vat/in" data-role="vat" href="<?php echo $this->url('vat/in') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>VAT đầu vào</a></li>

                <li><a data="vat/out" data-role="vat" href="<?php echo $this->url('vat/out') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>VAT đầu ra</a></li>

              </ul>

            </li>

            <li>

              <a data="#" href="#">

                <i class="fa fa-fw fa-truck text-aqua"></i>

                <span>Lô hàng</span>

                <span class="pull-right-container">

                  <i class="fa fa-angle-right pull-right"></i>

                </span>

              </a>

              <ul class="treeview-menu">

                <li><a data="exvat" data-role="exvat" href="<?php echo $this->url('exvat') ?>"><i class="fa fa-fw fa-calculator text-aqua"></i>Xuất hóa đơn</a></li>

                <li><a data="sales" data-role="sales" href="<?php echo $this->url('sales') ?>"><i class="fa fa-fw fa-bar-chart text-aqua"></i>Doanh thu</a></li>

                <li>

                  <a data="#" href="#">

                    <i class="fa fa-fw fa-money text-aqua"></i>

                    <span>Chi phí</span>

                    <span class="pull-right-container">

                      <i class="fa fa-angle-right pull-right"></i>

                    </span>

                  </a>

                  <ul class="treeview-menu">

                    <li><a data="cost" data-role="cost" href="<?php echo $this->url('cost') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Chi phí </a></li>

                    <li><a data="noinvoice" data-role="noinvoice" href="<?php echo $this->url('noinvoice') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Chi phí không hóa đơn</a></li>

                    <li><a data="tolls" data-role="tolls" href="<?php echo $this->url('tolls') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Phí cầu đường</a></li>

                  </ul>

                </li>

              </ul>

            </li>

            

            <li>

              <a data="#" href="#">

                <i class="fa fa-fw fa-users text-aqua"></i>

                <span>Tiền lương</span>

                <span class="pull-right-container">

                  <i class="fa fa-angle-right pull-right"></i>

                </span>

              </a>

              <ul class="treeview-menu">

                <li><a data="salary/staff" data-role="salary" href="<?php echo $this->url('salary/staff') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Lương nhân viên</a></li>

                <li><a data="salary" data-role="salary" href="<?php echo $this->url('salary') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Lương tài xế</a></li>

                <li><a data="repairsalary" data-role="repairsalary" href="<?php echo $this->url('repairsalary') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Sửa chữa bảo dưỡng</a></li>

              </ul>

            </li>

            <li><a data="costlist" data-role="costlist" href="<?php echo $this->url('costlist') ?>"><i class="fa fa-fw fa-file-text text-aqua"></i>Danh mục chi phí</a></li>

            <li><a data="bank" data-role="bank" href="<?php echo $this->url('bank') ?>"><i class="fa fa-fw fa-bank text-aqua"></i>Tài khoản TM-NH</a></li>

            <li><a data="account" data-role="account" href="<?php echo $this->url('account') ?>"><i class="fa fa-fw fa-list-ol text-aqua"></i>Tài khoản kế toán</a></li>

          </ul>

        </li>

        

        <li class="treeview">

          <a  data="#" href="#">

            <i class="fa fa-clipboard"></i>

            <span>Kinh doanh</span>

            <span class="pull-right-container">

              <i class="fa fa-angle-right pull-right"></i>

            </span>

          </a>

          <ul class="treeview-menu">

            <li><a data="marketing" data-role="marketing" href="<?php echo $this->url('marketing') ?>"><i class="fa fa-fw fa-cubes text-aqua"></i>Lô hàng</a></li>
            <li><a data="shipmentlist" data-role="shipmentlist" href="<?php echo $this->url('shipmentlist') ?>"><i class="fa fa-fw fa-file-text-o text-aqua"></i>Bảng kê</a></li>
            <li><a data="loanlist" data-role="loanlist" href="<?php echo $this->url('loanlist') ?>"><i class="fa fa-fw fa-file-text-o text-aqua"></i>Bảng kê chi hộ</a></li>
            <li><a data="sell" data-role="sell" href="<?php echo $this->url('sell') ?>"><i class="fa fa-fw fa-hdd-o text-aqua"></i>Xuất bán hàng hóa</a></li>

          </ul>

        </li>

        

        <li class="treeview">

          <a  data="#" href="#">

            <i class="fa fa-truck"></i>

            <span>Điều độ</span>

            <span class="pull-right-container">

              <i class="fa fa-angle-right pull-right"></i>

            </span>

          </a>

          <ul class="treeview-menu">

            <li><a data="shipment" data-role="shipment" href="<?php echo $this->url('shipment') ?>"><i class="fa fa-fw fa-road text-aqua"></i>Điều xe</a></li>

            <li>

              <a data="#" href="#">

                <i class="fa fa-fw fa-cubes text-aqua"></i>

                <span>Lô hàng</span>

                <span class="pull-right-container">

                  <i class="fa fa-angle-right pull-right"></i>

                </span>

              </a>

              <ul class="treeview-menu">

                <li><a data="newshipment" data-role="newshipment" href="<?php echo $this->url('newshipment') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Lô hàng mới 

                  <span class="pull-right-container">

                      <small class="label pull-right bg-green">new</small>

                    </span>

                  </a>

                </li>

                <li><a data="shipmenttemp" data-role="shipmenttemp" href="<?php echo $this->url('shipmenttemp') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Lô hàng đã nhận</a></li>

              </ul>

            </li>

            <li><a data="driver" data-role="driver" href="<?php echo $this->url('driver') ?>"><i class="fa fa-fw fa-exchange text-aqua"></i>Bàn giao xe</a></li>

            <li><a data="vehiclework" data-role="vehiclework" href="<?php echo $this->url('vehiclework') ?>"><i class="fa fa-fw fa-pause-circle-o text-aqua"></i>Tạm dừng xe</a></li>

            <li>

              <a data="#" href="#">

                <i class="fa fa-fw fa-eraser text-aqua"></i>

                <span>Mooc theo xe</span>

                <span class="pull-right-container">

                  <i class="fa fa-angle-right pull-right"></i>

                </span>

              </a>

              <ul class="treeview-menu">

                <li><a data="vehicleromooc" data-role="vehicleromooc" href="<?php echo $this->url('vehicleromooc') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Đổi mooc</a></li>

                <li><a data="vehicleromooc/vehicle" data-role="vehicleromooc" href="<?php echo $this->url('vehicleromooc/vehicle') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Danh sách mooc</a></li>

              </ul>

            </li>

            <li><a data="tollcost" data-role="tollcost" href="<?php echo $this->url('tollcost') ?>"><i class="fa fa-fw fa-file-text-o text-aqua"></i>Phiếu cầu đường</a></li>
            <li><a data="tolllist" data-role="tolllist" href="<?php echo $this->url('tolllist') ?>"><i class="fa fa-fw fa-file-text-o text-aqua"></i>Bảng kê phiếu cầu đường</a></li>
            <li><a data="roadlist" data-role="roadlist" href="<?php echo $this->url('roadlist') ?>"><i class="fa fa-fw fa-file-text-o text-aqua"></i>Bảng kê tiền đi đường</a></li>

          </ul>

        </li>

        

        <li class="treeview">

          <a  data="#" href="#">

            <i class="fa fa-gear"></i>

            <span>Vật tư</span>

            <span class="pull-right-container">

              <i class="fa fa-angle-right pull-right"></i>

            </span>

          </a>

          <ul class="treeview-menu">

            <li><a data="importstock" data-role="importstock" href="<?php echo $this->url('importstock') ?>"><i class="fa fa-fw fa-download text-aqua"></i>Nhập kho</a></li>

            <li>
              <a  data="#" href="#">
                <i class="fa fa-upload fa-fw text-aqua" ></i>
                <span>Xuất kho</span>
                <span class="pull-right-container">
                  <i class="fa fa-angle-right pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                <li><a data="exportstock/sale" data-role="exportstock" href="<?php echo $this->url('exportstock/sale') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Xuất kinh doanh</a></li>
                <li><a data="exportstock/internal" data-role="exportstock" href="<?php echo $this->url('exportstock/internal') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Xuất nội bộ</a></li>
              </ul>
            </li>

            <li><a data="house" data-role="house" href="<?php echo $this->url('house') ?>"><i class="fa fa-fw fa-home text-aqua"></i>Danh sách kho vật tư</a></li>

            <li><a data="sparepart" data-role="sparepart" href="<?php echo $this->url('sparepart') ?>"><i class="fa fa-fw fa-dropbox text-aqua"></i>Danh sách vật tư</a></li>

            <li><a data="repair" data-role="repair" href="<?php echo $this->url('repair') ?>"><i class="fa fa-fw fa-calendar-check-o text-aqua"></i>Phiếu sửa chữa bảo dưỡng</a></li>

            <li>
              <a  data="#" href="#">

                <i class="fa fa-calendar fa-fw text-aqua" ></i>

                <span>Kiểm định, bảo hiểm</span>

                <span class="pull-right-container">

                  <i class="fa fa-angle-right pull-right"></i>

                </span>

              </a>

              <ul class="treeview-menu">
                <li><a data="roadcost" data-role="roadcost" href="<?php echo $this->url('roadcost') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Phí sử dụng đường bộ</a></li>
                <li><a data="checkingcost" data-role="checkingcost" href="<?php echo $this->url('checkingcost') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Phí kiểm định</a></li>
                <li><a data="insurancecost" data-role="insurancecost" href="<?php echo $this->url('insurancecost') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Phí bảo hiểm</a></li>
              </ul>
            </li>

            <li><a data="sparevehicle" data-role="sparevehicle" href="<?php echo $this->url('sparevehicle') ?>"><i class="fa fa-fw fa-wrench text-aqua"></i>Thay thế phụ tùng</a></li>

            <li><a data="sparevehiclepass" data-role="sparevehiclepass" href="<?php echo $this->url('sparevehiclepass') ?>"><i class="fa fa-fw fa-exchange text-aqua"></i>Chuyển phụ tùng</a></li>

            <li><a data="sparevehiclelist" data-role="sparevehiclelist" href="<?php echo $this->url('sparevehiclelist') ?>"><i class="fa fa-fw fa-microchip text-aqua"></i>Phụ tùng sử dụng</a></li>

            <li><a data="sparedrap" data-role="sparedrap" href="<?php echo $this->url('sparedrap') ?>"><i class="fa fa-fw fa-plug text-aqua"></i>Vật tư thay ra</a></li>

            <li><a data="stock" data-role="stock" href="<?php echo $this->url('stock') ?>"><i class="fa fa-fw fa-database text-aqua"></i>Tồn kho</a></li>

            <li><a data="used" data-role="used" href="<?php echo $this->url('used') ?>"><i class="fa fa-fw fa-clock-o text-aqua"></i>Tình trạng sử dụng</a></li>

            <li><a data="spareparttracking" data-role="spareparttracking" href="<?php echo $this->url('spareparttracking') ?>"><i class="fa fa-fw fa-tachometer text-aqua"></i>Bảng theo dõi</a></li>

          </ul>

        </li>

        

        <li class="treeview">

          <a  data="#" href="#">

            <i class="fa fa-group"></i>

            <span>Nhân sự</span>

            <span class="pull-right-container">

              <i class="fa fa-angle-right pull-right"></i>

            </span>

          </a>

          <ul class="treeview-menu">

            <li><a data="salary" data-role="salary" href="<?php echo $this->url('salary') ?>"><i class="fa fa-fw fa-money text-aqua"></i>Lương tài xế</a></li>

            <li><a data="salarybonus" data-role="salarybonus" href="<?php echo $this->url('salarybonus') ?>"><i class="fa fa-fw fa-flask text-aqua"></i>Thưởng phạt dầu</a></li>

            <li><a data="steersman" data-role="steersman" href="<?php echo $this->url('steersman') ?>"><i class="fa fa-fw fa-user-secret text-aqua"></i>Danh sách tài xế</a></li>

            <li><a data="staff" data-role="staff" href="<?php echo $this->url('staff') ?>"><i class="fa fa-fw fa-user text-aqua"></i>Danh sách nhân viên</a></li>

            <li><a data="department" data-role="department" href="<?php echo $this->url('department') ?>"><i class="fa fa-fw fa-archive text-aqua"></i>Danh sách phòng ban</a></li>

          </ul>

        </li>

        <li class="treeview">

          <a  data="#" href="#">

            <i class="fa fa-th-list"></i>

            <span>Thông tin</span>

            <span class="pull-right-container">

              <i class="fa fa-angle-right pull-right"></i>

            </span>

          </a>

          <ul class="treeview-menu">

            <li>

              <a data="#" href="#">

                <i class="fa fa-fw fa-tasks text-aqua"></i>

                <span>Định mức</span>

                <span class="pull-right-container">

                  <i class="fa fa-angle-right pull-right"></i>

                </span>

              </a>

              <ul class="treeview-menu">

                <li><a data="oil" data-role="oil" href="<?php echo $this->url('oil') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Định mức dầu</a></li>

                <li><a data="road" data-role="road" href="<?php echo $this->url('road') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Định mức tuyến đường</a></li>

                <li><a data="warehouse" data-role="warehouse" href="<?php echo $this->url('warehouse') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Bồi dưỡng kho</a></li>

              </ul>

            </li>

            <li><a data="customer" data-role="customer" href="<?php echo $this->url('customer') ?>"><i class="fa fa-fw fa-user text-aqua"></i>Khách hàng - Đối tác</a></li>

            <li><a data="vehicle" data-role="vehicle" href="<?php echo $this->url('vehicle') ?>"><i class="fa fa-fw fa-truck text-aqua"></i>Danh sách xe</a></li>

            <li><a data="romooc" data-role="romooc" href="<?php echo $this->url('romooc') ?>"><i class="fa fa-fw fa-eraser text-aqua"></i>Danh sách mooc</a></li>

            <li><a data="place" data-role="place" href="<?php echo $this->url('place') ?>"><i class="fa fa-fw fa-home text-aqua"></i>Danh sách kho hàng</a></li>

            <li><a data="route" data-role="route" href="<?php echo $this->url('route') ?>"><i class="fa fa-fw fa-map-marker text-aqua"></i>Danh sách địa điểm</a></li>

            

            

          </ul>

        </li>

        

        <li class="treeview">

          <a  data="#" href="#">

            <i class="fa fa-cogs"></i>

            <span>Hệ thống</span>

            <span class="pull-right-container">

              <i class="fa fa-angle-right pull-right"></i>

            </span>

          </a>

          <ul class="treeview-menu">

            <li><a data="info" data-role="info" href="<?php echo $this->url('info') ?>"><i class="fa fa-fw fa-info-circle text-aqua"></i>Thông tin doanh nghiệp</a></li>

            <li><a data="user" data-role="user" href="<?php echo $this->url('user') ?>"><i class="fa fa-fw fa-user text-aqua"></i>Tài khoản</a></li>

            <li><a data="permission" data-role="permission" href="<?php echo $this->url('permission') ?>"><i class="fa fa-fw fa-lock text-aqua"></i>Phân quyền</a></li>

            <li><a data="backup" data-role="backup" href="<?php echo $this->url('backup') ?>"><i class="fa fa-fw fa-refresh text-aqua"></i>Sao lưu & Phục hồi</a></li>

            <li><a data="update" data-role="update" href="<?php echo $this->url('update') ?>"><i class="fa fa-fw fa-hdd-o text-aqua"></i>Cập nhật phần mềm</a></li>

          </ul>

        </li>

        

        

        <?php } ?>

        <li><a data="support" data-role="support" href="<?php echo $this->url('support') ?>"><i class="fa fa-question-circle"></i>Hỗ trợ</a></li>

      </ul>

    </section>

    <!-- /.sidebar -->

  </aside>



  <!-- Content Wrapper. Contains page content -->

  <div class="content-wrapper">

    <!-- Content Header (Page header) -->

    



    <!-- Main content -->

    <section class="content">

      <!-- Small boxes (Stat box) -->

      <div class="row">

        <div class="col-md-12 fixed-scrollbar">

          <?php echo $content; ?>

        </div>

        <!-- ./col --> 

      </div>

      <!-- /.row -->



    </section>

    <!-- /.content -->

    

  </div>

  <!-- /.content-wrapper -->

  <footer class="main-footer">

    <div class="pull-right hidden-xs">

      <b>Version</b> 3.0

    </div>

    <span style="font-size:5px">Powered by <a target="_blank" style="color:#fff" href="http://www.tinhoctainha.com">Dịch vụ Tin Học Tại Nhà</a></span>

  </footer>



  <!-- Control Sidebar -->

  

  <!-- /.control-sidebar -->

  <!-- Add the sidebar's background. This div must be placed

       immediately after the control sidebar -->

  <div class="control-sidebar-bg"></div>

</div>

<!-- ./wrapper -->





<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->

<script>

  $.widget.bridge('uibutton', $.ui.button);

</script>

<!-- Bootstrap 3.3.6 -->

<script src="<?php BASE_URL ?>/public/js/adminbar/bootstrap/js/bootstrap.min.js"></script>

<!-- Morris.js charts -->

<script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>

<script src="<?php BASE_URL ?>/public/js/adminbar/plugins/morris/morris.min.js"></script>

<!-- jQuery Knob Chart -->

<script src="<?php BASE_URL ?>/public/js/adminbar/plugins/knob/jquery.knob.js"></script>

<!-- daterangepicker -->

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script>

<script src="<?php BASE_URL ?>/public/js/adminbar/plugins/daterangepicker/daterangepicker.js"></script>

<!-- Bootstrap WYSIHTML5 -->

<script src="<?php BASE_URL ?>/public/js/adminbar/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>

<!-- AdminLTE App -->

<script src="<?php BASE_URL ?>/public/js/adminbar/dist/js/app.min.js"></script>

<!-- AdminLTE dashboard demo (This is only for demo purposes) -->

<!-- AdminLTE for demo purposes -->

<script src="<?php BASE_URL ?>/public/js/adminbar/dist/js/demo.js"></script>

<script type="text/javascript">

$( document ).ajaxStart(function() {

  $("#ajax_loader").fadeIn(200);

  $('input[type="submit"]').attr('disabled',true);
  $('button[type="submit"]').attr('disabled',true);

});

$( document ).ajaxComplete(function() {

  $("#ajax_loader").fadeOut(200);

  $('input[type="submit"]').attr('disabled',false);
  $('button[type="submit"]').attr('disabled',false);

});

$(window).load(function() { 

  $("#ajax_loader").fadeOut(200);

  var data_permission = jQuery.parseJSON('<?php echo isset($_SESSION["user_permission"])?$_SESSION["user_permission"]:"" ?>');

  $('.sidebar-menu a:not([data="#"])').hide();
  $.each(data_permission, function(i, item) {
      $('.sidebar-menu a[data-role="'+data_permission[i]+'"]').show();
  });
  $('.sidebar-menu a[data-role="admin"]').show();
  $('.sidebar-menu a[data-role="support"]').show();

});

</script>

</body>

</html>