<!DOCTYPE html <?php echo BASE_URL ?>/public "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title><?php echo isset($title) ? $title : "Công ty CP Tân Cảng Miền Trung" ?></title>
  <meta name="keywords" content="Logistics, Xuất Khẩu, Nhập Khẩu, Xuất Nhập Khẩu, Vận Chuyển Hàng Hóa, Vận Chuyển, Hàng Siêu Trọng, Salan, Xà Lan, Sà Lan, Vận Chuyển Sà Lan, Thủ Tục Hải Quan, Hải Quan, Thông Quan, Mở Tờ Khai, Hun Trùng, Đóng Cont, Đóng Hàng, Forwarder, Stufffing, Unstuffing, Export, Import, Terminal, Port, Sea Port, Transhit, Transhipment, OOG, Over Weight, Over Hight, Over Length, Barge, Barging, Barge team, Barge Fleet, Inland Water Way, IWW, Ship, Vessel, Canoe, River, Channal, Pilot, Boarding Agent, Đại lý tàu, Husbanding Agent, Cambudia, Barging Service, Customs, Customs transhipment, Customs Clearance, EDI, Manifest, E-Manifest, chỉnh sửa Manifest, Adjust Manifest, Inbound, Outbound, Cargo, container, 20', 40', Reefer container, Flatrach, Tank, Hàng Quá Khổ, Cấm Tải, Chất lượng,">
  <meta name="description" content="<?php echo isset($description) ? $description : 'Tân Cảng Miền Trung - Logistics, Vận chuyển đường bộ, đường biển, Thủ tục hải quan, Container, Xuất nhập khẩu tại Quy Nhơn, Bình Định' ?>">
  <meta property="og:url"           content="<?php echo "http://".$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'] ?>" />
  <meta property="og:type"          content="website" />
  <meta property="og:title"         content="<?php echo isset($title) ? $title : "Công ty CP Tân Cảng Miền Trung" ?>" />
  <meta property="og:description"   content="<?php echo isset($description) ? $description : 'Tân Cảng Miền Trung - Logistics, Vận chuyển đường bộ, đường biển, Thủ tục hải quan, Container, Xuất nhập khẩu tại Quy Nhơn, Bình Định' ?>" />
  <meta property="og:image"         content="<?php echo BASE_URL ?>/public/img/logo-tcmt.png" />
  <meta name="generator" content="Tan Cang Mien Trung">
  <meta name="alexaVerifyID" content="sxIal2YtJ9ubFCePnmLSE-La4c4"/>
  <meta http-equiv="content-language" content="vi" />
  <link rel="alternate" href="<?php echo BASE_URL ?>" hreflang="vi-vn" />
  <link href="<?php BASE_URL ?>/public/img/logo.png" rel="shortcut icon" type="image/vnd.microsoft.icon">
  <link rel="stylesheet" type="text/css" href="<?php BASE_URL ?>/public/css/style.css">
	<link rel="stylesheet" type="text/css" href="<?php BASE_URL ?>/public/css/default.css">
	<link rel="stylesheet" type="text/css" href="<?php BASE_URL ?>/public/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="<?php BASE_URL ?>/public/css/bootstrap-responsive.min.css">
  <link rel="stylesheet" type="text/css" href="<?php BASE_URL ?>/public/js/ui/jquery-ui.css">
  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/jquery-1.7.2.min.js"></script>
  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/ui/jquery-ui.js"></script>
	<script type="text/javascript" src="<?php BASE_URL ?>/public/js/html5.js"></script>
	<script type="text/javascript" src="<?php BASE_URL ?>/public/js/jquery.form.js"></script>
	<script type="text/javascript" src="<?php BASE_URL ?>/public/js/jquery.validate.min.js"></script>
	<script type="text/javascript" src="<?php BASE_URL ?>/public/js/custom.js"></script>
  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/localization/messages_vi.js"></script>
  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/bootstrap.js"></script>
  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/bootstrap.min.js"></script>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-56488212-2', 'auto');
  ga('send', 'pageview');

</script>
</head>

<body>
  <div class="Module">
      <a class="show-ctfrm" href="<?php echo $this->url('bang-gia') ?>">
          <img alt="Bảng giá dịch vụ" src="<?php echo BASE_URL ?>/public/img/baogia.png" title="Bảng giá dịch vụ" height="133px">
      </a>
  </div>
  <div  class="Module-left">
      <a class="show-ctfrm" href="<?php echo $this->url('gps') ?>">
          <img alt="Theo dõi hành trình" src="<?php echo BASE_URL ?>/public/img/hanhtrinh.png" title="Theo dõi hành trình" height="133px">
      </a>
  </div>
<!-- 
  <div id="loginBar"></div>
  <h3 id="loginBarHandle">
      <label for="LoginControl"><a href="<?php echo $this->url('bang-gia') ?>" class="concealed noOutline">Bảng giá dịch vụ</a></label>
    </h3> -->
  <div id="container">
    <header>
      <div id="ribbon">
        <div class="site-image-title">
          <h2 style="padding-top:5px">
            
            <table>
              <tbody><tr>
                <td>
                  <a href="<?php echo $this->url(""); ?>"><img src="<?php echo BASE_URL ?>/public/img/logo-tcmt.png"></a>
                </td>
                
              </tr>
            </tbody></table>
          </h2>       
        </div>
        <div class="s4-trc-container-menu">
          <span><a href="<?php echo $this->url(""); ?>" style="color:#fff">Trang chủ</a><span style="color:white">&nbsp;|&nbsp;</span>
          <a href="<?php echo $this->url(""); ?>" style="color:#fff">Sơ đồ trang</a><span style="color:white">&nbsp;|&nbsp;</span>

          
          </span>
          <?php if(!isset($_SESSION['userid_logined'])){ ?>
          <a id="ctl00_IdWelcome_ExplicitLogin" class="s4-signInLink" href="<?php echo $this->url("user/login"); ?>" style="display:inline;">Đăng nhập</a>
          <?php }else{ ?>
          <a id="ctl00_IdWelcome_ExplicitLogin" class="s4-signInLink" href="<?php echo $this->url("user/logout"); ?>" style="display:inline;">Đăng xuất</a>
          <?php } ?>
          <br>
          <div style="text-align:right; padding-top:5px">
            <table style="float:right">
              <tbody><tr>
                <td>
                  <img src="<?php echo BASE_URL ?>/public/images/flag_en.png" alt="English">
                </td>
                <td>
                  <a href="http://en.tancangmientrung.com"><span style="color:white; font-size:11px">English</span></a>
                </td>
              </tr>
            </tbody></table>
          </div>
        </div>
      </div>
      <div id="menu">
        <ul style="margin-left: -27px">

          <?php
          foreach ($menus as $menu) {
                if($menu->menu_parent == 0){
                    if ($menu->menu_id == 7) {
                      echo '<li><a href="#" title="Import - Export">Import - Export</a>
                          <ul>
                            <li><a href="'.$this->url('tapioca-chips').'" title="Tapioca Chips">Tapioca Chips</a></li>
                            <li><a href="'.$this->url('chili-powder').'" title="Chili Powder">Chili Powder</a></li>
                            <li><a href="'.$this->url('incense-powder').'" title="Incense Powder">Incense Powder</a></li>
                            <li><a href="'.$this->url('sugar').'" title="Sugar">Sugar</a></li>
                            <li><a href="'.$this->url('wood-pellets').'" title="Wood Pellets">Wood Pellets</a></li>
                          </ul>
                      </li>';
                      echo '<li><a href="'.$this->url('bang-gia').'">Bảng giá dịch vụ</a></li>';
                    }
                    echo '<li><a href="'.$this->url('page/'.$menu->permalink).'" title="'.$menu->menu_name.'">'.$menu->menu_name.'</a>';
                    echo '<ul>';
                    if($menu->menu_id != 5 && $menu->menu_id != 6){
                      foreach ($menus as $menu_child) {
                          if($menu_child->menu_parent == $menu->menu_id){
                              echo '<li><a href="'.$this->url('page/'.$menu_child->permalink).'" title="'.$menu_child->menu_name.'">'.$menu_child->menu_name.'</a></li>';
                          }
                      }
                    }
                    echo '</ul></li>';
                }
            }
          ?>
          
        </ul>
      </div>
    </header>
    <div id="wrapper">
      

      <div id="main-content">
        <?php echo $content ?>
      </div>
    </div>
  </div>
  <div style="clear:both"></div>
    <footer>
            @<?php echo date('Y') ?> -
            
                <b>CÔNG TY CỔ PHẦN TÂN CẢNG MIỀN TRUNG</b>
               &nbsp;
                Địa chỉ: Phường Hải Cảng, TP. Qui Nhơn, tỉnh Bình Định
                <br>
                Điện thoại: 056.65.56789 - 0932 6789 89 
                &nbsp;
                Email :
                <a href="mailto:biz@tancangmientrung.com" tabindex="0">
                    <span style="font-size: 11px; color:blue">biz@tancangmientrung.com</span>
                </a>
                &nbsp;
                - Skype :
                <a href="mailto:biz@tancangmientrung.com" tabindex="0">
                    <span style="font-size: 11px; color:blue">tcmt.hotline</span>
                </a>
                <br>
                <span style="font-size:5px">Powered by <a target="_blank" style="color:#fff" href="http://www.tinhoctainha.com">Dịch vụ Tin Học Tại Nhà</a></span>
    </footer>
  </div>

</body>
</html>