
<?php
$url_order = 'DESC';
if ($order_by == 'road_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'road_place_from')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'road_place_to')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'road_route_from')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'road_route_to')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'road_time')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'road_km')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'road_oil')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'road_oil_ton')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'road_bridge')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'road_police')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'road_tire')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'road_add')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'road_salary')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'road_start_date')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'road_end_date')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
$i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>
<div class="tools action-buttons pull-right">
    <?php
    if (isset($filter)) {
        echo '<a class="tooltip-warning" data-rel="tooltip" data-original-title="Dữ liệu đã được lọc bớt"><span class="green"><i class="ace-icon fa fa-filter bigger-150"></i></span></a>';
    }
    ?>
    <select name="m" id="chonloc" class="input-sm" onchange="limit_change($(this).val(),'<?php echo $order_by ?>','<?php echo $order ?>','<?php echo $keyword ?>')">
        <option value="18446744073709">All</option>
        <option value="10">10</option>
        <option value="20">20</option>
        <option value="50">50</option>
        <option value="100">100</option>
        <option value="500">500</option>
    </select>
    <a class="purpose" data-original-title="Thêm mới">
        <i class="ace-icon fa fa-plus-circle bigger-150" onclick="add_click('<?php echo $this->url("road/add") ?>','Thêm định mức tuyến đường mới')"></i>
    </a> 
    <div class="pull-right pos-rel dropdown-hover">
        <button class="btn btn-minier bigger" style="line-height: 26px">
            <i class="ace-icon fa fa-windows icon-only bigger-120"></i>
        </button>

        <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-caret dropdown-close dropdown-menu-right">
            <li>
                <a class="tooltip-warning" data-rel="tooltip" data-original-title="Tìm">
                    <span class="orange">
                        <i class="ace-icon fa fa-search bigger-150" onclick="search_click()"></i>
                    </span>
                </a>
            </li>
            <li>
                <a class="tooltip-success" data-rel="tooltip" data-original-title="Lọc">
                    <span class="green">
                        <i class="ace-icon fa fa-filter bigger-150" onclick="filter_click('<?php echo $this->url("road/filter?page=".$page."&order_by=".$order_by."&order=".$order."&limit=".$limit."&keyword=".$keyword) ?>','Lọc dữ liệu')"></i>
                    </span>
                </a>
            </li>
            <li>
                <a class="tooltip-error" data-rel="tooltip" data-original-title="Xóa">
                    <span class="red">
                        <i class="ace-icon fa fa-trash-o bigger-150" onclick="del_click()"></i>
                    </span>
                </a>
            </li>
            <li>
                <a class="tooltip-info" data-rel="tooltip" data-original-title="Nhập">
                    <span class="purple">
                        <i class="ace-icon fa fa-cloud-upload bigger-150" onclick="import_click('<?php echo $this->url("road/import") ?>','Nhập dữ liệu từ file Excel')"></i>
                    </span>
                </a>
            </li>
            <li>
                
                <div class="text-center pos-rel dropdown-hover">
                    <a class="tooltip-info" data-rel="tooltip" data-original-title="Xuất">
                        <span class="blue">
                            <i class="ace-icon fa fa-cloud-download bigger-150"></i>
                        </span>
                    </a>
                    <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-caret dropdown-close dropdown-menu-right">
                        <li>
                            <a class="tooltip-success" data-rel="tooltip" data-original-title="Excel">
                                <span class="green">
                                    <i class="ace-icon fa fa-file-excel-o bigger-130" onclick="export_click('excel','tblExport')"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a class="tooltip-error" data-rel="tooltip" data-original-title="PDF">
                                <span class="red">
                                    <i class="ace-icon fa fa-file-pdf-o bigger-130" onclick="export_click('pdf','tblExport')"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a class="tooltip-info" data-rel="tooltip" data-original-title="Word">
                                <span class="blue">
                                    <i class="ace-icon fa fa-file-word-o bigger-130" onclick="export_click('word','tblExport')"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            
        </ul>
    </div>                        
</div>
<div class="clearfix"></div>
<div id="content" style="padding:5px;">
   
<table class="table_data" id="tblExport" >
<thead>
    <tr>
    	<th><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall" class="ace ace-checkbox-2" /><span class="lbl"></span></th>
        <th><a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','road_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'road_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a></th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','road_place_from','<?php echo $url_order ?>')">Kho đi <?php if ($order_by == 'road_place_from'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','road_place_to','<?php echo $url_order ?>')">Kho đến <?php if ($order_by == 'road_place_to'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','road_route_from','<?php echo $url_order ?>')">Điểm đi <?php if ($order_by == 'road_route_from'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','road_route_to','<?php echo $url_order ?>')">Điểm đến <?php if ($order_by == 'road_route_to'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','road_km','<?php echo $url_order ?>')">Km <?php if ($order_by == 'road_km'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','road_oil','<?php echo $url_order ?>')">Lit dầu <?php if ($order_by == 'road_oil'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','road_oil_ton','<?php echo $url_order ?>')">Lit/tấn <?php if ($order_by == 'road_oil_ton'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','road_bridge','<?php echo $url_order ?>')">Cầu đường <?php if ($order_by == 'road_bridge'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','road_add','<?php echo $url_order ?>')">Đi đường <?php if ($order_by == 'road_add'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','road_salary','<?php echo $url_order ?>')">Lương chuyến <?php if ($order_by == 'road_salary'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','road_start_date','<?php echo $url_order ?>')">Ngày áp dụng <?php if ($order_by == 'road_start_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','road_end_date','<?php echo $url_order ?>')">Ngày hết hạn <?php if ($order_by == 'road_end_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
           
        <th>
            
        </th>
    </tr>
   </thead>
   <tbody>
    <?php $l=1;
        foreach ($arr as $key => $value) { ?>
        <tr style="font-weight: bold; background: #96d7f170">
            <td><a class="tr_parent" data="tr_<?php echo $l ?>" title="Ẩn/Hiện"><i class="fa fa-angle-down ace-icon bigger-150"></i></a></td>
            <td><?php echo $l++; ?></td>
            <td><a onclick="view_click('<?php echo $this->url("place/view/") ?>','Thông tin kho hàng','<?php echo $place_data['name'][$key] ?>','none')"><?php echo $key; ?></a></td>
            <td><a onclick="view_click('<?php echo $this->url("place/view/") ?>','Thông tin kho hàng','<?php echo $place_data['name'][key($value)] ?>','none')"><?php echo key($value); ?></a></td>
            <td colspan="11"></td>
        </tr>
        <?php $h=1;
            foreach ($value as $key1) { 
                foreach($key1 as $road){
                ?>
                <tr id="<?php echo $road->road_id ?>" class="edit_tr tr_<?php echo ($l-1) ?>" <?php echo ($road->road_end_date=="" || $road->road_end_date==0 || $road->road_end_date>=strtotime(date('d-m-Y')))?'style="color: #000"':'style="color:#999"' ?> >
                    <td class="text-center"><input name="check[]" type="checkbox" class="checkbox ace" value="<?php echo $road->road_id ?>"><span class="lbl"></span></td>
                    <td class="text-center"><?php echo $h++; ?></td>
                    <td></td>
                    <td></td>
                    <td><a onclick="view_click('<?php echo $this->url("route/view/") ?>','Thông tin địa điểm',<?php echo $road->road_route_from ?>,'none')"><?php echo isset($route_data[$road->road_route_from])?$route_data[$road->road_route_from]:null; ?></a></td>
                    <td><a onclick="view_click('<?php echo $this->url("route/view/") ?>','Thông tin địa điểm',<?php echo $road->road_route_to ?>,'none')"><?php echo isset($route_data[$road->road_route_to])?$route_data[$road->road_route_to]:null; ?></a></td>
                    <td class="text-right"><?php echo $lib->formatMoney($road->road_km,2); ?></td>
                    <td class="text-right"><?php echo $lib->formatMoney($road->road_oil,2); ?></td>
                    <td class="text-right"><?php echo $lib->formatMoney($road->road_oil_ton,2); ?></td>
                    <td class="text-right"><?php echo $lib->formatMoney($road->road_bridge); ?></td>
                    <td class="text-right"><?php echo $lib->formatMoney($road->road_add); ?></td>
                    <td class="text-right"><?php echo $lib->formatMoney($road->road_salary); ?></td>
                    <td><?php echo $lib->hien_thi_ngay_thang($road->road_start_date); ?></td>
                    <td><?php echo $lib->hien_thi_ngay_thang($road->road_end_date); ?></td>
                    
                    <td class="text-right">
                        <div class="tools action-buttons">
                            <a class="blue"  onclick="view_click('<?php echo $this->url("road/view/") ?>','Thông tin định mức tuyến đường',<?php echo $road->road_id ?>)">
                                <i class="ace-icon fa fa-info-circle bigger-130"></i>
                            </a>
                            <a class="green"  onclick="edit_click('<?php echo $this->url("road/edit/") ?>','Cập nhật định mức tuyến đường',<?php echo $road->road_id ?>)">
                                <i class="ace-icon fa fa-pencil bigger-130"></i>
                            </a>

                            <a class="red" >
                                <i class="ace-icon fa fa-trash-o bigger-130" onclick="del(<?php echo $road->road_id ?>)"></i>
                            </a>
                        </div>
                    </td>
                </tr>
    <?php  } } }?>
    
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>
</div>
<script type="text/javascript">
    var ch = "<?php echo $limit ?>";
$('#chonloc option[value='+ch+']').attr('selected','selected');

$('.tr_parent').on('click', function(event) {        
     $('.'+$(this).attr('data')).toggle('show');
});
</script>