
<?php
$url_order = 'ASC';
if ($order_by == 'steersman_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'steersman_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'steersman_phone')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'steersman_start_time')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'steersman_end_time')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';


    $i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>
<section class="content-header">
    <h1>DANH SÁCH TÀI XẾ</h1>
  <ol class="breadcrumb">
    <li><a href="<?php echo $this->url('admin') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><a href="<?php echo $this->url('steersman') ?>">Tài xế</a></li>
  </ol>
</section>
<div id="content" style="padding:5px;">

    <div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
        <?php if(!isset($disable_control)){ ?>
        <div class="add-box"><a class="add_button" id="btnExport" ><i class="fa fa-download"></i> Xuất</a></div>
        <div class="add-box"><a class="add_button" onClick="add_click();"><i class="fa fa-plus"></i> Thêm mới</a></div>
        <?php } ?>
    </div>
    <div class="tablenav top">
        <?php if(!isset($disable_control)){ ?>
    	<div class="alignleft actions">
			<select name="action" id="action">
            	<option value="-1" selected="selected">Chọn</option>
                
                <option value="delete">Xóa</option>
            </select>
            <input type="button" name="" id="doaction" class="button action" value="Áp dụng" onclick="action();">
		</div>
        <?php } ?>
		<div class="alignleft actions">
		<select name="m" id="chonloc">
			<option  value="18446744073709">Hiển thị tất cả</option>
			<option value="50">Hiển thị 50 giá trị</option>
            <option value="100">Hiển thị 100 giá trị</option>
            <option value="150">Hiển thị 150 giá trị</option>
            <option selected="selected" value="200">Hiển thị 200 giá trị</option>
		</select>
		<input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">						 		
        </div>

      </div>

</div>

<table class="table_data" id="tblExport">
<thead>
    <tr>
    	<th  class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','steersman_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'steersman_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','steersman_code','<?php echo $url_order ?>')">Mã NV <?php if ($order_by == 'steersman_code'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','steersman_name','<?php echo $url_order ?>')">Tên tài xế <?php if ($order_by == 'steersman_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','steersman_birth','<?php echo $url_order ?>')">Ngày sinh <?php if ($order_by == 'steersman_birth'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','steersman_cmnd','<?php echo $url_order ?>')">CMND <?php if ($order_by == 'steersman_cmnd'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','steersman_phone','<?php echo $url_order ?>')">SĐT <?php if ($order_by == 'steersman_phone'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','steersman_bank','<?php echo $url_order ?>')">TK<?php if ($order_by == 'steersman_bank'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','steersman_gplx','<?php echo $url_order ?>')">GPLX<?php if ($order_by == 'steersman_gplx'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','start_work','<?php echo $url_order ?>')">Ngày vào <?php if ($order_by == 'start_work'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','end_work','<?php echo $url_order ?>')">Ngày thôi việc <?php if ($order_by == 'end_work'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <?php if(!isset($disable_control)){ ?>
        <th  class="fix">&nbsp;</th>
        <?php } ?>
    </tr>
    
   </thead>
   <tbody>
    <?php foreach ($steersmans as $steersman) : ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $steersman->steersman_id ?>" class="edit_tr">
        	<td><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $steersman->steersman_id ?>"></td>
            <td class="fix"><?php echo $i++; ?></td>
            
            <td class="fix" id="steersman_code_<?php echo $steersman->steersman_id; ?>"><?php echo $steersman->steersman_code; ?></td>
            <td class="fix" id="steersman_name_<?php echo $steersman->steersman_id; ?>"><?php echo $steersman->steersman_name; ?></td>
            <td class="fix" id="steersman_birth_<?php echo $steersman->steersman_id; ?>"><?php echo $lib->hien_thi_ngay_thang($steersman->steersman_birth); ?></td>
            <td class="fix" id="steersman_cmnd_<?php echo $steersman->steersman_id; ?>"><?php echo $steersman->steersman_cmnd; ?></td>
            <td class="fix" id="steersman_phone_<?php echo $steersman->steersman_id; ?>"><?php echo $steersman->steersman_phone; ?></td>
            <td class="fix" id="steersman_bank_<?php echo $steersman->steersman_id; ?>"><?php echo $steersman->steersman_bank; ?></td>
            <td class="fix" id="steersman_gplx_<?php echo $steersman->steersman_id; ?>"><?php echo $steersman->steersman_gplx; ?></td>
            <td class="fix" id="steersman_start_time_<?php echo $steersman->steersman_id; ?>"><?php echo $lib->hien_thi_ngay_thang($steersman->steersman_start_time); ?></td>
            <td class="fix" id="steersman_end_time_<?php echo $steersman->steersman_id; ?>"><?php echo $steersman->steersman_end_time>0?$lib->hien_thi_ngay_thang($steersman->steersman_end_time):null; ?></td>
            <?php if(!isset($disable_control)){ ?>
            <td class="pull-right">
                <button class="btn btn-sm btn-flat btn-primary"><i class="fa fa-edit"></i> Sửa</button>
                <button class="btn btn-sm btn-flat btn-danger" onclick="del(<?php echo $steersman->steersman_id ?>)" ><i class="fa fa-remove"></i> Xóa</button>
            </td>
            <?php } ?>
        </tr>
    <?php endforeach; ?>
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>


<div class="add-field">
    <section class="content">
      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
            <!-- /.box-header -->
            <!-- form start -->
            <form id="add_steersman" role="form" method="post" action="" enctype="multipart/form-data">
              <div class="row">
                <div class="col-md-4 col-xs-6">
                  <div class="box-body">
                    <div class="form-group">
                      <label for="steersman_code">Mã NV</label>
                      <input type="text" id="steersman_code"  name="steersman_code" tabindex="1" required="required" >
                    </div>
                    <div class="form-group">
                      <label for="steersman_name">Tên tài xế</label>
                      <input type="text" id="steersman_name"  name="steersman_name" tabindex="2" required="required" >
                    </div>
                    
                    <div class="form-group">
                      <label for="steersman_birth">Ngày sinh</label>
                      <input class="ngay" type="text"   id="steersman_birth" name="steersman_birth" tabindex="3"  >
                    </div>
                    
                  </div>
                  <!-- /.box-body -->
                  
                </div>
                <div class="col-md-4 col-xs-6">
                  <div class="box-body">
                    <div class="form-group">
                      <label for="steersman_phone">SĐT</label>
                      <input type="text" class="numbers" id="steersman_phone" name="steersman_phone" tabindex="4" >
                    </div>
                    <div class="form-group">
                      <label for="steersman_cmnd">CMND</label>
                      <input type="text" class="number" id="steersman_cmnd"  name="steersman_cmnd" tabindex="5"  >
                    </div>
                    
                    <div class="form-group">
                      <label for="steersman_gplx">Số GPLX</label>
                      <input type="text" id="steersman_gplx"  name="steersman_gplx" tabindex="6"  >
                    </div>
                    
                  </div>
                  <!-- /.box-body -->
                </div>
                <div class="col-md-4 col-xs-6">
                  <div class="box-body">
                    <div class="form-group">
                      <label for="steersman_bank">Số TK</label>
                      <input type="text" id="steersman_bank"  name="steersman_bank" tabindex="7"  >
                    </div>
                    <div class="form-group">
                      <label for="steersman_start_time">Ngày vào</label>
                      <input class="ngay" type="text"   id="steersman_start_time" name="steersman_start_time" tabindex="8" required="required" >
                    </div>
                    
                    <div class="form-group">
                      <label for="steersman_end_time">Ngày thôi việc</label>
                      <input class="ngay" type="text"   id="steersman_end_time" name="steersman_end_time" tabindex="9"  >
                    </div>
                    
                  </div>
                  <!-- /.box-body -->

                </div>

              </div>
              <?php if(!isset($disable_control)){ ?>
              <div class="row">
                <div class="col-md-12">
                    <div class="box-footer">
                    <input type="hidden" readonly id="yes" name="yes" required="required" >
                    <button type="submit" class="btn btn-primary" tabindex="10">Hoàn thành</button>
                    <button type="reset" class="btn" tabindex="11">Nhập lại</button>
                  </div>
                  <div class="box-footer">
                    <div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>
                  </div>
                </div>
              </div>
              <?php } ?>
            </form>
          </div>
          <!-- /.box -->

        </div>
        <!--/.col (left) -->
        
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
       
</div>


<script type="text/javascript">
    $('.edit_tr').click(function(){
        if(!$('.checkbox').is(':checked')){
            $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);
        }
        
        var steersman_name = $(this).find("#steersman_name_"+$(this).attr('id')).text();
        var steersman_birth = $(this).find("#steersman_birth_"+$(this).attr('id')).text();
        var steersman_code = $(this).find("#steersman_code_"+$(this).attr('id')).text();
        var steersman_cmnd = $(this).find("#steersman_cmnd_"+$(this).attr('id')).text();
        var steersman_bank = $(this).find("#steersman_bank_"+$(this).attr('id')).text();
        var steersman_phone = $(this).find("#steersman_phone_"+$(this).attr('id')).text();
        var steersman_gplx = $(this).find("#steersman_gplx_"+$(this).attr('id')).text();
        var steersman_start_time = $(this).find("#steersman_start_time_"+$(this).attr('id')).text();
        var steersman_end_time = $(this).find("#steersman_end_time_"+$(this).attr('id')).text();
        //alert(steersman_from);
        $('#yes').val($(this).attr('id'));
        
        $('#steersman_birth').val(steersman_birth.replace(/\//g,"-"));
        $('#steersman_name').val(steersman_name);
        $('#steersman_bank').val(steersman_bank);
        $('#steersman_cmnd').val(steersman_cmnd);
        $('#steersman_code').val(steersman_code);
        $('#steersman_phone').val(steersman_phone);
        $('#steersman_gplx').val(steersman_gplx);
        
        $('#steersman_start_time').val(steersman_start_time.replace(/\//g,"-"));
        $('#steersman_end_time').val(steersman_end_time.replace(/\//g,"-"));
        
        $( ".add-field" ).dialog( "open" );
    });


</script>
<script type="text/javascript">

function add_click(){
    $('#yes').val("");
    $('.add-field').slideDown(500);
    $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);

        $('#steersman_name').focus();
        $('#steersman_name').val("");
        $('#steersman_phone').val(0);
        $('#steersman_code').val("");
        $('#steersman_bank').val("");
        $('#steersman_birth').val("");
        $('#steersman_cmnd').val("");
        $('#steersman_gplx').val("");
        
        $('.number').focus(function(){
            if ( $(this).val() == '0') {
               $(this).val(""); 
            };
            
        });
        $('.number').blur(function(){
            if ( $(this).val() == "") {
                $(this).val(0);
            };
            
        });

        $( ".add-field" ).dialog( "open" );
}


$(document).ready(function(){
            // Validate form
            $("#add_steersman").validate({
                errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
                rules: {
                    
                },
                submitHandler: function(form) {
                
                    
                
                    var steersman_name = $('#steersman_name').attr('value');
                    var steersman_phone = $('#steersman_phone').attr('value');
                    var steersman_start_time = $('#steersman_start_time').attr('value');
                    var steersman_end_time = $('#steersman_end_time').attr('value');
                    var steersman_code = $('#steersman_code').attr('value');
                    var steersman_bank = $('#steersman_bank').attr('value');
                    var steersman_birth = $('#steersman_birth').attr('value');
                    var steersman_cmnd = $('#steersman_cmnd').attr('value');
                    var steersman_gplx = $('#steersman_gplx').attr('value');
                    
                    var yes = $('#yes').attr('value');
                    
                    var action      = "them";
                 
                    $.ajax({
                        type: "POST", // phương thức gởi đi
                        url: "<?php echo BASE_URL ?>/steersman/add", // nơi mà dữ liệu sẽ chuyển đến khi submit
                        data: {
                            steersman_name: steersman_name,
                            steersman_phone: steersman_phone,
                            steersman_start_time: steersman_start_time,
                            steersman_end_time: steersman_end_time,
                            steersman_code: steersman_code,
                            steersman_bank: steersman_bank,
                            steersman_birth: steersman_birth,
                            steersman_cmnd: steersman_cmnd,
                            steersman_gplx: steersman_gplx,
                            yes: yes,
                            }, // giá trị post
                        success: function(answer){ // if everything goes well
                          //alert(answer);
                            $('#error').hide();
                            $('#error').slideToggle(100); // hiển thị thẻ div success
                            $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                            $('#error').fadeOut(10000);

                            if (yes != "") {
                                if (answer.trim() != "Thông tin này đã tồn tại") {
                                    setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);
                                    $('#steersman_name_'+yes).text(steersman_name);
                                    $('#steersman_phone_'+yes).text(steersman_phone);
                                    $('#vehicle_number_'+yes).text($("#vehicle :selected").text());
                                    $('#start_work_'+yes).text(start_work);
                                    $('#end_work_'+yes).text(end_work);
                                }
                                
                            }
                            else{
                                if (answer.trim() != "Thông tin này đã tồn tại") {
                                    setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);
                                    var lastID = parseInt($('#lasted').html());
                                    var rowCount = parseInt($('.table_data > tbody > tr').length);
                                    $('.table_data > tbody:last')
                                    .append(
                                        '<tr onclick="HighLightTR(this,"#4d90fe","cc3333");" id="'+parseInt(lastID+1)+'" class="edit_tr"><td><input name="check[]" type="checkbox" class="checkbox" value="'+parseInt(lastID+1)+'"></td><td class="fix">'+parseInt(rowCount+1)+'</td><td class="fix" id="steersman_name_'+parseInt(lastID+1)+'">'+steersman_name+'</td><td class="fix" id="steersman_phone_'+parseInt(lastID+1)+'">'+steersman_phone+'</td><td class="fix" id="vehicle_number_'+parseInt(lastID+1)+'">'+$("#vehicle :selected").text()+'</td><td class="fix" id="start_work_'+parseInt(lastID+1)+'">'+start_work+'</td><td class="fix" id="end_work_'+parseInt(lastID+1)+'">'+end_work+'</td><td><a class="error" href="#">Sửa</a> | <a class="error" onclick="del('+parseInt(lastID+1)+')">Xóa</a></td></tr>'
                                    );

                                    $('#lasted').html(parseInt(lastID+2));
                                }
                            }
                        }
                    });
                    return false;
                     
                 }
            });
   
   
   

   
   $('.number').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-]/g, "")
        ;
      });
    });

   $('.numbers').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9]/g, "")
          .replace(/(\d{3})(\d{3})(\d{4})/, "$1 $2 $3")
        ;
      });
    });
    

});
function get_number(id){
    return $(id).val().replace(/\,/g,'');
}

</script>


<div style="display:none" id="lasted"></div>
<script type="text/javascript">
    var count = parseInt(<?php echo $lastID ?>);
    $('#lasted').html(count);

    $("#import_excel").click(function(){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:200,
            width:500,
            resizable: false,
            title:'Import Excel',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        return false;
    });

var ch = "<?php echo $limit ?>";
$('#chonloc option[value='+ch+']').attr('selected','selected');

var pickerOpts = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+5",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#steersman_end_time" ).datepicker( "option", "minDate", selectedDate );

         },
    }; 
    $("#steersman_start_time").datepicker(pickerOpts);

    var pickerOpts2 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+5",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#steersman_start_time" ).datepicker( "option", "maxDate", selectedDate );

         },
    }; 
    $("#steersman_end_time").datepicker(pickerOpts2);


var pickerOpts3 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+5",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true
    }; 
    $("#steersman_birth").datepicker(pickerOpts3);


$( ".add-field" ).dialog({
    autoOpen: false,
    modal: true,
    width: "auto",
    title: "Thông tin tài xế",
    hide: 'fold',
    show: 'blind'
});

</script>
</div>
<style type="text/css">
    #ui-datepicker-div{
        font-size: 13px;
    }
</style>