
<div id="loading"></div>
<div id="winpopup"></div>
<section class="content-header">
    <h1>PHÂN QUYỀN HỆ THỐNG</h1>
  <ol class="breadcrumb">
    <li><a href="<?php echo $this->url('admin') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><a href="<?php echo $this->url('permission') ?>">Phân quyền</a></li>
  </ol>
</section>

<form id="add_permission" role="form" method="post" action="" enctype="multipart/form-data">
<div class="box box-primary">
  <div class="row">
    <div class="col-md-2 col-xs-6">
      <div class="box-body">
        <div class="form-group">
          <label for="role">Nhóm người dùng</label>
        </div>
      </div>
    </div>
    <div class="col-md-3 col-xs-6">
      <div class="box-body">
        <div class="form-group">
          <select id="role_name" name="role_name">
            <option>Chọn</option>
            <?php foreach ($roles as $role): ?>
            <option value="<?php echo $role->role_id ?>" ><?php echo $role->role_name ?></option>
          <?php endforeach; ?>
          </select>
        </div>
      </div>
    </div>
    <div class="col-md-2 col-xs-6">
      <div class="box-body">
        <div class="form-group">
          <label for="user">Người dùng</label>
        </div>
      </div>
    </div>
    <div class="col-md-3 col-xs-6">
      <div class="box-body">
        <div class="form-group">
          <select id="user_name" name="user_name">
          </select>
        </div>
      </div>
    </div>
    <div class="col-md-2 col-xs-6">
      <div class="box-body">
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Lưu</button>
        </div>
      </div>
    </div>
  </div>
  <table class="table_data">
    <thead>
      <tr>
        <th class="fix">Nghiệp vụ</th>
        <th class="fix">Truy cập</th>
        <th class="fix">Cập nhật</th>
      </tr>
    </thead>
    <tbody>
      <tr class="edit_tr">
        <td class="fix"><b>Thông tin</b></td>
        <td class="fix"><input type="checkbox" onclick="check_all('thongtin', this)" value=""></td>
        <td class="fix"><input type="radio" data="thongtin2" value=""></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Định mức</td>
        <td class="fix"><input type="checkbox" onclick="check_all('dinhmuc', this)" class="thongtin" value=""></td>
        <td class="fix"><input type="radio" data="dinhmuc2" class="thongtin2" value=""></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Định mức dầu</td>
        <td class="fix"><input type="checkbox" id="dmdau" value="oil" class="dinhmuc thongtin"></td>
        <td class="fix"><input type="radio" id="dmdau2" value="oil" class="dinhmuc2 thongtin2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Định mức tuyến đường</td>
        <td class="fix"><input type="checkbox" id="dmtuyenduong" value="road" class="dinhmuc thongtin"></td>
        <td class="fix"><input type="radio" id="dmtuyenduong2" value="road" class="dinhmuc2 thongtin2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Bồi dưỡng kho</td>
        <td class="fix"><input type="checkbox" id="bdkho" value="warehouse" class="dinhmuc thongtin"></td>
        <td class="fix"><input type="radio" id="bdkho2" value="warehouse" class="dinhmuc2 thongtin2"></td>
      </tr>

      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Khách hàng - Đối tác - Người thụ hưởng</td>
        <td class="fix"><input type="checkbox" id="dskhachhang" value="customer" class="thongtin"></td>
        <td class="fix"><input type="radio" id="dskhachhang2" value="customer" class="thongtin2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Danh sách xe</td>
        <td class="fix"><input type="checkbox" id="dsxe" value="vehicle" class="thongtin"></td>
        <td class="fix"><input type="radio" id="dsxe2" value="vehicle" class="thongtin2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Danh sách mooc</td>
        <td class="fix"><input type="checkbox" id="dsmooc" value="romooc" class="thongtin"></td>
        <td class="fix"><input type="radio" id="dsmooc2" value="romooc" class="thongtin2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Danh sách kho hàng</td>
        <td class="fix"><input type="checkbox" id="dskhohang" value="place" class="thongtin"></td>
        <td class="fix"><input type="radio" id="dskhohang2" value="place" class="thongtin2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Danh sách địa điểm</td>
        <td class="fix"><input type="checkbox" id="dsdiadiem" value="route" class="thongtin"></td>
        <td class="fix"><input type="radio" id="dsdiadiem2" value="route" class="thongtin2"></td>
      </tr>

      <tr class="edit_tr">
        <td class="fix"><b>Nhân sự</b></td>
        <td class="fix"><input type="checkbox" onclick="check_all('nhansu', this)" value=""></td>
        <td class="fix"><input type="radio" data="nhansu2" value=""></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Lương tài xế</td>
        <td class="fix"><input type="checkbox" id="luongtaixe" value="salary" class="nhansu"></td>
        <td class="fix"><input type="radio" id="luongtaixe2" value="salary" class="nhansu2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Thưởng phạt dầu</td>
        <td class="fix"><input type="checkbox" id="tpdau" value="salarybonus" class="nhansu"></td>
        <td class="fix"><input type="radio" id="tpdau2" value="salarybonus" class="nhansu2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Danh sách tài xế</td>
        <td class="fix"><input type="checkbox" id="dstaixe" value="steersman" class="nhansu"></td>
        <td class="fix"><input type="radio" id="dstaixe2" value="steersman" class="nhansu2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Danh sách nhân viên</td>
        <td class="fix"><input type="checkbox" id="dsnhanvien" value="staff" class="nhansu"></td>
        <td class="fix"><input type="radio" id="dsnhanvien2" value="staff" class="nhansu2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Danh sách phòng ban</td>
        <td class="fix"><input type="checkbox" id="dsphongban" value="department" class="nhansu"></td>
        <td class="fix"><input type="radio" id="dsphongban2" value="department" class="nhansu2"></td>
      </tr>

      <tr class="edit_tr">
        <td class="fix"><b>Vật tư</b></td>
        <td class="fix"><input type="checkbox" onclick="check_all('vattu', this)" value=""></td>
        <td class="fix"><input type="radio" data="vattu2" value=""></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Nhập kho</td>
        <td class="fix"><input type="checkbox" id="nhapkho" value="importstock" class="vattu"></td>
        <td class="fix"><input type="radio" id="nhapkho2" value="importstock" class="vattu2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Xuất kho</td>
        <td class="fix"><input type="checkbox" id="xuatkho" value="exportstock" class="vattu"></td>
        <td class="fix"><input type="radio" id="xuatkho2" value="exportstock" class="vattu2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Danh sách kho vật tư</td>
        <td class="fix"><input type="checkbox" id="dskhovt" value="house" class="vattu"></td>
        <td class="fix"><input type="radio" id="dskhovt2" value="house" class="vattu2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Danh sách vật tư</td>
        <td class="fix"><input type="checkbox" id="dsvattu" value="sparepart" class="vattu"></td>
        <td class="fix"><input type="radio" id="dsvattu2" value="sparepart" class="vattu2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Phiếu sử chữa bảo dưỡng</td>
        <td class="fix"><input type="checkbox" id="phieusc" value="repair" class="vattu"></td>
        <td class="fix"><input type="radio" id="phieusc2" value="repair" class="vattu2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Kiểm định, bảo hiểm</td>
        <td class="fix"><input type="checkbox" onclick="check_all('kiemdinh', this)" class="vattu" value=""></td>
        <td class="fix"><input type="radio" data="kiemdinh2" class="vattu2" value=""></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Phí sử dụng đường bộ</td>
        <td class="fix"><input type="checkbox" id="phisddb" value="roadcost" class="kiemdinh vattu"></td>
        <td class="fix"><input type="radio" id="phisddb2" value="roadcost" class="kiemdinh2 vattu2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Phí kiểm định</td>
        <td class="fix"><input type="checkbox" id="phikd" value="checkingcost" class="kiemdinh vattu"></td>
        <td class="fix"><input type="radio" id="phikd2" value="checkingcost" class="kiemdinh2 vattu2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Phí bảo hiểm</td>
        <td class="fix"><input type="checkbox" id="phibh" value="insurancecost" class="kiemdinh vattu"></td>
        <td class="fix"><input type="radio" id="phibh2" value="insurancecost" class="kiemdinh2 vattu2"></td>
      </tr>

      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Thay thế phụ tùng</td>
        <td class="fix"><input type="checkbox" id="thaythept" value="sparevehicle" class="vattu"></td>
        <td class="fix"><input type="radio" id="thaythept2" value="sparevehicle" class="vattu2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Chuyển phụ tùng</td>
        <td class="fix"><input type="checkbox" id="chuyenpt" value="sparevehiclepass" class="vattu"></td>
        <td class="fix"><input type="radio" id="chuyenpt2" value="sparevehiclepass" class="vattu2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Phụ tùng sử dụng</td>
        <td class="fix"><input type="checkbox" id="phutungsd" value="sparevehiclelist" class="vattu"></td>
        <td class="fix"><input type="radio" id="phutungsd2" value="sparevehiclelist" class="vattu2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Vật tư thay ra</td>
        <td class="fix"><input type="checkbox" id="vattuthayra" value="sparedrap" class="vattu"></td>
        <td class="fix"><input type="radio" id="vattuthayra2" value="sparedrap" class="vattu2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Tồn kho</td>
        <td class="fix"><input type="checkbox" id="tonkho" value="stock" class="vattu"></td>
        <td class="fix"><input type="radio" id="tonkho2" value="stock" class="vattu2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Tình trạng sử dụng</td>
        <td class="fix"><input type="checkbox" id="tinhtrangsd" value="used" class="vattu"></td>
        <td class="fix"><input type="radio" id="tinhtrangsd2" value="used" class="vattu2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Bảng theo dõi</td>
        <td class="fix"><input type="checkbox" id="bangtheodoi" value="spareparttracking" class="vattu"></td>
        <td class="fix"><input type="radio" id="bangtheodoi2" value="spareparttracking" class="vattu2"></td>
      </tr>

      <tr class="edit_tr">
        <td class="fix"><b>Điều độ</b></td>
        <td class="fix"><input type="checkbox" onclick="check_all('dieudo', this)" value=""></td>
        <td class="fix"><input type="radio" data="dieudo2" value=""></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Điều xe</td>
        <td class="fix"><input type="checkbox" id="dieuxe" value="shipment" class="dieudo"></td>
        <td class="fix"><input type="radio" id="dieuxe2" value="shipment" class="dieudo2"></td>
      </tr>
      
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Lô hàng</td>
        <td class="fix"><input type="checkbox" onclick="check_all('lohang', this)" class="dieudo" value=""></td>
        <td class="fix"><input type="radio" data="lohang2" class="dieudo2" value=""></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Lô hàng mới</td>
        <td class="fix"><input type="checkbox" id="lhmoi" value="newshipment" class="lohang dieudo"></td>
        <td class="fix"><input type="radio" id="lhmoi2" value="newshipment" class="lohang2 dieudo2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Lô hàng đã nhận</td>
        <td class="fix"><input type="checkbox" id="lhdanhan" value="shipmenttemp" class="lohang dieudo"></td>
        <td class="fix"><input type="radio" id="lhdanhan2" value="shipmenttemp" class="lohang2 dieudo2"></td>
      </tr>

      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Bàn giao xe</td>
        <td class="fix"><input type="checkbox" id="bangiaoxe" value="driver" class="dieudo"></td>
        <td class="fix"><input type="radio" id="bangiaoxe2" value="driver" class="dieudo2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Tạm dừng xe</td>
        <td class="fix"><input type="checkbox" id="tamdungxe" value="vehiclework" class="dieudo"></td>
        <td class="fix"><input type="radio" id="tamdungxe2" value="vehiclework" class="dieudo2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Mooc theo xe</td>
        <td class="fix"><input type="checkbox" onclick="check_all('mooc', this)" class="dieudo" value=""></td>
        <td class="fix"><input type="radio" data="mooc2" class="dieudo2" value=""></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Đổi mooc</td>
        <td class="fix"><input type="checkbox" id="doimooc" value="vehicleromooc" class="mooc dieudo"></td>
        <td class="fix"><input type="radio" id="doimooc2" value="vehicleromooc" class="mooc2 dieudo2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Danh sách mooc</td>
        <td class="fix"><input type="checkbox" id="dsdoimooc" value="vehicleromooc" class="mooc dieudo"></td>
        <td class="fix"><input type="radio" id="dsdoimooc2" value="vehicleromooc" class="mooc2 dieudo2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Phiếu cầu đường</td>
        <td class="fix"><input type="checkbox" id="phieucd" value="tollcost" class="dieudo"></td>
        <td class="fix"><input type="radio" id="phieucd2" value="tollcost" class="dieudo2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Bảng kê phiếu cầu đường</td>
        <td class="fix"><input type="checkbox" id="bkphieucd" value="tolllist" class="dieudo"></td>
        <td class="fix"><input type="radio" id="bkphieucd2" value="tolllist" class="dieudo2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Bảng kê tiền đi đường</td>
        <td class="fix"><input type="checkbox" id="bktiendiduong" value="roadlist" class="dieudo"></td>
        <td class="fix"><input type="radio" id="bktiendiduong2" value="roadlist" class="dieudo2"></td>
      </tr>
      
      <tr class="edit_tr">
        <td class="fix"><b>Kinh doanh</b></td>
        <td class="fix"><input type="checkbox" onclick="check_all('kinhdoanh', this)" value=""></td>
        <td class="fix"><input type="radio" data="kinhdoanh2" value=""></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Lô hàng</td>
        <td class="fix"><input type="checkbox" id="lohang" value="marketing" class="kinhdoanh"></td>
        <td class="fix"><input type="radio" id="lohang2" value="marketing" class="kinhdoanh2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Bảng kê</td>
        <td class="fix"><input type="checkbox" id="bangke" value="shipmentlist" class="kinhdoanh"></td>
        <td class="fix"><input type="radio" id="bangke2" value="shipmentlist" class="kinhdoanh2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Bảng kê chi hộ</td>
        <td class="fix"><input type="checkbox" id="bangke" value="loanlist" class="kinhdoanh"></td>
        <td class="fix"><input type="radio" id="bangke2" value="loanlist" class="kinhdoanh2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Xuất bán hàng hóa</td>
        <td class="fix"><input type="checkbox" id="xuatbanhh" value="sell" class="kinhdoanh"></td>
        <td class="fix"><input type="radio" id="xuatbanhh2" value="sell" class="kinhdoanh2"></td>
      </tr>

      <tr class="edit_tr">
        <td class="fix"><b>Kế toán</b></td>
        <td class="fix"><input type="checkbox" onclick="check_all('ketoan', this)" value=""></td>
        <td class="fix"><input type="radio" data="ketoan2" value=""></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Tiền mặt - Tiền gửi</td>
        <td class="fix"><input type="checkbox" onclick="check_all('tienmat', this)" class="ketoan" value=""></td>
        <td class="fix"><input type="radio" data="tienmat2" class="ketoan2" value=""></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Thu</td>
        <td class="fix"><input type="checkbox" id="thu" value="receiptvoucher" class="tienmat ketoan"></td>
        <td class="fix"><input type="radio" id="thu2" value="receiptvoucher" class="tienmat2 ketoan2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Chi</td>
        <td class="fix"><input type="checkbox" id="chi" value="paymentvoucher" class="tienmat ketoan"></td>
        <td class="fix"><input type="radio" id="chi2" value="paymentvoucher" class="tienmat2 ketoan2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Chuyển tiền nội bộ</td>
        <td class="fix"><input type="checkbox" id="chuyentien" value="internaltransfer" class="tienmat ketoan"></td>
        <td class="fix"><input type="radio" id="chuyentien2" value="internaltransfer" class="tienmat2 ketoan2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Số dư tài khoản</td>
        <td class="fix"><input type="checkbox" id="sodutk" value="bankbalance" class="tienmat ketoan"></td>
        <td class="fix"><input type="radio" id="sodutk2" value="bankbalance" class="tienmat2 ketoan2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Công nợ</td>
        <td class="fix"><input type="checkbox" onclick="check_all('congno', this)" class="ketoan" value=""></td>
        <td class="fix"><input type="radio" data="congno2" class="ketoan2" value=""></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Phải thu</td>
        <td class="fix"><input type="checkbox" id="phaithu" value="receivable" class="congno ketoan"></td>
        <td class="fix"><input type="radio" id="phaithu2" value="receivable" class="congno2 ketoan2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Phải trả</td>
        <td class="fix"><input type="checkbox" id="phaitra" value="payable" class="congno ketoan"></td>
        <td class="fix"><input type="radio" id="phaitra2" value="payable" class="congno2 ketoan2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Chi hộ</td>
        <td class="fix"><input type="checkbox" id="chiho" value="loan" class="congno ketoan"></td>
        <td class="fix"><input type="radio" id="chiho2" value="loan" class="congno2 ketoan2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Kho</td>
        <td class="fix"><input type="checkbox" onclick="check_all('kho', this)" class="ketoan" value=""></td>
        <td class="fix"><input type="radio" data="kho2" class="ketoan2" value=""></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Nhập</td>
        <td class="fix"><input type="checkbox" id="nhap" value="importstock" class="kho ketoan"></td>
        <td class="fix"><input type="radio" id="nhap2" value="importstock" class="kho2 ketoan2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Xuất</td>
        <td class="fix"><input type="checkbox" id="xuat" value="exportstock" class="kho ketoan"></td>
        <td class="fix"><input type="radio" id="xuat2" value="exportstock" class="kho2 ketoan2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Tồn</td>
        <td class="fix"><input type="checkbox" id="ton" value="stock" class="kho ketoan"></td>
        <td class="fix"><input type="radio" id="ton2" value="stock" class="kho2 ketoan2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Thuế</td>
        <td class="fix"><input type="checkbox" onclick="check_all('thue', this)" class="ketoan" value=""></td>
        <td class="fix"><input type="radio" data="thue2" class="ketoan2" value=""></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + VAT đầu vào</td>
        <td class="fix"><input type="checkbox" id="vatdauvao" value="vat" class="thue ketoan"></td>
        <td class="fix"><input type="radio" id="vatdauvao2" value="vat" class="thue2 ketoan2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + VAT đầu ra</td>
        <td class="fix"><input type="checkbox" id="vatdaura" value="vat" class="thue ketoan"></td>
        <td class="fix"><input type="radio" id="vatdaura2" value="vat" class="thue2 ketoan2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Lô hàng</td>
        <td class="fix"><input type="checkbox" onclick="check_all('ktlohang', this)" class="ketoan" value=""></td>
        <td class="fix"><input type="radio" data="ktlohang2" class="ketoan2" value=""></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Xuất hóa đơn</td>
        <td class="fix"><input type="checkbox" id="xuathd" value="exvat" class="ktlohang ketoan"></td>
        <td class="fix"><input type="radio" id="xuathd2" value="exvat" class="ktlohang2 ketoan2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Doanh thu</td>
        <td class="fix"><input type="checkbox" id="ktdoanhthu" value="sales" class="ktlohang ketoan"></td>
        <td class="fix"><input type="radio" id="ktdoanhthu2" value="sales" class="ktlohang2 ketoan2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Chi phí</td>
        <td class="fix"><input type="checkbox" onclick="check_all('ktchiphi', this)" class="ktlohang ketoan" value=""></td>
        <td class="fix"><input type="radio" data="ktchiphi2" class="ktlohang2 ketoan2" value=""></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ~ Chi phí</td>
        <td class="fix"><input type="checkbox" id="ktchiphi" value="cost" class="ktchiphi ktlohang ketoan"></td>
        <td class="fix"><input type="radio" id="ktchiphi2" value="cost" class="ktchiphi2 ktlohang2 ketoan2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ~ Chi phí không hóa đơn</td>
        <td class="fix"><input type="checkbox" id="chiphikvat" value="noinvoice" class="ktchiphi ktlohang ketoan"></td>
        <td class="fix"><input type="radio" id="chiphikvat2" value="noinvoice" class="ktchiphi2 ktlohang2 ketoan2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ~ Phí cầu đường</td>
        <td class="fix"><input type="checkbox" id="phicauduong" value="tolls" class="ktchiphi ktlohang ketoan"></td>
        <td class="fix"><input type="radio" id="phicauduong2" value="tolls" class="ktchiphi2 ktlohang2 ketoan2"></td>
      </tr>

      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Tiền lương</td>
        <td class="fix"><input type="checkbox" onclick="check_all('tienluong', this)" class="ketoan" value=""></td>
        <td class="fix"><input type="radio" data="tienluong2" class="ketoan2" value=""></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Lương nhân viên</td>
        <td class="fix"><input type="checkbox" id="ktluongnv" value="salary" class="tienluong ketoan"></td>
        <td class="fix"><input type="radio" id="ktluongnv2" value="salary" class="tienluong2 ketoan2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Lương tài xế</td>
        <td class="fix"><input type="checkbox" id="ktluongtx" value="salary" class="tienluong ketoan"></td>
        <td class="fix"><input type="radio" id="ktluongtx2" value="salary" class="tienluong2 ketoan2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Sửa chữa bảo dưỡng</td>
        <td class="fix"><input type="checkbox" id="luongsc" value="repairsalary" class="tienluong ketoan"></td>
        <td class="fix"><input type="radio" id="luongsc2" value="repairsalary" class="tienluong2 ketoan2"></td>
      </tr>

      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Danh mục chi phí</td>
        <td class="fix"><input type="checkbox" id="dmchiphi" value="costlist" class="ketoan"></td>
        <td class="fix"><input type="radio" id="dmchiphi2" value="costlist" class="ketoan2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Tài khoản TM-NH</td>
        <td class="fix"><input type="checkbox" id="tktienmat" value="bank" class="ketoan"></td>
        <td class="fix"><input type="radio" id="tktienmat2" value="bank" class="ketoan2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Tài khoản kế toán</td>
        <td class="fix"><input type="checkbox" id="tkketoan" value="account" class="ketoan"></td>
        <td class="fix"><input type="radio" id="tkketoan2" value="account" class="ketoan2"></td>
      </tr>

      <tr class="edit_tr">
        <td class="fix"><b>Báo cáo</b></td>
        <td class="fix"><input type="checkbox" onclick="check_all('baocao', this)" value=""></td>
        <td class="fix"><input type="radio" data="baocao2" value=""></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Phiếu vận chuyển</td>
        <td class="fix"><input type="checkbox" id="phieuvc" value="trucking" class="baocao"></td>
        <td class="fix"><input type="radio" id="phieuvc2" value="trucking" class="baocao2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Sản lượng khách hàng</td>
        <td class="fix"><input type="checkbox" id="slkhachhang" value="customership" class="baocao"></td>
        <td class="fix"><input type="radio" id="slkhachhang2" value="customership" class="baocao2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Bảng kê sản lượng</td>
        <td class="fix"><input type="checkbox" id="bksanluong" value="truckinglist" class="baocao"></td>
        <td class="fix"><input type="radio" id="bksanluong2" value="truckinglist" class="baocao2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Chi phí xe</td>
        <td class="fix"><input type="checkbox" onclick="check_all('chiphixe', this)" class="baocao" value=""></td>
        <td class="fix"><input type="radio" data="chiphixe2" class="baocao2" value=""></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Sửa chữa bảo dưỡng</td>
        <td class="fix"><input type="checkbox" id="cpsuachua" value="repairlist" class="chiphixe baocao"></td>
        <td class="fix"><input type="radio" id="cpsuachua2" value="repairlist" class="chiphixe2 baocao2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Phí sử dụng đường bộ</td>
        <td class="fix"><input type="checkbox" id="phisddb" value="roadcostlist" class="chiphixe baocao"></td>
        <td class="fix"><input type="radio" id="phisddb2" value="roadcostlist" class="chiphixe2 baocao2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Phí kiểm định</td>
        <td class="fix"><input type="checkbox" id="phikiemdinh" value="checkingcostlist" class="chiphixe baocao"></td>
        <td class="fix"><input type="radio" id="phikiemdinh2" value="checkingcostlist" class="chiphixe2 baocao2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Bảo hiểm</td>
        <td class="fix"><input type="checkbox" id="phibaohiem" value="insurancecostlist" class="chiphixe baocao"></td>
        <td class="fix"><input type="radio" id="phibaohiem2" value="insurancecostlist" class="chiphixe2 baocao2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Báo cáo dầu</td>
        <td class="fix"><input type="checkbox" id="bcdau" value="oilreport" class="baocao"></td>
        <td class="fix"><input type="radio" id="bcdau2" value="oilreport" class="baocao2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Tạm ứng</td>
        <td class="fix"><input type="checkbox" id="tamung" value="advance" class="baocao"></td>
        <td class="fix"><input type="radio" id="tamung2" value="advance" class="baocao2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Hoa hồng</td>
        <td class="fix"><input type="checkbox" id="hoahong" value="commission" class="baocao"></td>
        <td class="fix"><input type="radio" id="hoahong2" value="commission" class="baocao2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Doanh thu - Chi phí</td>
        <td class="fix"><input type="checkbox" onclick="check_all('doanhthuchiphi', this)" class="baocao" value=""></td>
        <td class="fix"><input type="radio" data="doanhthuchiphi2" class="baocao2" value=""></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Theo tuyến</td>
        <td class="fix"><input type="checkbox" id="theotuyen" value="quantity" class="doanhthuchiphi baocao"></td>
        <td class="fix"><input type="radio" id="theotuyen2" value="quantity" class="doanhthuchiphi2 baocao2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Theo vòng</td>
        <td class="fix"><input type="checkbox" id="theovong" value="profit" class="doanhthuchiphi baocao"></td>
        <td class="fix"><input type="radio" id="theovong2" value="profit" class="doanhthuchiphi2 baocao2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp;&nbsp;&nbsp; + Chi phí vòng</td>
        <td class="fix"><input type="checkbox" id="chiphivong" value="round" class="doanhthuchiphi baocao"></td>
        <td class="fix"><input type="radio" id="chiphivong2" value="round" class="doanhthuchiphi2 baocao2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Chi phí hành chính</td>
        <td class="fix"><input type="checkbox" id="cphanhchinh" value="officecost" class="baocao"></td>
        <td class="fix"><input type="radio" id="cphanhchinh2" value="officecost" class="baocao2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Quá trình hoạt động</td>
        <td class="fix"><input type="checkbox" id="quatrinhhd" value="vehicleanalytics" class="baocao"></td>
        <td class="fix"><input type="radio" id="quatrinhhd2" value="vehicleanalytics" class="baocao2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Kết quả hoạt động đội xe</td>
        <td class="fix"><input type="checkbox" id="kqhoatdong" value="report" class="baocao"></td>
        <td class="fix"><input type="radio" id="kqhoatdong2" value="report" class="baocao2"></td>
      </tr>

      <tr class="edit_tr">
        <td class="fix"><b>Hệ thống</b></td>
        <td class="fix"><input type="checkbox" onclick="check_all('hethong', this)" value=""></td>
        <td class="fix"><input type="radio" data="hethong2" value=""></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Thông tin doanh nghiệp</td>
        <td class="fix"><input type="checkbox" id="ttdoanhnghiep" value="info" class="hethong"></td>
        <td class="fix"><input type="radio" id="ttdoanhnghiep2" value="info" class="hethong2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Tài khoản</td>
        <td class="fix"><input type="checkbox" id="taikhoanuser" value="user" class="hethong"></td>
        <td class="fix"><input type="radio" id="taikhoanuser2" value="user" class="hethong2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Phân quyền</td>
        <td class="fix"><input type="checkbox" id="phanquyen" value="permission" class="hethong"></td>
        <td class="fix"><input type="radio" id="phanquyen2" value="permission" class="hethong2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Sao lưu & Phục hồi</td>
        <td class="fix"><input type="checkbox" id="backup" value="backup" class="hethong"></td>
        <td class="fix"><input type="radio" id="backup2" value="backup" class="hethong2"></td>
      </tr>
    </tbody>
  </table>
</div>
</form>

<script type="text/javascript">
function check_all(class_name, obj) {
    var items = document.getElementsByClassName(class_name);
    if(obj.checked == true) 
    {
      for(i=0; i < items.length ; i++)
        items[i].checked = true;
    }
    else { 
      for(i=0; i < items.length ; i++)
        items[i].checked = false;
    }
}
$("input[type='radio']").click(function()
{
  var previousValue = $(this).attr('previousValue');
  var name = $(this).attr('name');
  var items = document.getElementsByClassName($(this).attr('data'));

  if (previousValue == 'checked')
  {
    $(this).removeAttr('checked');
    $(this).attr('previousValue', false);
    for(i=0; i < items.length ; i++)
        items[i].checked = false;
  }
  else
  {
    $("input[name="+name+"]:radio").attr('previousValue', false);
    $(this).attr('previousValue', 'checked');
    for(i=0; i < items.length ; i++)
        items[i].checked = true;
  }
});


$('#role_name').change(function(){
  var val = $(this).val();

  $.ajax({

      url: '<?php echo BASE_URL ?>/permission/getrolepermission',

      type: 'POST',

      data: {data:val},

      success:function(data){
          $('input[type=checkbox]').prop('checked',false);
          if (data.trim() != "") {
            var data = jQuery.parseJSON(data);
            $.each(data, function(i, item) {
                $('input[type=checkbox][value='+data[i]+']').prop('checked',true);
            })
          }
      }

  });
  $.ajax({

      url: '<?php echo BASE_URL ?>/permission/getuser',

      type: 'POST',

      data: {data:val},

      success:function(data){
          $('#user_name').html(data);
      }

  });

  $.ajax({

      url: '<?php echo BASE_URL ?>/permission/getrolepermission2',

      type: 'POST',

      data: {data:val},

      success:function(data){
          $('input[type=radio]').prop('checked',false);
          if (data.trim() != "") {
            var data = jQuery.parseJSON(data);
            $.each(data, function(i, item) {
                $('input[type=radio][value='+data[i]+']').prop('checked',true);
                $('input[type=radio][value='+data[i]+']').attr('previousValue','checked');
            })
          }
      }

  });
});

$('#user_name').change(function(){
  var val = $(this).val();
  $.ajax({

      url: '<?php echo BASE_URL ?>/permission/getpermission',

      type: 'POST',

      data: {data:val},

      success:function(data){
        $('input[type=checkbox]').prop('checked',false);
        if (data.trim() != "") {
          var data = jQuery.parseJSON(data);
          $.each(data, function(i, item) {
              $('input[type=checkbox][value='+data[i]+']').prop('checked',true);
          })
        }
          
      }

  });

  $.ajax({

      url: '<?php echo BASE_URL ?>/permission/getpermission2',

      type: 'POST',

      data: {data:val},

      success:function(data){
        $('input[type=radio]').prop('checked',false);
        if (data.trim() != "") {
          var data = jQuery.parseJSON(data);
          $.each(data, function(i, item) {
              $('input[type=radio][value='+data[i]+']').prop('checked',true);
              $('input[type=radio][value='+data[i]+']').attr('previousValue','checked');
          })
        }
          
      }

  });
});

$("#add_permission").validate({
  errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
  rules: {
      
  },
  submitHandler: function(form) {
    var role = $('#role_name').val();
    var user = $('#user_name').val();
    var str = [];
    var act = {};

    $('input[type=checkbox]').each(function() { 
        if($(this).is(':checked')){
          var val = $(this).val();
          if ($(this).val() != "") {
            str.push(val);

            if($('input[type=radio][value='+val+']').is(':checked')){
              act[val] = val;
            }
            
          }
        }
    });
    if(role>0){
      $.ajax({
        type: "POST", // phương thức gởi đi
        url: "<?php echo BASE_URL ?>/permission/setpermission", // nơi mà dữ liệu sẽ chuyển đến khi submit
        data: {
            data: str,
            act: act,
            user: user,
            role: role,
            }, // giá trị post
        success: function(answer){ // if everything goes well
            alert(answer);
            
        }
      });
    }
    return false;
  }
});
</script>