<script type="text/javascript">
$(document).ready(function(){
	$.mask.definitions['~'] = '([0-9] )?';
  $('#staff_cmnd').mask('999999999');
  $("#staff_phone").mask("9999 999 999~");
  $( ".select2" ).select2();

			// Validate form
			$("#edit").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
				rules: {
				},
        submitHandler: function(form) {
                
          var formData = new FormData($("#edit")[0]);
          formData.append('staff_id', '<?php echo $staff_data->staff_id ?>');
          
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/staff/editstaff", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: formData, // giá trị post
              cache: false,
              contentType: false,
              processData: false,
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error').hide();
                  $('#error').slideToggle(100); // hiển thị thẻ div success
                  $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error').fadeOut(10000);

              }
          });
          return false;
           
       }
					 
				 
			});
	
});
</script>

<div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>
<div class="login_body">
 
  <form id="edit" method="post" action="">
      <div class="col-md-3 col-xs-6">
        <label for="staff_code">Mã nhân viên</label>
        <div class="input-group">
          <input class="form-control" type="text" id="staff_code" name="staff_code" required="required" tabindex="1" value="<?php echo $staff_data->staff_code ?>">
        </div>
        <label for="staff_name">Tên nhân viên</label>
        <div class="input-group">
          <input class="form-control" type="text" id="staff_name" name="staff_name" required="required" tabindex="2" value="<?php echo $staff_data->staff_name ?>">
        </div>
        <label for="staff_birthday">Ngày sinh</label>
        <div class="input-group">
          <input class="form-control input-mask-date" type="text" id="staff_birthday" name="staff_birthday" required="required" tabindex="3" value="<?php echo $lib->hien_thi_ngay_thang($staff_data->staff_birthday) ?>">
        </div>
        <label for="staff_code">Giới tính</label>
        <div class="input-group">
          <label>
            <input class="form-control ace" type="radio" name="staff_gender" tabindex="4" value="0" <?php echo $staff_data->staff_gender==0?'checked="checked"':null ?>> <span class="lbl">Nam</span>
          </label>
          &nbsp;
          <label>
            <input class="form-control ace" type="radio" name="staff_gender" tabindex="5" value="1" <?php echo $staff_data->staff_gender==1?'checked="checked"':null ?>> <span class="lbl">Nữ</span>
          </label>
          
        </div>
     </div>
     <div class="col-md-3 col-xs-6">
        <label for="staff_cmnd">Số CMND</label>
        <div class="input-group">
          <input class="form-control" type="text" id="staff_cmnd" name="staff_cmnd" required="required" tabindex="6" value="<?php echo $staff_data->staff_cmnd ?>">
        </div>
        <label for="staff_gplx">Số GPLX</label>
        <div class="input-group">
          <input class="form-control" type="text" id="staff_gplx" name="staff_gplx" tabindex="7" value="<?php echo $staff_data->staff_gplx ?>">
        </div>
        <label for="staff_address">Địa chỉ</label>
        <div class="input-group">
          <input class="form-control" type="text" id="staff_address" name="staff_address" required="required" tabindex="8" value="<?php echo $staff_data->staff_address ?>">
        </div>
        <label for="staff_position">Chức vụ</label>
        <div class="input-group">
          <select class="form-control select2" id="staff_position" name="staff_position" required="required" tabindex="9">
            <?php foreach ($positions as $position) { ?>
              <option value="<?php echo $position->position_id ?>" <?php echo $staff_data->staff_position==$position->position_id?'selected="selected"':null ?> ><?php echo $position->position_name ?></option>
            <?php } ?>
          </select>
        </div>
     </div>
     <div class="col-md-3 col-xs-6">
        <label for="staff_phone">Số điện thoại</label>
        <div class="input-group">
          <input class="form-control" type="text" id="staff_phone" name="staff_phone" required="required" tabindex="10" value="<?php echo $staff_data->staff_phone ?>_">
        </div>
        <label for="staff_email">Email</label>
        <div class="input-group">
          <input class="form-control" type="email" id="staff_email" name="staff_email" tabindex="11" value="<?php echo $staff_data->staff_email ?>">
        </div>
        <label for="staff_bank_account">Số tài khoản</label>
        <div class="input-group input-daterange">
          <input class="form-control input-sm" type="text" id="staff_bank_account" name="staff_bank_account" tabindex="12" value="<?php echo $staff_data->staff_bank_account ?>">
          <span class="input-group-addon">
            <i class="fa fa-bank"></i>
          </span>
          <input class="form-control input-sm" type="text" id="staff_bank" name="staff_bank" tabindex="13" value="<?php echo $staff_data->staff_bank ?>">
        </div>
        <label for="staff_department">Phòng</label>
        <div class="input-group">
          <select class="form-control select2" id="staff_department" name="staff_department" required="required" tabindex="14">
            <?php foreach ($departments as $department) { ?>
              <option value="<?php echo $department->department_id ?>" <?php echo $staff_data->staff_department==$department->department_id?'selected="selected"':null ?> ><?php echo $department->department_name ?></option>
            <?php } ?>
          </select>
        </div>
     </div>
     <div class="col-md-3 col-xs-6">
        <label for="staff_start_date">Ngày vào làm việc</label>
        <div class="input-group">
          <input class="form-control input-mask-date" type="text" id="staff_start_date" name="staff_start_date" required="required" tabindex="15" value="<?php echo $lib->hien_thi_ngay_thang($staff_data->staff_start_date) ?>">
        </div>
        <label for="staff_end_date">Ngày thôi việc</label>
        <div class="input-group">
          <input class="form-control input-mask-date" type="text" id="staff_end_date" name="staff_end_date" tabindex="16" value="<?php echo $lib->hien_thi_ngay_thang($staff_data->staff_end_date) ?>">
        </div>
        <label for="staff_account">Tên truy cập</label>
        <div class="input-group">
          <select class="form-control select2" id="staff_account" name="staff_account" tabindex="17">
            <option value="0">Không sử dụng</option>
            <?php foreach ($accounts as $account) { ?>
              <option value="<?php echo $account->user_id ?>" <?php echo $staff_data->staff_account==$account->user_id?'selected="selected"':null ?> ><?php echo $account->username ?></option>
            <?php } ?>
          </select>
        </div>
     </div>
  </form>
</div>



