<div id="loading"></div>
<div id="winpopup"></div>
<section class="content-header">
    <h1>BÁO CÁO DẦU</h1>
  <ol class="breadcrumb">
    <li><a href="<?php echo $this->url('admin') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><a href="<?php echo $this->url('oilreport') ?>">Dầu</a></li>
  </ol>
</section>

<div id="content" style="padding:5px;">
<form id="report" name="report" action method="post">
<div class="search-box">
    
    
    <select id="sl_round" name="sl_round" style="width:90px; margin-left:5px;">
     <?php 
        for ($i=1; $i < 13; $i++) { 
            echo '<option value="'.$i.'">Tháng '.$i.'</option>';
        }
     ?>
    </select>
    <select id="sl_trangthai" name="sl_trangthai" style="width:100px">
     <?php 
        $nam = date('Y');
        for ($i=($nam-5); $i < ($nam+5); $i++) { 
            echo '<option value="'.$i.'">Năm '.$i.'</option>';
        }
     ?>
    </select>
    <input type="submit" name="submit" id="xem" value="Xem">  
    
</div>
<div >
    
    Từ  <input style="width:100px" type="search" name="batdau" id="batdau" placeholder="Chọn ngày" <?php if(isset($batdau)) echo "value='$batdau'"; ?> >  
    Đến  <input style="width:100px" type="search" name="ketthuc" id="ketthuc" placeholder="Chọn ngày" <?php if(isset($ketthuc)) echo "value='$ketthuc'"; ?> >  
     <input type="submit" name="submit" id="xem" value="Xem">  
                            
</div>

<div >
    <select id="loc" name="loc" style="width: 139px">
        <option value="0">Địa điểm</option>
        <option value="1"> Bãi </option>
        <option value="5"> Dọc đường </option>
    </select>
    <select id="vehicle" name="vehicle" style="width: 139px">
        <option value="0">Xe</option>
        <?php foreach ($list_vehicle as $x): ?>
        <option value="<?php echo $x->vehicle_id ?>"><?php echo $x->vehicle_number ?></option>
        <?php endforeach; ?>
    </select>
     <input type="submit" name="submit" id="xem" value="Xem">  
     
     <div class="add-box">
        <a class="add_button" id="export_excel" href="<?php echo BASE_URL.'/oilreport/export/'.strtotime($batdau).'/'.strtotime($ketthuc).'/'.$xe.'/'.$loc ?>" ><i class="fa fa-download"></i> Xuất</a>
    </div>
                        
</div>
</form> 


<?php 

$dau = array();
$cong = 0;
$tiendau = array();
$tongtien = 0;

?>


<div class="report">
    <div class="report-left">
        <table class="table_data">
            <thead class="fixed-top">
                <tr>
                    <th class="fix">Ngày</th>
                </tr>
           </thead>
           <tbody>
                <?php foreach ($shipments as $shipment): ?>
                <tr style=" color:rgb(0, 32, 96); font-weight:bold;">
                    
                    <td class="fix"><?php echo $lib->hien_thi_ngay_thang($shipment->shipment_date); ?></td>
                    
                </tr>
                <?php endforeach; ?>
                <tr style=" color:rgb(211, 11, 57); text-align: center; font-weight:bold;">
                    <td class="fix">Tổng dầu</td>
                </tr>
                <tr style=" color:rgb(0, 123, 25); text-align: center; font-weight:bold;">
                    <td class="fix">Thành tiền</td>
                </tr>
           </tbody>
        </table>
    </div>
    <div class="report-right">
    <div class="report-right report-right-fix" style="float:left">
        <table class="table_data">
            <thead class="fixed-top">
                <tr>
                    <td></td>
                    <?php foreach ($vehicles as $vehicle): ?>
                    <th class="fix"><?php echo $vehicle->vehicle_number ?></th>
                    <?php endforeach; ?>
                </tr>
           </thead>
           <tbody>
                <?php foreach ($shipments as $shipment): ?> 
                <tr style=" color:rgb(0, 32, 96); font-weight:bold;">
                    <td></td>
                    <?php foreach ($vehicles as $vehicle): 
                    $dau[$vehicle->vehicle_id] = isset($dau[$vehicle->vehicle_id])?$dau[$vehicle->vehicle_id]+(isset($oil_data[$vehicle->vehicle_id][$shipment->shipment_date])?$oil_data[$vehicle->vehicle_id][$shipment->shipment_date]:0):0+(isset($oil_data[$vehicle->vehicle_id][$shipment->shipment_date])?$oil_data[$vehicle->vehicle_id][$shipment->shipment_date]:0) ;
                    $tiendau[$vehicle->vehicle_id] = isset($tiendau[$vehicle->vehicle_id])?($tiendau[$vehicle->vehicle_id] + ( isset($oil_data[$vehicle->vehicle_id][$shipment->shipment_date])?$oil_data[$vehicle->vehicle_id][$shipment->shipment_date]:0) * round($shipment->oil_cost*1.1)) : (0 + ( isset($oil_data[$vehicle->vehicle_id][$shipment->shipment_date])?$oil_data[$vehicle->vehicle_id][$shipment->shipment_date]:0) * round($shipment->oil_cost*1.1)) ;
                    ?>
                    <td class="fix masterTooltip" title="<?php echo $vehicle->vehicle_number ?>"><?php echo isset($oil_data[$vehicle->vehicle_id][$shipment->shipment_date])?$lib->formatMoney($oil_data[$vehicle->vehicle_id][$shipment->shipment_date]):0 ?></td>
                    <?php endforeach; ?>
                </tr>
                <?php endforeach; ?>
                <tr style=" color:rgb(211, 11, 57); font-style: italic; font-weight:bold;">
                    <td></td>
                    <?php foreach ($vehicles as $vehicle):  ?>
                    <td class="fix masterTooltip" title="<?php echo $vehicle->vehicle_number ?>" ><?php echo $lib->formatMoney(isset($dau[$vehicle->vehicle_id])?$dau[$vehicle->vehicle_id]:0) ?></td>
                    <?php endforeach; ?>
                </tr>
                <tr style=" color:rgb(0, 123, 25);  font-weight:bold;">
                    <td></td>
                    <?php foreach ($vehicles as $vehicle):  $tongtien += isset($tiendau[$vehicle->vehicle_id])?$tiendau[$vehicle->vehicle_id]:0; ?>
                    <td class="fix masterTooltip" title="<?php echo $vehicle->vehicle_number ?>"><?php echo $lib->formatMoney(isset($tiendau[$vehicle->vehicle_id])?$tiendau[$vehicle->vehicle_id]:0) ?></td>
                    <?php endforeach; ?>
                </tr>
                <tr>
                    <td></td>
                    <?php foreach ($vehicles as $vehicle): ?>
                    <td >
                        <?php if(!isset($disable_control)){ ?>
                        <a id="oil_<?php echo $vehicle->vehicle_id ?>" class="oil add_button approve_oil" data="<?php echo strtotime($batdau) ?>" alt="<?php echo strtotime($ketthuc) ?>" tabindex="<?php echo $vehicle->vehicle_id ?>" title="<?php echo $loc ?>" data-value="<?php echo isset($check_lock[$vehicle->vehicle_id])?$check_lock[$vehicle->vehicle_id]:1 ?>" ><?php if(isset($check_lock[$vehicle->vehicle_id]) && $check_lock[$vehicle->vehicle_id]==0){ echo "Kí duyệt"; }else{ echo "Mở"; } ?></a>
                        <?php } ?>
                    </td>
                    <?php endforeach; ?>
                </tr>
                
           </tbody>
        </table>
    </div>

    <div id="divRight" style="width:200px; float:right; ">
        <table class="table_data">
            <thead>
                <tr>
                    <th class="fix">Cộng</th>
                    <th class="fix">Giá dầu</th>
                    
                </tr>
           </thead>
           <tbody>
                <?php foreach ($shipments as $shipment): $tongdau = 0; ?> 
                <?php foreach ($vehicles as $vehicle): $tongdau += isset($oil_data[$vehicle->vehicle_id][$shipment->shipment_date])?$oil_data[$vehicle->vehicle_id][$shipment->shipment_date]:0; 
                    
                ?>
                    <?php endforeach; ?>

                    <?php $cong += $tongdau; ?>
                <tr style=" color:rgb(0, 32, 96); font-weight:bold;">
                    <td class="fix warning"  ><?php echo $lib->formatMoney($tongdau) ?></td>
                    <td class="fix"><?php echo $lib->formatMoney(round($shipment->oil_cost*1.1)) ?></td>
                    
                </tr>
                <?php endforeach; ?>

                <tr style="font-style: italic; font-weight:bold;">
                    <td class="fix warning"><?php echo $lib->formatMoney($cong) ?></td>
                    <td class="fix"></td>
                </tr>
                <tr style="color:rgb(0, 123, 25); font-weight:bold;">
                    <td colspan="2" class="fix"><?php echo $lib->formatMoney($tongtien).' VNĐ' ?></td>
                    
                </tr>
                <tr>
                    <td colspan="2" class="fix ">
                        <?php if(!isset($disable_control)){ ?>
                        <a class="oil_all add_button approve_oil" data="<?php echo strtotime($batdau) ?>" alt="<?php echo strtotime($ketthuc) ?>" tabindex="0" title="<?php echo $loc ?>" data-value="<?php echo isset($check_lock_all[$batdau.$ketthuc])?$check_lock_all[$batdau.$ketthuc]:1 ?>" ><?php if(isset($check_lock_all[$batdau.$ketthuc]) && $check_lock_all[$batdau.$ketthuc]==0){ echo "Kí duyệt tất cả"; }else{ echo "Mở tất cả"; } ?></a>
                        <?php } ?>
                    </td>
                </tr>
           </tbody>
        </table>
    </div>
</div>
</div>

<script type="text/javascript">
    $(function() {

        var w = $(".report").width();

      $(".report-right-fix").width(w-380);


    var pickerOpts = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#ketthuc" ).datepicker( "option", "minDate", selectedDate );

         },
         
    };  
    $("#batdau").datepicker(pickerOpts);

    var pickerOpts4 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#batdau" ).datepicker( "option", "maxDate", selectedDate );
                
         },
         
    };  
    $("#ketthuc").datepicker(pickerOpts4);
              
            
    
});



</script>
<style type="text/css">
    #ui-datepicker-div{
        font-size: 13px;
    }
    .table_data tbody tr td.fix{
        min-width: 130px;
    }
.table_data tbody tr td.fix:nth-child(1){
        min-width: 30px;
    }
.report{
    width: 100%;
    margin: -5px auto;
}
.report-left{
    float: left;
    width: 150px;
}
.report-right{
    
    overflow: auto;
}
.showtooltip {
        display:none;
        position:absolute;
        border:1px solid #333;
        background-color:#161616;
        border-radius:5px;
        padding:10px;
        color:#fff;
        font-size:12px Arial;
    }
</style>
<script type="text/javascript">
$(document).ready(function() {
// Tooltip only Text
$('.masterTooltip').hover(function(){
        // Hover over code
        var title = $(this).attr('title');
        $(this).data('tipText', title).removeAttr('title');
        $('<p class="showtooltip"></p>')
        .text(title)
        .appendTo('body')
        .fadeIn('slow');
}, function() {
        // Hover out code
        $(this).attr('title', $(this).data('tipText'));
        $('.showtooltip').remove();
}).mousemove(function(e) {
        var mousex = e.pageX + 20; //Get X coordinates
        var mousey = e.pageY + 10; //Get Y coordinates
        $('.showtooltip')
        .css({ top: mousey, left: mousex })
});


});

var w = $("#container").width();

      $(".container").width(w);
      $(".navbar-inner").width(w);
      $(".navbar").width(w);

$(document).ready(function() {
    function fixDiv() {
      
      var $cache = $('.navbar-fixed-top'); 
      if ($(window).scrollTop() > 42) {
        $cache.css({'position': 'fixed', 'top': '0'}); 
        $(".navbar-inner").css({'width':'100%'});
        $(".navbar").css({'width':'100%'});
      }
      else{
        var w = $("#container").width();
        $cache.css({'position': 'relative', 'top': 'auto'});
        $(".navbar-inner").width(w);
        $(".navbar").width(w);
      }
      
    }
  $(window).scroll(fixDiv);
  fixDiv();


});

var x = "<?php echo $xe ?>";
$('#vehicle option[value='+x+']').attr('selected','selected');

var tt = "<?php echo $loc ?>";
$('#loc option[value='+tt+']').attr('selected','selected');

var v = "<?php echo $vong ?>";
$('#sl_round option[value='+v+']').attr('selected','selected');

var tt = "<?php echo $trangthai ?>";
$('#sl_trangthai option[value='+tt+']').attr('selected','selected');

</script>
</div>

<script type="text/javascript">
    
    $('#sl_round').change(function(){
        var m = $(this).val();
        var y = $('#sl_trangthai').val();
        var firstDay = new Date(y, m-1, 1);
        var lastDay = new Date(y, m, 0);

        $('#batdau').datepicker("setDate", firstDay );
        $('#ketthuc').datepicker("setDate", lastDay );

    });

    $('#sl_trangthai').change(function(){
        var y = $(this).val();
        var m = $('#sl_round').val();
        var firstDay = new Date(y, m-1, 1);
        var lastDay = new Date(y, m, 0);

        $('#batdau').datepicker("setDate", firstDay );
        $('#ketthuc').datepicker("setDate", lastDay );

    });

$('.approve_oil').click(function(){
    var batdau = $(this).attr("data");
    var ketthuc = $(this).attr("alt");
    var xe = $(this).attr("tabindex");
    var diadiem = $(this).attr("title");
    var value = $(this).attr("data-value");
    var r = confirm("Bạn có chắc chắn không?");
      if (r == true){
        if (xe==0) {
                    if (value==1) {
                        $('.oil').text('Kí duyệt');
                        $('.oil').attr('data-value',0);
                        $('.oil_all').text('Kí duyệt tất cả');
                        $('.oil_all').attr('data-value',0);
                    }
                    else{
                        $('.oil').text('Mở');
                        $('.oil').attr('data-value',1);
                        $('.oil_all').text('Mở tất cả');
                        $('.oil_all').attr('data-value',1);
                    }
                }
                else{
                    if (value==1) {
                        $('#oil_'+xe).text('Kí duyệt');
                        $('#oil_'+xe).attr('data-value',0);
                        $('.oil_all').text('Kí duyệt tất cả');
                        $('.oil_all').attr('data-value',0);
                    }
                    else{
                        $('#oil_'+xe).text('Mở');
                        $('#oil_'+xe).attr('data-value',1);
                        $('.oil_all').text('Mở tất cả');
                        $('.oil_all').attr('data-value',1);
                    }
                }
                
        $.post("<?php echo BASE_URL ?>/oilreport/approve", {batdau: batdau,ketthuc: ketthuc,xe: xe,diadiem: diadiem,value: value},
           function(data){
                //alert(data);

           }); 
      }

});

</script>