<script type="text/javascript">
$(document).ready(function(){
	
			// Validate form
			$("#edit_romooc").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
				rules: {
				},
        submitHandler: function(form) {
          
          var formData = new FormData($("#edit_romooc")[0]);
          formData.append('romooc_id', '<?php echo $romooc_data->romooc_id ?>');
          
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/romooc/editromooc", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: formData, // giá trị post
              cache: false,
              contentType: false,
              processData: false,
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error_romooc').hide();
                  $('#error_romooc').slideToggle(100); // hiển thị thẻ div success
                  $('#error_romooc').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error_romooc').fadeOut(10000);

              }
          });
          return false;
           
       }
					 
				 
			});
	
});
</script>

        <div class="login_body">
         
              <form id="edit_romooc" method="post" action="" autocomplete="off">
                  <table style="margin-top:20px;">
                    
                    <tr>
                        <td>Số mooc</td>
                        <td><input type="text" id="romooc_number" name="romooc_number" tabindex="1" required="required" value="<?php echo $romooc_data->romooc_number ?>"></td>
                    </tr>
                </table> 
            </form>
        </div>
        <div id="error_romooc" class="error"><?php echo isset($error) ? $error : null; ?></div>


