
        <div class="login_body">
         
                  <table style="margin-top:20px;">
                    
                    <tr>
                        <td>Số mooc</td>
                        <td><input type="text" id="romooc_number" name="romooc_number" tabindex="1" required="required" value="<?php echo $romooc_data->romooc_number ?>"></td>
                    </tr>
                    <tr>
                        <td>Biển số</td>
                        <td><input type="text" id="romooc_license" name="romooc_license" tabindex="2" value="<?php echo $romooc_data->romooc_license ?>"></td>
                    </tr>
                </table> 
         
        </div>
        <div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>


