<script type="text/javascript">
$(document).ready(function(){

			// Validate form
			$("#edit_bonus").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
        ignore: "",
        rules: {
        },
        errorPlacement: function (error, element) {
          if(element.is('input[type=checkbox]') || element.is('input[type=radio]')) {
            var controls = element.closest('div[class*="col-"]');
            if(controls.find(':checkbox,:radio').length > 1) controls.append(error);
            else error.insertAfter(element.nextAll('.lbl:eq(0)').eq(0));
          }
          else if(element.is('.select2')) {
            error.insertAfter(element.siblings('[class*="select2-container"]:eq(0)'));
          }
          else if(element.is('.chosen-select')) {
            error.insertAfter(element.siblings('[class*="chosen-container"]:eq(0)'));
          }
          else error.insertAfter(element.parent());
        },
        submitHandler: function(form) {
          
          var formData = new FormData($("#edit_bonus")[0]);
          formData.append('bonus_id', '<?php echo $bonus_data->bonus_id ?>');
          
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/bonus/editbonus", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: formData, // giá trị post
              cache: false,
              contentType: false,
              processData: false,
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error_bonus').hide();
                  $('#error_bonus').slideToggle(100); // hiển thị thẻ div success
                  $('#error_bonus').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error_bonus').fadeOut(10000);

              }
          });
          return false;
           
       }
					 
				 
			});
	
});
</script>

        <div class="login_body">
         
              <form id="edit_bonus" method="post" action="" autocomplete="off">
                  <table style="margin-top:20px;">
                    <tr>
                        <td>Thưởng/lit </td>
                        <td><input type="text" id="bonus_plus" name="bonus_plus" tabindex="1" autofocus class="numbers" value="<?php echo $lib->formatMoney($bonus_data->bonus_plus) ?>"></td>
                        
                    </tr>
                    <tr>
                        <td>Phạt/lit </td>
                        <td><input type="text" id="bonus_minus" name="bonus_minus" tabindex="2" class="numbers" value="<?php echo $lib->formatMoney($bonus_data->bonus_minus) ?>"></td>
                    </tr>
                    <tr>
                        <td>Ngày áp dụng </td>
                        <td><input type="text" id="bonus_start_date" name="bonus_start_date" tabindex="3" class="start-date" required="required" value="<?php echo $lib->hien_thi_ngay_thang($bonus_data->bonus_start_date) ?>"></td>
                    </tr>
                    <tr>
                        <td>Ngày hết hạn </td>
                        <td><input type="text" id="bonus_end_date" name="bonus_end_date" tabindex="4" class="end-date" value="<?php echo $lib->hien_thi_ngay_thang($bonus_data->bonus_end_date) ?>"></td>
                    </tr>
                </table> 
            </form>
        </div>
        <div id="error_bonus" class="error"><?php echo isset($error) ? $error : null; ?></div>


