<script type="text/javascript">
$(document).ready(function(){
	
			// Validate form
			$("#edit").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
				rules: {
				},
        submitHandler: function(form) {
          
          var formData = new FormData($("#edit")[0]);
          formData.append('position_id', '<?php echo $position_data->position_id ?>');
          
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/position/editposition", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: formData, // giá trị post
              cache: false,
              contentType: false,
              processData: false,
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error').hide();
                  $('#error').slideToggle(100); // hiển thị thẻ div success
                  $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error').fadeOut(10000);

              }
          });
          return false;
           
       }
					 
				 
			});
	
});
</script>

        <div class="login_body">
         
              <form id="edit" method="post" action="" autocomplete="off">
                  <table style="margin-top:20px;">
                    
                    <tr>
                        <td>Mã chức vụ</td>
                        <td><input type="text" id="position_code" name="position_code" tabindex="1" required="required" autofocus value="<?php echo $position_data->position_code ?>"></td>
                        
                    </tr>
                    <tr>
                        <td>Tên chức vụ</td>
                        <td><input type="text" id="position_name" name="position_name" tabindex="2" required="required" value="<?php echo $position_data->position_name ?>"></td>
                    </tr>
                </table> 
            </form>
        </div>
        <div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>


