<script type="text/javascript">
$(document).ready(function(){
	$( ".select2" ).select2({dropdownAutoWidth : true});
			// Validate form
			$("#add_lift").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
				rules: {
				},
        submitHandler: function(form) {
                
          var formData = new FormData($("#add_lift")[0]);
          
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/lift/addlift", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: formData, // giá trị post
              cache: false,
              contentType: false,
              processData: false,
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error_lift').hide();
                  $('#error_lift').slideToggle(100); // hiển thị thẻ div success
                  $('#error_lift').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error_lift').fadeOut(10000);

              }
          });
          return false;
           
       }
					 
				 
			});
	
});
</script>
     
<div class="login_body">
  
      <form id="add_lift" method="post" action="" autocomplete="off">
          <table style="margin-top:20px;">
            <tr>
                <td>Cảng <a title="Thêm cảng mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("port/add") ?>','Thêm cảng mới','lift_place','<?php echo $this->url("port/getport") ?>','add_port')"></i></a></td>
                <td>
                  <select class="form-control select2" id="lift_place" name="lift_place" required="required" tabindex="1">
                    <?php foreach ($places as $place) { ?>
                      <option value="<?php echo $place->place_id ?>"><?php echo $place->place_name ?></option>
                    <?php } ?>
                  </select>
                </td>
            </tr>
            <tr>
                <td>Phí nâng </td>
                <td><input type="text" id="lift_on" name="lift_on" tabindex="2" class="numbers"></td>
            </tr>
            <tr>
                <td>Phí hạ </td>
                <td><input type="text" id="lift_off" name="lift_off" tabindex="3" class="numbers"></td>
            </tr>
            <tr>
                <td>Ngày áp dụng </td>
                <td><input type="text" id="lift_start_date" name="lift_start_date" tabindex="4" class="start-date" required="required"></td>
            </tr>
            <tr>
                <td>Ngày hết hạn </td>
                <td><input type="text" id="lift_end_date" name="lift_end_date" tabindex="5" class="end-date"></td>
            </tr>
        </table> 
    </form>
</div>
<div id="error_lift" class="error"><?php echo isset($error) ? $error : null; ?></div>


