<script type="text/javascript">
$(document).ready(function(){
  $( ".select2" ).select2({dropdownAutoWidth : true});
      // Validate form
      $("#edit_lift").validate({
        errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
        rules: {
        },
        submitHandler: function(form) {
                
          var formData = new FormData($("#edit_lift")[0]);
          formData.append('lift_id', '<?php echo $lift_data->lift_id ?>');
          
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/lift/editlift", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: formData, // giá trị post
              cache: false,
              contentType: false,
              processData: false,
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error_lift').hide();
                  $('#error_lift').slideToggle(100); // hiển thị thẻ div success
                  $('#error_lift').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error_lift').fadeOut(10000);

              }
          });
          return false;
           
       }
           
         
      });
  
});
</script>
<div id="error_lift" class="error"><?php echo isset($error) ? $error : null; ?></div>     
<div class="login_body">
  
      <form id="edit_lift" method="post" action="" autocomplete="off">
        <div class="col-md-6">
          <label for="lift_place">Cảng <a title="Thêm cảng mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("port/add") ?>','Thêm cảng mới','lift_place','<?php echo $this->url("port/getport") ?>','add_port')"></i></a></label>
          <div class="input-group">
            <select class="form-control select2" id="lift_place" name="lift_place" required="required" tabindex="1">
              <?php foreach ($places as $place) { ?>
                <option value="<?php echo $place->place_id ?>" <?php echo $lift_data->lift_place==$place->place_id?'selected="selected"':null ?>><?php echo $place->place_name ?></option>
              <?php } ?>
            </select>
          </div>
          <label for="lift_unit">Đơn vị <a title="Thêm đơn vị mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("unit/add") ?>','Thêm đơn vị mới','lift_unit','<?php echo $this->url("unit/getunit") ?>','add_unit')"></i></a></label>
          <div class="input-group">
            <select class="form-control" id="lift_unit" name="lift_unit" required="required" tabindex="2">
              <?php foreach ($units as $unit) { ?>
                <option <?php echo $lift_data->lift_unit==$unit->unit_id?'selected="selected"':null ?> value="<?php echo $unit->unit_id ?>"><?php echo $unit->unit_name ?></option>
              <?php } ?>
            </select>
          </div>
          <label for="lift_on">Phí nâng</label>
          <div class="input-group">
            <input type="text" id="lift_on" name="lift_on" tabindex="3" class="numbers" value="<?php echo $lib->formatMoney($lift_data->lift_on) ?>">
          </div>
          <label for="lift_off">Phí hạ</label>
          <div class="input-group">
            <input type="text" id="lift_off" name="lift_off" tabindex="4" class="numbers" value="<?php echo $lib->formatMoney($lift_data->lift_off) ?>">
          </div>
        </div>
        <div class="col-md-6">
          <label for="lift_start_date">Ngày áp dụng</label>
          <div class="input-group">
            <input type="text" id="lift_start_date" name="lift_start_date" tabindex="5" class="start-date" required="required" value="<?php echo $lib->hien_thi_ngay_thang($lift_data->lift_start_date) ?>">
          </div>
          <label for="lift_end_date">Ngày hết hạn</label>
          <div class="input-group">
            <input type="text" id="lift_end_date" name="lift_end_date" tabindex="6" class="end-date" value="<?php echo $lib->hien_thi_ngay_thang($lift_data->lift_end_date) ?>">
          </div>
          <label for="lift_on_null">Phí nâng rỗng</label>
          <div class="input-group">
            <input type="text" id="lift_on_null" name="lift_on_null" tabindex="7" class="numbers" value="<?php echo $lib->formatMoney($lift_data->lift_on_null) ?>">
          </div>
          <label for="lift_off_null">Phí hạ rỗng</label>
          <div class="input-group">
            <input type="text" id="lift_off_null" name="lift_off_null" tabindex="8" class="numbers" value="<?php echo $lib->formatMoney($lift_data->lift_off_null) ?>">
          </div>
          <label for="lift_customer">Tên đơn vị <a title="Thêm tên đơn vị mới"><i class="ace-icon fa fa-chevron-right blue" onclick="add_click_other('<?php echo $this->url("customer/add") ?>','Thêm tên đơn vị mới','lift_customer','<?php echo $this->url("customer/getsupply") ?>','add_customer')"></i></a></label>
          <div class="input-group">
            <select class="form-control select2" id="lift_customer" name="lift_customer" tabindex="9">
              <option value="">Chọn</option>
              <?php foreach ($customers as $customer) { ?>
                <option <?php echo $lift_data->lift_customer==$customer->customer_id?'selected="selected"':null ?> value="<?php echo $customer->customer_id ?>"><?php echo $customer->customer_name ?></option>
              <?php } ?>
            </select>
          </div>
        </div>
          
    </form>
</div>

